var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),h=console.error.bind(console),p,r=!1,na,la=a=>a.startsWith("file://"),oa,u,y,pa,qa,z,A,B,C,ra;
function sa(){var a=oa.buffer;u=new Int8Array(a);pa=new Int16Array(a);y=new Uint8Array(a);qa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var D=0,E=null;function ua(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}
async function ya(a){var b=va;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},Ea=!0,Fa=0,F={},Ga=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Ea||0<Fa||(e.onExit?.(a),r=!0);fa(a,new za(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Ea||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!r)try{a(),Ja()}catch(b){Ga(b)}},Sa=(a,b)=>{La=a;Ma=b;if(G)if(Na||=!0,0==a)H=function(){setTimeout(I,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)H=function(){Pa(I)};else if(2==a){if("undefined"==
typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qa=setImmediate;H=function(){Qa(I)}}},ab=(a,b,c,d,f)=>{function g(){return k<Ta?(Ja(),!1):!0}G=a;Ua=d;var k=Ta;Na=!1;I=function(){if(!r)if(0<Va.length){var m=
Va.shift();m.mc(m.cc);if(Wa){var n=Wa,t=0==n%1?n-1:Math.floor(n);Wa=m.fc?t:(8*n+(t+.5))/9}e.setStatus&&(m=e.statusMessage||"Please wait...",n=Wa??0,t=Xa.lc??0,n?n<t?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(m):e.setStatus(""));g()&&setTimeout(I,0)}else if(g())if(Ya=Ya+1|0,1==La&&1<Ma&&0!=Ya%Ma)H();else{0==La&&(Oa=performance.now());a:if(!r){for(m of Za)if(!1===m())break a;Ka(a);for(n of $a)n()}g()&&H()}};f||(0<b?Sa(0,1E3/b):Sa(1,1),H());if(c)throw"unwind";},Na=!1,H=
null,Ta=0,G=null,Ua=0,La=0,Ma=0,Ya=0,Va=[],Za=[],$a=[];function bb(){H=null;Ta++}var K=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===K)K=b+1E3/60;else for(;b+2>=K;)K+=1E3/60;setTimeout(a,Math.max(K-b,0))}}
var Xa={},Oa,I,Qa,Wa,cb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,L=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&cb)return cb.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},
db=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?L(y,a):"":a;return db[a]||("undefined"!=typeof document?document.querySelector(a):null)},eb=a=>0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},fb=[],gb,N=a=>{var b=fb[a];b||(fb[a]=b=gb.get(a));return b};function hb(a){var b=O.hb[a];b.target.removeEventListener(b.eb,b.Rb,b.ib);O.hb.splice(a,1)}
function ib(){if(navigator.userActivation?navigator.userActivation.isActive:O.Ib&&O.ac.Fb){var a=O.sb;O.sb=[];for(var b of a)b.Mb(...b.Qb)}}function P(a){if(!a.target)return-4;if(a.jb)a.Rb=function(c){++O.Ib;O.ac=a;ib();a.qb(c);ib();--O.Ib},a.target.addEventListener(a.eb,a.Rb,a.ib),O.hb.push(a);else for(var b=0;b<O.hb.length;++b)O.hb[b].target==a.target&&O.hb[b].eb==a.eb&&hb(b--);return 0}function jb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var O={dc:0,nc:0,Jb:0,tb:0,Pb:0,Ob:0,Gb:0,kc:0,qc:0,jc:0,Hb:0,Kb:0,zc:0,Nb:0,pc(a,b,c){u.set(u.subarray(b,b+c),a)},rc(){for(;O.hb.length;)hb(O.hb.length-1);O.sb=[]},Ib:0,sb:[],ic(a,b,c){function d(g,k){if(g.length!=k.length)return!1;for(var m in g)if(g[m]!=k[m])return!1;return!0}for(var f of O.sb)if(f.Mb==a&&d(f.Qb,c))return;O.sb.push({Mb:a,Ub:b,Qb:c});O.sb.sort((g,k)=>g.Ub<k.Ub)},tc(a){O.sb=O.sb.filter(b=>b.Mb!=a)},hb:[],sc:(a,b)=>{for(var c=0;c<O.hb.length;++c)O.hb[c].target!=a||b&&b!=O.hb[c].eb||
hb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Q=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0}},kb=(a,b,c,d,f,g)=>{O.Gb||
(O.Gb=R(256));a={target:M(a),eb:g,jb:d,qb:(k=event)=>{var m=k.target.id?k.target.id:"",n=O.Gb;Q(jb(k.target),n+0,128);Q(m,n+128,128);N(d)(f,n,b)&&k.preventDefault()},ib:c};return P(a)},lb=(a,b,c,d,f)=>{O.Hb||(O.Hb=R(276));return P({target:a,eb:f,jb:d,qb:(g=event)=>{var k=O.Hb,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!m;u[k]=n;u[k+1]=O.fullscreenEnabled();var t=n?m:O.bc,v=
t?.id||"";Q(jb(t),k+2,128);Q(v,k+130,128);z[k+260>>2]=t?t.clientWidth:0;z[k+264>>2]=t?t.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;n&&(O.bc=m);N(d)(19,k,b)&&g.preventDefault()},ib:c})},mb=(a,b,c,d,f,g)=>{O.Jb||(O.Jb=R(160));a={target:M(a),eb:g,jb:d,qb:k=>{var m=O.Jb;C[m>>3]=k.timeStamp;var n=m>>2;z[n+2]=k.location;u[m+12]=k.ctrlKey;u[m+13]=k.shiftKey;u[m+14]=k.altKey;u[m+15]=k.metaKey;u[m+16]=k.repeat;z[n+5]=k.charCode;z[n+6]=k.keyCode;z[n+7]=k.which;Q(k.key||"",m+32,32);Q(k.code||
"",m+64,32);Q(k.char||"",m+96,32);Q(k.locale||"",m+128,32);N(d)(f,m,b)&&k.preventDefault()},ib:c};return P(a)},nb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=eb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},ob=(a,b,c,d,f,g)=>{O.tb||(O.tb=R(64));a=M(a);return P({target:a,
Fb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,eb:g,jb:d,qb:(k=event)=>{nb(O.tb,k,a);N(d)(f,O.tb,b)&&k.preventDefault()},ib:c})},pb=(a,b,c,d)=>{O.Kb||(O.Kb=R(257));return P({target:a,eb:"pointerlockchange",jb:d,qb:(f=event)=>{var g=O.Kb,k=document.pointerLockElement;u[g]=!!k;var m=k?.id||"";Q(jb(k),g+1,128);Q(m,g+129,128);N(d)(20,g,b)&&f.preventDefault()},ib:c})},qb=(a,b,c,d)=>P({target:a,eb:"pointerlockerror",jb:d,qb:(f=event)=>{N(d)(38,0,b)&&f.preventDefault()},ib:c}),rb=(a,b,c,d)=>{O.Ob||
(O.Ob=R(36));a=M(a);return P({target:a,eb:"resize",jb:d,qb:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=O.Ob;z[k>>2]=0;z[k+4>>2]=g.clientWidth;z[k+8>>2]=g.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;N(d)(10,k,b)&&f.preventDefault()}}},ib:c})},sb=(a,b,c,d,f,g)=>{O.Nb||(O.Nb=R(1552));a=M(a);return P({target:a,Fb:"touchstart"==g||"touchend"==g,eb:g,jb:d,qb:k=>{var m={},n=k.touches;
for(var t of n)t.Sb=t.Tb=0,m[t.identifier]=t;for(var v of k.changedTouches)v.Sb=1,m[v.identifier]=v;for(var l of k.targetTouches)m[l.identifier].Tb=1;n=O.Nb;C[n>>3]=k.timeStamp;u[n+12]=k.ctrlKey;u[n+13]=k.shiftKey;u[n+14]=k.altKey;u[n+15]=k.metaKey;t=n+16;v=eb(a);l=0;for(let q of Object.values(m))if(m=t>>2,z[m]=q.identifier,z[m+1]=q.screenX,z[m+2]=q.screenY,z[m+3]=q.clientX,z[m+4]=q.clientY,z[m+5]=q.pageX,z[m+6]=q.pageY,u[t+28]=q.Sb,u[t+29]=q.Tb,z[m+8]=q.clientX-(v.left|0),z[m+9]=q.clientY-(v.top|
0),t+=48,31<++l)break;z[n+8>>2]=l;N(d)(f,n,b)&&k.preventDefault()},ib:c})},tb=(a,b,c,d)=>{O.Pb||(O.Pb=R(96));return P({target:a,Fb:!0,eb:"wheel",jb:d,qb:(f=event)=>{var g=O.Pb;nb(g,f,a);C[g+64>>3]=f.deltaX;C[g+72>>3]=f.deltaY;C[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;N(d)(9,g,b)&&f.preventDefault()},ib:c})},S=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=ub(b);Q(a,c,b);return c},vb=[],T=(a,b)=>{vb[a>>>=0]=b},wb=[],U=a=>
{if(a)return vb[a>>>0]},xb=a=>{var b=A[a>>2];return b?L(y,b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?L(y,b,a):"";if(0===a)return""},yb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),zb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Ab=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,g=xb(f+4);c[g]=C[f+16>>3]}return c}},Bb=a=>a?U(a):"auto",Ob=a=>{function b(d){if(d)return{operation:Cb[A[d>>2]],srcFactor:Db[A[d+4>>2]],dstFactor:Db[A[d+8>>2]]}}function c(d){return{compare:Eb[A[d>>
2]],failOp:Hb[A[d+4>>2]],depthFailOp:Hb[A[d+8>>2]],passOp:Hb[A[d+12>>2]]}}return{label:V(a+4),layout:Bb(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),g=Ab(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var m=A[d+28>>2];if(k){for(var n=[],t=0;t<k;++t){var v=n,l=v.push;var q=m+24*t;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var J=null;else{J=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Ib[w];q=A[q+20>>2];for(var Fb=[],Ra=0;Ra<x;++Ra){var Gb=Fb,sc=Gb.push,ta=q+24*Ra;sc.call(Gb,{format:Jb[A[ta+4>>2]],
offset:4294967296*A[ta+4+8>>2]+A[ta+8>>2],shaderLocation:A[ta+16>>2]})}J={arrayStride:J,stepMode:w,attributes:Fb}}}else J=void 0;l.call(v,J)}k=n}else k=void 0;return{module:f,constants:g,buffers:k,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Kb[A[d+4>>2]],stripIndexFormat:Lb[A[d+8>>2]],frontFace:Mb[A[d+12>>2]],cullMode:Nb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Eb[A[d+
12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),g=Ab(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],m=A[d+28>>2],n=[],t=0;t<k;++t){var v=n,l=v.push,q=m+24*t,w=A[q+4>>2];if(0===w)q=void 0;else{w=W[w];var x=
(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}l.call(v,q)}return{module:f,constants:g,targets:n,entryPoint:V(d+8)}}}(A[a+92>>2])}},Pb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",
36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",
108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.oc&&c("maxImmediateSize",148)},Qb=[,"clamp-to-edge","repeat","mirror-repeat"],Db=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha",
"dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Cb=[,"add","subtract","reverse-subtract","min","max"],Rb=["binding-not-used",,"uniform","storage","read-only-storage"],Eb=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Sb=[,"opaque","premultiplied","unpremultiplied","inherit"],Nb=[,"none","front","back"],Tb=[,"compatibility","core"],Ub={1:"core-features-and-limits",
2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",
327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Vb=[,"nearest","linear"],Mb=[,"ccw","cw"],Lb=[,"uint16","uint32"],Wb=[,"load","clear"],Xb=[,"nearest","linear"],Yb=[,"low-power","high-performance"],Zb=[,"srgb","display-p3"],Kb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],$b=["binding-not-used",,"filtering","non-filtering","comparison"],Hb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap",
"decrement-wrap"],ac=["binding-not-used",,"write-only","read-only","read-write"],bc=[,"store","discard"],cc=[,"all","stencil-only","depth-only"],dc=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint",
"rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm",
"bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb",
"astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],ec=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],fc=[,"1d","2d","2d-array","cube","cube-array","3d"],gc=[,"standard","extended"],Jb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4",
"snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Ib=[,"vertex","instance"],hc={undefined:1,unknown:1,destroyed:2},ic=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";ic.Lb||
(ic.Lb={});ic.Lb[a]||(ic.Lb[a]=1,ca&&(a="warning: "+a),h(a))},jc={rgba8unorm:22,bgra8unorm:27},kc=[null,[],[]],lc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Pa;e.pauseMainLoop=bb;e.resumeMainLoop=function(){Ta++;var a=La,b=Ma,c=G;G=null;ab(c,0,!1,Ua,!0);Sa(a,b);H()};e.preMainLoop&&Za.push(e.preMainLoop);e.postMainLoop&&$a.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(h=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);
e.thisProgram&&(ea=e.thisProgram);
var R,mc,nc,oc,pc,qc,rc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Y,ub,X,Mc={U:()=>ua(""),O:()=>{Ea=!1;Fa=0},P:(a,b)=>{F[a]&&(clearTimeout(F[a].id),delete F[a]);if(!b)return 0;var c=setTimeout(()=>{delete F[a];Ka(()=>Kc(a,performance.now()))},b);F[a]={id:c,xc:b};return 0},xa:()=>{bb();G=null},I:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,K:(a,b,c)=>{a=M(a);if(!a)return-4;a=eb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},ya:()=>performance.now(),Ea:(a,b)=>{function c(d){N(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Q:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},q:(a,b,c,d)=>kb(a,b,c,d,12,"blur"),H:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},r:(a,b,c,d)=>kb(a,b,c,d,13,"focus"),p:(a,
b,c,d)=>{if(!O.fullscreenEnabled())return-1;a=M(a);if(!a)return-4;lb(a,b,c,d,"webkitfullscreenchange");return lb(a,b,c,d,"fullscreenchange")},A:(a,b,c,d)=>mb(a,b,c,d,2,"keydown"),y:(a,b,c,d)=>mb(a,b,c,d,1,"keypress"),z:(a,b,c,d)=>mb(a,b,c,d,3,"keyup"),Fa:(a,b,c)=>{a=N(a);ab(a,b,c)},G:(a,b,c,d)=>ob(a,b,c,d,5,"mousedown"),D:(a,b,c,d)=>ob(a,b,c,d,33,"mouseenter"),C:(a,b,c,d)=>ob(a,b,c,d,34,"mouseleave"),E:(a,b,c,d)=>ob(a,b,c,d,8,"mousemove"),F:(a,b,c,d)=>ob(a,b,c,d,6,"mouseup"),t:(a,b,c,d)=>document.body?.requestPointerLock?
(a=M(a))?pb(a,b,c,d):-4:-1,s:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?qb(a,b,c,d):-4:-1,J:(a,b,c,d)=>rb(a,b,c,d),u:(a,b,c,d)=>sb(a,b,c,d,25,"touchcancel"),v:(a,b,c,d)=>sb(a,b,c,d,23,"touchend"),w:(a,b,c,d)=>sb(a,b,c,d,24,"touchmove"),x:(a,b,c,d)=>sb(a,b,c,d,22,"touchstart"),B:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?tb(a,b,c,d):-1:-4,Z:function(a,b,c,d,f,g){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);
var k={};if(g){var m=A[g+12>>2];if(m){var n=A[g+16>>2];k.requiredFeatures=Array.from(A.subarray(n>>2,n+4*m>>2),l=>Ub[l])}var t=A[g+20>>2];if(t){var v={};function l(w,x,J=!1){x=A[t+x>>2];4294967295==x||J&&0==x||(v[w]=x)}function q(w,x){x=t+x;var J=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=J)v[w]=4294967296*A[x+4>>2]+A[x>>2]}l("maxTextureDimension1D",4);l("maxTextureDimension2D",8);l("maxTextureDimension3D",12);l("maxTextureArrayLayers",16);l("maxBindGroups",20);l("maxBindGroupsPlusVertexBuffers",
24);l("maxDynamicUniformBuffersPerPipelineLayout",32);l("maxDynamicStorageBuffersPerPipelineLayout",36);l("maxSampledTexturesPerShaderStage",40);l("maxSamplersPerShaderStage",44);l("maxStorageBuffersPerShaderStage",48);l("maxStorageTexturesPerShaderStage",52);l("maxUniformBuffersPerShaderStage",56);l("minUniformBufferOffsetAlignment",80);l("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);l("maxVertexBuffers",88);q("maxBufferSize",96);l("maxVertexAttributes",
104);l("maxVertexBufferArrayStride",108);l("maxInterStageShaderVariables",112);l("maxColorAttachments",116);l("maxColorAttachmentBytesPerSample",120);l("maxComputeWorkgroupStorageSize",124);l("maxComputeInvocationsPerWorkgroup",128);l("maxComputeWorkgroupSizeX",132);l("maxComputeWorkgroupSizeY",136);l("maxComputeWorkgroupSizeZ",140);l("maxComputeWorkgroupsPerDimension",144);l("maxImmediateSize",148,!0);k.requiredLimits=v}if(m=A[g+24>>2])m={label:V(m+4)},k.defaultQueue=m;k.label=V(g+4)}a.requestDevice(k).then(l=>
{T(f,l.queue);T(d,l);c&&l.lost.then(q=>{l.onuncapturederror=()=>{};var w=X(),x=S(q.message);Gc(c,hc[q.reason],x);Y(w)});l.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=X();q=S(q.error.message);Jc(d,w,q);Y(x)};Ic(b,1,d,0)},l=>{var q=X();l=S(l.message);Ic(b,3,d,l);c&&Gc(c,4,l);Y(q)})},aa:(a,b,c)=>{var d=U(a);0===c&&ic();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(k){return 0}var g=
Lc(16,f.byteLength);y.fill(0,g,f.byteLength);wb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(g,g+f.byteLength));mc(g)});return g},$:a=>{var b=U(a),c=wb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete wb[a];b.unmap()}},a:a=>{delete vb[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(g){return!1}T(c,f);d&&(wb[c]=[]);return!0},Y:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+
4),code:""};switch(f){case 2:b.code=xb(d+8)}T(c,U(a).createShaderModule(b))},_:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},V:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return jc[a]},W:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Tb[A[c+4>>2]],powerPreference:Yb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Ac=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(g=>{if(g)T(d,g),Hc(b,1,d,0);else{g=
X();var k=S("WebGPU not available on this browser (requestAdapter returned null)");Hc(b,3,d,k);Y(g)}},g=>{var k=X();g=S(g.message);Hc(b,4,d,g);Y(k)}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Hc(b,3,d,a),Y(f))},T:()=>52,R:function(){return 70},S:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var k=A[b>>2],m=A[b+4>>2];b+=8;for(var n=0;n<m;n++){var t=a,v=y[k+n],l=kc[t];0===v||10===v?((1===t?ma:h)(L(l)),l.length=0):l.push(v)}f+=m}A[d>>2]=f;return 0},N:Ha,Ja:function(){e.Vb=
a=>{0!=oc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Vb)},Ca:function(){e.$b=a=>{const b=a.clipboardData.getData("text");lc(()=>{const c=S(b);nc(c)})};window.addEventListener("paste",e.$b)},za:function(){e.uc=[];e.Wb=b=>{b.stopPropagation();b.preventDefault()};e.Xb=b=>{b.stopPropagation();b.preventDefault()};e.Yb=b=>{b.stopPropagation();b.preventDefault()};e.Zb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.vc=c;pc(c.length);for(let f=
0;f<c.length;f++)lc(()=>{const g=S(c[f].name);qc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);rc(b.clientX,b.clientY,d)};const a=e.rb;a.addEventListener("dragenter",e.Wb,!1);a.addEventListener("dragleave",e.Xb,!1);a.addEventListener("dragover",e.Yb,!1);a.addEventListener("drop",e.Zb,!1)},Ha:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},M:function(a){e.ub&&(URL.revokeObjectURL(e.ub[a].ec),e.ub[a]=null)},la:function(a,
b){0!==b&&(document.title=b?L(y,b):"");a=a?L(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?db[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.rb=M(a);e.rb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.rb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ia:function(){window.removeEventListener("beforeunload",e.Vb)},Aa:function(){window.removeEventListener("paste",e.$b)},ua:function(){const a=
e.rb;a.removeEventListener("dragenter",e.Wb);a.removeEventListener("dragleave",e.Xb);a.removeEventListener("dragover",e.Yb);a.removeEventListener("drop",e.Zb)},i:function(){e.rb&&e.rb.requestPointerLock&&e.rb.requestPointerLock()},X:function(a,b,c){if(e.rb){if(0===b)a="none";else if(0!=c)a=e.ub[a].hc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a=
"nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.rb.style.cursor=a}},Ga:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(y.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},L:function(a,b){b=b?L(y,b):"";switch(a){case 0:console.error(b);
break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},e:(a,b)=>U(a).features.has(Ub[b]),oa:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],k=[],m=0;m<f;++m){var n=k,t=n.push;var v=g+56*m;var l=A[v+4>>2];if(0!==l){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:U(l),depthSlice:q,resolveTarget:U(A[v+12>>2]),clearValue:yb(v+24),loadOp:Wb[A[v+16>>2]],storeOp:bc[A[v+20>>2]]}}else v=void 0;t.call(n,v)}f=
A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Wb[A[f+8>>2]],depthStoreOp:bc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Wb[A[f+24>>2]],stencilStoreOp:bc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;g=A[b+28>>2];g=0!==g?{querySet:U(A[g+4>>2]),beginningOfPassWriteIndex:A[g+8>>2],endOfPassWriteIndex:A[g+12>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:g,maxDrawCount:d};
a=U(a);d=Ac(0);T(d,a.beginRenderPass(b));return d},ca:a=>{a=U(a);var b=wc(0);T(b,a.finish());return b},da:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ka:(a,b)=>{U(a).setPipeline(U(b))},j:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var g=[],k=0;k<f;++k){var m=g,n=m.push;var t=b+40*k;var v=A[t+8>>2],l=A[t+32>>2],q=A[t+36>>2],w=A[t+4>>2];v?(l=t+24,l=A[l>>2]+4294967296*z[l+4>>2],-1==l&&(l=void 0),t={binding:w,resource:{buffer:U(v),
offset:4294967296*A[t+4+16>>2]+A[t+16>>2],size:l}}):t=l?{binding:w,resource:U(l)}:{binding:w,resource:U(q)};n.call(m,t)}c={label:c,layout:d,entries:g};a=U(a);d=uc(0);T(d,a.createBindGroup(c));return d},k:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],g=0;g<d;++g){var k=f,m=k.push,n=b+88*g,t=A[n+4>>2],v=A[n+8>>2];var l=n+24;var q=A[l+4>>2];l=q?{type:Rb[q],hasDynamicOffset:!!A[l+8>>2],minBindingSize:4294967296*A[l+4+16>>2]+A[l+16>>2]}:void 0;q=(q=A[n+48+4>>2])?{type:$b[q]}:void 0;var w=
n+56;var x=A[w+4>>2];w=x?{sampleType:ec[x],viewDimension:fc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;n+=72;n=(x=A[n+4>>2])?{access:ac[x],format:W[A[n+8>>2]],viewDimension:fc[A[n+12>>2]]}:void 0;m.call(k,{binding:t,visibility:v,buffer:l,sampler:q,texture:w,storageTexture:n})}c={label:c,entries:f};a=U(a);d=vc(0);T(d,a.createBindGroupLayout(c));return d},o:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=xc(0);T(b,a.createCommandEncoder(c));return b},qa:(a,b)=>{var c=V(b+4);var d=Bb(A[b+12>>2]);b=(b+=
16)?{module:U(A[b+4>>2]),constants:Ab(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=yc(0);T(d,a.createComputePipeline(c));return d},ra:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],g=0;g<c;++g)f.push(U(A[d+4*g>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=zc(0);T(c,a.createPipelineLayout(b));return c},pa:(a,b)=>{b=Ob(b);a=U(a);var c=Bc(0);T(c,a.createRenderPipeline(b));return c},sa:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Qb[A[b+12>>2]],addressModeV:Qb[A[b+
16>>2]],addressModeW:Qb[A[b+20>>2]],magFilter:Vb[A[b+24>>2]],minFilter:Vb[A[b+28>>2]],mipmapFilter:Xb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Eb[A[b+44>>2]],maxAnisotropy:qa[b+48>>1]});a=U(a);b=Cc(0);T(b,a.createSampler(c));return b},l:(a,b)=>{var c={label:V(b+4),size:zb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:dc[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));
a=U(a);d=Ec(0);T(d,a.createTexture(c));return d},va:(a,b)=>{Pb(U(a).limits,b);return 1},d:(a,b)=>U(a).features.has(Ub[b]),Da:(a,b)=>{a=M(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.wc=V(b+4);b=Dc(0);T(b,a);return b},ba:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},h:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},ta:(a,b,c,d,f,g)=>{var k=A[f+8>>2],m=A[f+12>>2],n=b+8;U(a).writeTexture({texture:U(A[b>>
2]),mipLevel:A[b+4>>2],origin:{x:A[n>>2],y:A[n+4>>2],z:A[n+8>>2]},aspect:cc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===k?void 0:k,rowsPerImage:4294967295===m?void 0:m},zb(g))},m:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},n:(a,b,c,d,f,g)=>{U(a).drawIndexed(b,c,d>>>0,f,g>>>0)},ea:a=>{U(a).end()},b:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ia:(a,b)=>{U(a).setBlendConstant(yb(b))},ga:function(a,b,c,d,f){d=-9007199254740992>
d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Lb[c],d,f)},ja:(a,b)=>{U(a).setPipeline(U(b))},ma:(a,b,c,d,f)=>{U(a).setScissorRect(b,c,d,f)},ha:(a,b)=>{U(a).setStencilReference(b>>>0)},fa:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},na:(a,b,c,d,f,g,k)=>{U(a).setViewport(b,
c,d,f,g,k)},Ba:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Sb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),g=>W[g])}b=A[b>>2];0!==b&&(c.colorSpace=Zb[A[b+8>>2]],c.yc={mode:gc[A[b+12>>2]]});a.configure(c)},wa:(a,b)=>{a=U(a);try{var c=Ec(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>
2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:fc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:cc[A[b+36>>2]]}}a=U(a);b=Fc(0);T(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Ka;sa();gb=Z.zb;c=Z;R=c.Ma;mc=c.Na;e.__sapp_emsc_onpaste=nc=c.Oa;e.__sapp_html5_get_ask_leave_site=oc=c.Pa;e.__sapp_emsc_begin_drop=pc=c.Qa;e.__sapp_emsc_drop=qc=c.Ra;e.__sapp_emsc_end_drop=rc=c.Sa;e.__sapp_emsc_invoke_fetch_cb=c.Ta;e.__sapp_emsc_set_fullscreen_flag=c.Ua;e._main=tc=c.Va;e.__saudio_emsc_pull=c.Wa;e.__sfetch_emsc_head_response=c.Xa;e.__sfetch_emsc_get_response=c.Ya;e.__sfetch_emsc_failed_http_status=c.Za;e.__sfetch_emsc_failed_buffer_too_small=
c._a;e.__sfetch_emsc_failed_other=c.$a;uc=c.ab;vc=c.bb;wc=c.cb;xc=c.db;yc=c.fb;zc=c.gb;Ac=c.kb;Bc=c.lb;Cc=c.mb;Dc=c.nb;Ec=c.ob;Fc=c.pb;Gc=c.vb;Hc=c.wb;Ic=c.xb;Jc=c.yb;Kc=c.Ab;Lc=c.Bb;Y=c.Cb;ub=c.Db;X=c.Eb;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Mc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});va??=e.locateFile?e.locateFile("basisu-sapp.wasm",ia):ia+"basisu-sapp.wasm";return a((await ya(b)).instance)})();
function Nc(a=[]){var b=tc;a.unshift(ea);var c=a.length,d=ub(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=S(k);f+=4});A[f>>2]=0;try{var g=b(c,d);Ia(g)}catch(k){Ga(k)}}
function Oc(a=da){function b(){e.calledRun=!0;if(!r){Z.La();e.onRuntimeInitialized?.();e.noInitialRun||Nc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Oc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Oc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Oc();
