var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),h=console.error.bind(console),p,r=!1,na,la=a=>a.startsWith("file://"),oa,u,y,pa,qa,z,A,B,C,ra;
function sa(){var a=oa.buffer;u=new Int8Array(a);pa=new Int16Array(a);y=new Uint8Array(a);qa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=va;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},D=0,E=null,Ea=!0,Fa=0,F={},Ga=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Ea||0<Fa||(e.onExit?.(a),r=!0);fa(a,new za(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Ea||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!r)try{a(),Ja()}catch(b){Ga(b)}},Ra=(a,b)=>{La=a;Ma=b;if(G)if(Na||=!0,0==a)H=function(){setTimeout(I,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)H=function(){Pa(I)};else if(2==
a){if("undefined"==typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qa=setImmediate;H=function(){Qa(I)}}},ab=(a,b,c,d,f)=>{function g(){return k<Ta?(Ja(),!1):!0}G=a;Ua=d;var k=Ta;Na=!1;I=function(){if(!r)if(0<
Va.length){var l=Va.shift();l.pc(l.fc);if(Wa){var m=Wa,t=0==m%1?m-1:Math.floor(m);Wa=l.jc?t:(8*m+(t+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",m=Wa??0,t=Xa.oc??0,m?m<t?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));g()&&setTimeout(I,0)}else if(g())if(Ya=Ya+1|0,1==La&&1<Ma&&0!=Ya%Ma)H();else{0==La&&(Oa=performance.now());a:if(!r){for(l of Za)if(!1===l())break a;Ka(a);for(m of $a)m()}g()&&H()}};f||(0<b?Ra(0,1E3/b):Ra(1,1),H());if(c)throw"unwind";
},Na=!1,H=null,Ta=0,G=null,Ua=0,La=0,Ma=0,Ya=0,Va=[],Za=[],$a=[];function bb(){H=null;Ta++}var J=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===J)J=b+1E3/60;else for(;b+2>=J;)J+=1E3/60;setTimeout(a,Math.max(J-b,0))}}
var Xa={},Oa,I,Qa,Wa,cb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,L=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&cb)return cb.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},
db=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?L(y,a):"":a;return db[a]||("undefined"!=typeof document?document.querySelector(a):null)},eb=a=>0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},fb=[],gb,N=a=>{var b=fb[a];b||(fb[a]=b=gb.get(a));return b};function hb(a){var b=O.kb[a];b.target.removeEventListener(b.jb,b.Ub,b.lb);O.kb.splice(a,1)}
function ib(){if(navigator.userActivation?navigator.userActivation.isActive:O.Lb&&O.dc.Ib){var a=O.vb;O.vb=[];for(var b of a)b.Pb(...b.Tb)}}function P(a){if(!a.target)return-4;if(a.sb)a.Ub=function(c){++O.Lb;O.dc=a;ib();a.tb(c);ib();--O.Lb},a.target.addEventListener(a.jb,a.Ub,a.lb),O.kb.push(a);else for(var b=0;b<O.kb.length;++b)O.kb[b].target==a.target&&O.kb[b].jb==a.jb&&hb(b--);return 0}function jb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var O={hc:0,qc:0,Mb:0,wb:0,Sb:0,Rb:0,Jb:0,nc:0,tc:0,mc:0,Kb:0,Nb:0,Cc:0,Qb:0,sc(a,b,c){u.set(u.subarray(b,b+c),a)},uc(){for(;O.kb.length;)hb(O.kb.length-1);O.vb=[]},Lb:0,vb:[],lc(a,b,c){function d(g,k){if(g.length!=k.length)return!1;for(var l in g)if(g[l]!=k[l])return!1;return!0}for(var f of O.vb)if(f.Pb==a&&d(f.Tb,c))return;O.vb.push({Pb:a,Xb:b,Tb:c});O.vb.sort((g,k)=>g.Xb<k.Xb)},wc(a){O.vb=O.vb.filter(b=>b.Pb!=a)},kb:[],vc:(a,b)=>{for(var c=0;c<O.kb.length;++c)O.kb[c].target!=a||b&&b!=O.kb[c].jb||
hb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Q=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0}},kb=(a,b,c,d,f,g)=>{O.Jb||
(O.Jb=R(256));a={target:M(a),jb:g,sb:d,tb:(k=event)=>{var l=k.target.id?k.target.id:"",m=O.Jb;Q(jb(k.target),m+0,128);Q(l,m+128,128);N(d)(f,m,b)&&k.preventDefault()},lb:c};return P(a)},lb=(a,b,c,d,f)=>{O.Kb||(O.Kb=R(276));return P({target:a,jb:f,sb:d,tb:(g=event)=>{var k=O.Kb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,m=!!l;u[k]=m;u[k+1]=O.fullscreenEnabled();var t=m?l:O.ec,v=
t?.id||"";Q(jb(t),k+2,128);Q(v,k+130,128);z[k+260>>2]=t?t.clientWidth:0;z[k+264>>2]=t?t.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;m&&(O.ec=l);N(d)(19,k,b)&&g.preventDefault()},lb:c})},mb=(a,b,c,d,f,g)=>{O.Mb||(O.Mb=R(160));a={target:M(a),jb:g,sb:d,tb:k=>{var l=O.Mb;C[l>>3]=k.timeStamp;var m=l>>2;z[m+2]=k.location;u[l+12]=k.ctrlKey;u[l+13]=k.shiftKey;u[l+14]=k.altKey;u[l+15]=k.metaKey;u[l+16]=k.repeat;z[m+5]=k.charCode;z[m+6]=k.keyCode;z[m+7]=k.which;Q(k.key||"",l+32,32);Q(k.code||
"",l+64,32);Q(k.char||"",l+96,32);Q(k.locale||"",l+128,32);N(d)(f,l,b)&&k.preventDefault()},lb:c};return P(a)},nb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=eb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},ob=(a,b,c,d,f,g)=>{O.wb||(O.wb=R(64));a=M(a);return P({target:a,
Ib:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,jb:g,sb:d,tb:(k=event)=>{nb(O.wb,k,a);N(d)(f,O.wb,b)&&k.preventDefault()},lb:c})},pb=(a,b,c,d)=>{O.Nb||(O.Nb=R(257));return P({target:a,jb:"pointerlockchange",sb:d,tb:(f=event)=>{var g=O.Nb,k=document.pointerLockElement;u[g]=!!k;var l=k?.id||"";Q(jb(k),g+1,128);Q(l,g+129,128);N(d)(20,g,b)&&f.preventDefault()},lb:c})},qb=(a,b,c,d)=>P({target:a,jb:"pointerlockerror",sb:d,tb:(f=event)=>{N(d)(38,0,b)&&f.preventDefault()},lb:c}),rb=(a,b,c,d)=>{O.Rb||
(O.Rb=R(36));a=M(a);return P({target:a,jb:"resize",sb:d,tb:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=O.Rb;z[k>>2]=0;z[k+4>>2]=g.clientWidth;z[k+8>>2]=g.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;N(d)(10,k,b)&&f.preventDefault()}}},lb:c})},sb=(a,b,c,d,f,g)=>{O.Qb||(O.Qb=R(1552));a=M(a);return P({target:a,Ib:"touchstart"==g||"touchend"==g,jb:g,sb:d,tb:k=>{var l={},m=k.touches;
for(var t of m)t.Vb=t.Wb=0,l[t.identifier]=t;for(var v of k.changedTouches)v.Vb=1,l[v.identifier]=v;for(var n of k.targetTouches)l[n.identifier].Wb=1;m=O.Qb;C[m>>3]=k.timeStamp;u[m+12]=k.ctrlKey;u[m+13]=k.shiftKey;u[m+14]=k.altKey;u[m+15]=k.metaKey;t=m+16;v=eb(a);n=0;for(let q of Object.values(l))if(l=t>>2,z[l]=q.identifier,z[l+1]=q.screenX,z[l+2]=q.screenY,z[l+3]=q.clientX,z[l+4]=q.clientY,z[l+5]=q.pageX,z[l+6]=q.pageY,u[t+28]=q.Vb,u[t+29]=q.Wb,z[l+8]=q.clientX-(v.left|0),z[l+9]=q.clientY-(v.top|
0),t+=48,31<++n)break;z[m+8>>2]=n;N(d)(f,m,b)&&k.preventDefault()},lb:c})},tb=(a,b,c,d)=>{O.Sb||(O.Sb=R(96));return P({target:a,Ib:!0,jb:"wheel",sb:d,tb:(f=event)=>{var g=O.Sb;nb(g,f,a);C[g+64>>3]=f.deltaX;C[g+72>>3]=f.deltaY;C[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;N(d)(9,g,b)&&f.preventDefault()},lb:c})},S=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=ub(b);Q(a,c,b);return c},vb=[],T=(a,b)=>{vb[a>>>=0]=b},wb=[],U=a=>
{if(a)return vb[a>>>0]},xb=a=>{var b=A[a>>2];return b?L(y,b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?L(y,b,a):"";if(0===a)return""},yb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),zb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Ab=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},Bb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,g=xb(f+4);c[g]=C[f+16>>3]}return c}},Cb=a=>a?U(a):"auto",
Pb=a=>{function b(d){if(d)return{operation:Db[A[d>>2]],srcFactor:Eb[A[d+4>>2]],dstFactor:Eb[A[d+8>>2]]}}function c(d){return{compare:Fb[A[d>>2]],failOp:Gb[A[d+4>>2]],depthFailOp:Gb[A[d+8>>2]],passOp:Gb[A[d+12>>2]]}}return{label:V(a+4),layout:Cb(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),g=Bb(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var l=A[d+28>>2];if(k){for(var m=[],t=0;t<k;++t){var v=m,n=v.push;var q=l+24*t;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var K=null;else{K=4294967296*
A[q+4+8>>2]+A[q+8>>2];w=Hb[w];q=A[q+20>>2];for(var Ib=[],Sa=0;Sa<x;++Sa){var Jb=Ib,zc=Jb.push,ua=q+24*Sa;zc.call(Jb,{format:Kb[A[ua+4>>2]],offset:4294967296*A[ua+4+8>>2]+A[ua+8>>2],shaderLocation:A[ua+16>>2]})}K={arrayStride:K,stepMode:w,attributes:Ib}}}else K=void 0;n.call(v,K)}k=m}else k=void 0;return{module:f,constants:g,buffers:k,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Lb[A[d+4>>2]],stripIndexFormat:Mb[A[d+8>>2]],frontFace:Nb[A[d+12>>2]],cullMode:Ob[A[d+16>>2]],unclippedDepth:!!A[d+
20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Fb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),g=Bb(A[d+16>>2],A[d+20>>
2]),k=A[d+24>>2],l=A[d+28>>2],m=[],t=0;t<k;++t){var v=m,n=v.push,q=l+24*t,w=A[q+4>>2];if(0===w)q=void 0;else{w=W[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}n.call(v,q)}return{module:f,constants:g,targets:m,entryPoint:V(d+8)}}}(A[a+92>>2])}},Qb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",
24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);
c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.rc&&c("maxImmediateSize",148)},
Rb=[,"clamp-to-edge","repeat","mirror-repeat"],Eb=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Db=[,"add","subtract","reverse-subtract","min","max"],Sb=["binding-not-used",,"uniform","storage","read-only-storage"],Fb=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Tb=
[,"opaque","premultiplied","unpremultiplied","inherit"],Ob=[,"none","front","back"],Ub=[,"compatibility","core"],Vb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",
16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Wb=[,"nearest","linear"],Nb=[,"ccw","cw"],Mb=[,"uint16","uint32"],Xb=[,"load","clear"],Yb=[,"nearest","linear"],Zb=[,"low-power","high-performance"],$b=[,"srgb","display-p3"],Lb=[,"point-list","line-list","line-strip","triangle-list",
"triangle-strip"],ac=["binding-not-used",,"filtering","non-filtering","comparison"],Gb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],bc=["binding-not-used",,"write-only","read-only","read-write"],cc=[,"store","discard"],dc=[,"all","stencil-only","depth-only"],ec=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint",
"rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm",
"bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm",
"astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],fc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],
gc=[,"1d","2d","2d-array","cube","cube-array","3d"],hc=[,"standard","extended"],Kb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2",
"unorm8x4-bgra"],Hb=[,"vertex","instance"],ic={undefined:1,unknown:1,destroyed:2},jc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";jc.Ob||(jc.Ob={});jc.Ob[a]||(jc.Ob[a]=1,ca&&(a="warning: "+a),h(a))},kc={rgba8unorm:22,bgra8unorm:27},lc=[null,[],[]],mc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Pa;e.pauseMainLoop=bb;e.resumeMainLoop=function(){Ta++;var a=La,b=Ma,c=G;G=null;ab(c,0,!1,Ua,!0);Ra(a,b);H()};e.preMainLoop&&Za.push(e.preMainLoop);e.postMainLoop&&$a.push(e.postMainLoop);
e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(h=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var R,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Y,ub,X,Tc={V:()=>ta(""),O:()=>{Ea=!1;Fa=0},Q:(a,b)=>{F[a]&&(clearTimeout(F[a].id),delete F[a]);if(!b)return 0;var c=setTimeout(()=>{delete F[a];Ka(()=>Rc(a,performance.now()))},b);F[a]={id:c,Ac:b};return 0},ya:()=>{bb();G=null},I:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,K:(a,b,c)=>{a=M(a);if(!a)return-4;a=eb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},za:()=>performance.now(),Ea:(a,
b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},R:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},q:(a,b,c,d)=>kb(a,b,c,d,12,"blur"),H:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},r:(a,b,c,d)=>kb(a,
b,c,d,13,"focus"),p:(a,b,c,d)=>{if(!O.fullscreenEnabled())return-1;a=M(a);if(!a)return-4;lb(a,b,c,d,"webkitfullscreenchange");return lb(a,b,c,d,"fullscreenchange")},A:(a,b,c,d)=>mb(a,b,c,d,2,"keydown"),y:(a,b,c,d)=>mb(a,b,c,d,1,"keypress"),z:(a,b,c,d)=>mb(a,b,c,d,3,"keyup"),Fa:(a,b,c)=>{a=N(a);ab(a,b,c)},G:(a,b,c,d)=>ob(a,b,c,d,5,"mousedown"),D:(a,b,c,d)=>ob(a,b,c,d,33,"mouseenter"),C:(a,b,c,d)=>ob(a,b,c,d,34,"mouseleave"),E:(a,b,c,d)=>ob(a,b,c,d,8,"mousemove"),F:(a,b,c,d)=>ob(a,b,c,d,6,"mouseup"),
t:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?pb(a,b,c,d):-4:-1,s:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?qb(a,b,c,d):-4:-1,J:(a,b,c,d)=>rb(a,b,c,d),u:(a,b,c,d)=>sb(a,b,c,d,25,"touchcancel"),v:(a,b,c,d)=>sb(a,b,c,d,23,"touchend"),w:(a,b,c,d)=>sb(a,b,c,d,24,"touchmove"),x:(a,b,c,d)=>sb(a,b,c,d,22,"touchstart"),B:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?tb(a,b,c,d):-1:-4,_:function(a,b,c,d,f,g){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>
c||9007199254740992<c?NaN:Number(c);a=U(a);var k={};if(g){var l=A[g+12>>2];if(l){var m=A[g+16>>2];k.requiredFeatures=Array.from(A.subarray(m>>2,m+4*l>>2),n=>Vb[n])}var t=A[g+20>>2];if(t){var v={};function n(w,x,K=!1){x=A[t+x>>2];4294967295==x||K&&0==x||(v[w]=x)}function q(w,x){x=t+x;var K=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=K)v[w]=4294967296*A[x+4>>2]+A[x>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",8);n("maxTextureDimension3D",12);n("maxTextureArrayLayers",16);n("maxBindGroups",
20);n("maxBindGroupsPlusVertexBuffers",24);n("maxDynamicUniformBuffersPerPipelineLayout",32);n("maxDynamicStorageBuffersPerPipelineLayout",36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);n("maxVertexBuffers",
88);q("maxBufferSize",96);n("maxVertexAttributes",104);n("maxVertexBufferArrayStride",108);n("maxInterStageShaderVariables",112);n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",148,!0);k.requiredLimits=v}if(l=A[g+24>>2])l={label:V(l+
4)},k.defaultQueue=l;k.label=V(g+4)}a.requestDevice(k).then(n=>{T(f,n.queue);T(d,n);c&&n.lost.then(q=>{n.onuncapturederror=()=>{};var w=X(),x=S(q.message);Nc(c,ic[q.reason],x);Y(w)});n.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=X();q=S(q.error.message);Qc(d,w,q);Y(x)};Pc(b,1,d,0)},n=>{var q=X();n=S(n.message);Pc(b,3,d,n);c&&Nc(c,4,n);Y(q)})},ba:(a,b,c)=>{var d=U(a);0===c&&jc();
-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(k){return 0}var g=Sc(16,f.byteLength);y.fill(0,g,f.byteLength);wb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(g,g+f.byteLength));nc(g)});return g},aa:a=>{var b=U(a),c=wb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete wb[a];b.unmap()}},a:a=>{delete vb[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(g){return!1}T(c,f);
d&&(wb[c]=[]);return!0},Y:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=xb(d+8)}T(c,U(a).createShaderModule(b))},$:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},W:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return kc[a]},X:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Ub[A[c+4>>2]],powerPreference:Zb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Dc=!!A[a+8>>2])}"gpu"in navigator?
navigator.gpu.requestAdapter(f).then(g=>{if(g)T(d,g),Oc(b,1,d,0);else{g=X();var k=S("WebGPU not available on this browser (requestAdapter returned null)");Oc(b,3,d,k);Y(g)}},g=>{var k=X();g=S(g.message);Oc(b,4,d,g);Y(k)}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Oc(b,3,d,a),Y(f))},T:()=>52,S:function(){return 70},U:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var k=A[b>>2],l=A[b+4>>2];b+=8;for(var m=0;m<l;m++){var t=a,v=y[k+m],n=lc[t];0===v||10===v?((1===t?ma:h)(L(n)),
n.length=0):n.push(v)}f+=l}A[d>>2]=f;return 0},N:Ha,La:function(){e.Yb=a=>{0!=pc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Yb)},Ga:function(){e.cc=a=>{const b=a.clipboardData.getData("text");mc(()=>{const c=S(b);oc(c)})};window.addEventListener("paste",e.cc)},Aa:function(){e.xc=[];e.Zb=b=>{b.stopPropagation();b.preventDefault()};e.$b=b=>{b.stopPropagation();b.preventDefault()};e.ac=b=>{b.stopPropagation();b.preventDefault()};e.bc=b=>{b.stopPropagation();b.preventDefault();
const c=b.dataTransfer.files;e.yc=c;qc(c.length);for(let f=0;f<c.length;f++)mc(()=>{const g=S(c[f].name);rc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);sc(b.clientX,b.clientY,d)};const a=e.ub;a.addEventListener("dragenter",e.Zb,!1);a.addEventListener("dragleave",e.$b,!1);a.addEventListener("dragover",e.ac,!1);a.addEventListener("drop",e.bc,!1)},Ia:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ja:function(a){e.Hb&&
(URL.revokeObjectURL(e.Hb[a].ic),e.Hb[a]=null)},Z:function(){document.exitPointerLock&&document.exitPointerLock()},na:function(a,b){0!==b&&(document.title=b?L(y,b):"");a=a?L(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?db[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.ub=M(a);e.ub||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.ub.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},
Ka:function(){window.removeEventListener("beforeunload",e.Yb)},Ba:function(){window.removeEventListener("paste",e.cc)},wa:function(){const a=e.ub;a.removeEventListener("dragenter",e.Zb);a.removeEventListener("dragleave",e.$b);a.removeEventListener("dragover",e.ac);a.removeEventListener("drop",e.bc)},h:function(){e.ub&&e.ub.requestPointerLock&&e.ub.requestPointerLock()},P:function(a,b,c){if(e.ub){if(0===b)a="none";else if(0!=c)a=e.Hb[a].kc;else switch(a){case 0:a="auto";break;case 1:a="default";break;
case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.ub.style.cursor=a}},Ha:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(y.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},l:function(a,b,c,d,f,g){const k=b?L(y,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(k,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=g?(y.set(m,f),vc(a,d,m.length)):xc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${k} failed with: `,m);yc(a)}):wc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${k} failed with: `,l);
yc(a)})},M:function(a,b){const c=b?L(y,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),yc(a)):uc(a,Number(d))):wc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);yc(a)})},L:function(a,b){b=b?L(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},e:(a,b)=>U(a).features.has(Vb[b]),
oa:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:Ab(A[b+12>>2])});a=U(a);b=Ec(0);T(b,a.beginComputePass(c));return b},ma:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],k=[],l=0;l<f;++l){var m=k,t=m.push;var v=g+56*l;var n=A[v+4>>2];if(0!==n){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:U(n),depthSlice:q,resolveTarget:U(A[v+12>>2]),clearValue:yb(v+24),loadOp:Xb[A[v+16>>2]],storeOp:cc[A[v+20>>2]]}}else v=void 0;t.call(m,v)}f=A[b+
20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Xb[A[f+8>>2]],depthStoreOp:cc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Xb[A[f+24>>2]],stencilStoreOp:cc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:Ab(A[b+28>>2]),maxDrawCount:d};a=U(a);d=Hc(0);T(d,a.beginRenderPass(b));return d},da:a=>{a=U(a);var b=Cc(0);T(b,a.finish());return b},
ea:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},la:(a,b)=>{U(a).setPipeline(U(b))},i:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var g=[],k=0;k<f;++k){var l=g,m=l.push;var t=b+40*k;var v=A[t+8>>2],n=A[t+32>>2],q=A[t+36>>2],w=A[t+4>>2];v?(n=t+24,n=A[n>>2]+4294967296*z[n+4>>2],-1==n&&(n=void 0),t={binding:w,resource:{buffer:U(v),offset:4294967296*A[t+4+16>>2]+A[t+16>>2],size:n}}):t=n?{binding:w,resource:U(n)}:{binding:w,
resource:U(q)};m.call(l,t)}c={label:c,layout:d,entries:g};a=U(a);d=Ac(0);T(d,a.createBindGroup(c));return d},j:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],g=0;g<d;++g){var k=f,l=k.push,m=b+88*g,t=A[m+4>>2],v=A[m+8>>2];var n=m+24;var q=A[n+4>>2];n=q?{type:Sb[q],hasDynamicOffset:!!A[n+8>>2],minBindingSize:4294967296*A[n+4+16>>2]+A[n+16>>2]}:void 0;q=(q=A[m+48+4>>2])?{type:ac[q]}:void 0;var w=m+56;var x=A[w+4>>2];w=x?{sampleType:fc[x],viewDimension:gc[A[w+8>>2]],multisampled:!!A[w+12>>
2]}:void 0;m+=72;m=(x=A[m+4>>2])?{access:bc[x],format:W[A[m+8>>2]],viewDimension:gc[A[m+12>>2]]}:void 0;l.call(k,{binding:t,visibility:v,buffer:n,sampler:q,texture:w,storageTexture:m})}c={label:c,entries:f};a=U(a);d=Bc(0);T(d,a.createBindGroupLayout(c));return d},pa:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=Dc(0);T(b,a.createCommandEncoder(c));return b},ra:(a,b)=>{var c=V(b+4);var d=Cb(A[b+12>>2]);b=(b+=16)?{module:U(A[b+4>>2]),constants:Bb(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,
layout:d,compute:b};a=U(a);d=Fc(0);T(d,a.createComputePipeline(c));return d},sa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],g=0;g<c;++g)f.push(U(A[d+4*g>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=Gc(0);T(c,a.createPipelineLayout(b));return c},qa:(a,b)=>{b=Pb(b);a=U(a);var c=Ic(0);T(c,a.createRenderPipeline(b));return c},ta:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Rb[A[b+12>>2]],addressModeV:Rb[A[b+16>>2]],addressModeW:Rb[A[b+20>>2]],magFilter:Wb[A[b+24>>2]],minFilter:Wb[A[b+28>>2]],
mipmapFilter:Yb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Fb[A[b+44>>2]],maxAnisotropy:qa[b+48>>1]});a=U(a);b=Jc(0);T(b,a.createSampler(c));return b},k:(a,b)=>{var c={label:V(b+4),size:zb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:ec[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=Lc(0);T(d,a.createTexture(c));return d},va:(a,b)=>{Qb(U(a).limits,b);return 1},
d:(a,b)=>U(a).features.has(Vb[b]),Da:(a,b)=>{a=M(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.zc=V(b+4);b=Kc(0);T(b,a);return b},ca:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},m:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},ua:(a,b,c,d,f,g)=>{var k=A[f+8>>2],l=A[f+12>>2],m=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[m>>2],y:A[m+4>>2],z:A[m+8>>2]},aspect:dc[A[b+
20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===k?void 0:k,rowsPerImage:4294967295===l?void 0:l},zb(g))},n:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},o:(a,b,c,d,f,g)=>{U(a).drawIndexed(b,c,d>>>0,f,g>>>0)},fa:a=>{U(a).end()},b:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ja:(a,b)=>{U(a).setBlendConstant(yb(b))},ha:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<
f?NaN:Number(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Mb[c],d,f)},ka:(a,b)=>{U(a).setPipeline(U(b))},ia:(a,b)=>{U(a).setStencilReference(b>>>0)},ga:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},Ca:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+
8>>2]],usage:A[b+16>>2],alphaMode:Tb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),g=>W[g])}b=A[b>>2];0!==b&&(c.colorSpace=$b[A[b+8>>2]],c.Bc={mode:hc[A[b+12>>2]]});a.configure(c)},xa:(a,b)=>{a=U(a);try{var c=Lc(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:gc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===
c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:dc[A[b+36>>2]]}}a=U(a);b=Mc(0);T(b,a.createView(c));return b}};function Uc(a=[]){var b=tc;a.unshift(ea);var c=a.length,d=ub(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=S(k);f+=4});A[f>>2]=0;try{var g=b(c,d);Ia(g)}catch(k){Ga(k)}}
function Vc(a=da){function b(){e.calledRun=!0;if(!r){Z.Na();e.onRuntimeInitialized?.();e.noInitialRun||Uc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Vc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Vc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Z;
(async function(){function a(c){Z=c.exports;oa=Z.Ma;sa();gb=Z.Bb;c=Z;R=c.Oa;nc=c.Pa;e.__sapp_emsc_onpaste=oc=c.Qa;e.__sapp_html5_get_ask_leave_site=pc=c.Ra;e.__sapp_emsc_begin_drop=qc=c.Sa;e.__sapp_emsc_drop=rc=c.Ta;e.__sapp_emsc_end_drop=sc=c.Ua;e.__sapp_emsc_invoke_fetch_cb=c.Va;e.__sapp_emsc_set_fullscreen_flag=c.Wa;e._main=tc=c.Xa;e.__saudio_emsc_pull=c.Ya;e.__sfetch_emsc_head_response=uc=c.Za;e.__sfetch_emsc_get_response=vc=c._a;e.__sfetch_emsc_failed_http_status=wc=c.$a;e.__sfetch_emsc_failed_buffer_too_small=
xc=c.ab;e.__sfetch_emsc_failed_other=yc=c.bb;Ac=c.cb;Bc=c.db;Cc=c.eb;Dc=c.fb;Ec=c.gb;Fc=c.hb;Gc=c.ib;Hc=c.mb;Ic=c.nb;Jc=c.ob;Kc=c.pb;Lc=c.qb;Mc=c.rb;Nc=c.xb;Oc=c.yb;Pc=c.zb;Qc=c.Ab;Rc=c.Cb;Sc=c.Db;Y=c.Eb;ub=c.Fb;X=c.Gb;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Tc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});va??=e.locateFile?e.locateFile("cgltf-sapp.wasm",ia):ia+"cgltf-sapp.wasm";return a((await ya(b)).instance)})();
Vc();
