var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),h=console.error.bind(console),p,r=!1,na,la=a=>a.startsWith("file://"),u,y,oa,pa,z,A,B,C,qa;
function ra(){var a=sa.buffer;u=new Int8Array(a);oa=new Int16Array(a);y=new Uint8Array(a);pa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=va;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},D=0,E=null,Ea=!0,Fa=0,F={},Ga=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Ea||0<Fa||(e.onExit?.(a),r=!0);fa(a,new za(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Ea||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},G=a=>{if(!r)try{a(),Ja()}catch(b){Ga(b)}},Qa=(a,b)=>{Ka=a;La=b;if(H)if(Ma||=!0,0==a)I=function(){setTimeout(J,Math.max(0,Na+b-performance.now())|0)};else if(1==a)I=function(){Oa(J)};else if(2==
a){if(!Pa)if(globalThis.setImmediate)Pa=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}I=function(){Pa(J)}}},$a=(a,b,c,d,f)=>{function g(){return k<Sa?(Ja(),!1):!0}H=a;Ta=d;var k=Sa;Ma=!1;J=function(){if(!r)if(0<Ua.length){var l=
Ua.shift();l.qc(l.hc);if(Va){var m=Va,t=0==m%1?m-1:Math.floor(m);Va=l.kc?t:(8*m+(t+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",m=Va??0,t=Wa.pc??0,m?m<t?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));g()&&setTimeout(J,0)}else if(g())if(Xa=Xa+1|0,1==Ka&&1<La&&0!=Xa%La)I();else{0==Ka&&(Na=performance.now());a:if(!r){for(l of Ya)if(!1===l())break a;G(a);for(m of Za)m()}g()&&I()}};f||(0<b?Qa(0,1E3/b):Qa(1,1),I());if(c)throw"unwind";},Ma=!1,I=null,
Sa=0,H=null,Ta=0,Ka=0,La=0,Xa=0,Ua=[],Ya=[],Za=[];function ab(){I=null;Sa++}var L=0;function Oa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===L)L=b+1E3/60;else for(;b+2>=L;)L+=1E3/60;setTimeout(a,Math.max(L-b,0))}}
var Wa={},Na,J,Pa,Va,bb=globalThis.TextDecoder&&new TextDecoder,M=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&bb)return bb.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},cb=
[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?M(y,a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):null)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],O=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};function gb(a){var b=P.lb[a];b.target.removeEventListener(b.kb,b.Vb,b.mb);P.lb.splice(a,1)}
function hb(){if(navigator.userActivation?navigator.userActivation.isActive:P.Mb&&P.ec.Jb){var a=P.wb;P.wb=[];for(var b of a)b.Qb(...b.Ub)}}function Q(a){if(!a.target)return-4;if(a.tb)a.Vb=function(c){++P.Mb;P.ec=a;hb();a.ub(c);hb();--P.Mb},a.target.addEventListener(a.kb,a.Vb,a.mb),P.lb.push(a);else for(var b=0;b<P.lb.length;++b)P.lb[b].target==a.target&&P.lb[b].kb==a.kb&&gb(b--);return 0}function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={ic:0,rc:0,Nb:0,xb:0,Tb:0,Sb:0,Kb:0,oc:0,uc:0,nc:0,Lb:0,Ob:0,Dc:0,Rb:0,tc(a,b,c){u.set(u.subarray(b,b+c),a)},vc(){for(;P.lb.length;)gb(P.lb.length-1);P.wb=[]},Mb:0,wb:[],mc(a,b,c){function d(g,k){if(g.length!=k.length)return!1;for(var l in g)if(g[l]!=k[l])return!1;return!0}for(var f of P.wb)if(f.Qb==a&&d(f.Ub,c))return;P.wb.push({Qb:a,Yb:b,Ub:c});P.wb.sort((g,k)=>g.Yb<k.Yb)},xc(a){P.wb=P.wb.filter(b=>b.Qb!=a)},lb:[],wc:(a,b)=>{for(var c=0;c<P.lb.length;++c)P.lb[c].target!=a||b&&b!=P.lb[c].kb||
gb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},R=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0}},jb=(a,b,c,d,f,g)=>{P.Kb||
(P.Kb=S(256));a={target:N(a),kb:g,tb:d,ub:(k=event)=>{var l=k.target.id?k.target.id:"",m=P.Kb;R(ib(k.target),m+0,128);R(l,m+128,128);O(d)(f,m,b)&&k.preventDefault()},mb:c};return Q(a)},kb=(a,b,c,d,f)=>{P.Lb||(P.Lb=S(276));return Q({target:a,kb:f,tb:d,ub:(g=event)=>{var k=P.Lb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,m=!!l;u[k]=m;u[k+1]=P.fullscreenEnabled();var t=m?l:P.fc,v=
t?.id||"";R(ib(t),k+2,128);R(v,k+130,128);z[k+260>>2]=t?t.clientWidth:0;z[k+264>>2]=t?t.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;m&&(P.fc=l);O(d)(19,k,b)&&g.preventDefault()},mb:c})},lb=(a,b,c,d,f,g)=>{P.Nb||(P.Nb=S(160));a={target:N(a),kb:g,tb:d,ub:k=>{var l=P.Nb;C[l>>3]=k.timeStamp;var m=l>>2;z[m+2]=k.location;u[l+12]=k.ctrlKey;u[l+13]=k.shiftKey;u[l+14]=k.altKey;u[l+15]=k.metaKey;u[l+16]=k.repeat;z[m+5]=k.charCode;z[m+6]=k.keyCode;z[m+7]=k.which;R(k.key||"",l+32,32);R(k.code||
"",l+64,32);R(k.char||"",l+96,32);R(k.locale||"",l+128,32);O(d)(f,l,b)&&k.preventDefault()},mb:c};return Q(a)},mb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=db(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,f,g)=>{P.xb||(P.xb=S(64));a=N(a);return Q({target:a,
Jb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,kb:g,tb:d,ub:(k=event)=>{mb(P.xb,k,a);O(d)(f,P.xb,b)&&k.preventDefault()},mb:c})},ob=(a,b,c,d)=>{P.Ob||(P.Ob=S(257));return Q({target:a,kb:"pointerlockchange",tb:d,ub:(f=event)=>{var g=P.Ob,k=document.pointerLockElement;u[g]=!!k;var l=k?.id||"";R(ib(k),g+1,128);R(l,g+129,128);O(d)(20,g,b)&&f.preventDefault()},mb:c})},pb=(a,b,c,d)=>Q({target:a,kb:"pointerlockerror",tb:d,ub:(f=event)=>{O(d)(38,0,b)&&f.preventDefault()},mb:c}),qb=(a,b,c,d)=>{P.Sb||
(P.Sb=S(36));a=N(a);return Q({target:a,kb:"resize",tb:d,ub:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=P.Sb;z[k>>2]=0;z[k+4>>2]=g.clientWidth;z[k+8>>2]=g.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;O(d)(10,k,b)&&f.preventDefault()}}},mb:c})},rb=(a,b,c,d,f,g)=>{P.Rb||(P.Rb=S(1552));a=N(a);return Q({target:a,Jb:"touchstart"==g||"touchend"==g,kb:g,tb:d,ub:k=>{var l={},m=k.touches;
for(var t of m)t.Wb=t.Xb=0,l[t.identifier]=t;for(var v of k.changedTouches)v.Wb=1,l[v.identifier]=v;for(var n of k.targetTouches)l[n.identifier].Xb=1;m=P.Rb;C[m>>3]=k.timeStamp;u[m+12]=k.ctrlKey;u[m+13]=k.shiftKey;u[m+14]=k.altKey;u[m+15]=k.metaKey;t=m+16;v=db(a);n=0;for(let q of Object.values(l))if(l=t>>2,z[l]=q.identifier,z[l+1]=q.screenX,z[l+2]=q.screenY,z[l+3]=q.clientX,z[l+4]=q.clientY,z[l+5]=q.pageX,z[l+6]=q.pageY,u[t+28]=q.Wb,u[t+29]=q.Xb,z[l+8]=q.clientX-(v.left|0),z[l+9]=q.clientY-(v.top|
0),t+=48,31<++n)break;z[m+8>>2]=n;O(d)(f,m,b)&&k.preventDefault()},mb:c})},sb=(a,b,c,d)=>{P.Tb||(P.Tb=S(96));return Q({target:a,Jb:!0,kb:"wheel",tb:d,ub:(f=event)=>{var g=P.Tb;mb(g,f,a);C[g+64>>3]=f.deltaX;C[g+72>>3]=f.deltaY;C[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;O(d)(9,g,b)&&f.preventDefault()},mb:c})},T=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=tb(b);R(a,c,b);return c},U=[],ub=(a,b)=>{U[a>>>0]=b},vb=[],V=a=>{if(a)return U[a>>>
0]},wb=a=>{var b=A[a>>2];return b?M(y,b,A[a+4>>2]):""},W=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?M(y,b,a):"";if(0===a)return""},xb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),yb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),zb=a=>{if(0!==a)return{querySet:V(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},Ab=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,g=wb(f+4);c[g]=C[f+16>>3]}return c}},Bb=a=>a?V(a):"auto",Ob=a=>{function b(d){if(d)return{operation:Cb[A[d>>
2]],srcFactor:Db[A[d+4>>2]],dstFactor:Db[A[d+8>>2]]}}function c(d){return{compare:Eb[A[d>>2]],failOp:Fb[A[d+4>>2]],depthFailOp:Fb[A[d+8>>2]],passOp:Fb[A[d+12>>2]]}}return{label:W(a+4),layout:Bb(A[a+12>>2]),vertex:function(d){if(d){var f=V(A[d+4>>2]),g=Ab(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var l=A[d+28>>2];if(k){for(var m=[],t=0;t<k;++t){var v=m,n=v.push;var q=l+24*t;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var K=null;else{K=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Gb[w];q=A[q+20>>2];for(var Hb=
[],Ra=0;Ra<x;++Ra){var Ib=Hb,ua=q+24*Ra;Ib.push.call(Ib,{format:Jb[A[ua+4>>2]],offset:4294967296*A[ua+4+8>>2]+A[ua+8>>2],shaderLocation:A[ua+16>>2]})}K={arrayStride:K,stepMode:w,attributes:Hb}}}else K=void 0;n.call(v,K)}k=m}else k=void 0;return{module:f,constants:g,buffers:k,entryPoint:W(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Kb[A[d+4>>2]],stripIndexFormat:Lb[A[d+8>>2]],frontFace:Mb[A[d+12>>2]],cullMode:Nb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:X[A[d+
4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Eb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=V(A[d+4>>2]),g=Ab(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],l=A[d+28>>2],m=[],t=0;t<k;++t){var v=m,n=v.push,
q=l+24*t,w=A[q+4>>2];if(0===w)q=void 0;else{w=X[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}n.call(v,q)}return{module:f,constants:g,targets:m,entryPoint:W(d+8)}}}(A[a+92>>2])}},Pb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",
32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",
104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.sc&&c("maxImmediateSize",148)},Qb=[,"clamp-to-edge","repeat","mirror-repeat"],Db=[,"zero","one","src","one-minus-src",
"src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Cb=[,"add","subtract","reverse-subtract","min","max"],Rb=["binding-not-used",,"uniform","storage","read-only-storage"],Eb=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Sb=[,"opaque","premultiplied","unpremultiplied","inherit"],Nb=[,"none","front","back"],Tb=
[,"compatibility","core"],Ub={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",
20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Vb=[,"nearest","linear"],Mb=[,"ccw","cw"],Lb=[,"uint16","uint32"],Wb=[,"load","clear"],Xb=[,"nearest","linear"],Yb=[,"low-power","high-performance"],Zb=[,"srgb","display-p3"],Kb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],$b=["binding-not-used",,"filtering","non-filtering",
"comparison"],Fb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],ac=["binding-not-used",,"write-only","read-only","read-write"],bc=[,"store","discard"],cc=[,"all","stencil-only","depth-only"],dc=[,"1d","2d","3d"],X=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm",
"rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb",
"bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb",
"astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],ec=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],fc=[,"1d","2d","2d-array","cube","cube-array","3d"],gc=
[,"standard","extended"],Jb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Gb=[,"vertex","instance"],
hc={undefined:1,unknown:1,destroyed:2},ic=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";ic.Pb||(ic.Pb={});ic.Pb[a]||(ic.Pb[a]=1,ca&&(a="warning: "+a),h(a))},jc={rgba8unorm:22,bgra8unorm:27},kc=[null,[],[]],lc=a=>{var b=Y();a();Z(b)};e.requestAnimationFrame=Oa;e.pauseMainLoop=ab;e.resumeMainLoop=function(){Sa++;var a=Ka,b=La,c=H;H=null;$a(c,0,!1,Ta,!0);Qa(a,b);I()};e.preMainLoop&&Ya.push(e.preMainLoop);e.postMainLoop&&Za.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);
e.print&&(ma=e.print);e.printErr&&(h=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var S,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Z,tb,Y,sa,fb,Rc={V:()=>ta(""),O:()=>{Ea=!1;Fa=0},P:(a,b)=>{F[a]&&(clearTimeout(F[a].id),delete F[a]);if(!b)return 0;var c=setTimeout(()=>{delete F[a];G(()=>Pc(a,performance.now()))},b);F[a]={id:c,Bc:b};return 0},ya:()=>{ab();H=null},I:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,K:(a,b,c)=>{a=N(a);if(!a)return-4;a=db(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},za:()=>performance.now(),
Fa:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},R:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},q:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),H:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},r:(a,b,c,
d)=>jb(a,b,c,d,13,"focus"),p:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=N(a);if(!a)return-4;kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},A:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),y:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),z:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),Ga:(a,b,c)=>{a=O(a);$a(a,b,c)},G:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),D:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),C:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),E:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),F:(a,b,c,d)=>nb(a,b,c,d,6,
"mouseup"),t:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?ob(a,b,c,d):-4:-1,s:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?pb(a,b,c,d):-4:-1,J:(a,b,c,d)=>qb(a,b,c,d),u:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),v:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),w:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),x:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),B:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?sb(a,b,c,d):-1:-4,Z:function(a,b,c,d,f,g){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>
c||9007199254740992<c?NaN:Number(c);a=V(a);var k={};if(g){var l=A[g+12>>2];if(l){var m=A[g+16>>2];k.requiredFeatures=Array.from(A.subarray(m>>2,m+4*l>>2),n=>Ub[n])}var t=A[g+20>>2];if(t){var v={};function n(w,x,K=!1){x=A[t+x>>2];4294967295==x||K&&0==x||(v[w]=x)}function q(w,x){x=t+x;var K=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=K)v[w]=4294967296*A[x+4>>2]+A[x>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",8);n("maxTextureDimension3D",12);n("maxTextureArrayLayers",16);n("maxBindGroups",
20);n("maxBindGroupsPlusVertexBuffers",24);n("maxDynamicUniformBuffersPerPipelineLayout",32);n("maxDynamicStorageBuffersPerPipelineLayout",36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);n("maxVertexBuffers",
88);q("maxBufferSize",96);n("maxVertexAttributes",104);n("maxVertexBufferArrayStride",108);n("maxInterStageShaderVariables",112);n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",148,!0);k.requiredLimits=v}if(l=A[g+24>>2])l={label:W(l+
4)},k.defaultQueue=l;k.label=W(g+4)}a.requestDevice(k).then(n=>{G(()=>{U[f>>>0]=n.queue;U[d>>>0]=n;n.lost.then(q=>{G(()=>{n.onuncapturederror=()=>{};var w=Y(),x=T(q.message);Lc(c,hc[q.reason],x);Z(w)})});n.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=Y();q=T(q.error.message);Oc(d,w,q);Z(x)};Nc(b,1,d,0)})},n=>{G(()=>{var q=Y(),w=T(n.message);Nc(b,3,d,w);c&&Lc(c,4,w);Z(q)})})},ba:(a,
b,c)=>{var d=V(a);0===c&&ic();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(k){return 0}var g=Qc(16,f.byteLength);y.fill(0,g,f.byteLength);vb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(g,g+f.byteLength));mc(g)});return g},aa:a=>{var b=V(a),c=vb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete vb[a];b.unmap()}},a:a=>{delete U[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:W(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=V(a);try{var f=a.createBuffer(b)}catch(g){return!1}U[c>>>
0]=f;d&&(vb[c]=[]);return!0},Y:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:W(b+4),code:""};switch(f){case 2:b.code=wb(d+8)}a=V(a).createShaderModule(b);U[c>>>0]=a},$:a=>{a=V(a);a.onuncapturederror=null;a.destroy()},W:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return jc[a]},X:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Tb[A[c+4>>2]],powerPreference:Yb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Ec=!!A[a+8>>2])}"gpu"in
navigator?navigator.gpu.requestAdapter(f).then(g=>{G(()=>{if(g)U[d>>>0]=g,Mc(b,1,d,0);else{var k=Y(),l=T("WebGPU not available on this browser (requestAdapter returned null)");Mc(b,3,d,l);Z(k)}})},g=>{G(()=>{var k=Y(),l=T(g.message);Mc(b,4,d,l);Z(k)})}):(f=Y(),a=T("WebGPU not available on this browser (navigator.gpu is not available)"),Mc(b,3,d,a),Z(f))},T:()=>52,S:function(){return 70},U:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var k=A[b>>2],l=A[b+4>>2];b+=8;for(var m=0;m<l;m++){var t=a,v=y[k+m],n=kc[t];
0===v||10===v?((1===t?ma:h)(M(n)),n.length=0):n.push(v)}f+=l}A[d>>2]=f;return 0},N:Ha,Ma:function(){e.Zb=a=>{0!=oc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Zb)},Ha:function(){e.dc=a=>{const b=a.clipboardData.getData("text");lc(()=>{const c=T(b);nc(c)})};window.addEventListener("paste",e.dc)},Aa:function(){e.yc=[];e.$b=b=>{b.stopPropagation();b.preventDefault()};e.ac=b=>{b.stopPropagation();b.preventDefault()};e.bc=b=>{b.stopPropagation();b.preventDefault()};
e.cc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.zc=c;pc(c.length);for(let f=0;f<c.length;f++)lc(()=>{const g=T(c[f].name);qc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);rc(b.clientX,b.clientY,d)};const a=e.vb;a.addEventListener("dragenter",e.$b,!1);a.addEventListener("dragleave",e.ac,!1);a.addEventListener("dragover",e.bc,!1);a.addEventListener("drop",e.cc,!1)},Ja:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},Ka:function(a){e.Ib&&(URL.revokeObjectURL(e.Ib[a].jc),e.Ib[a]=null)},_:function(){document.exitPointerLock&&document.exitPointerLock()},na:function(a,b){0!==b&&(document.title=b?M(y,b):"");a=a?M(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?cb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.vb=N(a);e.vb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.vb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",
a)},La:function(){window.removeEventListener("beforeunload",e.Zb)},Ba:function(){window.removeEventListener("paste",e.dc)},wa:function(){const a=e.vb;a.removeEventListener("dragenter",e.$b);a.removeEventListener("dragleave",e.ac);a.removeEventListener("dragover",e.bc);a.removeEventListener("drop",e.cc)},h:function(){e.vb&&e.vb.requestPointerLock&&e.vb.requestPointerLock()},Q:function(a,b,c){if(e.vb){if(0===b)a="none";else if(0!=c)a=e.Ib[a].lc;else switch(a){case 0:a="auto";break;case 1:a="default";
break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.vb.style.cursor=a}},Ia:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(y.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},l:function(a,b,c,d,f,g){const k=b?M(y,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(k,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=g?(y.set(m,f),uc(a,d,m.length)):wc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${k} failed with: `,m);xc(a)}):vc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${k} failed with: `,l);
xc(a)})},M:function(a,b){const c=b?M(y,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),xc(a)):tc(a,Number(d))):vc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);xc(a)})},L:function(a,b){b=b?M(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Ca:(a,b)=>{Pb(V(a).limits,b);
return 1},e:(a,b)=>V(a).features.has(Ub[b]),oa:(a,b)=>{var c;b&&(c={label:W(b+4),timestampWrites:zb(A[b+12>>2])});b=V(a);a=Cc(0);c=b.beginComputePass(c);U[a>>>0]=c;return a},ma:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=W(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],k=[],l=0;l<f;++l){var m=k,t=m.push;var v=g+56*l;var n=A[v+4>>2];if(0!==n){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:V(n),depthSlice:q,resolveTarget:V(A[v+12>>2]),clearValue:xb(v+24),loadOp:Wb[A[v+16>>2]],storeOp:bc[A[v+
20>>2]]}}else v=void 0;t.call(m,v)}f=A[b+20>>2];f=0!==f?{view:V(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Wb[A[f+8>>2]],depthStoreOp:bc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Wb[A[f+24>>2]],stencilStoreOp:bc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:V(A[b+24>>2]),timestampWrites:zb(A[b+28>>2]),maxDrawCount:d};d=V(a);a=Fc(0);b=d.beginRenderPass(b);U[a>>>0]=b;return a},
da:a=>{var b=V(a);a=Ac(0);b=b.finish();U[a>>>0]=b;return a},ea:a=>{V(a).end()},c:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},la:(a,b)=>{V(a).setPipeline(V(b))},i:(a,b)=>{var c=W(b+4),d=V(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var g=[],k=0;k<f;++k){var l=g,m=l.push;var t=b+40*k;var v=A[t+8>>2],n=A[t+32>>2],q=A[t+36>>2],w=A[t+4>>2];v?(n=t+24,n=A[n>>2]+4294967296*z[n+4>>2],-1==n&&(n=void 0),t={binding:w,resource:{buffer:V(v),offset:4294967296*A[t+4+16>>2]+A[t+
16>>2],size:n}}):t=n?{binding:w,resource:V(n)}:{binding:w,resource:V(q)};m.call(l,t)}c={label:c,layout:d,entries:g};d=V(a);a=yc(0);c=d.createBindGroup(c);U[a>>>0]=c;return a},j:(a,b)=>{var c=W(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],g=0;g<d;++g){var k=f,l=k.push,m=b+88*g,t=A[m+4>>2],v=A[m+8>>2];var n=m+24;var q=A[n+4>>2];n=q?{type:Rb[q],hasDynamicOffset:!!A[n+8>>2],minBindingSize:4294967296*A[n+4+16>>2]+A[n+16>>2]}:void 0;q=(q=A[m+48+4>>2])?{type:$b[q]}:void 0;var w=m+56;var x=A[w+4>>2];w=x?{sampleType:ec[x],
viewDimension:fc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;m+=72;m=(x=A[m+4>>2])?{access:ac[x],format:X[A[m+8>>2]],viewDimension:fc[A[m+12>>2]]}:void 0;l.call(k,{binding:t,visibility:v,buffer:n,sampler:q,texture:w,storageTexture:m})}c={label:c,entries:f};d=V(a);a=zc(0);c=d.createBindGroupLayout(c);U[a>>>0]=c;return a},pa:(a,b)=>{var c;b&&(c={label:W(b+4)});b=V(a);a=Bc(0);c=b.createCommandEncoder(c);U[a>>>0]=c;return a},ra:(a,b)=>{var c=W(b+4);var d=Bb(A[b+12>>2]);b=(b+=16)?{module:V(A[b+4>>2]),
constants:Ab(A[b+16>>2],A[b+20>>2]),entryPoint:W(b+8)}:void 0;c={label:c,layout:d,compute:b};d=V(a);a=Dc(0);c=d.createComputePipeline(c);U[a>>>0]=c;return a},sa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],g=0;g<c;++g)f.push(V(A[d+4*g>>2]));b={label:W(b+4),bindGroupLayouts:f};c=V(a);a=Ec(0);b=c.createPipelineLayout(b);U[a>>>0]=b;return a},qa:(a,b)=>{b=Ob(b);var c=V(a);a=Gc(0);b=c.createRenderPipeline(b);U[a>>>0]=b;return a},ta:(a,b)=>{var c;b&&(c={label:W(b+4),addressModeU:Qb[A[b+12>>2]],addressModeV:Qb[A[b+
16>>2]],addressModeW:Qb[A[b+20>>2]],magFilter:Vb[A[b+24>>2]],minFilter:Vb[A[b+28>>2]],mipmapFilter:Xb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Eb[A[b+44>>2]],maxAnisotropy:pa[b+48>>1]});b=V(a);a=Hc(0);c=b.createSampler(c);U[a>>>0]=c;return a},k:(a,b)=>{var c={label:W(b+4),size:yb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:dc[A[b+24>>2]],format:X[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>
2),f=>X[f]));a=V(a);d=Jc(0);ub(d,a.createTexture(c));return d},va:(a,b)=>{Pb(V(a).limits,b);return 1},d:(a,b)=>V(a).features.has(Ub[b]),Ea:(a,b)=>{a=N(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Ac=W(b+4);b=Ic(0);U[b>>>0]=a;return b},ca:(a,b,c)=>{a=V(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>V(d));a.submit(b)},m:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);V(a).writeBuffer(V(b),c,y.subarray(d,d+f),0,f)},ua:(a,b,c,d,f,g)=>{var k=A[f+8>>2],l=A[f+12>>2],m=
b+8;V(a).writeTexture({texture:V(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[m>>2],y:A[m+4>>2],z:A[m+8>>2]},aspect:cc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===k?void 0:k,rowsPerImage:4294967295===l?void 0:l},yb(g))},n:(a,b,c,d,f)=>{V(a).draw(b,c,d>>>0,f>>>0)},o:(a,b,c,d,f,g)=>{V(a).drawIndexed(b,c,d>>>0,f,g>>>0)},fa:a=>{V(a).end()},b:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ja:(a,b)=>{V(a).setBlendConstant(xb(b))},
ha:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);b=V(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Lb[c],d,f)},ka:(a,b)=>{V(a).setPipeline(V(b))},ia:(a,b)=>{V(a).setStencilReference(b>>>0)},ga:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);c=V(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},Da:(a,b)=>{var c=A[b+4>>2];a=
V(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:V(c),format:X[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Sb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),g=>X[g])}b=A[b>>2];0!==b&&(c.colorSpace=Zb[A[b+8>>2]],c.Cc={mode:gc[A[b+12>>2]]});a.configure(c)},xa:(a,b)=>{a=V(a);try{var c=Jc(0),d=a.getCurrentTexture();U[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=
A[b+24>>2];var d=A[b+32>>2];c={label:W(b+4),format:X[A[b+12>>2]],dimension:fc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:cc[A[b+36>>2]]}}b=V(a);a=Kc(0);b=b.createView(c);U[a>>>0]=b;return a}};function Sc(a=[]){var b=sc;a.unshift(ea);var c=a.length,d=tb(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=T(k);f+=4});A[f>>2]=0;try{var g=b(c,d);Ia(g)}catch(k){Ga(k)}}
function Tc(a=da){function b(){e.calledRun=!0;if(!r){Uc.Oa();e.onRuntimeInitialized?.();e.noInitialRun||Sc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Tc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Tc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Uc;
(async function(){function a(c){c=Uc=c.exports;S=c.Pa;mc=c.Qa;nc=e.__sapp_emsc_onpaste=c.Ra;oc=e.__sapp_html5_get_ask_leave_site=c.Sa;pc=e.__sapp_emsc_begin_drop=c.Ta;qc=e.__sapp_emsc_drop=c.Ua;rc=e.__sapp_emsc_end_drop=c.Va;e.__sapp_emsc_invoke_fetch_cb=c.Wa;e.__sapp_emsc_set_fullscreen_flag=c.Xa;sc=e._main=c.Ya;e.__saudio_emsc_pull=c.Za;tc=e.__sfetch_emsc_head_response=c._a;uc=e.__sfetch_emsc_get_response=c.$a;vc=e.__sfetch_emsc_failed_http_status=c.ab;wc=e.__sfetch_emsc_failed_buffer_too_small=
c.bb;xc=e.__sfetch_emsc_failed_other=c.cb;yc=c.db;zc=c.eb;Ac=c.fb;Bc=c.gb;Cc=c.hb;Dc=c.ib;Ec=c.jb;Fc=c.nb;Gc=c.ob;Hc=c.pb;Ic=c.qb;Jc=c.rb;Kc=c.sb;Lc=c.yb;Mc=c.zb;Nc=c.Ab;Oc=c.Bb;Pc=c.Db;Qc=c.Eb;Z=c.Fb;tb=c.Gb;Y=c.Hb;sa=c.Na;fb=c.Cb;ra();D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Uc}D++;e.monitorRunDependencies?.(D);var b={a:Rc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});va??=e.locateFile?e.locateFile("cgltf-sapp.wasm",ia):ia+"cgltf-sapp.wasm";
return a((await ya(b)).instance)})();Tc();
