var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var g=console.error.bind(console),p,q=!1,ma,la=a=>a.startsWith("file://"),na,u,x,oa,z,A,pa,B,qa;
function ra(){var a=na.buffer;u=new Int8Array(a);oa=new Int16Array(a);x=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);pa=new Float32Array(a);B=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}var C=0,D=null;function sa(a){f.onAbort?.(a);a="Aborted("+a+")";g(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(f)},za=[],Aa=[],Ba=()=>{var a=f.preRun.shift();Aa.push(a)},Ca=!0,Da=0,E={},Ea=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Fa=a=>{ma=a;Ca||0<Da||(f.onExit?.(a),q=!0);fa(a,new xa(a))},Ga=a=>{ma=a;Fa(a)},Ha=()=>{if(!(Ca||0<Da))try{var a=ma;ma=a;Fa(a)}catch(b){Ea(b)}},Ia=a=>{if(!q)try{a(),Ha()}catch(b){Ea(b)}},Qa=(a,b)=>{Ja=a;Ka=b;if(F)if(La||=!0,0==a)G=function(){setTimeout(H,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)G=function(){Na(H)};else if(2==a){if("undefined"==
typeof Oa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Oa=setImmediate;G=function(){Oa(H)}}},Za=(a,b,c,d,e)=>{function h(){return k<Ra?(Ha(),!1):!0}F=a;Sa=d;var k=Ra;La=!1;H=function(){if(!q)if(0<Ta.length){var m=
Ta.shift();m.Jb(m.Ab);if(Ua){var n=Ua,r=0==n%1?n-1:Math.floor(n);Ua=m.Db?r:(8*n+(r+.5))/9}f.setStatus&&(m=f.statusMessage||"Please wait...",n=Ua??0,r=Va.Ib??0,n?n<r?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(m):f.setStatus(""));h()&&setTimeout(H,0)}else if(h())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)G();else{0==Ja&&(Ma=performance.now());a:if(!q){for(m of Xa)if(!1===m())break a;Ia(a);for(n of Ya)n()}h()&&G()}};e||(0<b?Qa(0,1E3/b):Qa(1,1),G());if(c)throw"unwind";},La=!1,G=
null,Ra=0,F=null,Sa=0,Ja=0,Ka=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){G=null;Ra++}var I=0;function Na(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===I)I=b+1E3/60;else for(;b+2>=I;)I+=1E3/60;setTimeout(a,Math.max(I-b,0))}}
var Va={},Ma,H,Oa,Ua,ab="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a=0,b)=>{var c=x;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&ab)return ab.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))b+=String.fromCharCode((e&31)<<6|h);else{var k=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|k:(e&7)<<18|h<<12|k<<6|c[a++]&63;65536>e?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},
bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?J(a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],eb,L=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=M.Ka[a];b.target.removeEventListener(b.Ja,b.ob,b.La);M.Ka.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:M.Za&&M.yb.Wa){var a=M.Qa;M.Qa=[];for(var b of a)b.jb(...b.nb)}}function N(a){if(!a.target)return-4;if(a.Ma)a.ob=function(c){++M.Za;M.yb=a;gb();a.Na(c);gb();--M.Za},a.target.addEventListener(a.Ja,a.ob,a.La),M.Ka.push(a);else for(var b=0;b<M.Ka.length;++b)M.Ka[b].target==a.target&&M.Ka[b].Ja==a.Ja&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={Bb:0,Kb:0,hb:0,Ra:0,mb:0,lb:0,Xa:0,Hb:0,Nb:0,Gb:0,Ya:0,ib:0,Wb:0,kb:0,Mb(a,b,c){u.set(u.subarray(b,b+c),a)},Ob(){for(;M.Ka.length;)fb(M.Ka.length-1);M.Qa=[]},Za:0,Qa:[],Fb(a,b,c){function d(h,k){if(h.length!=k.length)return!1;for(var m in h)if(h[m]!=k[m])return!1;return!0}for(var e of M.Qa)if(e.jb==a&&d(e.nb,c))return;M.Qa.push({jb:a,rb:b,nb:c});M.Qa.sort((h,k)=>h.rb<k.rb)},Qb(a){M.Qa=M.Qa.filter(b=>b.jb!=a)},Ka:[],Pb:(a,b)=>{for(var c=0;c<M.Ka.length;++c)M.Ka[c].target!=a||b&&b!=M.Ka[c].Ja||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},O=(a,b,c)=>{var d=x;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var h=a.codePointAt(e);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;e++}}d[b]=0}},ib=(a,b,c,d,e,h)=>{M.Xa||
(M.Xa=P(256));a={target:K(a),Ja:h,Ma:d,Na:(k=event)=>{var m=k.target.id?k.target.id:"",n=M.Xa;O(hb(k.target),n+0,128);O(m,n+128,128);L(d)(e,n,b)&&k.preventDefault()},La:c};return N(a)},jb=(a,b,c,d,e)=>{M.Ya||(M.Ya=P(276));return N({target:a,Ja:e,Ma:d,Na:(h=event)=>{var k=M.Ya,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!m;u[k]=n;u[k+1]=M.fullscreenEnabled();var r=n?m:M.zb,v=
r?.id||"";O(hb(r),k+2,128);O(v,k+130,128);z[k+260>>2]=r?r.clientWidth:0;z[k+264>>2]=r?r.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;n&&(M.zb=m);L(d)(19,k,b)&&h.preventDefault()},La:c})},kb=(a,b,c,d,e,h)=>{M.hb||(M.hb=P(160));a={target:K(a),Ja:h,Ma:d,Na:k=>{var m=M.hb;B[m>>3]=k.timeStamp;var n=m>>2;z[n+2]=k.location;u[m+12]=k.ctrlKey;u[m+13]=k.shiftKey;u[m+14]=k.altKey;u[m+15]=k.metaKey;u[m+16]=k.repeat;z[n+5]=k.charCode;z[n+6]=k.keyCode;z[n+7]=k.which;O(k.key||"",m+32,32);O(k.code||
"",m+64,32);O(k.char||"",m+96,32);O(k.locale||"",m+128,32);L(d)(e,m,b)&&k.preventDefault()},La:c};return N(a)},lb=(a,b,c)=>{B[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=cb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},Q=(a,b,c,d,e,h)=>{M.Ra||(M.Ra=P(64));a=K(a);return N({target:a,
Wa:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Ja:h,Ma:d,Na:(k=event)=>{lb(M.Ra,k,a);L(d)(e,M.Ra,b)&&k.preventDefault()},La:c})},mb=(a,b,c,d)=>{M.ib||(M.ib=P(257));return N({target:a,Ja:"pointerlockchange",Ma:d,Na:(e=event)=>{var h=M.ib,k=document.pointerLockElement;u[h]=!!k;var m=k?.id||"";O(hb(k),h+1,128);O(m,h+129,128);L(d)(20,h,b)&&e.preventDefault()},La:c})},nb=(a,b,c,d)=>N({target:a,Ja:"pointerlockerror",Ma:d,Na:(e=event)=>{L(d)(38,0,b)&&e.preventDefault()},La:c}),ob=(a,b,c,d)=>{M.lb||
(M.lb=P(36));a=K(a);return N({target:a,Ja:"resize",Ma:d,Na:(e=event)=>{if(e.target==a){var h=document.body;if(h){var k=M.lb;z[k>>2]=0;z[k+4>>2]=h.clientWidth;z[k+8>>2]=h.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;L(d)(10,k,b)&&e.preventDefault()}}},La:c})},pb=(a,b,c,d,e,h)=>{M.kb||(M.kb=P(1552));a=K(a);return N({target:a,Wa:"touchstart"==h||"touchend"==h,Ja:h,Ma:d,Na:k=>{var m={},n=k.touches;
for(var r of n)r.pb=r.qb=0,m[r.identifier]=r;for(var v of k.changedTouches)v.pb=1,m[v.identifier]=v;for(var l of k.targetTouches)m[l.identifier].qb=1;n=M.kb;B[n>>3]=k.timeStamp;u[n+12]=k.ctrlKey;u[n+13]=k.shiftKey;u[n+14]=k.altKey;u[n+15]=k.metaKey;r=n+16;v=cb(a);l=0;for(let t of Object.values(m))if(m=r>>2,z[m]=t.identifier,z[m+1]=t.screenX,z[m+2]=t.screenY,z[m+3]=t.clientX,z[m+4]=t.clientY,z[m+5]=t.pageX,z[m+6]=t.pageY,u[r+28]=t.pb,u[r+29]=t.qb,z[m+8]=t.clientX-(v.left|0),z[m+9]=t.clientY-(v.top|
0),r+=48,31<++l)break;z[n+8>>2]=l;L(d)(e,n,b)&&k.preventDefault()},La:c})},qb=(a,b,c,d)=>{M.mb||(M.mb=P(96));return N({target:a,Wa:!0,Ja:"wheel",Ma:d,Na:(e=event)=>{var h=M.mb;lb(h,e,a);B[h+64>>3]=e.deltaX;B[h+72>>3]=e.deltaY;B[h+80>>3]=e.deltaZ;z[h+88>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},La:c})},R=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=rb(b);O(a,c,b);return c},sb=[],S=(a,b)=>{sb[a>>>=0]=b},T=a=>{if(a)return sb[a>>>
0]},U=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?J(b,a):"";if(0===a)return""},tb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),ub=(a,b)=>{function c(d,e){z[b+e>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);
c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);
c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.Lb&&c("maxImmediateSize",148)},vb=["binding-not-used",,"uniform","storage","read-only-storage"],wb=[,"opaque","premultiplied","unpremultiplied","inherit"],
xb=[,"compatibility","core"],yb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",
20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},zb=[,"load","clear"],Ab=[,"low-power","high-performance"],Bb=[,"srgb","display-p3"],Cb=["binding-not-used",,"filtering","non-filtering","comparison"],Db=["binding-not-used",,"write-only","read-only","read-write"],Eb=[,"store","discard"],Fb=[,"all","stencil-only","depth-only"],Gb=[,"1d","2d","3d"],V=[,"r8unorm",
"r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint",
"stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm",
"eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb",
"astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],Hb=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],Ib=[,"1d","2d","2d-array","cube","cube-array","3d"],Jb=[,"standard","extended"],Kb={undefined:1,unknown:1,destroyed:2},Lb={rgba8unorm:22,bgra8unorm:27},Mb=a=>{var b=W();a();X(b)};f.requestAnimationFrame=Na;f.pauseMainLoop=$a;f.resumeMainLoop=function(){Ra++;var a=Ja,b=Ka,c=F;F=null;Za(c,0,!1,Sa,!0);Qa(a,b);G()};f.preMainLoop&&Xa.push(f.preMainLoop);
f.postMainLoop&&Ya.push(f.postMainLoop);f.noExitRuntime&&(Ca=f.noExitRuntime);f.printErr&&(g=f.printErr);f.wasmBinary&&(p=f.wasmBinary);f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);
var Nb,Ob,Pb,Qb,Rb,Sb,P,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,Y,bc,cc,dc,X,rb,W,ec={L:()=>sa(""),I:()=>{Ca=!1;Da=0},J:(a,b)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!b)return 0;var c=setTimeout(()=>{delete E[a];Ia(()=>dc(a,performance.now()))},b);E[a]={id:c,Ub:b};return 0},ba:()=>{$a();F=null},B:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,D:(a,b,c)=>{a=K(a);if(!a)return-4;a=cb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},ca:()=>performance.now(),ia:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}
return requestAnimationFrame(c)},K:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ra();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},i:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),A:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},j:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),h:(a,b,c,d)=>{if(!M.fullscreenEnabled())return-1;
a=K(a);if(!a)return-4;jb(a,b,c,d,"webkitfullscreenchange");return jb(a,b,c,d,"fullscreenchange")},s:(a,b,c,d)=>kb(a,b,c,d,2,"keydown"),q:(a,b,c,d)=>kb(a,b,c,d,1,"keypress"),r:(a,b,c,d)=>kb(a,b,c,d,3,"keyup"),ja:(a,b,c)=>{a=L(a);Za(a,b,c)},y:(a,b,c,d)=>Q(a,b,c,d,5,"mousedown"),v:(a,b,c,d)=>Q(a,b,c,d,33,"mouseenter"),u:(a,b,c,d)=>Q(a,b,c,d,34,"mouseleave"),w:(a,b,c,d)=>Q(a,b,c,d,8,"mousemove"),x:(a,b,c,d)=>Q(a,b,c,d,6,"mouseup"),l:(a,b,c,d)=>document.body?.requestPointerLock?(a=K(a))?mb(a,b,c,d):-4:
-1,k:(a,b,c,d)=>document.body?.requestPointerLock?(a=K(a))?nb(a,b,c,d):-4:-1,C:(a,b,c,d)=>ob(a,b,c,d),m:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),n:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),o:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),p:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),t:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?qb(a,b,c,d):-1:-4,Q:function(a,b,c,d,e,h){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=T(a);var k={};if(h){var m=A[h+
12>>2];if(m){var n=A[h+16>>2];k.requiredFeatures=Array.from(A.subarray(n>>2,n+4*m>>2),l=>yb[l])}var r=A[h+20>>2];if(r){var v={};function l(w,y,Pa=!1){y=A[r+y>>2];4294967295==y||Pa&&0==y||(v[w]=y)}function t(w,y){y=r+y;var Pa=A[y+4>>2];if(4294967295!=A[y>>2]||4294967295!=Pa)v[w]=4294967296*A[y+4>>2]+A[y>>2]}l("maxTextureDimension1D",4);l("maxTextureDimension2D",8);l("maxTextureDimension3D",12);l("maxTextureArrayLayers",16);l("maxBindGroups",20);l("maxBindGroupsPlusVertexBuffers",24);l("maxDynamicUniformBuffersPerPipelineLayout",
32);l("maxDynamicStorageBuffersPerPipelineLayout",36);l("maxSampledTexturesPerShaderStage",40);l("maxSamplersPerShaderStage",44);l("maxStorageBuffersPerShaderStage",48);l("maxStorageTexturesPerShaderStage",52);l("maxUniformBuffersPerShaderStage",56);l("minUniformBufferOffsetAlignment",80);l("minStorageBufferOffsetAlignment",84);t("maxUniformBufferBindingSize",64);t("maxStorageBufferBindingSize",72);l("maxVertexBuffers",88);t("maxBufferSize",96);l("maxVertexAttributes",104);l("maxVertexBufferArrayStride",
108);l("maxInterStageShaderVariables",112);l("maxColorAttachments",116);l("maxColorAttachmentBytesPerSample",120);l("maxComputeWorkgroupStorageSize",124);l("maxComputeInvocationsPerWorkgroup",128);l("maxComputeWorkgroupSizeX",132);l("maxComputeWorkgroupSizeY",136);l("maxComputeWorkgroupSizeZ",140);l("maxComputeWorkgroupsPerDimension",144);l("maxImmediateSize",148,!0);k.requiredLimits=v}if(m=A[h+24>>2])m={label:U(m+4)},k.defaultQueue=m;k.label=U(h+4)}a.requestDevice(k).then(l=>{S(e,l.queue);S(d,l);
c&&l.lost.then(t=>{l.onuncapturederror=()=>{};var w=W(),y=R(t.message);ac(c,Kb[t.reason],y);X(w)});l.onuncapturederror=t=>{var w=5;t.error instanceof GPUValidationError?w=2:t.error instanceof GPUOutOfMemoryError?w=3:t.error instanceof GPUInternalError&&(w=4);var y=W();t=R(t.error.message);cc(d,w,t);X(y)};bc(b,1,d,0)},l=>{var t=W();l=R(l.message);bc(b,3,d,l);c&&ac(c,4,l);X(t)})},a:a=>{delete sb[a]},O:(a,b,c)=>{var d=!!A[b+32>>2];b={label:U(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>
2],mappedAtCreation:d};a=T(a);try{var e=a.createBuffer(b)}catch(h){return!1}S(c,e);return!0},R:a=>{a=T(a);a.onuncapturederror=null;a.destroy()},M:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return Lb[a]},N:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var e={featureLevel:xb[A[c+4>>2]],powerPreference:Ab[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(e.Xb=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(e).then(h=>{if(h)S(d,h),Y(b,
1,d,0);else{h=W();var k=R("WebGPU not available on this browser (requestAdapter returned null)");Y(b,3,d,k);X(h)}},h=>{var k=W();h=R(h.message);Y(b,4,d,h);X(k)}):(e=W(),a=R("WebGPU not available on this browser (navigator.gpu is not available)"),Y(b,3,d,a),X(e))},H:Fa,na:function(){f.sb=a=>{0!=Ob()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.sb)},ga:function(){f.xb=a=>{const b=a.clipboardData.getData("text");Mb(()=>{const c=R(b);Nb(c)})};window.addEventListener("paste",
f.xb)},da:function(){f.Rb=[];f.tb=b=>{b.stopPropagation();b.preventDefault()};f.ub=b=>{b.stopPropagation();b.preventDefault()};f.vb=b=>{b.stopPropagation();b.preventDefault()};f.wb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Sb=c;Pb(c.length);for(let e=0;e<c.length;e++)Mb(()=>{const h=R(c[e].name);Qb(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Rb(b.clientX,b.clientY,d)};const a=f.Oa;a.addEventListener("dragenter",f.tb,!1);a.addEventListener("dragleave",
f.ub,!1);a.addEventListener("dragover",f.vb,!1);a.addEventListener("drop",f.wb,!1)},la:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},F:function(a){f.Va&&(URL.revokeObjectURL(f.Va[a].Cb),f.Va[a]=null)},P:function(a,b){0!==b&&(document.title=b?J(b):"");a=a?J(a):"";void 0!==f.canvas&&("object"===typeof f.canvas?bb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.Oa=K(a);f.Oa||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);f.Oa.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},ma:function(){window.removeEventListener("beforeunload",f.sb)},ea:function(){window.removeEventListener("paste",f.xb)},Y:function(){const a=f.Oa;a.removeEventListener("dragenter",f.tb);a.removeEventListener("dragleave",f.ub);a.removeEventListener("dragover",f.vb);a.removeEventListener("drop",f.wb)},d:function(){f.Oa&&f.Oa.requestPointerLock&&f.Oa.requestPointerLock()},G:function(a,b,c){if(f.Oa){if(0===
b)a="none";else if(0!=c)a=f.Va[a].Eb;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.Oa.style.cursor=a}},ka:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,
b);h.data.set(x.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},E:function(a,b){b=b?J(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},c:(a,b)=>T(a).features.has(yb[b]),X:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=U(b+4);for(var e=A[b+12>>2],h=A[b+16>>2],k=[],
m=0;m<e;++m){var n=k,r=n.push;var v=h+56*m;var l=A[v+4>>2];if(0!==l){var t=z[v+8>>2];-1==t&&(t=void 0);var w=v+24;v={view:T(l),depthSlice:t,resolveTarget:T(A[v+12>>2]),clearValue:{r:B[w>>3],g:B[w+8>>3],b:B[w+16>>3],a:B[w+24>>3]},loadOp:zb[A[v+16>>2]],storeOp:Eb[A[v+20>>2]]}}else v=void 0;r.call(n,v)}e=A[b+20>>2];e=0!==e?{view:T(A[e+4>>2]),depthClearValue:pa[e+16>>2],depthLoadOp:zb[A[e+8>>2]],depthStoreOp:Eb[A[e+12>>2]],depthReadOnly:!!A[e+20>>2],stencilClearValue:A[e+32>>2],stencilLoadOp:zb[A[e+24>>
2]],stencilStoreOp:Eb[A[e+28>>2]],stencilReadOnly:!!A[e+36>>2]}:void 0;h=A[b+28>>2];h=0!==h?{querySet:T(A[h+4>>2]),beginningOfPassWriteIndex:A[h+8>>2],endOfPassWriteIndex:A[h+12>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:e,occlusionQuerySet:T(A[b+24>>2]),timestampWrites:h,maxDrawCount:d};a=T(a);d=Xb(0);S(d,a.beginRenderPass(b));return d},U:a=>{a=T(a);var b=Vb(0);S(b,a.finish());return b},V:a=>{T(a).end()},_:(a,b)=>{var c=U(b+4),d=T(A[b+12>>2]),e=A[b+16>>2];b=A[b+20>>2];for(var h=
[],k=0;k<e;++k){var m=h,n=m.push;var r=b+40*k;var v=A[r+8>>2],l=A[r+32>>2],t=A[r+36>>2],w=A[r+4>>2];v?(l=r+24,l=A[l>>2]+4294967296*z[l+4>>2],-1==l&&(l=void 0),r={binding:w,resource:{buffer:T(v),offset:4294967296*A[r+4+16>>2]+A[r+16>>2],size:l}}):r=l?{binding:w,resource:T(l)}:{binding:w,resource:T(t)};n.call(m,r)}c={label:c,layout:d,entries:h};a=T(a);d=Tb(0);S(d,a.createBindGroup(c));return d},$:(a,b)=>{var c=U(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var e=[],h=0;h<d;++h){var k=e,m=k.push,n=b+88*h,r=A[n+
4>>2],v=A[n+8>>2];var l=n+24;var t=A[l+4>>2];l=t?{type:vb[t],hasDynamicOffset:!!A[l+8>>2],minBindingSize:4294967296*A[l+4+16>>2]+A[l+16>>2]}:void 0;t=(t=A[n+48+4>>2])?{type:Cb[t]}:void 0;var w=n+56;var y=A[w+4>>2];w=y?{sampleType:Hb[y],viewDimension:Ib[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;n+=72;n=(y=A[n+4>>2])?{access:Db[y],format:V[A[n+8>>2]],viewDimension:Ib[A[n+12>>2]]}:void 0;m.call(k,{binding:r,visibility:v,buffer:l,sampler:t,texture:w,storageTexture:n})}c={label:c,entries:e};a=T(a);
d=Ub(0);S(d,a.createBindGroupLayout(c));return d},g:(a,b)=>{var c;b&&(c={label:U(b+4)});a=T(a);b=Wb(0);S(b,a.createCommandEncoder(c));return b},z:(a,b)=>{var c={label:U(b+4),size:tb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:Gb[A[b+24>>2]],format:V[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),e=>V[e]));a=T(a);d=Zb(0);S(d,a.createTexture(c));return d},Z:(a,b)=>{ub(T(a).limits,b);return 1},b:(a,b)=>T(a).features.has(yb[b]),
ha:(a,b)=>{a=K(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Tb=U(b+4);b=Yb(0);S(b,a);return b},T:(a,b,c)=>{a=T(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>T(d));a.submit(b)},S:function(a,b,c,d,e){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);T(a).writeBuffer(T(b),c,x.subarray(d,d+e),0,e)},W:a=>{T(a).end()},f:(a,b,c,d,e)=>{a=T(a);c=T(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,e>>2,d)},fa:(a,b)=>{var c=A[b+4>>2];a=T(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=
d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:T(c),format:V[A[b+8>>2]],usage:A[b+16>>2],alphaMode:wb[A[b+40>>2]]};if(d=A[b+32>>2]){var e=A[b+36>>2];c.viewFormats=Array.from(z.subarray(e>>2,e+4*d>>2),h=>V[h])}b=A[b>>2];0!==b&&(c.colorSpace=Bb[A[b+8>>2]],c.Vb={mode:Jb[A[b+12>>2]]});a.configure(c)},aa:(a,b)=>{a=T(a);try{var c=Zb(0);S(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},e:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:U(b+4),format:V[A[b+12>>
2]],dimension:Ib[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Fb[A[b+36>>2]]}}a=T(a);b=$b(0);S(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;na=Z.oa;ra();eb=Z.cb;c=Z;f.__sapp_emsc_onpaste=Nb=c.qa;f.__sapp_html5_get_ask_leave_site=Ob=c.ra;f.__sapp_emsc_begin_drop=Pb=c.sa;f.__sapp_emsc_drop=Qb=c.ta;f.__sapp_emsc_end_drop=Rb=c.ua;f.__sapp_emsc_invoke_fetch_cb=c.va;f.__sapp_emsc_set_fullscreen_flag=c.wa;f._main=Sb=c.xa;f.__saudio_emsc_pull=c.ya;f.__sfetch_emsc_head_response=c.za;f.__sfetch_emsc_get_response=c.Aa;f.__sfetch_emsc_failed_http_status=c.Ba;f.__sfetch_emsc_failed_buffer_too_small=c.Ca;
f.__sfetch_emsc_failed_other=c.Da;P=c.Ea;Tb=c.Fa;Ub=c.Ga;Vb=c.Ha;Wb=c.Ia;Xb=c.Pa;Yb=c.Sa;Zb=c.Ta;$b=c.Ua;ac=c._a;Y=c.$a;bc=c.ab;cc=c.bb;dc=c.db;X=c.eb;rb=c.fb;W=c.gb;C--;f.monitorRunDependencies?.(C);0==C&&D&&(c=D,D=null,c());return Z}C++;f.monitorRunDependencies?.(C);var b={a:ec};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=f.locateFile?f.locateFile("clear-sapp.wasm",ia):ia+"clear-sapp.wasm";return a((await wa(b)).instance)})();
function fc(a=[]){var b=Sb;a.unshift(ea);var c=a.length,d=rb(4*(c+1)),e=d;a.forEach(k=>{A[e>>2]=R(k);e+=4});A[e>>2]=0;try{var h=b(c,d);Ga(h)}catch(k){Ea(k)}}
function gc(a=da){function b(){f.calledRun=!0;if(!q){Z.pa();f.onRuntimeInitialized?.();f.noInitialRun||fc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();za.push(c)}ya(za)}}if(0<C)D=gc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ba();ya(Aa);0<C?D=gc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();gc();
