var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var k=console.error.bind(console),m,p=!1,ma,la=a=>a.startsWith("file://"),t,w,na,z,A,oa,B,pa;
function qa(){var a=ra.buffer;t=new Int8Array(a);na=new Int16Array(a);w=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);oa=new Float32Array(a);B=new Float64Array(a);pa=new BigInt64Array(a);new BigUint64Array(a)}function sa(a){f.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(f)},za=[],Aa=[],Ba=()=>{var a=f.preRun.shift();Aa.push(a)},C=0,D=null,Ca=!0,Da=0,E={},Ea=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Fa=a=>{ma=a;Ca||0<Da||(f.onExit?.(a),p=!0);fa(a,new xa(a))},Ga=()=>{if(!(Ca||0<Da))try{var a=ma;ma=a;Fa(a)}catch(b){Ea(b)}},F=a=>{if(!p)try{a(),Ga()}catch(b){Ea(b)}},Oa=(a,b)=>{Ha=a;Ia=b;if(G)if(Ja||=!0,0==a)H=function(){setTimeout(I,Math.max(0,Ka+b-performance.now())|0)};else if(1==a)H=function(){La(I)};else if(2==a){if(!Ma)if(globalThis.setImmediate)Ma=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ma=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}H=function(){Ma(I)}}},Xa=(a,b,c,d,e)=>{function g(){return h<Pa?(Ga(),!1):!0}G=a;Qa=d;var h=Pa;Ja=!1;I=function(){if(!p)if(0<Ra.length){var l=Ra.shift();l.Mb(l.Db);if(Sa){var q=
Sa,u=0==q%1?q-1:Math.floor(q);Sa=l.Gb?u:(8*q+(u+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",q=Sa??0,u=Ta.Lb??0,q?q<u?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));g()&&setTimeout(I,0)}else if(g())if(Ua=Ua+1|0,1==Ha&&1<Ia&&0!=Ua%Ia)H();else{0==Ha&&(Ka=performance.now());a:if(!p){for(l of Va)if(!1===l())break a;F(a);for(q of Wa)q()}g()&&H()}};e||(0<b?Oa(0,1E3/b):Oa(1,1),H());if(c)throw"unwind";},Ja=!1,H=null,Pa=0,G=null,Qa=0,Ha=0,Ia=0,Ua=0,
Ra=[],Va=[],Wa=[];function Ya(){H=null;Pa++}var J=0;function La(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===J)J=b+1E3/60;else for(;b+2>=J;)J+=1E3/60;setTimeout(a,Math.max(J-b,0))}}
var Ta={},Ka,I,Ma,Sa,Za=globalThis.TextDecoder&&new TextDecoder,K=(a=0,b)=>{var c=w;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&Za)return Za.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))b+=String.fromCharCode((e&31)<<6|g);else{var h=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|c[a++]&63;65536>e?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},
$a=[0,globalThis.document??0,globalThis.window??0],L=a=>{a=2<a?a?K(a):"":a;return $a[a]||globalThis.document?.querySelector(a)},ab=a=>0>$a.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},bb=[],M=a=>{var b=bb[a];b||(bb[a]=b=cb.get(a));return b};function db(a){var b=N.Ga[a];b.target.removeEventListener(b.Ha,b.rb,b.Na);N.Ga.splice(a,1)}function eb(){if(navigator.userActivation?navigator.userActivation.isActive:N.jb&&N.Bb.Ya){var a=N.Sa;N.Sa=[];for(var b of a)b.mb(...b.qb)}}
function O(a){if(!a.target)return-4;if(a.La)a.rb=function(c){++N.jb;N.Bb=a;eb();a.Pa(c);eb();--N.jb},a.target.addEventListener(a.Ha,a.rb,a.Na),N.Ga.push(a);else for(var b=0;b<N.Ga.length;++b)N.Ga[b].target==a.target&&N.Ga[b].Ha==a.Ha&&db(b--);return 0}function fb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var N={Eb:0,Nb:0,kb:0,Wa:0,pb:0,ob:0,Za:0,Kb:0,Pb:0,Jb:0,ib:0,lb:0,Zb:0,nb:0,Qb(){for(;N.Ga.length;)db(N.Ga.length-1);N.Sa=[]},jb:0,Sa:[],Ib(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var l in g)if(g[l]!=h[l])return!1;return!0}for(var e of N.Sa)if(e.mb==a&&d(e.qb,c))return;N.Sa.push({mb:a,ub:b,qb:c});N.Sa.sort((g,h)=>g.ub<h.ub)},Sb(a){N.Sa=N.Sa.filter(b=>b.mb!=a)},Ga:[],Rb:(a,b)=>{for(var c=0;c<N.Ga.length;++c)N.Ga[c].target!=a||b&&b!=N.Ga[c].Ha||db(c--)},Tb(a){let b=!1;for(let c=0;c<
N.Ga.length;++c){const d=N.Ga[c];d.target===a.target&&d.Ma===a.Ma&&d.La===a.La&&d.Oa===a.Oa&&(db(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},P=(a,b,c)=>{var d=w;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var g=a.codePointAt(e);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;
d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;e++}}d[b]=0}},gb=(a,b,c,d,e,g)=>{N.Za||(N.Za=Q(256));a={target:L(a),Ha:g,Ma:e,Oa:b,La:d,Pa:h=>{var l=h.target.id?h.target.id:"",q=N.Za;P(fb(h.target),q+0,128);P(l,q+128,128);M(d)(e,q,b)&&h.preventDefault()},Na:c};return O(a)},hb=(a,b,c,d,e)=>{N.ib||(N.ib=Q(276));return O({target:a,Ha:e,Ma:19,Oa:b,La:d,Pa:g=>{var h=N.ib,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,q=!!l;t[h]=q;t[h+1]=N.fullscreenEnabled();var u=q?l:N.Cb,v=u?.id||"";P(fb(u),h+2,128);P(v,h+130,128);z[h+260>>2]=u?u.clientWidth:0;z[h+264>>2]=u?u.clientHeight:0;z[h+268>>2]=screen.width;z[h+272>>2]=screen.height;q&&(N.Cb=l);M(d)(19,h,b)&&g.preventDefault()},Na:c})},ib=(a,b,c,d,e,g)=>{N.kb||(N.kb=Q(160));a={target:L(a),Ha:g,Ma:e,Oa:b,La:d,Pa:h=>{var l=N.kb;B[l>>3]=h.timeStamp;var q=l>>2;z[q+2]=h.location;t[l+12]=h.ctrlKey;t[l+13]=h.shiftKey;t[l+14]=h.altKey;t[l+15]=h.metaKey;
t[l+16]=h.repeat;z[q+5]=h.charCode;z[q+6]=h.keyCode;z[q+7]=h.which;P(h.key||"",l+32,32);P(h.code||"",l+64,32);P(h.char||"",l+96,32);P(h.locale||"",l+128,32);M(d)(e,l,b)&&h.preventDefault()},Na:c};return O(a)},jb=(a,b,c)=>{B[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;na[2*d+14]=b.button;na[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=ab(c);z[d+10]=b.clientX-(a.left|
0);z[d+11]=b.clientY-(a.top|0)},R=(a,b,c,d,e,g)=>{N.Wa||(N.Wa=Q(64));a=L(a);return O({target:a,Ya:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Ha:g,Ma:e,Oa:b,La:d,Pa:h=>{jb(N.Wa,h,a);M(d)(e,N.Wa,b)&&h.preventDefault()},Na:c})},kb=(a,b,c,d)=>{N.lb||(N.lb=Q(257));return O({target:a,Ha:"pointerlockchange",Ma:20,Oa:b,La:d,Pa:e=>{var g=N.lb,h=document.pointerLockElement;t[g]=!!h;var l=h?.id||"";P(fb(h),g+1,128);P(l,g+129,128);M(d)(20,g,b)&&e.preventDefault()},Na:c})},lb=(a,b,c,d)=>O({target:a,Ha:"pointerlockerror",
Ma:38,Oa:b,La:d,Pa:e=>{M(d)(38,0,b)&&e.preventDefault()},Na:c}),mb=(a,b,c,d)=>{N.ob||(N.ob=Q(36));a=L(a);return O({target:a,Ha:"resize",Ma:10,Oa:b,La:d,Pa:e=>{if(e.target==a){var g=document.body;if(g){var h=N.ob;z[h>>2]=0;z[h+4>>2]=g.clientWidth;z[h+8>>2]=g.clientHeight;z[h+12>>2]=innerWidth;z[h+16>>2]=innerHeight;z[h+20>>2]=outerWidth;z[h+24>>2]=outerHeight;z[h+28>>2]=pageXOffset|0;z[h+32>>2]=pageYOffset|0;M(d)(10,h,b)&&e.preventDefault()}}},Na:c})},nb=(a,b,c,d,e,g)=>{N.nb||(N.nb=Q(1552));a=L(a);
return O({target:a,Ya:"touchstart"==g||"touchend"==g,Ha:g,Ma:e,Oa:b,La:d,Pa:h=>{var l={},q=h.touches;for(var u of q)u.sb=u.tb=0,l[u.identifier]=u;for(var v of h.changedTouches)v.sb=1,l[v.identifier]=v;for(var n of h.targetTouches)l[n.identifier].tb=1;q=N.nb;B[q>>3]=h.timeStamp;t[q+12]=h.ctrlKey;t[q+13]=h.shiftKey;t[q+14]=h.altKey;t[q+15]=h.metaKey;u=q+16;v=ab(a);n=0;for(let r of Object.values(l))if(l=u>>2,z[l]=r.identifier,z[l+1]=r.screenX,z[l+2]=r.screenY,z[l+3]=r.clientX,z[l+4]=r.clientY,z[l+5]=
r.pageX,z[l+6]=r.pageY,t[u+28]=r.sb,t[u+29]=r.tb,z[l+8]=r.clientX-(v.left|0),z[l+9]=r.clientY-(v.top|0),u+=48,31<++n)break;z[q+8>>2]=n;M(d)(e,q,b)&&h.preventDefault()},Na:c})},ob=(a,b,c,d)=>{N.pb||(N.pb=Q(96));return O({target:a,Ya:!0,Ha:"wheel",Ma:9,Oa:b,La:d,Pa:e=>{var g=N.pb;jb(g,e,a);B[g+64>>3]=e.deltaX;B[g+72>>3]=e.deltaY;B[g+80>>3]=e.deltaZ;z[g+88>>2]=e.deltaMode;M(d)(9,g,b)&&e.preventDefault()},Na:c})},S=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=
d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=pb(b);P(a,c,b);return c},T=[],qb=(a,b)=>{T[a>>>0]=b},U=a=>{if(a)return T[a>>>0]},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?K(b,a):"";if(0===a)return""},rb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),sb=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},tb=(a,b)=>{function c(d,e){z[b+e>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",
12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);
pa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);pa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);pa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",
140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.Ob&&c("maxImmediateSize",148)},ub=[,"opaque","premultiplied","unpremultiplied","inherit"],vb=[,"compatibility","core"],wb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",
13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},xb=[,"load","clear"],yb=[,"low-power","high-performance"],zb=[,"srgb","display-p3"],Ab=[,"store","discard"],Bb=[,"all","stencil-only",
"depth-only"],Cb=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint",
"rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm",
"etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb",
"astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],Db=[,"1d","2d","2d-array","cube","cube-array","3d"],Eb=[,"standard","extended"],Fb={undefined:1,unknown:1,destroyed:2},Gb={rgba8unorm:22,bgra8unorm:27},Hb=a=>{var b=X();a();Y(b)};f.requestAnimationFrame=La;f.pauseMainLoop=Ya;f.resumeMainLoop=function(){Pa++;var a=Ha,b=Ia,c=G;G=null;Xa(c,0,!1,Qa,!0);Oa(a,b);H()};f.preMainLoop&&Va.push(f.preMainLoop);f.postMainLoop&&Wa.push(f.postMainLoop);
f.noExitRuntime&&(Ca=f.noExitRuntime);f.printErr&&(k=f.printErr);f.wasmBinary&&(m=f.wasmBinary);f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
var Ib,Jb,Kb,Lb,Mb,Nb,Q,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Z,Wb,Xb,Yb,Y,pb,X,ra,cb,Zb={L:()=>sa(""),I:()=>{Ca=!1;Da=0},J:(a,b)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!b)return 0;var c=setTimeout(()=>{delete E[a];F(()=>Yb(a,performance.now()))},b);E[a]={id:c,Xb:b};return 0},ba:()=>{Ya();G=null},B:()=>globalThis.devicePixelRatio??1,D:(a,b,c)=>{a=L(a);if(!a)return-4;a=ab(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},ca:()=>performance.now(),ja:(a,b)=>{function c(d){M(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
K:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);qa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},i:(a,b,c,d)=>gb(a,b,c,d,12,"blur"),A:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},j:(a,b,c,d)=>gb(a,b,c,d,13,"focus"),h:(a,b,c,d)=>{if(!N.fullscreenEnabled())return-1;a=L(a);if(!a)return-4;
hb(a,b,c,d,"webkitfullscreenchange");return hb(a,b,c,d,"fullscreenchange")},s:(a,b,c,d)=>ib(a,b,c,d,2,"keydown"),q:(a,b,c,d)=>ib(a,b,c,d,1,"keypress"),r:(a,b,c,d)=>ib(a,b,c,d,3,"keyup"),ka:(a,b,c)=>{a=M(a);Xa(a,b,c)},y:(a,b,c,d)=>R(a,b,c,d,5,"mousedown"),v:(a,b,c,d)=>R(a,b,c,d,33,"mouseenter"),u:(a,b,c,d)=>R(a,b,c,d,34,"mouseleave"),w:(a,b,c,d)=>R(a,b,c,d,8,"mousemove"),x:(a,b,c,d)=>R(a,b,c,d,6,"mouseup"),l:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?kb(a,b,c,d):-4:-1,k:(a,b,c,d)=>document.body?.requestPointerLock?
(a=L(a))?lb(a,b,c,d):-4:-1,C:(a,b,c,d)=>mb(a,b,c,d),m:(a,b,c,d)=>nb(a,b,c,d,25,"touchcancel"),n:(a,b,c,d)=>nb(a,b,c,d,23,"touchend"),o:(a,b,c,d)=>nb(a,b,c,d,24,"touchmove"),p:(a,b,c,d)=>nb(a,b,c,d,22,"touchstart"),t:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?ob(a,b,c,d):-1:-4,P:function(a,b,c,d,e,g){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);var h={};if(g){var l=A[g+12>>2];if(l){var q=A[g+16>>2];h.requiredFeatures=
Array.from(A.subarray(q>>2,q+4*l>>2),n=>wb[n])}var u=A[g+20>>2];if(u){var v={};function n(x,y,Na=!1){y=A[u+y>>2];4294967295==y||Na&&0==y||(v[x]=y)}function r(x,y){y=u+y;var Na=A[y+4>>2];if(4294967295!=A[y>>2]||4294967295!=Na)v[x]=4294967296*A[y+4>>2]+A[y>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",8);n("maxTextureDimension3D",12);n("maxTextureArrayLayers",16);n("maxBindGroups",20);n("maxBindGroupsPlusVertexBuffers",24);n("maxDynamicUniformBuffersPerPipelineLayout",32);n("maxDynamicStorageBuffersPerPipelineLayout",
36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);r("maxUniformBufferBindingSize",64);r("maxStorageBufferBindingSize",72);n("maxVertexBuffers",88);r("maxBufferSize",96);n("maxVertexAttributes",104);n("maxVertexBufferArrayStride",108);n("maxInterStageShaderVariables",112);
n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",148,!0);h.requiredLimits=v}if(l=A[g+24>>2])l={label:V(l+4)},h.defaultQueue=l;h.label=V(g+4)}a.requestDevice(h).then(n=>{F(()=>{T[e>>>0]=n.queue;T[d>>>0]=n;n.lost.then(r=>{F(()=>{n.onuncapturederror=
()=>{};var x=X(),y=S(r.message);Vb(c,Fb[r.reason],y);Y(x)})});n.onuncapturederror=r=>{var x=5;r.error instanceof GPUValidationError?x=2:r.error instanceof GPUOutOfMemoryError?x=3:r.error instanceof GPUInternalError&&(x=4);var y=X();r=S(r.error.message);Xb(d,x,r);Y(y)};Wb(b,1,d,0)})},n=>{F(()=>{var r=X(),x=S(n.message);Wb(b,3,d,x);c&&Vb(c,4,x);Y(r)})})},a:a=>{delete T[a]},O:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);
try{var e=a.createBuffer(b)}catch(g){return!1}T[c>>>0]=e;return!0},R:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},M:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return Gb[a]},N:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var e={featureLevel:vb[A[c+4>>2]],powerPreference:yb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(e.$b=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(e).then(g=>{F(()=>{if(g)T[d>>>0]=g,Z(b,1,d,0);else{var h=
X(),l=S("WebGPU not available on this browser (requestAdapter returned null)");Z(b,3,d,l);Y(h)}})},g=>{F(()=>{var h=X(),l=S(g.message);Z(b,4,d,l);Y(h)})}):(e=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Z(b,3,d,a),Y(e))},H:Fa,oa:function(){f.vb=a=>{0!=Jb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.vb)},ha:function(){f.Ab=a=>{const b=a.clipboardData.getData("text");Hb(()=>{const c=S(b);Ib(c)})};window.addEventListener("paste",
f.Ab)},da:function(){f.Ub=[];f.wb=b=>{b.stopPropagation();b.preventDefault()};f.xb=b=>{b.stopPropagation();b.preventDefault()};f.yb=b=>{b.stopPropagation();b.preventDefault()};f.zb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Vb=c;Kb(c.length);for(let e=0;e<c.length;e++)Hb(()=>{const g=S(c[e].name);Lb(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Mb(b.clientX,b.clientY,d)};const a=f.Ra;a.addEventListener("dragenter",f.wb,!1);a.addEventListener("dragleave",
f.xb,!1);a.addEventListener("dragover",f.yb,!1);a.addEventListener("drop",f.zb,!1)},ma:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},F:function(a){f.Xa&&(URL.revokeObjectURL(f.Xa[a].Fb),f.Xa[a]=null)},Q:function(a,b){0!==b&&(document.title=b?K(b):"");a=a?K(a):"";void 0!==f.canvas&&("object"===typeof f.canvas?$a[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.Ra=L(a);f.Ra||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);f.Ra.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},na:function(){window.removeEventListener("beforeunload",f.vb)},ea:function(){window.removeEventListener("paste",f.Ab)},Y:function(){const a=f.Ra;a.removeEventListener("dragenter",f.wb);a.removeEventListener("dragleave",f.xb);a.removeEventListener("dragover",f.yb);a.removeEventListener("drop",f.zb)},d:function(){f.Ra&&f.Ra.requestPointerLock&&f.Ra.requestPointerLock()},G:function(a,b,c){if(f.Ra){if(0===
b)a="none";else if(0!=c)a=f.Xa[a].Hb;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.Ra.style.cursor=a}},la:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,
b);g.data.set(w.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},E:function(a,b){b=b?K(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},fa:(a,b)=>{tb(U(a).limits,b);return 1},c:(a,b)=>U(a).features.has(wb[b]),Z:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:sb(A[b+12>>2])});b=U(a);a=Qb(0);c=
b.beginComputePass(c);T[a>>>0]=c;return a},X:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var e=A[b+12>>2],g=A[b+16>>2],h=[],l=0;l<e;++l){var q=h,u=q.push;var v=g+56*l;var n=A[v+4>>2];if(0!==n){var r=z[v+8>>2];-1==r&&(r=void 0);var x=v+24;v={view:U(n),depthSlice:r,resolveTarget:U(A[v+12>>2]),clearValue:{r:B[x>>3],g:B[x+8>>3],b:B[x+16>>3],a:B[x+24>>3]},loadOp:xb[A[v+16>>2]],storeOp:Ab[A[v+20>>2]]}}else v=void 0;u.call(q,v)}e=A[b+20>>2];e=0!==e?{view:U(A[e+
4>>2]),depthClearValue:oa[e+16>>2],depthLoadOp:xb[A[e+8>>2]],depthStoreOp:Ab[A[e+12>>2]],depthReadOnly:!!A[e+20>>2],stencilClearValue:A[e+32>>2],stencilLoadOp:xb[A[e+24>>2]],stencilStoreOp:Ab[A[e+28>>2]],stencilReadOnly:!!A[e+36>>2]}:void 0;b={label:c,colorAttachments:h,depthStencilAttachment:e,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:sb(A[b+28>>2]),maxDrawCount:d};d=U(a);a=Rb(0);b=d.beginRenderPass(b);T[a>>>0]=b;return a},U:a=>{var b=U(a);a=Ob(0);b=b.finish();T[a>>>0]=b;return a},V:a=>{U(a).end()},
g:(a,b,c,d,e)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,e>>2,d)},_:(a,b)=>{var c;b&&(c={label:V(b+4)});b=U(a);a=Pb(0);c=b.createCommandEncoder(c);T[a>>>0]=c;return a},z:(a,b)=>{var c={label:V(b+4),size:rb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:Cb[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),e=>W[e]));a=U(a);d=Tb(0);qb(d,a.createTexture(c));return d},$:(a,b)=>{tb(U(a).limits,
b);return 1},b:(a,b)=>U(a).features.has(wb[b]),ia:(a,b)=>{a=L(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Wb=V(b+4);b=Sb(0);T[b>>>0]=a;return b},T:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},S:function(a,b,c,d,e){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,w.subarray(d,d+e),0,e)},W:a=>{U(a).end()},f:(a,b,c,d,e)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,e>>2,d)},ga:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=
[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:ub[A[b+40>>2]]};if(d=A[b+32>>2]){var e=A[b+36>>2];c.viewFormats=Array.from(z.subarray(e>>2,e+4*d>>2),g=>W[g])}b=A[b>>2];0!==b&&(c.colorSpace=zb[A[b+8>>2]],c.Yb={mode:Eb[A[b+12>>2]]});a.configure(c)},aa:(a,b)=>{a=U(a);try{var c=Tb(0),d=a.getCurrentTexture();T[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(e){A[b+4>>2]=0,z[b+8>>2]=6}},e:(a,b)=>{if(b){var c=A[b+
24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:Db[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Bb[A[b+36>>2]]}}b=U(a);a=Ub(0);b=b.createView(c);T[a>>>0]=b;return a}};function $b(a=[]){var b=Nb;a.unshift(ea);var c=a.length,d=pb(4*(c+1)),e=d,g;for(g of a)A[e>>2]=S(g),e+=4;A[e>>2]=0;try{var h=b(c,d);ma=h;Fa(h)}catch(l){Ea(l)}}
function ac(a=da){function b(){f.calledRun=!0;if(!p){bc.qa();f.onRuntimeInitialized?.();f.noInitialRun||$b(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();za.push(c)}ya(za)}}if(0<C)D=ac;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ba();ya(Aa);0<C?D=ac:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}var bc;
(async function(){function a(c){c=bc=c.exports;Ib=f.__sapp_emsc_onpaste=c.ra;Jb=f.__sapp_html5_get_ask_leave_site=c.sa;Kb=f.__sapp_emsc_begin_drop=c.ta;Lb=f.__sapp_emsc_drop=c.ua;Mb=f.__sapp_emsc_end_drop=c.va;f.__sapp_emsc_invoke_fetch_cb=c.wa;f.__sapp_emsc_set_fullscreen_flag=c.xa;Nb=f._main=c.ya;f.__saudio_emsc_pull=c.za;f.__sfetch_emsc_head_response=c.Aa;f.__sfetch_emsc_get_response=c.Ba;f.__sfetch_emsc_failed_http_status=c.Ca;f.__sfetch_emsc_failed_buffer_too_small=c.Da;f.__sfetch_emsc_failed_other=
c.Ea;Q=c.Fa;Ob=c.Ia;Pb=c.Ja;Qb=c.Ka;Rb=c.Qa;Sb=c.Ta;Tb=c.Ua;Ub=c.Va;Vb=c.$a;Z=c.ab;Wb=c.bb;Xb=c.cb;Yb=c.eb;Y=c.fb;pb=c.gb;X=c.hb;ra=c.pa;cb=c.db;qa();C--;f.monitorRunDependencies?.(C);0==C&&D&&(c=D,D=null,c());return bc}C++;f.monitorRunDependencies?.(C);var b={a:Zb};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=f.locateFile?f.locateFile("clear-sapp.wasm",ia):ia+"clear-sapp.wasm";return a((await wa(b)).instance)})();ac();
