var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var h=console.error.bind(console),n,r=!1,ma,la=a=>a.startsWith("file://"),na,u,y,oa,z,A,pa,B,qa;
function ra(){var a=na.buffer;u=new Int8Array(a);oa=new Int16Array(a);y=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);pa=new Float32Array(a);B=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function sa(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(e)},za=[],Aa=[],Ba=()=>{var a=e.preRun.shift();Aa.push(a)},C=0,D=null,Ca=!0,Da=0,E={},Ea=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Fa=a=>{ma=a;Ca||0<Da||(e.onExit?.(a),r=!0);fa(a,new xa(a))},Ga=a=>{ma=a;Fa(a)},Ha=()=>{if(!(Ca||0<Da))try{var a=ma;ma=a;Fa(a)}catch(b){Ea(b)}},Ia=a=>{if(!r)try{a(),Ha()}catch(b){Ea(b)}},Pa=(a,b)=>{Ja=a;Ka=b;if(F)if(La||=!0,0==a)G=function(){setTimeout(H,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)G=function(){Na(H)};else if(2==
a){if("undefined"==typeof Oa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Oa=setImmediate;G=function(){Oa(H)}}},Za=(a,b,c,d,f)=>{function g(){return k<Ra?(Ha(),!1):!0}F=a;Sa=d;var k=Ra;La=!1;H=function(){if(!r)if(0<
Ta.length){var m=Ta.shift();m.ic(m.Zb);if(Ua){var p=Ua,t=0==p%1?p-1:Math.floor(p);Ua=m.bc?t:(8*p+(t+.5))/9}e.setStatus&&(m=e.statusMessage||"Please wait...",p=Ua??0,t=Va.hc??0,p?p<t?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(m):e.setStatus(""));g()&&setTimeout(H,0)}else if(g())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)G();else{0==Ja&&(Ma=performance.now());a:if(!r){for(m of Xa)if(!1===m())break a;Ia(a);for(p of Ya)p()}g()&&G()}};f||(0<b?Pa(0,1E3/b):Pa(1,1),G());if(c)throw"unwind";
},La=!1,G=null,Ra=0,F=null,Sa=0,Ja=0,Ka=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){G=null;Ra++}var J=0;function Na(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===J)J=b+1E3/60;else for(;b+2>=J;)J+=1E3/60;setTimeout(a,Math.max(J-b,0))}}
var Va={},Ma,H,Oa,Ua,ab="undefined"!=typeof TextDecoder?new TextDecoder:void 0,K=(a=0,b)=>{var c=y;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&ab)return ab.decode(c.subarray(a,d));for(b="";a<d;){var f=c[a++];if(f&128){var g=c[a++]&63;if(192==(f&224))b+=String.fromCharCode((f&31)<<6|g);else{var k=c[a++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|c[a++]&63;65536>f?b+=String.fromCharCode(f):(f-=65536,b+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else b+=String.fromCharCode(f)}return b},
bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],L=a=>{a=2<a?a?K(a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],eb,M=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=N.eb[a];b.target.removeEventListener(b.cb,b.Nb,b.hb);N.eb.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:N.Eb&&N.Xb.Bb){var a=N.ob;N.ob=[];for(var b of a)b.Ib(...b.Mb)}}function O(a){if(!a.target)return-4;if(a.lb)a.Nb=function(c){++N.Eb;N.Xb=a;gb();a.mb(c);gb();--N.Eb},a.target.addEventListener(a.cb,a.Nb,a.hb),N.eb.push(a);else for(var b=0;b<N.eb.length;++b)N.eb[b].target==a.target&&N.eb[b].cb==a.cb&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var N={$b:0,jc:0,Fb:0,pb:0,Lb:0,Kb:0,Cb:0,fc:0,mc:0,ec:0,Db:0,Gb:0,vc:0,Jb:0,lc(a,b,c){u.set(u.subarray(b,b+c),a)},nc(){for(;N.eb.length;)fb(N.eb.length-1);N.ob=[]},Eb:0,ob:[],dc(a,b,c){function d(g,k){if(g.length!=k.length)return!1;for(var m in g)if(g[m]!=k[m])return!1;return!0}for(var f of N.ob)if(f.Ib==a&&d(f.Mb,c))return;N.ob.push({Ib:a,Qb:b,Mb:c});N.ob.sort((g,k)=>g.Qb<k.Qb)},pc(a){N.ob=N.ob.filter(b=>b.Ib!=a)},eb:[],oc:(a,b)=>{for(var c=0;c<N.eb.length;++c)N.eb[c].target!=a||b&&b!=N.eb[c].cb||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},P=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0}},ib=(a,b,c,d,f,g)=>{N.Cb||
(N.Cb=Q(256));a={target:L(a),cb:g,lb:d,mb:(k=event)=>{var m=k.target.id?k.target.id:"",p=N.Cb;P(hb(k.target),p+0,128);P(m,p+128,128);M(d)(f,p,b)&&k.preventDefault()},hb:c};return O(a)},jb=(a,b,c,d,f)=>{N.Db||(N.Db=Q(276));return O({target:a,cb:f,lb:d,mb:(g=event)=>{var k=N.Db,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,p=!!m;u[k]=p;u[k+1]=N.fullscreenEnabled();var t=p?m:N.Yb,v=
t?.id||"";P(hb(t),k+2,128);P(v,k+130,128);z[k+260>>2]=t?t.clientWidth:0;z[k+264>>2]=t?t.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;p&&(N.Yb=m);M(d)(19,k,b)&&g.preventDefault()},hb:c})},kb=(a,b,c,d,f,g)=>{N.Fb||(N.Fb=Q(160));a={target:L(a),cb:g,lb:d,mb:k=>{var m=N.Fb;B[m>>3]=k.timeStamp;var p=m>>2;z[p+2]=k.location;u[m+12]=k.ctrlKey;u[m+13]=k.shiftKey;u[m+14]=k.altKey;u[m+15]=k.metaKey;u[m+16]=k.repeat;z[p+5]=k.charCode;z[p+6]=k.keyCode;z[p+7]=k.which;P(k.key||"",m+32,32);P(k.code||
"",m+64,32);P(k.char||"",m+96,32);P(k.locale||"",m+128,32);M(d)(f,m,b)&&k.preventDefault()},hb:c};return O(a)},lb=(a,b,c)=>{B[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=cb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},mb=(a,b,c,d,f,g)=>{N.pb||(N.pb=Q(64));a=L(a);return O({target:a,
Bb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,cb:g,lb:d,mb:(k=event)=>{lb(N.pb,k,a);M(d)(f,N.pb,b)&&k.preventDefault()},hb:c})},nb=(a,b,c,d)=>{N.Gb||(N.Gb=Q(257));return O({target:a,cb:"pointerlockchange",lb:d,mb:(f=event)=>{var g=N.Gb,k=document.pointerLockElement;u[g]=!!k;var m=k?.id||"";P(hb(k),g+1,128);P(m,g+129,128);M(d)(20,g,b)&&f.preventDefault()},hb:c})},ob=(a,b,c,d)=>O({target:a,cb:"pointerlockerror",lb:d,mb:(f=event)=>{M(d)(38,0,b)&&f.preventDefault()},hb:c}),pb=(a,b,c,d)=>{N.Kb||
(N.Kb=Q(36));a=L(a);return O({target:a,cb:"resize",lb:d,mb:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=N.Kb;z[k>>2]=0;z[k+4>>2]=g.clientWidth;z[k+8>>2]=g.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;M(d)(10,k,b)&&f.preventDefault()}}},hb:c})},qb=(a,b,c,d,f,g)=>{N.Jb||(N.Jb=Q(1552));a=L(a);return O({target:a,Bb:"touchstart"==g||"touchend"==g,cb:g,lb:d,mb:k=>{var m={},p=k.touches;
for(var t of p)t.Ob=t.Pb=0,m[t.identifier]=t;for(var v of k.changedTouches)v.Ob=1,m[v.identifier]=v;for(var l of k.targetTouches)m[l.identifier].Pb=1;p=N.Jb;B[p>>3]=k.timeStamp;u[p+12]=k.ctrlKey;u[p+13]=k.shiftKey;u[p+14]=k.altKey;u[p+15]=k.metaKey;t=p+16;v=cb(a);l=0;for(let q of Object.values(m))if(m=t>>2,z[m]=q.identifier,z[m+1]=q.screenX,z[m+2]=q.screenY,z[m+3]=q.clientX,z[m+4]=q.clientY,z[m+5]=q.pageX,z[m+6]=q.pageY,u[t+28]=q.Ob,u[t+29]=q.Pb,z[m+8]=q.clientX-(v.left|0),z[m+9]=q.clientY-(v.top|
0),t+=48,31<++l)break;z[p+8>>2]=l;M(d)(f,p,b)&&k.preventDefault()},hb:c})},rb=(a,b,c,d)=>{N.Lb||(N.Lb=Q(96));return O({target:a,Bb:!0,cb:"wheel",lb:d,mb:(f=event)=>{var g=N.Lb;lb(g,f,a);B[g+64>>3]=f.deltaX;B[g+72>>3]=f.deltaY;B[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;M(d)(9,g,b)&&f.preventDefault()},hb:c})},R=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=sb(b);P(a,c,b);return c},tb=[],T=(a,b)=>{tb[a>>>=0]=b},ub=[],U=a=>
{if(a)return tb[a>>>0]},vb=a=>{var b=A[a>>2];return b?K(b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?K(b,a):"";if(0===a)return""},wb=a=>({r:B[a>>3],g:B[a+8>>3],b:B[a+16>>3],a:B[a+24>>3]}),xb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),yb=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},zb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,g=vb(f+4);c[g]=B[f+16>>3]}return c}},Ab=a=>a?U(a):"auto",
Nb=a=>{function b(d){if(d)return{operation:Bb[A[d>>2]],srcFactor:Eb[A[d+4>>2]],dstFactor:Eb[A[d+8>>2]]}}function c(d){return{compare:Fb[A[d>>2]],failOp:Gb[A[d+4>>2]],depthFailOp:Gb[A[d+8>>2]],passOp:Gb[A[d+12>>2]]}}return{label:V(a+4),layout:Ab(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),g=zb(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var m=A[d+28>>2];if(k){for(var p=[],t=0;t<k;++t){var v=p,l=v.push;var q=m+24*t;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var I=null;else{I=4294967296*
A[q+4+8>>2]+A[q+8>>2];w=Hb[w];q=A[q+20>>2];for(var Cb=[],Qa=0;Qa<x;++Qa){var Db=Cb,pc=Db.push;var S=q+24*Qa;S={format:Ib[A[S+4>>2]],offset:4294967296*A[S+4+8>>2]+A[S+8>>2],shaderLocation:A[S+16>>2]};pc.call(Db,S)}I={arrayStride:I,stepMode:w,attributes:Cb}}}else I=void 0;l.call(v,I)}k=p}else k=void 0;return{module:f,constants:g,buffers:k,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Jb[A[d+4>>2]],stripIndexFormat:Kb[A[d+8>>2]],frontFace:Lb[A[d+12>>2]],cullMode:Mb[A[d+16>>2]],
unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Fb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:pa[d+60>>2],depthBiasClamp:pa[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),
g=zb(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],m=A[d+28>>2],p=[],t=0;t<k;++t){var v=p,l=v.push,q=m+24*t,w=A[q+4>>2];if(0===w)q=void 0;else{w=W[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}l.call(v,q)}return{module:f,constants:g,targets:p,entryPoint:V(d+8)}}}(A[a+92>>2])}},Ob=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",
20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);
qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",
144);void 0!==a.kc&&c("maxImmediateSize",148)},Eb=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Bb=[,"add","subtract","reverse-subtract","min","max"],Pb=["binding-not-used",,"uniform","storage","read-only-storage"],Fb=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Qb=
[,"opaque","premultiplied","unpremultiplied","inherit"],Mb=[,"none","front","back"],Rb=[,"compatibility","core"],Sb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",
16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Lb=[,"ccw","cw"],Kb=[,"uint16","uint32"],Tb=[,"load","clear"],Ub=[,"low-power","high-performance"],Vb=[,"srgb","display-p3"],Jb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],Wb=["binding-not-used",
,"filtering","non-filtering","comparison"],Gb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],Xb=["binding-not-used",,"write-only","read-only","read-write"],Yb=[,"store","discard"],Zb=[,"all","stencil-only","depth-only"],$b=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint",
"rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb",
"bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb",
"astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],ac=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],bc=[,"1d","2d","2d-array",
"cube","cube-array","3d"],cc=[,"standard","extended"],Ib=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],
Hb=[,"vertex","instance"],dc={undefined:1,unknown:1,destroyed:2},ec=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";ec.Hb||(ec.Hb={});ec.Hb[a]||(ec.Hb[a]=1,ca&&(a="warning: "+a),h(a))},fc={rgba8unorm:22,bgra8unorm:27},gc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Na;e.pauseMainLoop=$a;e.resumeMainLoop=function(){Ra++;var a=Ja,b=Ka,c=F;F=null;Za(c,0,!1,Sa,!0);Pa(a,b);G()};e.preMainLoop&&Xa.push(e.preMainLoop);e.postMainLoop&&Ya.push(e.postMainLoop);
e.noExitRuntime&&(Ca=e.noExitRuntime);e.printErr&&(h=e.printErr);e.wasmBinary&&(n=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var hc,ic,jc,kc,lc,mc,Q,nc,oc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Y,sb,X,Hc={N:()=>sa(""),K:()=>{Ca=!1;Da=0},L:(a,b)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!b)return 0;var c=setTimeout(()=>{delete E[a];Ia(()=>Fc(a,performance.now()))},b);E[a]={id:c,tc:b};return 0},ra:()=>{$a();F=null},E:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,G:(a,b,c)=>{a=L(a);if(!a)return-4;a=cb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},sa:()=>performance.now(),za:(a,b)=>{function c(d){M(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},M:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ra();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},l:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),D:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},m:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),k:(a,
b,c,d)=>{if(!N.fullscreenEnabled())return-1;a=L(a);if(!a)return-4;jb(a,b,c,d,"webkitfullscreenchange");return jb(a,b,c,d,"fullscreenchange")},v:(a,b,c,d)=>kb(a,b,c,d,2,"keydown"),t:(a,b,c,d)=>kb(a,b,c,d,1,"keypress"),u:(a,b,c,d)=>kb(a,b,c,d,3,"keyup"),Aa:(a,b,c)=>{a=M(a);Za(a,b,c)},B:(a,b,c,d)=>mb(a,b,c,d,5,"mousedown"),y:(a,b,c,d)=>mb(a,b,c,d,33,"mouseenter"),x:(a,b,c,d)=>mb(a,b,c,d,34,"mouseleave"),z:(a,b,c,d)=>mb(a,b,c,d,8,"mousemove"),A:(a,b,c,d)=>mb(a,b,c,d,6,"mouseup"),o:(a,b,c,d)=>document.body?.requestPointerLock?
(a=L(a))?nb(a,b,c,d):-4:-1,n:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?ob(a,b,c,d):-4:-1,F:(a,b,c,d)=>pb(a,b,c,d),p:(a,b,c,d)=>qb(a,b,c,d,25,"touchcancel"),q:(a,b,c,d)=>qb(a,b,c,d,23,"touchend"),r:(a,b,c,d)=>qb(a,b,c,d,24,"touchmove"),s:(a,b,c,d)=>qb(a,b,c,d,22,"touchstart"),w:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?rb(a,b,c,d):-1:-4,S:function(a,b,c,d,f,g){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);
var k={};if(g){var m=A[g+12>>2];if(m){var p=A[g+16>>2];k.requiredFeatures=Array.from(A.subarray(p>>2,p+4*m>>2),l=>Sb[l])}var t=A[g+20>>2];if(t){var v={};function l(w,x,I=!1){x=A[t+x>>2];4294967295==x||I&&0==x||(v[w]=x)}function q(w,x){x=t+x;var I=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=I)v[w]=4294967296*A[x+4>>2]+A[x>>2]}l("maxTextureDimension1D",4);l("maxTextureDimension2D",8);l("maxTextureDimension3D",12);l("maxTextureArrayLayers",16);l("maxBindGroups",20);l("maxBindGroupsPlusVertexBuffers",
24);l("maxDynamicUniformBuffersPerPipelineLayout",32);l("maxDynamicStorageBuffersPerPipelineLayout",36);l("maxSampledTexturesPerShaderStage",40);l("maxSamplersPerShaderStage",44);l("maxStorageBuffersPerShaderStage",48);l("maxStorageTexturesPerShaderStage",52);l("maxUniformBuffersPerShaderStage",56);l("minUniformBufferOffsetAlignment",80);l("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);l("maxVertexBuffers",88);q("maxBufferSize",96);l("maxVertexAttributes",
104);l("maxVertexBufferArrayStride",108);l("maxInterStageShaderVariables",112);l("maxColorAttachments",116);l("maxColorAttachmentBytesPerSample",120);l("maxComputeWorkgroupStorageSize",124);l("maxComputeInvocationsPerWorkgroup",128);l("maxComputeWorkgroupSizeX",132);l("maxComputeWorkgroupSizeY",136);l("maxComputeWorkgroupSizeZ",140);l("maxComputeWorkgroupsPerDimension",144);l("maxImmediateSize",148,!0);k.requiredLimits=v}if(m=A[g+24>>2])m={label:V(m+4)},k.defaultQueue=m;k.label=V(g+4)}a.requestDevice(k).then(l=>
{T(f,l.queue);T(d,l);c&&l.lost.then(q=>{l.onuncapturederror=()=>{};var w=X(),x=R(q.message);Bc(c,dc[q.reason],x);Y(w)});l.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=X();q=R(q.error.message);Ec(d,w,q);Y(x)};Dc(b,1,d,0)},l=>{var q=X();l=R(l.message);Dc(b,3,d,l);c&&Bc(c,4,l);Y(q)})},V:(a,b,c)=>{var d=U(a);0===c&&ec();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(k){return 0}var g=
Gc(16,f.byteLength);y.fill(0,g,f.byteLength);ub[a].push(()=>{(new Uint8Array(f)).set(y.subarray(g,g+f.byteLength));nc(g)});return g},U:a=>{var b=U(a),c=ub[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete ub[a];b.unmap()}},a:a=>{delete tb[a]},f:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(g){return!1}T(c,f);d&&(ub[c]=[]);return!0},R:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+
4),code:""};switch(f){case 2:b.code=vb(d+8)}T(c,U(a).createShaderModule(b))},T:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},P:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return fc[a]},Q:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Rb[A[c+4>>2]],powerPreference:Ub[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.wc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(g=>{if(g)T(d,g),Cc(b,1,d,0);else{g=
X();var k=R("WebGPU not available on this browser (requestAdapter returned null)");Cc(b,3,d,k);Y(g)}},g=>{var k=X();g=R(g.message);Cc(b,4,d,g);Y(k)}):(f=X(),a=R("WebGPU not available on this browser (navigator.gpu is not available)"),Cc(b,3,d,a),Y(f))},J:Fa,Ea:function(){e.Rb=a=>{0!=ic()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Rb)},xa:function(){e.Wb=a=>{const b=a.clipboardData.getData("text");gc(()=>{const c=R(b);hc(c)})};window.addEventListener("paste",
e.Wb)},ta:function(){e.qc=[];e.Sb=b=>{b.stopPropagation();b.preventDefault()};e.Tb=b=>{b.stopPropagation();b.preventDefault()};e.Ub=b=>{b.stopPropagation();b.preventDefault()};e.Vb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.rc=c;jc(c.length);for(let f=0;f<c.length;f++)gc(()=>{const g=R(c[f].name);kc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);lc(b.clientX,b.clientY,d)};const a=e.nb;a.addEventListener("dragenter",e.Sb,!1);a.addEventListener("dragleave",
e.Tb,!1);a.addEventListener("dragover",e.Ub,!1);a.addEventListener("drop",e.Vb,!1)},Ca:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},I:function(a){e.Ab&&(URL.revokeObjectURL(e.Ab[a].ac),e.Ab[a]=null)},fa:function(a,b){0!==b&&(document.title=b?K(b):"");a=a?K(a):"";void 0!==e.canvas&&("object"===typeof e.canvas?bb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.nb=L(a);e.nb||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);e.nb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Da:function(){window.removeEventListener("beforeunload",e.Rb)},ua:function(){window.removeEventListener("paste",e.Wb)},oa:function(){const a=e.nb;a.removeEventListener("dragenter",e.Sb);a.removeEventListener("dragleave",e.Tb);a.removeEventListener("dragover",e.Ub);a.removeEventListener("drop",e.Vb)},g:function(){e.nb&&e.nb.requestPointerLock&&e.nb.requestPointerLock()},O:function(a,b,c){if(e.nb){if(0===
b)a="none";else if(0!=c)a=e.Ab[a].cc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.nb.style.cursor=a}},Ba:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,
b);g.data.set(y.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},H:function(a,b){b=b?K(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},va:(a,b)=>{Ob(U(a).limits,b);return 1},e:(a,b)=>U(a).features.has(Sb[b]),ja:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:yb(A[b+12>>2])});a=U(a);b=tc(0);
T(b,a.beginComputePass(c));return b},ia:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],k=[],m=0;m<f;++m){var p=k,t=p.push;var v=g+56*m;var l=A[v+4>>2];if(0!==l){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:U(l),depthSlice:q,resolveTarget:U(A[v+12>>2]),clearValue:wb(v+24),loadOp:Tb[A[v+16>>2]],storeOp:Yb[A[v+20>>2]]}}else v=void 0;t.call(p,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:pa[f+16>>2],depthLoadOp:Tb[A[f+8>>
2]],depthStoreOp:Yb[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Tb[A[f+24>>2]],stencilStoreOp:Yb[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:yb(A[b+28>>2]),maxDrawCount:d};a=U(a);d=wc(0);T(d,a.beginRenderPass(b));return d},Y:a=>{a=U(a);var b=rc(0);T(b,a.finish());return b},Z:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,
c,A,f>>2,d)},ha:(a,b)=>{U(a).setPipeline(U(b))},h:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var g=[],k=0;k<f;++k){var m=g,p=m.push;var t=b+40*k;var v=A[t+8>>2],l=A[t+32>>2],q=A[t+36>>2],w=A[t+4>>2];v?(l=t+24,l=A[l>>2]+4294967296*z[l+4>>2],-1==l&&(l=void 0),t={binding:w,resource:{buffer:U(v),offset:4294967296*A[t+4+16>>2]+A[t+16>>2],size:l}}):t=l?{binding:w,resource:U(l)}:{binding:w,resource:U(q)};p.call(m,t)}c={label:c,layout:d,entries:g};a=U(a);d=oc(0);T(d,a.createBindGroup(c));
return d},i:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],g=0;g<d;++g){var k=f,m=k.push,p=b+88*g,t=A[p+4>>2],v=A[p+8>>2];var l=p+24;var q=A[l+4>>2];l=q?{type:Pb[q],hasDynamicOffset:!!A[l+8>>2],minBindingSize:4294967296*A[l+4+16>>2]+A[l+16>>2]}:void 0;q=(q=A[p+48+4>>2])?{type:Wb[q]}:void 0;var w=p+56;var x=A[w+4>>2];w=x?{sampleType:ac[x],viewDimension:bc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;p+=72;p=(x=A[p+4>>2])?{access:Xb[x],format:W[A[p+8>>2]],viewDimension:bc[A[p+12>>2]]}:
void 0;m.call(k,{binding:t,visibility:v,buffer:l,sampler:q,texture:w,storageTexture:p})}c={label:c,entries:f};a=U(a);d=qc(0);T(d,a.createBindGroupLayout(c));return d},ka:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=sc(0);T(b,a.createCommandEncoder(c));return b},ma:(a,b)=>{var c=V(b+4);var d=Ab(A[b+12>>2]);b=(b+=16)?{module:U(A[b+4>>2]),constants:zb(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=uc(0);T(d,a.createComputePipeline(c));return d},na:(a,b)=>{for(var c=
A[b+12>>2],d=A[b+16>>2],f=[],g=0;g<c;++g)f.push(U(A[d+4*g>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=vc(0);T(c,a.createPipelineLayout(b));return c},la:(a,b)=>{b=Nb(b);a=U(a);var c=xc(0);T(c,a.createRenderPipeline(b));return c},C:(a,b)=>{var c={label:V(b+4),size:xb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:$b[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=zc(0);T(d,
a.createTexture(c));return d},pa:(a,b)=>{Ob(U(a).limits,b);return 1},d:(a,b)=>U(a).features.has(Sb[b]),ya:(a,b)=>{a=L(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.sc=V(b+4);b=yc(0);T(b,a);return b},X:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},W:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},$:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},aa:(a,b,c,d,f,g)=>{U(a).drawIndexed(b,c,d>>>
0,f,g>>>0)},_:a=>{U(a).end()},b:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ea:(a,b)=>{U(a).setBlendConstant(wb(b))},ca:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Kb[c],d,f)},ga:(a,b)=>{U(a).setPipeline(U(b))},da:(a,b)=>{U(a).setStencilReference(b>>>0)},ba:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:
Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},wa:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Qb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),g=>W[g])}b=A[b>>2];0!==b&&(c.colorSpace=Vb[A[b+8>>2]],c.uc={mode:cc[A[b+12>>2]]});a.configure(c)},
qa:(a,b)=>{a=U(a);try{var c=zc(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},j:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:bc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Zb[A[b+36>>2]]}}a=U(a);b=Ac(0);T(b,a.createView(c));return b}};
function Ic(a=[]){var b=mc;a.unshift(ea);var c=a.length,d=sb(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=R(k);f+=4});A[f>>2]=0;try{var g=b(c,d);Ga(g)}catch(k){Ea(k)}}
function Jc(a=da){function b(){e.calledRun=!0;if(!r){Z.Ga();e.onRuntimeInitialized?.();e.noInitialRun||Ic(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();za.push(c)}ya(za)}}if(0<C)D=Jc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ba();ya(Aa);0<C?D=Jc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Z;
(async function(){function a(c){Z=c.exports;na=Z.Fa;ra();eb=Z.ub;c=Z;e.__sapp_emsc_onpaste=hc=c.Ha;e.__sapp_html5_get_ask_leave_site=ic=c.Ia;e.__sapp_emsc_begin_drop=jc=c.Ja;e.__sapp_emsc_drop=kc=c.Ka;e.__sapp_emsc_end_drop=lc=c.La;e.__sapp_emsc_invoke_fetch_cb=c.Ma;e.__sapp_emsc_set_fullscreen_flag=c.Na;e._main=mc=c.Oa;e.__saudio_emsc_pull=c.Pa;e.__sfetch_emsc_head_response=c.Qa;e.__sfetch_emsc_get_response=c.Ra;e.__sfetch_emsc_failed_http_status=c.Sa;e.__sfetch_emsc_failed_buffer_too_small=c.Ta;
e.__sfetch_emsc_failed_other=c.Ua;Q=c.Va;nc=c.Wa;oc=c.Xa;qc=c.Ya;rc=c.Za;sc=c._a;tc=c.$a;uc=c.ab;vc=c.bb;wc=c.fb;xc=c.gb;yc=c.ib;zc=c.jb;Ac=c.kb;Bc=c.qb;Cc=c.rb;Dc=c.sb;Ec=c.tb;Fc=c.vb;Gc=c.wb;Y=c.xb;sb=c.yb;X=c.zb;C--;e.monitorRunDependencies?.(C);0==C&&D&&(c=D,D=null,c());return Z}C++;e.monitorRunDependencies?.(C);var b={a:Hc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ta??=e.locateFile?e.locateFile("cube-sapp.wasm",ia):ia+"cube-sapp.wasm";return a((await wa(b)).instance)})();
Jc();
