var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),h=console.error.bind(console),q,u=!1,na,la=a=>a.startsWith("file://"),v,y,oa,pa,z,A,B,C,qa;
function ra(){var a=sa.buffer;v=new Int8Array(a);oa=new Int16Array(a);y=new Uint8Array(a);pa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);u=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function wa(a){if(!q)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&q)a=new Uint8Array(q);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=ua;if(!q&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},D=0,E=null,Ea=!0,Fa=globalThis.TextDecoder&&new TextDecoder,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|k);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|g:(f&7)<<18|k<<12|g<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ga=0,G={},Ha=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ia=a=>{na=a;Ea||0<Ga||(e.onExit?.(a),u=!0);fa(a,new za(a))},Ja=a=>{na=a;Ia(a)},Ka=()=>{if(!(Ea||0<Ga))try{var a=na;na=a;Ia(a)}catch(b){Ha(b)}},H=a=>{if(!u)try{a(),Ka()}catch(b){Ha(b)}},Sa=(a,b)=>{La=a;Ma=b;if(I)if(Na||=!0,0==a)K=function(){setTimeout(L,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)K=function(){Pa(L)};else if(2==a){if(!Qa)if(globalThis.setImmediate)Qa=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}K=function(){Qa(L)}}},ab=(a,b,c,d,f)=>{function k(){return g<Ta?(Ka(),!1):!0}I=a;Ua=d;var g=Ta;Na=!1;L=function(){if(!u)if(0<Va.length){var m=Va.shift();m.yc(m.rc);if(Wa){var l=
Wa,p=0==l%1?l-1:Math.floor(l);Wa=m.tc?p:(8*l+(p+.5))/9}e.setStatus&&(m=e.statusMessage||"Please wait...",l=Wa??0,p=Xa.xc??0,l?l<p?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(m):e.setStatus(""));k()&&setTimeout(L,0)}else if(k())if(Ya=Ya+1|0,1==La&&1<Ma&&0!=Ya%Ma)K();else{0==La&&(Oa=performance.now());a:if(!u){for(m of Za)if(!1===m())break a;H(a);for(l of $a)l()}k()&&K()}};f||(0<b?Sa(0,1E3/b):Sa(1,1),K());if(c)throw"unwind";},Na=!1,K=null,Ta=0,I=null,Ua=0,La=0,Ma=0,Ya=0,
Va=[],Za=[],$a=[];function bb(){K=null;Ta++}var M=0;function Pa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===M)M=b+1E3/60;else for(;b+2>=M;)M+=1E3/60;setTimeout(a,Math.max(M-b,0))}}
var Xa={},Oa,L,Qa,Wa,cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?F(y,a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):null)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],O=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};function gb(a){var b=P.tb[a];b.target.removeEventListener(b.sb,b.cc,b.ub);P.tb.splice(a,1)}
function hb(){if(navigator.userActivation?navigator.userActivation.isActive:P.Ub&&P.pc.Rb){var a=P.Eb;P.Eb=[];for(var b of a)b.Yb(...b.bc)}}function Q(a){if(!a.target)return-4;if(a.Bb)a.cc=function(c){++P.Ub;P.pc=a;hb();a.Cb(c);hb();--P.Ub},a.target.addEventListener(a.sb,a.cc,a.ub),P.tb.push(a);else for(var b=0;b<P.tb.length;++b)P.tb[b].target==a.target&&P.tb[b].sb==a.sb&&gb(b--);return 0}function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={sc:0,zc:0,Vb:0,Qb:0,ac:0,$b:0,Sb:0,wc:0,Cc:0,vc:0,Tb:0,Wb:0,Lc:0,Zb:0,Bc(a,b,c){v.set(v.subarray(b,b+c),a)},Dc(){for(;P.tb.length;)gb(P.tb.length-1);P.Eb=[]},Ub:0,Eb:[],uc(a,b,c){function d(k,g){if(k.length!=g.length)return!1;for(var m in k)if(k[m]!=g[m])return!1;return!0}for(var f of P.Eb)if(f.Yb==a&&d(f.bc,c))return;P.Eb.push({Yb:a,fc:b,bc:c});P.Eb.sort((k,g)=>k.fc<g.fc)},Fc(a){P.Eb=P.Eb.filter(b=>b.Yb!=a)},tb:[],Ec:(a,b)=>{for(var c=0;c<P.tb.length;++c)P.tb[c].target!=a||b&&b!=P.tb[c].sb||
gb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},R=(a,b,c)=>{var d=y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var k=0;k<a.length;++k){var g=a.codePointAt(k);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;k++}}d[b]=0;return b-
f},jb=(a,b,c,d,f,k)=>{P.Sb||(P.Sb=S(256));a={target:N(a),sb:k,Bb:d,Cb:(g=event)=>{var m=g.target.id?g.target.id:"",l=P.Sb;R(ib(g.target),l+0,128);R(m,l+128,128);O(d)(f,l,b)&&g.preventDefault()},ub:c};return Q(a)},kb=(a,b,c,d,f)=>{P.Tb||(P.Tb=S(276));return Q({target:a,sb:f,Bb:d,Cb:(k=event)=>{var g=P.Tb,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,l=!!m;v[g]=l;v[g+1]=P.fullscreenEnabled();
var p=l?m:P.qc,r=p?.id||"";R(ib(p),g+2,128);R(r,g+130,128);z[g+260>>2]=p?p.clientWidth:0;z[g+264>>2]=p?p.clientHeight:0;z[g+268>>2]=screen.width;z[g+272>>2]=screen.height;l&&(P.qc=m);O(d)(19,g,b)&&k.preventDefault()},ub:c})},lb=(a,b,c,d,f,k)=>{P.Vb||(P.Vb=S(160));a={target:N(a),sb:k,Bb:d,Cb:g=>{var m=P.Vb;C[m>>3]=g.timeStamp;var l=m>>2;z[l+2]=g.location;v[m+12]=g.ctrlKey;v[m+13]=g.shiftKey;v[m+14]=g.altKey;v[m+15]=g.metaKey;v[m+16]=g.repeat;z[l+5]=g.charCode;z[l+6]=g.keyCode;z[l+7]=g.which;R(g.key||
"",m+32,32);R(g.code||"",m+64,32);R(g.char||"",m+96,32);R(g.locale||"",m+128,32);O(d)(f,m,b)&&g.preventDefault()},ub:c};return Q(a)},mb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;v[a+24]=b.ctrlKey;v[a+25]=b.shiftKey;v[a+26]=b.altKey;v[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=db(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,f,k)=>{P.Qb||(P.Qb=S(64));a=
N(a);return Q({target:a,Rb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,sb:k,Bb:d,Cb:(g=event)=>{mb(P.Qb,g,a);O(d)(f,P.Qb,b)&&g.preventDefault()},ub:c})},ob=(a,b,c,d)=>{P.Wb||(P.Wb=S(257));return Q({target:a,sb:"pointerlockchange",Bb:d,Cb:(f=event)=>{var k=P.Wb,g=document.pointerLockElement;v[k]=!!g;var m=g?.id||"";R(ib(g),k+1,128);R(m,k+129,128);O(d)(20,k,b)&&f.preventDefault()},ub:c})},pb=(a,b,c,d)=>Q({target:a,sb:"pointerlockerror",Bb:d,Cb:(f=event)=>{O(d)(38,0,b)&&f.preventDefault()},ub:c}),
qb=(a,b,c,d)=>{P.$b||(P.$b=S(36));a=N(a);return Q({target:a,sb:"resize",Bb:d,Cb:(f=event)=>{if(f.target==a){var k=document.body;if(k){var g=P.$b;z[g>>2]=0;z[g+4>>2]=k.clientWidth;z[g+8>>2]=k.clientHeight;z[g+12>>2]=innerWidth;z[g+16>>2]=innerHeight;z[g+20>>2]=outerWidth;z[g+24>>2]=outerHeight;z[g+28>>2]=pageXOffset|0;z[g+32>>2]=pageYOffset|0;O(d)(10,g,b)&&f.preventDefault()}}},ub:c})},rb=(a,b,c,d,f,k)=>{P.Zb||(P.Zb=S(1552));a=N(a);return Q({target:a,Rb:"touchstart"==k||"touchend"==k,sb:k,Bb:d,Cb:g=>
{var m={},l=g.touches;for(var p of l)p.dc=p.ec=0,m[p.identifier]=p;for(var r of g.changedTouches)r.dc=1,m[r.identifier]=r;for(var n of g.targetTouches)m[n.identifier].ec=1;l=P.Zb;C[l>>3]=g.timeStamp;v[l+12]=g.ctrlKey;v[l+13]=g.shiftKey;v[l+14]=g.altKey;v[l+15]=g.metaKey;p=l+16;r=db(a);n=0;for(let t of Object.values(m))if(m=p>>2,z[m]=t.identifier,z[m+1]=t.screenX,z[m+2]=t.screenY,z[m+3]=t.clientX,z[m+4]=t.clientY,z[m+5]=t.pageX,z[m+6]=t.pageY,v[p+28]=t.dc,v[p+29]=t.ec,z[m+8]=t.clientX-(r.left|0),z[m+
9]=t.clientY-(r.top|0),p+=48,31<++n)break;z[l+8>>2]=n;O(d)(f,l,b)&&g.preventDefault()},ub:c})},sb=(a,b,c,d)=>{P.ac||(P.ac=S(96));return Q({target:a,Rb:!0,sb:"wheel",Bb:d,Cb:(f=event)=>{var k=P.ac;mb(k,f,a);C[k+64>>3]=f.deltaX;C[k+72>>3]=f.deltaY;C[k+80>>3]=f.deltaZ;z[k+88>>2]=f.deltaMode;O(d)(9,k,b)&&f.preventDefault()},ub:c})},tb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},T=a=>{var b=tb(a)+1,c=ub(b);R(a,c,b);return c},
U=[],vb=(a,b)=>{U[a>>>0]=b},wb=[],V=a=>{if(a)return U[a>>>0]},xb=a=>{var b=A[a>>2];return b?F(y,b,A[a+4>>2]):""},W=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?F(y,b,a):"";if(0===a)return""},yb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),zb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Ab=a=>{if(0!==a)return{querySet:V(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},Bb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,k=xb(f+4);c[k]=
C[f+16>>3]}return c}},Cb=a=>a?V(a):"auto",Pb=a=>{function b(d){if(d)return{operation:Db[A[d>>2]],srcFactor:Eb[A[d+4>>2]],dstFactor:Eb[A[d+8>>2]]}}function c(d){return{compare:Fb[A[d>>2]],failOp:Gb[A[d+4>>2]],depthFailOp:Gb[A[d+8>>2]],passOp:Gb[A[d+12>>2]]}}return{label:W(a+4),layout:Cb(A[a+12>>2]),vertex:function(d){if(d){var f=V(A[d+4>>2]),k=Bb(A[d+16>>2],A[d+20>>2]);var g=A[d+24>>2];var m=A[d+28>>2];if(g){for(var l=[],p=0;p<g;++p){var r=l,n=r.push;var t=m+24*p;if(t){var w=A[t+4>>2],x=A[t+16>>2];
if(0===w&&0===x)var J=null;else{J=4294967296*A[t+4+8>>2]+A[t+8>>2];w=Hb[w];t=A[t+20>>2];for(var Ib=[],Ra=0;Ra<x;++Ra){var Jb=Ib,va=t+24*Ra;Jb.push.call(Jb,{format:Kb[A[va+4>>2]],offset:4294967296*A[va+4+8>>2]+A[va+8>>2],shaderLocation:A[va+16>>2]})}J={arrayStride:J,stepMode:w,attributes:Ib}}}else J=void 0;n.call(r,J)}g=l}else g=void 0;return{module:f,constants:k,buffers:g,entryPoint:W(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Lb[A[d+4>>2]],stripIndexFormat:Mb[A[d+8>>2]],frontFace:Nb[A[d+
12>>2]],cullMode:Ob[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:X[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Fb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=
V(A[d+4>>2]),k=Bb(A[d+16>>2],A[d+20>>2]),g=A[d+24>>2],m=A[d+28>>2],l=[],p=0;p<g;++p){var r=l,n=r.push,t=m+24*p,w=A[t+4>>2];if(0===w)t=void 0;else{w=X[w];var x=(x=A[t+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;t={format:w,blend:x,writeMask:A[t+16>>2]}}n.call(r,t)}return{module:f,constants:k,targets:l,entryPoint:W(d+8)}}}(A[a+92>>2])}},Qb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",
20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);
qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",
144);void 0!==a.Ac&&c("maxImmediateSize",148)},Rb=[,"clamp-to-edge","repeat","mirror-repeat"],Eb=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Db=[,"add","subtract","reverse-subtract","min","max"],Sb=["binding-not-used",,"uniform","storage","read-only-storage"],Fb=[,"never","less","equal","less-equal","greater",
"not-equal","greater-equal","always"],Tb=[,"opaque","premultiplied","unpremultiplied","inherit"],Ob=[,"none","front","back"],Ub=[,"compatibility","core"],Vb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",
14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Wb=[,"nearest","linear"],Nb=[,"ccw","cw"],Mb=[,"uint16","uint32"],Xb=[,"load","clear"],Yb=[,"nearest","linear"],Zb=[,"low-power","high-performance"],$b=[,"srgb",
"display-p3"],Lb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],ac=["binding-not-used",,"filtering","non-filtering","comparison"],Gb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],bc=["binding-not-used",,"write-only","read-only","read-write"],cc=[,"store","discard"],dc=[,"all","stencil-only","depth-only"],ec=[,"1d","2d","3d"],X=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float",
"rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float",
"depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm",
"astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],
fc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],gc=[,"1d","2d","2d-array","cube","cube-array","3d"],hc=[,"standard","extended"],Kb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2",
"uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Hb=[,"vertex","instance"],ic={undefined:1,unknown:1,destroyed:2},jc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";jc.Xb||(jc.Xb={});jc.Xb[a]||(jc.Xb[a]=1,ca&&(a="warning: "+a),h(a))},kc={rgba8unorm:22,bgra8unorm:27},lc={},nc=()=>{if(!mc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-",
"_")+".UTF-8",_:ea||"./this.program"},b;for(b in lc)void 0===lc[b]?delete a[b]:a[b]=lc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);mc=c}return mc},mc,oc=[null,[],[]],pc=a=>{var b=Y();a();Z(b)};e.requestAnimationFrame=Pa;e.pauseMainLoop=bb;e.resumeMainLoop=function(){Ta++;var a=La,b=Ma,c=I;I=null;ab(c,0,!1,Ua,!0);Sa(a,b);K()};e.preMainLoop&&Za.push(e.preMainLoop);e.postMainLoop&&$a.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(h=e.printErr);
e.wasmBinary&&(q=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var S,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Z,ub,Y,sa,fb,Qc={r:function(){return 0},W:function(){return 0},X:function(){},_:()=>ta(""),Q:()=>{Ea=!1;Ga=0},R:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];H(()=>Oc(a,performance.now()))},b);G[a]={id:c,Jc:b};return 0},Ga:()=>{bb();I=null},L:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,N:(a,b,c)=>{a=N(a);if(!a)return-4;a=db(a);C[b>>3]=a.width;C[c>>
3]=a.height;return 0},Ha:()=>performance.now(),Na:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},S:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},t:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),K:(a,b,c)=>{a=N(a);if(!a)return-4;
a.width=b;a.height=c;return 0},u:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),s:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=N(a);if(!a)return-4;kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},D:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),B:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),C:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),Oa:(a,b,c)=>{a=O(a);ab(a,b,c)},J:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),G:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),F:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),H:(a,b,c,d)=>nb(a,b,c,d,8,
"mousemove"),I:(a,b,c,d)=>nb(a,b,c,d,6,"mouseup"),w:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?ob(a,b,c,d):-4:-1,v:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?pb(a,b,c,d):-4:-1,M:(a,b,c,d)=>qb(a,b,c,d),x:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),y:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),z:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),A:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),E:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?sb(a,b,c,d):-1:-4,ca:function(a,b,c,d,f,k){b=-9007199254740992>b||
9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=V(a);var g={};if(k){var m=A[k+12>>2];if(m){var l=A[k+16>>2];g.requiredFeatures=Array.from(A.subarray(l>>2,l+4*m>>2),n=>Vb[n])}var p=A[k+20>>2];if(p){var r={};function n(w,x,J=!1){x=A[p+x>>2];4294967295==x||J&&0==x||(r[w]=x)}function t(w,x){x=p+x;var J=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=J)r[w]=4294967296*A[x+4>>2]+A[x>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",8);n("maxTextureDimension3D",
12);n("maxTextureArrayLayers",16);n("maxBindGroups",20);n("maxBindGroupsPlusVertexBuffers",24);n("maxDynamicUniformBuffersPerPipelineLayout",32);n("maxDynamicStorageBuffersPerPipelineLayout",36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);t("maxUniformBufferBindingSize",
64);t("maxStorageBufferBindingSize",72);n("maxVertexBuffers",88);t("maxBufferSize",96);n("maxVertexAttributes",104);n("maxVertexBufferArrayStride",108);n("maxInterStageShaderVariables",112);n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",
148,!0);g.requiredLimits=r}if(m=A[k+24>>2])m={label:W(m+4)},g.defaultQueue=m;g.label=W(k+4)}a.requestDevice(g).then(n=>{H(()=>{U[f>>>0]=n.queue;U[d>>>0]=n;n.lost.then(t=>{H(()=>{n.onuncapturederror=()=>{};var w=Y(),x=T(t.message);Kc(c,ic[t.reason],x);Z(w)})});n.onuncapturederror=t=>{var w=5;t.error instanceof GPUValidationError?w=2:t.error instanceof GPUOutOfMemoryError?w=3:t.error instanceof GPUInternalError&&(w=4);var x=Y();t=T(t.error.message);Nc(d,w,t);Z(x)};Mc(b,1,d,0)})},n=>{H(()=>{var t=Y(),
w=T(n.message);Mc(b,3,d,w);c&&Kc(c,4,w);Z(t)})})},ga:(a,b,c)=>{var d=V(a);0===c&&jc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(g){return 0}var k=Pc(16,f.byteLength);y.fill(0,k,f.byteLength);wb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(k,k+f.byteLength));qc(k)});return k},fa:a=>{var b=V(a),c=wb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete wb[a];b.unmap()}},a:a=>{delete U[a]},j:(a,b,c)=>{var d=!!A[b+32>>2];b={label:W(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>
2],mappedAtCreation:d};a=V(a);try{var f=a.createBuffer(b)}catch(k){return!1}U[c>>>0]=f;d&&(wb[c]=[]);return!0},ba:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:W(b+4),code:""};switch(f){case 2:b.code=xb(d+8)}a=V(a).createShaderModule(b);U[c>>>0]=a},da:a=>{a=V(a);a.onuncapturederror=null;a.destroy()},$:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return kc[a]},aa:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Ub[A[c+4>>2]],powerPreference:Zb[A[c+
8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Mc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(k=>{H(()=>{if(k)U[d>>>0]=k,Lc(b,1,d,0);else{var g=Y(),m=T("WebGPU not available on this browser (requestAdapter returned null)");Lc(b,3,d,m);Z(g)}})},k=>{H(()=>{var g=Y(),m=T(k.message);Lc(b,4,d,m);Z(g)})}):(f=Y(),a=T("WebGPU not available on this browser (navigator.gpu is not available)"),Lc(b,3,d,a),Z(f))},Y:(a,b)=>{var c=0,d=0,f;for(f of nc()){var k=b+c;A[a+d>>2]=
k;c+=R(f,k,Infinity)+1;d+=4}return 0},Z:(a,b)=>{var c=nc();A[a>>2]=c.length;a=0;for(var d of c)a+=tb(d)+1;A[b>>2]=a;return 0},q:()=>52,V:()=>52,T:function(){return 70},U:(a,b,c,d)=>{for(var f=0,k=0;k<c;k++){var g=A[b>>2],m=A[b+4>>2];b+=8;for(var l=0;l<m;l++){var p=a,r=y[g+l],n=oc[p];0===r||10===r?((1===p?ma:h)(F(n)),n.length=0):n.push(r)}f+=m}A[d>>2]=f;return 0},Ta:Ia,Ua:function(){e.hc=a=>{0!=sc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.hc)},Ja:function(){e.mc=
a=>{const b=a.clipboardData.getData("text");pc(()=>{const c=T(b);rc(c)})};window.addEventListener("paste",e.mc)},va:function(){e.Gc=[];e.ic=b=>{b.stopPropagation();b.preventDefault()};e.jc=b=>{b.stopPropagation();b.preventDefault()};e.kc=b=>{b.stopPropagation();b.preventDefault()};e.lc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Hc=c;tc(c.length);for(let f=0;f<c.length;f++)pc(()=>{const k=T(c[f].name);uc(f,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=
4);b.metaKey&&(d|=8);vc(b.clientX,b.clientY,d)};const a=e.Db;a.addEventListener("dragenter",e.ic,!1);a.addEventListener("dragleave",e.jc,!1);a.addEventListener("dragover",e.kc,!1);a.addEventListener("drop",e.lc,!1)},Ra:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},h:function(a){e.Fb&&(URL.revokeObjectURL(e.Fb[a].nc),e.Fb[a]=null)},ea:function(a,b){0!==b&&(document.title=b?F(y,b):"");a=a?F(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?cb[a]=
e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.Db=N(a);e.Db||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.Db.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Sa:function(a,b,c,d,f,k){var g=b*c*4,m=138+g;const l=new Uint8Array(m);let p=0;var r=n=>{l[p++]=n&255;l[p++]=n>>8&255;l[p++]=n>>16&255;l[p++]=n>>24&255};l[p++]=66;l[p++]=77;r(m);r(0);r(138);14==p||ta();r(124);r(b);r(c);l[p++]=1;l[p++]=
0;l[p++]=32;l[p++]=0;r(3);r(g);r(2835);r(2835);r(0);r(0);r(255);r(65280);r(16711680);r(4278190080);l[p++]=66;l[p++]=71;l[p++]=82;l[p++]=115;p+=64;138==p||ta();b*=4;for(g=0;g<c;g++)r=d+g*b,m=p+(c-g-1)*b,r=y.slice(r,r+b),l.set(r,m);c=URL.createObjectURL(new Blob([l.buffer],{type:"image/bmp"}));f={oc:`url('${c}') ${f} ${k}, auto`,nc:c};e.Fb||(e.Fb=[].fill(null));e.Fb[a]=f},Pa:function(){window.removeEventListener("beforeunload",e.hc)},Ia:function(){window.removeEventListener("paste",e.mc)},oa:function(){const a=
e.Db;a.removeEventListener("dragenter",e.ic);a.removeEventListener("dragleave",e.jc);a.removeEventListener("dragover",e.kc);a.removeEventListener("drop",e.lc)},i:function(){e.Db&&e.Db.requestPointerLock&&e.Db.requestPointerLock()},b:function(a,b,c){if(e.Db){if(0===b)a="none";else if(0!=c)a=e.Fb[a].oc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a=
"nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.Db.style.cursor=a}},Qa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),k=f.createImageData(a,b);k.data.set(y.subarray(c,c+a*b*4));f.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ea:function(a){a=a?F(y,a):"";const b=
document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},P:function(){return navigator.userAgent.includes("Macintosh")?1:0},O:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;
case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Ka:(a,b)=>{Qb(V(a).limits,b);return 1},f:(a,b)=>V(a).features.has(Vb[b]),wa:(a,b)=>{var c;b&&(c={label:W(b+4),timestampWrites:Ab(A[b+12>>2])});b=V(a);a=Bc(0);c=b.beginComputePass(c);U[a>>>0]=c;return a},ua:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=W(b+4);for(var f=A[b+12>>2],k=A[b+16>>2],g=[],m=0;m<f;++m){var l=g,p=l.push;var r=k+56*m;var n=A[r+4>>2];if(0!==n){var t=z[r+8>>2];-1==
t&&(t=void 0);r={view:V(n),depthSlice:t,resolveTarget:V(A[r+12>>2]),clearValue:yb(r+24),loadOp:Xb[A[r+16>>2]],storeOp:cc[A[r+20>>2]]}}else r=void 0;p.call(l,r)}f=A[b+20>>2];f=0!==f?{view:V(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Xb[A[f+8>>2]],depthStoreOp:cc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Xb[A[f+24>>2]],stencilStoreOp:cc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:g,depthStencilAttachment:f,occlusionQuerySet:V(A[b+
24>>2]),timestampWrites:Ab(A[b+28>>2]),maxDrawCount:d};d=V(a);a=Ec(0);b=d.beginRenderPass(b);U[a>>>0]=b;return a},ia:a=>{var b=V(a);a=zc(0);b=b.finish();U[a>>>0]=b;return a},ja:a=>{V(a).end()},d:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ta:(a,b)=>{V(a).setPipeline(V(b))},n:(a,b)=>{var c=W(b+4),d=V(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var k=[],g=0;g<f;++g){var m=k,l=m.push;var p=b+40*g;var r=A[p+8>>2],n=A[p+32>>2],t=A[p+36>>2],w=A[p+4>>2];r?(n=p+24,n=A[n>>
2]+4294967296*z[n+4>>2],-1==n&&(n=void 0),p={binding:w,resource:{buffer:V(r),offset:4294967296*A[p+4+16>>2]+A[p+16>>2],size:n}}):p=n?{binding:w,resource:V(n)}:{binding:w,resource:V(t)};l.call(m,p)}c={label:c,layout:d,entries:k};d=V(a);a=xc(0);c=d.createBindGroup(c);U[a>>>0]=c;return a},o:(a,b)=>{var c=W(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],k=0;k<d;++k){var g=f,m=g.push,l=b+88*k,p=A[l+4>>2],r=A[l+8>>2];var n=l+24;var t=A[n+4>>2];n=t?{type:Sb[t],hasDynamicOffset:!!A[n+8>>2],minBindingSize:4294967296*
A[n+4+16>>2]+A[n+16>>2]}:void 0;t=(t=A[l+48+4>>2])?{type:ac[t]}:void 0;var w=l+56;var x=A[w+4>>2];w=x?{sampleType:fc[x],viewDimension:gc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;l+=72;l=(x=A[l+4>>2])?{access:bc[x],format:X[A[l+8>>2]],viewDimension:gc[A[l+12>>2]]}:void 0;m.call(g,{binding:p,visibility:r,buffer:n,sampler:t,texture:w,storageTexture:l})}c={label:c,entries:f};d=V(a);a=yc(0);c=d.createBindGroupLayout(c);U[a>>>0]=c;return a},xa:(a,b)=>{var c;b&&(c={label:W(b+4)});b=V(a);a=Ac(0);c=b.createCommandEncoder(c);
U[a>>>0]=c;return a},za:(a,b)=>{var c=W(b+4);var d=Cb(A[b+12>>2]);b=(b+=16)?{module:V(A[b+4>>2]),constants:Bb(A[b+16>>2],A[b+20>>2]),entryPoint:W(b+8)}:void 0;c={label:c,layout:d,compute:b};d=V(a);a=Cc(0);c=d.createComputePipeline(c);U[a>>>0]=c;return a},Aa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],k=0;k<c;++k)f.push(V(A[d+4*k>>2]));b={label:W(b+4),bindGroupLayouts:f};c=V(a);a=Dc(0);b=c.createPipelineLayout(b);U[a>>>0]=b;return a},ya:(a,b)=>{b=Pb(b);var c=V(a);a=Fc(0);b=c.createRenderPipeline(b);
U[a>>>0]=b;return a},Ba:(a,b)=>{var c;b&&(c={label:W(b+4),addressModeU:Rb[A[b+12>>2]],addressModeV:Rb[A[b+16>>2]],addressModeW:Rb[A[b+20>>2]],magFilter:Wb[A[b+24>>2]],minFilter:Wb[A[b+28>>2]],mipmapFilter:Yb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Fb[A[b+44>>2]],maxAnisotropy:pa[b+48>>1]});b=V(a);a=Gc(0);c=b.createSampler(c);U[a>>>0]=c;return a},p:(a,b)=>{var c={label:W(b+4),size:zb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:ec[A[b+24>>2]],format:X[A[b+
40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>X[f]));a=V(a);d=Ic(0);vb(d,a.createTexture(c));return d},Da:(a,b)=>{Qb(V(a).limits,b);return 1},e:(a,b)=>V(a).features.has(Vb[b]),Ma:(a,b)=>{a=N(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Ic=W(b+4);b=Hc(0);U[b>>>0]=a;return b},ha:(a,b,c)=>{a=V(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>V(d));a.submit(b)},k:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);
V(a).writeBuffer(V(b),c,y.subarray(d,d+f),0,f)},Ca:(a,b,c,d,f,k)=>{var g=A[f+8>>2],m=A[f+12>>2],l=b+8;V(a).writeTexture({texture:V(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[l>>2],y:A[l+4>>2],z:A[l+8>>2]},aspect:dc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===g?void 0:g,rowsPerImage:4294967295===m?void 0:m},zb(k))},la:(a,b,c,d,f)=>{V(a).draw(b,c,d>>>0,f>>>0)},ma:(a,b,c,d,f,k)=>{V(a).drawIndexed(b,c,d>>>0,f,k>>>0)},ka:a=>{V(a).end()},c:(a,b,c,d,f)=>{a=V(a);
c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ra:(a,b)=>{V(a).setBlendConstant(yb(b))},pa:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);b=V(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Mb[c],d,f)},sa:(a,b)=>{V(a).setPipeline(V(b))},l:(a,b,c,d,f)=>{V(a).setScissorRect(b,c,d,f)},qa:(a,b)=>{V(a).setStencilReference(b>>>0)},na:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);
f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);c=V(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},m:(a,b,c,d,f,k,g)=>{V(a).setViewport(b,c,d,f,k,g)},La:(a,b)=>{var c=A[b+4>>2];a=V(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:V(c),format:X[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Tb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),k=>X[k])}b=A[b>>2];0!==b&&(c.colorSpace=$b[A[b+
8>>2]],c.Kc={mode:hc[A[b+12>>2]]});a.configure(c)},Fa:(a,b)=>{a=V(a);try{var c=Ic(0),d=a.getCurrentTexture();U[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},g:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:W(b+4),format:X[A[b+12>>2]],dimension:gc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:dc[A[b+36>>2]]}}b=V(a);a=Jc(0);b=b.createView(c);U[a>>>0]=b;return a}};
function Rc(a=[]){var b=wc;a.unshift(ea);var c=a.length,d=ub(4*(c+1)),f=d;a.forEach(g=>{A[f>>2]=T(g);f+=4});A[f>>2]=0;try{var k=b(c,d);Ja(k)}catch(g){Ha(g)}}
function Sc(a=da){function b(){e.calledRun=!0;if(!u){Tc.Wa();e.onRuntimeInitialized?.();e.noInitialRun||Rc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Sc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Sc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Tc;
(async function(){function a(c){c=Tc=c.exports;S=c.Xa;qc=c.Ya;rc=e.__sapp_emsc_onpaste=c.Za;sc=e.__sapp_html5_get_ask_leave_site=c._a;tc=e.__sapp_emsc_begin_drop=c.$a;uc=e.__sapp_emsc_drop=c.ab;vc=e.__sapp_emsc_end_drop=c.bb;e.__sapp_emsc_invoke_fetch_cb=c.cb;e.__sapp_emsc_set_fullscreen_flag=c.db;wc=e._main=c.eb;e.__saudio_emsc_pull=c.fb;e.__sfetch_emsc_head_response=c.gb;e.__sfetch_emsc_get_response=c.hb;e.__sfetch_emsc_failed_http_status=c.ib;e.__sfetch_emsc_failed_buffer_too_small=c.jb;e.__sfetch_emsc_failed_other=
c.kb;xc=c.lb;yc=c.mb;zc=c.nb;Ac=c.ob;Bc=c.pb;Cc=c.qb;Dc=c.rb;Ec=c.vb;Fc=c.wb;Gc=c.xb;Hc=c.yb;Ic=c.zb;Jc=c.Ab;Kc=c.Gb;Lc=c.Hb;Mc=c.Ib;Nc=c.Jb;Oc=c.Lb;Pc=c.Mb;Z=c.Nb;ub=c.Ob;Y=c.Pb;sa=c.Va;fb=c.Kb;ra();D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Tc}D++;e.monitorRunDependencies?.(D);var b={a:Qc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("cursor-sapp.wasm",ia):ia+"cursor-sapp.wasm";return a((await ya(b)).instance)})();
Sc();
