var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),h=console.error.bind(console),q,u=!1,na,la=a=>a.startsWith("file://"),oa,v,y,pa,qa,z,A,B,C,ra;
function sa(){var a=oa.buffer;v=new Int8Array(a);pa=new Int16Array(a);y=new Uint8Array(a);qa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var D=0,E=null;function ta(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);u=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function wa(a){if(!q)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&q)a=new Uint8Array(q);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=ua;if(!q&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},Ea=!0,Fa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|k);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|g:(f&7)<<18|k<<12|g<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ga=0,G={},Ha=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ia=a=>{na=a;Ea||0<Ga||(e.onExit?.(a),u=!0);fa(a,new za(a))},Ja=a=>{na=a;Ia(a)},Ka=()=>{if(!(Ea||0<Ga))try{var a=na;na=a;Ia(a)}catch(b){Ha(b)}},La=a=>{if(!u)try{a(),Ka()}catch(b){Ha(b)}},Ta=(a,b)=>{Ma=a;Na=b;if(H)if(Oa||=!0,0==a)I=function(){setTimeout(K,Math.max(0,Pa+b-performance.now())|0)};else if(1==a)I=function(){Qa(K)};else if(2==a){if("undefined"==
typeof Ra)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ra=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ra=setImmediate;I=function(){Ra(K)}}},bb=(a,b,c,d,f)=>{function k(){return g<Ua?(Ka(),!1):!0}H=a;Va=d;var g=Ua;Oa=!1;K=function(){if(!u)if(0<Wa.length){var n=
Wa.shift();n.xc(n.qc);if(Xa){var l=Xa,p=0==l%1?l-1:Math.floor(l);Xa=n.sc?p:(8*l+(p+.5))/9}e.setStatus&&(n=e.statusMessage||"Please wait...",l=Xa??0,p=Ya.wc??0,l?l<p?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(n):e.setStatus(""));k()&&setTimeout(K,0)}else if(k())if(Za=Za+1|0,1==Ma&&1<Na&&0!=Za%Na)I();else{0==Ma&&(Pa=performance.now());a:if(!u){for(n of $a)if(!1===n())break a;La(a);for(l of ab)l()}k()&&I()}};f||(0<b?Ta(0,1E3/b):Ta(1,1),I());if(c)throw"unwind";},Oa=!1,I=
null,Ua=0,H=null,Va=0,Ma=0,Na=0,Za=0,Wa=[],$a=[],ab=[];function cb(){I=null;Ua++}var L=0;function Qa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===L)L=b+1E3/60;else for(;b+2>=L;)L+=1E3/60;setTimeout(a,Math.max(L-b,0))}}
var Ya={},Pa,K,Ra,Xa,db=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?F(y,a):"":a;return db[a]||("undefined"!=typeof document?document.querySelector(a):null)},eb=a=>0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},fb=[],gb,N=a=>{var b=fb[a];b||(fb[a]=b=gb.get(a));return b};function hb(a){var b=O.sb[a];b.target.removeEventListener(b.rb,b.bc,b.tb);O.sb.splice(a,1)}
function ib(){if(navigator.userActivation?navigator.userActivation.isActive:O.Tb&&O.oc.Qb){var a=O.Db;O.Db=[];for(var b of a)b.Xb(...b.ac)}}function P(a){if(!a.target)return-4;if(a.Ab)a.bc=function(c){++O.Tb;O.oc=a;ib();a.Bb(c);ib();--O.Tb},a.target.addEventListener(a.rb,a.bc,a.tb),O.sb.push(a);else for(var b=0;b<O.sb.length;++b)O.sb[b].target==a.target&&O.sb[b].rb==a.rb&&hb(b--);return 0}function jb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var O={rc:0,yc:0,Ub:0,Pb:0,$b:0,Zb:0,Rb:0,vc:0,Bc:0,uc:0,Sb:0,Vb:0,Kc:0,Yb:0,Ac(a,b,c){v.set(v.subarray(b,b+c),a)},Cc(){for(;O.sb.length;)hb(O.sb.length-1);O.Db=[]},Tb:0,Db:[],tc(a,b,c){function d(k,g){if(k.length!=g.length)return!1;for(var n in k)if(k[n]!=g[n])return!1;return!0}for(var f of O.Db)if(f.Xb==a&&d(f.ac,c))return;O.Db.push({Xb:a,ec:b,ac:c});O.Db.sort((k,g)=>k.ec<g.ec)},Ec(a){O.Db=O.Db.filter(b=>b.Xb!=a)},sb:[],Dc:(a,b)=>{for(var c=0;c<O.sb.length;++c)O.sb[c].target!=a||b&&b!=O.sb[c].rb||
hb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Q=(a,b,c)=>{var d=y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var k=0;k<a.length;++k){var g=a.codePointAt(k);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;k++}}d[b]=0;return b-
f},kb=(a,b,c,d,f,k)=>{O.Rb||(O.Rb=R(256));a={target:M(a),rb:k,Ab:d,Bb:(g=event)=>{var n=g.target.id?g.target.id:"",l=O.Rb;Q(jb(g.target),l+0,128);Q(n,l+128,128);N(d)(f,l,b)&&g.preventDefault()},tb:c};return P(a)},lb=(a,b,c,d,f)=>{O.Sb||(O.Sb=R(276));return P({target:a,rb:f,Ab:d,Bb:(k=event)=>{var g=O.Sb,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,l=!!n;v[g]=l;v[g+1]=O.fullscreenEnabled();
var p=l?n:O.pc,r=p?.id||"";Q(jb(p),g+2,128);Q(r,g+130,128);z[g+260>>2]=p?p.clientWidth:0;z[g+264>>2]=p?p.clientHeight:0;z[g+268>>2]=screen.width;z[g+272>>2]=screen.height;l&&(O.pc=n);N(d)(19,g,b)&&k.preventDefault()},tb:c})},mb=(a,b,c,d,f,k)=>{O.Ub||(O.Ub=R(160));a={target:M(a),rb:k,Ab:d,Bb:g=>{var n=O.Ub;C[n>>3]=g.timeStamp;var l=n>>2;z[l+2]=g.location;v[n+12]=g.ctrlKey;v[n+13]=g.shiftKey;v[n+14]=g.altKey;v[n+15]=g.metaKey;v[n+16]=g.repeat;z[l+5]=g.charCode;z[l+6]=g.keyCode;z[l+7]=g.which;Q(g.key||
"",n+32,32);Q(g.code||"",n+64,32);Q(g.char||"",n+96,32);Q(g.locale||"",n+128,32);N(d)(f,n,b)&&g.preventDefault()},tb:c};return P(a)},nb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;v[a+24]=b.ctrlKey;v[a+25]=b.shiftKey;v[a+26]=b.altKey;v[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=eb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},ob=(a,b,c,d,f,k)=>{O.Pb||(O.Pb=R(64));a=
M(a);return P({target:a,Qb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,rb:k,Ab:d,Bb:(g=event)=>{nb(O.Pb,g,a);N(d)(f,O.Pb,b)&&g.preventDefault()},tb:c})},pb=(a,b,c,d)=>{O.Vb||(O.Vb=R(257));return P({target:a,rb:"pointerlockchange",Ab:d,Bb:(f=event)=>{var k=O.Vb,g=document.pointerLockElement;v[k]=!!g;var n=g?.id||"";Q(jb(g),k+1,128);Q(n,k+129,128);N(d)(20,k,b)&&f.preventDefault()},tb:c})},qb=(a,b,c,d)=>P({target:a,rb:"pointerlockerror",Ab:d,Bb:(f=event)=>{N(d)(38,0,b)&&f.preventDefault()},tb:c}),
rb=(a,b,c,d)=>{O.Zb||(O.Zb=R(36));a=M(a);return P({target:a,rb:"resize",Ab:d,Bb:(f=event)=>{if(f.target==a){var k=document.body;if(k){var g=O.Zb;z[g>>2]=0;z[g+4>>2]=k.clientWidth;z[g+8>>2]=k.clientHeight;z[g+12>>2]=innerWidth;z[g+16>>2]=innerHeight;z[g+20>>2]=outerWidth;z[g+24>>2]=outerHeight;z[g+28>>2]=pageXOffset|0;z[g+32>>2]=pageYOffset|0;N(d)(10,g,b)&&f.preventDefault()}}},tb:c})},sb=(a,b,c,d,f,k)=>{O.Yb||(O.Yb=R(1552));a=M(a);return P({target:a,Qb:"touchstart"==k||"touchend"==k,rb:k,Ab:d,Bb:g=>
{var n={},l=g.touches;for(var p of l)p.cc=p.dc=0,n[p.identifier]=p;for(var r of g.changedTouches)r.cc=1,n[r.identifier]=r;for(var m of g.targetTouches)n[m.identifier].dc=1;l=O.Yb;C[l>>3]=g.timeStamp;v[l+12]=g.ctrlKey;v[l+13]=g.shiftKey;v[l+14]=g.altKey;v[l+15]=g.metaKey;p=l+16;r=eb(a);m=0;for(let t of Object.values(n))if(n=p>>2,z[n]=t.identifier,z[n+1]=t.screenX,z[n+2]=t.screenY,z[n+3]=t.clientX,z[n+4]=t.clientY,z[n+5]=t.pageX,z[n+6]=t.pageY,v[p+28]=t.cc,v[p+29]=t.dc,z[n+8]=t.clientX-(r.left|0),z[n+
9]=t.clientY-(r.top|0),p+=48,31<++m)break;z[l+8>>2]=m;N(d)(f,l,b)&&g.preventDefault()},tb:c})},tb=(a,b,c,d)=>{O.$b||(O.$b=R(96));return P({target:a,Qb:!0,rb:"wheel",Ab:d,Bb:(f=event)=>{var k=O.$b;nb(k,f,a);C[k+64>>3]=f.deltaX;C[k+72>>3]=f.deltaY;C[k+80>>3]=f.deltaZ;z[k+88>>2]=f.deltaMode;N(d)(9,k,b)&&f.preventDefault()},tb:c})},ub=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},S=a=>{var b=ub(a)+1,c=vb(b);Q(a,c,b);return c},
wb=[],T=(a,b)=>{wb[a>>>=0]=b},xb=[],U=a=>{if(a)return wb[a>>>0]},yb=a=>{var b=A[a>>2];return b?F(y,b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?F(y,b,a):"";if(0===a)return""},zb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),Ab=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Bb=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},Cb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,k=yb(f+4);
c[k]=C[f+16>>3]}return c}},Db=a=>a?U(a):"auto",Qb=a=>{function b(d){if(d)return{operation:Eb[A[d>>2]],srcFactor:Fb[A[d+4>>2]],dstFactor:Fb[A[d+8>>2]]}}function c(d){return{compare:Gb[A[d>>2]],failOp:Hb[A[d+4>>2]],depthFailOp:Hb[A[d+8>>2]],passOp:Hb[A[d+12>>2]]}}return{label:V(a+4),layout:Db(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),k=Cb(A[d+16>>2],A[d+20>>2]);var g=A[d+24>>2];var n=A[d+28>>2];if(g){for(var l=[],p=0;p<g;++p){var r=l,m=r.push;var t=n+24*p;if(t){var w=A[t+4>>2],x=A[t+16>>
2];if(0===w&&0===x)var J=null;else{J=4294967296*A[t+4+8>>2]+A[t+8>>2];w=Ib[w];t=A[t+20>>2];for(var Jb=[],Sa=0;Sa<x;++Sa){var Kb=Jb,yc=Kb.push,va=t+24*Sa;yc.call(Kb,{format:Lb[A[va+4>>2]],offset:4294967296*A[va+4+8>>2]+A[va+8>>2],shaderLocation:A[va+16>>2]})}J={arrayStride:J,stepMode:w,attributes:Jb}}}else J=void 0;m.call(r,J)}g=l}else g=void 0;return{module:f,constants:k,buffers:g,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Mb[A[d+4>>2]],stripIndexFormat:Nb[A[d+8>>2]],frontFace:Ob[A[d+
12>>2]],cullMode:Pb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Gb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=
U(A[d+4>>2]),k=Cb(A[d+16>>2],A[d+20>>2]),g=A[d+24>>2],n=A[d+28>>2],l=[],p=0;p<g;++p){var r=l,m=r.push,t=n+24*p,w=A[t+4>>2];if(0===w)t=void 0;else{w=W[w];var x=(x=A[t+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;t={format:w,blend:x,writeMask:A[t+16>>2]}}m.call(r,t)}return{module:f,constants:k,targets:l,entryPoint:V(d+8)}}}(A[a+92>>2])}},Rb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",
20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);
ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",
144);void 0!==a.zc&&c("maxImmediateSize",148)},Sb=[,"clamp-to-edge","repeat","mirror-repeat"],Fb=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Eb=[,"add","subtract","reverse-subtract","min","max"],Tb=["binding-not-used",,"uniform","storage","read-only-storage"],Gb=[,"never","less","equal","less-equal","greater",
"not-equal","greater-equal","always"],Ub=[,"opaque","premultiplied","unpremultiplied","inherit"],Pb=[,"none","front","back"],Vb=[,"compatibility","core"],Wb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",
14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Xb=[,"nearest","linear"],Ob=[,"ccw","cw"],Nb=[,"uint16","uint32"],Yb=[,"load","clear"],Zb=[,"nearest","linear"],$b=[,"low-power","high-performance"],ac=[,"srgb","display-p3"],Mb=
[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],bc=["binding-not-used",,"filtering","non-filtering","comparison"],Hb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],cc=["binding-not-used",,"write-only","read-only","read-write"],dc=[,"store","discard"],ec=[,"all","stencil-only","depth-only"],fc=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm",
"rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8",
"bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb",
"astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],gc=["binding-not-used",
,"float","unfilterable-float","depth","sint","uint"],hc=[,"1d","2d","2d-array","cube","cube-array","3d"],ic=[,"standard","extended"],Lb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4",
"sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Ib=[,"vertex","instance"],jc={undefined:1,unknown:1,destroyed:2},kc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";kc.Wb||(kc.Wb={});kc.Wb[a]||(kc.Wb[a]=1,ca&&(a="warning: "+a),h(a))},lc={rgba8unorm:22,bgra8unorm:27},mc={},oc=()=>{if(!nc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",
_:ea||"./this.program"},b;for(b in mc)void 0===mc[b]?delete a[b]:a[b]=mc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);nc=c}return nc},nc,pc=[null,[],[]],qc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Qa;e.pauseMainLoop=cb;e.resumeMainLoop=function(){Ua++;var a=Ma,b=Na,c=H;H=null;bb(c,0,!1,Va,!0);Ta(a,b);I()};e.preMainLoop&&$a.push(e.preMainLoop);e.postMainLoop&&ab.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(h=e.printErr);e.wasmBinary&&(q=e.wasmBinary);
e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
var R,rc,sc,tc,uc,vc,wc,xc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Y,vb,X,Sc={r:function(){return 0},Y:function(){return 0},Z:function(){},aa:()=>ta(""),S:()=>{Ea=!1;Ga=0},T:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];La(()=>Qc(a,performance.now()))},b);G[a]={id:c,Ic:b};return 0},Ha:()=>{cb();H=null},M:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,O:(a,b,c)=>{a=M(a);if(!a)return-4;a=eb(a);C[b>>3]=a.width;C[c>>3]=
a.height;return 0},Ia:()=>performance.now(),Na:(a,b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},U:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},u:(a,b,c,d)=>kb(a,b,c,d,12,"blur"),L:(a,b,c)=>{a=M(a);if(!a)return-4;
a.width=b;a.height=c;return 0},v:(a,b,c,d)=>kb(a,b,c,d,13,"focus"),t:(a,b,c,d)=>{if(!O.fullscreenEnabled())return-1;a=M(a);if(!a)return-4;lb(a,b,c,d,"webkitfullscreenchange");return lb(a,b,c,d,"fullscreenchange")},E:(a,b,c,d)=>mb(a,b,c,d,2,"keydown"),C:(a,b,c,d)=>mb(a,b,c,d,1,"keypress"),D:(a,b,c,d)=>mb(a,b,c,d,3,"keyup"),Oa:(a,b,c)=>{a=N(a);bb(a,b,c)},K:(a,b,c,d)=>ob(a,b,c,d,5,"mousedown"),H:(a,b,c,d)=>ob(a,b,c,d,33,"mouseenter"),G:(a,b,c,d)=>ob(a,b,c,d,34,"mouseleave"),I:(a,b,c,d)=>ob(a,b,c,d,8,
"mousemove"),J:(a,b,c,d)=>ob(a,b,c,d,6,"mouseup"),x:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?pb(a,b,c,d):-4:-1,w:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?qb(a,b,c,d):-4:-1,N:(a,b,c,d)=>rb(a,b,c,d),y:(a,b,c,d)=>sb(a,b,c,d,25,"touchcancel"),z:(a,b,c,d)=>sb(a,b,c,d,23,"touchend"),A:(a,b,c,d)=>sb(a,b,c,d,24,"touchmove"),B:(a,b,c,d)=>sb(a,b,c,d,22,"touchstart"),F:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?tb(a,b,c,d):-1:-4,ea:function(a,b,c,d,f,k){b=-9007199254740992>b||
9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);var g={};if(k){var n=A[k+12>>2];if(n){var l=A[k+16>>2];g.requiredFeatures=Array.from(A.subarray(l>>2,l+4*n>>2),m=>Wb[m])}var p=A[k+20>>2];if(p){var r={};function m(w,x,J=!1){x=A[p+x>>2];4294967295==x||J&&0==x||(r[w]=x)}function t(w,x){x=p+x;var J=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=J)r[w]=4294967296*A[x+4>>2]+A[x>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",
12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",24);m("maxDynamicUniformBuffersPerPipelineLayout",32);m("maxDynamicStorageBuffersPerPipelineLayout",36);m("maxSampledTexturesPerShaderStage",40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);t("maxUniformBufferBindingSize",
64);t("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);t("maxBufferSize",96);m("maxVertexAttributes",104);m("maxVertexBufferArrayStride",108);m("maxInterStageShaderVariables",112);m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",
148,!0);g.requiredLimits=r}if(n=A[k+24>>2])n={label:V(n+4)},g.defaultQueue=n;g.label=V(k+4)}a.requestDevice(g).then(m=>{T(f,m.queue);T(d,m);c&&m.lost.then(t=>{m.onuncapturederror=()=>{};var w=X(),x=S(t.message);Mc(c,jc[t.reason],x);Y(w)});m.onuncapturederror=t=>{var w=5;t.error instanceof GPUValidationError?w=2:t.error instanceof GPUOutOfMemoryError?w=3:t.error instanceof GPUInternalError&&(w=4);var x=X();t=S(t.error.message);Pc(d,w,t);Y(x)};Oc(b,1,d,0)},m=>{var t=X();m=S(m.message);Oc(b,3,d,m);c&&
Mc(c,4,m);Y(t)})},ia:(a,b,c)=>{var d=U(a);0===c&&kc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(g){return 0}var k=Rc(16,f.byteLength);y.fill(0,k,f.byteLength);xb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(k,k+f.byteLength));rc(k)});return k},ha:a=>{var b=U(a),c=xb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete xb[a];b.unmap()}},a:a=>{delete wb[a]},j:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);
try{var f=a.createBuffer(b)}catch(k){return!1}T(c,f);d&&(xb[c]=[]);return!0},da:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=yb(d+8)}T(c,U(a).createShaderModule(b))},ga:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},ba:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return lc[a]},ca:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Vb[A[c+4>>2]],powerPreference:$b[A[c+8>>2]],forceFallbackAdapter:!!A[c+
12>>2]};a=A[c>>2];0!==a&&(f.Lc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(k=>{if(k)T(d,k),Nc(b,1,d,0);else{k=X();var g=S("WebGPU not available on this browser (requestAdapter returned null)");Nc(b,3,d,g);Y(k)}},k=>{var g=X();k=S(k.message);Nc(b,4,d,k);Y(g)}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Nc(b,3,d,a),Y(f))},_:(a,b)=>{var c=0,d=0,f;for(f of oc()){var k=b+c;A[a+d>>2]=k;c+=Q(f,k,Infinity)+1;d+=4}return 0},$:(a,b)=>{var c=oc();
A[a>>2]=c.length;a=0;for(var d of c)a+=ub(d)+1;A[b>>2]=a;return 0},q:()=>52,X:()=>52,V:function(){return 70},W:(a,b,c,d)=>{for(var f=0,k=0;k<c;k++){var g=A[b>>2],n=A[b+4>>2];b+=8;for(var l=0;l<n;l++){var p=a,r=y[g+l],m=pc[p];0===r||10===r?((1===p?ma:h)(F(m)),m.length=0):m.push(r)}f+=n}A[d>>2]=f;return 0},R:Ia,Ta:function(){e.fc=a=>{0!=tc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.fc)},Ka:function(){e.lc=a=>{const b=a.clipboardData.getData("text");qc(()=>{const c=
S(b);sc(c)})};window.addEventListener("paste",e.lc)},xa:function(){e.Fc=[];e.hc=b=>{b.stopPropagation();b.preventDefault()};e.ic=b=>{b.stopPropagation();b.preventDefault()};e.jc=b=>{b.stopPropagation();b.preventDefault()};e.kc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Gc=c;uc(c.length);for(let f=0;f<c.length;f++)qc(()=>{const k=S(c[f].name);vc(f,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);wc(b.clientX,b.clientY,d)};const a=e.Cb;
a.addEventListener("dragenter",e.hc,!1);a.addEventListener("dragleave",e.ic,!1);a.addEventListener("dragover",e.jc,!1);a.addEventListener("drop",e.kc,!1)},Ra:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},h:function(a){e.Eb&&(URL.revokeObjectURL(e.Eb[a].mc),e.Eb[a]=null)},fa:function(a,b){0!==b&&(document.title=b?F(y,b):"");a=a?F(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?db[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
e.Cb=M(a);e.Cb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.Cb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Sa:function(a,b,c,d,f,k){var g=b*c*4,n=138+g;const l=new Uint8Array(n);let p=0;var r=m=>{l[p++]=m&255;l[p++]=m>>8&255;l[p++]=m>>16&255;l[p++]=m>>24&255};l[p++]=66;l[p++]=77;r(n);r(0);r(138);14==p||ta();r(124);r(b);r(c);l[p++]=1;l[p++]=0;l[p++]=32;l[p++]=0;r(3);r(g);r(2835);r(2835);r(0);r(0);r(255);r(65280);r(16711680);
r(4278190080);l[p++]=66;l[p++]=71;l[p++]=82;l[p++]=115;p+=64;138==p||ta();b*=4;for(g=0;g<c;g++)r=d+g*b,n=p+(c-g-1)*b,r=y.slice(r,r+b),l.set(r,n);c=URL.createObjectURL(new Blob([l.buffer],{type:"image/bmp"}));f={nc:`url('${c}') ${f} ${k}, auto`,mc:c};e.Eb||(e.Eb=[].fill(null));e.Eb[a]=f},Pa:function(){window.removeEventListener("beforeunload",e.fc)},Ja:function(){window.removeEventListener("paste",e.lc)},pa:function(){const a=e.Cb;a.removeEventListener("dragenter",e.hc);a.removeEventListener("dragleave",
e.ic);a.removeEventListener("dragover",e.jc);a.removeEventListener("drop",e.kc)},i:function(){e.Cb&&e.Cb.requestPointerLock&&e.Cb.requestPointerLock()},b:function(a,b,c){if(e.Cb){if(0===b)a="none";else if(0!=c)a=e.Eb[a].nc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a=
"not-allowed";break;default:a="auto"}e.Cb.style.cursor=a}},Qa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),k=f.createImageData(a,b);k.data.set(y.subarray(c,c+a*b*4));f.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Fa:function(a){a=a?F(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect",
"off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},Q:function(){return navigator.userAgent.includes("Macintosh")?1:0},P:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},f:(a,b)=>U(a).features.has(Wb[b]),
ya:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:Bb(A[b+12>>2])});a=U(a);b=Dc(0);T(b,a.beginComputePass(c));return b},wa:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],k=A[b+16>>2],g=[],n=0;n<f;++n){var l=g,p=l.push;var r=k+56*n;var m=A[r+4>>2];if(0!==m){var t=z[r+8>>2];-1==t&&(t=void 0);r={view:U(m),depthSlice:t,resolveTarget:U(A[r+12>>2]),clearValue:zb(r+24),loadOp:Yb[A[r+16>>2]],storeOp:dc[A[r+20>>2]]}}else r=void 0;p.call(l,r)}f=A[b+
20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Yb[A[f+8>>2]],depthStoreOp:dc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Yb[A[f+24>>2]],stencilStoreOp:dc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:g,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:Bb(A[b+28>>2]),maxDrawCount:d};a=U(a);d=Gc(0);T(d,a.beginRenderPass(b));return d},ka:a=>{a=U(a);var b=Bc(0);T(b,a.finish());return b},
la:a=>{U(a).end()},d:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},va:(a,b)=>{U(a).setPipeline(U(b))},n:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var k=[],g=0;g<f;++g){var n=k,l=n.push;var p=b+40*g;var r=A[p+8>>2],m=A[p+32>>2],t=A[p+36>>2],w=A[p+4>>2];r?(m=p+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),p={binding:w,resource:{buffer:U(r),offset:4294967296*A[p+4+16>>2]+A[p+16>>2],size:m}}):p=m?{binding:w,resource:U(m)}:{binding:w,
resource:U(t)};l.call(n,p)}c={label:c,layout:d,entries:k};a=U(a);d=zc(0);T(d,a.createBindGroup(c));return d},o:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],k=0;k<d;++k){var g=f,n=g.push,l=b+88*k,p=A[l+4>>2],r=A[l+8>>2];var m=l+24;var t=A[m+4>>2];m=t?{type:Tb[t],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;t=(t=A[l+48+4>>2])?{type:bc[t]}:void 0;var w=l+56;var x=A[w+4>>2];w=x?{sampleType:gc[x],viewDimension:hc[A[w+8>>2]],multisampled:!!A[w+12>>
2]}:void 0;l+=72;l=(x=A[l+4>>2])?{access:cc[x],format:W[A[l+8>>2]],viewDimension:hc[A[l+12>>2]]}:void 0;n.call(g,{binding:p,visibility:r,buffer:m,sampler:t,texture:w,storageTexture:l})}c={label:c,entries:f};a=U(a);d=Ac(0);T(d,a.createBindGroupLayout(c));return d},s:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=Cc(0);T(b,a.createCommandEncoder(c));return b},Aa:(a,b)=>{var c=V(b+4);var d=Db(A[b+12>>2]);b=(b+=16)?{module:U(A[b+4>>2]),constants:Cb(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,
layout:d,compute:b};a=U(a);d=Ec(0);T(d,a.createComputePipeline(c));return d},Ba:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],k=0;k<c;++k)f.push(U(A[d+4*k>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=Fc(0);T(c,a.createPipelineLayout(b));return c},za:(a,b)=>{b=Qb(b);a=U(a);var c=Hc(0);T(c,a.createRenderPipeline(b));return c},Ca:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Sb[A[b+12>>2]],addressModeV:Sb[A[b+16>>2]],addressModeW:Sb[A[b+20>>2]],magFilter:Xb[A[b+24>>2]],minFilter:Xb[A[b+28>>2]],
mipmapFilter:Zb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Gb[A[b+44>>2]],maxAnisotropy:qa[b+48>>1]});a=U(a);b=Ic(0);T(b,a.createSampler(c));return b},p:(a,b)=>{var c={label:V(b+4),size:Ab(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:fc[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=Kc(0);T(d,a.createTexture(c));return d},Ea:(a,b)=>{Rb(U(a).limits,b);return 1},
e:(a,b)=>U(a).features.has(Wb[b]),Ma:(a,b)=>{a=M(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Hc=V(b+4);b=Jc(0);T(b,a);return b},ja:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},k:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},Da:(a,b,c,d,f,k)=>{var g=A[f+8>>2],n=A[f+12>>2],l=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[l>>2],y:A[l+4>>2],z:A[l+8>>2]},aspect:ec[A[b+
20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===g?void 0:g,rowsPerImage:4294967295===n?void 0:n},Ab(k))},na:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},oa:(a,b,c,d,f,k)=>{U(a).drawIndexed(b,c,d>>>0,f,k>>>0)},ma:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ta:(a,b)=>{U(a).setBlendConstant(zb(b))},ra:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<
f?NaN:Number(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Nb[c],d,f)},ua:(a,b)=>{U(a).setPipeline(U(b))},l:(a,b,c,d,f)=>{U(a).setScissorRect(b,c,d,f)},sa:(a,b)=>{U(a).setStencilReference(b>>>0)},qa:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},m:(a,b,c,d,f,k,g)=>{U(a).setViewport(b,c,d,f,k,g)},La:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],
A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Ub[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),k=>W[k])}b=A[b>>2];0!==b&&(c.colorSpace=ac[A[b+8>>2]],c.Jc={mode:ic[A[b+12>>2]]});a.configure(c)},Ga:(a,b)=>{a=U(a);try{var c=Kc(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},g:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+
32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:hc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:ec[A[b+36>>2]]}}a=U(a);b=Lc(0);T(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Ua;sa();gb=Z.Jb;c=Z;R=c.Wa;rc=c.Xa;e.__sapp_emsc_onpaste=sc=c.Ya;e.__sapp_html5_get_ask_leave_site=tc=c.Za;e.__sapp_emsc_begin_drop=uc=c._a;e.__sapp_emsc_drop=vc=c.$a;e.__sapp_emsc_end_drop=wc=c.ab;e.__sapp_emsc_invoke_fetch_cb=c.bb;e.__sapp_emsc_set_fullscreen_flag=c.cb;e._main=xc=c.db;e.__saudio_emsc_pull=c.eb;e.__sfetch_emsc_head_response=c.fb;e.__sfetch_emsc_get_response=c.gb;e.__sfetch_emsc_failed_http_status=c.hb;e.__sfetch_emsc_failed_buffer_too_small=
c.ib;e.__sfetch_emsc_failed_other=c.jb;zc=c.kb;Ac=c.lb;Bc=c.mb;Cc=c.nb;Dc=c.ob;Ec=c.pb;Fc=c.qb;Gc=c.ub;Hc=c.vb;Ic=c.wb;Jc=c.xb;Kc=c.yb;Lc=c.zb;Mc=c.Fb;Nc=c.Gb;Oc=c.Hb;Pc=c.Ib;Qc=c.Kb;Rc=c.Lb;Y=c.Mb;vb=c.Nb;X=c.Ob;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Sc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("cursor-sapp.wasm",ia):ia+"cursor-sapp.wasm";return a((await ya(b)).instance)})();
function Tc(a=[]){var b=xc;a.unshift(ea);var c=a.length,d=vb(4*(c+1)),f=d;a.forEach(g=>{A[f>>2]=S(g);f+=4});A[f>>2]=0;try{var k=b(c,d);Ja(k)}catch(g){Ha(g)}}
function Uc(a=da){function b(){e.calledRun=!0;if(!u){Z.Va();e.onRuntimeInitialized?.();e.noInitialRun||Tc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Uc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Uc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Uc();
