var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),p,r=!1,na,la=a=>a.startsWith("file://"),oa,u,y,pa,qa,z,A,B,C,ra;
function sa(){var a=oa.buffer;u=new Int8Array(a);pa=new Int16Array(a);y=new Uint8Array(a);qa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var D=0,E=null;function ta(a){e.onAbort?.(a);a="Aborted("+a+")";k(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function wa(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=ua;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},Ea=!0,Fa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ga=0,G={},Ha=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ia=a=>{na=a;Ea||0<Ga||(e.onExit?.(a),r=!0);fa(a,new za(a))},Ja=a=>{na=a;Ia(a)},Ka=()=>{if(!(Ea||0<Ga))try{var a=na;na=a;Ia(a)}catch(b){Ha(b)}},La=a=>{if(!r)try{a(),Ka()}catch(b){Ha(b)}},Ta=(a,b)=>{Ma=a;Na=b;if(H)if(Oa||=!0,0==a)J=function(){setTimeout(K,Math.max(0,Pa+b-performance.now())|0)};else if(1==a)J=function(){Qa(K)};else if(2==a){if("undefined"==
typeof Sa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Sa=setImmediate;J=function(){Sa(K)}}},bb=(a,b,c,d,f)=>{function g(){return h<Ua?(Ka(),!1):!0}H=a;Va=d;var h=Ua;Oa=!1;K=function(){if(!r)if(0<Wa.length){var l=
Wa.shift();l.pc(l.hc);if(Xa){var n=Xa,t=0==n%1?n-1:Math.floor(n);Xa=l.jc?t:(8*n+(t+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",n=Xa??0,t=Ya.nc??0,n?n<t?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));g()&&setTimeout(K,0)}else if(g())if(Za=Za+1|0,1==Ma&&1<Na&&0!=Za%Na)J();else{0==Ma&&(Pa=performance.now());a:if(!r){for(l of $a)if(!1===l())break a;La(a);for(n of ab)n()}g()&&J()}};f||(0<b?Ta(0,1E3/b):Ta(1,1),J());if(c)throw"unwind";},Oa=!1,J=
null,Ua=0,H=null,Va=0,Ma=0,Na=0,Za=0,Wa=[],$a=[],ab=[];function cb(){J=null;Ua++}var L=0;function Qa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===L)L=b+1E3/60;else for(;b+2>=L;)L+=1E3/60;setTimeout(a,Math.max(L-b,0))}}
var Ya={},Pa,K,Sa,Xa,db=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?F(y,a):"":a;return db[a]||("undefined"!=typeof document?document.querySelector(a):null)},eb=a=>0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},fb=[],gb,N=a=>{var b=fb[a];b||(fb[a]=b=gb.get(a));return b};function hb(a){var b=O.ob[a];b.target.removeEventListener(b.lb,b.Wb,b.qb);O.ob.splice(a,1)}
function ib(){if(navigator.userActivation?navigator.userActivation.isActive:O.Nb&&O.fc.Bb){var a=O.yb;O.yb=[];for(var b of a)b.Rb(...b.Vb)}}function P(a){if(!a.target)return-4;if(a.xb)a.Wb=function(c){++O.Nb;O.fc=a;ib();a.zb(c);ib();--O.Nb},a.target.addEventListener(a.lb,a.Wb,a.qb),O.ob.push(a);else for(var b=0;b<O.ob.length;++b)O.ob[b].target==a.target&&O.ob[b].lb==a.lb&&hb(b--);return 0}function jb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var O={ic:0,qc:0,Ob:0,Ab:0,Ub:0,Tb:0,Mb:0,mc:0,tc:0,lc:0,oc:0,Pb:0,Cc:0,Sb:0,sc(a,b,c){u.set(u.subarray(b,b+c),a)},uc(){for(;O.ob.length;)hb(O.ob.length-1);O.yb=[]},Nb:0,yb:[],kc(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var l in g)if(g[l]!=h[l])return!1;return!0}for(var f of O.yb)if(f.Rb==a&&d(f.Vb,c))return;O.yb.push({Rb:a,Zb:b,Vb:c});O.yb.sort((g,h)=>g.Zb<h.Zb)},wc(a){O.yb=O.yb.filter(b=>b.Rb!=a)},ob:[],vc:(a,b)=>{for(var c=0;c<O.ob.length;++c)O.ob[c].target!=a||b&&b!=O.ob[c].lb||
hb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Q=(a,b,c)=>{var d=y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;g++}}d[b]=0;return b-
f},kb=(a,b,c,d,f,g)=>{O.Mb||(O.Mb=R(256));a={target:M(a),lb:g,xb:d,zb:(h=event)=>{var l=h.target.id?h.target.id:"",n=O.Mb;Q(jb(h.target),n+0,128);Q(l,n+128,128);N(d)(f,n,b)&&h.preventDefault()},qb:c};return P(a)},lb=(a,b,c,d,f,g)=>{O.Ob||(O.Ob=R(160));a={target:M(a),lb:g,xb:d,zb:h=>{var l=O.Ob;C[l>>3]=h.timeStamp;var n=l>>2;z[n+2]=h.location;u[l+12]=h.ctrlKey;u[l+13]=h.shiftKey;u[l+14]=h.altKey;u[l+15]=h.metaKey;u[l+16]=h.repeat;z[n+5]=h.charCode;z[n+6]=h.keyCode;z[n+7]=h.which;Q(h.key||"",l+32,32);
Q(h.code||"",l+64,32);Q(h.char||"",l+96,32);Q(h.locale||"",l+128,32);N(d)(f,l,b)&&h.preventDefault()},qb:c};return P(a)},mb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=eb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,f,g)=>{O.Ab||(O.Ab=R(64));a=M(a);return P({target:a,
Bb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,lb:g,xb:d,zb:(h=event)=>{mb(O.Ab,h,a);N(d)(f,O.Ab,b)&&h.preventDefault()},qb:c})},ob=(a,b,c,d)=>{O.Pb||(O.Pb=R(257));return P({target:a,lb:"pointerlockchange",xb:d,zb:(f=event)=>{var g=O.Pb,h=document.pointerLockElement;u[g]=!!h;var l=h?.id||"";Q(jb(h),g+1,128);Q(l,g+129,128);N(d)(20,g,b)&&f.preventDefault()},qb:c})},pb=(a,b,c,d)=>P({target:a,lb:"pointerlockerror",xb:d,zb:(f=event)=>{N(d)(38,0,b)&&f.preventDefault()},qb:c}),qb=(a,b,c,d)=>{O.Tb||
(O.Tb=R(36));a=M(a);return P({target:a,lb:"resize",xb:d,zb:(f=event)=>{if(f.target==a){var g=document.body;if(g){var h=O.Tb;z[h>>2]=0;z[h+4>>2]=g.clientWidth;z[h+8>>2]=g.clientHeight;z[h+12>>2]=innerWidth;z[h+16>>2]=innerHeight;z[h+20>>2]=outerWidth;z[h+24>>2]=outerHeight;z[h+28>>2]=pageXOffset|0;z[h+32>>2]=pageYOffset|0;N(d)(10,h,b)&&f.preventDefault()}}},qb:c})},rb=(a,b,c,d,f,g)=>{O.Sb||(O.Sb=R(1552));a=M(a);return P({target:a,Bb:"touchstart"==g||"touchend"==g,lb:g,xb:d,zb:h=>{var l={},n=h.touches;
for(var t of n)t.Xb=t.Yb=0,l[t.identifier]=t;for(var v of h.changedTouches)v.Xb=1,l[v.identifier]=v;for(var m of h.targetTouches)l[m.identifier].Yb=1;n=O.Sb;C[n>>3]=h.timeStamp;u[n+12]=h.ctrlKey;u[n+13]=h.shiftKey;u[n+14]=h.altKey;u[n+15]=h.metaKey;t=n+16;v=eb(a);m=0;for(let q of Object.values(l))if(l=t>>2,z[l]=q.identifier,z[l+1]=q.screenX,z[l+2]=q.screenY,z[l+3]=q.clientX,z[l+4]=q.clientY,z[l+5]=q.pageX,z[l+6]=q.pageY,u[t+28]=q.Xb,u[t+29]=q.Yb,z[l+8]=q.clientX-(v.left|0),z[l+9]=q.clientY-(v.top|
0),t+=48,31<++m)break;z[n+8>>2]=m;N(d)(f,n,b)&&h.preventDefault()},qb:c})},sb=(a,b,c,d)=>{O.Ub||(O.Ub=R(96));return P({target:a,Bb:!0,lb:"wheel",xb:d,zb:(f=event)=>{var g=O.Ub;mb(g,f,a);C[g+64>>3]=f.deltaX;C[g+72>>3]=f.deltaY;C[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;N(d)(9,g,b)&&f.preventDefault()},qb:c})},tb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},S=a=>{var b=tb(a)+1,c=ub(b);Q(a,c,b);return c},vb=[],T=(a,b)=>
{vb[a>>>=0]=b},wb=[],U=a=>{if(a)return vb[a>>>0]},xb=a=>{var b=A[a>>2];return b?F(y,b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?F(y,b,a):"";if(0===a)return""},yb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),zb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Ab=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,g=xb(f+4);c[g]=C[f+16>>3]}return c}},Bb=a=>a?U(a):"auto",Ob=a=>{function b(d){if(d)return{operation:Cb[A[d>>2]],srcFactor:Db[A[d+4>>2]],dstFactor:Db[A[d+
8>>2]]}}function c(d){return{compare:Eb[A[d>>2]],failOp:Fb[A[d+4>>2]],depthFailOp:Fb[A[d+8>>2]],passOp:Fb[A[d+12>>2]]}}return{label:V(a+4),layout:Bb(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),g=Ab(A[d+16>>2],A[d+20>>2]);var h=A[d+24>>2];var l=A[d+28>>2];if(h){for(var n=[],t=0;t<h;++t){var v=n,m=v.push;var q=l+24*t;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var I=null;else{I=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Gb[w];q=A[q+20>>2];for(var Jb=[],Ra=0;Ra<x;++Ra){var Kb=Jb,Ac=Kb.push,
va=q+24*Ra;Ac.call(Kb,{format:Hb[A[va+4>>2]],offset:4294967296*A[va+4+8>>2]+A[va+8>>2],shaderLocation:A[va+16>>2]})}I={arrayStride:I,stepMode:w,attributes:Jb}}}else I=void 0;m.call(v,I)}h=n}else h=void 0;return{module:f,constants:g,buffers:h,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Ib[A[d+4>>2]],stripIndexFormat:Lb[A[d+8>>2]],frontFace:Mb[A[d+12>>2]],cullMode:Nb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+4>>2]],depthWriteEnabled:!!A[d+
8>>2],depthCompare:Eb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),g=Ab(A[d+16>>2],A[d+20>>2]),h=A[d+24>>2],l=A[d+28>>2],n=[],t=0;t<h;++t){var v=n,m=v.push,q=l+24*t,w=A[q+4>>2];if(0===w)q=
void 0;else{w=W[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}m.call(v,q)}return{module:f,constants:g,targets:n,entryPoint:V(d+8)}}}(A[a+92>>2])}},Pb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",
32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",
104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.rc&&c("maxImmediateSize",148)},Qb=[,"clamp-to-edge","repeat","mirror-repeat"],Db=[,"zero","one","src","one-minus-src",
"src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Cb=[,"add","subtract","reverse-subtract","min","max"],Rb=["binding-not-used",,"uniform","storage","read-only-storage"],Eb=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Sb=[,"opaque","premultiplied","unpremultiplied","inherit"],Nb=[,"none","front","back"],Tb=
[,"compatibility","core"],Ub={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",
20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Vb=[,"nearest","linear"],Mb=[,"ccw","cw"],Lb=[,"uint16","uint32"],Wb=[,"load","clear"],Xb=[,"nearest","linear"],Yb=[,"low-power","high-performance"],Zb=[,"srgb","display-p3"],Ib=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],$b=["binding-not-used",,"filtering","non-filtering","comparison"],
Fb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],ac=["binding-not-used",,"write-only","read-only","read-write"],bc=[,"store","discard"],cc=[,"all","stencil-only","depth-only"],dc=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb",
"rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm",
"bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm",
"astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],ec=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],fc=[,"1d","2d","2d-array","cube","cube-array","3d"],gc=[,"standard","extended"],
Hb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Gb=[,"vertex","instance"],hc={undefined:1,unknown:1,
destroyed:2},ic=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";ic.Qb||(ic.Qb={});ic.Qb[a]||(ic.Qb[a]=1,ca&&(a="warning: "+a),k(a))},jc={rgba8unorm:22,bgra8unorm:27},kc={},mc=()=>{if(!lc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in kc)void 0===kc[b]?delete a[b]:a[b]=kc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);lc=c}return lc},
lc,nc=[null,[],[]],oc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Qa;e.pauseMainLoop=cb;e.resumeMainLoop=function(){Ua++;var a=Ma,b=Na,c=H;H=null;bb(c,0,!1,Va,!0);Ta(a,b);J()};e.preMainLoop&&$a.push(e.preMainLoop);e.postMainLoop&&ab.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(k=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
var pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,R,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Y,ub,X,Uc={q:function(){return 0},_:function(){return 0},$:function(){},ca:()=>ta(""),T:()=>{Ea=!1;Ga=0},U:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];La(()=>Sc(a,performance.now()))},b);G[a]={id:c,Ac:b};return 0},Fa:()=>{cb();H=null},N:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,P:(a,b,c)=>{a=M(a);if(!a)return-4;a=eb(a);C[b>>3]=a.width;
C[c>>3]=a.height;return 0},Ga:()=>performance.now(),La:(a,b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},V:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},v:(a,b,c,d)=>kb(a,b,c,d,12,"blur"),M:(a,b,c)=>{a=M(a);if(!a)return-4;
a.width=b;a.height=c;return 0},w:(a,b,c,d)=>kb(a,b,c,d,13,"focus"),F:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),D:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),E:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),Na:(a,b,c)=>{a=N(a);bb(a,b,c)},L:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),I:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),H:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),J:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),K:(a,b,c,d)=>nb(a,b,c,d,6,"mouseup"),y:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?ob(a,b,c,d):-4:-1,x:(a,b,c,d)=>document.body?.requestPointerLock?
(a=M(a))?pb(a,b,c,d):-4:-1,O:(a,b,c,d)=>qb(a,b,c,d),z:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),A:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),B:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),C:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),G:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?sb(a,b,c,d):-1:-4,ga:function(a,b,c,d,f,g){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);var h={};if(g){var l=A[g+12>>2];if(l){var n=A[g+16>>2];h.requiredFeatures=
Array.from(A.subarray(n>>2,n+4*l>>2),m=>Ub[m])}var t=A[g+20>>2];if(t){var v={};function m(w,x,I=!1){x=A[t+x>>2];4294967295==x||I&&0==x||(v[w]=x)}function q(w,x){x=t+x;var I=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=I)v[w]=4294967296*A[x+4>>2]+A[x>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",24);m("maxDynamicUniformBuffersPerPipelineLayout",32);m("maxDynamicStorageBuffersPerPipelineLayout",
36);m("maxSampledTexturesPerShaderStage",40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);q("maxBufferSize",96);m("maxVertexAttributes",104);m("maxVertexBufferArrayStride",108);m("maxInterStageShaderVariables",112);
m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",148,!0);h.requiredLimits=v}if(l=A[g+24>>2])l={label:V(l+4)},h.defaultQueue=l;h.label=V(g+4)}a.requestDevice(h).then(m=>{T(f,m.queue);T(d,m);c&&m.lost.then(q=>{m.onuncapturederror=()=>
{};var w=X(),x=S(q.message);Oc(c,hc[q.reason],x);Y(w)});m.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=X();q=S(q.error.message);Rc(d,w,q);Y(x)};Qc(b,1,d,0)},m=>{var q=X();m=S(m.message);Qc(b,3,d,m);c&&Oc(c,4,m);Y(q)})},ja:(a,b,c)=>{var d=U(a);0===c&&ic();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(h){return 0}var g=Tc(16,f.byteLength);y.fill(0,g,f.byteLength);wb[a].push(()=>
{(new Uint8Array(f)).set(y.subarray(g,g+f.byteLength));Bc(g)});return g},ia:a=>{var b=U(a),c=wb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete wb[a];b.unmap()}},a:a=>{delete vb[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(g){return!1}T(c,f);d&&(wb[c]=[]);return!0},fa:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=xb(d+8)}T(c,U(a).createShaderModule(b))},
ha:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},da:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return jc[a]},ea:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Tb[A[c+4>>2]],powerPreference:Yb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Dc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(g=>{if(g)T(d,g),Pc(b,1,d,0);else{g=X();var h=S("WebGPU not available on this browser (requestAdapter returned null)");
Pc(b,3,d,h);Y(g)}},g=>{var h=X();g=S(g.message);Pc(b,4,d,g);Y(h)}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Pc(b,3,d,a),Y(f))},aa:(a,b)=>{var c=0,d=0,f;for(f of mc()){var g=b+c;A[a+d>>2]=g;c+=Q(f,g,Infinity)+1;d+=4}return 0},ba:(a,b)=>{var c=mc();A[a>>2]=c.length;a=0;for(var d of c)a+=tb(d)+1;A[b>>2]=a;return 0},p:()=>52,Y:()=>52,W:function(){return 70},X:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var h=A[b>>2],l=A[b+4>>2];b+=8;for(var n=0;n<l;n++){var t=a,v=y[h+
n],m=nc[t];0===v||10===v?((1===t?ma:k)(F(m)),m.length=0):m.push(v)}f+=l}A[d>>2]=f;return 0},S:Ia,Ra:function(){e.$b=a=>{0!=qc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.$b)},Ma:function(){e.ec=a=>{const b=a.clipboardData.getData("text");oc(()=>{const c=S(b);pc(c)})};window.addEventListener("paste",e.ec)},Ca:function(){e.xc=[];e.ac=b=>{b.stopPropagation();b.preventDefault()};e.bc=b=>{b.stopPropagation();b.preventDefault()};e.cc=b=>{b.stopPropagation();b.preventDefault()};
e.dc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.yc=c;rc(c.length);for(let f=0;f<c.length;f++)oc(()=>{const g=S(c[f].name);sc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);tc(b.clientX,b.clientY,d)};const a=e.pb;a.addEventListener("dragenter",e.ac,!1);a.addEventListener("dragleave",e.bc,!1);a.addEventListener("dragover",e.cc,!1);a.addEventListener("drop",e.dc,!1)},Pa:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},na:function(a,b){0!==b&&(document.title=b?F(y,b):"");a=a?F(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?db[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.pb=M(a);e.pb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.pb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Qa:function(){window.removeEventListener("beforeunload",e.$b)},Ia:function(){window.removeEventListener("paste",
e.ec)},va:function(){const a=e.pb;a.removeEventListener("dragenter",e.ac);a.removeEventListener("dragleave",e.bc);a.removeEventListener("dragover",e.cc);a.removeEventListener("drop",e.dc)},h:function(){e.pb&&e.pb.requestPointerLock&&e.pb.requestPointerLock()},Z:function(a,b){if(e.pb){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a=
"nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.pb.style.cursor=a}},Oa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(y.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ha:function(a){a=a?F(y,a):"";const b=
document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},o:function(a,b,c,d,f,g){const h=b?F(y,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(h,{method:"GET",headers:b}).then(l=>
{l.ok?l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=g?(y.set(n,f),wc(a,d,n.length)):yc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,n);zc(a)}):xc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,l);zc(a)})},R:function(a,b){const c=b?F(y,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),zc(a)):vc(a,Number(d))):xc(a,d.status)}).catch(d=>
{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);zc(a)})},r:function(){return navigator.userAgent.includes("Macintosh")?1:0},Q:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},e:(a,b)=>U(a).features.has(Ub[b]),wa:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],h=[],l=0;l<f;++l){var n=h,t=n.push;var v=g+56*l;var m=A[v+
4>>2];if(0!==m){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:U(m),depthSlice:q,resolveTarget:U(A[v+12>>2]),clearValue:yb(v+24),loadOp:Wb[A[v+16>>2]],storeOp:bc[A[v+20>>2]]}}else v=void 0;t.call(n,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Wb[A[f+8>>2]],depthStoreOp:bc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Wb[A[f+24>>2]],stencilStoreOp:bc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;g=A[b+28>>2];g=0!==g?{querySet:U(A[g+
4>>2]),beginningOfPassWriteIndex:A[g+8>>2],endOfPassWriteIndex:A[g+12>>2]}:void 0;b={label:c,colorAttachments:h,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:g,maxDrawCount:d};a=U(a);d=Ic(0);T(d,a.beginRenderPass(b));return d},la:a=>{a=U(a);var b=Ec(0);T(b,a.finish());return b},ma:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ua:(a,b)=>{U(a).setPipeline(U(b))},l:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+
20>>2];for(var g=[],h=0;h<f;++h){var l=g,n=l.push;var t=b+40*h;var v=A[t+8>>2],m=A[t+32>>2],q=A[t+36>>2],w=A[t+4>>2];v?(m=t+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),t={binding:w,resource:{buffer:U(v),offset:4294967296*A[t+4+16>>2]+A[t+16>>2],size:m}}):t=m?{binding:w,resource:U(m)}:{binding:w,resource:U(q)};n.call(l,t)}c={label:c,layout:d,entries:g};a=U(a);d=Cc(0);T(d,a.createBindGroup(c));return d},m:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],g=0;g<d;++g){var h=f,l=h.push,
n=b+88*g,t=A[n+4>>2],v=A[n+8>>2];var m=n+24;var q=A[m+4>>2];m=q?{type:Rb[q],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;q=(q=A[n+48+4>>2])?{type:$b[q]}:void 0;var w=n+56;var x=A[w+4>>2];w=x?{sampleType:ec[x],viewDimension:fc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;n+=72;n=(x=A[n+4>>2])?{access:ac[x],format:W[A[n+8>>2]],viewDimension:fc[A[n+12>>2]]}:void 0;l.call(h,{binding:t,visibility:v,buffer:m,sampler:q,texture:w,storageTexture:n})}c={label:c,entries:f};
a=U(a);d=Dc(0);T(d,a.createBindGroupLayout(c));return d},u:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=Fc(0);T(b,a.createCommandEncoder(c));return b},ya:(a,b)=>{var c=V(b+4);var d=Bb(A[b+12>>2]);b=(b+=16)?{module:U(A[b+4>>2]),constants:Ab(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=Gc(0);T(d,a.createComputePipeline(c));return d},za:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],g=0;g<c;++g)f.push(U(A[d+4*g>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);
c=Hc(0);T(c,a.createPipelineLayout(b));return c},xa:(a,b)=>{b=Ob(b);a=U(a);var c=Jc(0);T(c,a.createRenderPipeline(b));return c},Aa:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Qb[A[b+12>>2]],addressModeV:Qb[A[b+16>>2]],addressModeW:Qb[A[b+20>>2]],magFilter:Vb[A[b+24>>2]],minFilter:Vb[A[b+28>>2]],mipmapFilter:Xb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Eb[A[b+44>>2]],maxAnisotropy:qa[b+48>>1]});a=U(a);b=Kc(0);T(b,a.createSampler(c));return b},n:(a,b)=>{var c={label:V(b+4),
size:zb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:dc[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=Mc(0);T(d,a.createTexture(c));return d},Da:(a,b)=>{Pb(U(a).limits,b);return 1},d:(a,b)=>U(a).features.has(Ub[b]),Ka:(a,b)=>{a=M(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.zc=V(b+4);b=Lc(0);T(b,a);return b},ka:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),
d=>U(d));a.submit(b)},i:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},Ba:(a,b,c,d,f,g)=>{var h=A[f+8>>2],l=A[f+12>>2],n=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[n>>2],y:A[n+4>>2],z:A[n+8>>2]},aspect:cc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===h?void 0:h,rowsPerImage:4294967295===l?void 0:l},zb(g))},s:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>
0)},t:(a,b,c,d,f,g)=>{U(a).drawIndexed(b,c,d>>>0,f,g>>>0)},oa:a=>{U(a).end()},b:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},sa:(a,b)=>{U(a).setBlendConstant(yb(b))},qa:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Lb[c],d,f)},ta:(a,b)=>{U(a).setPipeline(U(b))},j:(a,b,c,d,f)=>{U(a).setScissorRect(b,c,d,f)},ra:(a,b)=>{U(a).setStencilReference(b>>>
0)},pa:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},k:(a,b,c,d,f,g,h)=>{U(a).setViewport(b,c,d,f,g,h)},Ja:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Sb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=
Array.from(z.subarray(f>>2,f+4*d>>2),g=>W[g])}b=A[b>>2];0!==b&&(c.colorSpace=Zb[A[b+8>>2]],c.Bc={mode:gc[A[b+12>>2]]});a.configure(c)},Ea:(a,b)=>{a=U(a);try{var c=Mc(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:fc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:cc[A[b+
36>>2]]}}a=U(a);b=Nc(0);T(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Sa;sa();gb=Z.Gb;c=Z;e.__sapp_emsc_onpaste=pc=c.Ua;e.__sapp_html5_get_ask_leave_site=qc=c.Va;e.__sapp_emsc_begin_drop=rc=c.Wa;e.__sapp_emsc_drop=sc=c.Xa;e.__sapp_emsc_end_drop=tc=c.Ya;e.__sapp_emsc_invoke_fetch_cb=c.Za;e._main=uc=c._a;e.__saudio_emsc_pull=c.$a;e.__sfetch_emsc_head_response=vc=c.ab;e.__sfetch_emsc_get_response=wc=c.bb;e.__sfetch_emsc_failed_http_status=xc=c.cb;e.__sfetch_emsc_failed_buffer_too_small=yc=c.db;e.__sfetch_emsc_failed_other=
zc=c.eb;R=c.fb;Bc=c.gb;Cc=c.hb;Dc=c.ib;Ec=c.jb;Fc=c.kb;Gc=c.mb;Hc=c.nb;Ic=c.rb;Jc=c.sb;Kc=c.tb;Lc=c.ub;Mc=c.vb;Nc=c.wb;Oc=c.Cb;Pc=c.Db;Qc=c.Eb;Rc=c.Fb;Sc=c.Hb;Tc=c.Ib;Y=c.Jb;ub=c.Kb;X=c.Lb;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Uc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("loadpng-sapp-ui.wasm",ia):ia+"loadpng-sapp-ui.wasm";return a((await ya(b)).instance)})();
function Vc(a=[]){var b=uc;a.unshift(ea);var c=a.length,d=ub(4*(c+1)),f=d;a.forEach(h=>{A[f>>2]=S(h);f+=4});A[f>>2]=0;try{var g=b(c,d);Ja(g)}catch(h){Ha(h)}}
function Wc(a=da){function b(){e.calledRun=!0;if(!r){Z.Ta();e.onRuntimeInitialized?.();e.noInitialRun||Vc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Wc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Wc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Wc();
