var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),h=console.error.bind(console),m,q=!1,na,la=a=>a.startsWith("file://"),u,w,oa,z,A,pa,B,qa;
function ra(){var a=sa.buffer;u=new Int8Array(a);oa=new Int16Array(a);w=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);pa=new Float32Array(a);B=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function xa(a){var b=ua;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(e)},Aa=[],Ba=[],Ca=()=>{var a=e.preRun.shift();Ba.push(a)},C=0,D=null,Da=!0,Ea=globalThis.TextDecoder&&new TextDecoder,E=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|k);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|g:(f&7)<<18|k<<12|g<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Fa=0,F={},Ga=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Da||0<Fa||(e.onExit?.(a),q=!0);fa(a,new ya(a))},Ia=()=>{if(!(Da||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},G=a=>{if(!q)try{a(),Ia()}catch(b){Ga(b)}},Pa=(a,b)=>{Ja=a;Ka=b;if(H)if(La||=!0,0==a)I=function(){setTimeout(J,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)I=function(){Na(J)};else if(2==a){if(!Oa)if(globalThis.setImmediate)Oa=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}I=function(){Oa(J)}}},Za=(a,b,c,d,f)=>{function k(){return g<Ra?(Ia(),!1):!0}H=a;Sa=d;var g=Ra;La=!1;J=function(){if(!q)if(0<Ta.length){var l=Ta.shift();l.cc(l.Ub);if(Ua){var p=
Ua,r=0==p%1?p-1:Math.floor(p);Ua=l.Xb?r:(8*p+(r+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",p=Ua??0,r=Va.bc??0,p?p<r?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));k()&&setTimeout(J,0)}else if(k())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)I();else{0==Ja&&(Ma=performance.now());a:if(!q){for(l of Xa)if(!1===l())break a;G(a);for(p of Ya)p()}k()&&I()}};f||(0<b?Pa(0,1E3/b):Pa(1,1),I());if(c)throw"unwind";},La=!1,I=null,Ra=0,H=null,Sa=0,Ja=0,Ka=0,Wa=0,
Ta=[],Xa=[],Ya=[];function $a(){I=null;Ra++}var K=0;function Na(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===K)K=b+1E3/60;else for(;b+2>=K;)K+=1E3/60;setTimeout(a,Math.max(K-b,0))}}var Va={},Ma,J,Oa,Ua,ab=[0,globalThis.document??0,globalThis.window??0],L=a=>{a=2<a?a?E(w,a):"":a;return ab[a]||globalThis.document?.querySelector(a)},bb=a=>0>ab.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},cb=[],M=a=>{var b=cb[a];b||(cb[a]=b=db.get(a));return b};
function eb(a){var b=N.Wa[a];b.target.removeEventListener(b.$a,b.Ib,b.cb);N.Wa.splice(a,1)}function fb(){if(navigator.userActivation?navigator.userActivation.isActive:N.Ab&&N.Sb.xb){var a=N.lb;N.lb=[];for(var b of a)b.Db(...b.Hb)}}function O(a){if(!a.target)return-4;if(a.ab)a.Ib=function(c){++N.Ab;N.Sb=a;fb();a.fb(c);fb();--N.Ab},a.target.addEventListener(a.$a,a.Ib,a.cb),N.Wa.push(a);else for(var b=0;b<N.Wa.length;++b)N.Wa[b].target==a.target&&N.Wa[b].$a==a.$a&&eb(b--);return 0}
function gb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var N={Vb:0,dc:0,Bb:0,mb:0,Gb:0,Fb:0,yb:0,ac:0,fc:0,$b:0,zb:0,Cb:0,qc:0,Eb:0,hc(){for(;N.Wa.length;)eb(N.Wa.length-1);N.lb=[]},Ab:0,lb:[],Zb(a,b,c){function d(k,g){if(k.length!=g.length)return!1;for(var l in k)if(k[l]!=g[l])return!1;return!0}for(var f of N.lb)if(f.Db==a&&d(f.Hb,c))return;N.lb.push({Db:a,Lb:b,Hb:c});N.lb.sort((k,g)=>k.Lb<g.Lb)},jc(a){N.lb=N.lb.filter(b=>b.Db!=a)},Wa:[],ic:(a,b)=>{for(var c=0;c<N.Wa.length;++c)N.Wa[c].target!=a||b&&b!=N.Wa[c].$a||eb(c--)},kc(a){let b=!1;for(let c=0;c<
N.Wa.length;++c){const d=N.Wa[c];d.target===a.target&&d.bb===a.bb&&d.ab===a.ab&&d.eb===a.eb&&(eb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},P=(a,b,c)=>{var d=w;if(!(0<c))return 0;var f=b;c=b+c-1;for(var k=0;k<a.length;++k){var g=a.codePointAt(k);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&
63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;k++}}d[b]=0;return b-f},hb=(a,b,c,d,f,k)=>{N.yb||(N.yb=Q(256));a={target:L(a),$a:k,bb:f,eb:b,ab:d,fb:g=>{var l=g.target.id?g.target.id:"",p=N.yb;P(gb(g.target),p+0,128);P(l,p+128,128);M(d)(f,p,b)&&g.preventDefault()},cb:c};return O(a)},ib=(a,b,c,d,f)=>{N.zb||(N.zb=Q(276));return O({target:a,$a:f,bb:19,eb:b,ab:d,fb:k=>{var g=N.zb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement||document.msFullscreenElement,p=!!l;u[g]=p;u[g+1]=N.fullscreenEnabled();var r=p?l:N.Tb,v=r?.id||"";P(gb(r),g+2,128);P(v,g+130,128);z[g+260>>2]=r?r.clientWidth:0;z[g+264>>2]=r?r.clientHeight:0;z[g+268>>2]=screen.width;z[g+272>>2]=screen.height;p&&(N.Tb=l);M(d)(19,g,b)&&k.preventDefault()},cb:c})},jb=(a,b,c,d,f,k)=>{N.Bb||(N.Bb=Q(160));a={target:L(a),$a:k,bb:f,eb:b,ab:d,fb:g=>{var l=N.Bb;B[l>>3]=g.timeStamp;var p=l>>2;z[p+2]=g.location;u[l+12]=g.ctrlKey;u[l+13]=
g.shiftKey;u[l+14]=g.altKey;u[l+15]=g.metaKey;u[l+16]=g.repeat;z[p+5]=g.charCode;z[p+6]=g.keyCode;z[p+7]=g.which;P(g.key||"",l+32,32);P(g.code||"",l+64,32);P(g.char||"",l+96,32);P(g.locale||"",l+128,32);M(d)(f,l,b)&&g.preventDefault()},cb:c};return O(a)},kb=(a,b,c)=>{B[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+
9]=b.movementY;a=bb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},R=(a,b,c,d,f,k)=>{N.mb||(N.mb=Q(64));a=L(a);return O({target:a,xb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,$a:k,bb:f,eb:b,ab:d,fb:g=>{kb(N.mb,g,a);M(d)(f,N.mb,b)&&g.preventDefault()},cb:c})},lb=(a,b,c,d)=>{N.Cb||(N.Cb=Q(257));return O({target:a,$a:"pointerlockchange",bb:20,eb:b,ab:d,fb:f=>{var k=N.Cb,g=document.pointerLockElement;u[k]=!!g;var l=g?.id||"";P(gb(g),k+1,128);P(l,k+129,128);M(d)(20,k,b)&&f.preventDefault()},
cb:c})},mb=(a,b,c,d)=>O({target:a,$a:"pointerlockerror",bb:38,eb:b,ab:d,fb:f=>{M(d)(38,0,b)&&f.preventDefault()},cb:c}),nb=(a,b,c,d)=>{N.Fb||(N.Fb=Q(36));a=L(a);return O({target:a,$a:"resize",bb:10,eb:b,ab:d,fb:f=>{if(f.target==a){var k=document.body;if(k){var g=N.Fb;z[g>>2]=0;z[g+4>>2]=k.clientWidth;z[g+8>>2]=k.clientHeight;z[g+12>>2]=innerWidth;z[g+16>>2]=innerHeight;z[g+20>>2]=outerWidth;z[g+24>>2]=outerHeight;z[g+28>>2]=pageXOffset|0;z[g+32>>2]=pageYOffset|0;M(d)(10,g,b)&&f.preventDefault()}}},
cb:c})},ob=(a,b,c,d,f,k)=>{N.Eb||(N.Eb=Q(1552));a=L(a);return O({target:a,xb:"touchstart"==k||"touchend"==k,$a:k,bb:f,eb:b,ab:d,fb:g=>{var l={},p=g.touches;for(var r of p)r.Jb=r.Kb=0,l[r.identifier]=r;for(var v of g.changedTouches)v.Jb=1,l[v.identifier]=v;for(var n of g.targetTouches)l[n.identifier].Kb=1;p=N.Eb;B[p>>3]=g.timeStamp;u[p+12]=g.ctrlKey;u[p+13]=g.shiftKey;u[p+14]=g.altKey;u[p+15]=g.metaKey;r=p+16;v=bb(a);n=0;for(let t of Object.values(l))if(l=r>>2,z[l]=t.identifier,z[l+1]=t.screenX,z[l+
2]=t.screenY,z[l+3]=t.clientX,z[l+4]=t.clientY,z[l+5]=t.pageX,z[l+6]=t.pageY,u[r+28]=t.Jb,u[r+29]=t.Kb,z[l+8]=t.clientX-(v.left|0),z[l+9]=t.clientY-(v.top|0),r+=48,31<++n)break;z[p+8>>2]=n;M(d)(f,p,b)&&g.preventDefault()},cb:c})},pb=(a,b,c,d)=>{N.Gb||(N.Gb=Q(96));return O({target:a,xb:!0,$a:"wheel",bb:9,eb:b,ab:d,fb:f=>{var k=N.Gb;kb(k,f,a);B[k+64>>3]=f.deltaX;B[k+72>>3]=f.deltaY;B[k+80>>3]=f.deltaZ;z[k+88>>2]=f.deltaMode;M(d)(9,k,b)&&f.preventDefault()},cb:c})},qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=
a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},S=a=>{var b=qb(a)+1,c=rb(b);P(a,c,b);return c},T=[],sb=(a,b)=>{T[a>>>0]=b},U=a=>{if(a)return T[a>>>0]},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?E(w,b,a):"";if(0===a)return""},tb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),ub=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},vb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",
4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",
80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",
136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.ec&&c("maxImmediateSize",148)},wb=[,"opaque","premultiplied","unpremultiplied","inherit"],xb=[,"compatibility","core"],yb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",
11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},zb=[,"load","clear"],Ab=[,"low-power","high-performance"],Bb=[,"srgb","display-p3"],Cb=
[,"store","discard"],Db=[,"all","stencil-only","depth-only"],Eb=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint",
"rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm",
"etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb",
"astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],Fb=[,"1d","2d","2d-array","cube","cube-array","3d"],Gb=[,"standard","extended"],Hb={undefined:1,unknown:1,destroyed:2},Ib={rgba8unorm:22,bgra8unorm:27},Jb={},Lb=()=>{if(!Kb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||
"./this.program"},b;for(b in Jb)void 0===Jb[b]?delete a[b]:a[b]=Jb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Kb=c}return Kb},Kb,Mb=[null,[],[]],Nb=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Na;e.pauseMainLoop=$a;e.resumeMainLoop=function(){Ra++;var a=Ja,b=Ka,c=H;H=null;Za(c,0,!1,Sa,!0);Pa(a,b);I()};e.preMainLoop&&Xa.push(e.preMainLoop);e.postMainLoop&&Ya.push(e.postMainLoop);e.noExitRuntime&&(Da=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(h=e.printErr);e.wasmBinary&&(m=e.wasmBinary);
e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var Ob,Pb,Qb,Rb,Sb,Tb,Ub,Q,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,Z,cc,dc,ec,Y,rb,X,sa,db,fc={h:function(){return 0},U:function(){return 0},V:function(){},X:()=>ta(""),L:()=>{Da=!1;Fa=0},M:(a,b)=>{F[a]&&(clearTimeout(F[a].id),delete F[a]);if(!b)return 0;var c=setTimeout(()=>{delete F[a];G(()=>ec(a,performance.now()))},b);F[a]={id:c,oc:b};return 0},na:()=>{$a();H=null},W:()=>Date.now(),E:()=>globalThis.devicePixelRatio??1,G:(a,b,c)=>{a=L(a);if(!a)return-4;a=bb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},f:()=>
performance.now(),oa:()=>performance.now(),ua:(a,b)=>{function c(d){M(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},N:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},l:(a,b,c,d)=>hb(a,b,c,d,12,"blur"),D:(a,b,c)=>{a=L(a);if(!a)return-4;
a.width=b;a.height=c;return 0},m:(a,b,c,d)=>hb(a,b,c,d,13,"focus"),k:(a,b,c,d)=>{if(!N.fullscreenEnabled())return-1;a=L(a);if(!a)return-4;ib(a,b,c,d,"webkitfullscreenchange");return ib(a,b,c,d,"fullscreenchange")},v:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),t:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),u:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),va:(a,b,c)=>{a=M(a);Za(a,b,c)},B:(a,b,c,d)=>R(a,b,c,d,5,"mousedown"),y:(a,b,c,d)=>R(a,b,c,d,33,"mouseenter"),x:(a,b,c,d)=>R(a,b,c,d,34,"mouseleave"),z:(a,b,c,d)=>R(a,b,c,d,8,"mousemove"),
A:(a,b,c,d)=>R(a,b,c,d,6,"mouseup"),o:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?lb(a,b,c,d):-4:-1,n:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?mb(a,b,c,d):-4:-1,F:(a,b,c,d)=>nb(a,b,c,d),p:(a,b,c,d)=>ob(a,b,c,d,25,"touchcancel"),q:(a,b,c,d)=>ob(a,b,c,d,23,"touchend"),r:(a,b,c,d)=>ob(a,b,c,d,24,"touchmove"),s:(a,b,c,d)=>ob(a,b,c,d,22,"touchstart"),w:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?pb(a,b,c,d):-1:-4,$:function(a,b,c,d,f,k){b=-9007199254740992>b||9007199254740992<
b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);var g={};if(k){var l=A[k+12>>2];if(l){var p=A[k+16>>2];g.requiredFeatures=Array.from(A.subarray(p>>2,p+4*l>>2),n=>yb[n])}var r=A[k+20>>2];if(r){var v={};function n(x,y,Qa=!1){y=A[r+y>>2];4294967295==y||Qa&&0==y||(v[x]=y)}function t(x,y){y=r+y;var Qa=A[y+4>>2];if(4294967295!=A[y>>2]||4294967295!=Qa)v[x]=4294967296*A[y+4>>2]+A[y>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",8);n("maxTextureDimension3D",12);n("maxTextureArrayLayers",
16);n("maxBindGroups",20);n("maxBindGroupsPlusVertexBuffers",24);n("maxDynamicUniformBuffersPerPipelineLayout",32);n("maxDynamicStorageBuffersPerPipelineLayout",36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);t("maxUniformBufferBindingSize",64);t("maxStorageBufferBindingSize",
72);n("maxVertexBuffers",88);t("maxBufferSize",96);n("maxVertexAttributes",104);n("maxVertexBufferArrayStride",108);n("maxInterStageShaderVariables",112);n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",148,!0);g.requiredLimits=v}if(l=
A[k+24>>2])l={label:V(l+4)},g.defaultQueue=l;g.label=V(k+4)}a.requestDevice(g).then(n=>{G(()=>{T[f>>>0]=n.queue;T[d>>>0]=n;n.lost.then(t=>{G(()=>{n.onuncapturederror=()=>{};var x=X(),y=S(t.message);bc(c,Hb[t.reason],y);Y(x)})});n.onuncapturederror=t=>{var x=5;t.error instanceof GPUValidationError?x=2:t.error instanceof GPUOutOfMemoryError?x=3:t.error instanceof GPUInternalError&&(x=4);var y=X();t=S(t.error.message);dc(d,x,t);Y(y)};cc(b,1,d,0)})},n=>{G(()=>{var t=X(),x=S(n.message);cc(b,3,d,x);c&&
bc(c,4,x);Y(t)})})},a:a=>{delete T[a]},_:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(k){return!1}T[c>>>0]=f;return!0},aa:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},Y:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return Ib[a]},Z:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:xb[A[c+4>>2]],powerPreference:Ab[A[c+8>>2]],
forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.rc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(k=>{G(()=>{if(k)T[d>>>0]=k,Z(b,1,d,0);else{var g=X(),l=S("WebGPU not available on this browser (requestAdapter returned null)");Z(b,3,d,l);Y(g)}})},k=>{G(()=>{var g=X(),l=S(k.message);Z(b,4,d,l);Y(g)})}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Z(b,3,d,a),Y(f))},Q:(a,b)=>{var c=0,d=0,f;for(f of Lb()){var k=b+c;A[a+d>>2]=k;c+=P(f,k,
Infinity)+1;d+=4}return 0},R:(a,b)=>{var c=Lb();A[a>>2]=c.length;a=0;for(var d of c)a+=qb(d)+1;A[b>>2]=a;return 0},g:()=>52,T:()=>52,P:function(){return 70},S:(a,b,c,d)=>{for(var f=0,k=0;k<c;k++){var g=A[b>>2],l=A[b+4>>2];b+=8;for(var p=0;p<l;p++){var r=a,v=w[g+p],n=Mb[r];0===v||10===v?((1===r?ma:h)(E(n)),n.length=0):n.push(v)}f+=l}A[d>>2]=f;return 0},K:Ha,Da:function(){e.Mb=a=>{0!=Pb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Mb)},wa:function(){e.Rb=a=>{const b=
a.clipboardData.getData("text");Nb(()=>{const c=S(b);Ob(c)})};window.addEventListener("paste",e.Rb)},pa:function(){e.lc=[];e.Nb=b=>{b.stopPropagation();b.preventDefault()};e.Ob=b=>{b.stopPropagation();b.preventDefault()};e.Pb=b=>{b.stopPropagation();b.preventDefault()};e.Qb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.mc=c;Qb(c.length);for(let f=0;f<c.length;f++)Nb(()=>{const k=S(c[f].name);Rb(f,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&
(d|=8);Sb(b.clientX,b.clientY,d)};const a=e.jb;a.addEventListener("dragenter",e.Nb,!1);a.addEventListener("dragleave",e.Ob,!1);a.addEventListener("dragover",e.Pb,!1);a.addEventListener("drop",e.Qb,!1)},Ba:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},J:function(a){e.nb&&(URL.revokeObjectURL(e.nb[a].Wb),e.nb[a]=null)},ea:function(a,b){0!==b&&(document.title=b?E(w,b):"");a=a?E(w,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?ab[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
e.jb=L(a);e.jb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.jb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ca:function(){window.removeEventListener("beforeunload",e.Mb)},qa:function(){window.removeEventListener("paste",e.Rb)},ma:function(){const a=e.jb;a.removeEventListener("dragenter",e.Nb);a.removeEventListener("dragleave",e.Ob);a.removeEventListener("dragover",e.Pb);a.removeEventListener("drop",e.Qb)},d:function(){e.jb&&
e.jb.requestPointerLock&&e.jb.requestPointerLock()},O:function(a,b,c){if(e.jb){if(0===b)a="none";else if(0!=c)a=e.nb[a].Yb;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.jb.style.cursor=a}},Aa:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const f=d.getContext("2d"),k=f.createImageData(a,b);k.data.set(w.subarray(c,c+a*b*4));f.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},xa:function(){return e.kb?e.kb.bufferSize:0},za:function(a,b,c){e.Va=null;e.kb=null;"undefined"!==typeof AudioContext?e.Va=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Va=null,console.log("sokol_audio.h: no WebAudio support"));
return e.Va?(console.log("sokol_audio.h: sample rate ",e.Va.sampleRate),e.kb=e.Va.createScriptProcessor(c,0,b),e.kb.onaudioprocess=d=>{const f=d.outputBuffer.length,k=Ub(f);if(k){const g=d.outputBuffer.numberOfChannels;for(let l=0;l<g;l++){const p=d.outputBuffer.getChannelData(l);for(let r=0;r<f;r++)p[r]=pa[(k>>2)+(g*r+l)]}}},e.kb.connect(e.Va.destination),a=()=>{e.Va&&"suspended"===e.Va.state&&e.Va.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),
document.addEventListener("keydown",a,{once:!0}),1):0},ya:function(){return e.Va?e.Va.sampleRate:0},I:function(){const a=e.Va;null!==a&&(e.kb&&e.kb.disconnect(),a.close(),e.Va=null,e.kb=null)},H:function(a,b){b=b?E(w,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},ra:(a,b)=>{vb(U(a).limits,b);return 1},c:(a,b)=>U(a).features.has(yb[b]),ia:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:ub(A[b+12>>2])});b=U(a);a=Xb(0);
c=b.beginComputePass(c);T[a>>>0]=c;return a},ha:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],k=A[b+16>>2],g=[],l=0;l<f;++l){var p=g,r=p.push;var v=k+56*l;var n=A[v+4>>2];if(0!==n){var t=z[v+8>>2];-1==t&&(t=void 0);var x=v+24;v={view:U(n),depthSlice:t,resolveTarget:U(A[v+12>>2]),clearValue:{r:B[x>>3],g:B[x+8>>3],b:B[x+16>>3],a:B[x+24>>3]},loadOp:zb[A[v+16>>2]],storeOp:Cb[A[v+20>>2]]}}else v=void 0;r.call(p,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+
4>>2]),depthClearValue:pa[f+16>>2],depthLoadOp:zb[A[f+8>>2]],depthStoreOp:Cb[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:zb[A[f+24>>2]],stencilStoreOp:Cb[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:g,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:ub(A[b+28>>2]),maxDrawCount:d};d=U(a);a=Yb(0);b=d.beginRenderPass(b);T[a>>>0]=b;return a},da:a=>{var b=U(a);a=Vb(0);b=b.finish();T[a>>>0]=b;return a},fa:a=>{U(a).end()},
j:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ja:(a,b)=>{var c;b&&(c={label:V(b+4)});b=U(a);a=Wb(0);c=b.createCommandEncoder(c);T[a>>>0]=c;return a},C:(a,b)=>{var c={label:V(b+4),size:tb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:Eb[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=$b(0);sb(d,a.createTexture(c));return d},ka:(a,b)=>{vb(U(a).limits,
b);return 1},b:(a,b)=>U(a).features.has(yb[b]),ta:(a,b)=>{a=L(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.nc=V(b+4);b=Zb(0);T[b>>>0]=a;return b},ca:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},ba:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,w.subarray(d,d+f),0,f)},ga:a=>{U(a).end()},i:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},sa:(a,b)=>{var c=A[b+4>>2];a=U(a);
var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:wb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),k=>W[k])}b=A[b>>2];0!==b&&(c.colorSpace=Bb[A[b+8>>2]],c.pc={mode:Gb[A[b+12>>2]]});a.configure(c)},la:(a,b)=>{a=U(a);try{var c=$b(0),d=a.getCurrentTexture();T[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},e:(a,b)=>{if(b){var c=
A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:Fb[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Db[A[b+36>>2]]}}b=U(a);a=ac(0);b=b.createView(c);T[a>>>0]=b;return a}};function gc(a=[]){var b=Tb;a.unshift(ea);var c=a.length,d=rb(4*(c+1)),f=d,k;for(k of a)A[f>>2]=S(k),f+=4;A[f>>2]=0;try{var g=b(c,d);na=g;Ha(g)}catch(l){Ga(l)}}
function hc(a=da){function b(){e.calledRun=!0;if(!q){ic.Fa();e.onRuntimeInitialized?.();e.noInitialRun||gc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Aa.push(c)}za(Aa)}}if(0<C)D=hc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ca();za(Ba);0<C?D=hc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var ic;
(async function(){function a(c){c=ic=c.exports;Ob=e.__sapp_emsc_onpaste=c.Ga;Pb=e.__sapp_html5_get_ask_leave_site=c.Ha;Qb=e.__sapp_emsc_begin_drop=c.Ia;Rb=e.__sapp_emsc_drop=c.Ja;Sb=e.__sapp_emsc_end_drop=c.Ka;e.__sapp_emsc_invoke_fetch_cb=c.La;e.__sapp_emsc_set_fullscreen_flag=c.Ma;Tb=e._main=c.Na;Ub=e.__saudio_emsc_pull=c.Oa;e.__sfetch_emsc_head_response=c.Pa;e.__sfetch_emsc_get_response=c.Qa;e.__sfetch_emsc_failed_http_status=c.Ra;e.__sfetch_emsc_failed_buffer_too_small=c.Sa;e.__sfetch_emsc_failed_other=
c.Ta;Q=c.Ua;Vb=c.Xa;Wb=c.Ya;Xb=c.Za;Yb=c.db;Zb=c.gb;$b=c.hb;ac=c.ib;bc=c.ob;Z=c.pb;cc=c.qb;dc=c.rb;ec=c.tb;Y=c.ub;rb=c.vb;X=c.wb;sa=c.Ea;db=c.sb;ra();C--;e.monitorRunDependencies?.(C);0==C&&D&&(c=D,D=null,c());return ic}C++;e.monitorRunDependencies?.(C);var b={a:fc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("modplay-sapp.wasm",ia):ia+"modplay-sapp.wasm";return a((await xa(b)).instance)})();hc();
