var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),g=console.error.bind(console),p,r=!1,na,la=a=>a.startsWith("file://"),oa,u,x,pa,z,A,qa,B,ra;
function sa(){var a=oa.buffer;u=new Int8Array(a);pa=new Int16Array(a);x=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);qa=new Float32Array(a);B=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var C=0,D=null;function ta(a){e.onAbort?.(a);a="Aborted("+a+")";g(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function xa(a){var b=ua;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(e)},Aa=[],Ba=[],Ca=()=>{var a=e.preRun.shift();Ba.push(a)},Da=!0,Ea="undefined"!=typeof TextDecoder?new TextDecoder:void 0,E=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|k);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|h:(f&7)<<18|k<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Fa=0,F={},Ga=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Da||0<Fa||(e.onExit?.(a),r=!0);fa(a,new ya(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Da||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!r)try{a(),Ja()}catch(b){Ga(b)}},Ra=(a,b)=>{La=a;Ma=b;if(G)if(Na||=!0,0==a)H=function(){setTimeout(I,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)H=function(){Pa(I)};else if(2==a){if("undefined"==
typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qa=setImmediate;H=function(){Qa(I)}}},ab=(a,b,c,d,f)=>{function k(){return h<Ta?(Ja(),!1):!0}G=a;Ua=d;var h=Ta;Na=!1;I=function(){if(!r)if(0<Va.length){var l=
Va.shift();l.bc(l.Tb);if(Wa){var n=Wa,q=0==n%1?n-1:Math.floor(n);Wa=l.Wb?q:(8*n+(q+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",n=Wa??0,q=Xa.ac??0,n?n<q?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));k()&&setTimeout(I,0)}else if(k())if(Ya=Ya+1|0,1==La&&1<Ma&&0!=Ya%Ma)H();else{0==La&&(Oa=performance.now());a:if(!r){for(l of Za)if(!1===l())break a;Ka(a);for(n of $a)n()}k()&&H()}};f||(0<b?Ra(0,1E3/b):Ra(1,1),H());if(c)throw"unwind";},Na=!1,H=
null,Ta=0,G=null,Ua=0,La=0,Ma=0,Ya=0,Va=[],Za=[],$a=[];function bb(){H=null;Ta++}var J=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===J)J=b+1E3/60;else for(;b+2>=J;)J+=1E3/60;setTimeout(a,Math.max(J-b,0))}}
var Xa={},Oa,I,Qa,Wa,cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?E(x,a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):null)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],fb,L=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};function gb(a){var b=M.$a[a];b.target.removeEventListener(b.Za,b.Hb,b.ab);M.$a.splice(a,1)}
function hb(){if(navigator.userActivation?navigator.userActivation.isActive:M.zb&&M.Rb.wb){var a=M.kb;M.kb=[];for(var b of a)b.Cb(...b.Gb)}}function N(a){if(!a.target)return-4;if(a.bb)a.Hb=function(c){++M.zb;M.Rb=a;hb();a.eb(c);hb();--M.zb},a.target.addEventListener(a.Za,a.Hb,a.ab),M.$a.push(a);else for(var b=0;b<M.$a.length;++b)M.$a[b].target==a.target&&M.$a[b].Za==a.Za&&gb(b--);return 0}function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={Ub:0,cc:0,Ab:0,lb:0,Fb:0,Eb:0,xb:0,$b:0,fc:0,Zb:0,yb:0,Bb:0,pc:0,Db:0,ec(a,b,c){u.set(u.subarray(b,b+c),a)},hc(){for(;M.$a.length;)gb(M.$a.length-1);M.kb=[]},zb:0,kb:[],Yb(a,b,c){function d(k,h){if(k.length!=h.length)return!1;for(var l in k)if(k[l]!=h[l])return!1;return!0}for(var f of M.kb)if(f.Cb==a&&d(f.Gb,c))return;M.kb.push({Cb:a,Kb:b,Gb:c});M.kb.sort((k,h)=>k.Kb<h.Kb)},jc(a){M.kb=M.kb.filter(b=>b.Cb!=a)},$a:[],ic:(a,b)=>{for(var c=0;c<M.$a.length;++c)M.$a[c].target!=a||b&&b!=M.$a[c].Za||
gb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},O=(a,b,c)=>{var d=x;if(!(0<c))return 0;var f=b;c=b+c-1;for(var k=0;k<a.length;++k){var h=a.codePointAt(k);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;k++}}d[b]=0;return b-
f},jb=(a,b,c,d,f,k)=>{M.xb||(M.xb=P(256));a={target:K(a),Za:k,bb:d,eb:(h=event)=>{var l=h.target.id?h.target.id:"",n=M.xb;O(ib(h.target),n+0,128);O(l,n+128,128);L(d)(f,n,b)&&h.preventDefault()},ab:c};return N(a)},kb=(a,b,c,d,f)=>{M.yb||(M.yb=P(276));return N({target:a,Za:f,bb:d,eb:(k=event)=>{var h=M.yb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;u[h]=n;u[h+1]=M.fullscreenEnabled();
var q=n?l:M.Sb,v=q?.id||"";O(ib(q),h+2,128);O(v,h+130,128);z[h+260>>2]=q?q.clientWidth:0;z[h+264>>2]=q?q.clientHeight:0;z[h+268>>2]=screen.width;z[h+272>>2]=screen.height;n&&(M.Sb=l);L(d)(19,h,b)&&k.preventDefault()},ab:c})},lb=(a,b,c,d,f,k)=>{M.Ab||(M.Ab=P(160));a={target:K(a),Za:k,bb:d,eb:h=>{var l=M.Ab;B[l>>3]=h.timeStamp;var n=l>>2;z[n+2]=h.location;u[l+12]=h.ctrlKey;u[l+13]=h.shiftKey;u[l+14]=h.altKey;u[l+15]=h.metaKey;u[l+16]=h.repeat;z[n+5]=h.charCode;z[n+6]=h.keyCode;z[n+7]=h.which;O(h.key||
"",l+32,32);O(h.code||"",l+64,32);O(h.char||"",l+96,32);O(h.locale||"",l+128,32);L(d)(f,l,b)&&h.preventDefault()},ab:c};return N(a)},mb=(a,b,c)=>{B[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=db(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},Q=(a,b,c,d,f,k)=>{M.lb||(M.lb=P(64));a=
K(a);return N({target:a,wb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Za:k,bb:d,eb:(h=event)=>{mb(M.lb,h,a);L(d)(f,M.lb,b)&&h.preventDefault()},ab:c})},nb=(a,b,c,d)=>{M.Bb||(M.Bb=P(257));return N({target:a,Za:"pointerlockchange",bb:d,eb:(f=event)=>{var k=M.Bb,h=document.pointerLockElement;u[k]=!!h;var l=h?.id||"";O(ib(h),k+1,128);O(l,k+129,128);L(d)(20,k,b)&&f.preventDefault()},ab:c})},ob=(a,b,c,d)=>N({target:a,Za:"pointerlockerror",bb:d,eb:(f=event)=>{L(d)(38,0,b)&&f.preventDefault()},ab:c}),
pb=(a,b,c,d)=>{M.Eb||(M.Eb=P(36));a=K(a);return N({target:a,Za:"resize",bb:d,eb:(f=event)=>{if(f.target==a){var k=document.body;if(k){var h=M.Eb;z[h>>2]=0;z[h+4>>2]=k.clientWidth;z[h+8>>2]=k.clientHeight;z[h+12>>2]=innerWidth;z[h+16>>2]=innerHeight;z[h+20>>2]=outerWidth;z[h+24>>2]=outerHeight;z[h+28>>2]=pageXOffset|0;z[h+32>>2]=pageYOffset|0;L(d)(10,h,b)&&f.preventDefault()}}},ab:c})},qb=(a,b,c,d,f,k)=>{M.Db||(M.Db=P(1552));a=K(a);return N({target:a,wb:"touchstart"==k||"touchend"==k,Za:k,bb:d,eb:h=>
{var l={},n=h.touches;for(var q of n)q.Ib=q.Jb=0,l[q.identifier]=q;for(var v of h.changedTouches)v.Ib=1,l[v.identifier]=v;for(var m of h.targetTouches)l[m.identifier].Jb=1;n=M.Db;B[n>>3]=h.timeStamp;u[n+12]=h.ctrlKey;u[n+13]=h.shiftKey;u[n+14]=h.altKey;u[n+15]=h.metaKey;q=n+16;v=db(a);m=0;for(let t of Object.values(l))if(l=q>>2,z[l]=t.identifier,z[l+1]=t.screenX,z[l+2]=t.screenY,z[l+3]=t.clientX,z[l+4]=t.clientY,z[l+5]=t.pageX,z[l+6]=t.pageY,u[q+28]=t.Ib,u[q+29]=t.Jb,z[l+8]=t.clientX-(v.left|0),z[l+
9]=t.clientY-(v.top|0),q+=48,31<++m)break;z[n+8>>2]=m;L(d)(f,n,b)&&h.preventDefault()},ab:c})},rb=(a,b,c,d)=>{M.Fb||(M.Fb=P(96));return N({target:a,wb:!0,Za:"wheel",bb:d,eb:(f=event)=>{var k=M.Fb;mb(k,f,a);B[k+64>>3]=f.deltaX;B[k+72>>3]=f.deltaY;B[k+80>>3]=f.deltaZ;z[k+88>>2]=f.deltaMode;L(d)(9,k,b)&&f.preventDefault()},ab:c})},sb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},R=a=>{var b=sb(a)+1,c=tb(b);O(a,c,b);return c},
ub=[],S=(a,b)=>{ub[a>>>=0]=b},T=a=>{if(a)return ub[a>>>0]},U=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?E(x,b,a):"";if(0===a)return""},vb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),wb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",
32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",
104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.dc&&c("maxImmediateSize",148)},xb=["binding-not-used",,"uniform","storage","read-only-storage"],yb=[,"opaque","premultiplied",
"unpremultiplied","inherit"],zb=[,"compatibility","core"],Ab={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",
18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Bb=[,"load","clear"],Cb=[,"low-power","high-performance"],Db=[,"srgb","display-p3"],Eb=["binding-not-used",,"filtering","non-filtering","comparison"],Fb=["binding-not-used",,"write-only","read-only","read-write"],Gb=[,"store","discard"],Hb=[,"all","stencil-only","depth-only"],
Ib=[,"1d","2d","3d"],V=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float",
"rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb",
"eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm",
"astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],Jb=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],Kb=[,"1d","2d","2d-array","cube","cube-array","3d"],Lb=[,"standard","extended"],Mb={undefined:1,unknown:1,destroyed:2},Nb={rgba8unorm:22,bgra8unorm:27},Ob={},Qb=()=>{if(!Pb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-",
"_")+".UTF-8",_:ea||"./this.program"},b;for(b in Ob)void 0===Ob[b]?delete a[b]:a[b]=Ob[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Pb=c}return Pb},Pb,Rb=[null,[],[]],Sb=a=>{var b=W();a();X(b)};e.requestAnimationFrame=Pa;e.pauseMainLoop=bb;e.resumeMainLoop=function(){Ta++;var a=La,b=Ma,c=G;G=null;ab(c,0,!1,Ua,!0);Ra(a,b);H()};e.preMainLoop&&Za.push(e.preMainLoop);e.postMainLoop&&$a.push(e.postMainLoop);e.noExitRuntime&&(Da=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(g=e.printErr);
e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
var Tb,Ub,Vb,Wb,Xb,Yb,Zb,P,$b,ac,bc,cc,dc,ec,fc,gc,hc,Y,ic,jc,kc,X,tb,W,lc={h:function(){return 0},U:function(){return 0},V:function(){},X:()=>ta(""),L:()=>{Da=!1;Fa=0},M:(a,b)=>{F[a]&&(clearTimeout(F[a].id),delete F[a]);if(!b)return 0;var c=setTimeout(()=>{delete F[a];Ka(()=>kc(a,performance.now()))},b);F[a]={id:c,nc:b};return 0},na:()=>{bb();G=null},W:()=>Date.now(),E:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,G:(a,b,c)=>{a=K(a);if(!a)return-4;a=db(a);B[b>>3]=a.width;B[c>>3]=a.height;
return 0},f:()=>performance.now(),oa:()=>performance.now(),ta:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},O:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},l:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),D:(a,b,c)=>{a=K(a);
if(!a)return-4;a.width=b;a.height=c;return 0},m:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),k:(a,b,c,d)=>{if(!M.fullscreenEnabled())return-1;a=K(a);if(!a)return-4;kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},v:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),t:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),u:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),ua:(a,b,c)=>{a=L(a);ab(a,b,c)},B:(a,b,c,d)=>Q(a,b,c,d,5,"mousedown"),y:(a,b,c,d)=>Q(a,b,c,d,33,"mouseenter"),x:(a,b,c,d)=>Q(a,b,c,d,34,"mouseleave"),z:(a,b,c,d)=>
Q(a,b,c,d,8,"mousemove"),A:(a,b,c,d)=>Q(a,b,c,d,6,"mouseup"),o:(a,b,c,d)=>document.body?.requestPointerLock?(a=K(a))?nb(a,b,c,d):-4:-1,n:(a,b,c,d)=>document.body?.requestPointerLock?(a=K(a))?ob(a,b,c,d):-4:-1,F:(a,b,c,d)=>pb(a,b,c,d),p:(a,b,c,d)=>qb(a,b,c,d,25,"touchcancel"),q:(a,b,c,d)=>qb(a,b,c,d,23,"touchend"),r:(a,b,c,d)=>qb(a,b,c,d,24,"touchmove"),s:(a,b,c,d)=>qb(a,b,c,d,22,"touchstart"),w:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?rb(a,b,c,d):-1:-4,$:function(a,b,c,d,f,k){b=-9007199254740992>
b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=T(a);var h={};if(k){var l=A[k+12>>2];if(l){var n=A[k+16>>2];h.requiredFeatures=Array.from(A.subarray(n>>2,n+4*l>>2),m=>Ab[m])}var q=A[k+20>>2];if(q){var v={};function m(w,y,Sa=!1){y=A[q+y>>2];4294967295==y||Sa&&0==y||(v[w]=y)}function t(w,y){y=q+y;var Sa=A[y+4>>2];if(4294967295!=A[y>>2]||4294967295!=Sa)v[w]=4294967296*A[y+4>>2]+A[y>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",
12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",24);m("maxDynamicUniformBuffersPerPipelineLayout",32);m("maxDynamicStorageBuffersPerPipelineLayout",36);m("maxSampledTexturesPerShaderStage",40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);t("maxUniformBufferBindingSize",
64);t("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);t("maxBufferSize",96);m("maxVertexAttributes",104);m("maxVertexBufferArrayStride",108);m("maxInterStageShaderVariables",112);m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",
148,!0);h.requiredLimits=v}if(l=A[k+24>>2])l={label:U(l+4)},h.defaultQueue=l;h.label=U(k+4)}a.requestDevice(h).then(m=>{S(f,m.queue);S(d,m);c&&m.lost.then(t=>{m.onuncapturederror=()=>{};var w=W(),y=R(t.message);hc(c,Mb[t.reason],y);X(w)});m.onuncapturederror=t=>{var w=5;t.error instanceof GPUValidationError?w=2:t.error instanceof GPUOutOfMemoryError?w=3:t.error instanceof GPUInternalError&&(w=4);var y=W();t=R(t.error.message);jc(d,w,t);X(y)};ic(b,1,d,0)},m=>{var t=W();m=R(m.message);ic(b,3,d,m);c&&
hc(c,4,m);X(t)})},a:a=>{delete ub[a]},_:(a,b,c)=>{var d=!!A[b+32>>2];b={label:U(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=T(a);try{var f=a.createBuffer(b)}catch(k){return!1}S(c,f);return!0},aa:a=>{a=T(a);a.onuncapturederror=null;a.destroy()},Y:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return Nb[a]},Z:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:zb[A[c+4>>2]],powerPreference:Cb[A[c+8>>2]],forceFallbackAdapter:!!A[c+
12>>2]};a=A[c>>2];0!==a&&(f.qc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(k=>{if(k)S(d,k),Y(b,1,d,0);else{k=W();var h=R("WebGPU not available on this browser (requestAdapter returned null)");Y(b,3,d,h);X(k)}},k=>{var h=W();k=R(k.message);Y(b,4,d,k);X(h)}):(f=W(),a=R("WebGPU not available on this browser (navigator.gpu is not available)"),Y(b,3,d,a),X(f))},Q:(a,b)=>{var c=0,d=0,f;for(f of Qb()){var k=b+c;A[a+d>>2]=k;c+=O(f,k,Infinity)+1;d+=4}return 0},R:(a,b)=>{var c=Qb();
A[a>>2]=c.length;a=0;for(var d of c)a+=sb(d)+1;A[b>>2]=a;return 0},g:()=>52,T:()=>52,P:function(){return 70},S:(a,b,c,d)=>{for(var f=0,k=0;k<c;k++){var h=A[b>>2],l=A[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=a,v=x[h+n],m=Rb[q];0===v||10===v?((1===q?ma:g)(E(m)),m.length=0):m.push(v)}f+=l}A[d>>2]=f;return 0},K:Ha,Ca:function(){e.Lb=a=>{0!=Ub()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Lb)},va:function(){e.Qb=a=>{const b=a.clipboardData.getData("text");Sb(()=>{const c=
R(b);Tb(c)})};window.addEventListener("paste",e.Qb)},pa:function(){e.kc=[];e.Mb=b=>{b.stopPropagation();b.preventDefault()};e.Nb=b=>{b.stopPropagation();b.preventDefault()};e.Ob=b=>{b.stopPropagation();b.preventDefault()};e.Pb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.lc=c;Vb(c.length);for(let f=0;f<c.length;f++)Sb(()=>{const k=R(c[f].name);Wb(f,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Xb(b.clientX,b.clientY,d)};const a=e.ib;
a.addEventListener("dragenter",e.Mb,!1);a.addEventListener("dragleave",e.Nb,!1);a.addEventListener("dragover",e.Ob,!1);a.addEventListener("drop",e.Pb,!1)},Aa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},J:function(a){e.mb&&(URL.revokeObjectURL(e.mb[a].Vb),e.mb[a]=null)},da:function(a,b){0!==b&&(document.title=b?E(x,b):"");a=a?E(x,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?cb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
e.ib=K(a);e.ib||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.ib.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ba:function(){window.removeEventListener("beforeunload",e.Lb)},qa:function(){window.removeEventListener("paste",e.Qb)},la:function(){const a=e.ib;a.removeEventListener("dragenter",e.Mb);a.removeEventListener("dragleave",e.Nb);a.removeEventListener("dragover",e.Ob);a.removeEventListener("drop",e.Pb)},d:function(){e.ib&&
e.ib.requestPointerLock&&e.ib.requestPointerLock()},N:function(a,b,c){if(e.ib){if(0===b)a="none";else if(0!=c)a=e.mb[a].Xb;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.ib.style.cursor=a}},za:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const f=d.getContext("2d"),k=f.createImageData(a,b);k.data.set(x.subarray(c,c+a*b*4));f.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},wa:function(){return e.jb?e.jb.bufferSize:0},ya:function(a,b,c){e.Ya=null;e.jb=null;"undefined"!==typeof AudioContext?e.Ya=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Ya=null,console.log("sokol_audio.h: no WebAudio support"));
return e.Ya?(console.log("sokol_audio.h: sample rate ",e.Ya.sampleRate),e.jb=e.Ya.createScriptProcessor(c,0,b),e.jb.onaudioprocess=d=>{const f=d.outputBuffer.length,k=Zb(f);if(k){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const n=d.outputBuffer.getChannelData(l);for(let q=0;q<f;q++)n[q]=qa[(k>>2)+(h*q+l)]}}},e.jb.connect(e.Ya.destination),a=()=>{e.Ya&&"suspended"===e.Ya.state&&e.Ya.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),
document.addEventListener("keydown",a,{once:!0}),1):0},xa:function(){return e.Ya?e.Ya.sampleRate:0},I:function(){const a=e.Ya;null!==a&&(e.jb&&e.jb.disconnect(),a.close(),e.Ya=null,e.jb=null)},H:function(a,b){b=b?E(x,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},c:(a,b)=>T(a).features.has(Ab[b]),ha:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=U(b+4);for(var f=A[b+12>>2],k=A[b+16>>2],
h=[],l=0;l<f;++l){var n=h,q=n.push;var v=k+56*l;var m=A[v+4>>2];if(0!==m){var t=z[v+8>>2];-1==t&&(t=void 0);var w=v+24;v={view:T(m),depthSlice:t,resolveTarget:T(A[v+12>>2]),clearValue:{r:B[w>>3],g:B[w+8>>3],b:B[w+16>>3],a:B[w+24>>3]},loadOp:Bb[A[v+16>>2]],storeOp:Gb[A[v+20>>2]]}}else v=void 0;q.call(n,v)}f=A[b+20>>2];f=0!==f?{view:T(A[f+4>>2]),depthClearValue:qa[f+16>>2],depthLoadOp:Bb[A[f+8>>2]],depthStoreOp:Gb[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Bb[A[f+
24>>2]],stencilStoreOp:Gb[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;k=A[b+28>>2];k=0!==k?{querySet:T(A[k+4>>2]),beginningOfPassWriteIndex:A[k+8>>2],endOfPassWriteIndex:A[k+12>>2]}:void 0;b={label:c,colorAttachments:h,depthStencilAttachment:f,occlusionQuerySet:T(A[b+24>>2]),timestampWrites:k,maxDrawCount:d};a=T(a);d=dc(0);S(d,a.beginRenderPass(b));return d},ea:a=>{a=T(a);var b=bc(0);S(b,a.finish());return b},fa:a=>{T(a).end()},ja:(a,b)=>{var c=U(b+4),d=T(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];
for(var k=[],h=0;h<f;++h){var l=k,n=l.push;var q=b+40*h;var v=A[q+8>>2],m=A[q+32>>2],t=A[q+36>>2],w=A[q+4>>2];v?(m=q+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),q={binding:w,resource:{buffer:T(v),offset:4294967296*A[q+4+16>>2]+A[q+16>>2],size:m}}):q=m?{binding:w,resource:T(m)}:{binding:w,resource:T(t)};n.call(l,q)}c={label:c,layout:d,entries:k};a=T(a);d=$b(0);S(d,a.createBindGroup(c));return d},ka:(a,b)=>{var c=U(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],k=0;k<d;++k){var h=f,l=h.push,n=
b+88*k,q=A[n+4>>2],v=A[n+8>>2];var m=n+24;var t=A[m+4>>2];m=t?{type:xb[t],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;t=(t=A[n+48+4>>2])?{type:Eb[t]}:void 0;var w=n+56;var y=A[w+4>>2];w=y?{sampleType:Jb[y],viewDimension:Kb[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;n+=72;n=(y=A[n+4>>2])?{access:Fb[y],format:V[A[n+8>>2]],viewDimension:Kb[A[n+12>>2]]}:void 0;l.call(h,{binding:q,visibility:v,buffer:m,sampler:t,texture:w,storageTexture:n})}c={label:c,entries:f};
a=T(a);d=ac(0);S(d,a.createBindGroupLayout(c));return d},j:(a,b)=>{var c;b&&(c={label:U(b+4)});a=T(a);b=cc(0);S(b,a.createCommandEncoder(c));return b},C:(a,b)=>{var c={label:U(b+4),size:vb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:Ib[A[b+24>>2]],format:V[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>V[f]));a=T(a);d=fc(0);S(d,a.createTexture(c));return d},ia:(a,b)=>{wb(T(a).limits,b);return 1},b:(a,b)=>T(a).features.has(Ab[b]),
sa:(a,b)=>{a=K(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.mc=U(b+4);b=ec(0);S(b,a);return b},ca:(a,b,c)=>{a=T(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>T(d));a.submit(b)},ba:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);T(a).writeBuffer(T(b),c,x.subarray(d,d+f),0,f)},ga:a=>{T(a).end()},i:(a,b,c,d,f)=>{a=T(a);c=T(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ra:(a,b)=>{var c=A[b+4>>2];a=T(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=
d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:T(c),format:V[A[b+8>>2]],usage:A[b+16>>2],alphaMode:yb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),k=>V[k])}b=A[b>>2];0!==b&&(c.colorSpace=Db[A[b+8>>2]],c.oc={mode:Lb[A[b+12>>2]]});a.configure(c)},ma:(a,b)=>{a=T(a);try{var c=fc(0);S(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},e:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:U(b+4),format:V[A[b+12>>
2]],dimension:Kb[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Hb[A[b+36>>2]]}}a=T(a);b=gc(0);S(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Da;sa();fb=Z.rb;c=Z;e.__sapp_emsc_onpaste=Tb=c.Fa;e.__sapp_html5_get_ask_leave_site=Ub=c.Ga;e.__sapp_emsc_begin_drop=Vb=c.Ha;e.__sapp_emsc_drop=Wb=c.Ia;e.__sapp_emsc_end_drop=Xb=c.Ja;e.__sapp_emsc_invoke_fetch_cb=c.Ka;e.__sapp_emsc_set_fullscreen_flag=c.La;e._main=Yb=c.Ma;e.__saudio_emsc_pull=Zb=c.Na;e.__sfetch_emsc_head_response=c.Oa;e.__sfetch_emsc_get_response=c.Pa;e.__sfetch_emsc_failed_http_status=c.Qa;e.__sfetch_emsc_failed_buffer_too_small=c.Ra;
e.__sfetch_emsc_failed_other=c.Sa;P=c.Ta;$b=c.Ua;ac=c.Va;bc=c.Wa;cc=c.Xa;dc=c.cb;ec=c.fb;fc=c.gb;gc=c.hb;hc=c.nb;Y=c.ob;ic=c.pb;jc=c.qb;kc=c.sb;X=c.tb;tb=c.ub;W=c.vb;C--;e.monitorRunDependencies?.(C);0==C&&D&&(c=D,D=null,c());return Z}C++;e.monitorRunDependencies?.(C);var b={a:lc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("modplay-sapp.wasm",ia):ia+"modplay-sapp.wasm";return a((await xa(b)).instance)})();
function mc(a=[]){var b=Yb;a.unshift(ea);var c=a.length,d=tb(4*(c+1)),f=d;a.forEach(h=>{A[f>>2]=R(h);f+=4});A[f>>2]=0;try{var k=b(c,d);Ia(k)}catch(h){Ga(h)}}
function nc(a=da){function b(){e.calledRun=!0;if(!r){Z.Ea();e.onRuntimeInitialized?.();e.noInitialRun||mc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Aa.push(c)}za(Aa)}}if(0<C)D=nc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ca();za(Ba);0<C?D=nc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();nc();
