var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var g=console.error.bind(console),n,r=!1,ma,la=a=>a.startsWith("file://"),u,y,na,z,A,oa,B,pa;
function qa(){var a=ra.buffer;u=new Int8Array(a);na=new Int16Array(a);y=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);oa=new Float32Array(a);B=new Float64Array(a);pa=new BigInt64Array(a);new BigUint64Array(a)}function sa(a){f.onAbort?.(a);a="Aborted("+a+")";g(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function va(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function xa(a){var b=ta;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(f)},Aa=[],Ba=[],Ca=()=>{var a=f.preRun.shift();Ba.push(a)},C=0,D=null,Da=!0,Ea=0,E={},Fa=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ga=a=>{ma=a;Da||0<Ea||(f.onExit?.(a),r=!0);fa(a,new ya(a))},Ha=()=>{if(!(Da||0<Ea))try{var a=ma;ma=a;Ga(a)}catch(b){Fa(b)}},F=a=>{if(!r)try{a(),Ha()}catch(b){Fa(b)}},Oa=(a,b)=>{Ia=a;Ja=b;if(G)if(Ka||=!0,0==a)H=function(){setTimeout(J,Math.max(0,La+b-performance.now())|0)};else if(1==a)H=function(){Ma(J)};else if(2==a){if(!Na)if(globalThis.setImmediate)Na=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Na=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}H=function(){Na(J)}}},Ya=(a,b,c,d,e)=>{function h(){return k<Qa?(Ha(),!1):!0}G=a;Ra=d;var k=Qa;Ka=!1;J=function(){if(!r)if(0<Sa.length){var l=Sa.shift();l.kc(l.ac);if(Ta){var p=
Ta,t=0==p%1?p-1:Math.floor(p);Ta=l.dc?t:(8*p+(t+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",p=Ta??0,t=Ua.jc??0,p?p<t?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(J,0)}else if(h())if(Va=Va+1|0,1==Ia&&1<Ja&&0!=Va%Ja)H();else{0==Ia&&(La=performance.now());a:if(!r){for(l of Wa)if(!1===l())break a;F(a);for(p of Xa)p()}h()&&H()}};e||(0<b?Oa(0,1E3/b):Oa(1,1),H());if(c)throw"unwind";},Ka=!1,H=null,Qa=0,G=null,Ra=0,Ia=0,Ja=0,Va=0,
Sa=[],Wa=[],Xa=[];function Za(){H=null;Qa++}var K=0;function Ma(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===K)K=b+1E3/60;else for(;b+2>=K;)K+=1E3/60;setTimeout(a,Math.max(K-b,0))}}
var Ua={},La,J,Na,Ta,$a=globalThis.TextDecoder&&new TextDecoder,L=(a=0,b)=>{var c=y;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&$a)return $a.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))b+=String.fromCharCode((e&31)<<6|h);else{var k=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|k:(e&7)<<18|h<<12|k<<6|c[a++]&63;65536>e?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},
ab=[0,globalThis.document??0,globalThis.window??0],M=a=>{a=2<a?a?L(a):"":a;return ab[a]||globalThis.document?.querySelector(a)},bb=a=>0>ab.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},cb=[],N=a=>{var b=cb[a];b||(cb[a]=b=db.get(a));return b};function eb(a){var b=O.cb[a];b.target.removeEventListener(b.eb,b.Pb,b.mb);O.cb.splice(a,1)}function fb(){if(navigator.userActivation?navigator.userActivation.isActive:O.Gb&&O.Zb.Db){var a=O.Ab;O.Ab=[];for(var b of a)b.Kb(...b.Ob)}}
function P(a){if(!a.target)return-4;if(a.hb)a.Pb=function(c){++O.Gb;O.Zb=a;fb();a.ob(c);fb();--O.Gb},a.target.addEventListener(a.eb,a.Pb,a.mb),O.cb.push(a);else for(var b=0;b<O.cb.length;++b)O.cb[b].target==a.target&&O.cb[b].eb==a.eb&&eb(b--);return 0}function gb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var O={bc:0,lc:0,Hb:0,Bb:0,Nb:0,Mb:0,Eb:0,ic:0,nc:0,hc:0,Fb:0,Ib:0,xc:0,Lb:0,oc(){for(;O.cb.length;)eb(O.cb.length-1);O.Ab=[]},Gb:0,Ab:[],fc(a,b,c){function d(h,k){if(h.length!=k.length)return!1;for(var l in h)if(h[l]!=k[l])return!1;return!0}for(var e of O.Ab)if(e.Kb==a&&d(e.Ob,c))return;O.Ab.push({Kb:a,Sb:b,Ob:c});O.Ab.sort((h,k)=>h.Sb<k.Sb)},qc(a){O.Ab=O.Ab.filter(b=>b.Kb!=a)},cb:[],pc:(a,b)=>{for(var c=0;c<O.cb.length;++c)O.cb[c].target!=a||b&&b!=O.cb[c].eb||eb(c--)},rc(a){let b=!1;for(let c=0;c<
O.cb.length;++c){const d=O.cb[c];d.target===a.target&&d.lb===a.lb&&d.hb===a.hb&&d.nb===a.nb&&(eb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Q=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var h=a.codePointAt(e);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;
d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;e++}}d[b]=0}},hb=(a,b,c,d,e,h)=>{O.Eb||(O.Eb=R(256));a={target:M(a),eb:h,lb:e,nb:b,hb:d,ob:k=>{var l=k.target.id?k.target.id:"",p=O.Eb;Q(gb(k.target),p+0,128);Q(l,p+128,128);N(d)(e,p,b)&&k.preventDefault()},mb:c};return P(a)},ib=(a,b,c,d,e)=>{O.Fb||(O.Fb=R(276));return P({target:a,eb:e,lb:19,nb:b,hb:d,ob:h=>{var k=O.Fb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,p=!!l;u[k]=p;u[k+1]=O.fullscreenEnabled();var t=p?l:O.$b,v=t?.id||"";Q(gb(t),k+2,128);Q(v,k+130,128);z[k+260>>2]=t?t.clientWidth:0;z[k+264>>2]=t?t.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;p&&(O.$b=l);N(d)(19,k,b)&&h.preventDefault()},mb:c})},jb=(a,b,c,d,e,h)=>{O.Hb||(O.Hb=R(160));a={target:M(a),eb:h,lb:e,nb:b,hb:d,ob:k=>{var l=O.Hb;B[l>>3]=k.timeStamp;var p=l>>2;z[p+2]=k.location;u[l+12]=k.ctrlKey;u[l+13]=k.shiftKey;u[l+14]=k.altKey;u[l+15]=k.metaKey;
u[l+16]=k.repeat;z[p+5]=k.charCode;z[p+6]=k.keyCode;z[p+7]=k.which;Q(k.key||"",l+32,32);Q(k.code||"",l+64,32);Q(k.char||"",l+96,32);Q(k.locale||"",l+128,32);N(d)(e,l,b)&&k.preventDefault()},mb:c};return P(a)},kb=(a,b,c)=>{B[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;na[2*d+14]=b.button;na[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=bb(c);z[d+10]=b.clientX-(a.left|
0);z[d+11]=b.clientY-(a.top|0)},S=(a,b,c,d,e,h)=>{O.Bb||(O.Bb=R(64));a=M(a);return P({target:a,Db:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,eb:h,lb:e,nb:b,hb:d,ob:k=>{kb(O.Bb,k,a);N(d)(e,O.Bb,b)&&k.preventDefault()},mb:c})},lb=(a,b,c,d)=>{O.Ib||(O.Ib=R(257));return P({target:a,eb:"pointerlockchange",lb:20,nb:b,hb:d,ob:e=>{var h=O.Ib,k=document.pointerLockElement;u[h]=!!k;var l=k?.id||"";Q(gb(k),h+1,128);Q(l,h+129,128);N(d)(20,h,b)&&e.preventDefault()},mb:c})},mb=(a,b,c,d)=>P({target:a,eb:"pointerlockerror",
lb:38,nb:b,hb:d,ob:e=>{N(d)(38,0,b)&&e.preventDefault()},mb:c}),nb=(a,b,c,d)=>{O.Mb||(O.Mb=R(36));a=M(a);return P({target:a,eb:"resize",lb:10,nb:b,hb:d,ob:e=>{if(e.target==a){var h=document.body;if(h){var k=O.Mb;z[k>>2]=0;z[k+4>>2]=h.clientWidth;z[k+8>>2]=h.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;N(d)(10,k,b)&&e.preventDefault()}}},mb:c})},ob=(a,b,c,d,e,h)=>{O.Lb||(O.Lb=R(1552));a=M(a);
return P({target:a,Db:"touchstart"==h||"touchend"==h,eb:h,lb:e,nb:b,hb:d,ob:k=>{var l={},p=k.touches;for(var t of p)t.Qb=t.Rb=0,l[t.identifier]=t;for(var v of k.changedTouches)v.Qb=1,l[v.identifier]=v;for(var m of k.targetTouches)l[m.identifier].Rb=1;p=O.Lb;B[p>>3]=k.timeStamp;u[p+12]=k.ctrlKey;u[p+13]=k.shiftKey;u[p+14]=k.altKey;u[p+15]=k.metaKey;t=p+16;v=bb(a);m=0;for(let q of Object.values(l))if(l=t>>2,z[l]=q.identifier,z[l+1]=q.screenX,z[l+2]=q.screenY,z[l+3]=q.clientX,z[l+4]=q.clientY,z[l+5]=
q.pageX,z[l+6]=q.pageY,u[t+28]=q.Qb,u[t+29]=q.Rb,z[l+8]=q.clientX-(v.left|0),z[l+9]=q.clientY-(v.top|0),t+=48,31<++m)break;z[p+8>>2]=m;N(d)(e,p,b)&&k.preventDefault()},mb:c})},pb=(a,b,c,d)=>{O.Nb||(O.Nb=R(96));return P({target:a,Db:!0,eb:"wheel",lb:9,nb:b,hb:d,ob:e=>{var h=O.Nb;kb(h,e,a);B[h+64>>3]=e.deltaX;B[h+72>>3]=e.deltaY;B[h+80>>3]=e.deltaZ;z[h+88>>2]=e.deltaMode;N(d)(9,h,b)&&e.preventDefault()},mb:c})},T=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=
d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=qb(b);Q(a,c,b);return c},U=[],rb=(a,b)=>{U[a>>>0]=b},sb=[],V=a=>{if(a)return U[a>>>0]},tb=a=>{var b=A[a>>2];return b?L(b,A[a+4>>2]):""},W=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?L(b,a):"";if(0===a)return""},ub=a=>({r:B[a>>3],g:B[a+8>>3],b:B[a+16>>3],a:B[a+24>>3]}),vb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),wb=a=>{if(0!==a)return{querySet:V(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},xb=(a,b)=>{if(a){for(var c=
{},d=0;d<a;++d){var e=b+24*d,h=tb(e+4);c[h]=B[e+16>>3]}return c}},yb=a=>a?V(a):"auto",Lb=a=>{function b(d){if(d)return{operation:zb[A[d>>2]],srcFactor:Ab[A[d+4>>2]],dstFactor:Ab[A[d+8>>2]]}}function c(d){return{compare:Db[A[d>>2]],failOp:Eb[A[d+4>>2]],depthFailOp:Eb[A[d+8>>2]],passOp:Eb[A[d+12>>2]]}}return{label:W(a+4),layout:yb(A[a+12>>2]),vertex:function(d){if(d){var e=V(A[d+4>>2]),h=xb(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var l=A[d+28>>2];if(k){for(var p=[],t=0;t<k;++t){var v=p,m=v.push;var q=
l+24*t;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var I=null;else{I=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Fb[w];q=A[q+20>>2];for(var Bb=[],Pa=0;Pa<x;++Pa){var Cb=Bb,ua=q+24*Pa;Cb.push.call(Cb,{format:Gb[A[ua+4>>2]],offset:4294967296*A[ua+4+8>>2]+A[ua+8>>2],shaderLocation:A[ua+16>>2]})}I={arrayStride:I,stepMode:w,attributes:Bb}}}else I=void 0;m.call(v,I)}k=p}else k=void 0;return{module:e,constants:h,buffers:k,entryPoint:W(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Hb[A[d+4>>2]],
stripIndexFormat:Ib[A[d+8>>2]],frontFace:Jb[A[d+12>>2]],cullMode:Kb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:X[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Db[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:oa[d+60>>2],depthBiasClamp:oa[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+
12>>2]}}(a+76),fragment:function(d){if(d){for(var e=V(A[d+4>>2]),h=xb(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],l=A[d+28>>2],p=[],t=0;t<k;++t){var v=p,m=v.push,q=l+24*t,w=A[q+4>>2];if(0===w)q=void 0;else{w=X[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}m.call(v,q)}return{module:e,constants:h,targets:p,entryPoint:W(d+8)}}}(A[a+92>>2])}},Mb=(a,b)=>{function c(d,e){z[b+e>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",
12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);
pa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);pa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);pa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",
140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.mc&&c("maxImmediateSize",148)},Ab=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],zb=[,"add","subtract","reverse-subtract","min","max"],Nb=["binding-not-used",,"uniform","storage","read-only-storage"],Db=[,"never","less","equal","less-equal","greater",
"not-equal","greater-equal","always"],Ob=[,"opaque","premultiplied","unpremultiplied","inherit"],Kb=[,"none","front","back"],Pb=[,"compatibility","core"],Qb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",
14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Jb=[,"ccw","cw"],Ib=[,"uint16","uint32"],Rb=[,"load","clear"],Sb=[,"low-power","high-performance"],Tb=[,"srgb","display-p3"],Hb=[,"point-list","line-list","line-strip",
"triangle-list","triangle-strip"],Ub=["binding-not-used",,"filtering","non-filtering","comparison"],Eb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],Vb=["binding-not-used",,"write-only","read-only","read-write"],Wb=[,"store","discard"],Xb=[,"all","stencil-only","depth-only"],Yb=[,"1d","2d","3d"],X=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float",
"r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb",
"bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb",
"astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],Zb=["binding-not-used",,"float","unfilterable-float",
"depth","sint","uint"],$b=[,"1d","2d","2d-array","cube","cube-array","3d"],ac=[,"standard","extended"],Gb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3",
"sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Fb=[,"vertex","instance"],bc={undefined:1,unknown:1,destroyed:2},cc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";cc.Jb||(cc.Jb={});cc.Jb[a]||(cc.Jb[a]=1,ca&&(a="warning: "+a),g(a))},dc={rgba8unorm:22,bgra8unorm:27},ec=a=>{var b=Y();a();Z(b)};f.requestAnimationFrame=Ma;f.pauseMainLoop=Za;f.resumeMainLoop=function(){Qa++;var a=Ia,b=Ja,c=G;G=null;Ya(c,0,!1,Ra,!0);Oa(a,b);H()};f.preMainLoop&&Wa.push(f.preMainLoop);
f.postMainLoop&&Xa.push(f.postMainLoop);f.noExitRuntime&&(Da=f.noExitRuntime);f.printErr&&(g=f.printErr);f.wasmBinary&&(n=f.wasmBinary);f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
var fc,gc,hc,ic,jc,kc,R,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Z,qb,Y,ra,db,Ec={O:()=>sa(""),L:()=>{Da=!1;Ea=0},M:(a,b)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!b)return 0;var c=setTimeout(()=>{delete E[a];F(()=>Cc(a,performance.now()))},b);E[a]={id:c,vc:b};return 0},ra:()=>{Za();G=null},F:()=>globalThis.devicePixelRatio??1,H:(a,b,c)=>{a=M(a);if(!a)return-4;a=bb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},sa:()=>performance.now(),za:(a,b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}
return requestAnimationFrame(c)},N:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);qa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},m:(a,b,c,d)=>hb(a,b,c,d,12,"blur"),E:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},n:(a,b,c,d)=>hb(a,b,c,d,13,"focus"),l:(a,b,c,d)=>{if(!O.fullscreenEnabled())return-1;
a=M(a);if(!a)return-4;ib(a,b,c,d,"webkitfullscreenchange");return ib(a,b,c,d,"fullscreenchange")},w:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),u:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),v:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),Aa:(a,b,c)=>{a=N(a);Ya(a,b,c)},C:(a,b,c,d)=>S(a,b,c,d,5,"mousedown"),z:(a,b,c,d)=>S(a,b,c,d,33,"mouseenter"),y:(a,b,c,d)=>S(a,b,c,d,34,"mouseleave"),A:(a,b,c,d)=>S(a,b,c,d,8,"mousemove"),B:(a,b,c,d)=>S(a,b,c,d,6,"mouseup"),p:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?lb(a,b,c,d):-4:
-1,o:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?mb(a,b,c,d):-4:-1,G:(a,b,c,d)=>nb(a,b,c,d),q:(a,b,c,d)=>ob(a,b,c,d,25,"touchcancel"),r:(a,b,c,d)=>ob(a,b,c,d,23,"touchend"),s:(a,b,c,d)=>ob(a,b,c,d,24,"touchmove"),t:(a,b,c,d)=>ob(a,b,c,d,22,"touchstart"),x:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?pb(a,b,c,d):-1:-4,T:function(a,b,c,d,e,h){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=V(a);var k={};if(h){var l=A[h+
12>>2];if(l){var p=A[h+16>>2];k.requiredFeatures=Array.from(A.subarray(p>>2,p+4*l>>2),m=>Qb[m])}var t=A[h+20>>2];if(t){var v={};function m(w,x,I=!1){x=A[t+x>>2];4294967295==x||I&&0==x||(v[w]=x)}function q(w,x){x=t+x;var I=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=I)v[w]=4294967296*A[x+4>>2]+A[x>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",24);m("maxDynamicUniformBuffersPerPipelineLayout",
32);m("maxDynamicStorageBuffersPerPipelineLayout",36);m("maxSampledTexturesPerShaderStage",40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);q("maxBufferSize",96);m("maxVertexAttributes",104);m("maxVertexBufferArrayStride",
108);m("maxInterStageShaderVariables",112);m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",148,!0);k.requiredLimits=v}if(l=A[h+24>>2])l={label:W(l+4)},k.defaultQueue=l;k.label=W(h+4)}a.requestDevice(k).then(m=>{F(()=>{U[e>>>0]=m.queue;
U[d>>>0]=m;m.lost.then(q=>{F(()=>{m.onuncapturederror=()=>{};var w=Y(),x=T(q.message);yc(c,bc[q.reason],x);Z(w)})});m.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=Y();q=T(q.error.message);Bc(d,w,q);Z(x)};Ac(b,1,d,0)})},m=>{F(()=>{var q=Y(),w=T(m.message);Ac(b,3,d,w);c&&yc(c,4,w);Z(q)})})},W:(a,b,c)=>{var d=V(a);0===c&&cc();-1==c&&(c=void 0);try{var e=d.getMappedRange(b,c)}catch(k){return 0}var h=
Dc(16,e.byteLength);y.fill(0,h,e.byteLength);sb[a].push(()=>{(new Uint8Array(e)).set(y.subarray(h,h+e.byteLength));lc(h)});return h},V:a=>{var b=V(a),c=sb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete sb[a];b.unmap()}},a:a=>{delete U[a]},f:(a,b,c)=>{var d=!!A[b+32>>2];b={label:W(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=V(a);try{var e=a.createBuffer(b)}catch(h){return!1}U[c>>>0]=e;d&&(sb[c]=[]);return!0},S:(a,b,c)=>{var d=A[b>>2],e=A[d+4>>2];b={label:W(b+
4),code:""};switch(e){case 2:b.code=tb(d+8)}a=V(a).createShaderModule(b);U[c>>>0]=a},U:a=>{a=V(a);a.onuncapturederror=null;a.destroy()},Q:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return dc[a]},R:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var e={featureLevel:Pb[A[c+4>>2]],powerPreference:Sb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(e.yc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(e).then(h=>{F(()=>{if(h)U[d>>>0]=
h,zc(b,1,d,0);else{var k=Y(),l=T("WebGPU not available on this browser (requestAdapter returned null)");zc(b,3,d,l);Z(k)}})},h=>{F(()=>{var k=Y(),l=T(h.message);zc(b,4,d,l);Z(k)})}):(e=Y(),a=T("WebGPU not available on this browser (navigator.gpu is not available)"),zc(b,3,d,a),Z(e))},K:Ga,Ea:function(){f.Tb=a=>{0!=gc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Tb)},xa:function(){f.Yb=a=>{const b=a.clipboardData.getData("text");ec(()=>{const c=T(b);fc(c)})};
window.addEventListener("paste",f.Yb)},ta:function(){f.sc=[];f.Ub=b=>{b.stopPropagation();b.preventDefault()};f.Vb=b=>{b.stopPropagation();b.preventDefault()};f.Wb=b=>{b.stopPropagation();b.preventDefault()};f.Xb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.tc=c;hc(c.length);for(let e=0;e<c.length;e++)ec(()=>{const h=T(c[e].name);ic(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);jc(b.clientX,b.clientY,d)};const a=f.pb;a.addEventListener("dragenter",
f.Ub,!1);a.addEventListener("dragleave",f.Vb,!1);a.addEventListener("dragover",f.Wb,!1);a.addEventListener("drop",f.Xb,!1)},Ca:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},J:function(a){f.Cb&&(URL.revokeObjectURL(f.Cb[a].cc),f.Cb[a]=null)},fa:function(a,b){0!==b&&(document.title=b?L(b):"");a=a?L(a):"";void 0!==f.canvas&&("object"===typeof f.canvas?ab[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.pb=M(a);
f.pb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.pb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Da:function(){window.removeEventListener("beforeunload",f.Tb)},ua:function(){window.removeEventListener("paste",f.Yb)},oa:function(){const a=f.pb;a.removeEventListener("dragenter",f.Ub);a.removeEventListener("dragleave",f.Vb);a.removeEventListener("dragover",f.Wb);a.removeEventListener("drop",f.Xb)},g:function(){f.pb&&f.pb.requestPointerLock&&
f.pb.requestPointerLock()},P:function(a,b,c){if(f.pb){if(0===b)a="none";else if(0!=c)a=f.Cb[a].ec;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.pb.style.cursor=a}},Ba:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},I:function(a,b){b=b?L(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},va:(a,b)=>{Mb(V(a).limits,b);return 1},e:(a,b)=>V(a).features.has(Qb[b]),ja:(a,b)=>{var c;
b&&(c={label:W(b+4),timestampWrites:wb(A[b+12>>2])});b=V(a);a=qc(0);c=b.beginComputePass(c);U[a>>>0]=c;return a},ia:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=W(b+4);for(var e=A[b+12>>2],h=A[b+16>>2],k=[],l=0;l<e;++l){var p=k,t=p.push;var v=h+56*l;var m=A[v+4>>2];if(0!==m){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:V(m),depthSlice:q,resolveTarget:V(A[v+12>>2]),clearValue:ub(v+24),loadOp:Rb[A[v+16>>2]],storeOp:Wb[A[v+20>>2]]}}else v=void 0;t.call(p,v)}e=A[b+20>>2];e=
0!==e?{view:V(A[e+4>>2]),depthClearValue:oa[e+16>>2],depthLoadOp:Rb[A[e+8>>2]],depthStoreOp:Wb[A[e+12>>2]],depthReadOnly:!!A[e+20>>2],stencilClearValue:A[e+32>>2],stencilLoadOp:Rb[A[e+24>>2]],stencilStoreOp:Wb[A[e+28>>2]],stencilReadOnly:!!A[e+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:e,occlusionQuerySet:V(A[b+24>>2]),timestampWrites:wb(A[b+28>>2]),maxDrawCount:d};d=V(a);a=tc(0);b=d.beginRenderPass(b);U[a>>>0]=b;return a},Z:a=>{var b=V(a);a=oc(0);b=b.finish();U[a>>>0]=b;
return a},_:a=>{V(a).end()},c:(a,b,c,d,e)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,e>>2,d)},ha:(a,b)=>{V(a).setPipeline(V(b))},j:(a,b)=>{var c=W(b+4),d=V(A[b+12>>2]),e=A[b+16>>2];b=A[b+20>>2];for(var h=[],k=0;k<e;++k){var l=h,p=l.push;var t=b+40*k;var v=A[t+8>>2],m=A[t+32>>2],q=A[t+36>>2],w=A[t+4>>2];v?(m=t+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),t={binding:w,resource:{buffer:V(v),offset:4294967296*A[t+4+16>>2]+A[t+16>>2],size:m}}):t=m?{binding:w,resource:V(m)}:{binding:w,
resource:V(q)};p.call(l,t)}c={label:c,layout:d,entries:h};d=V(a);a=mc(0);c=d.createBindGroup(c);U[a>>>0]=c;return a},k:(a,b)=>{var c=W(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var e=[],h=0;h<d;++h){var k=e,l=k.push,p=b+88*h,t=A[p+4>>2],v=A[p+8>>2];var m=p+24;var q=A[m+4>>2];m=q?{type:Nb[q],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;q=(q=A[p+48+4>>2])?{type:Ub[q]}:void 0;var w=p+56;var x=A[w+4>>2];w=x?{sampleType:Zb[x],viewDimension:$b[A[w+8>>2]],multisampled:!!A[w+
12>>2]}:void 0;p+=72;p=(x=A[p+4>>2])?{access:Vb[x],format:X[A[p+8>>2]],viewDimension:$b[A[p+12>>2]]}:void 0;l.call(k,{binding:t,visibility:v,buffer:m,sampler:q,texture:w,storageTexture:p})}c={label:c,entries:e};d=V(a);a=nc(0);c=d.createBindGroupLayout(c);U[a>>>0]=c;return a},ka:(a,b)=>{var c;b&&(c={label:W(b+4)});b=V(a);a=pc(0);c=b.createCommandEncoder(c);U[a>>>0]=c;return a},ma:(a,b)=>{var c=W(b+4);var d=yb(A[b+12>>2]);b=(b+=16)?{module:V(A[b+4>>2]),constants:xb(A[b+16>>2],A[b+20>>2]),entryPoint:W(b+
8)}:void 0;c={label:c,layout:d,compute:b};d=V(a);a=rc(0);c=d.createComputePipeline(c);U[a>>>0]=c;return a},na:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],e=[],h=0;h<c;++h)e.push(V(A[d+4*h>>2]));b={label:W(b+4),bindGroupLayouts:e};c=V(a);a=sc(0);b=c.createPipelineLayout(b);U[a>>>0]=b;return a},la:(a,b)=>{b=Lb(b);var c=V(a);a=uc(0);b=c.createRenderPipeline(b);U[a>>>0]=b;return a},D:(a,b)=>{var c={label:W(b+4),size:vb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:Yb[A[b+24>>2]],format:X[A[b+
40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),e=>X[e]));a=V(a);d=wc(0);rb(d,a.createTexture(c));return d},pa:(a,b)=>{Mb(V(a).limits,b);return 1},d:(a,b)=>V(a).features.has(Qb[b]),ya:(a,b)=>{a=M(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.uc=W(b+4);b=vc(0);U[b>>>0]=a;return b},Y:(a,b,c)=>{a=V(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>V(d));a.submit(b)},X:function(a,b,c,d,e){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);
V(a).writeBuffer(V(b),c,y.subarray(d,d+e),0,e)},aa:(a,b,c,d,e)=>{V(a).draw(b,c,d>>>0,e>>>0)},ba:(a,b,c,d,e,h)=>{V(a).drawIndexed(b,c,d>>>0,e,h>>>0)},$:a=>{V(a).end()},b:(a,b,c,d,e)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,e>>2,d)},ea:(a,b)=>{V(a).setBlendConstant(ub(b))},ca:function(a,b,c,d,e){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);a=V(a);b=V(b);-1==e&&(e=void 0);a.setIndexBuffer(b,Ib[c],d,e)},ga:(a,b)=>
{V(a).setPipeline(V(b))},da:(a,b)=>{V(a).setStencilReference(b>>>0)},i:function(a,b,c,d,e){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);a=V(a);c=V(c);-1==e&&(e=void 0);a.setVertexBuffer(b,c,d,e)},wa:(a,b)=>{var c=A[b+4>>2];a=V(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:V(c),format:X[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Ob[A[b+40>>2]]};if(d=A[b+32>>2]){var e=A[b+36>>
2];c.viewFormats=Array.from(z.subarray(e>>2,e+4*d>>2),h=>X[h])}b=A[b>>2];0!==b&&(c.colorSpace=Tb[A[b+8>>2]],c.wc={mode:ac[A[b+12>>2]]});a.configure(c)},qa:(a,b)=>{a=V(a);try{var c=wc(0),d=a.getCurrentTexture();U[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(e){A[b+4>>2]=0,z[b+8>>2]=6}},h:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:W(b+4),format:X[A[b+12>>2]],dimension:$b[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===
d?void 0:d,aspect:Xb[A[b+36>>2]]}}b=V(a);a=xc(0);b=b.createView(c);U[a>>>0]=b;return a}};function Fc(a=[]){var b=kc;a.unshift(ea);var c=a.length,d=qb(4*(c+1)),e=d,h;for(h of a)A[e>>2]=T(h),e+=4;A[e>>2]=0;try{var k=b(c,d);ma=k;Ga(k)}catch(l){Fa(l)}}
function Gc(a=da){function b(){f.calledRun=!0;if(!r){Hc.Ga();f.onRuntimeInitialized?.();f.noInitialRun||Fc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();Aa.push(c)}za(Aa)}}if(0<C)D=Gc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ca();za(Ba);0<C?D=Gc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}var Hc;
(async function(){function a(c){c=Hc=c.exports;fc=f.__sapp_emsc_onpaste=c.Ha;gc=f.__sapp_html5_get_ask_leave_site=c.Ia;hc=f.__sapp_emsc_begin_drop=c.Ja;ic=f.__sapp_emsc_drop=c.Ka;jc=f.__sapp_emsc_end_drop=c.La;f.__sapp_emsc_invoke_fetch_cb=c.Ma;f.__sapp_emsc_set_fullscreen_flag=c.Na;kc=f._main=c.Oa;f.__saudio_emsc_pull=c.Pa;f.__sfetch_emsc_head_response=c.Qa;f.__sfetch_emsc_get_response=c.Ra;f.__sfetch_emsc_failed_http_status=c.Sa;f.__sfetch_emsc_failed_buffer_too_small=c.Ta;f.__sfetch_emsc_failed_other=
c.Ua;R=c.Va;lc=c.Wa;mc=c.Xa;nc=c.Ya;oc=c.Za;pc=c._a;qc=c.$a;rc=c.ab;sc=c.bb;tc=c.fb;uc=c.gb;vc=c.ib;wc=c.jb;xc=c.kb;yc=c.qb;zc=c.rb;Ac=c.sb;Bc=c.tb;Cc=c.vb;Dc=c.wb;Z=c.xb;qb=c.yb;Y=c.zb;ra=c.Fa;db=c.ub;qa();C--;f.monitorRunDependencies?.(C);0==C&&D&&(c=D,D=null,c());return Hc}C++;f.monitorRunDependencies?.(C);var b={a:Ec};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=f.locateFile?f.locateFile("noninterleaved-sapp.wasm",ia):ia+"noninterleaved-sapp.wasm";
return a((await xa(b)).instance)})();Gc();
