var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),p,q=!1,na,la=a=>a.startsWith("file://"),t,y,oa,pa,z,A,B,C,qa;
function ra(){var a=sa.buffer;t=new Int8Array(a);oa=new Int16Array(a);y=new Uint8Array(a);pa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){e.onAbort?.(a);a="Aborted("+a+")";k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=ua;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},D=0,E=null,Ea=!0,Fa=globalThis.TextDecoder&&new TextDecoder,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|h);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ga=0,Ha=[0,31,60,91,121,152,182,213,244,274,305,335],Ia=[0,31,59,90,120,151,181,212,243,273,304,334],G=a=>-9007199254740992>a||9007199254740992<a?NaN:Number(a),H={},Ja=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ka=a=>{na=a;Ea||0<Ga||(e.onExit?.(a),q=!0);fa(a,new za(a))},La=()=>{if(!(Ea||0<Ga))try{var a=na;na=a;Ka(a)}catch(b){Ja(b)}},I=a=>{if(!q)try{a(),La()}catch(b){Ja(b)}},J=(a,b,c)=>{var d=y;if(!(0<c))return 0;
var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;h++}}d[b]=0;return b-f},Ta=(a,b)=>{Ma=a;Na=b;if(L)if(Oa||=!0,0==a)M=function(){setTimeout(N,Math.max(0,Pa+b-performance.now())|0)};else if(1==a)M=function(){Qa(N)};
else if(2==a){if(!Sa)if(globalThis.setImmediate)Sa=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}M=function(){Sa(N)}}},bb=(a,b,c,d,f)=>{function h(){return g<Ua?(La(),!1):!0}L=a;Va=d;var g=Ua;Oa=!1;N=function(){if(!q)if(0<
Wa.length){var l=Wa.shift();l.Dc(l.uc);if(Xa){var n=Xa,u=0==n%1?n-1:Math.floor(n);Xa=l.xc?u:(8*n+(u+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",n=Xa??0,u=Ya.Cc??0,n?n<u?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));h()&&setTimeout(N,0)}else if(h())if(Za=Za+1|0,1==Ma&&1<Na&&0!=Za%Na)M();else{0==Ma&&(Pa=performance.now());a:if(!q){for(l of $a)if(!1===l())break a;I(a);for(n of ab)n()}h()&&M()}};f||(0<b?Ta(0,1E3/b):Ta(1,1),M());if(c)throw"unwind";
},Oa=!1,M=null,Ua=0,L=null,Va=0,Ma=0,Na=0,Za=0,Wa=[],$a=[],ab=[];function cb(){M=null;Ua++}var db=0;function Qa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===db)db=b+1E3/60;else for(;b+2>=db;)db+=1E3/60;setTimeout(a,Math.max(db-b,0))}}
var Ya={},Pa,N,Sa,Xa,eb=[0,globalThis.document??0,globalThis.window??0],O=a=>{a=2<a?a?F(y,a):"":a;return eb[a]||globalThis.document?.querySelector(a)},fb=a=>0>eb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},gb=[],P=a=>{var b=gb[a];b||(gb[a]=b=hb.get(a));return b};function ib(a){var b=Q.vb[a];b.target.removeEventListener(b.wb,b.ic,b.Fb);Q.vb.splice(a,1)}
function jb(){if(navigator.userActivation?navigator.userActivation.isActive:Q.Zb&&Q.sc.Wb){var a=Q.Tb;Q.Tb=[];for(var b of a)b.cc(...b.hc)}}function R(a){if(!a.target)return-4;if(a.xb)a.ic=function(c){++Q.Zb;Q.sc=a;jb();a.Hb(c);jb();--Q.Zb},a.target.addEventListener(a.wb,a.ic,a.Fb),Q.vb.push(a);else for(var b=0;b<Q.vb.length;++b)Q.vb[b].target==a.target&&Q.vb[b].wb==a.wb&&ib(b--);return 0}function kb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var Q={vc:0,Ec:0,$b:0,Ub:0,fc:0,ec:0,Xb:0,Bc:0,Gc:0,Ac:0,Yb:0,ac:0,Qc:0,dc:0,Hc(){for(;Q.vb.length;)ib(Q.vb.length-1);Q.Tb=[]},Zb:0,Tb:[],zc(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var f of Q.Tb)if(f.cc==a&&d(f.hc,c))return;Q.Tb.push({cc:a,lc:b,hc:c});Q.Tb.sort((h,g)=>h.lc<g.lc)},Jc(a){Q.Tb=Q.Tb.filter(b=>b.cc!=a)},vb:[],Ic:(a,b)=>{for(var c=0;c<Q.vb.length;++c)Q.vb[c].target!=a||b&&b!=Q.vb[c].wb||ib(c--)},Kc(a){let b=!1;for(let c=0;c<
Q.vb.length;++c){const d=Q.vb[c];d.target===a.target&&d.Eb===a.Eb&&d.xb===a.xb&&d.Gb===a.Gb&&(ib(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},lb=(a,b,c,d,f,h)=>{Q.Xb||(Q.Xb=S(256));a={target:O(a),wb:h,Eb:f,Gb:b,xb:d,Hb:g=>{var l=g.target.id?g.target.id:"",n=Q.Xb;J(kb(g.target),n+0,128);J(l,n+128,128);P(d)(f,n,b)&&g.preventDefault()},Fb:c};return R(a)},mb=(a,b,c,d,f)=>{Q.Yb||(Q.Yb=S(276));return R({target:a,wb:f,Eb:19,Gb:b,xb:d,
Hb:h=>{var g=Q.Yb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;t[g]=n;t[g+1]=Q.fullscreenEnabled();var u=n?l:Q.tc,v=u?.id||"";J(kb(u),g+2,128);J(v,g+130,128);z[g+260>>2]=u?u.clientWidth:0;z[g+264>>2]=u?u.clientHeight:0;z[g+268>>2]=screen.width;z[g+272>>2]=screen.height;n&&(Q.tc=l);P(d)(19,g,b)&&h.preventDefault()},Fb:c})},nb=(a,b,c,d,f,h)=>{Q.$b||(Q.$b=S(160));a={target:O(a),
wb:h,Eb:f,Gb:b,xb:d,Hb:g=>{var l=Q.$b;C[l>>3]=g.timeStamp;var n=l>>2;z[n+2]=g.location;t[l+12]=g.ctrlKey;t[l+13]=g.shiftKey;t[l+14]=g.altKey;t[l+15]=g.metaKey;t[l+16]=g.repeat;z[n+5]=g.charCode;z[n+6]=g.keyCode;z[n+7]=g.which;J(g.key||"",l+32,32);J(g.code||"",l+64,32);J(g.char||"",l+96,32);J(g.locale||"",l+128,32);P(d)(f,l,b)&&g.preventDefault()},Fb:c};return R(a)},ob=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+
25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=fb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},pb=(a,b,c,d,f,h)=>{Q.Ub||(Q.Ub=S(64));a=O(a);return R({target:a,Wb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,wb:h,Eb:f,Gb:b,xb:d,Hb:g=>{ob(Q.Ub,g,a);P(d)(f,Q.Ub,b)&&g.preventDefault()},Fb:c})},qb=(a,b,c,d)=>{Q.ac||(Q.ac=S(257));return R({target:a,wb:"pointerlockchange",Eb:20,Gb:b,xb:d,Hb:f=>{var h=
Q.ac,g=document.pointerLockElement;t[h]=!!g;var l=g?.id||"";J(kb(g),h+1,128);J(l,h+129,128);P(d)(20,h,b)&&f.preventDefault()},Fb:c})},rb=(a,b,c,d)=>R({target:a,wb:"pointerlockerror",Eb:38,Gb:b,xb:d,Hb:f=>{P(d)(38,0,b)&&f.preventDefault()},Fb:c}),sb=(a,b,c,d)=>{Q.ec||(Q.ec=S(36));a=O(a);return R({target:a,wb:"resize",Eb:10,Gb:b,xb:d,Hb:f=>{if(f.target==a){var h=document.body;if(h){var g=Q.ec;z[g>>2]=0;z[g+4>>2]=h.clientWidth;z[g+8>>2]=h.clientHeight;z[g+12>>2]=innerWidth;z[g+16>>2]=innerHeight;z[g+
20>>2]=outerWidth;z[g+24>>2]=outerHeight;z[g+28>>2]=pageXOffset|0;z[g+32>>2]=pageYOffset|0;P(d)(10,g,b)&&f.preventDefault()}}},Fb:c})},tb=(a,b,c,d,f,h)=>{Q.dc||(Q.dc=S(1552));a=O(a);return R({target:a,Wb:"touchstart"==h||"touchend"==h,wb:h,Eb:f,Gb:b,xb:d,Hb:g=>{var l={},n=g.touches;for(var u of n)u.jc=u.kc=0,l[u.identifier]=u;for(var v of g.changedTouches)v.jc=1,l[v.identifier]=v;for(var m of g.targetTouches)l[m.identifier].kc=1;n=Q.dc;C[n>>3]=g.timeStamp;t[n+12]=g.ctrlKey;t[n+13]=g.shiftKey;t[n+
14]=g.altKey;t[n+15]=g.metaKey;u=n+16;v=fb(a);m=0;for(let r of Object.values(l))if(l=u>>2,z[l]=r.identifier,z[l+1]=r.screenX,z[l+2]=r.screenY,z[l+3]=r.clientX,z[l+4]=r.clientY,z[l+5]=r.pageX,z[l+6]=r.pageY,t[u+28]=r.jc,t[u+29]=r.kc,z[l+8]=r.clientX-(v.left|0),z[l+9]=r.clientY-(v.top|0),u+=48,31<++m)break;z[n+8>>2]=m;P(d)(f,n,b)&&g.preventDefault()},Fb:c})},ub=(a,b,c,d)=>{Q.fc||(Q.fc=S(96));return R({target:a,Wb:!0,wb:"wheel",Eb:9,Gb:b,xb:d,Hb:f=>{var h=Q.fc;ob(h,f,a);C[h+64>>3]=f.deltaX;C[h+72>>3]=
f.deltaY;C[h+80>>3]=f.deltaZ;z[h+88>>2]=f.deltaMode;P(d)(9,h,b)&&f.preventDefault()},Fb:c})},vb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},T=a=>{var b=vb(a)+1,c=wb(b);J(a,c,b);return c},U=[],xb=(a,b)=>{U[a>>>0]=b},yb=[],V=a=>{if(a)return U[a>>>0]},zb=a=>{var b=A[a>>2];return b?F(y,b,A[a+4>>2]):""},W=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?F(y,b,a):"";if(0===a)return""},Ab=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],
a:C[a+24>>3]}),Bb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Cb=a=>{if(0!==a)return{querySet:V(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},Db=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,h=zb(f+4);c[h]=C[f+16>>3]}return c}},Eb=a=>a?V(a):"auto",Rb=a=>{function b(d){if(d)return{operation:Fb[A[d>>2]],srcFactor:Gb[A[d+4>>2]],dstFactor:Gb[A[d+8>>2]]}}function c(d){return{compare:Hb[A[d>>2]],failOp:Ib[A[d+4>>2]],depthFailOp:Ib[A[d+8>>2]],
passOp:Ib[A[d+12>>2]]}}return{label:W(a+4),layout:Eb(A[a+12>>2]),vertex:function(d){if(d){var f=V(A[d+4>>2]),h=Db(A[d+16>>2],A[d+20>>2]);var g=A[d+24>>2];var l=A[d+28>>2];if(g){for(var n=[],u=0;u<g;++u){var v=n,m=v.push;var r=l+24*u;if(r){var w=A[r+4>>2],x=A[r+16>>2];if(0===w&&0===x)var K=null;else{K=4294967296*A[r+4+8>>2]+A[r+8>>2];w=Lb[w];r=A[r+20>>2];for(var Jb=[],Ra=0;Ra<x;++Ra){var Kb=Jb,wa=r+24*Ra;Kb.push.call(Kb,{format:Mb[A[wa+4>>2]],offset:4294967296*A[wa+4+8>>2]+A[wa+8>>2],shaderLocation:A[wa+
16>>2]})}K={arrayStride:K,stepMode:w,attributes:Jb}}}else K=void 0;m.call(v,K)}g=n}else g=void 0;return{module:f,constants:h,buffers:g,entryPoint:W(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Nb[A[d+4>>2]],stripIndexFormat:Ob[A[d+8>>2]],frontFace:Pb[A[d+12>>2]],cullMode:Qb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:X[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Hb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+
48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=V(A[d+4>>2]),h=Db(A[d+16>>2],A[d+20>>2]),g=A[d+24>>2],l=A[d+28>>2],n=[],u=0;u<g;++u){var v=n,m=v.push,r=l+24*u,w=A[r+4>>2];if(0===w)r=void 0;else{w=X[w];var x=(x=A[r+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;r={format:w,blend:x,
writeMask:A[r+16>>2]}}m.call(v,r)}return{module:f,constants:h,targets:n,entryPoint:W(d+8)}}}(A[a+92>>2])}},Sb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);
c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",
116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.Fc&&c("maxImmediateSize",148)},Tb=[,"clamp-to-edge","repeat","mirror-repeat"],Gb=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated",
"constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Fb=[,"add","subtract","reverse-subtract","min","max"],Ub=["binding-not-used",,"uniform","storage","read-only-storage"],Hb=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Vb=[,"opaque","premultiplied","unpremultiplied","inherit"],Qb=[,"none","front","back"],Wb=[,"compatibility","core"],Xb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",
5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",
327732:"chromium-experimental-multi-draw-indirect"},Yb=[,"nearest","linear"],Pb=[,"ccw","cw"],Ob=[,"uint16","uint32"],Zb=[,"load","clear"],$b=[,"nearest","linear"],ac=[,"low-power","high-performance"],bc=[,"srgb","display-p3"],Nb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],cc=["binding-not-used",,"filtering","non-filtering","comparison"],Ib=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],dc=["binding-not-used",
,"write-only","read-only","read-write"],ec=[,"store","discard"],fc=[,"all","stencil-only","depth-only"],gc=[,"1d","2d","3d"],X=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat",
"rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm",
"etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb",
"astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],hc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],ic=[,"1d","2d","2d-array","cube","cube-array","3d"],jc=[,"standard","extended"],Mb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2",
"uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Lb=[,"vertex","instance"],kc={undefined:1,unknown:1,destroyed:2},lc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";lc.bc||(lc.bc={});lc.bc[a]||(lc.bc[a]=1,ca&&(a="warning: "+
a),k(a))},mc={rgba8unorm:22,bgra8unorm:27},nc={},pc=()=>{if(!oc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in nc)void 0===nc[b]?delete a[b]:a[b]=nc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);oc=c}return oc},oc,qc=[null,[],[]],rc=a=>{var b=Y();a();Z(b)};e.requestAnimationFrame=Qa;e.pauseMainLoop=cb;
e.resumeMainLoop=function(){Ua++;var a=Ma,b=Na,c=L;L=null;bb(c,0,!1,Va,!0);Ta(a,b);M()};e.preMainLoop&&$a.push(e.preMainLoop);e.postMainLoop&&ab.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(k=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var S,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Z,wb,Y,sa,hb,Sc={o:function(){return 0},V:function(){return 0},W:function(){},_:()=>ta(""),Ta:()=>{Ea=!1;Ga=0},Q:function(a,b){a=G(a);a=new Date(1E3*a);z[b>>2]=a.getSeconds();z[b+4>>2]=a.getMinutes();z[b+8>>2]=a.getHours();z[b+12>>2]=a.getDate();z[b+16>>2]=a.getMonth();z[b+20>>2]=a.getFullYear()-1900;z[b+24>>2]=a.getDay();var c=a.getFullYear();z[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ia:Ha)[a.getMonth()]+a.getDate()-
1|0;z[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Ua:(a,b)=>{H[a]&&(clearTimeout(H[a].id),delete H[a]);if(!b)return 0;var c=setTimeout(()=>{delete H[a];I(()=>Qc(a,performance.now()))},b);H[a]={id:c,Oc:b};return 0},R:(a,b,c,d)=>{var f=(new Date).getFullYear(),h=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();
A[a>>2]=60*Math.max(h,f);z[b>>2]=Number(h!=f);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(h);b=b(f);f<h?(J(a,c,17),J(b,d,17)):(J(a,d,17),J(b,c,17))},Fa:()=>{cb();L=null},Z:()=>Date.now(),M:()=>globalThis.devicePixelRatio??1,O:(a,b,c)=>{a=O(a);if(!a)return-4;a=fb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},Ga:()=>performance.now(),Ma:(a,b)=>{function c(d){P(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Va:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},u:(a,b,c,d)=>lb(a,b,c,d,12,"blur"),L:(a,b,c)=>{a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},v:(a,b,c,d)=>lb(a,b,c,d,13,"focus"),t:(a,b,c,d)=>{if(!Q.fullscreenEnabled())return-1;a=O(a);if(!a)return-4;
mb(a,b,c,d,"webkitfullscreenchange");return mb(a,b,c,d,"fullscreenchange")},E:(a,b,c,d)=>nb(a,b,c,d,2,"keydown"),C:(a,b,c,d)=>nb(a,b,c,d,1,"keypress"),D:(a,b,c,d)=>nb(a,b,c,d,3,"keyup"),Oa:(a,b,c)=>{a=P(a);bb(a,b,c)},K:(a,b,c,d)=>pb(a,b,c,d,5,"mousedown"),H:(a,b,c,d)=>pb(a,b,c,d,33,"mouseenter"),G:(a,b,c,d)=>pb(a,b,c,d,34,"mouseleave"),I:(a,b,c,d)=>pb(a,b,c,d,8,"mousemove"),J:(a,b,c,d)=>pb(a,b,c,d,6,"mouseup"),x:(a,b,c,d)=>document.body?.requestPointerLock?(a=O(a))?qb(a,b,c,d):-4:-1,w:(a,b,c,d)=>
document.body?.requestPointerLock?(a=O(a))?rb(a,b,c,d):-4:-1,N:(a,b,c,d)=>sb(a,b,c,d),y:(a,b,c,d)=>tb(a,b,c,d,25,"touchcancel"),z:(a,b,c,d)=>tb(a,b,c,d,23,"touchend"),A:(a,b,c,d)=>tb(a,b,c,d,24,"touchmove"),B:(a,b,c,d)=>tb(a,b,c,d,22,"touchstart"),F:(a,b,c,d)=>(a=O(a))?"undefined"!=typeof a.onwheel?ub(a,b,c,d):-1:-4,ca:function(a,b,c,d,f,h){b=G(b);c=G(c);a=V(a);var g={};if(h){var l=A[h+12>>2];if(l){var n=A[h+16>>2];g.requiredFeatures=Array.from(A.subarray(n>>2,n+4*l>>2),m=>Xb[m])}var u=A[h+20>>2];
if(u){var v={};function m(w,x,K=!1){x=A[u+x>>2];4294967295==x||K&&0==x||(v[w]=x)}function r(w,x){x=u+x;var K=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=K)v[w]=4294967296*A[x+4>>2]+A[x>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",24);m("maxDynamicUniformBuffersPerPipelineLayout",32);m("maxDynamicStorageBuffersPerPipelineLayout",36);m("maxSampledTexturesPerShaderStage",
40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);r("maxUniformBufferBindingSize",64);r("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);r("maxBufferSize",96);m("maxVertexAttributes",104);m("maxVertexBufferArrayStride",108);m("maxInterStageShaderVariables",112);m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",
120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",148,!0);g.requiredLimits=v}if(l=A[h+24>>2])l={label:W(l+4)},g.defaultQueue=l;g.label=W(h+4)}a.requestDevice(g).then(m=>{I(()=>{U[f>>>0]=m.queue;U[d>>>0]=m;m.lost.then(r=>{I(()=>{m.onuncapturederror=()=>{};var w=Y(),x=T(r.message);Mc(c,kc[r.reason],
x);Z(w)})});m.onuncapturederror=r=>{var w=5;r.error instanceof GPUValidationError?w=2:r.error instanceof GPUOutOfMemoryError?w=3:r.error instanceof GPUInternalError&&(w=4);var x=Y();r=T(r.error.message);Pc(d,w,r);Z(x)};Oc(b,1,d,0)})},m=>{I(()=>{var r=Y(),w=T(m.message);Oc(b,3,d,w);c&&Mc(c,4,w);Z(r)})})},ga:(a,b,c)=>{var d=V(a);0===c&&lc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(g){return 0}var h=Rc(16,f.byteLength);y.fill(0,h,f.byteLength);yb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(h,
h+f.byteLength));sc(h)});return h},fa:a=>{var b=V(a),c=yb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete yb[a];b.unmap()}},a:a=>{delete U[a]},j:(a,b,c)=>{var d=!!A[b+32>>2];b={label:W(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=V(a);try{var f=a.createBuffer(b)}catch(h){return!1}U[c>>>0]=f;d&&(yb[c]=[]);return!0},ba:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:W(b+4),code:""};switch(f){case 2:b.code=zb(d+8)}a=V(a).createShaderModule(b);U[c>>>0]=a},da:a=>{a=
V(a);a.onuncapturederror=null;a.destroy()},$:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return mc[a]},aa:function(a,b,c,d){b=G(b);if(c){var f={featureLevel:Wb[A[c+4>>2]],powerPreference:ac[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Rc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(h=>{I(()=>{if(h)U[d>>>0]=h,Nc(b,1,d,0);else{var g=Y(),l=T("WebGPU not available on this browser (requestAdapter returned null)");Nc(b,3,d,l);Z(g)}})},h=>{I(()=>{var g=
Y(),l=T(h.message);Nc(b,4,d,l);Z(g)})}):(f=Y(),a=T("WebGPU not available on this browser (navigator.gpu is not available)"),Nc(b,3,d,a),Z(f))},X:(a,b)=>{var c=0,d=0,f;for(f of pc()){var h=b+c;A[a+d>>2]=h;c+=J(f,h,Infinity)+1;d+=4}return 0},Y:(a,b)=>{var c=pc();A[a>>2]=c.length;a=0;for(var d of c)a+=vb(d)+1;A[b>>2]=a;return 0},n:()=>52,U:()=>52,S:function(){return 70},T:(a,b,c,d)=>{for(var f=0,h=0;h<c;h++){var g=A[b>>2],l=A[b+4>>2];b+=8;for(var n=0;n<l;n++){var u=a,v=y[g+n],m=qc[u];0===v||10===v?((1===
u?ma:k)(F(m)),m.length=0):m.push(v)}f+=l}A[d>>2]=f;return 0},Sa:Ka,Wa:function(){e.mc=a=>{0!=uc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.mc)},Ia:function(){e.rc=a=>{const b=a.clipboardData.getData("text");rc(()=>{const c=T(b);tc(c)})};window.addEventListener("paste",e.rc)},ua:function(){e.Lc=[];e.nc=b=>{b.stopPropagation();b.preventDefault()};e.oc=b=>{b.stopPropagation();b.preventDefault()};e.pc=b=>{b.stopPropagation();b.preventDefault()};e.qc=b=>{b.stopPropagation();
b.preventDefault();const c=b.dataTransfer.files;e.Mc=c;vc(c.length);for(let f=0;f<c.length;f++)rc(()=>{const h=T(c[f].name);wc(f,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);xc(b.clientX,b.clientY,d)};const a=e.Ib;a.addEventListener("dragenter",e.nc,!1);a.addEventListener("dragleave",e.oc,!1);a.addEventListener("dragover",e.pc,!1);a.addEventListener("drop",e.qc,!1)},Qa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},
Ra:function(a){e.Vb&&(URL.revokeObjectURL(e.Vb[a].wc),e.Vb[a]=null)},ea:function(a,b){0!==b&&(document.title=b?F(y,b):"");a=a?F(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?eb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.Ib=O(a);e.Ib||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.Ib.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Na:function(){window.removeEventListener("beforeunload",
e.mc)},Ha:function(){window.removeEventListener("paste",e.rc)},na:function(){const a=e.Ib;a.removeEventListener("dragenter",e.nc);a.removeEventListener("dragleave",e.oc);a.removeEventListener("dragover",e.pc);a.removeEventListener("drop",e.qc)},i:function(){e.Ib&&e.Ib.requestPointerLock&&e.Ib.requestPointerLock()},m:function(a,b,c){if(e.Ib){if(0===b)a="none";else if(0!=c)a=e.Vb[a].yc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.Ib.style.cursor=a}},Pa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},Ca:function(a){a=a?F(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},p:function(){return navigator.userAgent.includes("Macintosh")?
1:0},P:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Xa:function(){return navigator.userAgent.includes("Macintosh")?1:0},Ja:(a,b)=>{Sb(V(a).limits,b);return 1},g:(a,b)=>V(a).features.has(Xb[b]),va:(a,b)=>{var c;b&&(c={label:W(b+4),timestampWrites:Cb(A[b+12>>2])});b=V(a);a=Dc(0);c=b.beginComputePass(c);U[a>>>0]=c;return a},ta:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+
8>>2]);c=W(b+4);for(var f=A[b+12>>2],h=A[b+16>>2],g=[],l=0;l<f;++l){var n=g,u=n.push;var v=h+56*l;var m=A[v+4>>2];if(0!==m){var r=z[v+8>>2];-1==r&&(r=void 0);v={view:V(m),depthSlice:r,resolveTarget:V(A[v+12>>2]),clearValue:Ab(v+24),loadOp:Zb[A[v+16>>2]],storeOp:ec[A[v+20>>2]]}}else v=void 0;u.call(n,v)}f=A[b+20>>2];f=0!==f?{view:V(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Zb[A[f+8>>2]],depthStoreOp:ec[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Zb[A[f+
24>>2]],stencilStoreOp:ec[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:g,depthStencilAttachment:f,occlusionQuerySet:V(A[b+24>>2]),timestampWrites:Cb(A[b+28>>2]),maxDrawCount:d};d=V(a);a=Gc(0);b=d.beginRenderPass(b);U[a>>>0]=b;return a},ia:a=>{var b=V(a);a=Bc(0);b=b.finish();U[a>>>0]=b;return a},ja:a=>{V(a).end()},d:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},sa:(a,b)=>{V(a).setPipeline(V(b))},r:(a,b)=>{var c=W(b+4),d=V(A[b+12>>
2]),f=A[b+16>>2];b=A[b+20>>2];for(var h=[],g=0;g<f;++g){var l=h,n=l.push;var u=b+40*g;var v=A[u+8>>2],m=A[u+32>>2],r=A[u+36>>2],w=A[u+4>>2];v?(m=u+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),u={binding:w,resource:{buffer:V(v),offset:4294967296*A[u+4+16>>2]+A[u+16>>2],size:m}}):u=m?{binding:w,resource:V(m)}:{binding:w,resource:V(r)};n.call(l,u)}c={label:c,layout:d,entries:h};d=V(a);a=zc(0);c=d.createBindGroup(c);U[a>>>0]=c;return a},s:(a,b)=>{var c=W(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=
[],h=0;h<d;++h){var g=f,l=g.push,n=b+88*h,u=A[n+4>>2],v=A[n+8>>2];var m=n+24;var r=A[m+4>>2];m=r?{type:Ub[r],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;r=(r=A[n+48+4>>2])?{type:cc[r]}:void 0;var w=n+56;var x=A[w+4>>2];w=x?{sampleType:hc[x],viewDimension:ic[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;n+=72;n=(x=A[n+4>>2])?{access:dc[x],format:X[A[n+8>>2]],viewDimension:ic[A[n+12>>2]]}:void 0;l.call(g,{binding:u,visibility:v,buffer:m,sampler:r,texture:w,
storageTexture:n})}c={label:c,entries:f};d=V(a);a=Ac(0);c=d.createBindGroupLayout(c);U[a>>>0]=c;return a},wa:(a,b)=>{var c;b&&(c={label:W(b+4)});b=V(a);a=Cc(0);c=b.createCommandEncoder(c);U[a>>>0]=c;return a},ya:(a,b)=>{var c=W(b+4);var d=Eb(A[b+12>>2]);b=(b+=16)?{module:V(A[b+4>>2]),constants:Db(A[b+16>>2],A[b+20>>2]),entryPoint:W(b+8)}:void 0;c={label:c,layout:d,compute:b};d=V(a);a=Ec(0);c=d.createComputePipeline(c);U[a>>>0]=c;return a},za:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],h=0;h<c;++h)f.push(V(A[d+
4*h>>2]));b={label:W(b+4),bindGroupLayouts:f};c=V(a);a=Fc(0);b=c.createPipelineLayout(b);U[a>>>0]=b;return a},xa:(a,b)=>{b=Rb(b);var c=V(a);a=Hc(0);b=c.createRenderPipeline(b);U[a>>>0]=b;return a},Aa:(a,b)=>{var c;b&&(c={label:W(b+4),addressModeU:Tb[A[b+12>>2]],addressModeV:Tb[A[b+16>>2]],addressModeW:Tb[A[b+20>>2]],magFilter:Yb[A[b+24>>2]],minFilter:Yb[A[b+28>>2]],mipmapFilter:$b[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Hb[A[b+44>>2]],maxAnisotropy:pa[b+48>>1]});b=V(a);a=
Ic(0);c=b.createSampler(c);U[a>>>0]=c;return a},l:(a,b)=>{var c={label:W(b+4),size:Bb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:gc[A[b+24>>2]],format:X[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>X[f]));a=V(a);d=Kc(0);xb(d,a.createTexture(c));return d},Da:(a,b)=>{Sb(V(a).limits,b);return 1},f:(a,b)=>V(a).features.has(Xb[b]),La:(a,b)=>{a=O(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Nc=W(b+4);b=Jc(0);
U[b>>>0]=a;return b},ha:(a,b,c)=>{a=V(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>V(d));a.submit(b)},k:function(a,b,c,d,f){c=G(c);V(a).writeBuffer(V(b),c,y.subarray(d,d+f),0,f)},Ba:(a,b,c,d,f,h)=>{var g=A[f+8>>2],l=A[f+12>>2],n=b+8;V(a).writeTexture({texture:V(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[n>>2],y:A[n+4>>2],z:A[n+8>>2]},aspect:fc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===g?void 0:g,rowsPerImage:4294967295===l?void 0:l},Bb(h))},la:(a,b,
c,d,f)=>{V(a).draw(b,c,d>>>0,f>>>0)},ma:(a,b,c,d,f,h)=>{V(a).drawIndexed(b,c,d>>>0,f,h>>>0)},ka:a=>{V(a).end()},c:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},qa:(a,b)=>{V(a).setBlendConstant(Ab(b))},oa:function(a,b,c,d,f){d=G(d);f=G(f);a=V(a);b=V(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Ob[c],d,f)},ra:(a,b)=>{V(a).setPipeline(V(b))},b:(a,b,c,d,f)=>{V(a).setScissorRect(b,c,d,f)},pa:(a,b)=>{V(a).setStencilReference(b>>>0)},q:function(a,b,c,d,f){d=G(d);f=G(f);a=
V(a);c=V(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},e:(a,b,c,d,f,h,g)=>{V(a).setViewport(b,c,d,f,h,g)},Ka:(a,b)=>{var c=A[b+4>>2];a=V(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:V(c),format:X[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Vb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),h=>X[h])}b=A[b>>2];0!==b&&(c.colorSpace=bc[A[b+8>>2]],c.Pc={mode:jc[A[b+12>>2]]});a.configure(c)},Ea:(a,
b)=>{a=V(a);try{var c=Kc(0),d=a.getCurrentTexture();U[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},h:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:W(b+4),format:X[A[b+12>>2]],dimension:ic[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:fc[A[b+36>>2]]}}b=V(a);a=Lc(0);b=b.createView(c);U[a>>>0]=b;return a}};
function Tc(a=[]){var b=yc;a.unshift(ea);var c=a.length,d=wb(4*(c+1)),f=d,h;for(h of a)A[f>>2]=T(h),f+=4;A[f>>2]=0;try{var g=b(c,d);na=g;Ka(g)}catch(l){Ja(l)}}
function Uc(a=da){function b(){e.calledRun=!0;if(!q){Vc.Za();e.onRuntimeInitialized?.();e.noInitialRun||Tc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Uc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Uc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Vc;
(async function(){function a(c){c=Vc=c.exports;S=c._a;sc=c.$a;tc=e.__sapp_emsc_onpaste=c.ab;uc=e.__sapp_html5_get_ask_leave_site=c.bb;vc=e.__sapp_emsc_begin_drop=c.cb;wc=e.__sapp_emsc_drop=c.db;xc=e.__sapp_emsc_end_drop=c.eb;e.__sapp_emsc_invoke_fetch_cb=c.fb;e.__sapp_emsc_set_fullscreen_flag=c.gb;yc=e._main=c.hb;e.__saudio_emsc_pull=c.ib;e.__sfetch_emsc_head_response=c.jb;e.__sfetch_emsc_get_response=c.kb;e.__sfetch_emsc_failed_http_status=c.lb;e.__sfetch_emsc_failed_buffer_too_small=c.mb;e.__sfetch_emsc_failed_other=
c.nb;zc=c.ob;Ac=c.pb;Bc=c.qb;Cc=c.rb;Dc=c.sb;Ec=c.tb;Fc=c.ub;Gc=c.yb;Hc=c.zb;Ic=c.Ab;Jc=c.Bb;Kc=c.Cb;Lc=c.Db;Mc=c.Jb;Nc=c.Kb;Oc=c.Lb;Pc=c.Mb;Qc=c.Ob;Rc=c.Pb;Z=c.Qb;wb=c.Rb;Y=c.Sb;sa=c.Ya;hb=c.Nb;ra();D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Vc}D++;e.monitorRunDependencies?.(D);var b={a:Sc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("nuklear-sapp-ui.wasm",ia):ia+"nuklear-sapp-ui.wasm";return a((await ya(b)).instance)})();
Uc();
