var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),h=console.error.bind(console),p,q=!1,na,la=a=>a.startsWith("file://"),t,y,oa,pa,z,A,B,C,qa;
function ra(){var a=sa.buffer;t=new Int8Array(a);oa=new Int16Array(a);y=new Uint8Array(a);pa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=va;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},D=0,E=null,Ea=!0,Fa=0,Ga=[0,31,60,91,121,152,182,213,244,274,305,335],Ha=[0,31,59,90,120,151,181,212,243,273,304,334],F=a=>-9007199254740992>a||9007199254740992<a?NaN:Number(a),G={},Ia=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ja=a=>{na=a;Ea||0<Fa||(e.onExit?.(a),q=!0);fa(a,new za(a))},Ka=a=>{na=a;Ja(a)},La=()=>{if(!(Ea||0<Fa))try{var a=na;na=a;Ja(a)}catch(b){Ia(b)}},H=a=>{if(!q)try{a(),La()}catch(b){Ia(b)}},
I=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0}},Ta=(a,b)=>{Ma=a;Na=b;if(J)if(Oa||=!0,0==a)L=function(){setTimeout(M,Math.max(0,Pa+b-performance.now())|0)};else if(1==a)L=
function(){Qa(M)};else if(2==a){if(!Sa)if(globalThis.setImmediate)Sa=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}L=function(){Sa(M)}}},bb=(a,b,c,d,f)=>{function g(){return k<Ua?(La(),!1):!0}J=a;Va=d;var k=Ua;Oa=!1;M=function(){if(!q)if(0<
Wa.length){var l=Wa.shift();l.sc(l.jc);if(Xa){var n=Xa,u=0==n%1?n-1:Math.floor(n);Xa=l.mc?u:(8*n+(u+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",n=Xa??0,u=Ya.rc??0,n?n<u?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));g()&&setTimeout(M,0)}else if(g())if(Za=Za+1|0,1==Ma&&1<Na&&0!=Za%Na)L();else{0==Ma&&(Pa=performance.now());a:if(!q){for(l of $a)if(!1===l())break a;H(a);for(n of ab)n()}g()&&L()}};f||(0<b?Ta(0,1E3/b):Ta(1,1),L());if(c)throw"unwind";
},Oa=!1,L=null,Ua=0,J=null,Va=0,Ma=0,Na=0,Za=0,Wa=[],$a=[],ab=[];function cb(){L=null;Ua++}var db=0;function Qa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===db)db=b+1E3/60;else for(;b+2>=db;)db+=1E3/60;setTimeout(a,Math.max(db-b,0))}}
var Ya={},Pa,M,Sa,Xa,eb=globalThis.TextDecoder&&new TextDecoder,N=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&eb)return eb.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},fb=
[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],O=a=>{a=2<a?a?N(y,a):"":a;return fb[a]||("undefined"!=typeof document?document.querySelector(a):null)},gb=a=>0>fb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},hb=[],P=a=>{var b=hb[a];b||(hb[a]=b=ib.get(a));return b};function jb(a){var b=Q.nb[a];b.target.removeEventListener(b.mb,b.Xb,b.ob);Q.nb.splice(a,1)}
function kb(){if(navigator.userActivation?navigator.userActivation.isActive:Q.Ob&&Q.hc.Lb){var a=Q.yb;Q.yb=[];for(var b of a)b.Sb(...b.Wb)}}function R(a){if(!a.target)return-4;if(a.vb)a.Xb=function(c){++Q.Ob;Q.hc=a;kb();a.wb(c);kb();--Q.Ob},a.target.addEventListener(a.mb,a.Xb,a.ob),Q.nb.push(a);else for(var b=0;b<Q.nb.length;++b)Q.nb[b].target==a.target&&Q.nb[b].mb==a.mb&&jb(b--);return 0}function lb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var Q={kc:0,tc:0,Pb:0,zb:0,Vb:0,Ub:0,Mb:0,qc:0,wc:0,pc:0,Nb:0,Qb:0,Fc:0,Tb:0,vc(a,b,c){t.set(t.subarray(b,b+c),a)},xc(){for(;Q.nb.length;)jb(Q.nb.length-1);Q.yb=[]},Ob:0,yb:[],oc(a,b,c){function d(g,k){if(g.length!=k.length)return!1;for(var l in g)if(g[l]!=k[l])return!1;return!0}for(var f of Q.yb)if(f.Sb==a&&d(f.Wb,c))return;Q.yb.push({Sb:a,$b:b,Wb:c});Q.yb.sort((g,k)=>g.$b<k.$b)},zc(a){Q.yb=Q.yb.filter(b=>b.Sb!=a)},nb:[],yc:(a,b)=>{for(var c=0;c<Q.nb.length;++c)Q.nb[c].target!=a||b&&b!=Q.nb[c].mb||
jb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},mb=(a,b,c,d,f,g)=>{Q.Mb||(Q.Mb=S(256));a={target:O(a),mb:g,vb:d,wb:(k=event)=>{var l=k.target.id?k.target.id:"",n=Q.Mb;I(lb(k.target),n+0,128);I(l,n+128,128);P(d)(f,n,b)&&k.preventDefault()},ob:c};return R(a)},nb=(a,b,c,d,f)=>{Q.Nb||(Q.Nb=S(276));return R({target:a,mb:f,vb:d,wb:(g=event)=>{var k=Q.Nb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,n=!!l;t[k]=n;t[k+1]=Q.fullscreenEnabled();var u=n?l:Q.ic,v=u?.id||"";I(lb(u),k+2,128);I(v,k+130,128);z[k+260>>2]=u?u.clientWidth:0;z[k+264>>2]=u?u.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;n&&(Q.ic=l);P(d)(19,k,b)&&g.preventDefault()},ob:c})},ob=(a,b,c,d,f,g)=>{Q.Pb||(Q.Pb=S(160));a={target:O(a),mb:g,vb:d,wb:k=>{var l=Q.Pb;C[l>>3]=k.timeStamp;var n=l>>2;z[n+2]=k.location;t[l+12]=k.ctrlKey;t[l+13]=k.shiftKey;t[l+14]=k.altKey;t[l+15]=k.metaKey;t[l+
16]=k.repeat;z[n+5]=k.charCode;z[n+6]=k.keyCode;z[n+7]=k.which;I(k.key||"",l+32,32);I(k.code||"",l+64,32);I(k.char||"",l+96,32);I(k.locale||"",l+128,32);P(d)(f,l,b)&&k.preventDefault()},ob:c};return R(a)},pb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=gb(c);z[d+10]=b.clientX-(a.left|
0);z[d+11]=b.clientY-(a.top|0)},qb=(a,b,c,d,f,g)=>{Q.zb||(Q.zb=S(64));a=O(a);return R({target:a,Lb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,mb:g,vb:d,wb:(k=event)=>{pb(Q.zb,k,a);P(d)(f,Q.zb,b)&&k.preventDefault()},ob:c})},rb=(a,b,c,d)=>{Q.Qb||(Q.Qb=S(257));return R({target:a,mb:"pointerlockchange",vb:d,wb:(f=event)=>{var g=Q.Qb,k=document.pointerLockElement;t[g]=!!k;var l=k?.id||"";I(lb(k),g+1,128);I(l,g+129,128);P(d)(20,g,b)&&f.preventDefault()},ob:c})},sb=(a,b,c,d)=>R({target:a,mb:"pointerlockerror",
vb:d,wb:(f=event)=>{P(d)(38,0,b)&&f.preventDefault()},ob:c}),tb=(a,b,c,d)=>{Q.Ub||(Q.Ub=S(36));a=O(a);return R({target:a,mb:"resize",vb:d,wb:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=Q.Ub;z[k>>2]=0;z[k+4>>2]=g.clientWidth;z[k+8>>2]=g.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;P(d)(10,k,b)&&f.preventDefault()}}},ob:c})},ub=(a,b,c,d,f,g)=>{Q.Tb||(Q.Tb=S(1552));a=O(a);return R({target:a,
Lb:"touchstart"==g||"touchend"==g,mb:g,vb:d,wb:k=>{var l={},n=k.touches;for(var u of n)u.Yb=u.Zb=0,l[u.identifier]=u;for(var v of k.changedTouches)v.Yb=1,l[v.identifier]=v;for(var m of k.targetTouches)l[m.identifier].Zb=1;n=Q.Tb;C[n>>3]=k.timeStamp;t[n+12]=k.ctrlKey;t[n+13]=k.shiftKey;t[n+14]=k.altKey;t[n+15]=k.metaKey;u=n+16;v=gb(a);m=0;for(let r of Object.values(l))if(l=u>>2,z[l]=r.identifier,z[l+1]=r.screenX,z[l+2]=r.screenY,z[l+3]=r.clientX,z[l+4]=r.clientY,z[l+5]=r.pageX,z[l+6]=r.pageY,t[u+28]=
r.Yb,t[u+29]=r.Zb,z[l+8]=r.clientX-(v.left|0),z[l+9]=r.clientY-(v.top|0),u+=48,31<++m)break;z[n+8>>2]=m;P(d)(f,n,b)&&k.preventDefault()},ob:c})},vb=(a,b,c,d)=>{Q.Vb||(Q.Vb=S(96));return R({target:a,Lb:!0,mb:"wheel",vb:d,wb:(f=event)=>{var g=Q.Vb;pb(g,f,a);C[g+64>>3]=f.deltaX;C[g+72>>3]=f.deltaY;C[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;P(d)(9,g,b)&&f.preventDefault()},ob:c})},T=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=
1;c=wb(b);I(a,c,b);return c},U=[],xb=(a,b)=>{U[a>>>0]=b},yb=[],V=a=>{if(a)return U[a>>>0]},zb=a=>{var b=A[a>>2];return b?N(y,b,A[a+4>>2]):""},W=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?N(y,b,a):"";if(0===a)return""},Ab=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),Bb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Cb=a=>{if(0!==a)return{querySet:V(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},Db=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=
b+24*d,g=zb(f+4);c[g]=C[f+16>>3]}return c}},Eb=a=>a?V(a):"auto",Rb=a=>{function b(d){if(d)return{operation:Fb[A[d>>2]],srcFactor:Ib[A[d+4>>2]],dstFactor:Ib[A[d+8>>2]]}}function c(d){return{compare:Jb[A[d>>2]],failOp:Kb[A[d+4>>2]],depthFailOp:Kb[A[d+8>>2]],passOp:Kb[A[d+12>>2]]}}return{label:W(a+4),layout:Eb(A[a+12>>2]),vertex:function(d){if(d){var f=V(A[d+4>>2]),g=Db(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var l=A[d+28>>2];if(k){for(var n=[],u=0;u<k;++u){var v=n,m=v.push;var r=l+24*u;if(r){var w=
A[r+4>>2],x=A[r+16>>2];if(0===w&&0===x)var K=null;else{K=4294967296*A[r+4+8>>2]+A[r+8>>2];w=Lb[w];r=A[r+20>>2];for(var Gb=[],Ra=0;Ra<x;++Ra){var Hb=Gb,ua=r+24*Ra;Hb.push.call(Hb,{format:Mb[A[ua+4>>2]],offset:4294967296*A[ua+4+8>>2]+A[ua+8>>2],shaderLocation:A[ua+16>>2]})}K={arrayStride:K,stepMode:w,attributes:Gb}}}else K=void 0;m.call(v,K)}k=n}else k=void 0;return{module:f,constants:g,buffers:k,entryPoint:W(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Nb[A[d+4>>2]],stripIndexFormat:Ob[A[d+
8>>2]],frontFace:Pb[A[d+12>>2]],cullMode:Qb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:X[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Jb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+
76),fragment:function(d){if(d){for(var f=V(A[d+4>>2]),g=Db(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],l=A[d+28>>2],n=[],u=0;u<k;++u){var v=n,m=v.push,r=l+24*u,w=A[r+4>>2];if(0===w)r=void 0;else{w=X[w];var x=(x=A[r+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;r={format:w,blend:x,writeMask:A[r+16>>2]}}m.call(v,r)}return{module:f,constants:g,targets:n,entryPoint:W(d+8)}}}(A[a+92>>2])}},Sb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",
12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);
qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",
140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.uc&&c("maxImmediateSize",148)},Tb=[,"clamp-to-edge","repeat","mirror-repeat"],Ib=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Fb=[,"add","subtract","reverse-subtract","min","max"],Ub=["binding-not-used",,"uniform","storage","read-only-storage"],Jb=
[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Vb=[,"opaque","premultiplied","unpremultiplied","inherit"],Qb=[,"none","front","back"],Wb=[,"compatibility","core"],Xb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",
12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Yb=[,"nearest","linear"],Pb=[,"ccw","cw"],Ob=[,"uint16","uint32"],Zb=[,"load","clear"],$b=[,"nearest",
"linear"],ac=[,"low-power","high-performance"],bc=[,"srgb","display-p3"],Nb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],cc=["binding-not-used",,"filtering","non-filtering","comparison"],Kb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],dc=["binding-not-used",,"write-only","read-only","read-write"],ec=[,"store","discard"],fc=[,"all","stencil-only","depth-only"],gc=[,"1d","2d","3d"],X=[,"r8unorm","r8snorm","r8uint",
"r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8",
"depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm",
"eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm",
"astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],hc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],ic=[,"1d","2d","2d-array","cube","cube-array","3d"],jc=[,"standard","extended"],Mb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4",
"float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Lb=[,"vertex","instance"],kc={undefined:1,unknown:1,destroyed:2},lc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";lc.Rb||(lc.Rb={});lc.Rb[a]||(lc.Rb[a]=1,ca&&(a="warning: "+a),h(a))},mc={rgba8unorm:22,bgra8unorm:27},nc=[null,[],[]],oc=a=>{var b=Y();a();Z(b)};e.requestAnimationFrame=Qa;e.pauseMainLoop=cb;
e.resumeMainLoop=function(){Ua++;var a=Ma,b=Na,c=J;J=null;bb(c,0,!1,Va,!0);Ta(a,b);L()};e.preMainLoop&&$a.push(e.preMainLoop);e.postMainLoop&&ab.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(h=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var S,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Z,wb,Y,sa,ib,Pc={T:()=>ta(""),M:()=>{Ea=!1;Fa=0},P:function(a,b){a=F(a);a=new Date(1E3*a);z[b>>2]=a.getSeconds();z[b+4>>2]=a.getMinutes();z[b+8>>2]=a.getHours();z[b+12>>2]=a.getDate();z[b+16>>2]=a.getMonth();z[b+20>>2]=a.getFullYear()-1900;z[b+24>>2]=a.getDay();var c=a.getFullYear();z[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ha:Ga)[a.getMonth()]+a.getDate()-1|0;z[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},N:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];H(()=>Nc(a,performance.now()))},b);G[a]={id:c,Dc:b};return 0},Q:(a,b,c,d)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();A[a>>2]=60*Math.max(g,f);z[b>>2]=Number(g!=f);b=k=>{var l=Math.abs(k);
return`UTC${0<=k?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(f);f<g?(I(a,c,17),I(b,d,17)):(I(a,d,17),I(b,c,17))},Aa:()=>{cb();J=null},S:()=>Date.now(),G:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,I:(a,b,c)=>{a=O(a);if(!a)return-4;a=gb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},Ba:()=>performance.now(),Ha:(a,b)=>{function c(d){P(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},O:a=>{var b=y.length;a>>>=0;if(2147483648<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},o:(a,b,c,d)=>mb(a,b,c,d,12,"blur"),F:(a,b,c)=>{a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},p:(a,b,c,d)=>mb(a,b,c,d,13,"focus"),n:(a,b,c,d)=>{if(!Q.fullscreenEnabled())return-1;a=O(a);if(!a)return-4;nb(a,b,c,d,"webkitfullscreenchange");return nb(a,
b,c,d,"fullscreenchange")},y:(a,b,c,d)=>ob(a,b,c,d,2,"keydown"),w:(a,b,c,d)=>ob(a,b,c,d,1,"keypress"),x:(a,b,c,d)=>ob(a,b,c,d,3,"keyup"),Ja:(a,b,c)=>{a=P(a);bb(a,b,c)},E:(a,b,c,d)=>qb(a,b,c,d,5,"mousedown"),B:(a,b,c,d)=>qb(a,b,c,d,33,"mouseenter"),A:(a,b,c,d)=>qb(a,b,c,d,34,"mouseleave"),C:(a,b,c,d)=>qb(a,b,c,d,8,"mousemove"),D:(a,b,c,d)=>qb(a,b,c,d,6,"mouseup"),r:(a,b,c,d)=>document.body?.requestPointerLock?(a=O(a))?rb(a,b,c,d):-4:-1,q:(a,b,c,d)=>document.body?.requestPointerLock?(a=O(a))?sb(a,b,
c,d):-4:-1,H:(a,b,c,d)=>tb(a,b,c,d),s:(a,b,c,d)=>ub(a,b,c,d,25,"touchcancel"),t:(a,b,c,d)=>ub(a,b,c,d,23,"touchend"),u:(a,b,c,d)=>ub(a,b,c,d,24,"touchmove"),v:(a,b,c,d)=>ub(a,b,c,d,22,"touchstart"),z:(a,b,c,d)=>(a=O(a))?"undefined"!=typeof a.onwheel?vb(a,b,c,d):-1:-4,X:function(a,b,c,d,f,g){b=F(b);c=F(c);a=V(a);var k={};if(g){var l=A[g+12>>2];if(l){var n=A[g+16>>2];k.requiredFeatures=Array.from(A.subarray(n>>2,n+4*l>>2),m=>Xb[m])}var u=A[g+20>>2];if(u){var v={};function m(w,x,K=!1){x=A[u+x>>2];4294967295==
x||K&&0==x||(v[w]=x)}function r(w,x){x=u+x;var K=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=K)v[w]=4294967296*A[x+4>>2]+A[x>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",24);m("maxDynamicUniformBuffersPerPipelineLayout",32);m("maxDynamicStorageBuffersPerPipelineLayout",36);m("maxSampledTexturesPerShaderStage",40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",
48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);r("maxUniformBufferBindingSize",64);r("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);r("maxBufferSize",96);m("maxVertexAttributes",104);m("maxVertexBufferArrayStride",108);m("maxInterStageShaderVariables",112);m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",
128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",148,!0);k.requiredLimits=v}if(l=A[g+24>>2])l={label:W(l+4)},k.defaultQueue=l;k.label=W(g+4)}a.requestDevice(k).then(m=>{H(()=>{U[f>>>0]=m.queue;U[d>>>0]=m;m.lost.then(r=>{H(()=>{m.onuncapturederror=()=>{};var w=Y(),x=T(r.message);Jc(c,kc[r.reason],x);Z(w)})});m.onuncapturederror=r=>{var w=5;r.error instanceof GPUValidationError?w=
2:r.error instanceof GPUOutOfMemoryError?w=3:r.error instanceof GPUInternalError&&(w=4);var x=Y();r=T(r.error.message);Mc(d,w,r);Z(x)};Lc(b,1,d,0)})},m=>{H(()=>{var r=Y(),w=T(m.message);Lc(b,3,d,w);c&&Jc(c,4,w);Z(r)})})},$:(a,b,c)=>{var d=V(a);0===c&&lc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(k){return 0}var g=Oc(16,f.byteLength);y.fill(0,g,f.byteLength);yb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(g,g+f.byteLength));pc(g)});return g},_:a=>{var b=V(a),c=yb[a];if(c){for(var d=
0;d<c.length;++d)c[d]();delete yb[a];b.unmap()}},a:a=>{delete U[a]},h:(a,b,c)=>{var d=!!A[b+32>>2];b={label:W(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=V(a);try{var f=a.createBuffer(b)}catch(g){return!1}U[c>>>0]=f;d&&(yb[c]=[]);return!0},W:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:W(b+4),code:""};switch(f){case 2:b.code=zb(d+8)}a=V(a).createShaderModule(b);U[c>>>0]=a},Z:a=>{a=V(a);a.onuncapturederror=null;a.destroy()},U:()=>{var a=navigator.gpu.getPreferredCanvasFormat();
return mc[a]},V:function(a,b,c,d){b=F(b);if(c){var f={featureLevel:Wb[A[c+4>>2]],powerPreference:ac[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Gc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(g=>{H(()=>{if(g)U[d>>>0]=g,Kc(b,1,d,0);else{var k=Y(),l=T("WebGPU not available on this browser (requestAdapter returned null)");Kc(b,3,d,l);Z(k)}})},g=>{H(()=>{var k=Y(),l=T(g.message);Kc(b,4,d,l);Z(k)})}):(f=Y(),a=T("WebGPU not available on this browser (navigator.gpu is not available)"),
Kc(b,3,d,a),Z(f))},R:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var k=A[b>>2],l=A[b+4>>2];b+=8;for(var n=0;n<l;n++){var u=a,v=y[k+n],m=nc[u];0===v||10===v?((1===u?ma:h)(N(m)),m.length=0):m.push(v)}f+=l}A[d>>2]=f;return 0},L:Ja,Na:function(){e.ac=a=>{0!=rc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.ac)},Da:function(){e.fc=a=>{const b=a.clipboardData.getData("text");oc(()=>{const c=T(b);qc(c)})};window.addEventListener("paste",e.fc)},pa:function(){e.Ac=[];e.bc=b=>
{b.stopPropagation();b.preventDefault()};e.cc=b=>{b.stopPropagation();b.preventDefault()};e.dc=b=>{b.stopPropagation();b.preventDefault()};e.ec=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Bc=c;sc(c.length);for(let f=0;f<c.length;f++)oc(()=>{const g=T(c[f].name);tc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);uc(b.clientX,b.clientY,d)};const a=e.xb;a.addEventListener("dragenter",e.bc,!1);a.addEventListener("dragleave",e.cc,!1);
a.addEventListener("dragover",e.dc,!1);a.addEventListener("drop",e.ec,!1)},La:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ma:function(a){e.Kb&&(URL.revokeObjectURL(e.Kb[a].lc),e.Kb[a]=null)},Y:function(a,b){0!==b&&(document.title=b?N(y,b):"");a=a?N(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?fb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.xb=O(a);e.xb||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);e.xb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ia:function(){window.removeEventListener("beforeunload",e.ac)},Ca:function(){window.removeEventListener("paste",e.fc)},ga:function(){const a=e.xb;a.removeEventListener("dragenter",e.bc);a.removeEventListener("dragleave",e.cc);a.removeEventListener("dragover",e.dc);a.removeEventListener("drop",e.ec)},g:function(){e.xb&&e.xb.requestPointerLock&&e.xb.requestPointerLock()},K:function(a,b,c){if(e.xb){if(0===
b)a="none";else if(0!=c)a=e.Kb[a].nc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.xb.style.cursor=a}},Ka:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,
b);g.data.set(y.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ya:function(a){a=a?N(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);
b.select();document.execCommand("copy");document.body.removeChild(b)},J:function(a,b){b=b?N(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Oa:function(){return navigator.userAgent.includes("Macintosh")?1:0},Ea:(a,b)=>{Sb(V(a).limits,b);return 1},e:(a,b)=>V(a).features.has(Xb[b]),qa:(a,b)=>{var c;b&&(c={label:W(b+4),timestampWrites:Cb(A[b+12>>2])});b=V(a);a=Ac(0);c=b.beginComputePass(c);U[a>>>0]=c;return a},oa:(a,
b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=W(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],k=[],l=0;l<f;++l){var n=k,u=n.push;var v=g+56*l;var m=A[v+4>>2];if(0!==m){var r=z[v+8>>2];-1==r&&(r=void 0);v={view:V(m),depthSlice:r,resolveTarget:V(A[v+12>>2]),clearValue:Ab(v+24),loadOp:Zb[A[v+16>>2]],storeOp:ec[A[v+20>>2]]}}else v=void 0;u.call(n,v)}f=A[b+20>>2];f=0!==f?{view:V(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Zb[A[f+8>>2]],depthStoreOp:ec[A[f+12>>2]],depthReadOnly:!!A[f+
20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Zb[A[f+24>>2]],stencilStoreOp:ec[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:V(A[b+24>>2]),timestampWrites:Cb(A[b+28>>2]),maxDrawCount:d};d=V(a);a=Dc(0);b=d.beginRenderPass(b);U[a>>>0]=b;return a},ba:a=>{var b=V(a);a=yc(0);b=b.finish();U[a>>>0]=b;return a},ca:a=>{V(a).end()},c:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ma:(a,b)=>{V(a).setPipeline(V(b))},
k:(a,b)=>{var c=W(b+4),d=V(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var g=[],k=0;k<f;++k){var l=g,n=l.push;var u=b+40*k;var v=A[u+8>>2],m=A[u+32>>2],r=A[u+36>>2],w=A[u+4>>2];v?(m=u+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),u={binding:w,resource:{buffer:V(v),offset:4294967296*A[u+4+16>>2]+A[u+16>>2],size:m}}):u=m?{binding:w,resource:V(m)}:{binding:w,resource:V(r)};n.call(l,u)}c={label:c,layout:d,entries:g};d=V(a);a=wc(0);c=d.createBindGroup(c);U[a>>>0]=c;return a},l:(a,b)=>{var c=W(b+4),
d=A[b+12>>2];b=A[b+16>>2];for(var f=[],g=0;g<d;++g){var k=f,l=k.push,n=b+88*g,u=A[n+4>>2],v=A[n+8>>2];var m=n+24;var r=A[m+4>>2];m=r?{type:Ub[r],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;r=(r=A[n+48+4>>2])?{type:cc[r]}:void 0;var w=n+56;var x=A[w+4>>2];w=x?{sampleType:hc[x],viewDimension:ic[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;n+=72;n=(x=A[n+4>>2])?{access:dc[x],format:X[A[n+8>>2]],viewDimension:ic[A[n+12>>2]]}:void 0;l.call(k,{binding:u,visibility:v,
buffer:m,sampler:r,texture:w,storageTexture:n})}c={label:c,entries:f};d=V(a);a=xc(0);c=d.createBindGroupLayout(c);U[a>>>0]=c;return a},ra:(a,b)=>{var c;b&&(c={label:W(b+4)});b=V(a);a=zc(0);c=b.createCommandEncoder(c);U[a>>>0]=c;return a},ta:(a,b)=>{var c=W(b+4);var d=Eb(A[b+12>>2]);b=(b+=16)?{module:V(A[b+4>>2]),constants:Db(A[b+16>>2],A[b+20>>2]),entryPoint:W(b+8)}:void 0;c={label:c,layout:d,compute:b};d=V(a);a=Bc(0);c=d.createComputePipeline(c);U[a>>>0]=c;return a},ua:(a,b)=>{for(var c=A[b+12>>
2],d=A[b+16>>2],f=[],g=0;g<c;++g)f.push(V(A[d+4*g>>2]));b={label:W(b+4),bindGroupLayouts:f};c=V(a);a=Cc(0);b=c.createPipelineLayout(b);U[a>>>0]=b;return a},sa:(a,b)=>{b=Rb(b);var c=V(a);a=Ec(0);b=c.createRenderPipeline(b);U[a>>>0]=b;return a},va:(a,b)=>{var c;b&&(c={label:W(b+4),addressModeU:Tb[A[b+12>>2]],addressModeV:Tb[A[b+16>>2]],addressModeW:Tb[A[b+20>>2]],magFilter:Yb[A[b+24>>2]],minFilter:Yb[A[b+28>>2]],mipmapFilter:$b[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Jb[A[b+
44>>2]],maxAnisotropy:pa[b+48>>1]});b=V(a);a=Fc(0);c=b.createSampler(c);U[a>>>0]=c;return a},m:(a,b)=>{var c={label:W(b+4),size:Bb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:gc[A[b+24>>2]],format:X[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>X[f]));a=V(a);d=Hc(0);xb(d,a.createTexture(c));return d},xa:(a,b)=>{Sb(V(a).limits,b);return 1},d:(a,b)=>V(a).features.has(Xb[b]),Ga:(a,b)=>{a=O(A[A[b>>2]+8>>2]).getContext("webgpu");
if(!a)return 0;a.Cc=W(b+4);b=Gc(0);U[b>>>0]=a;return b},aa:(a,b,c)=>{a=V(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>V(d));a.submit(b)},i:function(a,b,c,d,f){c=F(c);V(a).writeBuffer(V(b),c,y.subarray(d,d+f),0,f)},wa:(a,b,c,d,f,g)=>{var k=A[f+8>>2],l=A[f+12>>2],n=b+8;V(a).writeTexture({texture:V(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[n>>2],y:A[n+4>>2],z:A[n+8>>2]},aspect:fc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===k?void 0:k,rowsPerImage:4294967295===
l?void 0:l},Bb(g))},ea:(a,b,c,d,f)=>{V(a).draw(b,c,d>>>0,f>>>0)},fa:(a,b,c,d,f,g)=>{V(a).drawIndexed(b,c,d>>>0,f,g>>>0)},da:a=>{V(a).end()},b:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ka:(a,b)=>{V(a).setBlendConstant(Ab(b))},ia:function(a,b,c,d,f){d=F(d);f=F(f);a=V(a);b=V(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Ob[c],d,f)},la:(a,b)=>{V(a).setPipeline(V(b))},j:(a,b,c,d,f)=>{V(a).setScissorRect(b,c,d,f)},ja:(a,b)=>{V(a).setStencilReference(b>>>0)},ha:function(a,
b,c,d,f){d=F(d);f=F(f);a=V(a);c=V(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},na:(a,b,c,d,f,g,k)=>{V(a).setViewport(b,c,d,f,g,k)},Fa:(a,b)=>{var c=A[b+4>>2];a=V(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:V(c),format:X[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Vb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),g=>X[g])}b=A[b>>2];0!==b&&(c.colorSpace=bc[A[b+8>>2]],c.Ec={mode:jc[A[b+12>>
2]]});a.configure(c)},za:(a,b)=>{a=V(a);try{var c=Hc(0),d=a.getCurrentTexture();U[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:W(b+4),format:X[A[b+12>>2]],dimension:ic[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:fc[A[b+36>>2]]}}b=V(a);a=Ic(0);b=b.createView(c);U[a>>>0]=b;return a}};
function Qc(a=[]){var b=vc;a.unshift(ea);var c=a.length,d=wb(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=T(k);f+=4});A[f>>2]=0;try{var g=b(c,d);Ka(g)}catch(k){Ia(k)}}
function Rc(a=da){function b(){e.calledRun=!0;if(!q){Sc.Qa();e.onRuntimeInitialized?.();e.noInitialRun||Qc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Rc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Rc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Sc;
(async function(){function a(c){c=Sc=c.exports;S=c.Ra;pc=c.Sa;qc=e.__sapp_emsc_onpaste=c.Ta;rc=e.__sapp_html5_get_ask_leave_site=c.Ua;sc=e.__sapp_emsc_begin_drop=c.Va;tc=e.__sapp_emsc_drop=c.Wa;uc=e.__sapp_emsc_end_drop=c.Xa;e.__sapp_emsc_invoke_fetch_cb=c.Ya;e.__sapp_emsc_set_fullscreen_flag=c.Za;vc=e._main=c._a;e.__saudio_emsc_pull=c.$a;e.__sfetch_emsc_head_response=c.ab;e.__sfetch_emsc_get_response=c.bb;e.__sfetch_emsc_failed_http_status=c.cb;e.__sfetch_emsc_failed_buffer_too_small=c.db;e.__sfetch_emsc_failed_other=
c.eb;wc=c.fb;xc=c.gb;yc=c.hb;zc=c.ib;Ac=c.jb;Bc=c.kb;Cc=c.lb;Dc=c.pb;Ec=c.qb;Fc=c.rb;Gc=c.sb;Hc=c.tb;Ic=c.ub;Jc=c.Ab;Kc=c.Bb;Lc=c.Cb;Mc=c.Db;Nc=c.Fb;Oc=c.Gb;Z=c.Hb;wb=c.Ib;Y=c.Jb;sa=c.Pa;ib=c.Eb;ra();D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Sc}D++;e.monitorRunDependencies?.(D);var b={a:Pc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});va??=e.locateFile?e.locateFile("nuklear-sapp.wasm",ia):ia+"nuklear-sapp.wasm";return a((await ya(b)).instance)})();
Rc();
