var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),h=console.error.bind(console),p,q=!1,na,la=a=>a.startsWith("file://"),oa,t,y,pa,qa,z,A,B,C,ra;
function sa(){var a=oa.buffer;t=new Int8Array(a);pa=new Int16Array(a);y=new Uint8Array(a);qa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var D=0,E=null;function ta(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=va;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},Ea=!0,Fa=0,Ga=[0,31,60,91,121,152,182,213,244,274,305,335],Ha=[0,31,59,90,120,151,181,212,243,273,304,334],F=a=>-9007199254740992>a||9007199254740992<a?NaN:Number(a),G={},Ia=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ja=a=>{na=a;Ea||0<Fa||(e.onExit?.(a),q=!0);fa(a,new za(a))},Ka=a=>{na=a;Ja(a)},La=()=>{if(!(Ea||0<Fa))try{var a=na;na=a;Ja(a)}catch(b){Ia(b)}},Ma=a=>{if(!q)try{a(),La()}catch(b){Ia(b)}},H=
(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0}},Ua=(a,b)=>{Na=a;Oa=b;if(I)if(Pa||=!0,0==a)J=function(){setTimeout(L,Math.max(0,Qa+b-performance.now())|0)};else if(1==a)J=function(){Ra(L)};
else if(2==a){if("undefined"==typeof Ta)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ta=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ta=setImmediate;J=function(){Ta(L)}}},cb=(a,b,c,d,f)=>{function g(){return k<Va?(La(),!1):!0}I=a;Wa=d;var k=Va;Pa=
!1;L=function(){if(!q)if(0<Xa.length){var l=Xa.shift();l.rc(l.ic);if(Ya){var n=Ya,u=0==n%1?n-1:Math.floor(n);Ya=l.lc?u:(8*n+(u+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",n=Ya??0,u=Za.qc??0,n?n<u?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));g()&&setTimeout(L,0)}else if(g())if($a=$a+1|0,1==Na&&1<Oa&&0!=$a%Oa)J();else{0==Na&&(Qa=performance.now());a:if(!q){for(l of ab)if(!1===l())break a;Ma(a);for(n of bb)n()}g()&&J()}};f||(0<b?Ua(0,1E3/b):
Ua(1,1),J());if(c)throw"unwind";},Pa=!1,J=null,Va=0,I=null,Wa=0,Na=0,Oa=0,$a=0,Xa=[],ab=[],bb=[];function db(){J=null;Va++}var eb=0;function Ra(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===eb)eb=b+1E3/60;else for(;b+2>=eb;)eb+=1E3/60;setTimeout(a,Math.max(eb-b,0))}}
var Za={},Qa,L,Ta,Ya,fb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,M=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&fb)return fb.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},
gb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?M(y,a):"":a;return gb[a]||("undefined"!=typeof document?document.querySelector(a):null)},hb=a=>0>gb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ib=[],jb,O=a=>{var b=ib[a];b||(ib[a]=b=jb.get(a));return b};function kb(a){var b=P.mb[a];b.target.removeEventListener(b.lb,b.Wb,b.nb);P.mb.splice(a,1)}
function lb(){if(navigator.userActivation?navigator.userActivation.isActive:P.Nb&&P.fc.Kb){var a=P.xb;P.xb=[];for(var b of a)b.Rb(...b.Vb)}}function Q(a){if(!a.target)return-4;if(a.ub)a.Wb=function(c){++P.Nb;P.fc=a;lb();a.vb(c);lb();--P.Nb},a.target.addEventListener(a.lb,a.Wb,a.nb),P.mb.push(a);else for(var b=0;b<P.mb.length;++b)P.mb[b].target==a.target&&P.mb[b].lb==a.lb&&kb(b--);return 0}function mb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={jc:0,sc:0,Ob:0,yb:0,Ub:0,Tb:0,Lb:0,pc:0,vc:0,oc:0,Mb:0,Pb:0,Ec:0,Sb:0,uc(a,b,c){t.set(t.subarray(b,b+c),a)},wc(){for(;P.mb.length;)kb(P.mb.length-1);P.xb=[]},Nb:0,xb:[],nc(a,b,c){function d(g,k){if(g.length!=k.length)return!1;for(var l in g)if(g[l]!=k[l])return!1;return!0}for(var f of P.xb)if(f.Rb==a&&d(f.Vb,c))return;P.xb.push({Rb:a,Zb:b,Vb:c});P.xb.sort((g,k)=>g.Zb<k.Zb)},yc(a){P.xb=P.xb.filter(b=>b.Rb!=a)},mb:[],xc:(a,b)=>{for(var c=0;c<P.mb.length;++c)P.mb[c].target!=a||b&&b!=P.mb[c].lb||
kb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},nb=(a,b,c,d,f,g)=>{P.Lb||(P.Lb=R(256));a={target:N(a),lb:g,ub:d,vb:(k=event)=>{var l=k.target.id?k.target.id:"",n=P.Lb;H(mb(k.target),n+0,128);H(l,n+128,128);O(d)(f,n,b)&&k.preventDefault()},nb:c};return Q(a)},ob=(a,b,c,d,f)=>{P.Mb||(P.Mb=R(276));return Q({target:a,lb:f,ub:d,vb:(g=event)=>{var k=P.Mb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,n=!!l;t[k]=n;t[k+1]=P.fullscreenEnabled();var u=n?l:P.hc,v=u?.id||"";H(mb(u),k+2,128);H(v,k+130,128);z[k+260>>2]=u?u.clientWidth:0;z[k+264>>2]=u?u.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;n&&(P.hc=l);O(d)(19,k,b)&&g.preventDefault()},nb:c})},pb=(a,b,c,d,f,g)=>{P.Ob||(P.Ob=R(160));a={target:N(a),lb:g,ub:d,vb:k=>{var l=P.Ob;C[l>>3]=k.timeStamp;var n=l>>2;z[n+2]=k.location;t[l+12]=k.ctrlKey;t[l+13]=k.shiftKey;t[l+14]=k.altKey;t[l+15]=k.metaKey;t[l+
16]=k.repeat;z[n+5]=k.charCode;z[n+6]=k.keyCode;z[n+7]=k.which;H(k.key||"",l+32,32);H(k.code||"",l+64,32);H(k.char||"",l+96,32);H(k.locale||"",l+128,32);O(d)(f,l,b)&&k.preventDefault()},nb:c};return Q(a)},qb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=hb(c);z[d+10]=b.clientX-(a.left|
0);z[d+11]=b.clientY-(a.top|0)},rb=(a,b,c,d,f,g)=>{P.yb||(P.yb=R(64));a=N(a);return Q({target:a,Kb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,lb:g,ub:d,vb:(k=event)=>{qb(P.yb,k,a);O(d)(f,P.yb,b)&&k.preventDefault()},nb:c})},sb=(a,b,c,d)=>{P.Pb||(P.Pb=R(257));return Q({target:a,lb:"pointerlockchange",ub:d,vb:(f=event)=>{var g=P.Pb,k=document.pointerLockElement;t[g]=!!k;var l=k?.id||"";H(mb(k),g+1,128);H(l,g+129,128);O(d)(20,g,b)&&f.preventDefault()},nb:c})},tb=(a,b,c,d)=>Q({target:a,lb:"pointerlockerror",
ub:d,vb:(f=event)=>{O(d)(38,0,b)&&f.preventDefault()},nb:c}),ub=(a,b,c,d)=>{P.Tb||(P.Tb=R(36));a=N(a);return Q({target:a,lb:"resize",ub:d,vb:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=P.Tb;z[k>>2]=0;z[k+4>>2]=g.clientWidth;z[k+8>>2]=g.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;O(d)(10,k,b)&&f.preventDefault()}}},nb:c})},vb=(a,b,c,d,f,g)=>{P.Sb||(P.Sb=R(1552));a=N(a);return Q({target:a,
Kb:"touchstart"==g||"touchend"==g,lb:g,ub:d,vb:k=>{var l={},n=k.touches;for(var u of n)u.Xb=u.Yb=0,l[u.identifier]=u;for(var v of k.changedTouches)v.Xb=1,l[v.identifier]=v;for(var m of k.targetTouches)l[m.identifier].Yb=1;n=P.Sb;C[n>>3]=k.timeStamp;t[n+12]=k.ctrlKey;t[n+13]=k.shiftKey;t[n+14]=k.altKey;t[n+15]=k.metaKey;u=n+16;v=hb(a);m=0;for(let r of Object.values(l))if(l=u>>2,z[l]=r.identifier,z[l+1]=r.screenX,z[l+2]=r.screenY,z[l+3]=r.clientX,z[l+4]=r.clientY,z[l+5]=r.pageX,z[l+6]=r.pageY,t[u+28]=
r.Xb,t[u+29]=r.Yb,z[l+8]=r.clientX-(v.left|0),z[l+9]=r.clientY-(v.top|0),u+=48,31<++m)break;z[n+8>>2]=m;O(d)(f,n,b)&&k.preventDefault()},nb:c})},wb=(a,b,c,d)=>{P.Ub||(P.Ub=R(96));return Q({target:a,Kb:!0,lb:"wheel",ub:d,vb:(f=event)=>{var g=P.Ub;qb(g,f,a);C[g+64>>3]=f.deltaX;C[g+72>>3]=f.deltaY;C[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;O(d)(9,g,b)&&f.preventDefault()},nb:c})},S=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=
1;c=xb(b);H(a,c,b);return c},yb=[],T=(a,b)=>{yb[a>>>=0]=b},zb=[],U=a=>{if(a)return yb[a>>>0]},Ab=a=>{var b=A[a>>2];return b?M(y,b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?M(y,b,a):"";if(0===a)return""},Bb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),Cb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Db=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},Eb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=
b+24*d,g=Ab(f+4);c[g]=C[f+16>>3]}return c}},Fb=a=>a?U(a):"auto",Sb=a=>{function b(d){if(d)return{operation:Gb[A[d>>2]],srcFactor:Jb[A[d+4>>2]],dstFactor:Jb[A[d+8>>2]]}}function c(d){return{compare:Kb[A[d>>2]],failOp:Lb[A[d+4>>2]],depthFailOp:Lb[A[d+8>>2]],passOp:Lb[A[d+12>>2]]}}return{label:V(a+4),layout:Fb(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),g=Eb(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var l=A[d+28>>2];if(k){for(var n=[],u=0;u<k;++u){var v=n,m=v.push;var r=l+24*u;if(r){var w=
A[r+4>>2],x=A[r+16>>2];if(0===w&&0===x)var K=null;else{K=4294967296*A[r+4+8>>2]+A[r+8>>2];w=Mb[w];r=A[r+20>>2];for(var Hb=[],Sa=0;Sa<x;++Sa){var Ib=Hb,xc=Ib.push,ua=r+24*Sa;xc.call(Ib,{format:Nb[A[ua+4>>2]],offset:4294967296*A[ua+4+8>>2]+A[ua+8>>2],shaderLocation:A[ua+16>>2]})}K={arrayStride:K,stepMode:w,attributes:Hb}}}else K=void 0;m.call(v,K)}k=n}else k=void 0;return{module:f,constants:g,buffers:k,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Ob[A[d+4>>2]],stripIndexFormat:Pb[A[d+
8>>2]],frontFace:Qb[A[d+12>>2]],cullMode:Rb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Kb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+
76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),g=Eb(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],l=A[d+28>>2],n=[],u=0;u<k;++u){var v=n,m=v.push,r=l+24*u,w=A[r+4>>2];if(0===w)r=void 0;else{w=W[w];var x=(x=A[r+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;r={format:w,blend:x,writeMask:A[r+16>>2]}}m.call(v,r)}return{module:f,constants:g,targets:n,entryPoint:V(d+8)}}}(A[a+92>>2])}},Tb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",
12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);
ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",
140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.tc&&c("maxImmediateSize",148)},Ub=[,"clamp-to-edge","repeat","mirror-repeat"],Jb=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Gb=[,"add","subtract","reverse-subtract","min","max"],Vb=["binding-not-used",,"uniform","storage","read-only-storage"],Kb=
[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Wb=[,"opaque","premultiplied","unpremultiplied","inherit"],Rb=[,"none","front","back"],Xb=[,"compatibility","core"],Yb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",
12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Zb=[,"nearest","linear"],Qb=[,"ccw","cw"],Pb=[,"uint16","uint32"],$b=[,"load","clear"],ac=[,"nearest","linear"],bc=[,"low-power",
"high-performance"],cc=[,"srgb","display-p3"],Ob=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],dc=["binding-not-used",,"filtering","non-filtering","comparison"],Lb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],ec=["binding-not-used",,"write-only","read-only","read-write"],fc=[,"store","discard"],gc=[,"all","stencil-only","depth-only"],hc=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm",
"r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus",
"depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm",
"astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb",
"astc-12x12-unorm","astc-12x12-unorm-srgb"],ic=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],jc=[,"1d","2d","2d-array","cube","cube-array","3d"],kc=[,"standard","extended"],Nb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2",
"float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Mb=[,"vertex","instance"],lc={undefined:1,unknown:1,destroyed:2},mc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";mc.Qb||(mc.Qb={});mc.Qb[a]||(mc.Qb[a]=1,ca&&(a="warning: "+a),h(a))},nc={rgba8unorm:22,bgra8unorm:27},oc=[null,[],[]],pc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Ra;e.pauseMainLoop=db;
e.resumeMainLoop=function(){Va++;var a=Na,b=Oa,c=I;I=null;cb(c,0,!1,Wa,!0);Ua(a,b);J()};e.preMainLoop&&ab.push(e.preMainLoop);e.postMainLoop&&bb.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(h=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
var R,qc,rc,sc,tc,uc,vc,wc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Y,xb,X,Rc={U:()=>ta(""),N:()=>{Ea=!1;Fa=0},Q:function(a,b){a=F(a);a=new Date(1E3*a);z[b>>2]=a.getSeconds();z[b+4>>2]=a.getMinutes();z[b+8>>2]=a.getHours();z[b+12>>2]=a.getDate();z[b+16>>2]=a.getMonth();z[b+20>>2]=a.getFullYear()-1900;z[b+24>>2]=a.getDay();var c=a.getFullYear();z[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ha:Ga)[a.getMonth()]+a.getDate()-1|0;z[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},O:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];Ma(()=>Pc(a,performance.now()))},b);G[a]={id:c,Cc:b};return 0},R:(a,b,c,d)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();A[a>>2]=60*Math.max(g,f);z[b>>2]=Number(g!=f);b=k=>{var l=Math.abs(k);
return`UTC${0<=k?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(f);f<g?(H(a,c,17),H(b,d,17)):(H(a,d,17),H(b,c,17))},Aa:()=>{db();I=null},T:()=>Date.now(),H:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,J:(a,b,c)=>{a=N(a);if(!a)return-4;a=hb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},Ba:()=>performance.now(),Ga:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},P:a=>{var b=y.length;a>>>=0;if(2147483648<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},p:(a,b,c,d)=>nb(a,b,c,d,12,"blur"),G:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},q:(a,b,c,d)=>nb(a,b,c,d,13,"focus"),o:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=N(a);if(!a)return-4;ob(a,b,c,d,"webkitfullscreenchange");return ob(a,
b,c,d,"fullscreenchange")},z:(a,b,c,d)=>pb(a,b,c,d,2,"keydown"),x:(a,b,c,d)=>pb(a,b,c,d,1,"keypress"),y:(a,b,c,d)=>pb(a,b,c,d,3,"keyup"),Ia:(a,b,c)=>{a=O(a);cb(a,b,c)},F:(a,b,c,d)=>rb(a,b,c,d,5,"mousedown"),C:(a,b,c,d)=>rb(a,b,c,d,33,"mouseenter"),B:(a,b,c,d)=>rb(a,b,c,d,34,"mouseleave"),D:(a,b,c,d)=>rb(a,b,c,d,8,"mousemove"),E:(a,b,c,d)=>rb(a,b,c,d,6,"mouseup"),s:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?sb(a,b,c,d):-4:-1,r:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?tb(a,b,
c,d):-4:-1,I:(a,b,c,d)=>ub(a,b,c,d),t:(a,b,c,d)=>vb(a,b,c,d,25,"touchcancel"),u:(a,b,c,d)=>vb(a,b,c,d,23,"touchend"),v:(a,b,c,d)=>vb(a,b,c,d,24,"touchmove"),w:(a,b,c,d)=>vb(a,b,c,d,22,"touchstart"),A:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?wb(a,b,c,d):-1:-4,Y:function(a,b,c,d,f,g){b=F(b);c=F(c);a=U(a);var k={};if(g){var l=A[g+12>>2];if(l){var n=A[g+16>>2];k.requiredFeatures=Array.from(A.subarray(n>>2,n+4*l>>2),m=>Yb[m])}var u=A[g+20>>2];if(u){var v={};function m(w,x,K=!1){x=A[u+x>>2];4294967295==
x||K&&0==x||(v[w]=x)}function r(w,x){x=u+x;var K=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=K)v[w]=4294967296*A[x+4>>2]+A[x>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",24);m("maxDynamicUniformBuffersPerPipelineLayout",32);m("maxDynamicStorageBuffersPerPipelineLayout",36);m("maxSampledTexturesPerShaderStage",40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",
48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);r("maxUniformBufferBindingSize",64);r("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);r("maxBufferSize",96);m("maxVertexAttributes",104);m("maxVertexBufferArrayStride",108);m("maxInterStageShaderVariables",112);m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",
128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",148,!0);k.requiredLimits=v}if(l=A[g+24>>2])l={label:V(l+4)},k.defaultQueue=l;k.label=V(g+4)}a.requestDevice(k).then(m=>{T(f,m.queue);T(d,m);c&&m.lost.then(r=>{m.onuncapturederror=()=>{};var w=X(),x=S(r.message);Lc(c,lc[r.reason],x);Y(w)});m.onuncapturederror=r=>{var w=5;r.error instanceof GPUValidationError?w=2:r.error instanceof
GPUOutOfMemoryError?w=3:r.error instanceof GPUInternalError&&(w=4);var x=X();r=S(r.error.message);Oc(d,w,r);Y(x)};Nc(b,1,d,0)},m=>{var r=X();m=S(m.message);Nc(b,3,d,m);c&&Lc(c,4,m);Y(r)})},aa:(a,b,c)=>{var d=U(a);0===c&&mc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(k){return 0}var g=Qc(16,f.byteLength);y.fill(0,g,f.byteLength);zb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(g,g+f.byteLength));qc(g)});return g},$:a=>{var b=U(a),c=zb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete zb[a];
b.unmap()}},a:a=>{delete yb[a]},h:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(g){return!1}T(c,f);d&&(zb[c]=[]);return!0},X:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=Ab(d+8)}T(c,U(a).createShaderModule(b))},_:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},V:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return nc[a]},W:function(a,b,
c,d){b=F(b);if(c){var f={featureLevel:Xb[A[c+4>>2]],powerPreference:bc[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Fc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(g=>{if(g)T(d,g),Mc(b,1,d,0);else{g=X();var k=S("WebGPU not available on this browser (requestAdapter returned null)");Mc(b,3,d,k);Y(g)}},g=>{var k=X();g=S(g.message);Mc(b,4,d,g);Y(k)}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Mc(b,3,d,a),Y(f))},S:(a,
b,c,d)=>{for(var f=0,g=0;g<c;g++){var k=A[b>>2],l=A[b+4>>2];b+=8;for(var n=0;n<l;n++){var u=a,v=y[k+n],m=oc[u];0===v||10===v?((1===u?ma:h)(M(m)),m.length=0):m.push(v)}f+=l}A[d>>2]=f;return 0},M:Ja,Ma:function(){e.$b=a=>{0!=sc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.$b)},Da:function(){e.ec=a=>{const b=a.clipboardData.getData("text");pc(()=>{const c=S(b);rc(c)})};window.addEventListener("paste",e.ec)},pa:function(){e.zc=[];e.ac=b=>{b.stopPropagation();b.preventDefault()};
e.bc=b=>{b.stopPropagation();b.preventDefault()};e.cc=b=>{b.stopPropagation();b.preventDefault()};e.dc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Ac=c;tc(c.length);for(let f=0;f<c.length;f++)pc(()=>{const g=S(c[f].name);uc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);vc(b.clientX,b.clientY,d)};const a=e.wb;a.addEventListener("dragenter",e.ac,!1);a.addEventListener("dragleave",e.bc,!1);a.addEventListener("dragover",e.cc,!1);a.addEventListener("drop",
e.dc,!1)},Ka:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},La:function(a){e.Jb&&(URL.revokeObjectURL(e.Jb[a].kc),e.Jb[a]=null)},Z:function(a,b){0!==b&&(document.title=b?M(y,b):"");a=a?M(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?gb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.wb=N(a);e.wb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.wb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",
a)},Ha:function(){window.removeEventListener("beforeunload",e.$b)},Ca:function(){window.removeEventListener("paste",e.ec)},ga:function(){const a=e.wb;a.removeEventListener("dragenter",e.ac);a.removeEventListener("dragleave",e.bc);a.removeEventListener("dragover",e.cc);a.removeEventListener("drop",e.dc)},g:function(){e.wb&&e.wb.requestPointerLock&&e.wb.requestPointerLock()},L:function(a,b,c){if(e.wb){if(0===b)a="none";else if(0!=c)a=e.Jb[a].mc;else switch(a){case 0:a="auto";break;case 1:a="default";
break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.wb.style.cursor=a}},Ja:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(y.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ya:function(a){a=a?M(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},
K:function(a,b){b=b?M(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Na:function(){return navigator.userAgent.includes("Macintosh")?1:0},e:(a,b)=>U(a).features.has(Yb[b]),ra:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:Db(A[b+12>>2])});a=U(a);b=Cc(0);T(b,a.beginComputePass(c));return b},qa:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],k=
[],l=0;l<f;++l){var n=k,u=n.push;var v=g+56*l;var m=A[v+4>>2];if(0!==m){var r=z[v+8>>2];-1==r&&(r=void 0);v={view:U(m),depthSlice:r,resolveTarget:U(A[v+12>>2]),clearValue:Bb(v+24),loadOp:$b[A[v+16>>2]],storeOp:fc[A[v+20>>2]]}}else v=void 0;u.call(n,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:$b[A[f+8>>2]],depthStoreOp:fc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:$b[A[f+24>>2]],stencilStoreOp:fc[A[f+28>>2]],stencilReadOnly:!!A[f+
36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:Db(A[b+28>>2]),maxDrawCount:d};a=U(a);d=Fc(0);T(d,a.beginRenderPass(b));return d},ca:a=>{a=U(a);var b=Ac(0);T(b,a.finish());return b},da:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},na:(a,b)=>{U(a).setPipeline(U(b))},k:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var g=[],k=0;k<f;++k){var l=g,n=l.push;var u=
b+40*k;var v=A[u+8>>2],m=A[u+32>>2],r=A[u+36>>2],w=A[u+4>>2];v?(m=u+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),u={binding:w,resource:{buffer:U(v),offset:4294967296*A[u+4+16>>2]+A[u+16>>2],size:m}}):u=m?{binding:w,resource:U(m)}:{binding:w,resource:U(r)};n.call(l,u)}c={label:c,layout:d,entries:g};a=U(a);d=yc(0);T(d,a.createBindGroup(c));return d},l:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],g=0;g<d;++g){var k=f,l=k.push,n=b+88*g,u=A[n+4>>2],v=A[n+8>>2];var m=n+24;var r=A[m+
4>>2];m=r?{type:Vb[r],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;r=(r=A[n+48+4>>2])?{type:dc[r]}:void 0;var w=n+56;var x=A[w+4>>2];w=x?{sampleType:ic[x],viewDimension:jc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;n+=72;n=(x=A[n+4>>2])?{access:ec[x],format:W[A[n+8>>2]],viewDimension:jc[A[n+12>>2]]}:void 0;l.call(k,{binding:u,visibility:v,buffer:m,sampler:r,texture:w,storageTexture:n})}c={label:c,entries:f};a=U(a);d=zc(0);T(d,a.createBindGroupLayout(c));
return d},n:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=Bc(0);T(b,a.createCommandEncoder(c));return b},ta:(a,b)=>{var c=V(b+4);var d=Fb(A[b+12>>2]);b=(b+=16)?{module:U(A[b+4>>2]),constants:Eb(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=Dc(0);T(d,a.createComputePipeline(c));return d},ua:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],g=0;g<c;++g)f.push(U(A[d+4*g>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=Ec(0);T(c,a.createPipelineLayout(b));return c},
sa:(a,b)=>{b=Sb(b);a=U(a);var c=Gc(0);T(c,a.createRenderPipeline(b));return c},va:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Ub[A[b+12>>2]],addressModeV:Ub[A[b+16>>2]],addressModeW:Ub[A[b+20>>2]],magFilter:Zb[A[b+24>>2]],minFilter:Zb[A[b+28>>2]],mipmapFilter:ac[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Kb[A[b+44>>2]],maxAnisotropy:qa[b+48>>1]});a=U(a);b=Hc(0);T(b,a.createSampler(c));return b},m:(a,b)=>{var c={label:V(b+4),size:Cb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+
48>>2],dimension:hc[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=Jc(0);T(d,a.createTexture(c));return d},xa:(a,b)=>{Tb(U(a).limits,b);return 1},d:(a,b)=>U(a).features.has(Yb[b]),Fa:(a,b)=>{a=N(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Bc=V(b+4);b=Ic(0);T(b,a);return b},ba:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},i:function(a,b,c,d,f){c=F(c);U(a).writeBuffer(U(b),
c,y.subarray(d,d+f),0,f)},wa:(a,b,c,d,f,g)=>{var k=A[f+8>>2],l=A[f+12>>2],n=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[n>>2],y:A[n+4>>2],z:A[n+8>>2]},aspect:gc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===k?void 0:k,rowsPerImage:4294967295===l?void 0:l},Cb(g))},fa:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},ha:(a,b,c,d,f,g)=>{U(a).drawIndexed(b,c,d>>>0,f,g>>>0)},ea:a=>{U(a).end()},b:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,
c):a.setBindGroup(b,c,A,f>>2,d)},la:(a,b)=>{U(a).setBlendConstant(Bb(b))},ja:function(a,b,c,d,f){d=F(d);f=F(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Pb[c],d,f)},ma:(a,b)=>{U(a).setPipeline(U(b))},j:(a,b,c,d,f)=>{U(a).setScissorRect(b,c,d,f)},ka:(a,b)=>{U(a).setStencilReference(b>>>0)},ia:function(a,b,c,d,f){d=F(d);f=F(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},oa:(a,b,c,d,f,g,k)=>{U(a).setViewport(b,c,d,f,g,k)},Ea:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+
28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Wb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),g=>W[g])}b=A[b>>2];0!==b&&(c.colorSpace=cc[A[b+8>>2]],c.Dc={mode:kc[A[b+12>>2]]});a.configure(c)},za:(a,b)=>{a=U(a);try{var c=Jc(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>
2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:jc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:gc[A[b+36>>2]]}}a=U(a);b=Kc(0);T(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Oa;sa();jb=Z.Db;c=Z;R=c.Qa;qc=c.Ra;e.__sapp_emsc_onpaste=rc=c.Sa;e.__sapp_html5_get_ask_leave_site=sc=c.Ta;e.__sapp_emsc_begin_drop=tc=c.Ua;e.__sapp_emsc_drop=uc=c.Va;e.__sapp_emsc_end_drop=vc=c.Wa;e.__sapp_emsc_invoke_fetch_cb=c.Xa;e.__sapp_emsc_set_fullscreen_flag=c.Ya;e._main=wc=c.Za;e.__saudio_emsc_pull=c._a;e.__sfetch_emsc_head_response=c.$a;e.__sfetch_emsc_get_response=c.ab;e.__sfetch_emsc_failed_http_status=c.bb;e.__sfetch_emsc_failed_buffer_too_small=
c.cb;e.__sfetch_emsc_failed_other=c.db;yc=c.eb;zc=c.fb;Ac=c.gb;Bc=c.hb;Cc=c.ib;Dc=c.jb;Ec=c.kb;Fc=c.ob;Gc=c.pb;Hc=c.qb;Ic=c.rb;Jc=c.sb;Kc=c.tb;Lc=c.zb;Mc=c.Ab;Nc=c.Bb;Oc=c.Cb;Pc=c.Eb;Qc=c.Fb;Y=c.Gb;xb=c.Hb;X=c.Ib;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Rc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});va??=e.locateFile?e.locateFile("nuklear-sapp.wasm",ia):ia+"nuklear-sapp.wasm";return a((await ya(b)).instance)})();
function Sc(a=[]){var b=wc;a.unshift(ea);var c=a.length,d=xb(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=S(k);f+=4});A[f>>2]=0;try{var g=b(c,d);Ka(g)}catch(k){Ia(k)}}
function Tc(a=da){function b(){e.calledRun=!0;if(!q){Z.Pa();e.onRuntimeInitialized?.();e.noInitialRun||Sc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Tc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Tc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Tc();
