var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),h=console.error.bind(console),n,r=!1,na,la=a=>a.startsWith("file://"),oa,t,y,pa,qa,z,A,B,C,ra;
function sa(){var a=oa.buffer;t=new Int8Array(a);pa=new Int16Array(a);y=new Uint8Array(a);qa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var D=0,E=null;function ta(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=va;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},Ea=!0,Fa=0,Ga=[0,31,60,91,121,152,182,213,244,274,305,335],Ha=[0,31,59,90,120,151,181,212,243,273,304,334],F=a=>-9007199254740992>a||9007199254740992<a?NaN:Number(a),G={},Ia=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ja=a=>{na=a;Ea||0<Fa||(e.onExit?.(a),r=!0);fa(a,new za(a))},Ka=a=>{na=a;Ja(a)},La=()=>{if(!(Ea||0<Fa))try{var a=na;na=a;Ja(a)}catch(b){Ia(b)}},Ma=a=>{if(!r)try{a(),La()}catch(b){Ia(b)}},H=
(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0}},Ua=(a,b)=>{Na=a;Oa=b;if(J)if(Pa||=!0,0==a)K=function(){setTimeout(L,Math.max(0,Qa+b-performance.now())|0)};else if(1==a)K=function(){Sa(L)};
else if(2==a){if("undefined"==typeof Ta)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ta=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ta=setImmediate;K=function(){Ta(L)}}},cb=(a,b,c,d,f)=>{function g(){return k<Va?(La(),!1):!0}J=a;Wa=d;var k=Va;Pa=
!1;L=function(){if(!r)if(0<Xa.length){var m=Xa.shift();m.kc(m.bc);if(Ya){var p=Ya,u=0==p%1?p-1:Math.floor(p);Ya=m.dc?u:(8*p+(u+.5))/9}e.setStatus&&(m=e.statusMessage||"Please wait...",p=Ya??0,u=Za.ic??0,p?p<u?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(m):e.setStatus(""));g()&&setTimeout(L,0)}else if(g())if($a=$a+1|0,1==Na&&1<Oa&&0!=$a%Oa)K();else{0==Na&&(Qa=performance.now());a:if(!r){for(m of ab)if(!1===m())break a;Ma(a);for(p of bb)p()}g()&&K()}};f||(0<b?Ua(0,1E3/b):
Ua(1,1),K());if(c)throw"unwind";},Pa=!1,K=null,Va=0,J=null,Wa=0,Na=0,Oa=0,$a=0,Xa=[],ab=[],bb=[];function db(){K=null;Va++}var eb=0;function Sa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===eb)eb=b+1E3/60;else for(;b+2>=eb;)eb+=1E3/60;setTimeout(a,Math.max(eb-b,0))}}
var Za={},Qa,L,Ta,Ya,fb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,M=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&fb)return fb.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},
gb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?M(y,a):"":a;return gb[a]||("undefined"!=typeof document?document.querySelector(a):null)},hb=a=>0>gb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ib=[],jb,O=a=>{var b=ib[a];b||(ib[a]=b=jb.get(a));return b};function kb(a){var b=P.jb[a];b.target.removeEventListener(b.ib,b.Rb,b.rb);P.jb.splice(a,1)}
function lb(){if(navigator.userActivation?navigator.userActivation.isActive:P.Ib&&P.ac.Gb){var a=P.tb;P.tb=[];for(var b of a)b.Mb(...b.Qb)}}function Q(a){if(!a.target)return-4;if(a.sb)a.Rb=function(c){++P.Ib;P.ac=a;lb();a.ub(c);lb();--P.Ib},a.target.addEventListener(a.ib,a.Rb,a.rb),P.jb.push(a);else for(var b=0;b<P.jb.length;++b)P.jb[b].target==a.target&&P.jb[b].ib==a.ib&&kb(b--);return 0}function mb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={cc:0,lc:0,Jb:0,vb:0,Pb:0,Ob:0,Hb:0,hc:0,oc:0,fc:0,jc:0,Kb:0,xc:0,Nb:0,nc(a,b,c){t.set(t.subarray(b,b+c),a)},pc(){for(;P.jb.length;)kb(P.jb.length-1);P.tb=[]},Ib:0,tb:[],ec(a,b,c){function d(g,k){if(g.length!=k.length)return!1;for(var m in g)if(g[m]!=k[m])return!1;return!0}for(var f of P.tb)if(f.Mb==a&&d(f.Qb,c))return;P.tb.push({Mb:a,Ub:b,Qb:c});P.tb.sort((g,k)=>g.Ub<k.Ub)},rc(a){P.tb=P.tb.filter(b=>b.Mb!=a)},jb:[],qc:(a,b)=>{for(var c=0;c<P.jb.length;++c)P.jb[c].target!=a||b&&b!=P.jb[c].ib||
kb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},nb=(a,b,c,d,f,g)=>{P.Hb||(P.Hb=R(256));a={target:N(a),ib:g,sb:d,ub:(k=event)=>{var m=k.target.id?k.target.id:"",p=P.Hb;H(mb(k.target),p+0,128);H(m,p+128,128);O(d)(f,p,b)&&k.preventDefault()},rb:c};return Q(a)},ob=(a,b,c,d,f,g)=>{P.Jb||(P.Jb=R(160));a={target:N(a),ib:g,sb:d,ub:k=>{var m=P.Jb;C[m>>3]=k.timeStamp;var p=m>>2;z[p+2]=k.location;t[m+12]=k.ctrlKey;t[m+13]=k.shiftKey;t[m+14]=k.altKey;t[m+15]=
k.metaKey;t[m+16]=k.repeat;z[p+5]=k.charCode;z[p+6]=k.keyCode;z[p+7]=k.which;H(k.key||"",m+32,32);H(k.code||"",m+64,32);H(k.char||"",m+96,32);H(k.locale||"",m+128,32);O(d)(f,m,b)&&k.preventDefault()},rb:c};return Q(a)},pb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=hb(c);z[d+10]=b.clientX-
(a.left|0);z[d+11]=b.clientY-(a.top|0)},qb=(a,b,c,d,f,g)=>{P.vb||(P.vb=R(64));a=N(a);return Q({target:a,Gb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,ib:g,sb:d,ub:(k=event)=>{pb(P.vb,k,a);O(d)(f,P.vb,b)&&k.preventDefault()},rb:c})},rb=(a,b,c,d)=>{P.Kb||(P.Kb=R(257));return Q({target:a,ib:"pointerlockchange",sb:d,ub:(f=event)=>{var g=P.Kb,k=document.pointerLockElement;t[g]=!!k;var m=k?.id||"";H(mb(k),g+1,128);H(m,g+129,128);O(d)(20,g,b)&&f.preventDefault()},rb:c})},sb=(a,b,c,d)=>Q({target:a,
ib:"pointerlockerror",sb:d,ub:(f=event)=>{O(d)(38,0,b)&&f.preventDefault()},rb:c}),tb=(a,b,c,d)=>{P.Ob||(P.Ob=R(36));a=N(a);return Q({target:a,ib:"resize",sb:d,ub:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=P.Ob;z[k>>2]=0;z[k+4>>2]=g.clientWidth;z[k+8>>2]=g.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;O(d)(10,k,b)&&f.preventDefault()}}},rb:c})},ub=(a,b,c,d,f,g)=>{P.Nb||(P.Nb=
R(1552));a=N(a);return Q({target:a,Gb:"touchstart"==g||"touchend"==g,ib:g,sb:d,ub:k=>{var m={},p=k.touches;for(var u of p)u.Sb=u.Tb=0,m[u.identifier]=u;for(var v of k.changedTouches)v.Sb=1,m[v.identifier]=v;for(var l of k.targetTouches)m[l.identifier].Tb=1;p=P.Nb;C[p>>3]=k.timeStamp;t[p+12]=k.ctrlKey;t[p+13]=k.shiftKey;t[p+14]=k.altKey;t[p+15]=k.metaKey;u=p+16;v=hb(a);l=0;for(let q of Object.values(m))if(m=u>>2,z[m]=q.identifier,z[m+1]=q.screenX,z[m+2]=q.screenY,z[m+3]=q.clientX,z[m+4]=q.clientY,
z[m+5]=q.pageX,z[m+6]=q.pageY,t[u+28]=q.Sb,t[u+29]=q.Tb,z[m+8]=q.clientX-(v.left|0),z[m+9]=q.clientY-(v.top|0),u+=48,31<++l)break;z[p+8>>2]=l;O(d)(f,p,b)&&k.preventDefault()},rb:c})},vb=(a,b,c,d)=>{P.Pb||(P.Pb=R(96));return Q({target:a,Gb:!0,ib:"wheel",sb:d,ub:(f=event)=>{var g=P.Pb;pb(g,f,a);C[g+64>>3]=f.deltaX;C[g+72>>3]=f.deltaY;C[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;O(d)(9,g,b)&&f.preventDefault()},rb:c})},S=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:
55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=wb(b);H(a,c,b);return c},xb=[],T=(a,b)=>{xb[a>>>=0]=b},yb=[],U=a=>{if(a)return xb[a>>>0]},zb=a=>{var b=A[a>>2];return b?M(y,b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?M(y,b,a):"";if(0===a)return""},Ab=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),Bb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Cb=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},
Db=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,g=zb(f+4);c[g]=C[f+16>>3]}return c}},Eb=a=>a?U(a):"auto",Rb=a=>{function b(d){if(d)return{operation:Fb[A[d>>2]],srcFactor:Ib[A[d+4>>2]],dstFactor:Ib[A[d+8>>2]]}}function c(d){return{compare:Jb[A[d>>2]],failOp:Kb[A[d+4>>2]],depthFailOp:Kb[A[d+8>>2]],passOp:Kb[A[d+12>>2]]}}return{label:V(a+4),layout:Eb(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),g=Db(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var m=A[d+28>>2];if(k){for(var p=[],u=0;u<
k;++u){var v=p,l=v.push;var q=m+24*u;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var I=null;else{I=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Lb[w];q=A[q+20>>2];for(var Gb=[],Ra=0;Ra<x;++Ra){var Hb=Gb,wc=Hb.push,ua=q+24*Ra;wc.call(Hb,{format:Mb[A[ua+4>>2]],offset:4294967296*A[ua+4+8>>2]+A[ua+8>>2],shaderLocation:A[ua+16>>2]})}I={arrayStride:I,stepMode:w,attributes:Gb}}}else I=void 0;l.call(v,I)}k=p}else k=void 0;return{module:f,constants:g,buffers:k,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Nb[A[d+
4>>2]],stripIndexFormat:Ob[A[d+8>>2]],frontFace:Pb[A[d+12>>2]],cullMode:Qb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Jb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+
12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),g=Db(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],m=A[d+28>>2],p=[],u=0;u<k;++u){var v=p,l=v.push,q=m+24*u,w=A[q+4>>2];if(0===w)q=void 0;else{w=W[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}l.call(v,q)}return{module:f,constants:g,targets:p,entryPoint:V(d+8)}}}(A[a+92>>2])}},Sb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",
12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);
ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",
140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.mc&&c("maxImmediateSize",148)},Tb=[,"clamp-to-edge","repeat","mirror-repeat"],Ib=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Fb=[,"add","subtract","reverse-subtract","min","max"],Ub=["binding-not-used",,"uniform","storage","read-only-storage"],Jb=
[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Vb=[,"opaque","premultiplied","unpremultiplied","inherit"],Qb=[,"none","front","back"],Wb=[,"compatibility","core"],Xb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",
12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Yb=[,"nearest","linear"],Pb=[,"ccw","cw"],Ob=[,"uint16","uint32"],Zb=[,"load","clear"],$b=[,"nearest","linear"],ac=[,"low-power",
"high-performance"],bc=[,"srgb","display-p3"],Nb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],cc=["binding-not-used",,"filtering","non-filtering","comparison"],Kb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],dc=["binding-not-used",,"write-only","read-only","read-write"],ec=[,"store","discard"],fc=[,"all","stencil-only","depth-only"],gc=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm",
"r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus",
"depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm",
"astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb",
"astc-12x12-unorm","astc-12x12-unorm-srgb"],hc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],ic=[,"1d","2d","2d-array","cube","cube-array","3d"],jc=[,"standard","extended"],Mb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2",
"float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Lb=[,"vertex","instance"],kc={undefined:1,unknown:1,destroyed:2},lc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";lc.Lb||(lc.Lb={});lc.Lb[a]||(lc.Lb[a]=1,ca&&(a="warning: "+a),h(a))},mc={rgba8unorm:22,bgra8unorm:27},nc=[null,[],[]],oc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Sa;e.pauseMainLoop=db;
e.resumeMainLoop=function(){Va++;var a=Na,b=Oa,c=J;J=null;cb(c,0,!1,Wa,!0);Ua(a,b);K()};e.preMainLoop&&ab.push(e.preMainLoop);e.postMainLoop&&bb.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(h=e.printErr);e.wasmBinary&&(n=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
var R,pc,qc,rc,sc,tc,uc,vc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Y,wb,X,Qc={S:()=>ta(""),L:()=>{Ea=!1;Fa=0},O:function(a,b){a=F(a);a=new Date(1E3*a);z[b>>2]=a.getSeconds();z[b+4>>2]=a.getMinutes();z[b+8>>2]=a.getHours();z[b+12>>2]=a.getDate();z[b+16>>2]=a.getMonth();z[b+20>>2]=a.getFullYear()-1900;z[b+24>>2]=a.getDay();var c=a.getFullYear();z[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ha:Ga)[a.getMonth()]+a.getDate()-1|0;z[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},M:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];Ma(()=>Oc(a,performance.now()))},b);G[a]={id:c,vc:b};return 0},P:(a,b,c,d)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();A[a>>2]=60*Math.max(g,f);z[b>>2]=Number(g!=f);b=k=>{var m=Math.abs(k);
return`UTC${0<=k?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(g);b=b(f);f<g?(H(a,c,17),H(b,d,17)):(H(a,d,17),H(b,c,17))},ya:()=>{db();J=null},R:()=>Date.now(),G:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,I:(a,b,c)=>{a=N(a);if(!a)return-4;a=hb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},za:()=>performance.now(),Fa:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},N:a=>{var b=y.length;a>>>=0;if(2147483648<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},o:(a,b,c,d)=>nb(a,b,c,d,12,"blur"),F:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},p:(a,b,c,d)=>nb(a,b,c,d,13,"focus"),y:(a,b,c,d)=>ob(a,b,c,d,2,"keydown"),w:(a,b,c,d)=>ob(a,b,c,d,1,"keypress"),x:(a,b,c,d)=>ob(a,b,c,d,3,"keyup"),
Ga:(a,b,c)=>{a=O(a);cb(a,b,c)},E:(a,b,c,d)=>qb(a,b,c,d,5,"mousedown"),B:(a,b,c,d)=>qb(a,b,c,d,33,"mouseenter"),A:(a,b,c,d)=>qb(a,b,c,d,34,"mouseleave"),C:(a,b,c,d)=>qb(a,b,c,d,8,"mousemove"),D:(a,b,c,d)=>qb(a,b,c,d,6,"mouseup"),r:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?rb(a,b,c,d):-4:-1,q:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?sb(a,b,c,d):-4:-1,H:(a,b,c,d)=>tb(a,b,c,d),s:(a,b,c,d)=>ub(a,b,c,d,25,"touchcancel"),t:(a,b,c,d)=>ub(a,b,c,d,23,"touchend"),u:(a,b,c,d)=>ub(a,b,
c,d,24,"touchmove"),v:(a,b,c,d)=>ub(a,b,c,d,22,"touchstart"),z:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?vb(a,b,c,d):-1:-4,X:function(a,b,c,d,f,g){b=F(b);c=F(c);a=U(a);var k={};if(g){var m=A[g+12>>2];if(m){var p=A[g+16>>2];k.requiredFeatures=Array.from(A.subarray(p>>2,p+4*m>>2),l=>Xb[l])}var u=A[g+20>>2];if(u){var v={};function l(w,x,I=!1){x=A[u+x>>2];4294967295==x||I&&0==x||(v[w]=x)}function q(w,x){x=u+x;var I=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=I)v[w]=4294967296*A[x+4>>2]+A[x>>
2]}l("maxTextureDimension1D",4);l("maxTextureDimension2D",8);l("maxTextureDimension3D",12);l("maxTextureArrayLayers",16);l("maxBindGroups",20);l("maxBindGroupsPlusVertexBuffers",24);l("maxDynamicUniformBuffersPerPipelineLayout",32);l("maxDynamicStorageBuffersPerPipelineLayout",36);l("maxSampledTexturesPerShaderStage",40);l("maxSamplersPerShaderStage",44);l("maxStorageBuffersPerShaderStage",48);l("maxStorageTexturesPerShaderStage",52);l("maxUniformBuffersPerShaderStage",56);l("minUniformBufferOffsetAlignment",
80);l("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);l("maxVertexBuffers",88);q("maxBufferSize",96);l("maxVertexAttributes",104);l("maxVertexBufferArrayStride",108);l("maxInterStageShaderVariables",112);l("maxColorAttachments",116);l("maxColorAttachmentBytesPerSample",120);l("maxComputeWorkgroupStorageSize",124);l("maxComputeInvocationsPerWorkgroup",128);l("maxComputeWorkgroupSizeX",132);l("maxComputeWorkgroupSizeY",136);l("maxComputeWorkgroupSizeZ",
140);l("maxComputeWorkgroupsPerDimension",144);l("maxImmediateSize",148,!0);k.requiredLimits=v}if(m=A[g+24>>2])m={label:V(m+4)},k.defaultQueue=m;k.label=V(g+4)}a.requestDevice(k).then(l=>{T(f,l.queue);T(d,l);c&&l.lost.then(q=>{l.onuncapturederror=()=>{};var w=X(),x=S(q.message);Kc(c,kc[q.reason],x);Y(w)});l.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=X();q=S(q.error.message);Nc(d,
w,q);Y(x)};Mc(b,1,d,0)},l=>{var q=X();l=S(l.message);Mc(b,3,d,l);c&&Kc(c,4,l);Y(q)})},_:(a,b,c)=>{var d=U(a);0===c&&lc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(k){return 0}var g=Pc(16,f.byteLength);y.fill(0,g,f.byteLength);yb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(g,g+f.byteLength));pc(g)});return g},Z:a=>{var b=U(a),c=yb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete yb[a];b.unmap()}},a:a=>{delete xb[a]},h:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],
size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(g){return!1}T(c,f);d&&(yb[c]=[]);return!0},V:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=zb(d+8)}T(c,U(a).createShaderModule(b))},Y:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},T:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return mc[a]},U:function(a,b,c,d){b=F(b);if(c){var f={featureLevel:Wb[A[c+4>>2]],powerPreference:ac[A[c+8>>2]],forceFallbackAdapter:!!A[c+
12>>2]};a=A[c>>2];0!==a&&(f.yc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(g=>{if(g)T(d,g),Lc(b,1,d,0);else{g=X();var k=S("WebGPU not available on this browser (requestAdapter returned null)");Lc(b,3,d,k);Y(g)}},g=>{var k=X();g=S(g.message);Lc(b,4,d,g);Y(k)}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Lc(b,3,d,a),Y(f))},Q:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var k=A[b>>2],m=A[b+4>>2];b+=8;for(var p=0;p<m;p++){var u=a,v=y[k+p],l=nc[u];
0===v||10===v?((1===u?ma:h)(M(l)),l.length=0):l.push(v)}f+=m}A[d>>2]=f;return 0},K:Ja,Ka:function(){e.Vb=a=>{0!=rc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Vb)},Ba:function(){e.$b=a=>{const b=a.clipboardData.getData("text");oc(()=>{const c=S(b);qc(c)})};window.addEventListener("paste",e.$b)},ma:function(){e.sc=[];e.Wb=b=>{b.stopPropagation();b.preventDefault()};e.Xb=b=>{b.stopPropagation();b.preventDefault()};e.Yb=b=>{b.stopPropagation();b.preventDefault()};
e.Zb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.tc=c;sc(c.length);for(let f=0;f<c.length;f++)oc(()=>{const g=S(c[f].name);tc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);uc(b.clientX,b.clientY,d)};const a=e.kb;a.addEventListener("dragenter",e.Wb,!1);a.addEventListener("dragleave",e.Xb,!1);a.addEventListener("dragover",e.Yb,!1);a.addEventListener("drop",e.Zb,!1)},Ia:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},W:function(a,b){0!==b&&(document.title=b?M(y,b):"");a=a?M(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?gb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.kb=N(a);e.kb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.kb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ea:function(){window.removeEventListener("beforeunload",e.Vb)},Aa:function(){window.removeEventListener("paste",
e.$b)},ca:function(){const a=e.kb;a.removeEventListener("dragenter",e.Wb);a.removeEventListener("dragleave",e.Xb);a.removeEventListener("dragover",e.Yb);a.removeEventListener("drop",e.Zb)},g:function(){e.kb&&e.kb.requestPointerLock&&e.kb.requestPointerLock()},Ja:function(a,b){if(e.kb){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a=
"nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.kb.style.cursor=a}},Ha:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(y.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},va:function(a){a=a?M(y,a):"";const b=
document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},J:function(a,b){b=b?M(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},
La:function(){return navigator.userAgent.includes("Macintosh")?1:0},e:(a,b)=>U(a).features.has(Xb[b]),pa:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:Cb(A[b+12>>2])});a=U(a);b=Bc(0);T(b,a.beginComputePass(c));return b},oa:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],k=[],m=0;m<f;++m){var p=k,u=p.push;var v=g+56*m;var l=A[v+4>>2];if(0!==l){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:U(l),depthSlice:q,resolveTarget:U(A[v+12>>
2]),clearValue:Ab(v+24),loadOp:Zb[A[v+16>>2]],storeOp:ec[A[v+20>>2]]}}else v=void 0;u.call(p,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Zb[A[f+8>>2]],depthStoreOp:ec[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Zb[A[f+24>>2]],stencilStoreOp:ec[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:Cb(A[b+28>>2]),maxDrawCount:d};
a=U(a);d=Ec(0);T(d,a.beginRenderPass(b));return d},aa:a=>{a=U(a);var b=zc(0);T(b,a.finish());return b},ba:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},la:(a,b)=>{U(a).setPipeline(U(b))},k:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var g=[],k=0;k<f;++k){var m=g,p=m.push;var u=b+40*k;var v=A[u+8>>2],l=A[u+32>>2],q=A[u+36>>2],w=A[u+4>>2];v?(l=u+24,l=A[l>>2]+4294967296*z[l+4>>2],-1==l&&(l=void 0),u={binding:w,resource:{buffer:U(v),
offset:4294967296*A[u+4+16>>2]+A[u+16>>2],size:l}}):u=l?{binding:w,resource:U(l)}:{binding:w,resource:U(q)};p.call(m,u)}c={label:c,layout:d,entries:g};a=U(a);d=xc(0);T(d,a.createBindGroup(c));return d},l:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],g=0;g<d;++g){var k=f,m=k.push,p=b+88*g,u=A[p+4>>2],v=A[p+8>>2];var l=p+24;var q=A[l+4>>2];l=q?{type:Ub[q],hasDynamicOffset:!!A[l+8>>2],minBindingSize:4294967296*A[l+4+16>>2]+A[l+16>>2]}:void 0;q=(q=A[p+48+4>>2])?{type:cc[q]}:void 0;var w=
p+56;var x=A[w+4>>2];w=x?{sampleType:hc[x],viewDimension:ic[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;p+=72;p=(x=A[p+4>>2])?{access:dc[x],format:W[A[p+8>>2]],viewDimension:ic[A[p+12>>2]]}:void 0;m.call(k,{binding:u,visibility:v,buffer:l,sampler:q,texture:w,storageTexture:p})}c={label:c,entries:f};a=U(a);d=yc(0);T(d,a.createBindGroupLayout(c));return d},n:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=Ac(0);T(b,a.createCommandEncoder(c));return b},ra:(a,b)=>{var c=V(b+4);var d=Eb(A[b+12>>2]);b=(b+=
16)?{module:U(A[b+4>>2]),constants:Db(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=Cc(0);T(d,a.createComputePipeline(c));return d},sa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],g=0;g<c;++g)f.push(U(A[d+4*g>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=Dc(0);T(c,a.createPipelineLayout(b));return c},qa:(a,b)=>{b=Rb(b);a=U(a);var c=Fc(0);T(c,a.createRenderPipeline(b));return c},ta:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Tb[A[b+12>>2]],addressModeV:Tb[A[b+
16>>2]],addressModeW:Tb[A[b+20>>2]],magFilter:Yb[A[b+24>>2]],minFilter:Yb[A[b+28>>2]],mipmapFilter:$b[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Jb[A[b+44>>2]],maxAnisotropy:qa[b+48>>1]});a=U(a);b=Gc(0);T(b,a.createSampler(c));return b},m:(a,b)=>{var c={label:V(b+4),size:Bb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:gc[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));
a=U(a);d=Ic(0);T(d,a.createTexture(c));return d},wa:(a,b)=>{Sb(U(a).limits,b);return 1},d:(a,b)=>U(a).features.has(Xb[b]),Da:(a,b)=>{a=N(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.uc=V(b+4);b=Hc(0);T(b,a);return b},$:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},i:function(a,b,c,d,f){c=F(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},ua:(a,b,c,d,f,g)=>{var k=A[f+8>>2],m=A[f+12>>2],p=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[p>>
2],y:A[p+4>>2],z:A[p+8>>2]},aspect:fc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===k?void 0:k,rowsPerImage:4294967295===m?void 0:m},Bb(g))},ea:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},fa:(a,b,c,d,f,g)=>{U(a).drawIndexed(b,c,d>>>0,f,g>>>0)},da:a=>{U(a).end()},b:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ja:(a,b)=>{U(a).setBlendConstant(Ab(b))},ha:function(a,b,c,d,f){d=F(d);f=F(f);a=U(a);b=U(b);-1==f&&(f=void 0);
a.setIndexBuffer(b,Ob[c],d,f)},ka:(a,b)=>{U(a).setPipeline(U(b))},j:(a,b,c,d,f)=>{U(a).setScissorRect(b,c,d,f)},ia:(a,b)=>{U(a).setStencilReference(b>>>0)},ga:function(a,b,c,d,f){d=F(d);f=F(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},na:(a,b,c,d,f,g,k)=>{U(a).setViewport(b,c,d,f,g,k)},Ca:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Vb[A[b+
40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),g=>W[g])}b=A[b>>2];0!==b&&(c.colorSpace=bc[A[b+8>>2]],c.wc={mode:jc[A[b+12>>2]]});a.configure(c)},xa:(a,b)=>{a=U(a);try{var c=Ic(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:ic[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+
28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:fc[A[b+36>>2]]}}a=U(a);b=Jc(0);T(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Ma;sa();jb=Z.Ab;c=Z;R=c.Oa;pc=c.Pa;e.__sapp_emsc_onpaste=qc=c.Qa;e.__sapp_html5_get_ask_leave_site=rc=c.Ra;e.__sapp_emsc_begin_drop=sc=c.Sa;e.__sapp_emsc_drop=tc=c.Ta;e.__sapp_emsc_end_drop=uc=c.Ua;e.__sapp_emsc_invoke_fetch_cb=c.Va;e._main=vc=c.Wa;e.__saudio_emsc_pull=c.Xa;e.__sfetch_emsc_head_response=c.Ya;e.__sfetch_emsc_get_response=c.Za;e.__sfetch_emsc_failed_http_status=c._a;e.__sfetch_emsc_failed_buffer_too_small=c.$a;e.__sfetch_emsc_failed_other=
c.ab;xc=c.bb;yc=c.cb;zc=c.db;Ac=c.eb;Bc=c.fb;Cc=c.gb;Dc=c.hb;Ec=c.lb;Fc=c.mb;Gc=c.nb;Hc=c.ob;Ic=c.pb;Jc=c.qb;Kc=c.wb;Lc=c.xb;Mc=c.yb;Nc=c.zb;Oc=c.Bb;Pc=c.Cb;Y=c.Db;wb=c.Eb;X=c.Fb;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Qc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});va??=e.locateFile?e.locateFile("nuklear-sapp.wasm",ia):ia+"nuklear-sapp.wasm";return a((await ya(b)).instance)})();
function Rc(a=[]){var b=vc;a.unshift(ea);var c=a.length,d=wb(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=S(k);f+=4});A[f>>2]=0;try{var g=b(c,d);Ka(g)}catch(k){Ia(k)}}
function Sc(a=da){function b(){e.calledRun=!0;if(!r){Z.Na();e.onRuntimeInitialized?.();e.noInitialRun||Rc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Sc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Sc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Sc();
