var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),n,r=!1,na,la=a=>a.startsWith("file://"),oa,t,y,pa,qa,z,A,B,C,ra;
function sa(){var a=oa.buffer;t=new Int8Array(a);pa=new Int16Array(a);y=new Uint8Array(a);qa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var D=0,E=null;function ta(a){e.onAbort?.(a);a="Aborted("+a+")";k(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function wa(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=ua;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},Ea=!0,Fa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ga=0,Ha=[0,31,60,91,121,152,182,213,244,274,305,335],Ia=[0,31,59,90,120,151,181,212,243,273,304,334],G=a=>-9007199254740992>a||9007199254740992<a?NaN:Number(a),H={},Ja=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ka=a=>{na=a;Ea||0<Ga||(e.onExit?.(a),r=!0);fa(a,new za(a))},La=a=>{na=a;Ka(a)},Ma=()=>{if(!(Ea||0<Ga))try{var a=na;na=a;Ka(a)}catch(b){Ja(b)}},Na=a=>{if(!r)try{a(),Ma()}catch(b){Ja(b)}},J=(a,b,c)=>{var d=
y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;g++}}d[b]=0;return b-f},Va=(a,b)=>{Oa=a;Pa=b;if(K)if(Qa||=!0,0==a)L=function(){setTimeout(M,Math.max(0,Sa+b-performance.now())|0)};else if(1==
a)L=function(){Ta(M)};else if(2==a){if("undefined"==typeof Ua)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ua=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ua=setImmediate;L=function(){Ua(M)}}},db=(a,b,c,d,f)=>{function g(){return h<Wa?(Ma(),!1):
!0}K=a;Xa=d;var h=Wa;Qa=!1;M=function(){if(!r)if(0<Ya.length){var m=Ya.shift();m.xc(m.nc);if(Za){var p=Za,u=0==p%1?p-1:Math.floor(p);Za=m.qc?u:(8*p+(u+.5))/9}e.setStatus&&(m=e.statusMessage||"Please wait...",p=Za??0,u=$a.vc??0,p?p<u?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(m):e.setStatus(""));g()&&setTimeout(M,0)}else if(g())if(ab=ab+1|0,1==Oa&&1<Pa&&0!=ab%Pa)L();else{0==Oa&&(Sa=performance.now());a:if(!r){for(m of bb)if(!1===m())break a;Na(a);for(p of cb)p()}g()&&
L()}};f||(0<b?Va(0,1E3/b):Va(1,1),L());if(c)throw"unwind";},Qa=!1,L=null,Wa=0,K=null,Xa=0,Oa=0,Pa=0,ab=0,Ya=[],bb=[],cb=[];function eb(){L=null;Wa++}var fb=0;function Ta(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===fb)fb=b+1E3/60;else for(;b+2>=fb;)fb+=1E3/60;setTimeout(a,Math.max(fb-b,0))}}
var $a={},Sa,M,Ua,Za,gb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?F(y,a):"":a;return gb[a]||("undefined"!=typeof document?document.querySelector(a):null)},hb=a=>0>gb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ib=[],jb,O=a=>{var b=ib[a];b||(ib[a]=b=jb.get(a));return b};function kb(a){var b=P.tb[a];b.target.removeEventListener(b.sb,b.bc,b.Bb);P.tb.splice(a,1)}
function lb(){if(navigator.userActivation?navigator.userActivation.isActive:P.Tb&&P.mc.Rb){var a=P.Db;P.Db=[];for(var b of a)b.Xb(...b.ac)}}function Q(a){if(!a.target)return-4;if(a.Cb)a.bc=function(c){++P.Tb;P.mc=a;lb();a.Eb(c);lb();--P.Tb},a.target.addEventListener(a.sb,a.bc,a.Bb),P.tb.push(a);else for(var b=0;b<P.tb.length;++b)P.tb[b].target==a.target&&P.tb[b].sb==a.sb&&kb(b--);return 0}function mb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={oc:0,yc:0,Ub:0,Fb:0,$b:0,Zb:0,Sb:0,uc:0,Bc:0,tc:0,wc:0,Vb:0,Kc:0,Yb:0,Ac(a,b,c){t.set(t.subarray(b,b+c),a)},Cc(){for(;P.tb.length;)kb(P.tb.length-1);P.Db=[]},Tb:0,Db:[],sc(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var m in g)if(g[m]!=h[m])return!1;return!0}for(var f of P.Db)if(f.Xb==a&&d(f.ac,c))return;P.Db.push({Xb:a,ec:b,ac:c});P.Db.sort((g,h)=>g.ec<h.ec)},Ec(a){P.Db=P.Db.filter(b=>b.Xb!=a)},tb:[],Dc:(a,b)=>{for(var c=0;c<P.tb.length;++c)P.tb[c].target!=a||b&&b!=P.tb[c].sb||
kb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},nb=(a,b,c,d,f,g)=>{P.Sb||(P.Sb=R(256));a={target:N(a),sb:g,Cb:d,Eb:(h=event)=>{var m=h.target.id?h.target.id:"",p=P.Sb;J(mb(h.target),p+0,128);J(m,p+128,128);O(d)(f,p,b)&&h.preventDefault()},Bb:c};return Q(a)},ob=(a,b,c,d,f,g)=>{P.Ub||(P.Ub=R(160));a={target:N(a),sb:g,Cb:d,Eb:h=>{var m=P.Ub;C[m>>3]=h.timeStamp;var p=m>>2;z[p+2]=h.location;t[m+12]=h.ctrlKey;t[m+13]=h.shiftKey;t[m+14]=h.altKey;t[m+15]=
h.metaKey;t[m+16]=h.repeat;z[p+5]=h.charCode;z[p+6]=h.keyCode;z[p+7]=h.which;J(h.key||"",m+32,32);J(h.code||"",m+64,32);J(h.char||"",m+96,32);J(h.locale||"",m+128,32);O(d)(f,m,b)&&h.preventDefault()},Bb:c};return Q(a)},pb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=hb(c);z[d+10]=b.clientX-
(a.left|0);z[d+11]=b.clientY-(a.top|0)},qb=(a,b,c,d,f,g)=>{P.Fb||(P.Fb=R(64));a=N(a);return Q({target:a,Rb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,sb:g,Cb:d,Eb:(h=event)=>{pb(P.Fb,h,a);O(d)(f,P.Fb,b)&&h.preventDefault()},Bb:c})},rb=(a,b,c,d)=>{P.Vb||(P.Vb=R(257));return Q({target:a,sb:"pointerlockchange",Cb:d,Eb:(f=event)=>{var g=P.Vb,h=document.pointerLockElement;t[g]=!!h;var m=h?.id||"";J(mb(h),g+1,128);J(m,g+129,128);O(d)(20,g,b)&&f.preventDefault()},Bb:c})},sb=(a,b,c,d)=>Q({target:a,
sb:"pointerlockerror",Cb:d,Eb:(f=event)=>{O(d)(38,0,b)&&f.preventDefault()},Bb:c}),tb=(a,b,c,d)=>{P.Zb||(P.Zb=R(36));a=N(a);return Q({target:a,sb:"resize",Cb:d,Eb:(f=event)=>{if(f.target==a){var g=document.body;if(g){var h=P.Zb;z[h>>2]=0;z[h+4>>2]=g.clientWidth;z[h+8>>2]=g.clientHeight;z[h+12>>2]=innerWidth;z[h+16>>2]=innerHeight;z[h+20>>2]=outerWidth;z[h+24>>2]=outerHeight;z[h+28>>2]=pageXOffset|0;z[h+32>>2]=pageYOffset|0;O(d)(10,h,b)&&f.preventDefault()}}},Bb:c})},ub=(a,b,c,d,f,g)=>{P.Yb||(P.Yb=
R(1552));a=N(a);return Q({target:a,Rb:"touchstart"==g||"touchend"==g,sb:g,Cb:d,Eb:h=>{var m={},p=h.touches;for(var u of p)u.cc=u.dc=0,m[u.identifier]=u;for(var v of h.changedTouches)v.cc=1,m[v.identifier]=v;for(var l of h.targetTouches)m[l.identifier].dc=1;p=P.Yb;C[p>>3]=h.timeStamp;t[p+12]=h.ctrlKey;t[p+13]=h.shiftKey;t[p+14]=h.altKey;t[p+15]=h.metaKey;u=p+16;v=hb(a);l=0;for(let q of Object.values(m))if(m=u>>2,z[m]=q.identifier,z[m+1]=q.screenX,z[m+2]=q.screenY,z[m+3]=q.clientX,z[m+4]=q.clientY,
z[m+5]=q.pageX,z[m+6]=q.pageY,t[u+28]=q.cc,t[u+29]=q.dc,z[m+8]=q.clientX-(v.left|0),z[m+9]=q.clientY-(v.top|0),u+=48,31<++l)break;z[p+8>>2]=l;O(d)(f,p,b)&&h.preventDefault()},Bb:c})},vb=(a,b,c,d)=>{P.$b||(P.$b=R(96));return Q({target:a,Rb:!0,sb:"wheel",Cb:d,Eb:(f=event)=>{var g=P.$b;pb(g,f,a);C[g+64>>3]=f.deltaX;C[g+72>>3]=f.deltaY;C[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;O(d)(9,g,b)&&f.preventDefault()},Bb:c})},wb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=
2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},S=a=>{var b=wb(a)+1,c=xb(b);J(a,c,b);return c},yb=[],T=(a,b)=>{yb[a>>>=0]=b},zb=[],U=a=>{if(a)return yb[a>>>0]},Ab=a=>{var b=A[a>>2];return b?F(y,b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?F(y,b,a):"";if(0===a)return""},Bb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),Cb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Db=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+
12>>2]}},Eb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,g=Ab(f+4);c[g]=C[f+16>>3]}return c}},Fb=a=>a?U(a):"auto",Sb=a=>{function b(d){if(d)return{operation:Gb[A[d>>2]],srcFactor:Hb[A[d+4>>2]],dstFactor:Hb[A[d+8>>2]]}}function c(d){return{compare:Ib[A[d>>2]],failOp:Lb[A[d+4>>2]],depthFailOp:Lb[A[d+8>>2]],passOp:Lb[A[d+12>>2]]}}return{label:V(a+4),layout:Fb(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),g=Eb(A[d+16>>2],A[d+20>>2]);var h=A[d+24>>2];var m=A[d+28>>2];if(h){for(var p=
[],u=0;u<h;++u){var v=p,l=v.push;var q=m+24*u;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var I=null;else{I=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Mb[w];q=A[q+20>>2];for(var Jb=[],Ra=0;Ra<x;++Ra){var Kb=Jb,Ac=Kb.push,va=q+24*Ra;Ac.call(Kb,{format:Nb[A[va+4>>2]],offset:4294967296*A[va+4+8>>2]+A[va+8>>2],shaderLocation:A[va+16>>2]})}I={arrayStride:I,stepMode:w,attributes:Jb}}}else I=void 0;l.call(v,I)}h=p}else h=void 0;return{module:f,constants:g,buffers:h,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Ob[A[d+
4>>2]],stripIndexFormat:Pb[A[d+8>>2]],frontFace:Qb[A[d+12>>2]],cullMode:Rb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Ib[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+
12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),g=Eb(A[d+16>>2],A[d+20>>2]),h=A[d+24>>2],m=A[d+28>>2],p=[],u=0;u<h;++u){var v=p,l=v.push,q=m+24*u,w=A[q+4>>2];if(0===w)q=void 0;else{w=W[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}l.call(v,q)}return{module:f,constants:g,targets:p,entryPoint:V(d+8)}}}(A[a+92>>2])}},Tb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",
12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);
ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",
140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.zc&&c("maxImmediateSize",148)},Ub=[,"clamp-to-edge","repeat","mirror-repeat"],Hb=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Gb=[,"add","subtract","reverse-subtract","min","max"],Vb=["binding-not-used",,"uniform","storage","read-only-storage"],Ib=
[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Wb=[,"opaque","premultiplied","unpremultiplied","inherit"],Rb=[,"none","front","back"],Xb=[,"compatibility","core"],Yb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",
12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Zb=[,"nearest","linear"],Qb=[,"ccw","cw"],Pb=[,"uint16","uint32"],$b=[,"load","clear"],ac=[,"nearest","linear"],bc=[,"low-power",
"high-performance"],cc=[,"srgb","display-p3"],Ob=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],dc=["binding-not-used",,"filtering","non-filtering","comparison"],Lb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],ec=["binding-not-used",,"write-only","read-only","read-write"],fc=[,"store","discard"],gc=[,"all","stencil-only","depth-only"],hc=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm",
"r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus",
"depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm",
"astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb",
"astc-12x12-unorm","astc-12x12-unorm-srgb"],ic=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],jc=[,"1d","2d","2d-array","cube","cube-array","3d"],kc=[,"standard","extended"],Nb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2",
"float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Mb=[,"vertex","instance"],lc={undefined:1,unknown:1,destroyed:2},mc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";mc.Wb||(mc.Wb={});mc.Wb[a]||(mc.Wb[a]=1,ca&&(a="warning: "+a),k(a))},nc={rgba8unorm:22,bgra8unorm:27},oc={},qc=()=>{if(!pc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==
typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in oc)void 0===oc[b]?delete a[b]:a[b]=oc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);pc=c}return pc},pc,rc=[null,[],[]],sc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Ta;e.pauseMainLoop=eb;e.resumeMainLoop=function(){Wa++;var a=Oa,b=Pa,c=K;K=null;db(c,0,!1,Xa,!0);Va(a,b);L()};e.preMainLoop&&bb.push(e.preMainLoop);e.postMainLoop&&cb.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);
e.print&&(ma=e.print);e.printErr&&(k=e.printErr);e.wasmBinary&&(n=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
var R,tc,uc,vc,wc,xc,yc,zc,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Y,xb,X,Uc={q:function(){return 0},Y:function(){return 0},Z:function(){},ba:()=>ta(""),Ta:()=>{Ea=!1;Ga=0},T:function(a,b){a=G(a);a=new Date(1E3*a);z[b>>2]=a.getSeconds();z[b+4>>2]=a.getMinutes();z[b+8>>2]=a.getHours();z[b+12>>2]=a.getDate();z[b+16>>2]=a.getMonth();z[b+20>>2]=a.getFullYear()-1900;z[b+24>>2]=a.getDay();var c=a.getFullYear();z[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ia:Ha)[a.getMonth()]+a.getDate()-1|
0;z[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},R:(a,b)=>{H[a]&&(clearTimeout(H[a].id),delete H[a]);if(!b)return 0;var c=setTimeout(()=>{delete H[a];Na(()=>Sc(a,performance.now()))},b);H[a]={id:c,Ic:b};return 0},U:(a,b,c,d)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();
A[a>>2]=60*Math.max(g,f);z[b>>2]=Number(g!=f);b=h=>{var m=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(g);b=b(f);f<g?(J(a,c,17),J(b,d,17)):(J(a,d,17),J(b,c,17))},Ga:()=>{eb();K=null},aa:()=>Date.now(),N:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,P:(a,b,c)=>{a=N(a);if(!a)return-4;a=hb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},Ha:()=>performance.now(),Ma:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}
return requestAnimationFrame(c)},S:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},v:(a,b,c,d)=>nb(a,b,c,d,12,"blur"),M:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},w:(a,b,c,d)=>nb(a,b,c,d,13,"focus"),F:(a,b,c,d)=>ob(a,b,c,d,2,"keydown"),
D:(a,b,c,d)=>ob(a,b,c,d,1,"keypress"),E:(a,b,c,d)=>ob(a,b,c,d,3,"keyup"),Oa:(a,b,c)=>{a=O(a);db(a,b,c)},L:(a,b,c,d)=>qb(a,b,c,d,5,"mousedown"),I:(a,b,c,d)=>qb(a,b,c,d,33,"mouseenter"),H:(a,b,c,d)=>qb(a,b,c,d,34,"mouseleave"),J:(a,b,c,d)=>qb(a,b,c,d,8,"mousemove"),K:(a,b,c,d)=>qb(a,b,c,d,6,"mouseup"),y:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?rb(a,b,c,d):-4:-1,x:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?sb(a,b,c,d):-4:-1,O:(a,b,c,d)=>tb(a,b,c,d),z:(a,b,c,d)=>ub(a,b,c,d,25,
"touchcancel"),A:(a,b,c,d)=>ub(a,b,c,d,23,"touchend"),B:(a,b,c,d)=>ub(a,b,c,d,24,"touchmove"),C:(a,b,c,d)=>ub(a,b,c,d,22,"touchstart"),G:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?vb(a,b,c,d):-1:-4,fa:function(a,b,c,d,f,g){b=G(b);c=G(c);a=U(a);var h={};if(g){var m=A[g+12>>2];if(m){var p=A[g+16>>2];h.requiredFeatures=Array.from(A.subarray(p>>2,p+4*m>>2),l=>Yb[l])}var u=A[g+20>>2];if(u){var v={};function l(w,x,I=!1){x=A[u+x>>2];4294967295==x||I&&0==x||(v[w]=x)}function q(w,x){x=u+x;var I=A[x+
4>>2];if(4294967295!=A[x>>2]||4294967295!=I)v[w]=4294967296*A[x+4>>2]+A[x>>2]}l("maxTextureDimension1D",4);l("maxTextureDimension2D",8);l("maxTextureDimension3D",12);l("maxTextureArrayLayers",16);l("maxBindGroups",20);l("maxBindGroupsPlusVertexBuffers",24);l("maxDynamicUniformBuffersPerPipelineLayout",32);l("maxDynamicStorageBuffersPerPipelineLayout",36);l("maxSampledTexturesPerShaderStage",40);l("maxSamplersPerShaderStage",44);l("maxStorageBuffersPerShaderStage",48);l("maxStorageTexturesPerShaderStage",
52);l("maxUniformBuffersPerShaderStage",56);l("minUniformBufferOffsetAlignment",80);l("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);l("maxVertexBuffers",88);q("maxBufferSize",96);l("maxVertexAttributes",104);l("maxVertexBufferArrayStride",108);l("maxInterStageShaderVariables",112);l("maxColorAttachments",116);l("maxColorAttachmentBytesPerSample",120);l("maxComputeWorkgroupStorageSize",124);l("maxComputeInvocationsPerWorkgroup",128);l("maxComputeWorkgroupSizeX",
132);l("maxComputeWorkgroupSizeY",136);l("maxComputeWorkgroupSizeZ",140);l("maxComputeWorkgroupsPerDimension",144);l("maxImmediateSize",148,!0);h.requiredLimits=v}if(m=A[g+24>>2])m={label:V(m+4)},h.defaultQueue=m;h.label=V(g+4)}a.requestDevice(h).then(l=>{T(f,l.queue);T(d,l);c&&l.lost.then(q=>{l.onuncapturederror=()=>{};var w=X(),x=S(q.message);Oc(c,lc[q.reason],x);Y(w)});l.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof
GPUInternalError&&(w=4);var x=X();q=S(q.error.message);Rc(d,w,q);Y(x)};Qc(b,1,d,0)},l=>{var q=X();l=S(l.message);Qc(b,3,d,l);c&&Oc(c,4,l);Y(q)})},ja:(a,b,c)=>{var d=U(a);0===c&&mc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(h){return 0}var g=Tc(16,f.byteLength);y.fill(0,g,f.byteLength);zb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(g,g+f.byteLength));tc(g)});return g},ia:a=>{var b=U(a),c=zb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete zb[a];b.unmap()}},a:a=>{delete yb[a]},j:(a,
b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(g){return!1}T(c,f);d&&(zb[c]=[]);return!0},ea:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=Ab(d+8)}T(c,U(a).createShaderModule(b))},ha:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},ca:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return nc[a]},da:function(a,b,c,d){b=G(b);if(c){var f={featureLevel:Xb[A[c+
4>>2]],powerPreference:bc[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Lc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(g=>{if(g)T(d,g),Pc(b,1,d,0);else{g=X();var h=S("WebGPU not available on this browser (requestAdapter returned null)");Pc(b,3,d,h);Y(g)}},g=>{var h=X();g=S(g.message);Pc(b,4,d,g);Y(h)}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Pc(b,3,d,a),Y(f))},_:(a,b)=>{var c=0,d=0,f;for(f of qc()){var g=b+c;A[a+
d>>2]=g;c+=J(f,g,Infinity)+1;d+=4}return 0},$:(a,b)=>{var c=qc();A[a>>2]=c.length;a=0;for(var d of c)a+=wb(d)+1;A[b>>2]=a;return 0},p:()=>52,X:()=>52,V:function(){return 70},W:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var h=A[b>>2],m=A[b+4>>2];b+=8;for(var p=0;p<m;p++){var u=a,v=y[h+p],l=rc[u];0===v||10===v?((1===u?ma:k)(F(l)),l.length=0):l.push(v)}f+=m}A[d>>2]=f;return 0},Sa:Ka,Ua:function(){e.fc=a=>{0!=vc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.fc)},Ja:function(){e.lc=
a=>{const b=a.clipboardData.getData("text");sc(()=>{const c=S(b);uc(c)})};window.addEventListener("paste",e.lc)},va:function(){e.Fc=[];e.hc=b=>{b.stopPropagation();b.preventDefault()};e.ic=b=>{b.stopPropagation();b.preventDefault()};e.jc=b=>{b.stopPropagation();b.preventDefault()};e.kc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Gc=c;wc(c.length);for(let f=0;f<c.length;f++)sc(()=>{const g=S(c[f].name);xc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=
4);b.metaKey&&(d|=8);yc(b.clientX,b.clientY,d)};const a=e.ub;a.addEventListener("dragenter",e.hc,!1);a.addEventListener("dragleave",e.ic,!1);a.addEventListener("dragover",e.jc,!1);a.addEventListener("drop",e.kc,!1)},Qa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ra:function(a){e.Qb&&(URL.revokeObjectURL(e.Qb[a].pc),e.Qb[a]=null)},ga:function(a,b){0!==b&&(document.title=b?F(y,b):"");a=a?F(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?gb[a]=
e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.ub=N(a);e.ub||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.ub.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Na:function(){window.removeEventListener("beforeunload",e.fc)},Ia:function(){window.removeEventListener("paste",e.lc)},oa:function(){const a=e.ub;a.removeEventListener("dragenter",e.hc);a.removeEventListener("dragleave",e.ic);a.removeEventListener("dragover",
e.jc);a.removeEventListener("drop",e.kc)},i:function(){e.ub&&e.ub.requestPointerLock&&e.ub.requestPointerLock()},o:function(a,b,c){if(e.ub){if(0===b)a="none";else if(0!=c)a=e.Qb[a].rc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.ub.style.cursor=
a}},Pa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(y.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Da:function(a){a=a?F(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize",
"off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},r:function(){return navigator.userAgent.includes("Macintosh")?1:0},Q:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Va:function(){return navigator.userAgent.includes("Macintosh")?
1:0},g:(a,b)=>U(a).features.has(Yb[b]),xa:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:Db(A[b+12>>2])});a=U(a);b=Fc(0);T(b,a.beginComputePass(c));return b},wa:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],h=[],m=0;m<f;++m){var p=h,u=p.push;var v=g+56*m;var l=A[v+4>>2];if(0!==l){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:U(l),depthSlice:q,resolveTarget:U(A[v+12>>2]),clearValue:Bb(v+24),loadOp:$b[A[v+16>>2]],storeOp:fc[A[v+20>>
2]]}}else v=void 0;u.call(p,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:$b[A[f+8>>2]],depthStoreOp:fc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:$b[A[f+24>>2]],stencilStoreOp:fc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:h,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:Db(A[b+28>>2]),maxDrawCount:d};a=U(a);d=Ic(0);T(d,a.beginRenderPass(b));return d},la:a=>{a=U(a);
var b=Dc(0);T(b,a.finish());return b},ma:a=>{U(a).end()},d:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ua:(a,b)=>{U(a).setPipeline(U(b))},l:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var g=[],h=0;h<f;++h){var m=g,p=m.push;var u=b+40*h;var v=A[u+8>>2],l=A[u+32>>2],q=A[u+36>>2],w=A[u+4>>2];v?(l=u+24,l=A[l>>2]+4294967296*z[l+4>>2],-1==l&&(l=void 0),u={binding:w,resource:{buffer:U(v),offset:4294967296*A[u+4+16>>2]+A[u+16>>2],size:l}}):u=l?
{binding:w,resource:U(l)}:{binding:w,resource:U(q)};p.call(m,u)}c={label:c,layout:d,entries:g};a=U(a);d=Bc(0);T(d,a.createBindGroup(c));return d},m:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],g=0;g<d;++g){var h=f,m=h.push,p=b+88*g,u=A[p+4>>2],v=A[p+8>>2];var l=p+24;var q=A[l+4>>2];l=q?{type:Vb[q],hasDynamicOffset:!!A[l+8>>2],minBindingSize:4294967296*A[l+4+16>>2]+A[l+16>>2]}:void 0;q=(q=A[p+48+4>>2])?{type:dc[q]}:void 0;var w=p+56;var x=A[w+4>>2];w=x?{sampleType:ic[x],viewDimension:jc[A[w+
8>>2]],multisampled:!!A[w+12>>2]}:void 0;p+=72;p=(x=A[p+4>>2])?{access:ec[x],format:W[A[p+8>>2]],viewDimension:jc[A[p+12>>2]]}:void 0;m.call(h,{binding:u,visibility:v,buffer:l,sampler:q,texture:w,storageTexture:p})}c={label:c,entries:f};a=U(a);d=Cc(0);T(d,a.createBindGroupLayout(c));return d},u:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=Ec(0);T(b,a.createCommandEncoder(c));return b},za:(a,b)=>{var c=V(b+4);var d=Fb(A[b+12>>2]);b=(b+=16)?{module:U(A[b+4>>2]),constants:Eb(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+
8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=Gc(0);T(d,a.createComputePipeline(c));return d},Aa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],g=0;g<c;++g)f.push(U(A[d+4*g>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=Hc(0);T(c,a.createPipelineLayout(b));return c},ya:(a,b)=>{b=Sb(b);a=U(a);var c=Jc(0);T(c,a.createRenderPipeline(b));return c},Ba:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Ub[A[b+12>>2]],addressModeV:Ub[A[b+16>>2]],addressModeW:Ub[A[b+20>>2]],magFilter:Zb[A[b+24>>2]],
minFilter:Zb[A[b+28>>2]],mipmapFilter:ac[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Ib[A[b+44>>2]],maxAnisotropy:qa[b+48>>1]});a=U(a);b=Kc(0);T(b,a.createSampler(c));return b},n:(a,b)=>{var c={label:V(b+4),size:Cb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:hc[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=Mc(0);T(d,a.createTexture(c));return d},Ea:(a,
b)=>{Tb(U(a).limits,b);return 1},f:(a,b)=>U(a).features.has(Yb[b]),La:(a,b)=>{a=N(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Hc=V(b+4);b=Lc(0);T(b,a);return b},ka:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},k:function(a,b,c,d,f){c=G(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},Ca:(a,b,c,d,f,g)=>{var h=A[f+8>>2],m=A[f+12>>2],p=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[p>>2],y:A[p+4>>2],z:A[p+8>>2]},aspect:gc[A[b+20>>
2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===h?void 0:h,rowsPerImage:4294967295===m?void 0:m},Cb(g))},s:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},t:(a,b,c,d,f,g)=>{U(a).drawIndexed(b,c,d>>>0,f,g>>>0)},na:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},sa:(a,b)=>{U(a).setBlendConstant(Bb(b))},qa:function(a,b,c,d,f){d=G(d);f=G(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Pb[c],d,f)},ta:(a,b)=>{U(a).setPipeline(U(b))},
b:(a,b,c,d,f)=>{U(a).setScissorRect(b,c,d,f)},ra:(a,b)=>{U(a).setStencilReference(b>>>0)},pa:function(a,b,c,d,f){d=G(d);f=G(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},e:(a,b,c,d,f,g,h)=>{U(a).setViewport(b,c,d,f,g,h)},Ka:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Wb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>
2,f+4*d>>2),g=>W[g])}b=A[b>>2];0!==b&&(c.colorSpace=cc[A[b+8>>2]],c.Jc={mode:kc[A[b+12>>2]]});a.configure(c)},Fa:(a,b)=>{a=U(a);try{var c=Mc(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},h:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:jc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:gc[A[b+36>>2]]}}a=U(a);b=
Nc(0);T(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Wa;sa();jb=Z.Kb;c=Z;R=c.Ya;tc=c.Za;e.__sapp_emsc_onpaste=uc=c._a;e.__sapp_html5_get_ask_leave_site=vc=c.$a;e.__sapp_emsc_begin_drop=wc=c.ab;e.__sapp_emsc_drop=xc=c.bb;e.__sapp_emsc_end_drop=yc=c.cb;e.__sapp_emsc_invoke_fetch_cb=c.db;e._main=zc=c.eb;e.__saudio_emsc_pull=c.fb;e.__sfetch_emsc_head_response=c.gb;e.__sfetch_emsc_get_response=c.hb;e.__sfetch_emsc_failed_http_status=c.ib;e.__sfetch_emsc_failed_buffer_too_small=c.jb;e.__sfetch_emsc_failed_other=
c.kb;Bc=c.lb;Cc=c.mb;Dc=c.nb;Ec=c.ob;Fc=c.pb;Gc=c.qb;Hc=c.rb;Ic=c.vb;Jc=c.wb;Kc=c.xb;Lc=c.yb;Mc=c.zb;Nc=c.Ab;Oc=c.Gb;Pc=c.Hb;Qc=c.Ib;Rc=c.Jb;Sc=c.Lb;Tc=c.Mb;Y=c.Nb;xb=c.Ob;X=c.Pb;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Uc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("nuklear-sapp-ui.wasm",ia):ia+"nuklear-sapp-ui.wasm";return a((await ya(b)).instance)})();
function Vc(a=[]){var b=zc;a.unshift(ea);var c=a.length,d=xb(4*(c+1)),f=d;a.forEach(h=>{A[f>>2]=S(h);f+=4});A[f>>2]=0;try{var g=b(c,d);La(g)}catch(h){Ja(h)}}
function Wc(a=da){function b(){e.calledRun=!0;if(!r){Z.Xa();e.onRuntimeInitialized?.();e.noInitialRun||Vc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Wc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Wc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Wc();
