var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),p,q=!1,na,la=a=>a.startsWith("file://"),oa,t,y,pa,qa,z,A,B,C,ra;
function sa(){var a=oa.buffer;t=new Int8Array(a);pa=new Int16Array(a);y=new Uint8Array(a);qa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){e.onAbort?.(a);a="Aborted("+a+")";k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function wa(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=ua;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},D=0,E=null,Ea=!0,Fa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|h);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):
(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ga=0,Ha=[0,31,60,91,121,152,182,213,244,274,305,335],Ia=[0,31,59,90,120,151,181,212,243,273,304,334],G=a=>-9007199254740992>a||9007199254740992<a?NaN:Number(a),H={},Ja=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ka=a=>{na=a;Ea||0<Ga||(e.onExit?.(a),q=!0);fa(a,new za(a))},La=a=>{na=a;Ka(a)},Ma=()=>{if(!(Ea||0<Ga))try{var a=na;na=a;Ka(a)}catch(b){Ja(b)}},Na=a=>{if(!q)try{a(),Ma()}catch(b){Ja(b)}},I=
(a,b,c)=>{var d=y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;h++}}d[b]=0;return b-f},Va=(a,b)=>{Oa=a;Pa=b;if(J)if(Qa||=!0,0==a)L=function(){setTimeout(M,Math.max(0,Ra+b-performance.now())|
0)};else if(1==a)L=function(){Ta(M)};else if(2==a){if("undefined"==typeof Ua)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ua=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ua=setImmediate;L=function(){Ua(M)}}},db=(a,b,c,d,f)=>{function h(){return g<
Wa?(Ma(),!1):!0}J=a;Xa=d;var g=Wa;Qa=!1;M=function(){if(!q)if(0<Ya.length){var l=Ya.shift();l.Ac(l.rc);if(Za){var n=Za,u=0==n%1?n-1:Math.floor(n);Za=l.uc?u:(8*n+(u+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",n=Za??0,u=$a.zc??0,n?n<u?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));h()&&setTimeout(M,0)}else if(h())if(ab=ab+1|0,1==Oa&&1<Pa&&0!=ab%Pa)L();else{0==Oa&&(Ra=performance.now());a:if(!q){for(l of bb)if(!1===l())break a;Na(a);for(n of cb)n()}h()&&
L()}};f||(0<b?Va(0,1E3/b):Va(1,1),L());if(c)throw"unwind";},Qa=!1,L=null,Wa=0,J=null,Xa=0,Oa=0,Pa=0,ab=0,Ya=[],bb=[],cb=[];function eb(){L=null;Wa++}var fb=0;function Ta(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===fb)fb=b+1E3/60;else for(;b+2>=fb;)fb+=1E3/60;setTimeout(a,Math.max(fb-b,0))}}
var $a={},Ra,M,Ua,Za,gb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?F(y,a):"":a;return gb[a]||("undefined"!=typeof document?document.querySelector(a):null)},hb=a=>0>gb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ib=[],jb,O=a=>{var b=ib[a];b||(ib[a]=b=jb.get(a));return b};function kb(a){var b=P.vb[a];b.target.removeEventListener(b.ub,b.ec,b.wb);P.vb.splice(a,1)}
function lb(){if(navigator.userActivation?navigator.userActivation.isActive:P.Wb&&P.pc.Tb){var a=P.Gb;P.Gb=[];for(var b of a)b.$b(...b.dc)}}function Q(a){if(!a.target)return-4;if(a.Db)a.ec=function(c){++P.Wb;P.pc=a;lb();a.Eb(c);lb();--P.Wb},a.target.addEventListener(a.ub,a.ec,a.wb),P.vb.push(a);else for(var b=0;b<P.vb.length;++b)P.vb[b].target==a.target&&P.vb[b].ub==a.ub&&kb(b--);return 0}function mb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={sc:0,Bc:0,Xb:0,Hb:0,cc:0,bc:0,Ub:0,yc:0,Ec:0,xc:0,Vb:0,Yb:0,Nc:0,ac:0,Dc(a,b,c){t.set(t.subarray(b,b+c),a)},Fc(){for(;P.vb.length;)kb(P.vb.length-1);P.Gb=[]},Wb:0,Gb:[],wc(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var f of P.Gb)if(f.$b==a&&d(f.dc,c))return;P.Gb.push({$b:a,ic:b,dc:c});P.Gb.sort((h,g)=>h.ic<g.ic)},Hc(a){P.Gb=P.Gb.filter(b=>b.$b!=a)},vb:[],Gc:(a,b)=>{for(var c=0;c<P.vb.length;++c)P.vb[c].target!=a||b&&b!=P.vb[c].ub||
kb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},nb=(a,b,c,d,f,h)=>{P.Ub||(P.Ub=R(256));a={target:N(a),ub:h,Db:d,Eb:(g=event)=>{var l=g.target.id?g.target.id:"",n=P.Ub;I(mb(g.target),n+0,128);I(l,n+128,128);O(d)(f,n,b)&&g.preventDefault()},wb:c};return Q(a)},ob=(a,b,c,d,f)=>{P.Vb||(P.Vb=R(276));return Q({target:a,ub:f,Db:d,Eb:(h=event)=>{var g=P.Vb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,n=!!l;t[g]=n;t[g+1]=P.fullscreenEnabled();var u=n?l:P.qc,v=u?.id||"";I(mb(u),g+2,128);I(v,g+130,128);z[g+260>>2]=u?u.clientWidth:0;z[g+264>>2]=u?u.clientHeight:0;z[g+268>>2]=screen.width;z[g+272>>2]=screen.height;n&&(P.qc=l);O(d)(19,g,b)&&h.preventDefault()},wb:c})},pb=(a,b,c,d,f,h)=>{P.Xb||(P.Xb=R(160));a={target:N(a),ub:h,Db:d,Eb:g=>{var l=P.Xb;C[l>>3]=g.timeStamp;var n=l>>2;z[n+2]=g.location;t[l+12]=g.ctrlKey;t[l+13]=g.shiftKey;t[l+14]=g.altKey;t[l+15]=g.metaKey;t[l+
16]=g.repeat;z[n+5]=g.charCode;z[n+6]=g.keyCode;z[n+7]=g.which;I(g.key||"",l+32,32);I(g.code||"",l+64,32);I(g.char||"",l+96,32);I(g.locale||"",l+128,32);O(d)(f,l,b)&&g.preventDefault()},wb:c};return Q(a)},qb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=hb(c);z[d+10]=b.clientX-(a.left|
0);z[d+11]=b.clientY-(a.top|0)},rb=(a,b,c,d,f,h)=>{P.Hb||(P.Hb=R(64));a=N(a);return Q({target:a,Tb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ub:h,Db:d,Eb:(g=event)=>{qb(P.Hb,g,a);O(d)(f,P.Hb,b)&&g.preventDefault()},wb:c})},sb=(a,b,c,d)=>{P.Yb||(P.Yb=R(257));return Q({target:a,ub:"pointerlockchange",Db:d,Eb:(f=event)=>{var h=P.Yb,g=document.pointerLockElement;t[h]=!!g;var l=g?.id||"";I(mb(g),h+1,128);I(l,h+129,128);O(d)(20,h,b)&&f.preventDefault()},wb:c})},tb=(a,b,c,d)=>Q({target:a,ub:"pointerlockerror",
Db:d,Eb:(f=event)=>{O(d)(38,0,b)&&f.preventDefault()},wb:c}),ub=(a,b,c,d)=>{P.bc||(P.bc=R(36));a=N(a);return Q({target:a,ub:"resize",Db:d,Eb:(f=event)=>{if(f.target==a){var h=document.body;if(h){var g=P.bc;z[g>>2]=0;z[g+4>>2]=h.clientWidth;z[g+8>>2]=h.clientHeight;z[g+12>>2]=innerWidth;z[g+16>>2]=innerHeight;z[g+20>>2]=outerWidth;z[g+24>>2]=outerHeight;z[g+28>>2]=pageXOffset|0;z[g+32>>2]=pageYOffset|0;O(d)(10,g,b)&&f.preventDefault()}}},wb:c})},vb=(a,b,c,d,f,h)=>{P.ac||(P.ac=R(1552));a=N(a);return Q({target:a,
Tb:"touchstart"==h||"touchend"==h,ub:h,Db:d,Eb:g=>{var l={},n=g.touches;for(var u of n)u.fc=u.hc=0,l[u.identifier]=u;for(var v of g.changedTouches)v.fc=1,l[v.identifier]=v;for(var m of g.targetTouches)l[m.identifier].hc=1;n=P.ac;C[n>>3]=g.timeStamp;t[n+12]=g.ctrlKey;t[n+13]=g.shiftKey;t[n+14]=g.altKey;t[n+15]=g.metaKey;u=n+16;v=hb(a);m=0;for(let r of Object.values(l))if(l=u>>2,z[l]=r.identifier,z[l+1]=r.screenX,z[l+2]=r.screenY,z[l+3]=r.clientX,z[l+4]=r.clientY,z[l+5]=r.pageX,z[l+6]=r.pageY,t[u+28]=
r.fc,t[u+29]=r.hc,z[l+8]=r.clientX-(v.left|0),z[l+9]=r.clientY-(v.top|0),u+=48,31<++m)break;z[n+8>>2]=m;O(d)(f,n,b)&&g.preventDefault()},wb:c})},wb=(a,b,c,d)=>{P.cc||(P.cc=R(96));return Q({target:a,Tb:!0,ub:"wheel",Db:d,Eb:(f=event)=>{var h=P.cc;qb(h,f,a);C[h+64>>3]=f.deltaX;C[h+72>>3]=f.deltaY;C[h+80>>3]=f.deltaZ;z[h+88>>2]=f.deltaMode;O(d)(9,h,b)&&f.preventDefault()},wb:c})},xb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
S=a=>{var b=xb(a)+1,c=yb(b);I(a,c,b);return c},zb=[],T=(a,b)=>{zb[a>>>=0]=b},Ab=[],U=a=>{if(a)return zb[a>>>0]},Bb=a=>{var b=A[a>>2];return b?F(y,b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?F(y,b,a):"";if(0===a)return""},Cb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),Db=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Eb=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},Fb=(a,b)=>{if(a){for(var c=
{},d=0;d<a;++d){var f=b+24*d,h=Bb(f+4);c[h]=C[f+16>>3]}return c}},Gb=a=>a?U(a):"auto",Tb=a=>{function b(d){if(d)return{operation:Hb[A[d>>2]],srcFactor:Ib[A[d+4>>2]],dstFactor:Ib[A[d+8>>2]]}}function c(d){return{compare:Jb[A[d>>2]],failOp:Mb[A[d+4>>2]],depthFailOp:Mb[A[d+8>>2]],passOp:Mb[A[d+12>>2]]}}return{label:V(a+4),layout:Gb(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),h=Fb(A[d+16>>2],A[d+20>>2]);var g=A[d+24>>2];var l=A[d+28>>2];if(g){for(var n=[],u=0;u<g;++u){var v=n,m=v.push;var r=
l+24*u;if(r){var w=A[r+4>>2],x=A[r+16>>2];if(0===w&&0===x)var K=null;else{K=4294967296*A[r+4+8>>2]+A[r+8>>2];w=Nb[w];r=A[r+20>>2];for(var Kb=[],Sa=0;Sa<x;++Sa){var Lb=Kb,Bc=Lb.push,va=r+24*Sa;Bc.call(Lb,{format:Ob[A[va+4>>2]],offset:4294967296*A[va+4+8>>2]+A[va+8>>2],shaderLocation:A[va+16>>2]})}K={arrayStride:K,stepMode:w,attributes:Kb}}}else K=void 0;m.call(v,K)}g=n}else g=void 0;return{module:f,constants:h,buffers:g,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Pb[A[d+4>>
2]],stripIndexFormat:Qb[A[d+8>>2]],frontFace:Rb[A[d+12>>2]],cullMode:Sb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Jb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+
12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),h=Fb(A[d+16>>2],A[d+20>>2]),g=A[d+24>>2],l=A[d+28>>2],n=[],u=0;u<g;++u){var v=n,m=v.push,r=l+24*u,w=A[r+4>>2];if(0===w)r=void 0;else{w=W[w];var x=(x=A[r+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;r={format:w,blend:x,writeMask:A[r+16>>2]}}m.call(v,r)}return{module:f,constants:h,targets:n,entryPoint:V(d+8)}}}(A[a+92>>2])}},Ub=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",
12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);
ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",
140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.Cc&&c("maxImmediateSize",148)},Vb=[,"clamp-to-edge","repeat","mirror-repeat"],Ib=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Hb=[,"add","subtract","reverse-subtract","min","max"],Wb=["binding-not-used",,"uniform","storage","read-only-storage"],Jb=
[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Xb=[,"opaque","premultiplied","unpremultiplied","inherit"],Sb=[,"none","front","back"],Yb=[,"compatibility","core"],Zb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",
12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},$b=[,"nearest","linear"],Rb=[,"ccw","cw"],Qb=[,"uint16","uint32"],ac=[,"load","clear"],bc=[,"nearest","linear"],cc=[,"low-power",
"high-performance"],dc=[,"srgb","display-p3"],Pb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],ec=["binding-not-used",,"filtering","non-filtering","comparison"],Mb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],fc=["binding-not-used",,"write-only","read-only","read-write"],gc=[,"store","discard"],hc=[,"all","stencil-only","depth-only"],ic=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm",
"r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus",
"depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm",
"astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb",
"astc-12x12-unorm","astc-12x12-unorm-srgb"],jc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],kc=[,"1d","2d","2d-array","cube","cube-array","3d"],lc=[,"standard","extended"],Ob=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2",
"float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Nb=[,"vertex","instance"],mc={undefined:1,unknown:1,destroyed:2},nc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";nc.Zb||(nc.Zb={});nc.Zb[a]||(nc.Zb[a]=1,ca&&(a="warning: "+a),k(a))},oc={rgba8unorm:22,bgra8unorm:27},pc={},rc=()=>{if(!qc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==
typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in pc)void 0===pc[b]?delete a[b]:a[b]=pc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);qc=c}return qc},qc,sc=[null,[],[]],tc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Ta;e.pauseMainLoop=eb;e.resumeMainLoop=function(){Wa++;var a=Oa,b=Pa,c=J;J=null;db(c,0,!1,Xa,!0);Va(a,b);L()};e.preMainLoop&&bb.push(e.preMainLoop);e.postMainLoop&&cb.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);
e.print&&(ma=e.print);e.printErr&&(k=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var R,uc,vc,wc,xc,yc,zc,Ac,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Y,yb,X,Vc={q:function(){return 0},X:function(){return 0},Y:function(){},aa:()=>ta(""),Ta:()=>{Ea=!1;Ga=0},S:function(a,b){a=G(a);a=new Date(1E3*a);z[b>>2]=a.getSeconds();z[b+4>>2]=a.getMinutes();z[b+8>>2]=a.getHours();z[b+12>>2]=a.getDate();z[b+16>>2]=a.getMonth();z[b+20>>2]=a.getFullYear()-1900;z[b+24>>2]=a.getDay();var c=a.getFullYear();z[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ia:Ha)[a.getMonth()]+a.getDate()-1|
0;z[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Ua:(a,b)=>{H[a]&&(clearTimeout(H[a].id),delete H[a]);if(!b)return 0;var c=setTimeout(()=>{delete H[a];Na(()=>Tc(a,performance.now()))},b);H[a]={id:c,Lc:b};return 0},T:(a,b,c,d)=>{var f=(new Date).getFullYear(),h=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();
A[a>>2]=60*Math.max(h,f);z[b>>2]=Number(h!=f);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(h);b=b(f);f<h?(I(a,c,17),I(b,d,17)):(I(a,d,17),I(b,c,17))},Ga:()=>{eb();J=null},$:()=>Date.now(),N:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,P:(a,b,c)=>{a=N(a);if(!a)return-4;a=hb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},Ha:()=>performance.now(),Ma:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}
return requestAnimationFrame(c)},R:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},v:(a,b,c,d)=>nb(a,b,c,d,12,"blur"),M:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},w:(a,b,c,d)=>nb(a,b,c,d,13,"focus"),u:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;
a=N(a);if(!a)return-4;ob(a,b,c,d,"webkitfullscreenchange");return ob(a,b,c,d,"fullscreenchange")},F:(a,b,c,d)=>pb(a,b,c,d,2,"keydown"),D:(a,b,c,d)=>pb(a,b,c,d,1,"keypress"),E:(a,b,c,d)=>pb(a,b,c,d,3,"keyup"),Oa:(a,b,c)=>{a=O(a);db(a,b,c)},L:(a,b,c,d)=>rb(a,b,c,d,5,"mousedown"),I:(a,b,c,d)=>rb(a,b,c,d,33,"mouseenter"),H:(a,b,c,d)=>rb(a,b,c,d,34,"mouseleave"),J:(a,b,c,d)=>rb(a,b,c,d,8,"mousemove"),K:(a,b,c,d)=>rb(a,b,c,d,6,"mouseup"),y:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?sb(a,b,c,
d):-4:-1,x:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?tb(a,b,c,d):-4:-1,O:(a,b,c,d)=>ub(a,b,c,d),z:(a,b,c,d)=>vb(a,b,c,d,25,"touchcancel"),A:(a,b,c,d)=>vb(a,b,c,d,23,"touchend"),B:(a,b,c,d)=>vb(a,b,c,d,24,"touchmove"),C:(a,b,c,d)=>vb(a,b,c,d,22,"touchstart"),G:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?wb(a,b,c,d):-1:-4,ea:function(a,b,c,d,f,h){b=G(b);c=G(c);a=U(a);var g={};if(h){var l=A[h+12>>2];if(l){var n=A[h+16>>2];g.requiredFeatures=Array.from(A.subarray(n>>2,n+4*l>>2),m=>Zb[m])}var u=
A[h+20>>2];if(u){var v={};function m(w,x,K=!1){x=A[u+x>>2];4294967295==x||K&&0==x||(v[w]=x)}function r(w,x){x=u+x;var K=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=K)v[w]=4294967296*A[x+4>>2]+A[x>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",24);m("maxDynamicUniformBuffersPerPipelineLayout",32);m("maxDynamicStorageBuffersPerPipelineLayout",36);m("maxSampledTexturesPerShaderStage",
40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);r("maxUniformBufferBindingSize",64);r("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);r("maxBufferSize",96);m("maxVertexAttributes",104);m("maxVertexBufferArrayStride",108);m("maxInterStageShaderVariables",112);m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",
120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",148,!0);g.requiredLimits=v}if(l=A[h+24>>2])l={label:V(l+4)},g.defaultQueue=l;g.label=V(h+4)}a.requestDevice(g).then(m=>{T(f,m.queue);T(d,m);c&&m.lost.then(r=>{m.onuncapturederror=()=>{};var w=X(),x=S(r.message);Pc(c,mc[r.reason],x);Y(w)});m.onuncapturederror=
r=>{var w=5;r.error instanceof GPUValidationError?w=2:r.error instanceof GPUOutOfMemoryError?w=3:r.error instanceof GPUInternalError&&(w=4);var x=X();r=S(r.error.message);Sc(d,w,r);Y(x)};Rc(b,1,d,0)},m=>{var r=X();m=S(m.message);Rc(b,3,d,m);c&&Pc(c,4,m);Y(r)})},ia:(a,b,c)=>{var d=U(a);0===c&&nc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(g){return 0}var h=Uc(16,f.byteLength);y.fill(0,h,f.byteLength);Ab[a].push(()=>{(new Uint8Array(f)).set(y.subarray(h,h+f.byteLength));uc(h)});return h},
ha:a=>{var b=U(a),c=Ab[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete Ab[a];b.unmap()}},a:a=>{delete zb[a]},j:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(h){return!1}T(c,f);d&&(Ab[c]=[]);return!0},da:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=Bb(d+8)}T(c,U(a).createShaderModule(b))},ga:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},ba:()=>
{var a=navigator.gpu.getPreferredCanvasFormat();return oc[a]},ca:function(a,b,c,d){b=G(b);if(c){var f={featureLevel:Yb[A[c+4>>2]],powerPreference:cc[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Oc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(h=>{if(h)T(d,h),Qc(b,1,d,0);else{h=X();var g=S("WebGPU not available on this browser (requestAdapter returned null)");Qc(b,3,d,g);Y(h)}},h=>{var g=X();h=S(h.message);Qc(b,4,d,h);Y(g)}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),
Qc(b,3,d,a),Y(f))},Z:(a,b)=>{var c=0,d=0,f;for(f of rc()){var h=b+c;A[a+d>>2]=h;c+=I(f,h,Infinity)+1;d+=4}return 0},_:(a,b)=>{var c=rc();A[a>>2]=c.length;a=0;for(var d of c)a+=xb(d)+1;A[b>>2]=a;return 0},p:()=>52,W:()=>52,U:function(){return 70},V:(a,b,c,d)=>{for(var f=0,h=0;h<c;h++){var g=A[b>>2],l=A[b+4>>2];b+=8;for(var n=0;n<l;n++){var u=a,v=y[g+n],m=sc[u];0===v||10===v?((1===u?ma:k)(F(m)),m.length=0):m.push(v)}f+=l}A[d>>2]=f;return 0},Sa:Ka,Va:function(){e.jc=a=>{0!=wc()&&(a.preventDefault(),
a.returnValue=" ")};window.addEventListener("beforeunload",e.jc)},Ja:function(){e.oc=a=>{const b=a.clipboardData.getData("text");tc(()=>{const c=S(b);vc(c)})};window.addEventListener("paste",e.oc)},ua:function(){e.Ic=[];e.kc=b=>{b.stopPropagation();b.preventDefault()};e.lc=b=>{b.stopPropagation();b.preventDefault()};e.mc=b=>{b.stopPropagation();b.preventDefault()};e.nc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Jc=c;xc(c.length);for(let f=0;f<c.length;f++)tc(()=>{const h=
S(c[f].name);yc(f,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);zc(b.clientX,b.clientY,d)};const a=e.Fb;a.addEventListener("dragenter",e.kc,!1);a.addEventListener("dragleave",e.lc,!1);a.addEventListener("dragover",e.mc,!1);a.addEventListener("drop",e.nc,!1)},Qa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ra:function(a){e.Sb&&(URL.revokeObjectURL(e.Sb[a].tc),e.Sb[a]=null)},fa:function(a,b){0!==b&&(document.title=
b?F(y,b):"");a=a?F(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?gb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.Fb=N(a);e.Fb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.Fb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Na:function(){window.removeEventListener("beforeunload",e.jc)},Ia:function(){window.removeEventListener("paste",e.oc)},na:function(){const a=e.Fb;a.removeEventListener("dragenter",
e.kc);a.removeEventListener("dragleave",e.lc);a.removeEventListener("dragover",e.mc);a.removeEventListener("drop",e.nc)},i:function(){e.Fb&&e.Fb.requestPointerLock&&e.Fb.requestPointerLock()},o:function(a,b,c){if(e.Fb){if(0===b)a="none";else if(0!=c)a=e.Sb[a].vc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";
break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.Fb.style.cursor=a}},Pa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Da:function(a){a=a?F(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete",
"off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},r:function(){return navigator.userAgent.includes("Macintosh")?1:0},Q:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},
Wa:function(){return navigator.userAgent.includes("Macintosh")?1:0},g:(a,b)=>U(a).features.has(Zb[b]),wa:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:Eb(A[b+12>>2])});a=U(a);b=Gc(0);T(b,a.beginComputePass(c));return b},va:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],h=A[b+16>>2],g=[],l=0;l<f;++l){var n=g,u=n.push;var v=h+56*l;var m=A[v+4>>2];if(0!==m){var r=z[v+8>>2];-1==r&&(r=void 0);v={view:U(m),depthSlice:r,resolveTarget:U(A[v+12>>
2]),clearValue:Cb(v+24),loadOp:ac[A[v+16>>2]],storeOp:gc[A[v+20>>2]]}}else v=void 0;u.call(n,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:ac[A[f+8>>2]],depthStoreOp:gc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:ac[A[f+24>>2]],stencilStoreOp:gc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:g,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:Eb(A[b+28>>2]),maxDrawCount:d};
a=U(a);d=Jc(0);T(d,a.beginRenderPass(b));return d},ka:a=>{a=U(a);var b=Ec(0);T(b,a.finish());return b},la:a=>{U(a).end()},d:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ta:(a,b)=>{U(a).setPipeline(U(b))},l:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var h=[],g=0;g<f;++g){var l=h,n=l.push;var u=b+40*g;var v=A[u+8>>2],m=A[u+32>>2],r=A[u+36>>2],w=A[u+4>>2];v?(m=u+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),u={binding:w,resource:{buffer:U(v),
offset:4294967296*A[u+4+16>>2]+A[u+16>>2],size:m}}):u=m?{binding:w,resource:U(m)}:{binding:w,resource:U(r)};n.call(l,u)}c={label:c,layout:d,entries:h};a=U(a);d=Cc(0);T(d,a.createBindGroup(c));return d},m:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],h=0;h<d;++h){var g=f,l=g.push,n=b+88*h,u=A[n+4>>2],v=A[n+8>>2];var m=n+24;var r=A[m+4>>2];m=r?{type:Wb[r],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;r=(r=A[n+48+4>>2])?{type:ec[r]}:void 0;var w=
n+56;var x=A[w+4>>2];w=x?{sampleType:jc[x],viewDimension:kc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;n+=72;n=(x=A[n+4>>2])?{access:fc[x],format:W[A[n+8>>2]],viewDimension:kc[A[n+12>>2]]}:void 0;l.call(g,{binding:u,visibility:v,buffer:m,sampler:r,texture:w,storageTexture:n})}c={label:c,entries:f};a=U(a);d=Dc(0);T(d,a.createBindGroupLayout(c));return d},xa:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=Fc(0);T(b,a.createCommandEncoder(c));return b},za:(a,b)=>{var c=V(b+4);var d=Gb(A[b+12>>2]);b=(b+=
16)?{module:U(A[b+4>>2]),constants:Fb(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=Hc(0);T(d,a.createComputePipeline(c));return d},Aa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],h=0;h<c;++h)f.push(U(A[d+4*h>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=Ic(0);T(c,a.createPipelineLayout(b));return c},ya:(a,b)=>{b=Tb(b);a=U(a);var c=Kc(0);T(c,a.createRenderPipeline(b));return c},Ba:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Vb[A[b+12>>2]],addressModeV:Vb[A[b+
16>>2]],addressModeW:Vb[A[b+20>>2]],magFilter:$b[A[b+24>>2]],minFilter:$b[A[b+28>>2]],mipmapFilter:bc[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Jb[A[b+44>>2]],maxAnisotropy:qa[b+48>>1]});a=U(a);b=Lc(0);T(b,a.createSampler(c));return b},n:(a,b)=>{var c={label:V(b+4),size:Db(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:ic[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));
a=U(a);d=Nc(0);T(d,a.createTexture(c));return d},Ea:(a,b)=>{Ub(U(a).limits,b);return 1},f:(a,b)=>U(a).features.has(Zb[b]),La:(a,b)=>{a=N(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Kc=V(b+4);b=Mc(0);T(b,a);return b},ja:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},k:function(a,b,c,d,f){c=G(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},Ca:(a,b,c,d,f,h)=>{var g=A[f+8>>2],l=A[f+12>>2],n=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[n>>
2],y:A[n+4>>2],z:A[n+8>>2]},aspect:hc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===g?void 0:g,rowsPerImage:4294967295===l?void 0:l},Db(h))},s:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},t:(a,b,c,d,f,h)=>{U(a).drawIndexed(b,c,d>>>0,f,h>>>0)},ma:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ra:(a,b)=>{U(a).setBlendConstant(Cb(b))},pa:function(a,b,c,d,f){d=G(d);f=G(f);a=U(a);b=U(b);-1==f&&(f=void 0);
a.setIndexBuffer(b,Qb[c],d,f)},sa:(a,b)=>{U(a).setPipeline(U(b))},b:(a,b,c,d,f)=>{U(a).setScissorRect(b,c,d,f)},qa:(a,b)=>{U(a).setStencilReference(b>>>0)},oa:function(a,b,c,d,f){d=G(d);f=G(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},e:(a,b,c,d,f,h,g)=>{U(a).setViewport(b,c,d,f,h,g)},Ka:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Xb[A[b+
40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),h=>W[h])}b=A[b>>2];0!==b&&(c.colorSpace=dc[A[b+8>>2]],c.Mc={mode:lc[A[b+12>>2]]});a.configure(c)},Fa:(a,b)=>{a=U(a);try{var c=Nc(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},h:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:kc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+
28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:hc[A[b+36>>2]]}}a=U(a);b=Oc(0);T(b,a.createView(c));return b}};function Wc(a=[]){var b=Ac;a.unshift(ea);var c=a.length,d=yb(4*(c+1)),f=d;a.forEach(g=>{A[f>>2]=S(g);f+=4});A[f>>2]=0;try{var h=b(c,d);La(h)}catch(g){Ja(g)}}
function Xc(a=da){function b(){e.calledRun=!0;if(!q){Z.Ya();e.onRuntimeInitialized?.();e.noInitialRun||Wc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Xc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Xc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Z;
(async function(){function a(c){Z=c.exports;oa=Z.Xa;sa();jb=Z.Mb;c=Z;R=c.Za;uc=c._a;e.__sapp_emsc_onpaste=vc=c.$a;e.__sapp_html5_get_ask_leave_site=wc=c.ab;e.__sapp_emsc_begin_drop=xc=c.bb;e.__sapp_emsc_drop=yc=c.cb;e.__sapp_emsc_end_drop=zc=c.db;e.__sapp_emsc_invoke_fetch_cb=c.eb;e.__sapp_emsc_set_fullscreen_flag=c.fb;e._main=Ac=c.gb;e.__saudio_emsc_pull=c.hb;e.__sfetch_emsc_head_response=c.ib;e.__sfetch_emsc_get_response=c.jb;e.__sfetch_emsc_failed_http_status=c.kb;e.__sfetch_emsc_failed_buffer_too_small=
c.lb;e.__sfetch_emsc_failed_other=c.mb;Cc=c.nb;Dc=c.ob;Ec=c.pb;Fc=c.qb;Gc=c.rb;Hc=c.sb;Ic=c.tb;Jc=c.xb;Kc=c.yb;Lc=c.zb;Mc=c.Ab;Nc=c.Bb;Oc=c.Cb;Pc=c.Ib;Qc=c.Jb;Rc=c.Kb;Sc=c.Lb;Tc=c.Nb;Uc=c.Ob;Y=c.Pb;yb=c.Qb;X=c.Rb;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Vc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("nuklear-sapp-ui.wasm",ia):ia+"nuklear-sapp-ui.wasm";return a((await ya(b)).instance)})();
Xc();
