var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),g=console.error.bind(console),p,t=!1,na,la=a=>a.startsWith("file://"),u,y,oa,pa,z,A,B,C,qa;
function ra(){var a=sa.buffer;u=new Int8Array(a);oa=new Int16Array(a);y=new Uint8Array(a);pa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){e.onAbort?.(a);a="Aborted("+a+")";g(a);t=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function wa(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=ua;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},D=0,E=null,Ea=!0,Fa=globalThis.TextDecoder&&new TextDecoder,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|k);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|h:(f&7)<<18|k<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ga=0,G={},Ha=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ia=a=>{na=a;Ea||0<Ga||(e.onExit?.(a),t=!0);fa(a,new za(a))},Ja=a=>{na=a;Ia(a)},Ka=()=>{if(!(Ea||0<Ga))try{var a=na;na=a;Ia(a)}catch(b){Ha(b)}},H=a=>{if(!t)try{a(),Ka()}catch(b){Ha(b)}},Sa=(a,b)=>{La=a;Ma=b;if(I)if(Na||=!0,0==a)J=function(){setTimeout(L,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)J=function(){Pa(L)};else if(2==a){if(!Qa)if(globalThis.setImmediate)Qa=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}J=function(){Qa(L)}}},ab=(a,b,c,d,f)=>{function k(){return h<Ta?(Ka(),!1):!0}I=a;Ua=d;var h=Ta;Na=!1;L=function(){if(!t)if(0<Va.length){var l=Va.shift();l.Fc(l.wc);if(Wa){var m=
Wa,q=0==m%1?m-1:Math.floor(m);Wa=l.zc?q:(8*m+(q+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",m=Wa??0,q=Xa.Ec??0,m?m<q?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));k()&&setTimeout(L,0)}else if(k())if(Ya=Ya+1|0,1==La&&1<Ma&&0!=Ya%Ma)J();else{0==La&&(Oa=performance.now());a:if(!t){for(l of Za)if(!1===l())break a;H(a);for(m of $a)m()}k()&&J()}};f||(0<b?Sa(0,1E3/b):Sa(1,1),J());if(c)throw"unwind";},Na=!1,J=null,Ta=0,I=null,Ua=0,La=0,Ma=0,Ya=0,
Va=[],Za=[],$a=[];function bb(){J=null;Ta++}var M=0;function Pa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===M)M=b+1E3/60;else for(;b+2>=M;)M+=1E3/60;setTimeout(a,Math.max(M-b,0))}}
var Xa={},Oa,L,Qa,Wa,cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?F(y,a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):null)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],O=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};function gb(a){var b=P.zb[a];b.target.removeEventListener(b.yb,b.kc,b.Gb);P.zb.splice(a,1)}
function hb(){if(navigator.userActivation?navigator.userActivation.isActive:P.ac&&P.uc.Yb){var a=P.Vb;P.Vb=[];for(var b of a)b.ec(...b.jc)}}function Q(a){if(!a.target)return-4;if(a.Hb)a.kc=function(c){++P.ac;P.uc=a;hb();a.Ib(c);hb();--P.ac},a.target.addEventListener(a.yb,a.kc,a.Gb),P.zb.push(a);else for(var b=0;b<P.zb.length;++b)P.zb[b].target==a.target&&P.zb[b].yb==a.yb&&gb(b--);return 0}function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={xc:0,Gc:0,bc:0,Wb:0,ic:0,hc:0,Zb:0,Dc:0,Jc:0,Cc:0,$b:0,cc:0,Sc:0,fc:0,Ic(a,b,c){u.set(u.subarray(b,b+c),a)},Kc(){for(;P.zb.length;)gb(P.zb.length-1);P.Vb=[]},ac:0,Vb:[],Bc(a,b,c){function d(k,h){if(k.length!=h.length)return!1;for(var l in k)if(k[l]!=h[l])return!1;return!0}for(var f of P.Vb)if(f.ec==a&&d(f.jc,c))return;P.Vb.push({ec:a,nc:b,jc:c});P.Vb.sort((k,h)=>k.nc<h.nc)},Mc(a){P.Vb=P.Vb.filter(b=>b.ec!=a)},zb:[],Lc:(a,b)=>{for(var c=0;c<P.zb.length;++c)P.zb[c].target!=a||b&&b!=P.zb[c].yb||
gb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},R=(a,b,c)=>{var d=y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var k=0;k<a.length;++k){var h=a.codePointAt(k);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;k++}}d[b]=0;return b-
f},jb=(a,b,c,d,f,k)=>{P.Zb||(P.Zb=S(256));a={target:N(a),yb:k,Hb:d,Ib:(h=event)=>{var l=h.target.id?h.target.id:"",m=P.Zb;R(ib(h.target),m+0,128);R(l,m+128,128);O(d)(f,m,b)&&h.preventDefault()},Gb:c};return Q(a)},kb=(a,b,c,d,f)=>{P.$b||(P.$b=S(276));return Q({target:a,yb:f,Hb:d,Ib:(k=event)=>{var h=P.$b,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,m=!!l;u[h]=m;u[h+1]=P.fullscreenEnabled();
var q=m?l:P.vc,v=q?.id||"";R(ib(q),h+2,128);R(v,h+130,128);z[h+260>>2]=q?q.clientWidth:0;z[h+264>>2]=q?q.clientHeight:0;z[h+268>>2]=screen.width;z[h+272>>2]=screen.height;m&&(P.vc=l);O(d)(19,h,b)&&k.preventDefault()},Gb:c})},lb=(a,b,c,d,f,k)=>{P.bc||(P.bc=S(160));a={target:N(a),yb:k,Hb:d,Ib:h=>{var l=P.bc;C[l>>3]=h.timeStamp;var m=l>>2;z[m+2]=h.location;u[l+12]=h.ctrlKey;u[l+13]=h.shiftKey;u[l+14]=h.altKey;u[l+15]=h.metaKey;u[l+16]=h.repeat;z[m+5]=h.charCode;z[m+6]=h.keyCode;z[m+7]=h.which;R(h.key||
"",l+32,32);R(h.code||"",l+64,32);R(h.char||"",l+96,32);R(h.locale||"",l+128,32);O(d)(f,l,b)&&h.preventDefault()},Gb:c};return Q(a)},mb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=db(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,f,k)=>{P.Wb||(P.Wb=S(64));a=
N(a);return Q({target:a,Yb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,yb:k,Hb:d,Ib:(h=event)=>{mb(P.Wb,h,a);O(d)(f,P.Wb,b)&&h.preventDefault()},Gb:c})},ob=(a,b,c,d)=>{P.cc||(P.cc=S(257));return Q({target:a,yb:"pointerlockchange",Hb:d,Ib:(f=event)=>{var k=P.cc,h=document.pointerLockElement;u[k]=!!h;var l=h?.id||"";R(ib(h),k+1,128);R(l,k+129,128);O(d)(20,k,b)&&f.preventDefault()},Gb:c})},pb=(a,b,c,d)=>Q({target:a,yb:"pointerlockerror",Hb:d,Ib:(f=event)=>{O(d)(38,0,b)&&f.preventDefault()},Gb:c}),
qb=(a,b,c,d)=>{P.hc||(P.hc=S(36));a=N(a);return Q({target:a,yb:"resize",Hb:d,Ib:(f=event)=>{if(f.target==a){var k=document.body;if(k){var h=P.hc;z[h>>2]=0;z[h+4>>2]=k.clientWidth;z[h+8>>2]=k.clientHeight;z[h+12>>2]=innerWidth;z[h+16>>2]=innerHeight;z[h+20>>2]=outerWidth;z[h+24>>2]=outerHeight;z[h+28>>2]=pageXOffset|0;z[h+32>>2]=pageYOffset|0;O(d)(10,h,b)&&f.preventDefault()}}},Gb:c})},rb=(a,b,c,d,f,k)=>{P.fc||(P.fc=S(1552));a=N(a);return Q({target:a,Yb:"touchstart"==k||"touchend"==k,yb:k,Hb:d,Ib:h=>
{var l={},m=h.touches;for(var q of m)q.lc=q.mc=0,l[q.identifier]=q;for(var v of h.changedTouches)v.lc=1,l[v.identifier]=v;for(var n of h.targetTouches)l[n.identifier].mc=1;m=P.fc;C[m>>3]=h.timeStamp;u[m+12]=h.ctrlKey;u[m+13]=h.shiftKey;u[m+14]=h.altKey;u[m+15]=h.metaKey;q=m+16;v=db(a);n=0;for(let r of Object.values(l))if(l=q>>2,z[l]=r.identifier,z[l+1]=r.screenX,z[l+2]=r.screenY,z[l+3]=r.clientX,z[l+4]=r.clientY,z[l+5]=r.pageX,z[l+6]=r.pageY,u[q+28]=r.lc,u[q+29]=r.mc,z[l+8]=r.clientX-(v.left|0),z[l+
9]=r.clientY-(v.top|0),q+=48,31<++n)break;z[m+8>>2]=n;O(d)(f,m,b)&&h.preventDefault()},Gb:c})},sb=(a,b,c,d)=>{P.ic||(P.ic=S(96));return Q({target:a,Yb:!0,yb:"wheel",Hb:d,Ib:(f=event)=>{var k=P.ic;mb(k,f,a);C[k+64>>3]=f.deltaX;C[k+72>>3]=f.deltaY;C[k+80>>3]=f.deltaZ;z[k+88>>2]=f.deltaMode;O(d)(9,k,b)&&f.preventDefault()},Gb:c})},tb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},T=a=>{var b=tb(a)+1,c=ub(b);R(a,c,b);return c},
U=[],vb=(a,b)=>{U[a>>>0]=b},wb=[],V=a=>{if(a)return U[a>>>0]},xb=a=>{var b=A[a>>2];return b?F(y,b,A[a+4>>2]):""},W=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?F(y,b,a):"";if(0===a)return""},yb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),zb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Ab=a=>{if(0!==a)return{querySet:V(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},Bb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,k=xb(f+4);c[k]=
C[f+16>>3]}return c}},Cb=a=>a?V(a):"auto",Pb=a=>{function b(d){if(d)return{operation:Db[A[d>>2]],srcFactor:Eb[A[d+4>>2]],dstFactor:Eb[A[d+8>>2]]}}function c(d){return{compare:Fb[A[d>>2]],failOp:Gb[A[d+4>>2]],depthFailOp:Gb[A[d+8>>2]],passOp:Gb[A[d+12>>2]]}}return{label:W(a+4),layout:Cb(A[a+12>>2]),vertex:function(d){if(d){var f=V(A[d+4>>2]),k=Bb(A[d+16>>2],A[d+20>>2]);var h=A[d+24>>2];var l=A[d+28>>2];if(h){for(var m=[],q=0;q<h;++q){var v=m,n=v.push;var r=l+24*q;if(r){var w=A[r+4>>2],x=A[r+16>>2];
if(0===w&&0===x)var K=null;else{K=4294967296*A[r+4+8>>2]+A[r+8>>2];w=Hb[w];r=A[r+20>>2];for(var Kb=[],Ra=0;Ra<x;++Ra){var Lb=Kb,va=r+24*Ra;Lb.push.call(Lb,{format:Ib[A[va+4>>2]],offset:4294967296*A[va+4+8>>2]+A[va+8>>2],shaderLocation:A[va+16>>2]})}K={arrayStride:K,stepMode:w,attributes:Kb}}}else K=void 0;n.call(v,K)}h=m}else h=void 0;return{module:f,constants:k,buffers:h,entryPoint:W(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Jb[A[d+4>>2]],stripIndexFormat:Mb[A[d+8>>2]],frontFace:Nb[A[d+
12>>2]],cullMode:Ob[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:X[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Fb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=
V(A[d+4>>2]),k=Bb(A[d+16>>2],A[d+20>>2]),h=A[d+24>>2],l=A[d+28>>2],m=[],q=0;q<h;++q){var v=m,n=v.push,r=l+24*q,w=A[r+4>>2];if(0===w)r=void 0;else{w=X[w];var x=(x=A[r+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;r={format:w,blend:x,writeMask:A[r+16>>2]}}n.call(v,r)}return{module:f,constants:k,targets:m,entryPoint:W(d+8)}}}(A[a+92>>2])}},Qb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",
20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);
qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",
144);void 0!==a.Hc&&c("maxImmediateSize",148)},Rb=[,"clamp-to-edge","repeat","mirror-repeat"],Eb=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Db=[,"add","subtract","reverse-subtract","min","max"],Sb=["binding-not-used",,"uniform","storage","read-only-storage"],Fb=[,"never","less","equal","less-equal","greater",
"not-equal","greater-equal","always"],Tb=[,"opaque","premultiplied","unpremultiplied","inherit"],Ob=[,"none","front","back"],Ub=[,"compatibility","core"],Vb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",
14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Wb=[,"nearest","linear"],Nb=[,"ccw","cw"],Mb=[,"uint16","uint32"],Xb=[,"load","clear"],Yb=[,"nearest","linear"],Zb=[,"low-power","high-performance"],$b=[,"srgb",
"display-p3"],Jb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],ac=["binding-not-used",,"filtering","non-filtering","comparison"],Gb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],bc=["binding-not-used",,"write-only","read-only","read-write"],cc=[,"store","discard"],dc=[,"all","stencil-only","depth-only"],ec=[,"1d","2d","3d"],X=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float",
"rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float",
"depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm",
"astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],
fc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],gc=[,"1d","2d","2d-array","cube","cube-array","3d"],hc=[,"standard","extended"],Ib=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2",
"uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Hb=[,"vertex","instance"],ic={undefined:1,unknown:1,destroyed:2},jc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";jc.dc||(jc.dc={});jc.dc[a]||(jc.dc[a]=1,ca&&(a="warning: "+a),g(a))},kc={rgba8unorm:22,bgra8unorm:27},lc={},nc=()=>{if(!mc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-",
"_")+".UTF-8",_:ea||"./this.program"},b;for(b in lc)void 0===lc[b]?delete a[b]:a[b]=lc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);mc=c}return mc},mc,oc=[null,[],[]],pc=a=>{var b=Y();a();Z(b)};e.requestAnimationFrame=Pa;e.pauseMainLoop=bb;e.resumeMainLoop=function(){Ta++;var a=La,b=Ma,c=I;I=null;ab(c,0,!1,Ua,!0);Sa(a,b);J()};e.preMainLoop&&Za.push(e.preMainLoop);e.postMainLoop&&$a.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(g=e.printErr);
e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var S,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Z,ub,Y,sa,fb,Wc={p:function(){return 0},V:function(){return 0},W:function(){},Z:()=>ta(""),Ta:()=>{Ea=!1;Ga=0},Ua:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];H(()=>Uc(a,performance.now()))},b);G[a]={id:c,Qc:b};return 0},Ba:()=>{bb();I=null},N:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,P:(a,b,c)=>{a=N(a);if(!a)return-4;a=db(a);
C[b>>3]=a.width;C[c>>3]=a.height;return 0},Ca:()=>performance.now(),Ja:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Va:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},v:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),M:(a,
b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},w:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),u:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=N(a);if(!a)return-4;kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},F:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),D:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),E:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),Ka:(a,b,c)=>{a=O(a);ab(a,b,c)},L:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),I:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),H:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),
J:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),K:(a,b,c,d)=>nb(a,b,c,d,6,"mouseup"),y:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?ob(a,b,c,d):-4:-1,x:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?pb(a,b,c,d):-4:-1,O:(a,b,c,d)=>qb(a,b,c,d),z:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),A:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),B:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),C:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),G:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?sb(a,b,c,d):-1:-4,ba:function(a,b,c,d,
f,k){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=V(a);var h={};if(k){var l=A[k+12>>2];if(l){var m=A[k+16>>2];h.requiredFeatures=Array.from(A.subarray(m>>2,m+4*l>>2),n=>Vb[n])}var q=A[k+20>>2];if(q){var v={};function n(w,x,K=!1){x=A[q+x>>2];4294967295==x||K&&0==x||(v[w]=x)}function r(w,x){x=q+x;var K=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=K)v[w]=4294967296*A[x+4>>2]+A[x>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",
8);n("maxTextureDimension3D",12);n("maxTextureArrayLayers",16);n("maxBindGroups",20);n("maxBindGroupsPlusVertexBuffers",24);n("maxDynamicUniformBuffersPerPipelineLayout",32);n("maxDynamicStorageBuffersPerPipelineLayout",36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);r("maxUniformBufferBindingSize",
64);r("maxStorageBufferBindingSize",72);n("maxVertexBuffers",88);r("maxBufferSize",96);n("maxVertexAttributes",104);n("maxVertexBufferArrayStride",108);n("maxInterStageShaderVariables",112);n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",
148,!0);h.requiredLimits=v}if(l=A[k+24>>2])l={label:W(l+4)},h.defaultQueue=l;h.label=W(k+4)}a.requestDevice(h).then(n=>{H(()=>{U[f>>>0]=n.queue;U[d>>>0]=n;n.lost.then(r=>{H(()=>{n.onuncapturederror=()=>{};var w=Y(),x=T(r.message);Qc(c,ic[r.reason],x);Z(w)})});n.onuncapturederror=r=>{var w=5;r.error instanceof GPUValidationError?w=2:r.error instanceof GPUOutOfMemoryError?w=3:r.error instanceof GPUInternalError&&(w=4);var x=Y();r=T(r.error.message);Tc(d,w,r);Z(x)};Sc(b,1,d,0)})},n=>{H(()=>{var r=Y(),
w=T(n.message);Sc(b,3,d,w);c&&Qc(c,4,w);Z(r)})})},ea:(a,b,c)=>{var d=V(a);0===c&&jc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(h){return 0}var k=Vc(16,f.byteLength);y.fill(0,k,f.byteLength);wb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(k,k+f.byteLength));qc(k)});return k},da:a=>{var b=V(a),c=wb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete wb[a];b.unmap()}},a:a=>{delete U[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:W(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>
2],mappedAtCreation:d};a=V(a);try{var f=a.createBuffer(b)}catch(k){return!1}U[c>>>0]=f;d&&(wb[c]=[]);return!0},aa:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:W(b+4),code:""};switch(f){case 2:b.code=xb(d+8)}a=V(a).createShaderModule(b);U[c>>>0]=a},ca:a=>{a=V(a);a.onuncapturederror=null;a.destroy()},_:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return kc[a]},$:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Ub[A[c+4>>2]],powerPreference:Zb[A[c+
8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Tc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(k=>{H(()=>{if(k)U[d>>>0]=k,Rc(b,1,d,0);else{var h=Y(),l=T("WebGPU not available on this browser (requestAdapter returned null)");Rc(b,3,d,l);Z(h)}})},k=>{H(()=>{var h=Y(),l=T(k.message);Rc(b,4,d,l);Z(h)})}):(f=Y(),a=T("WebGPU not available on this browser (navigator.gpu is not available)"),Rc(b,3,d,a),Z(f))},X:(a,b)=>{var c=0,d=0,f;for(f of nc()){var k=b+c;A[a+d>>2]=
k;c+=R(f,k,Infinity)+1;d+=4}return 0},Y:(a,b)=>{var c=nc();A[a>>2]=c.length;a=0;for(var d of c)a+=tb(d)+1;A[b>>2]=a;return 0},S:()=>52,U:()=>52,Wa:function(){return 70},T:(a,b,c,d)=>{for(var f=0,k=0;k<c;k++){var h=A[b>>2],l=A[b+4>>2];b+=8;for(var m=0;m<l;m++){var q=a,v=y[h+m],n=oc[q];0===v||10===v?((1===q?ma:g)(F(n)),n.length=0):n.push(v)}f+=l}A[d>>2]=f;return 0},Sa:Ia,Za:function(){e.oc=a=>{0!=sc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.oc)},La:function(){e.tc=
a=>{const b=a.clipboardData.getData("text");pc(()=>{const c=T(b);rc(c)})};window.addEventListener("paste",e.tc)},Da:function(){e.Nc=[];e.pc=b=>{b.stopPropagation();b.preventDefault()};e.qc=b=>{b.stopPropagation();b.preventDefault()};e.rc=b=>{b.stopPropagation();b.preventDefault()};e.sc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Oc=c;tc(c.length);for(let f=0;f<c.length;f++)pc(()=>{const k=T(c[f].name);uc(f,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=
4);b.metaKey&&(d|=8);vc(b.clientX,b.clientY,d)};const a=e.Jb;a.addEventListener("dragenter",e.pc,!1);a.addEventListener("dragleave",e.qc,!1);a.addEventListener("dragover",e.rc,!1);a.addEventListener("drop",e.sc,!1)},Ra:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Xa:function(a){e.Xb&&(URL.revokeObjectURL(e.Xb[a].yc),e.Xb[a]=null)},oa:function(a,b){0!==b&&(document.title=b?F(y,b):"");a=a?F(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?cb[a]=
e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.Jb=N(a);e.Jb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.Jb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ya:function(){window.removeEventListener("beforeunload",e.oc)},Ga:function(){window.removeEventListener("paste",e.tc)},va:function(){const a=e.Jb;a.removeEventListener("dragenter",e.pc);a.removeEventListener("dragleave",e.qc);a.removeEventListener("dragover",
e.rc);a.removeEventListener("drop",e.sc)},i:function(){e.Jb&&e.Jb.requestPointerLock&&e.Jb.requestPointerLock()},q:function(a,b,c){if(e.Jb){if(0===b)a="none";else if(0!=c)a=e.Xb[a].Ac;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.Jb.style.cursor=
a}},Qa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),k=f.createImageData(a,b);k.data.set(y.subarray(c,c+a*b*4));f.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ea:function(a){a=a?F(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize",
"off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},Ma:function(){return e.Kb?e.Kb.bufferSize:0},Pa:function(a,b,c){e.xb=null;e.Kb=null;"undefined"!==typeof AudioContext?e.xb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.xb=null,console.log("sokol_audio.h: no WebAudio support"));return e.xb?(console.log("sokol_audio.h: sample rate ",
e.xb.sampleRate),e.Kb=e.xb.createScriptProcessor(c,0,b),e.Kb.onaudioprocess=d=>{const f=d.outputBuffer.length,k=xc(f);if(k){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const m=d.outputBuffer.getChannelData(l);for(let q=0;q<f;q++)m[q]=B[(k>>2)+(h*q+l)]}}},e.Kb.connect(e.xb.destination),a=()=>{e.xb&&"suspended"===e.xb.state&&e.xb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},Na:function(){return e.xb?e.xb.sampleRate:0},Oa:function(){const a=e.xb;null!==a&&(e.Kb&&e.Kb.disconnect(),a.close(),e.xb=null,e.Kb=null)},o:function(a,b,c,d,f,k){const h=b?F(y,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(h,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=k?(y.set(m,f),zc(a,d,m.length)):Bc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,m);Cc(a)}):Ac(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,
l);Cc(a)})},R:function(a,b){const c=b?F(y,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),Cc(a)):yc(a,Number(d))):Ac(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);Cc(a)})},r:function(){return navigator.userAgent.includes("Macintosh")?1:0},Q:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);
break;default:console.info(b)}},Fa:(a,b)=>{Qb(V(a).limits,b);return 1},e:(a,b)=>V(a).features.has(Vb[b]),ra:(a,b)=>{var c;b&&(c={label:W(b+4),timestampWrites:Ab(A[b+12>>2])});b=V(a);a=Hc(0);c=b.beginComputePass(c);U[a>>>0]=c;return a},qa:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=W(b+4);for(var f=A[b+12>>2],k=A[b+16>>2],h=[],l=0;l<f;++l){var m=h,q=m.push;var v=k+56*l;var n=A[v+4>>2];if(0!==n){var r=z[v+8>>2];-1==r&&(r=void 0);v={view:V(n),depthSlice:r,resolveTarget:V(A[v+
12>>2]),clearValue:yb(v+24),loadOp:Xb[A[v+16>>2]],storeOp:cc[A[v+20>>2]]}}else v=void 0;q.call(m,v)}f=A[b+20>>2];f=0!==f?{view:V(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Xb[A[f+8>>2]],depthStoreOp:cc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Xb[A[f+24>>2]],stencilStoreOp:cc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:h,depthStencilAttachment:f,occlusionQuerySet:V(A[b+24>>2]),timestampWrites:Ab(A[b+28>>2]),maxDrawCount:d};
d=V(a);a=Kc(0);b=d.beginRenderPass(b);U[a>>>0]=b;return a},ga:a=>{var b=V(a);a=Fc(0);b=b.finish();U[a>>>0]=b;return a},ha:a=>{V(a).end()},c:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},pa:(a,b)=>{V(a).setPipeline(V(b))},l:(a,b)=>{var c=W(b+4),d=V(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var k=[],h=0;h<f;++h){var l=k,m=l.push;var q=b+40*h;var v=A[q+8>>2],n=A[q+32>>2],r=A[q+36>>2],w=A[q+4>>2];v?(n=q+24,n=A[n>>2]+4294967296*z[n+4>>2],-1==n&&(n=void 0),q={binding:w,
resource:{buffer:V(v),offset:4294967296*A[q+4+16>>2]+A[q+16>>2],size:n}}):q=n?{binding:w,resource:V(n)}:{binding:w,resource:V(r)};m.call(l,q)}c={label:c,layout:d,entries:k};d=V(a);a=Dc(0);c=d.createBindGroup(c);U[a>>>0]=c;return a},m:(a,b)=>{var c=W(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],k=0;k<d;++k){var h=f,l=h.push,m=b+88*k,q=A[m+4>>2],v=A[m+8>>2];var n=m+24;var r=A[n+4>>2];n=r?{type:Sb[r],hasDynamicOffset:!!A[n+8>>2],minBindingSize:4294967296*A[n+4+16>>2]+A[n+16>>2]}:void 0;r=(r=A[m+48+4>>
2])?{type:ac[r]}:void 0;var w=m+56;var x=A[w+4>>2];w=x?{sampleType:fc[x],viewDimension:gc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;m+=72;m=(x=A[m+4>>2])?{access:bc[x],format:X[A[m+8>>2]],viewDimension:gc[A[m+12>>2]]}:void 0;l.call(h,{binding:q,visibility:v,buffer:n,sampler:r,texture:w,storageTexture:m})}c={label:c,entries:f};d=V(a);a=Ec(0);c=d.createBindGroupLayout(c);U[a>>>0]=c;return a},sa:(a,b)=>{var c;b&&(c={label:W(b+4)});b=V(a);a=Gc(0);c=b.createCommandEncoder(c);U[a>>>0]=c;return a},ua:(a,
b)=>{var c=W(b+4);var d=Cb(A[b+12>>2]);b=(b+=16)?{module:V(A[b+4>>2]),constants:Bb(A[b+16>>2],A[b+20>>2]),entryPoint:W(b+8)}:void 0;c={label:c,layout:d,compute:b};d=V(a);a=Ic(0);c=d.createComputePipeline(c);U[a>>>0]=c;return a},wa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],k=0;k<c;++k)f.push(V(A[d+4*k>>2]));b={label:W(b+4),bindGroupLayouts:f};c=V(a);a=Jc(0);b=c.createPipelineLayout(b);U[a>>>0]=b;return a},ta:(a,b)=>{b=Pb(b);var c=V(a);a=Lc(0);b=c.createRenderPipeline(b);U[a>>>0]=b;return a},xa:(a,
b)=>{var c;b&&(c={label:W(b+4),addressModeU:Rb[A[b+12>>2]],addressModeV:Rb[A[b+16>>2]],addressModeW:Rb[A[b+20>>2]],magFilter:Wb[A[b+24>>2]],minFilter:Wb[A[b+28>>2]],mipmapFilter:Yb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Fb[A[b+44>>2]],maxAnisotropy:pa[b+48>>1]});b=V(a);a=Mc(0);c=b.createSampler(c);U[a>>>0]=c;return a},n:(a,b)=>{var c={label:W(b+4),size:zb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:ec[A[b+24>>2]],format:X[A[b+40>>2]],usage:A[b+16>>2]},
d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>X[f]));a=V(a);d=Oc(0);vb(d,a.createTexture(c));return d},za:(a,b)=>{Qb(V(a).limits,b);return 1},d:(a,b)=>V(a).features.has(Vb[b]),Ia:(a,b)=>{a=N(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Pc=W(b+4);b=Nc(0);U[b>>>0]=a;return b},fa:(a,b,c)=>{a=V(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>V(d));a.submit(b)},h:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);V(a).writeBuffer(V(b),
c,y.subarray(d,d+f),0,f)},ya:(a,b,c,d,f,k)=>{var h=A[f+8>>2],l=A[f+12>>2],m=b+8;V(a).writeTexture({texture:V(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[m>>2],y:A[m+4>>2],z:A[m+8>>2]},aspect:dc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===h?void 0:h,rowsPerImage:4294967295===l?void 0:l},zb(k))},s:(a,b,c,d,f)=>{V(a).draw(b,c,d>>>0,f>>>0)},t:(a,b,c,d,f,k)=>{V(a).drawIndexed(b,c,d>>>0,f,k>>>0)},ia:a=>{V(a).end()},b:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,
c):a.setBindGroup(b,c,A,f>>2,d)},ma:(a,b)=>{V(a).setBlendConstant(yb(b))},ka:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);b=V(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Mb[c],d,f)},na:(a,b)=>{V(a).setPipeline(V(b))},j:(a,b,c,d,f)=>{V(a).setScissorRect(b,c,d,f)},la:(a,b)=>{V(a).setStencilReference(b>>>0)},ja:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<
f?NaN:Number(f);a=V(a);c=V(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},k:(a,b,c,d,f,k,h)=>{V(a).setViewport(b,c,d,f,k,h)},Ha:(a,b)=>{var c=A[b+4>>2];a=V(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:V(c),format:X[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Tb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),k=>X[k])}b=A[b>>2];0!==b&&(c.colorSpace=$b[A[b+8>>2]],c.Rc={mode:hc[A[b+12>>2]]});
a.configure(c)},Aa:(a,b)=>{a=V(a);try{var c=Oc(0),d=a.getCurrentTexture();U[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:W(b+4),format:X[A[b+12>>2]],dimension:gc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:dc[A[b+36>>2]]}}b=V(a);a=Pc(0);b=b.createView(c);U[a>>>0]=b;return a}};
function Xc(a=[]){var b=wc;a.unshift(ea);var c=a.length,d=ub(4*(c+1)),f=d;a.forEach(h=>{A[f>>2]=T(h);f+=4});A[f>>2]=0;try{var k=b(c,d);Ja(k)}catch(h){Ha(h)}}
function Yc(a=da){function b(){e.calledRun=!0;if(!t){Zc.$a();e.onRuntimeInitialized?.();e.noInitialRun||Xc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Yc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Yc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Zc;
(async function(){function a(c){c=Zc=c.exports;S=c.ab;qc=c.bb;rc=e.__sapp_emsc_onpaste=c.cb;sc=e.__sapp_html5_get_ask_leave_site=c.db;tc=e.__sapp_emsc_begin_drop=c.eb;uc=e.__sapp_emsc_drop=c.fb;vc=e.__sapp_emsc_end_drop=c.gb;e.__sapp_emsc_invoke_fetch_cb=c.hb;e.__sapp_emsc_set_fullscreen_flag=c.ib;wc=e._main=c.jb;xc=e.__saudio_emsc_pull=c.kb;yc=e.__sfetch_emsc_head_response=c.lb;zc=e.__sfetch_emsc_get_response=c.mb;Ac=e.__sfetch_emsc_failed_http_status=c.nb;Bc=e.__sfetch_emsc_failed_buffer_too_small=
c.ob;Cc=e.__sfetch_emsc_failed_other=c.pb;Dc=c.qb;Ec=c.rb;Fc=c.sb;Gc=c.tb;Hc=c.ub;Ic=c.vb;Jc=c.wb;Kc=c.Ab;Lc=c.Bb;Mc=c.Cb;Nc=c.Db;Oc=c.Eb;Pc=c.Fb;Qc=c.Lb;Rc=c.Mb;Sc=c.Nb;Tc=c.Ob;Uc=c.Qb;Vc=c.Rb;Z=c.Sb;ub=c.Tb;Y=c.Ub;sa=c._a;fb=c.Pb;ra();D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Zc}D++;e.monitorRunDependencies?.(D);var b={a:Wc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("plmpeg-sapp-ui.wasm",ia):ia+"plmpeg-sapp-ui.wasm";
return a((await ya(b)).instance)})();Yc();
