var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var g=console.error.bind(console),p,t=!1,ma,la=a=>a.startsWith("file://"),na,u,y,oa,pa,z,A,B,C,qa;
function ra(){var a=na.buffer;u=new Int8Array(a);oa=new Int16Array(a);y=new Uint8Array(a);pa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function sa(a){e.onAbort?.(a);a="Aborted("+a+")";g(a);t=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(e)},za=[],Aa=[],Ba=()=>{var a=e.preRun.shift();Aa.push(a)},D=0,E=null,Ca=!0,Da=0,F={},Ea=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Fa=a=>{ma=a;Ca||0<Da||(e.onExit?.(a),t=!0);fa(a,new xa(a))},Ga=a=>{ma=a;Fa(a)},Ha=()=>{if(!(Ca||0<Da))try{var a=ma;ma=a;Fa(a)}catch(b){Ea(b)}},Ia=a=>{if(!t)try{a(),Ha()}catch(b){Ea(b)}},Pa=(a,b)=>{Ja=a;Ka=b;if(G)if(La||=!0,0==a)H=function(){setTimeout(I,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)H=function(){Na(I)};else if(2==
a){if("undefined"==typeof Oa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Oa=setImmediate;H=function(){Oa(I)}}},Za=(a,b,c,d,f)=>{function h(){return k<Qa?(Ha(),!1):!0}G=a;Ra=d;var k=Qa;La=!1;I=function(){if(!t)if(0<
Ta.length){var l=Ta.shift();l.sc(l.jc);if(Ua){var m=Ua,r=0==m%1?m-1:Math.floor(m);Ua=l.mc?r:(8*m+(r+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",m=Ua??0,r=Va.rc??0,m?m<r?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));h()&&setTimeout(I,0)}else if(h())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)H();else{0==Ja&&(Ma=performance.now());a:if(!t){for(l of Xa)if(!1===l())break a;Ia(a);for(m of Ya)m()}h()&&H()}};f||(0<b?Pa(0,1E3/b):Pa(1,1),H());if(c)throw"unwind";
},La=!1,H=null,Qa=0,G=null,Ra=0,Ja=0,Ka=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){H=null;Qa++}var ab=0;function Na(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ab)ab=b+1E3/60;else for(;b+2>=ab;)ab+=1E3/60;setTimeout(a,Math.max(ab-b,0))}}
var Va={},Ma,I,Oa,Ua,bb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,K=(a=0,b)=>{var c=y;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&bb)return bb.decode(c.subarray(a,d));for(b="";a<d;){var f=c[a++];if(f&128){var h=c[a++]&63;if(192==(f&224))b+=String.fromCharCode((f&31)<<6|h);else{var k=c[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|c[a++]&63;65536>f?b+=String.fromCharCode(f):(f-=65536,b+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else b+=String.fromCharCode(f)}return b},
cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],L=a=>{a=2<a?a?K(a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):null)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],fb,M=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};function gb(a){var b=N.mb[a];b.target.removeEventListener(b.lb,b.Xb,b.tb);N.mb.splice(a,1)}
function hb(){if(navigator.userActivation?navigator.userActivation.isActive:N.Ob&&N.hc.Lb){var a=N.Ib;N.Ib=[];for(var b of a)b.Sb(...b.Wb)}}function O(a){if(!a.target)return-4;if(a.ub)a.Xb=function(c){++N.Ob;N.hc=a;hb();a.vb(c);hb();--N.Ob},a.target.addEventListener(a.lb,a.Xb,a.tb),N.mb.push(a);else for(var b=0;b<N.mb.length;++b)N.mb[b].target==a.target&&N.mb[b].lb==a.lb&&gb(b--);return 0}function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var N={kc:0,tc:0,Pb:0,Jb:0,Vb:0,Ub:0,Mb:0,qc:0,wc:0,pc:0,Nb:0,Qb:0,Fc:0,Tb:0,vc(a,b,c){u.set(u.subarray(b,b+c),a)},xc(){for(;N.mb.length;)gb(N.mb.length-1);N.Ib=[]},Ob:0,Ib:[],oc(a,b,c){function d(h,k){if(h.length!=k.length)return!1;for(var l in h)if(h[l]!=k[l])return!1;return!0}for(var f of N.Ib)if(f.Sb==a&&d(f.Wb,c))return;N.Ib.push({Sb:a,$b:b,Wb:c});N.Ib.sort((h,k)=>h.$b<k.$b)},zc(a){N.Ib=N.Ib.filter(b=>b.Sb!=a)},mb:[],yc:(a,b)=>{for(var c=0;c<N.mb.length;++c)N.mb[c].target!=a||b&&b!=N.mb[c].lb||
gb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},P=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;f++}}d[b]=0}},jb=(a,b,c,d,f,h)=>{N.Mb||
(N.Mb=Q(256));a={target:L(a),lb:h,ub:d,vb:(k=event)=>{var l=k.target.id?k.target.id:"",m=N.Mb;P(ib(k.target),m+0,128);P(l,m+128,128);M(d)(f,m,b)&&k.preventDefault()},tb:c};return O(a)},kb=(a,b,c,d,f)=>{N.Nb||(N.Nb=Q(276));return O({target:a,lb:f,ub:d,vb:(h=event)=>{var k=N.Nb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,m=!!l;u[k]=m;u[k+1]=N.fullscreenEnabled();var r=m?l:N.ic,v=
r?.id||"";P(ib(r),k+2,128);P(v,k+130,128);z[k+260>>2]=r?r.clientWidth:0;z[k+264>>2]=r?r.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;m&&(N.ic=l);M(d)(19,k,b)&&h.preventDefault()},tb:c})},lb=(a,b,c,d,f,h)=>{N.Pb||(N.Pb=Q(160));a={target:L(a),lb:h,ub:d,vb:k=>{var l=N.Pb;C[l>>3]=k.timeStamp;var m=l>>2;z[m+2]=k.location;u[l+12]=k.ctrlKey;u[l+13]=k.shiftKey;u[l+14]=k.altKey;u[l+15]=k.metaKey;u[l+16]=k.repeat;z[m+5]=k.charCode;z[m+6]=k.keyCode;z[m+7]=k.which;P(k.key||"",l+32,32);P(k.code||
"",l+64,32);P(k.char||"",l+96,32);P(k.locale||"",l+128,32);M(d)(f,l,b)&&k.preventDefault()},tb:c};return O(a)},mb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=db(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,f,h)=>{N.Jb||(N.Jb=Q(64));a=L(a);return O({target:a,
Lb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,lb:h,ub:d,vb:(k=event)=>{mb(N.Jb,k,a);M(d)(f,N.Jb,b)&&k.preventDefault()},tb:c})},ob=(a,b,c,d)=>{N.Qb||(N.Qb=Q(257));return O({target:a,lb:"pointerlockchange",ub:d,vb:(f=event)=>{var h=N.Qb,k=document.pointerLockElement;u[h]=!!k;var l=k?.id||"";P(ib(k),h+1,128);P(l,h+129,128);M(d)(20,h,b)&&f.preventDefault()},tb:c})},pb=(a,b,c,d)=>O({target:a,lb:"pointerlockerror",ub:d,vb:(f=event)=>{M(d)(38,0,b)&&f.preventDefault()},tb:c}),qb=(a,b,c,d)=>{N.Ub||
(N.Ub=Q(36));a=L(a);return O({target:a,lb:"resize",ub:d,vb:(f=event)=>{if(f.target==a){var h=document.body;if(h){var k=N.Ub;z[k>>2]=0;z[k+4>>2]=h.clientWidth;z[k+8>>2]=h.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;M(d)(10,k,b)&&f.preventDefault()}}},tb:c})},rb=(a,b,c,d,f,h)=>{N.Tb||(N.Tb=Q(1552));a=L(a);return O({target:a,Lb:"touchstart"==h||"touchend"==h,lb:h,ub:d,vb:k=>{var l={},m=k.touches;
for(var r of m)r.Yb=r.Zb=0,l[r.identifier]=r;for(var v of k.changedTouches)v.Yb=1,l[v.identifier]=v;for(var n of k.targetTouches)l[n.identifier].Zb=1;m=N.Tb;C[m>>3]=k.timeStamp;u[m+12]=k.ctrlKey;u[m+13]=k.shiftKey;u[m+14]=k.altKey;u[m+15]=k.metaKey;r=m+16;v=db(a);n=0;for(let q of Object.values(l))if(l=r>>2,z[l]=q.identifier,z[l+1]=q.screenX,z[l+2]=q.screenY,z[l+3]=q.clientX,z[l+4]=q.clientY,z[l+5]=q.pageX,z[l+6]=q.pageY,u[r+28]=q.Yb,u[r+29]=q.Zb,z[l+8]=q.clientX-(v.left|0),z[l+9]=q.clientY-(v.top|
0),r+=48,31<++n)break;z[m+8>>2]=n;M(d)(f,m,b)&&k.preventDefault()},tb:c})},sb=(a,b,c,d)=>{N.Vb||(N.Vb=Q(96));return O({target:a,Lb:!0,lb:"wheel",ub:d,vb:(f=event)=>{var h=N.Vb;mb(h,f,a);C[h+64>>3]=f.deltaX;C[h+72>>3]=f.deltaY;C[h+80>>3]=f.deltaZ;z[h+88>>2]=f.deltaMode;M(d)(9,h,b)&&f.preventDefault()},tb:c})},R=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=tb(b);P(a,c,b);return c},ub=[],S=(a,b)=>{ub[a>>>=0]=b},vb=[],U=a=>
{if(a)return ub[a>>>0]},wb=a=>{var b=A[a>>2];return b?K(b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?K(b,a):"";if(0===a)return""},xb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),yb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),zb=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},Ab=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,h=wb(f+4);c[h]=C[f+16>>3]}return c}},Bb=a=>a?U(a):"auto",
Ob=a=>{function b(d){if(d)return{operation:Cb[A[d>>2]],srcFactor:Db[A[d+4>>2]],dstFactor:Db[A[d+8>>2]]}}function c(d){return{compare:Eb[A[d>>2]],failOp:Fb[A[d+4>>2]],depthFailOp:Fb[A[d+8>>2]],passOp:Fb[A[d+12>>2]]}}return{label:V(a+4),layout:Bb(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),h=Ab(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var l=A[d+28>>2];if(k){for(var m=[],r=0;r<k;++r){var v=m,n=v.push;var q=l+24*r;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var J=null;else{J=4294967296*
A[q+4+8>>2]+A[q+8>>2];w=Gb[w];q=A[q+20>>2];for(var Hb=[],Sa=0;Sa<x;++Sa){var Ib=Hb,Ac=Ib.push;var T=q+24*Sa;T={format:Jb[A[T+4>>2]],offset:4294967296*A[T+4+8>>2]+A[T+8>>2],shaderLocation:A[T+16>>2]};Ac.call(Ib,T)}J={arrayStride:J,stepMode:w,attributes:Hb}}}else J=void 0;n.call(v,J)}k=m}else k=void 0;return{module:f,constants:h,buffers:k,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Kb[A[d+4>>2]],stripIndexFormat:Lb[A[d+8>>2]],frontFace:Mb[A[d+12>>2]],cullMode:Nb[A[d+16>>2]],
unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Eb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),h=
Ab(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],l=A[d+28>>2],m=[],r=0;r<k;++r){var v=m,n=v.push,q=l+24*r,w=A[q+4>>2];if(0===w)q=void 0;else{w=W[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}n.call(v,q)}return{module:f,constants:h,targets:m,entryPoint:V(d+8)}}}(A[a+92>>2])}},Pb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);
c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);qa[b+
72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",
144);void 0!==a.uc&&c("maxImmediateSize",148)},Qb=[,"clamp-to-edge","repeat","mirror-repeat"],Db=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Cb=[,"add","subtract","reverse-subtract","min","max"],Rb=["binding-not-used",,"uniform","storage","read-only-storage"],Eb=[,"never","less","equal","less-equal","greater",
"not-equal","greater-equal","always"],Sb=[,"opaque","premultiplied","unpremultiplied","inherit"],Nb=[,"none","front","back"],Tb=[,"compatibility","core"],Ub={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",
14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Vb=[,"nearest","linear"],Mb=[,"ccw","cw"],Lb=[,"uint16","uint32"],Wb=[,"load","clear"],Xb=[,"nearest","linear"],Yb=[,"low-power","high-performance"],Zb=[,"srgb","display-p3"],Kb=
[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],$b=["binding-not-used",,"filtering","non-filtering","comparison"],Fb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],ac=["binding-not-used",,"write-only","read-only","read-write"],bc=[,"store","discard"],cc=[,"all","stencil-only","depth-only"],dc=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm",
"rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8",
"bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb",
"astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],ec=["binding-not-used",
,"float","unfilterable-float","depth","sint","uint"],fc=[,"1d","2d","2d-array","cube","cube-array","3d"],gc=[,"standard","extended"],Jb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4",
"sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Gb=[,"vertex","instance"],hc={undefined:1,unknown:1,destroyed:2},ic=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";ic.Rb||(ic.Rb={});ic.Rb[a]||(ic.Rb[a]=1,ca&&(a="warning: "+a),g(a))},jc={rgba8unorm:22,bgra8unorm:27},kc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Na;e.pauseMainLoop=$a;e.resumeMainLoop=function(){Qa++;var a=Ja,b=Ka,c=G;G=null;Za(c,0,!1,Ra,!0);Pa(a,b);H()};e.preMainLoop&&Xa.push(e.preMainLoop);
e.postMainLoop&&Ya.push(e.postMainLoop);e.noExitRuntime&&(Ca=e.noExitRuntime);e.printErr&&(g=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var Q,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Y,tb,X,Sc={P:()=>sa(""),L:()=>{Ca=!1;Da=0},M:(a,b)=>{F[a]&&(clearTimeout(F[a].id),delete F[a]);if(!b)return 0;var c=setTimeout(()=>{delete F[a];Ia(()=>Qc(a,performance.now()))},b);F[a]={id:c,Dc:b};return 0},ua:()=>{$a();G=null},F:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,H:(a,b,c)=>{a=L(a);if(!a)return-4;a=db(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},wa:()=>performance.now(),
Ca:(a,b)=>{function c(d){M(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},O:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ra();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},n:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),E:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},o:(a,b,c,
d)=>jb(a,b,c,d,13,"focus"),m:(a,b,c,d)=>{if(!N.fullscreenEnabled())return-1;a=L(a);if(!a)return-4;kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},x:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),v:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),w:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),Da:(a,b,c)=>{a=M(a);Za(a,b,c)},D:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),A:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),z:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),B:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),C:(a,b,c,d)=>nb(a,b,c,d,6,
"mouseup"),q:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?ob(a,b,c,d):-4:-1,p:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?pb(a,b,c,d):-4:-1,G:(a,b,c,d)=>qb(a,b,c,d),r:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),s:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),t:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),u:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),y:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?sb(a,b,c,d):-1:-4,T:function(a,b,c,d,f,h){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>
c||9007199254740992<c?NaN:Number(c);a=U(a);var k={};if(h){var l=A[h+12>>2];if(l){var m=A[h+16>>2];k.requiredFeatures=Array.from(A.subarray(m>>2,m+4*l>>2),n=>Ub[n])}var r=A[h+20>>2];if(r){var v={};function n(w,x,J=!1){x=A[r+x>>2];4294967295==x||J&&0==x||(v[w]=x)}function q(w,x){x=r+x;var J=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=J)v[w]=4294967296*A[x+4>>2]+A[x>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",8);n("maxTextureDimension3D",12);n("maxTextureArrayLayers",16);n("maxBindGroups",
20);n("maxBindGroupsPlusVertexBuffers",24);n("maxDynamicUniformBuffersPerPipelineLayout",32);n("maxDynamicStorageBuffersPerPipelineLayout",36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);n("maxVertexBuffers",
88);q("maxBufferSize",96);n("maxVertexAttributes",104);n("maxVertexBufferArrayStride",108);n("maxInterStageShaderVariables",112);n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",148,!0);k.requiredLimits=v}if(l=A[h+24>>2])l={label:V(l+
4)},k.defaultQueue=l;k.label=V(h+4)}a.requestDevice(k).then(n=>{S(f,n.queue);S(d,n);c&&n.lost.then(q=>{n.onuncapturederror=()=>{};var w=X(),x=R(q.message);Mc(c,hc[q.reason],x);Y(w)});n.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=X();q=R(q.error.message);Pc(d,w,q);Y(x)};Oc(b,1,d,0)},n=>{var q=X();n=R(n.message);Oc(b,3,d,n);c&&Mc(c,4,n);Y(q)})},X:(a,b,c)=>{var d=U(a);0===c&&ic();-1==
c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(k){return 0}var h=Rc(16,f.byteLength);y.fill(0,h,f.byteLength);vb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(h,h+f.byteLength));lc(h)});return h},V:a=>{var b=U(a),c=vb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete vb[a];b.unmap()}},a:a=>{delete ub[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(h){return!1}S(c,f);d&&(vb[c]=
[]);return!0},S:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=wb(d+8)}S(c,U(a).createShaderModule(b))},U:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},Q:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return jc[a]},R:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Tb[A[c+4>>2]],powerPreference:Yb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Gc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(h=>
{if(h)S(d,h),Nc(b,1,d,0);else{h=X();var k=R("WebGPU not available on this browser (requestAdapter returned null)");Nc(b,3,d,k);Y(h)}},h=>{var k=X();h=R(h.message);Nc(b,4,d,h);Y(k)}):(f=X(),a=R("WebGPU not available on this browser (navigator.gpu is not available)"),Nc(b,3,d,a),Y(f))},K:Fa,Ma:function(){e.ac=a=>{0!=nc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.ac)},Ea:function(){e.fc=a=>{const b=a.clipboardData.getData("text");kc(()=>{const c=R(b);mc(c)})};
window.addEventListener("paste",e.fc)},xa:function(){e.Ac=[];e.bc=b=>{b.stopPropagation();b.preventDefault()};e.cc=b=>{b.stopPropagation();b.preventDefault()};e.dc=b=>{b.stopPropagation();b.preventDefault()};e.ec=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Bc=c;oc(c.length);for(let f=0;f<c.length;f++)kc(()=>{const h=R(c[f].name);pc(f,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);qc(b.clientX,b.clientY,d)};const a=e.wb;a.addEventListener("dragenter",
e.bc,!1);a.addEventListener("dragleave",e.cc,!1);a.addEventListener("dragover",e.dc,!1);a.addEventListener("drop",e.ec,!1)},Ka:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},N:function(a){e.Kb&&(URL.revokeObjectURL(e.Kb[a].lc),e.Kb[a]=null)},na:function(a,b){0!==b&&(document.title=b?K(b):"");a=a?K(a):"";void 0!==e.canvas&&("object"===typeof e.canvas?cb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.wb=L(a);
e.wb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.wb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},La:function(){window.removeEventListener("beforeunload",e.ac)},za:function(){window.removeEventListener("paste",e.fc)},va:function(){const a=e.wb;a.removeEventListener("dragenter",e.bc);a.removeEventListener("dragleave",e.cc);a.removeEventListener("dragover",e.dc);a.removeEventListener("drop",e.ec)},h:function(){e.wb&&e.wb.requestPointerLock&&
e.wb.requestPointerLock()},W:function(a,b,c){if(e.wb){if(0===b)a="none";else if(0!=c)a=e.Kb[a].nc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.wb.style.cursor=a}},Ja:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Fa:function(){return e.xb?e.xb.bufferSize:0},Ia:function(a,b,c){e.kb=null;e.xb=null;"undefined"!==typeof AudioContext?e.kb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.kb=null,console.log("sokol_audio.h: no WebAudio support"));
return e.kb?(console.log("sokol_audio.h: sample rate ",e.kb.sampleRate),e.xb=e.kb.createScriptProcessor(c,0,b),e.xb.onaudioprocess=d=>{const f=d.outputBuffer.length,h=sc(f);if(h){const k=d.outputBuffer.numberOfChannels;for(let l=0;l<k;l++){const m=d.outputBuffer.getChannelData(l);for(let r=0;r<f;r++)m[r]=B[(h>>2)+(k*r+l)]}}},e.xb.connect(e.kb.destination),a=()=>{e.kb&&"suspended"===e.kb.state&&e.kb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),
document.addEventListener("keydown",a,{once:!0}),1):0},Ga:function(){return e.kb?e.kb.sampleRate:0},Ha:function(){const a=e.kb;null!==a&&(e.xb&&e.xb.disconnect(),a.close(),e.kb=null,e.xb=null)},l:function(a,b,c,d,f,h){const k=b?K(b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(k,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=h?(y.set(m,f),uc(a,d,m.length)):wc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${k} failed with: `,
m);xc(a)}):vc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${k} failed with: `,l);xc(a)})},J:function(a,b){const c=b?K(b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),xc(a)):tc(a,Number(d))):vc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);xc(a)})},I:function(a,b){b=b?K(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);
break;case 2:console.warn(b);break;default:console.info(b)}},ya:(a,b)=>{Pb(U(a).limits,b);return 1},e:(a,b)=>U(a).features.has(Ub[b]),ka:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:zb(A[b+12>>2])});a=U(a);b=Dc(0);S(b,a.beginComputePass(c));return b},ja:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],h=A[b+16>>2],k=[],l=0;l<f;++l){var m=k,r=m.push;var v=h+56*l;var n=A[v+4>>2];if(0!==n){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:U(n),depthSlice:q,
resolveTarget:U(A[v+12>>2]),clearValue:xb(v+24),loadOp:Wb[A[v+16>>2]],storeOp:bc[A[v+20>>2]]}}else v=void 0;r.call(m,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Wb[A[f+8>>2]],depthStoreOp:bc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Wb[A[f+24>>2]],stencilStoreOp:bc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:zb(A[b+
28>>2]),maxDrawCount:d};a=U(a);d=Gc(0);S(d,a.beginRenderPass(b));return d},_:a=>{a=U(a);var b=Bc(0);S(b,a.finish());return b},$:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ia:(a,b)=>{U(a).setPipeline(U(b))},i:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var h=[],k=0;k<f;++k){var l=h,m=l.push;var r=b+40*k;var v=A[r+8>>2],n=A[r+32>>2],q=A[r+36>>2],w=A[r+4>>2];v?(n=r+24,n=A[n>>2]+4294967296*z[n+4>>2],-1==n&&(n=void 0),r={binding:w,
resource:{buffer:U(v),offset:4294967296*A[r+4+16>>2]+A[r+16>>2],size:n}}):r=n?{binding:w,resource:U(n)}:{binding:w,resource:U(q)};m.call(l,r)}c={label:c,layout:d,entries:h};a=U(a);d=yc(0);S(d,a.createBindGroup(c));return d},j:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],h=0;h<d;++h){var k=f,l=k.push,m=b+88*h,r=A[m+4>>2],v=A[m+8>>2];var n=m+24;var q=A[n+4>>2];n=q?{type:Rb[q],hasDynamicOffset:!!A[n+8>>2],minBindingSize:4294967296*A[n+4+16>>2]+A[n+16>>2]}:void 0;q=(q=A[m+48+4>>2])?{type:$b[q]}:
void 0;var w=m+56;var x=A[w+4>>2];w=x?{sampleType:ec[x],viewDimension:fc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;m+=72;m=(x=A[m+4>>2])?{access:ac[x],format:W[A[m+8>>2]],viewDimension:fc[A[m+12>>2]]}:void 0;l.call(k,{binding:r,visibility:v,buffer:n,sampler:q,texture:w,storageTexture:m})}c={label:c,entries:f};a=U(a);d=zc(0);S(d,a.createBindGroupLayout(c));return d},la:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=Cc(0);S(b,a.createCommandEncoder(c));return b},oa:(a,b)=>{var c=V(b+4);var d=Bb(A[b+
12>>2]);b=(b+=16)?{module:U(A[b+4>>2]),constants:Ab(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=Ec(0);S(d,a.createComputePipeline(c));return d},pa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],h=0;h<c;++h)f.push(U(A[d+4*h>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=Fc(0);S(c,a.createPipelineLayout(b));return c},ma:(a,b)=>{b=Ob(b);a=U(a);var c=Hc(0);S(c,a.createRenderPipeline(b));return c},qa:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Qb[A[b+
12>>2]],addressModeV:Qb[A[b+16>>2]],addressModeW:Qb[A[b+20>>2]],magFilter:Vb[A[b+24>>2]],minFilter:Vb[A[b+28>>2]],mipmapFilter:Xb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Eb[A[b+44>>2]],maxAnisotropy:pa[b+48>>1]});a=U(a);b=Ic(0);S(b,a.createSampler(c));return b},k:(a,b)=>{var c={label:V(b+4),size:yb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:dc[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>
2,b+4*d>>2),f=>W[f]));a=U(a);d=Kc(0);S(d,a.createTexture(c));return d},sa:(a,b)=>{Pb(U(a).limits,b);return 1},d:(a,b)=>U(a).features.has(Ub[b]),Ba:(a,b)=>{a=L(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Cc=V(b+4);b=Jc(0);S(b,a);return b},Z:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},Y:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},ra:(a,b,c,d,f,h)=>{var k=A[f+8>>2],l=A[f+12>>2],
m=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[m>>2],y:A[m+4>>2],z:A[m+8>>2]},aspect:cc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===k?void 0:k,rowsPerImage:4294967295===l?void 0:l},yb(h))},ba:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},ca:(a,b,c,d,f,h)=>{U(a).drawIndexed(b,c,d>>>0,f,h>>>0)},aa:a=>{U(a).end()},b:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ga:(a,b)=>{U(a).setBlendConstant(xb(b))},
ea:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Lb[c],d,f)},ha:(a,b)=>{U(a).setPipeline(U(b))},fa:(a,b)=>{U(a).setStencilReference(b>>>0)},da:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},Aa:(a,b)=>{var c=A[b+4>>2];a=
U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Sb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),h=>W[h])}b=A[b>>2];0!==b&&(c.colorSpace=Zb[A[b+8>>2]],c.Ec={mode:gc[A[b+12>>2]]});a.configure(c)},ta:(a,b)=>{a=U(a);try{var c=Kc(0);S(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=
A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:fc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:cc[A[b+36>>2]]}}a=U(a);b=Lc(0);S(b,a.createView(c));return b}};function Tc(a=[]){var b=rc;a.unshift(ea);var c=a.length,d=tb(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=R(k);f+=4});A[f>>2]=0;try{var h=b(c,d);Ga(h)}catch(k){Ea(k)}}
function Uc(a=da){function b(){e.calledRun=!0;if(!t){Z.Oa();e.onRuntimeInitialized?.();e.noInitialRun||Tc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();za.push(c)}ya(za)}}if(0<D)E=Uc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ba();ya(Aa);0<D?E=Uc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Z;
(async function(){function a(c){Z=c.exports;na=Z.Na;ra();fb=Z.Cb;c=Z;Q=c.Pa;lc=c.Qa;e.__sapp_emsc_onpaste=mc=c.Ra;e.__sapp_html5_get_ask_leave_site=nc=c.Sa;e.__sapp_emsc_begin_drop=oc=c.Ta;e.__sapp_emsc_drop=pc=c.Ua;e.__sapp_emsc_end_drop=qc=c.Va;e.__sapp_emsc_invoke_fetch_cb=c.Wa;e.__sapp_emsc_set_fullscreen_flag=c.Xa;e._main=rc=c.Ya;e.__saudio_emsc_pull=sc=c.Za;e.__sfetch_emsc_head_response=tc=c._a;e.__sfetch_emsc_get_response=uc=c.$a;e.__sfetch_emsc_failed_http_status=vc=c.ab;e.__sfetch_emsc_failed_buffer_too_small=
wc=c.bb;e.__sfetch_emsc_failed_other=xc=c.cb;yc=c.db;zc=c.eb;Bc=c.fb;Cc=c.gb;Dc=c.hb;Ec=c.ib;Fc=c.jb;Gc=c.nb;Hc=c.ob;Ic=c.pb;Jc=c.qb;Kc=c.rb;Lc=c.sb;Mc=c.yb;Nc=c.zb;Oc=c.Ab;Pc=c.Bb;Qc=c.Db;Rc=c.Eb;Y=c.Fb;tb=c.Gb;X=c.Hb;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Sc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ta??=e.locateFile?e.locateFile("plmpeg-sapp.wasm",ia):ia+"plmpeg-sapp.wasm";return a((await wa(b)).instance)})();
Uc();
