var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var g=console.error.bind(console),p,r=!1,ma,la=a=>a.startsWith("file://"),u,y,na,oa,z,A,B,C,pa;
function qa(){var a=ra.buffer;u=new Int8Array(a);na=new Int16Array(a);y=new Uint8Array(a);oa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);pa=new BigInt64Array(a);new BigUint64Array(a)}function sa(a){e.onAbort?.(a);a="Aborted("+a+")";g(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function xa(a){var b=ta;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(e)},Aa=[],Ba=[],Ca=()=>{var a=e.preRun.shift();Ba.push(a)},D=0,E=null,Da=!0,Ea=0,F={},Fa=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ga=a=>{ma=a;Da||0<Ea||(e.onExit?.(a),r=!0);fa(a,new ya(a))},Ha=()=>{if(!(Da||0<Ea))try{var a=ma;ma=a;Ga(a)}catch(b){Fa(b)}},G=a=>{if(!r)try{a(),Ha()}catch(b){Fa(b)}},Oa=(a,b)=>{Ia=a;Ja=b;if(H)if(Ka||=!0,0==a)I=function(){setTimeout(K,Math.max(0,La+b-performance.now())|0)};else if(1==a)I=function(){Ma(K)};else if(2==a){if(!Na)if(globalThis.setImmediate)Na=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Na=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}I=function(){Na(K)}}},Ya=(a,b,c,d,f)=>{function h(){return k<Pa?(Ha(),!1):!0}H=a;Qa=d;var k=Pa;Ka=!1;K=function(){if(!r)if(0<Sa.length){var l=Sa.shift();l.uc(l.lc);if(Ta){var m=
Ta,t=0==m%1?m-1:Math.floor(m);Ta=l.oc?t:(8*m+(t+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",m=Ta??0,t=Ua.tc??0,m?m<t?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));h()&&setTimeout(K,0)}else if(h())if(Va=Va+1|0,1==Ia&&1<Ja&&0!=Va%Ja)I();else{0==Ia&&(La=performance.now());a:if(!r){for(l of Wa)if(!1===l())break a;G(a);for(m of Xa)m()}h()&&I()}};f||(0<b?Oa(0,1E3/b):Oa(1,1),I());if(c)throw"unwind";},Ka=!1,I=null,Pa=0,H=null,Qa=0,Ia=0,Ja=0,Va=0,
Sa=[],Wa=[],Xa=[];function Za(){I=null;Pa++}var L=0;function Ma(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===L)L=b+1E3/60;else for(;b+2>=L;)L+=1E3/60;setTimeout(a,Math.max(L-b,0))}}
var Ua={},La,K,Na,Ta,$a=globalThis.TextDecoder&&new TextDecoder,M=(a=0,b)=>{var c=y;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&$a)return $a.decode(c.subarray(a,d));for(b="";a<d;){var f=c[a++];if(f&128){var h=c[a++]&63;if(192==(f&224))b+=String.fromCharCode((f&31)<<6|h);else{var k=c[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|c[a++]&63;65536>f?b+=String.fromCharCode(f):(f-=65536,b+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else b+=String.fromCharCode(f)}return b},
ab=[0,globalThis.document??0,globalThis.window??0],N=a=>{a=2<a?a?M(a):"":a;return ab[a]||globalThis.document?.querySelector(a)},bb=a=>0>ab.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},cb=[],O=a=>{var b=cb[a];b||(cb[a]=b=db.get(a));return b};function eb(a){var b=P.lb[a];b.target.removeEventListener(b.mb,b.Zb,b.vb);P.lb.splice(a,1)}function fb(){if(navigator.userActivation?navigator.userActivation.isActive:P.Qb&&P.jc.Nb){var a=P.Kb;P.Kb=[];for(var b of a)b.Ub(...b.Yb)}}
function Q(a){if(!a.target)return-4;if(a.tb)a.Zb=function(c){++P.Qb;P.jc=a;fb();a.xb(c);fb();--P.Qb},a.target.addEventListener(a.mb,a.Zb,a.vb),P.lb.push(a);else for(var b=0;b<P.lb.length;++b)P.lb[b].target==a.target&&P.lb[b].mb==a.mb&&eb(b--);return 0}function gb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={mc:0,vc:0,Rb:0,Lb:0,Xb:0,Wb:0,Ob:0,sc:0,xc:0,rc:0,Pb:0,Sb:0,Hc:0,Vb:0,yc(){for(;P.lb.length;)eb(P.lb.length-1);P.Kb=[]},Qb:0,Kb:[],qc(a,b,c){function d(h,k){if(h.length!=k.length)return!1;for(var l in h)if(h[l]!=k[l])return!1;return!0}for(var f of P.Kb)if(f.Ub==a&&d(f.Yb,c))return;P.Kb.push({Ub:a,bc:b,Yb:c});P.Kb.sort((h,k)=>h.bc<k.bc)},Ac(a){P.Kb=P.Kb.filter(b=>b.Ub!=a)},lb:[],zc:(a,b)=>{for(var c=0;c<P.lb.length;++c)P.lb[c].target!=a||b&&b!=P.lb[c].mb||eb(c--)},Bc(a){let b=!1;for(let c=0;c<
P.lb.length;++c){const d=P.lb[c];d.target===a.target&&d.ub===a.ub&&d.tb===a.tb&&d.wb===a.wb&&(eb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},R=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;
d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;f++}}d[b]=0}},hb=(a,b,c,d,f,h)=>{P.Ob||(P.Ob=S(256));a={target:N(a),mb:h,ub:f,wb:b,tb:d,xb:k=>{var l=k.target.id?k.target.id:"",m=P.Ob;R(gb(k.target),m+0,128);R(l,m+128,128);O(d)(f,m,b)&&k.preventDefault()},vb:c};return Q(a)},ib=(a,b,c,d,f)=>{P.Pb||(P.Pb=S(276));return Q({target:a,mb:f,ub:19,wb:b,tb:d,xb:h=>{var k=P.Pb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,m=!!l;u[k]=m;u[k+1]=P.fullscreenEnabled();var t=m?l:P.kc,v=t?.id||"";R(gb(t),k+2,128);R(v,k+130,128);z[k+260>>2]=t?t.clientWidth:0;z[k+264>>2]=t?t.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;m&&(P.kc=l);O(d)(19,k,b)&&h.preventDefault()},vb:c})},jb=(a,b,c,d,f,h)=>{P.Rb||(P.Rb=S(160));a={target:N(a),mb:h,ub:f,wb:b,tb:d,xb:k=>{var l=P.Rb;C[l>>3]=k.timeStamp;var m=l>>2;z[m+2]=k.location;u[l+12]=k.ctrlKey;u[l+13]=k.shiftKey;u[l+14]=k.altKey;u[l+15]=k.metaKey;
u[l+16]=k.repeat;z[m+5]=k.charCode;z[m+6]=k.keyCode;z[m+7]=k.which;R(k.key||"",l+32,32);R(k.code||"",l+64,32);R(k.char||"",l+96,32);R(k.locale||"",l+128,32);O(d)(f,l,b)&&k.preventDefault()},vb:c};return Q(a)},kb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;na[2*d+14]=b.button;na[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=bb(c);z[d+10]=b.clientX-(a.left|
0);z[d+11]=b.clientY-(a.top|0)},lb=(a,b,c,d,f,h)=>{P.Lb||(P.Lb=S(64));a=N(a);return Q({target:a,Nb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,mb:h,ub:f,wb:b,tb:d,xb:k=>{kb(P.Lb,k,a);O(d)(f,P.Lb,b)&&k.preventDefault()},vb:c})},mb=(a,b,c,d)=>{P.Sb||(P.Sb=S(257));return Q({target:a,mb:"pointerlockchange",ub:20,wb:b,tb:d,xb:f=>{var h=P.Sb,k=document.pointerLockElement;u[h]=!!k;var l=k?.id||"";R(gb(k),h+1,128);R(l,h+129,128);O(d)(20,h,b)&&f.preventDefault()},vb:c})},nb=(a,b,c,d)=>Q({target:a,mb:"pointerlockerror",
ub:38,wb:b,tb:d,xb:f=>{O(d)(38,0,b)&&f.preventDefault()},vb:c}),ob=(a,b,c,d)=>{P.Wb||(P.Wb=S(36));a=N(a);return Q({target:a,mb:"resize",ub:10,wb:b,tb:d,xb:f=>{if(f.target==a){var h=document.body;if(h){var k=P.Wb;z[k>>2]=0;z[k+4>>2]=h.clientWidth;z[k+8>>2]=h.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;O(d)(10,k,b)&&f.preventDefault()}}},vb:c})},pb=(a,b,c,d,f,h)=>{P.Vb||(P.Vb=S(1552));a=N(a);
return Q({target:a,Nb:"touchstart"==h||"touchend"==h,mb:h,ub:f,wb:b,tb:d,xb:k=>{var l={},m=k.touches;for(var t of m)t.$b=t.ac=0,l[t.identifier]=t;for(var v of k.changedTouches)v.$b=1,l[v.identifier]=v;for(var n of k.targetTouches)l[n.identifier].ac=1;m=P.Vb;C[m>>3]=k.timeStamp;u[m+12]=k.ctrlKey;u[m+13]=k.shiftKey;u[m+14]=k.altKey;u[m+15]=k.metaKey;t=m+16;v=bb(a);n=0;for(let q of Object.values(l))if(l=t>>2,z[l]=q.identifier,z[l+1]=q.screenX,z[l+2]=q.screenY,z[l+3]=q.clientX,z[l+4]=q.clientY,z[l+5]=
q.pageX,z[l+6]=q.pageY,u[t+28]=q.$b,u[t+29]=q.ac,z[l+8]=q.clientX-(v.left|0),z[l+9]=q.clientY-(v.top|0),t+=48,31<++n)break;z[m+8>>2]=n;O(d)(f,m,b)&&k.preventDefault()},vb:c})},qb=(a,b,c,d)=>{P.Xb||(P.Xb=S(96));return Q({target:a,Nb:!0,mb:"wheel",ub:9,wb:b,tb:d,xb:f=>{var h=P.Xb;kb(h,f,a);C[h+64>>3]=f.deltaX;C[h+72>>3]=f.deltaY;C[h+80>>3]=f.deltaZ;z[h+88>>2]=f.deltaMode;O(d)(9,h,b)&&f.preventDefault()},vb:c})},T=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=
d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=rb(b);R(a,c,b);return c},U=[],sb=(a,b)=>{U[a>>>0]=b},tb=[],V=a=>{if(a)return U[a>>>0]},ub=a=>{var b=A[a>>2];return b?M(b,A[a+4>>2]):""},W=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?M(b,a):"";if(0===a)return""},vb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),wb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),xb=a=>{if(0!==a)return{querySet:V(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},yb=(a,b)=>{if(a){for(var c=
{},d=0;d<a;++d){var f=b+24*d,h=ub(f+4);c[h]=C[f+16>>3]}return c}},zb=a=>a?V(a):"auto",Mb=a=>{function b(d){if(d)return{operation:Ab[A[d>>2]],srcFactor:Bb[A[d+4>>2]],dstFactor:Bb[A[d+8>>2]]}}function c(d){return{compare:Cb[A[d>>2]],failOp:Db[A[d+4>>2]],depthFailOp:Db[A[d+8>>2]],passOp:Db[A[d+12>>2]]}}return{label:W(a+4),layout:zb(A[a+12>>2]),vertex:function(d){if(d){var f=V(A[d+4>>2]),h=yb(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var l=A[d+28>>2];if(k){for(var m=[],t=0;t<k;++t){var v=m,n=v.push;var q=
l+24*t;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var J=null;else{J=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Eb[w];q=A[q+20>>2];for(var Gb=[],Ra=0;Ra<x;++Ra){var Hb=Gb,va=q+24*Ra;Hb.push.call(Hb,{format:Fb[A[va+4>>2]],offset:4294967296*A[va+4+8>>2]+A[va+8>>2],shaderLocation:A[va+16>>2]})}J={arrayStride:J,stepMode:w,attributes:Gb}}}else J=void 0;n.call(v,J)}k=m}else k=void 0;return{module:f,constants:h,buffers:k,entryPoint:W(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Ib[A[d+4>>2]],
stripIndexFormat:Jb[A[d+8>>2]],frontFace:Kb[A[d+12>>2]],cullMode:Lb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:X[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Cb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+
12>>2]}}(a+76),fragment:function(d){if(d){for(var f=V(A[d+4>>2]),h=yb(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],l=A[d+28>>2],m=[],t=0;t<k;++t){var v=m,n=v.push,q=l+24*t,w=A[q+4>>2];if(0===w)q=void 0;else{w=X[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}n.call(v,q)}return{module:f,constants:h,targets:m,entryPoint:W(d+8)}}}(A[a+92>>2])}},Nb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",
12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);
pa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);pa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);pa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",
140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.wc&&c("maxImmediateSize",148)},Ob=[,"clamp-to-edge","repeat","mirror-repeat"],Bb=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Ab=[,"add","subtract","reverse-subtract","min","max"],Pb=["binding-not-used",,"uniform","storage","read-only-storage"],Cb=
[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Qb=[,"opaque","premultiplied","unpremultiplied","inherit"],Lb=[,"none","front","back"],Rb=[,"compatibility","core"],Sb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",
12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Tb=[,"nearest","linear"],Kb=[,"ccw","cw"],Jb=[,"uint16","uint32"],Ub=[,"load","clear"],Vb=[,"nearest",
"linear"],Wb=[,"low-power","high-performance"],Xb=[,"srgb","display-p3"],Ib=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],Yb=["binding-not-used",,"filtering","non-filtering","comparison"],Db=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],Zb=["binding-not-used",,"write-only","read-only","read-write"],$b=[,"store","discard"],ac=[,"all","stencil-only","depth-only"],bc=[,"1d","2d","3d"],X=[,"r8unorm","r8snorm","r8uint",
"r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8",
"depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm",
"eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm",
"astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],cc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],dc=[,"1d","2d","2d-array","cube","cube-array","3d"],ec=[,"standard","extended"],Fb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4",
"float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Eb=[,"vertex","instance"],fc={undefined:1,unknown:1,destroyed:2},gc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";gc.Tb||(gc.Tb={});gc.Tb[a]||(gc.Tb[a]=1,ca&&(a="warning: "+a),g(a))},hc={rgba8unorm:22,bgra8unorm:27},ic=a=>{var b=Y();a();Z(b)};e.requestAnimationFrame=Ma;e.pauseMainLoop=Za;
e.resumeMainLoop=function(){Pa++;var a=Ia,b=Ja,c=H;H=null;Ya(c,0,!1,Qa,!0);Oa(a,b);I()};e.preMainLoop&&Wa.push(e.preMainLoop);e.postMainLoop&&Xa.push(e.postMainLoop);e.noExitRuntime&&(Da=e.noExitRuntime);e.printErr&&(g=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var S,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Z,rb,Y,ra,db,Pc={Q:()=>sa(""),M:()=>{Da=!1;Ea=0},N:(a,b)=>{F[a]&&(clearTimeout(F[a].id),delete F[a]);if(!b)return 0;var c=setTimeout(()=>{delete F[a];G(()=>Nc(a,performance.now()))},b);F[a]={id:c,Fc:b};return 0},ua:()=>{Za();H=null},G:()=>globalThis.devicePixelRatio??1,I:(a,b,c)=>{a=N(a);if(!a)return-4;a=bb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},wa:()=>performance.now(),Ca:(a,b)=>{function c(d){O(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},P:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);qa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},o:(a,b,c,d)=>hb(a,b,c,d,12,"blur"),F:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},p:(a,b,c,d)=>hb(a,b,c,d,13,"focus"),n:(a,
b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=N(a);if(!a)return-4;ib(a,b,c,d,"webkitfullscreenchange");return ib(a,b,c,d,"fullscreenchange")},y:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),w:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),x:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),Da:(a,b,c)=>{a=O(a);Ya(a,b,c)},E:(a,b,c,d)=>lb(a,b,c,d,5,"mousedown"),B:(a,b,c,d)=>lb(a,b,c,d,33,"mouseenter"),A:(a,b,c,d)=>lb(a,b,c,d,34,"mouseleave"),C:(a,b,c,d)=>lb(a,b,c,d,8,"mousemove"),D:(a,b,c,d)=>lb(a,b,c,d,6,"mouseup"),r:(a,b,c,d)=>document.body?.requestPointerLock?
(a=N(a))?mb(a,b,c,d):-4:-1,q:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?nb(a,b,c,d):-4:-1,H:(a,b,c,d)=>ob(a,b,c,d),s:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),t:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),u:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),v:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),z:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?qb(a,b,c,d):-1:-4,U:function(a,b,c,d,f,h){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=V(a);
var k={};if(h){var l=A[h+12>>2];if(l){var m=A[h+16>>2];k.requiredFeatures=Array.from(A.subarray(m>>2,m+4*l>>2),n=>Sb[n])}var t=A[h+20>>2];if(t){var v={};function n(w,x,J=!1){x=A[t+x>>2];4294967295==x||J&&0==x||(v[w]=x)}function q(w,x){x=t+x;var J=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=J)v[w]=4294967296*A[x+4>>2]+A[x>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",8);n("maxTextureDimension3D",12);n("maxTextureArrayLayers",16);n("maxBindGroups",20);n("maxBindGroupsPlusVertexBuffers",
24);n("maxDynamicUniformBuffersPerPipelineLayout",32);n("maxDynamicStorageBuffersPerPipelineLayout",36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);n("maxVertexBuffers",88);q("maxBufferSize",96);n("maxVertexAttributes",
104);n("maxVertexBufferArrayStride",108);n("maxInterStageShaderVariables",112);n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",148,!0);k.requiredLimits=v}if(l=A[h+24>>2])l={label:W(l+4)},k.defaultQueue=l;k.label=W(h+4)}a.requestDevice(k).then(n=>
{G(()=>{U[f>>>0]=n.queue;U[d>>>0]=n;n.lost.then(q=>{G(()=>{n.onuncapturederror=()=>{};var w=Y(),x=T(q.message);Jc(c,fc[q.reason],x);Z(w)})});n.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=Y();q=T(q.error.message);Mc(d,w,q);Z(x)};Lc(b,1,d,0)})},n=>{G(()=>{var q=Y(),w=T(n.message);Lc(b,3,d,w);c&&Jc(c,4,w);Z(q)})})},Y:(a,b,c)=>{var d=V(a);0===c&&gc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,
c)}catch(k){return 0}var h=Oc(16,f.byteLength);y.fill(0,h,f.byteLength);tb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(h,h+f.byteLength));jc(h)});return h},W:a=>{var b=V(a),c=tb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete tb[a];b.unmap()}},a:a=>{delete U[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:W(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=V(a);try{var f=a.createBuffer(b)}catch(h){return!1}U[c>>>0]=f;d&&(tb[c]=[]);return!0},T:(a,b,c)=>{var d=A[b>>
2],f=A[d+4>>2];b={label:W(b+4),code:""};switch(f){case 2:b.code=ub(d+8)}a=V(a).createShaderModule(b);U[c>>>0]=a},V:a=>{a=V(a);a.onuncapturederror=null;a.destroy()},R:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return hc[a]},S:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Rb[A[c+4>>2]],powerPreference:Wb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Ic=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(h=>
{G(()=>{if(h)U[d>>>0]=h,Kc(b,1,d,0);else{var k=Y(),l=T("WebGPU not available on this browser (requestAdapter returned null)");Kc(b,3,d,l);Z(k)}})},h=>{G(()=>{var k=Y(),l=T(h.message);Kc(b,4,d,l);Z(k)})}):(f=Y(),a=T("WebGPU not available on this browser (navigator.gpu is not available)"),Kc(b,3,d,a),Z(f))},L:Ga,Ma:function(){e.cc=a=>{0!=lc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.cc)},Ea:function(){e.ic=a=>{const b=a.clipboardData.getData("text");ic(()=>{const c=
T(b);kc(c)})};window.addEventListener("paste",e.ic)},xa:function(){e.Cc=[];e.dc=b=>{b.stopPropagation();b.preventDefault()};e.ec=b=>{b.stopPropagation();b.preventDefault()};e.fc=b=>{b.stopPropagation();b.preventDefault()};e.hc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Dc=c;mc(c.length);for(let f=0;f<c.length;f++)ic(()=>{const h=T(c[f].name);nc(f,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);oc(b.clientX,b.clientY,d)};const a=e.Ib;
a.addEventListener("dragenter",e.dc,!1);a.addEventListener("dragleave",e.ec,!1);a.addEventListener("dragover",e.fc,!1);a.addEventListener("drop",e.hc,!1)},Ka:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},O:function(a){e.Mb&&(URL.revokeObjectURL(e.Mb[a].nc),e.Mb[a]=null)},na:function(a,b){0!==b&&(document.title=b?M(b):"");a=a?M(a):"";void 0!==e.canvas&&("object"===typeof e.canvas?ab[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
e.Ib=N(a);e.Ib||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.Ib.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},La:function(){window.removeEventListener("beforeunload",e.cc)},za:function(){window.removeEventListener("paste",e.ic)},va:function(){const a=e.Ib;a.removeEventListener("dragenter",e.dc);a.removeEventListener("dragleave",e.ec);a.removeEventListener("dragover",e.fc);a.removeEventListener("drop",e.hc)},h:function(){e.Ib&&
e.Ib.requestPointerLock&&e.Ib.requestPointerLock()},X:function(a,b,c){if(e.Ib){if(0===b)a="none";else if(0!=c)a=e.Mb[a].pc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.Ib.style.cursor=a}},Ja:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Fa:function(){return e.Jb?e.Jb.bufferSize:0},Ia:function(a,b,c){e.kb=null;e.Jb=null;"undefined"!==typeof AudioContext?e.kb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.kb=null,console.log("sokol_audio.h: no WebAudio support"));
return e.kb?(console.log("sokol_audio.h: sample rate ",e.kb.sampleRate),e.Jb=e.kb.createScriptProcessor(c,0,b),e.Jb.onaudioprocess=d=>{const f=d.outputBuffer.length,h=qc(f);if(h){const k=d.outputBuffer.numberOfChannels;for(let l=0;l<k;l++){const m=d.outputBuffer.getChannelData(l);for(let t=0;t<f;t++)m[t]=B[(h>>2)+(k*t+l)]}}},e.Jb.connect(e.kb.destination),a=()=>{e.kb&&"suspended"===e.kb.state&&e.kb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),
document.addEventListener("keydown",a,{once:!0}),1):0},Ga:function(){return e.kb?e.kb.sampleRate:0},Ha:function(){const a=e.kb;null!==a&&(e.Jb&&e.Jb.disconnect(),a.close(),e.kb=null,e.Jb=null)},j:function(a,b,c,d,f,h){const k=b?M(b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(k,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=h?(y.set(m,f),sc(a,d,m.length)):uc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${k} failed with: `,
m);vc(a)}):tc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${k} failed with: `,l);vc(a)})},K:function(a,b){const c=b?M(b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),vc(a)):rc(a,Number(d))):tc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);vc(a)})},J:function(a,b){b=b?M(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);
break;case 2:console.warn(b);break;default:console.info(b)}},ya:(a,b)=>{Nb(V(a).limits,b);return 1},e:(a,b)=>V(a).features.has(Sb[b]),ka:(a,b)=>{var c;b&&(c={label:W(b+4),timestampWrites:xb(A[b+12>>2])});b=V(a);a=Ac(0);c=b.beginComputePass(c);U[a>>>0]=c;return a},ja:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=W(b+4);for(var f=A[b+12>>2],h=A[b+16>>2],k=[],l=0;l<f;++l){var m=k,t=m.push;var v=h+56*l;var n=A[v+4>>2];if(0!==n){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:V(n),
depthSlice:q,resolveTarget:V(A[v+12>>2]),clearValue:vb(v+24),loadOp:Ub[A[v+16>>2]],storeOp:$b[A[v+20>>2]]}}else v=void 0;t.call(m,v)}f=A[b+20>>2];f=0!==f?{view:V(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Ub[A[f+8>>2]],depthStoreOp:$b[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Ub[A[f+24>>2]],stencilStoreOp:$b[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:V(A[b+24>>2]),timestampWrites:xb(A[b+
28>>2]),maxDrawCount:d};d=V(a);a=Dc(0);b=d.beginRenderPass(b);U[a>>>0]=b;return a},$:a=>{var b=V(a);a=yc(0);b=b.finish();U[a>>>0]=b;return a},aa:a=>{V(a).end()},c:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ia:(a,b)=>{V(a).setPipeline(V(b))},l:(a,b)=>{var c=W(b+4),d=V(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var h=[],k=0;k<f;++k){var l=h,m=l.push;var t=b+40*k;var v=A[t+8>>2],n=A[t+32>>2],q=A[t+36>>2],w=A[t+4>>2];v?(n=t+24,n=A[n>>2]+4294967296*z[n+4>>2],-1==
n&&(n=void 0),t={binding:w,resource:{buffer:V(v),offset:4294967296*A[t+4+16>>2]+A[t+16>>2],size:n}}):t=n?{binding:w,resource:V(n)}:{binding:w,resource:V(q)};m.call(l,t)}c={label:c,layout:d,entries:h};d=V(a);a=wc(0);c=d.createBindGroup(c);U[a>>>0]=c;return a},m:(a,b)=>{var c=W(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],h=0;h<d;++h){var k=f,l=k.push,m=b+88*h,t=A[m+4>>2],v=A[m+8>>2];var n=m+24;var q=A[n+4>>2];n=q?{type:Pb[q],hasDynamicOffset:!!A[n+8>>2],minBindingSize:4294967296*A[n+4+16>>2]+A[n+16>>
2]}:void 0;q=(q=A[m+48+4>>2])?{type:Yb[q]}:void 0;var w=m+56;var x=A[w+4>>2];w=x?{sampleType:cc[x],viewDimension:dc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;m+=72;m=(x=A[m+4>>2])?{access:Zb[x],format:X[A[m+8>>2]],viewDimension:dc[A[m+12>>2]]}:void 0;l.call(k,{binding:t,visibility:v,buffer:n,sampler:q,texture:w,storageTexture:m})}c={label:c,entries:f};d=V(a);a=xc(0);c=d.createBindGroupLayout(c);U[a>>>0]=c;return a},la:(a,b)=>{var c;b&&(c={label:W(b+4)});b=V(a);a=zc(0);c=b.createCommandEncoder(c);
U[a>>>0]=c;return a},oa:(a,b)=>{var c=W(b+4);var d=zb(A[b+12>>2]);b=(b+=16)?{module:V(A[b+4>>2]),constants:yb(A[b+16>>2],A[b+20>>2]),entryPoint:W(b+8)}:void 0;c={label:c,layout:d,compute:b};d=V(a);a=Bc(0);c=d.createComputePipeline(c);U[a>>>0]=c;return a},pa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],h=0;h<c;++h)f.push(V(A[d+4*h>>2]));b={label:W(b+4),bindGroupLayouts:f};c=V(a);a=Cc(0);b=c.createPipelineLayout(b);U[a>>>0]=b;return a},ma:(a,b)=>{b=Mb(b);var c=V(a);a=Ec(0);b=c.createRenderPipeline(b);
U[a>>>0]=b;return a},qa:(a,b)=>{var c;b&&(c={label:W(b+4),addressModeU:Ob[A[b+12>>2]],addressModeV:Ob[A[b+16>>2]],addressModeW:Ob[A[b+20>>2]],magFilter:Tb[A[b+24>>2]],minFilter:Tb[A[b+28>>2]],mipmapFilter:Vb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Cb[A[b+44>>2]],maxAnisotropy:oa[b+48>>1]});b=V(a);a=Fc(0);c=b.createSampler(c);U[a>>>0]=c;return a},i:(a,b)=>{var c={label:W(b+4),size:wb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:bc[A[b+24>>2]],format:X[A[b+
40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>X[f]));a=V(a);d=Hc(0);sb(d,a.createTexture(c));return d},sa:(a,b)=>{Nb(V(a).limits,b);return 1},d:(a,b)=>V(a).features.has(Sb[b]),Ba:(a,b)=>{a=N(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Ec=W(b+4);b=Gc(0);U[b>>>0]=a;return b},_:(a,b,c)=>{a=V(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>V(d));a.submit(b)},Z:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);
V(a).writeBuffer(V(b),c,y.subarray(d,d+f),0,f)},ra:(a,b,c,d,f,h)=>{var k=A[f+8>>2],l=A[f+12>>2],m=b+8;V(a).writeTexture({texture:V(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[m>>2],y:A[m+4>>2],z:A[m+8>>2]},aspect:ac[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===k?void 0:k,rowsPerImage:4294967295===l?void 0:l},wb(h))},ca:(a,b,c,d,f)=>{V(a).draw(b,c,d>>>0,f>>>0)},da:(a,b,c,d,f,h)=>{V(a).drawIndexed(b,c,d>>>0,f,h>>>0)},ba:a=>{V(a).end()},b:(a,b,c,d,f)=>{a=V(a);
c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ga:(a,b)=>{V(a).setBlendConstant(vb(b))},ea:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);b=V(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Jb[c],d,f)},ha:(a,b)=>{V(a).setPipeline(V(b))},fa:(a,b)=>{V(a).setStencilReference(b>>>0)},k:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:
Number(f);a=V(a);c=V(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},Aa:(a,b)=>{var c=A[b+4>>2];a=V(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:V(c),format:X[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Qb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),h=>X[h])}b=A[b>>2];0!==b&&(c.colorSpace=Xb[A[b+8>>2]],c.Gc={mode:ec[A[b+12>>2]]});a.configure(c)},ta:(a,b)=>{a=V(a);try{var c=Hc(0),d=a.getCurrentTexture();
U[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:W(b+4),format:X[A[b+12>>2]],dimension:dc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:ac[A[b+36>>2]]}}b=V(a);a=Ic(0);b=b.createView(c);U[a>>>0]=b;return a}};
function Qc(a=[]){var b=pc;a.unshift(ea);var c=a.length,d=rb(4*(c+1)),f=d,h;for(h of a)A[f>>2]=T(h),f+=4;A[f>>2]=0;try{var k=b(c,d);ma=k;Ga(k)}catch(l){Fa(l)}}
function Rc(a=da){function b(){e.calledRun=!0;if(!r){Sc.Oa();e.onRuntimeInitialized?.();e.noInitialRun||Qc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Aa.push(c)}za(Aa)}}if(0<D)E=Rc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ca();za(Ba);0<D?E=Rc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Sc;
(async function(){function a(c){c=Sc=c.exports;S=c.Pa;jc=c.Qa;kc=e.__sapp_emsc_onpaste=c.Ra;lc=e.__sapp_html5_get_ask_leave_site=c.Sa;mc=e.__sapp_emsc_begin_drop=c.Ta;nc=e.__sapp_emsc_drop=c.Ua;oc=e.__sapp_emsc_end_drop=c.Va;e.__sapp_emsc_invoke_fetch_cb=c.Wa;e.__sapp_emsc_set_fullscreen_flag=c.Xa;pc=e._main=c.Ya;qc=e.__saudio_emsc_pull=c.Za;rc=e.__sfetch_emsc_head_response=c._a;sc=e.__sfetch_emsc_get_response=c.$a;tc=e.__sfetch_emsc_failed_http_status=c.ab;uc=e.__sfetch_emsc_failed_buffer_too_small=
c.bb;vc=e.__sfetch_emsc_failed_other=c.cb;wc=c.db;xc=c.eb;yc=c.fb;zc=c.gb;Ac=c.hb;Bc=c.ib;Cc=c.jb;Dc=c.nb;Ec=c.ob;Fc=c.pb;Gc=c.qb;Hc=c.rb;Ic=c.sb;Jc=c.yb;Kc=c.zb;Lc=c.Ab;Mc=c.Bb;Nc=c.Db;Oc=c.Eb;Z=c.Fb;rb=c.Gb;Y=c.Hb;ra=c.Na;db=c.Cb;qa();D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Sc}D++;e.monitorRunDependencies?.(D);var b={a:Pc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ta??=e.locateFile?e.locateFile("plmpeg-sapp.wasm",ia):ia+"plmpeg-sapp.wasm";
return a((await xa(b)).instance)})();Rc();
