var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),g=console.error.bind(console),p,t=!1,na,la=a=>a.startsWith("file://"),oa,u,y,pa,qa,z,A,B,C,ra;
function sa(){var a=oa.buffer;u=new Int8Array(a);pa=new Int16Array(a);y=new Uint8Array(a);qa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var D=0,E=null;function ta(a){e.onAbort?.(a);a="Aborted("+a+")";g(a);t=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function wa(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=ua;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},Ea=!0,Fa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|k);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|h:(f&7)<<18|k<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ga=0,G={},Ha=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ia=a=>{na=a;Ea||0<Ga||(e.onExit?.(a),t=!0);fa(a,new za(a))},Ja=a=>{na=a;Ia(a)},Ka=()=>{if(!(Ea||0<Ga))try{var a=na;na=a;Ia(a)}catch(b){Ha(b)}},La=a=>{if(!t)try{a(),Ka()}catch(b){Ha(b)}},Ta=(a,b)=>{Ma=a;Na=b;if(H)if(Oa||=!0,0==a)I=function(){setTimeout(J,Math.max(0,Pa+b-performance.now())|0)};else if(1==a)I=function(){Qa(J)};else if(2==a){if("undefined"==
typeof Ra)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ra=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ra=setImmediate;I=function(){Ra(J)}}},bb=(a,b,c,d,f)=>{function k(){return h<Ua?(Ka(),!1):!0}H=a;Va=d;var h=Ua;Oa=!1;J=function(){if(!t)if(0<Wa.length){var l=
Wa.shift();l.Cc(l.tc);if(Xa){var m=Xa,q=0==m%1?m-1:Math.floor(m);Xa=l.wc?q:(8*m+(q+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",m=Xa??0,q=Ya.Bc??0,m?m<q?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));k()&&setTimeout(J,0)}else if(k())if(Za=Za+1|0,1==Ma&&1<Na&&0!=Za%Na)I();else{0==Ma&&(Pa=performance.now());a:if(!t){for(l of $a)if(!1===l())break a;La(a);for(m of ab)m()}k()&&I()}};f||(0<b?Ta(0,1E3/b):Ta(1,1),I());if(c)throw"unwind";},Oa=!1,I=
null,Ua=0,H=null,Va=0,Ma=0,Na=0,Za=0,Wa=[],$a=[],ab=[];function cb(){I=null;Ua++}var L=0;function Qa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===L)L=b+1E3/60;else for(;b+2>=L;)L+=1E3/60;setTimeout(a,Math.max(L-b,0))}}
var Ya={},Pa,J,Ra,Xa,db=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?F(y,a):"":a;return db[a]||("undefined"!=typeof document?document.querySelector(a):null)},eb=a=>0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},fb=[],gb,N=a=>{var b=fb[a];b||(fb[a]=b=gb.get(a));return b};function hb(a){var b=O.wb[a];b.target.removeEventListener(b.vb,b.hc,b.xb);O.wb.splice(a,1)}
function ib(){if(navigator.userActivation?navigator.userActivation.isActive:O.Yb&&O.rc.Vb){var a=O.Ib;O.Ib=[];for(var b of a)b.bc(...b.fc)}}function P(a){if(!a.target)return-4;if(a.Eb)a.hc=function(c){++O.Yb;O.rc=a;ib();a.Fb(c);ib();--O.Yb},a.target.addEventListener(a.vb,a.hc,a.xb),O.wb.push(a);else for(var b=0;b<O.wb.length;++b)O.wb[b].target==a.target&&O.wb[b].vb==a.vb&&hb(b--);return 0}function jb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var O={uc:0,Dc:0,Zb:0,Tb:0,ec:0,dc:0,Wb:0,Ac:0,Gc:0,zc:0,Xb:0,$b:0,Pc:0,cc:0,Fc(a,b,c){u.set(u.subarray(b,b+c),a)},Hc(){for(;O.wb.length;)hb(O.wb.length-1);O.Ib=[]},Yb:0,Ib:[],yc(a,b,c){function d(k,h){if(k.length!=h.length)return!1;for(var l in k)if(k[l]!=h[l])return!1;return!0}for(var f of O.Ib)if(f.bc==a&&d(f.fc,c))return;O.Ib.push({bc:a,kc:b,fc:c});O.Ib.sort((k,h)=>k.kc<h.kc)},Jc(a){O.Ib=O.Ib.filter(b=>b.bc!=a)},wb:[],Ic:(a,b)=>{for(var c=0;c<O.wb.length;++c)O.wb[c].target!=a||b&&b!=O.wb[c].vb||
hb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Q=(a,b,c)=>{var d=y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var k=0;k<a.length;++k){var h=a.codePointAt(k);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;k++}}d[b]=0;return b-
f},kb=(a,b,c,d,f,k)=>{O.Wb||(O.Wb=R(256));a={target:M(a),vb:k,Eb:d,Fb:(h=event)=>{var l=h.target.id?h.target.id:"",m=O.Wb;Q(jb(h.target),m+0,128);Q(l,m+128,128);N(d)(f,m,b)&&h.preventDefault()},xb:c};return P(a)},lb=(a,b,c,d,f)=>{O.Xb||(O.Xb=R(276));return P({target:a,vb:f,Eb:d,Fb:(k=event)=>{var h=O.Xb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,m=!!l;u[h]=m;u[h+1]=O.fullscreenEnabled();
var q=m?l:O.sc,v=q?.id||"";Q(jb(q),h+2,128);Q(v,h+130,128);z[h+260>>2]=q?q.clientWidth:0;z[h+264>>2]=q?q.clientHeight:0;z[h+268>>2]=screen.width;z[h+272>>2]=screen.height;m&&(O.sc=l);N(d)(19,h,b)&&k.preventDefault()},xb:c})},mb=(a,b,c,d,f,k)=>{O.Zb||(O.Zb=R(160));a={target:M(a),vb:k,Eb:d,Fb:h=>{var l=O.Zb;C[l>>3]=h.timeStamp;var m=l>>2;z[m+2]=h.location;u[l+12]=h.ctrlKey;u[l+13]=h.shiftKey;u[l+14]=h.altKey;u[l+15]=h.metaKey;u[l+16]=h.repeat;z[m+5]=h.charCode;z[m+6]=h.keyCode;z[m+7]=h.which;Q(h.key||
"",l+32,32);Q(h.code||"",l+64,32);Q(h.char||"",l+96,32);Q(h.locale||"",l+128,32);N(d)(f,l,b)&&h.preventDefault()},xb:c};return P(a)},nb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=eb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},ob=(a,b,c,d,f,k)=>{O.Tb||(O.Tb=R(64));a=
M(a);return P({target:a,Vb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,vb:k,Eb:d,Fb:(h=event)=>{nb(O.Tb,h,a);N(d)(f,O.Tb,b)&&h.preventDefault()},xb:c})},pb=(a,b,c,d)=>{O.$b||(O.$b=R(257));return P({target:a,vb:"pointerlockchange",Eb:d,Fb:(f=event)=>{var k=O.$b,h=document.pointerLockElement;u[k]=!!h;var l=h?.id||"";Q(jb(h),k+1,128);Q(l,k+129,128);N(d)(20,k,b)&&f.preventDefault()},xb:c})},qb=(a,b,c,d)=>P({target:a,vb:"pointerlockerror",Eb:d,Fb:(f=event)=>{N(d)(38,0,b)&&f.preventDefault()},xb:c}),
rb=(a,b,c,d)=>{O.dc||(O.dc=R(36));a=M(a);return P({target:a,vb:"resize",Eb:d,Fb:(f=event)=>{if(f.target==a){var k=document.body;if(k){var h=O.dc;z[h>>2]=0;z[h+4>>2]=k.clientWidth;z[h+8>>2]=k.clientHeight;z[h+12>>2]=innerWidth;z[h+16>>2]=innerHeight;z[h+20>>2]=outerWidth;z[h+24>>2]=outerHeight;z[h+28>>2]=pageXOffset|0;z[h+32>>2]=pageYOffset|0;N(d)(10,h,b)&&f.preventDefault()}}},xb:c})},sb=(a,b,c,d,f,k)=>{O.cc||(O.cc=R(1552));a=M(a);return P({target:a,Vb:"touchstart"==k||"touchend"==k,vb:k,Eb:d,Fb:h=>
{var l={},m=h.touches;for(var q of m)q.ic=q.jc=0,l[q.identifier]=q;for(var v of h.changedTouches)v.ic=1,l[v.identifier]=v;for(var n of h.targetTouches)l[n.identifier].jc=1;m=O.cc;C[m>>3]=h.timeStamp;u[m+12]=h.ctrlKey;u[m+13]=h.shiftKey;u[m+14]=h.altKey;u[m+15]=h.metaKey;q=m+16;v=eb(a);n=0;for(let r of Object.values(l))if(l=q>>2,z[l]=r.identifier,z[l+1]=r.screenX,z[l+2]=r.screenY,z[l+3]=r.clientX,z[l+4]=r.clientY,z[l+5]=r.pageX,z[l+6]=r.pageY,u[q+28]=r.ic,u[q+29]=r.jc,z[l+8]=r.clientX-(v.left|0),z[l+
9]=r.clientY-(v.top|0),q+=48,31<++n)break;z[m+8>>2]=n;N(d)(f,m,b)&&h.preventDefault()},xb:c})},tb=(a,b,c,d)=>{O.ec||(O.ec=R(96));return P({target:a,Vb:!0,vb:"wheel",Eb:d,Fb:(f=event)=>{var k=O.ec;nb(k,f,a);C[k+64>>3]=f.deltaX;C[k+72>>3]=f.deltaY;C[k+80>>3]=f.deltaZ;z[k+88>>2]=f.deltaMode;N(d)(9,k,b)&&f.preventDefault()},xb:c})},ub=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},S=a=>{var b=ub(a)+1,c=vb(b);Q(a,c,b);return c},
wb=[],T=(a,b)=>{wb[a>>>=0]=b},xb=[],U=a=>{if(a)return wb[a>>>0]},yb=a=>{var b=A[a>>2];return b?F(y,b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?F(y,b,a):"";if(0===a)return""},zb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),Ab=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Bb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,k=yb(f+4);c[k]=C[f+16>>3]}return c}},Cb=a=>a?U(a):"auto",Pb=a=>{function b(d){if(d)return{operation:Db[A[d>>2]],srcFactor:Eb[A[d+
4>>2]],dstFactor:Eb[A[d+8>>2]]}}function c(d){return{compare:Fb[A[d>>2]],failOp:Gb[A[d+4>>2]],depthFailOp:Gb[A[d+8>>2]],passOp:Gb[A[d+12>>2]]}}return{label:V(a+4),layout:Cb(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),k=Bb(A[d+16>>2],A[d+20>>2]);var h=A[d+24>>2];var l=A[d+28>>2];if(h){for(var m=[],q=0;q<h;++q){var v=m,n=v.push;var r=l+24*q;if(r){var w=A[r+4>>2],x=A[r+16>>2];if(0===w&&0===x)var K=null;else{K=4294967296*A[r+4+8>>2]+A[r+8>>2];w=Hb[w];r=A[r+20>>2];for(var Kb=[],Sa=0;Sa<x;++Sa){var Lb=
Kb,Cc=Lb.push,va=r+24*Sa;Cc.call(Lb,{format:Ib[A[va+4>>2]],offset:4294967296*A[va+4+8>>2]+A[va+8>>2],shaderLocation:A[va+16>>2]})}K={arrayStride:K,stepMode:w,attributes:Kb}}}else K=void 0;n.call(v,K)}h=m}else h=void 0;return{module:f,constants:k,buffers:h,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Jb[A[d+4>>2]],stripIndexFormat:Mb[A[d+8>>2]],frontFace:Nb[A[d+12>>2]],cullMode:Ob[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+
4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Fb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),k=Bb(A[d+16>>2],A[d+20>>2]),h=A[d+24>>2],l=A[d+28>>2],m=[],q=0;q<h;++q){var v=m,n=v.push,
r=l+24*q,w=A[r+4>>2];if(0===w)r=void 0;else{w=W[w];var x=(x=A[r+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;r={format:w,blend:x,writeMask:A[r+16>>2]}}n.call(v,r)}return{module:f,constants:k,targets:m,entryPoint:V(d+8)}}}(A[a+92>>2])}},Qb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",
32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",
104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.Ec&&c("maxImmediateSize",148)},Rb=[,"clamp-to-edge","repeat","mirror-repeat"],Eb=[,"zero","one","src","one-minus-src",
"src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Db=[,"add","subtract","reverse-subtract","min","max"],Sb=["binding-not-used",,"uniform","storage","read-only-storage"],Fb=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Tb=[,"opaque","premultiplied","unpremultiplied","inherit"],Ob=[,"none","front","back"],Ub=
[,"compatibility","core"],Vb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",
20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Wb=[,"nearest","linear"],Nb=[,"ccw","cw"],Mb=[,"uint16","uint32"],Xb=[,"load","clear"],Yb=[,"nearest","linear"],Zb=[,"low-power","high-performance"],$b=[,"srgb","display-p3"],Jb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],ac=["binding-not-used",,"filtering","non-filtering","comparison"],
Gb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],bc=["binding-not-used",,"write-only","read-only","read-write"],cc=[,"store","discard"],dc=[,"all","stencil-only","depth-only"],ec=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb",
"rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm",
"bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm",
"astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],fc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],gc=[,"1d","2d","2d-array","cube","cube-array","3d"],hc=[,"standard","extended"],
Ib=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Hb=[,"vertex","instance"],ic={undefined:1,unknown:1,
destroyed:2},jc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";jc.ac||(jc.ac={});jc.ac[a]||(jc.ac[a]=1,ca&&(a="warning: "+a),g(a))},kc={rgba8unorm:22,bgra8unorm:27},lc={},nc=()=>{if(!mc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in lc)void 0===lc[b]?delete a[b]:a[b]=lc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);mc=c}return mc},
mc,oc=[null,[],[]],pc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Qa;e.pauseMainLoop=cb;e.resumeMainLoop=function(){Ua++;var a=Ma,b=Na,c=H;H=null;bb(c,0,!1,Va,!0);Ta(a,b);I()};e.preMainLoop&&$a.push(e.preMainLoop);e.postMainLoop&&ab.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(g=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
var R,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Y,vb,X,Wc={q:function(){return 0},X:function(){return 0},Y:function(){},$:()=>ta(""),Sa:()=>{Ea=!1;Ga=0},Ta:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];La(()=>Uc(a,performance.now()))},b);G[a]={id:c,Nc:b};return 0},Ba:()=>{cb();H=null},P:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,R:(a,b,c)=>{a=M(a);if(!a)return-4;a=eb(a);C[b>>3]=
a.width;C[c>>3]=a.height;return 0},Da:()=>performance.now(),Ia:(a,b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ua:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},x:(a,b,c,d)=>kb(a,b,c,d,12,"blur"),O:(a,b,c)=>{a=
M(a);if(!a)return-4;a.width=b;a.height=c;return 0},y:(a,b,c,d)=>kb(a,b,c,d,13,"focus"),w:(a,b,c,d)=>{if(!O.fullscreenEnabled())return-1;a=M(a);if(!a)return-4;lb(a,b,c,d,"webkitfullscreenchange");return lb(a,b,c,d,"fullscreenchange")},H:(a,b,c,d)=>mb(a,b,c,d,2,"keydown"),F:(a,b,c,d)=>mb(a,b,c,d,1,"keypress"),G:(a,b,c,d)=>mb(a,b,c,d,3,"keyup"),Ja:(a,b,c)=>{a=N(a);bb(a,b,c)},N:(a,b,c,d)=>ob(a,b,c,d,5,"mousedown"),K:(a,b,c,d)=>ob(a,b,c,d,33,"mouseenter"),J:(a,b,c,d)=>ob(a,b,c,d,34,"mouseleave"),L:(a,
b,c,d)=>ob(a,b,c,d,8,"mousemove"),M:(a,b,c,d)=>ob(a,b,c,d,6,"mouseup"),A:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?pb(a,b,c,d):-4:-1,z:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?qb(a,b,c,d):-4:-1,Q:(a,b,c,d)=>rb(a,b,c,d),B:(a,b,c,d)=>sb(a,b,c,d,25,"touchcancel"),C:(a,b,c,d)=>sb(a,b,c,d,23,"touchend"),D:(a,b,c,d)=>sb(a,b,c,d,24,"touchmove"),E:(a,b,c,d)=>sb(a,b,c,d,22,"touchstart"),I:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?tb(a,b,c,d):-1:-4,da:function(a,b,c,d,f,k){b=
-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);var h={};if(k){var l=A[k+12>>2];if(l){var m=A[k+16>>2];h.requiredFeatures=Array.from(A.subarray(m>>2,m+4*l>>2),n=>Vb[n])}var q=A[k+20>>2];if(q){var v={};function n(w,x,K=!1){x=A[q+x>>2];4294967295==x||K&&0==x||(v[w]=x)}function r(w,x){x=q+x;var K=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=K)v[w]=4294967296*A[x+4>>2]+A[x>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",
8);n("maxTextureDimension3D",12);n("maxTextureArrayLayers",16);n("maxBindGroups",20);n("maxBindGroupsPlusVertexBuffers",24);n("maxDynamicUniformBuffersPerPipelineLayout",32);n("maxDynamicStorageBuffersPerPipelineLayout",36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);r("maxUniformBufferBindingSize",
64);r("maxStorageBufferBindingSize",72);n("maxVertexBuffers",88);r("maxBufferSize",96);n("maxVertexAttributes",104);n("maxVertexBufferArrayStride",108);n("maxInterStageShaderVariables",112);n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",
148,!0);h.requiredLimits=v}if(l=A[k+24>>2])l={label:V(l+4)},h.defaultQueue=l;h.label=V(k+4)}a.requestDevice(h).then(n=>{T(f,n.queue);T(d,n);c&&n.lost.then(r=>{n.onuncapturederror=()=>{};var w=X(),x=S(r.message);Qc(c,ic[r.reason],x);Y(w)});n.onuncapturederror=r=>{var w=5;r.error instanceof GPUValidationError?w=2:r.error instanceof GPUOutOfMemoryError?w=3:r.error instanceof GPUInternalError&&(w=4);var x=X();r=S(r.error.message);Tc(d,w,r);Y(x)};Sc(b,1,d,0)},n=>{var r=X();n=S(n.message);Sc(b,3,d,n);c&&
Qc(c,4,n);Y(r)})},ga:(a,b,c)=>{var d=U(a);0===c&&jc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(h){return 0}var k=Vc(16,f.byteLength);y.fill(0,k,f.byteLength);xb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(k,k+f.byteLength));qc(k)});return k},fa:a=>{var b=U(a),c=xb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete xb[a];b.unmap()}},a:a=>{delete wb[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);
try{var f=a.createBuffer(b)}catch(k){return!1}T(c,f);d&&(xb[c]=[]);return!0},ca:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=yb(d+8)}T(c,U(a).createShaderModule(b))},ea:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},aa:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return kc[a]},ba:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Ub[A[c+4>>2]],powerPreference:Zb[A[c+8>>2]],forceFallbackAdapter:!!A[c+
12>>2]};a=A[c>>2];0!==a&&(f.Qc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(k=>{if(k)T(d,k),Rc(b,1,d,0);else{k=X();var h=S("WebGPU not available on this browser (requestAdapter returned null)");Rc(b,3,d,h);Y(k)}},k=>{var h=X();k=S(k.message);Rc(b,4,d,k);Y(h)}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Rc(b,3,d,a),Y(f))},Z:(a,b)=>{var c=0,d=0,f;for(f of nc()){var k=b+c;A[a+d>>2]=k;c+=Q(f,k,Infinity)+1;d+=4}return 0},_:(a,b)=>{var c=nc();
A[a>>2]=c.length;a=0;for(var d of c)a+=ub(d)+1;A[b>>2]=a;return 0},p:()=>52,W:()=>52,U:function(){return 70},V:(a,b,c,d)=>{for(var f=0,k=0;k<c;k++){var h=A[b>>2],l=A[b+4>>2];b+=8;for(var m=0;m<l;m++){var q=a,v=y[h+m],n=oc[q];0===v||10===v?((1===q?ma:g)(F(n)),n.length=0):n.push(v)}f+=l}A[d>>2]=f;return 0},Ra:Ia,Xa:function(){e.lc=a=>{0!=sc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.lc)},Ka:function(){e.qc=a=>{const b=a.clipboardData.getData("text");pc(()=>{const c=
S(b);rc(c)})};window.addEventListener("paste",e.qc)},Ca:function(){e.Kc=[];e.mc=b=>{b.stopPropagation();b.preventDefault()};e.nc=b=>{b.stopPropagation();b.preventDefault()};e.oc=b=>{b.stopPropagation();b.preventDefault()};e.pc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Lc=c;tc(c.length);for(let f=0;f<c.length;f++)pc(()=>{const k=S(c[f].name);uc(f,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);vc(b.clientX,b.clientY,d)};const a=e.Gb;
a.addEventListener("dragenter",e.mc,!1);a.addEventListener("dragleave",e.nc,!1);a.addEventListener("dragover",e.oc,!1);a.addEventListener("drop",e.pc,!1)},Qa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Va:function(a){e.Ub&&(URL.revokeObjectURL(e.Ub[a].vc),e.Ub[a]=null)},oa:function(a,b){0!==b&&(document.title=b?F(y,b):"");a=a?F(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?db[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
e.Gb=M(a);e.Gb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.Gb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Wa:function(){window.removeEventListener("beforeunload",e.lc)},Fa:function(){window.removeEventListener("paste",e.qc)},va:function(){const a=e.Gb;a.removeEventListener("dragenter",e.mc);a.removeEventListener("dragleave",e.nc);a.removeEventListener("dragover",e.oc);a.removeEventListener("drop",e.pc)},h:function(){e.Gb&&
e.Gb.requestPointerLock&&e.Gb.requestPointerLock()},r:function(a,b,c){if(e.Gb){if(0===b)a="none";else if(0!=c)a=e.Ub[a].xc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.Gb.style.cursor=a}},Pa:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const f=d.getContext("2d"),k=f.createImageData(a,b);k.data.set(y.subarray(c,c+a*b*4));f.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ea:function(a){a=a?F(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";
b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},La:function(){return e.Hb?e.Hb.bufferSize:0},Oa:function(a,b,c){e.sb=null;e.Hb=null;"undefined"!==typeof AudioContext?e.sb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.sb=null,console.log("sokol_audio.h: no WebAudio support"));return e.sb?(console.log("sokol_audio.h: sample rate ",e.sb.sampleRate),e.Hb=e.sb.createScriptProcessor(c,
0,b),e.Hb.onaudioprocess=d=>{const f=d.outputBuffer.length,k=xc(f);if(k){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const m=d.outputBuffer.getChannelData(l);for(let q=0;q<f;q++)m[q]=B[(k>>2)+(h*q+l)]}}},e.Hb.connect(e.sb.destination),a=()=>{e.sb&&"suspended"===e.sb.state&&e.sb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},Ma:function(){return e.sb?e.sb.sampleRate:0},
Na:function(){const a=e.sb;null!==a&&(e.Hb&&e.Hb.disconnect(),a.close(),e.sb=null,e.Hb=null)},o:function(a,b,c,d,f,k){const h=b?F(y,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(h,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=k?(y.set(m,f),zc(a,d,m.length)):Bc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,m);Dc(a)}):Ac(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,l);Dc(a)})},
T:function(a,b){const c=b?F(y,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),Dc(a)):yc(a,Number(d))):Ac(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);Dc(a)})},s:function(){return navigator.userAgent.includes("Macintosh")?1:0},S:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;
default:console.info(b)}},e:(a,b)=>U(a).features.has(Vb[b]),sa:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],k=A[b+16>>2],h=[],l=0;l<f;++l){var m=h,q=m.push;var v=k+56*l;var n=A[v+4>>2];if(0!==n){var r=z[v+8>>2];-1==r&&(r=void 0);v={view:U(n),depthSlice:r,resolveTarget:U(A[v+12>>2]),clearValue:zb(v+24),loadOp:Xb[A[v+16>>2]],storeOp:cc[A[v+20>>2]]}}else v=void 0;q.call(m,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],
depthLoadOp:Xb[A[f+8>>2]],depthStoreOp:cc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Xb[A[f+24>>2]],stencilStoreOp:cc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;k=A[b+28>>2];k=0!==k?{querySet:U(A[k+4>>2]),beginningOfPassWriteIndex:A[k+8>>2],endOfPassWriteIndex:A[k+12>>2]}:void 0;b={label:c,colorAttachments:h,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:k,maxDrawCount:d};a=U(a);d=Kc(0);T(d,a.beginRenderPass(b));return d},ia:a=>
{a=U(a);var b=Gc(0);T(b,a.finish());return b},ja:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ra:(a,b)=>{U(a).setPipeline(U(b))},l:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var k=[],h=0;h<f;++h){var l=k,m=l.push;var q=b+40*h;var v=A[q+8>>2],n=A[q+32>>2],r=A[q+36>>2],w=A[q+4>>2];v?(n=q+24,n=A[n>>2]+4294967296*z[n+4>>2],-1==n&&(n=void 0),q={binding:w,resource:{buffer:U(v),offset:4294967296*A[q+4+16>>2]+A[q+16>>2],size:n}}):
q=n?{binding:w,resource:U(n)}:{binding:w,resource:U(r)};m.call(l,q)}c={label:c,layout:d,entries:k};a=U(a);d=Ec(0);T(d,a.createBindGroup(c));return d},m:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],k=0;k<d;++k){var h=f,l=h.push,m=b+88*k,q=A[m+4>>2],v=A[m+8>>2];var n=m+24;var r=A[n+4>>2];n=r?{type:Sb[r],hasDynamicOffset:!!A[n+8>>2],minBindingSize:4294967296*A[n+4+16>>2]+A[n+16>>2]}:void 0;r=(r=A[m+48+4>>2])?{type:ac[r]}:void 0;var w=m+56;var x=A[w+4>>2];w=x?{sampleType:fc[x],viewDimension:gc[A[w+
8>>2]],multisampled:!!A[w+12>>2]}:void 0;m+=72;m=(x=A[m+4>>2])?{access:bc[x],format:W[A[m+8>>2]],viewDimension:gc[A[m+12>>2]]}:void 0;l.call(h,{binding:q,visibility:v,buffer:n,sampler:r,texture:w,storageTexture:m})}c={label:c,entries:f};a=U(a);d=Fc(0);T(d,a.createBindGroupLayout(c));return d},v:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=Hc(0);T(b,a.createCommandEncoder(c));return b},ua:(a,b)=>{var c=V(b+4);var d=Cb(A[b+12>>2]);b=(b+=16)?{module:U(A[b+4>>2]),constants:Bb(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+
8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=Ic(0);T(d,a.createComputePipeline(c));return d},wa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],k=0;k<c;++k)f.push(U(A[d+4*k>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=Jc(0);T(c,a.createPipelineLayout(b));return c},ta:(a,b)=>{b=Pb(b);a=U(a);var c=Lc(0);T(c,a.createRenderPipeline(b));return c},xa:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Rb[A[b+12>>2]],addressModeV:Rb[A[b+16>>2]],addressModeW:Rb[A[b+20>>2]],magFilter:Wb[A[b+24>>2]],
minFilter:Wb[A[b+28>>2]],mipmapFilter:Yb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Fb[A[b+44>>2]],maxAnisotropy:qa[b+48>>1]});a=U(a);b=Mc(0);T(b,a.createSampler(c));return b},n:(a,b)=>{var c={label:V(b+4),size:Ab(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:ec[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=Oc(0);T(d,a.createTexture(c));return d},za:(a,
b)=>{Qb(U(a).limits,b);return 1},d:(a,b)=>U(a).features.has(Vb[b]),Ha:(a,b)=>{a=M(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Mc=V(b+4);b=Nc(0);T(b,a);return b},ha:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},i:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},ya:(a,b,c,d,f,k)=>{var h=A[f+8>>2],l=A[f+12>>2],m=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[m>>
2],y:A[m+4>>2],z:A[m+8>>2]},aspect:dc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===h?void 0:h,rowsPerImage:4294967295===l?void 0:l},Ab(k))},t:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},u:(a,b,c,d,f,k)=>{U(a).drawIndexed(b,c,d>>>0,f,k>>>0)},ka:a=>{U(a).end()},b:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},pa:(a,b)=>{U(a).setBlendConstant(zb(b))},ma:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:
Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Mb[c],d,f)},qa:(a,b)=>{U(a).setPipeline(U(b))},j:(a,b,c,d,f)=>{U(a).setScissorRect(b,c,d,f)},na:(a,b)=>{U(a).setStencilReference(b>>>0)},la:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},k:(a,b,c,d,f,k,h)=>{U(a).setViewport(b,c,d,f,k,h)},Ga:(a,
b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Tb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),k=>W[k])}b=A[b>>2];0!==b&&(c.colorSpace=$b[A[b+8>>2]],c.Oc={mode:hc[A[b+12>>2]]});a.configure(c)},Aa:(a,b)=>{a=U(a);try{var c=Oc(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},
f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:gc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:dc[A[b+36>>2]]}}a=U(a);b=Pc(0);T(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Ya;sa();gb=Z.Nb;c=Z;R=c._a;qc=c.$a;e.__sapp_emsc_onpaste=rc=c.ab;e.__sapp_html5_get_ask_leave_site=sc=c.bb;e.__sapp_emsc_begin_drop=tc=c.cb;e.__sapp_emsc_drop=uc=c.db;e.__sapp_emsc_end_drop=vc=c.eb;e.__sapp_emsc_invoke_fetch_cb=c.fb;e.__sapp_emsc_set_fullscreen_flag=c.gb;e._main=wc=c.hb;e.__saudio_emsc_pull=xc=c.ib;e.__sfetch_emsc_head_response=yc=c.jb;e.__sfetch_emsc_get_response=zc=c.kb;e.__sfetch_emsc_failed_http_status=Ac=c.lb;e.__sfetch_emsc_failed_buffer_too_small=
Bc=c.mb;e.__sfetch_emsc_failed_other=Dc=c.nb;Ec=c.ob;Fc=c.pb;Gc=c.qb;Hc=c.rb;Ic=c.tb;Jc=c.ub;Kc=c.yb;Lc=c.zb;Mc=c.Ab;Nc=c.Bb;Oc=c.Cb;Pc=c.Db;Qc=c.Jb;Rc=c.Kb;Sc=c.Lb;Tc=c.Mb;Uc=c.Ob;Vc=c.Pb;Y=c.Qb;vb=c.Rb;X=c.Sb;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Wc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("plmpeg-sapp-ui.wasm",ia):ia+"plmpeg-sapp-ui.wasm";return a((await ya(b)).instance)})();
function Xc(a=[]){var b=wc;a.unshift(ea);var c=a.length,d=vb(4*(c+1)),f=d;a.forEach(h=>{A[f>>2]=S(h);f+=4});A[f>>2]=0;try{var k=b(c,d);Ja(k)}catch(h){Ha(h)}}
function Yc(a=da){function b(){e.calledRun=!0;if(!t){Z.Za();e.onRuntimeInitialized?.();e.noInitialRun||Xc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Yc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Yc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Yc();
