var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),g=console.error.bind(console),p,t=!1,na,la=a=>a.startsWith("file://"),u,y,oa,pa,z,A,B,C,qa;
function ra(){var a=sa.buffer;u=new Int8Array(a);oa=new Int16Array(a);y=new Uint8Array(a);pa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){e.onAbort?.(a);a="Aborted("+a+")";g(a);t=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=ua;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},D=0,E=null,Ea=!0,Fa=globalThis.TextDecoder&&new TextDecoder,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|k);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|h:(f&7)<<18|k<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ga=0,G={},Ha=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ia=a=>{na=a;Ea||0<Ga||(e.onExit?.(a),t=!0);fa(a,new za(a))},Ja=()=>{if(!(Ea||0<Ga))try{var a=na;na=a;Ia(a)}catch(b){Ha(b)}},H=a=>{if(!t)try{a(),Ja()}catch(b){Ha(b)}},Qa=(a,b)=>{Ka=a;La=b;if(I)if(Ma||=!0,0==a)J=function(){setTimeout(L,Math.max(0,Na+b-performance.now())|0)};else if(1==a)J=function(){Oa(L)};else if(2==a){if(!Pa)if(globalThis.setImmediate)Pa=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}J=function(){Pa(L)}}},$a=(a,b,c,d,f)=>{function k(){return h<Sa?(Ja(),!1):!0}I=a;Ta=d;var h=Sa;Ma=!1;L=function(){if(!t)if(0<Ua.length){var l=Ua.shift();l.Hc(l.yc);if(Va){var m=
Va,q=0==m%1?m-1:Math.floor(m);Va=l.Bc?q:(8*m+(q+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",m=Va??0,q=Wa.Gc??0,m?m<q?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));k()&&setTimeout(L,0)}else if(k())if(Xa=Xa+1|0,1==Ka&&1<La&&0!=Xa%La)J();else{0==Ka&&(Na=performance.now());a:if(!t){for(l of Ya)if(!1===l())break a;H(a);for(m of Za)m()}k()&&J()}};f||(0<b?Qa(0,1E3/b):Qa(1,1),J());if(c)throw"unwind";},Ma=!1,J=null,Sa=0,I=null,Ta=0,Ka=0,La=0,Xa=0,
Ua=[],Ya=[],Za=[];function ab(){J=null;Sa++}var M=0;function Oa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===M)M=b+1E3/60;else for(;b+2>=M;)M+=1E3/60;setTimeout(a,Math.max(M-b,0))}}var Wa={},Na,L,Pa,Va,bb=[0,globalThis.document??0,globalThis.window??0],N=a=>{a=2<a?a?F(y,a):"":a;return bb[a]||globalThis.document?.querySelector(a)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],O=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};
function fb(a){var b=P.yb[a];b.target.removeEventListener(b.zb,b.mc,b.Ib);P.yb.splice(a,1)}function gb(){if(navigator.userActivation?navigator.userActivation.isActive:P.cc&&P.wc.$b){var a=P.Xb;P.Xb=[];for(var b of a)b.hc(...b.lc)}}function Q(a){if(!a.target)return-4;if(a.Gb)a.mc=function(c){++P.cc;P.wc=a;gb();a.Kb(c);gb();--P.cc},a.target.addEventListener(a.zb,a.mc,a.Ib),P.yb.push(a);else for(var b=0;b<P.yb.length;++b)P.yb[b].target==a.target&&P.yb[b].zb==a.zb&&fb(b--);return 0}
function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={zc:0,Ic:0,dc:0,Yb:0,kc:0,jc:0,ac:0,Fc:0,Kc:0,Ec:0,bc:0,ec:0,Uc:0,ic:0,Lc(){for(;P.yb.length;)fb(P.yb.length-1);P.Xb=[]},cc:0,Xb:[],Dc(a,b,c){function d(k,h){if(k.length!=h.length)return!1;for(var l in k)if(k[l]!=h[l])return!1;return!0}for(var f of P.Xb)if(f.hc==a&&d(f.lc,c))return;P.Xb.push({hc:a,pc:b,lc:c});P.Xb.sort((k,h)=>k.pc<h.pc)},Nc(a){P.Xb=P.Xb.filter(b=>b.hc!=a)},yb:[],Mc:(a,b)=>{for(var c=0;c<P.yb.length;++c)P.yb[c].target!=a||b&&b!=P.yb[c].zb||fb(c--)},Oc(a){let b=!1;for(let c=0;c<
P.yb.length;++c){const d=P.yb[c];d.target===a.target&&d.Hb===a.Hb&&d.Gb===a.Gb&&d.Jb===a.Jb&&(fb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},R=(a,b,c)=>{var d=y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var k=0;k<a.length;++k){var h=a.codePointAt(k);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&
63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;k++}}d[b]=0;return b-f},ib=(a,b,c,d,f,k)=>{P.ac||(P.ac=S(256));a={target:N(a),zb:k,Hb:f,Jb:b,Gb:d,Kb:h=>{var l=h.target.id?h.target.id:"",m=P.ac;R(hb(h.target),m+0,128);R(l,m+128,128);O(d)(f,m,b)&&h.preventDefault()},Ib:c};return Q(a)},jb=(a,b,c,d,f)=>{P.bc||(P.bc=S(276));return Q({target:a,zb:f,Hb:19,Jb:b,Gb:d,Kb:k=>{var h=P.bc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement||document.msFullscreenElement,m=!!l;u[h]=m;u[h+1]=P.fullscreenEnabled();var q=m?l:P.xc,v=q?.id||"";R(hb(q),h+2,128);R(v,h+130,128);z[h+260>>2]=q?q.clientWidth:0;z[h+264>>2]=q?q.clientHeight:0;z[h+268>>2]=screen.width;z[h+272>>2]=screen.height;m&&(P.xc=l);O(d)(19,h,b)&&k.preventDefault()},Ib:c})},kb=(a,b,c,d,f,k)=>{P.dc||(P.dc=S(160));a={target:N(a),zb:k,Hb:f,Jb:b,Gb:d,Kb:h=>{var l=P.dc;C[l>>3]=h.timeStamp;var m=l>>2;z[m+2]=h.location;u[l+12]=h.ctrlKey;u[l+13]=
h.shiftKey;u[l+14]=h.altKey;u[l+15]=h.metaKey;u[l+16]=h.repeat;z[m+5]=h.charCode;z[m+6]=h.keyCode;z[m+7]=h.which;R(h.key||"",l+32,32);R(h.code||"",l+64,32);R(h.char||"",l+96,32);R(h.locale||"",l+128,32);O(d)(f,l,b)&&h.preventDefault()},Ib:c};return Q(a)},lb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+
9]=b.movementY;a=cb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},mb=(a,b,c,d,f,k)=>{P.Yb||(P.Yb=S(64));a=N(a);return Q({target:a,$b:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,zb:k,Hb:f,Jb:b,Gb:d,Kb:h=>{lb(P.Yb,h,a);O(d)(f,P.Yb,b)&&h.preventDefault()},Ib:c})},nb=(a,b,c,d)=>{P.ec||(P.ec=S(257));return Q({target:a,zb:"pointerlockchange",Hb:20,Jb:b,Gb:d,Kb:f=>{var k=P.ec,h=document.pointerLockElement;u[k]=!!h;var l=h?.id||"";R(hb(h),k+1,128);R(l,k+129,128);O(d)(20,k,b)&&f.preventDefault()},
Ib:c})},ob=(a,b,c,d)=>Q({target:a,zb:"pointerlockerror",Hb:38,Jb:b,Gb:d,Kb:f=>{O(d)(38,0,b)&&f.preventDefault()},Ib:c}),pb=(a,b,c,d)=>{P.jc||(P.jc=S(36));a=N(a);return Q({target:a,zb:"resize",Hb:10,Jb:b,Gb:d,Kb:f=>{if(f.target==a){var k=document.body;if(k){var h=P.jc;z[h>>2]=0;z[h+4>>2]=k.clientWidth;z[h+8>>2]=k.clientHeight;z[h+12>>2]=innerWidth;z[h+16>>2]=innerHeight;z[h+20>>2]=outerWidth;z[h+24>>2]=outerHeight;z[h+28>>2]=pageXOffset|0;z[h+32>>2]=pageYOffset|0;O(d)(10,h,b)&&f.preventDefault()}}},
Ib:c})},qb=(a,b,c,d,f,k)=>{P.ic||(P.ic=S(1552));a=N(a);return Q({target:a,$b:"touchstart"==k||"touchend"==k,zb:k,Hb:f,Jb:b,Gb:d,Kb:h=>{var l={},m=h.touches;for(var q of m)q.nc=q.oc=0,l[q.identifier]=q;for(var v of h.changedTouches)v.nc=1,l[v.identifier]=v;for(var n of h.targetTouches)l[n.identifier].oc=1;m=P.ic;C[m>>3]=h.timeStamp;u[m+12]=h.ctrlKey;u[m+13]=h.shiftKey;u[m+14]=h.altKey;u[m+15]=h.metaKey;q=m+16;v=cb(a);n=0;for(let r of Object.values(l))if(l=q>>2,z[l]=r.identifier,z[l+1]=r.screenX,z[l+
2]=r.screenY,z[l+3]=r.clientX,z[l+4]=r.clientY,z[l+5]=r.pageX,z[l+6]=r.pageY,u[q+28]=r.nc,u[q+29]=r.oc,z[l+8]=r.clientX-(v.left|0),z[l+9]=r.clientY-(v.top|0),q+=48,31<++n)break;z[m+8>>2]=n;O(d)(f,m,b)&&h.preventDefault()},Ib:c})},rb=(a,b,c,d)=>{P.kc||(P.kc=S(96));return Q({target:a,$b:!0,zb:"wheel",Hb:9,Jb:b,Gb:d,Kb:f=>{var k=P.kc;lb(k,f,a);C[k+64>>3]=f.deltaX;C[k+72>>3]=f.deltaY;C[k+80>>3]=f.deltaZ;z[k+88>>2]=f.deltaMode;O(d)(9,k,b)&&f.preventDefault()},Ib:c})},sb=a=>{for(var b=0,c=0;c<a.length;++c){var d=
a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},T=a=>{var b=sb(a)+1,c=tb(b);R(a,c,b);return c},U=[],ub=(a,b)=>{U[a>>>0]=b},vb=[],V=a=>{if(a)return U[a>>>0]},wb=a=>{var b=A[a>>2];return b?F(y,b,A[a+4>>2]):""},W=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?F(y,b,a):"";if(0===a)return""},xb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),yb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),zb=a=>{if(0!==a)return{querySet:V(A[a+4>>2]),beginningOfPassWriteIndex:A[a+
8>>2],endOfPassWriteIndex:A[a+12>>2]}},Ab=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,k=wb(f+4);c[k]=C[f+16>>3]}return c}},Bb=a=>a?V(a):"auto",Ob=a=>{function b(d){if(d)return{operation:Cb[A[d>>2]],srcFactor:Db[A[d+4>>2]],dstFactor:Db[A[d+8>>2]]}}function c(d){return{compare:Eb[A[d>>2]],failOp:Fb[A[d+4>>2]],depthFailOp:Fb[A[d+8>>2]],passOp:Fb[A[d+12>>2]]}}return{label:W(a+4),layout:Bb(A[a+12>>2]),vertex:function(d){if(d){var f=V(A[d+4>>2]),k=Ab(A[d+16>>2],A[d+20>>2]);var h=A[d+24>>2];var l=
A[d+28>>2];if(h){for(var m=[],q=0;q<h;++q){var v=m,n=v.push;var r=l+24*q;if(r){var w=A[r+4>>2],x=A[r+16>>2];if(0===w&&0===x)var K=null;else{K=4294967296*A[r+4+8>>2]+A[r+8>>2];w=Gb[w];r=A[r+20>>2];for(var Kb=[],Ra=0;Ra<x;++Ra){var Lb=Kb,wa=r+24*Ra;Lb.push.call(Lb,{format:Hb[A[wa+4>>2]],offset:4294967296*A[wa+4+8>>2]+A[wa+8>>2],shaderLocation:A[wa+16>>2]})}K={arrayStride:K,stepMode:w,attributes:Kb}}}else K=void 0;n.call(v,K)}h=m}else h=void 0;return{module:f,constants:k,buffers:h,entryPoint:W(d+8)}}}(a+
16),primitive:function(d){if(d)return{topology:Ib[A[d+4>>2]],stripIndexFormat:Jb[A[d+8>>2]],frontFace:Mb[A[d+12>>2]],cullMode:Nb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:X[A[d+4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Eb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+
4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=V(A[d+4>>2]),k=Ab(A[d+16>>2],A[d+20>>2]),h=A[d+24>>2],l=A[d+28>>2],m=[],q=0;q<h;++q){var v=m,n=v.push,r=l+24*q,w=A[r+4>>2];if(0===w)r=void 0;else{w=X[w];var x=(x=A[r+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;r={format:w,blend:x,writeMask:A[r+16>>2]}}n.call(v,r)}return{module:f,constants:k,targets:m,entryPoint:W(d+8)}}}(A[a+92>>2])}},Pb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",
4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",
80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",
136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.Jc&&c("maxImmediateSize",148)},Qb=[,"clamp-to-edge","repeat","mirror-repeat"],Db=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Cb=[,"add","subtract","reverse-subtract","min","max"],Rb=["binding-not-used",,"uniform",
"storage","read-only-storage"],Eb=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Sb=[,"opaque","premultiplied","unpremultiplied","inherit"],Nb=[,"none","front","back"],Tb=[,"compatibility","core"],Ub={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",
11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Vb=[,"nearest","linear"],Mb=[,"ccw","cw"],Jb=[,"uint16","uint32"],Wb=[,"load","clear"],
Xb=[,"nearest","linear"],Yb=[,"low-power","high-performance"],Zb=[,"srgb","display-p3"],Ib=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],$b=["binding-not-used",,"filtering","non-filtering","comparison"],Fb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],ac=["binding-not-used",,"write-only","read-only","read-write"],bc=[,"store","discard"],cc=[,"all","stencil-only","depth-only"],dc=[,"1d","2d","3d"],X=[,"r8unorm",
"r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint",
"stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm",
"eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb",
"astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],ec=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],fc=[,"1d","2d","2d-array","cube","cube-array","3d"],gc=[,"standard","extended"],Hb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16",
"float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Gb=[,"vertex","instance"],hc={undefined:1,unknown:1,destroyed:2},ic=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";ic.fc||(ic.fc={});ic.fc[a]||(ic.fc[a]=1,ca&&(a="warning: "+a),g(a))},jc={rgba8unorm:22,bgra8unorm:27},kc={},mc=()=>{if(!lc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",
PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in kc)void 0===kc[b]?delete a[b]:a[b]=kc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);lc=c}return lc},lc,nc=[null,[],[]],oc=a=>{var b=Y();a();Z(b)};e.requestAnimationFrame=Oa;e.pauseMainLoop=ab;e.resumeMainLoop=function(){Sa++;var a=Ka,b=La,c=I;I=null;$a(c,0,!1,Ta,!0);Qa(a,b);J()};e.preMainLoop&&Ya.push(e.preMainLoop);e.postMainLoop&&Za.push(e.postMainLoop);
e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(g=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var S,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Z,tb,Y,sa,eb,Vc={s:function(){return 0},U:function(){return 0},V:function(){},X:()=>ta(""),Sa:()=>{Ea=!1;Ga=0},Ta:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];H(()=>Tc(a,performance.now()))},b);G[a]={id:c,Sc:b};return 0},Ca:()=>{ab();I=null},W:()=>Date.now(),M:()=>globalThis.devicePixelRatio??1,O:(a,b,c)=>{a=N(a);if(!a)return-4;a=cb(a);C[b>>3]=
a.width;C[c>>3]=a.height;return 0},q:()=>performance.now(),Da:()=>performance.now(),Ka:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ua:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},u:(a,b,c,d)=>ib(a,b,c,d,
12,"blur"),L:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},v:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),t:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=N(a);if(!a)return-4;jb(a,b,c,d,"webkitfullscreenchange");return jb(a,b,c,d,"fullscreenchange")},E:(a,b,c,d)=>kb(a,b,c,d,2,"keydown"),C:(a,b,c,d)=>kb(a,b,c,d,1,"keypress"),D:(a,b,c,d)=>kb(a,b,c,d,3,"keyup"),La:(a,b,c)=>{a=O(a);$a(a,b,c)},K:(a,b,c,d)=>mb(a,b,c,d,5,"mousedown"),H:(a,b,c,d)=>mb(a,b,c,d,33,"mouseenter"),G:(a,b,c,d)=>mb(a,b,c,
d,34,"mouseleave"),I:(a,b,c,d)=>mb(a,b,c,d,8,"mousemove"),J:(a,b,c,d)=>mb(a,b,c,d,6,"mouseup"),x:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?nb(a,b,c,d):-4:-1,w:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?ob(a,b,c,d):-4:-1,N:(a,b,c,d)=>pb(a,b,c,d),y:(a,b,c,d)=>qb(a,b,c,d,25,"touchcancel"),z:(a,b,c,d)=>qb(a,b,c,d,23,"touchend"),A:(a,b,c,d)=>qb(a,b,c,d,24,"touchmove"),B:(a,b,c,d)=>qb(a,b,c,d,22,"touchstart"),F:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?rb(a,b,c,d):-1:-4,aa:function(a,
b,c,d,f,k){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=V(a);var h={};if(k){var l=A[k+12>>2];if(l){var m=A[k+16>>2];h.requiredFeatures=Array.from(A.subarray(m>>2,m+4*l>>2),n=>Ub[n])}var q=A[k+20>>2];if(q){var v={};function n(w,x,K=!1){x=A[q+x>>2];4294967295==x||K&&0==x||(v[w]=x)}function r(w,x){x=q+x;var K=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=K)v[w]=4294967296*A[x+4>>2]+A[x>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",
8);n("maxTextureDimension3D",12);n("maxTextureArrayLayers",16);n("maxBindGroups",20);n("maxBindGroupsPlusVertexBuffers",24);n("maxDynamicUniformBuffersPerPipelineLayout",32);n("maxDynamicStorageBuffersPerPipelineLayout",36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);r("maxUniformBufferBindingSize",
64);r("maxStorageBufferBindingSize",72);n("maxVertexBuffers",88);r("maxBufferSize",96);n("maxVertexAttributes",104);n("maxVertexBufferArrayStride",108);n("maxInterStageShaderVariables",112);n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",
148,!0);h.requiredLimits=v}if(l=A[k+24>>2])l={label:W(l+4)},h.defaultQueue=l;h.label=W(k+4)}a.requestDevice(h).then(n=>{H(()=>{U[f>>>0]=n.queue;U[d>>>0]=n;n.lost.then(r=>{H(()=>{n.onuncapturederror=()=>{};var w=Y(),x=T(r.message);Pc(c,hc[r.reason],x);Z(w)})});n.onuncapturederror=r=>{var w=5;r.error instanceof GPUValidationError?w=2:r.error instanceof GPUOutOfMemoryError?w=3:r.error instanceof GPUInternalError&&(w=4);var x=Y();r=T(r.error.message);Sc(d,w,r);Z(x)};Rc(b,1,d,0)})},n=>{H(()=>{var r=Y(),
w=T(n.message);Rc(b,3,d,w);c&&Pc(c,4,w);Z(r)})})},da:(a,b,c)=>{var d=V(a);0===c&&ic();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(h){return 0}var k=Uc(16,f.byteLength);y.fill(0,k,f.byteLength);vb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(k,k+f.byteLength));pc(k)});return k},ca:a=>{var b=V(a),c=vb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete vb[a];b.unmap()}},a:a=>{delete U[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:W(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>
2],mappedAtCreation:d};a=V(a);try{var f=a.createBuffer(b)}catch(k){return!1}U[c>>>0]=f;d&&(vb[c]=[]);return!0},$:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:W(b+4),code:""};switch(f){case 2:b.code=wb(d+8)}a=V(a).createShaderModule(b);U[c>>>0]=a},ba:a=>{a=V(a);a.onuncapturederror=null;a.destroy()},Y:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return jc[a]},_:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Tb[A[c+4>>2]],powerPreference:Yb[A[c+
8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Vc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(k=>{H(()=>{if(k)U[d>>>0]=k,Qc(b,1,d,0);else{var h=Y(),l=T("WebGPU not available on this browser (requestAdapter returned null)");Qc(b,3,d,l);Z(h)}})},k=>{H(()=>{var h=Y(),l=T(k.message);Qc(b,4,d,l);Z(h)})}):(f=Y(),a=T("WebGPU not available on this browser (navigator.gpu is not available)"),Qc(b,3,d,a),Z(f))},Wa:(a,b)=>{var c=0,d=0,f;for(f of mc()){var k=b+c;A[a+d>>2]=
k;c+=R(f,k,Infinity)+1;d+=4}return 0},R:(a,b)=>{var c=mc();A[a>>2]=c.length;a=0;for(var d of c)a+=sb(d)+1;A[b>>2]=a;return 0},r:()=>52,T:()=>52,Va:function(){return 70},S:(a,b,c,d)=>{for(var f=0,k=0;k<c;k++){var h=A[b>>2],l=A[b+4>>2];b+=8;for(var m=0;m<l;m++){var q=a,v=y[h+m],n=nc[q];0===v||10===v?((1===q?ma:g)(F(n)),n.length=0):n.push(v)}f+=l}A[d>>2]=f;return 0},Ra:Ia,Za:function(){e.qc=a=>{0!=rc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.qc)},Ma:function(){e.vc=
a=>{const b=a.clipboardData.getData("text");oc(()=>{const c=T(b);qc(c)})};window.addEventListener("paste",e.vc)},Fa:function(){e.Pc=[];e.rc=b=>{b.stopPropagation();b.preventDefault()};e.sc=b=>{b.stopPropagation();b.preventDefault()};e.tc=b=>{b.stopPropagation();b.preventDefault()};e.uc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Qc=c;sc(c.length);for(let f=0;f<c.length;f++)oc(()=>{const k=T(c[f].name);tc(f,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=
4);b.metaKey&&(d|=8);uc(b.clientX,b.clientY,d)};const a=e.Vb;a.addEventListener("dragenter",e.rc,!1);a.addEventListener("dragleave",e.sc,!1);a.addEventListener("dragover",e.tc,!1);a.addEventListener("drop",e.uc,!1)},Xa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Z:function(a){e.Zb&&(URL.revokeObjectURL(e.Zb[a].Ac),e.Zb[a]=null)},wa:function(a,b){0!==b&&(document.title=b?F(y,b):"");a=a?F(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?bb[a]=
e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.Vb=N(a);e.Vb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.Vb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ya:function(){window.removeEventListener("beforeunload",e.qc)},Ha:function(){window.removeEventListener("paste",e.vc)},Ea:function(){const a=e.Vb;a.removeEventListener("dragenter",e.rc);a.removeEventListener("dragleave",e.sc);a.removeEventListener("dragover",
e.tc);a.removeEventListener("drop",e.uc)},k:function(){e.Vb&&e.Vb.requestPointerLock&&e.Vb.requestPointerLock()},fa:function(a,b,c){if(e.Vb){if(0===b)a="none";else if(0!=c)a=e.Zb[a].Cc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a=
"auto"}e.Vb.style.cursor=a}},Qa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),k=f.createImageData(a,b);k.data.set(y.subarray(c,c+a*b*4));f.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Na:function(){return e.Wb?e.Wb.bufferSize:0},Pa:function(a,b,c){e.xb=null;e.Wb=null;"undefined"!==typeof AudioContext?e.xb=new AudioContext({sampleRate:a,
latencyHint:"interactive"}):(e.xb=null,console.log("sokol_audio.h: no WebAudio support"));return e.xb?(console.log("sokol_audio.h: sample rate ",e.xb.sampleRate),e.Wb=e.xb.createScriptProcessor(c,0,b),e.Wb.onaudioprocess=d=>{const f=d.outputBuffer.length,k=wc(f);if(k){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const m=d.outputBuffer.getChannelData(l);for(let q=0;q<f;q++)m[q]=B[(k>>2)+(h*q+l)]}}},e.Wb.connect(e.xb.destination),a=()=>{e.xb&&"suspended"===e.xb.state&&e.xb.resume()},
document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},Oa:function(){return e.xb?e.xb.sampleRate:0},p:function(){const a=e.xb;null!==a&&(e.Wb&&e.Wb.disconnect(),a.close(),e.xb=null,e.Wb=null)},o:function(a,b,c,d,f,k){const h=b?F(y,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(h,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=k?(y.set(m,
f),yc(a,d,m.length)):Ac(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,m);Bc(a)}):zc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,l);Bc(a)})},Q:function(a,b){const c=b?F(y,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),Bc(a)):xc(a,Number(d))):zc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);Bc(a)})},
P:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Ga:(a,b)=>{Pb(V(a).limits,b);return 1},e:(a,b)=>V(a).features.has(Ub[b]),sa:(a,b)=>{var c;b&&(c={label:W(b+4),timestampWrites:zb(A[b+12>>2])});b=V(a);a=Gc(0);c=b.beginComputePass(c);U[a>>>0]=c;return a},ra:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=W(b+4);for(var f=A[b+12>>2],k=A[b+16>>2],h=[],l=0;l<f;++l){var m=
h,q=m.push;var v=k+56*l;var n=A[v+4>>2];if(0!==n){var r=z[v+8>>2];-1==r&&(r=void 0);v={view:V(n),depthSlice:r,resolveTarget:V(A[v+12>>2]),clearValue:xb(v+24),loadOp:Wb[A[v+16>>2]],storeOp:bc[A[v+20>>2]]}}else v=void 0;q.call(m,v)}f=A[b+20>>2];f=0!==f?{view:V(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Wb[A[f+8>>2]],depthStoreOp:bc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Wb[A[f+24>>2]],stencilStoreOp:bc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;
b={label:c,colorAttachments:h,depthStencilAttachment:f,occlusionQuerySet:V(A[b+24>>2]),timestampWrites:zb(A[b+28>>2]),maxDrawCount:d};d=V(a);a=Jc(0);b=d.beginRenderPass(b);U[a>>>0]=b;return a},ga:a=>{var b=V(a);a=Ec(0);b=b.finish();U[a>>>0]=b;return a},ha:a=>{V(a).end()},c:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},oa:(a,b)=>{V(a).setPipeline(V(b))},l:(a,b)=>{var c=W(b+4),d=V(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var k=[],h=0;h<f;++h){var l=k,m=l.push;var q=
b+40*h;var v=A[q+8>>2],n=A[q+32>>2],r=A[q+36>>2],w=A[q+4>>2];v?(n=q+24,n=A[n>>2]+4294967296*z[n+4>>2],-1==n&&(n=void 0),q={binding:w,resource:{buffer:V(v),offset:4294967296*A[q+4+16>>2]+A[q+16>>2],size:n}}):q=n?{binding:w,resource:V(n)}:{binding:w,resource:V(r)};m.call(l,q)}c={label:c,layout:d,entries:k};d=V(a);a=Cc(0);c=d.createBindGroup(c);U[a>>>0]=c;return a},m:(a,b)=>{var c=W(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],k=0;k<d;++k){var h=f,l=h.push,m=b+88*k,q=A[m+4>>2],v=A[m+8>>2];var n=m+24;
var r=A[n+4>>2];n=r?{type:Rb[r],hasDynamicOffset:!!A[n+8>>2],minBindingSize:4294967296*A[n+4+16>>2]+A[n+16>>2]}:void 0;r=(r=A[m+48+4>>2])?{type:$b[r]}:void 0;var w=m+56;var x=A[w+4>>2];w=x?{sampleType:ec[x],viewDimension:fc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;m+=72;m=(x=A[m+4>>2])?{access:ac[x],format:X[A[m+8>>2]],viewDimension:fc[A[m+12>>2]]}:void 0;l.call(h,{binding:q,visibility:v,buffer:n,sampler:r,texture:w,storageTexture:m})}c={label:c,entries:f};d=V(a);a=Dc(0);c=d.createBindGroupLayout(c);
U[a>>>0]=c;return a},ta:(a,b)=>{var c;b&&(c={label:W(b+4)});b=V(a);a=Fc(0);c=b.createCommandEncoder(c);U[a>>>0]=c;return a},va:(a,b)=>{var c=W(b+4);var d=Bb(A[b+12>>2]);b=(b+=16)?{module:V(A[b+4>>2]),constants:Ab(A[b+16>>2],A[b+20>>2]),entryPoint:W(b+8)}:void 0;c={label:c,layout:d,compute:b};d=V(a);a=Hc(0);c=d.createComputePipeline(c);U[a>>>0]=c;return a},xa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],k=0;k<c;++k)f.push(V(A[d+4*k>>2]));b={label:W(b+4),bindGroupLayouts:f};c=V(a);a=Ic(0);b=c.createPipelineLayout(b);
U[a>>>0]=b;return a},ua:(a,b)=>{b=Ob(b);var c=V(a);a=Kc(0);b=c.createRenderPipeline(b);U[a>>>0]=b;return a},ya:(a,b)=>{var c;b&&(c={label:W(b+4),addressModeU:Qb[A[b+12>>2]],addressModeV:Qb[A[b+16>>2]],addressModeW:Qb[A[b+20>>2]],magFilter:Vb[A[b+24>>2]],minFilter:Vb[A[b+28>>2]],mipmapFilter:Xb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Eb[A[b+44>>2]],maxAnisotropy:pa[b+48>>1]});b=V(a);a=Lc(0);c=b.createSampler(c);U[a>>>0]=c;return a},n:(a,b)=>{var c={label:W(b+4),size:yb(b+
28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:dc[A[b+24>>2]],format:X[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>X[f]));a=V(a);d=Nc(0);ub(d,a.createTexture(c));return d},Aa:(a,b)=>{Pb(V(a).limits,b);return 1},d:(a,b)=>V(a).features.has(Ub[b]),Ja:(a,b)=>{a=N(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Rc=W(b+4);b=Mc(0);U[b>>>0]=a;return b},ea:(a,b,c)=>{a=V(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>
V(d));a.submit(b)},h:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);V(a).writeBuffer(V(b),c,y.subarray(d,d+f),0,f)},za:(a,b,c,d,f,k)=>{var h=A[f+8>>2],l=A[f+12>>2],m=b+8;V(a).writeTexture({texture:V(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[m>>2],y:A[m+4>>2],z:A[m+8>>2]},aspect:cc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===h?void 0:h,rowsPerImage:4294967295===l?void 0:l},yb(k))},i:(a,b,c,d,f)=>{V(a).draw(b,c,d>>>0,f>>>0)},
j:(a,b,c,d,f,k)=>{V(a).drawIndexed(b,c,d>>>0,f,k>>>0)},ia:a=>{V(a).end()},b:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ma:(a,b)=>{V(a).setBlendConstant(xb(b))},ka:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);b=V(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Jb[c],d,f)},na:(a,b)=>{V(a).setPipeline(V(b))},pa:(a,b,c,d,f)=>{V(a).setScissorRect(b,c,d,f)},la:(a,b)=>{V(a).setStencilReference(b>>>
0)},ja:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);c=V(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},qa:(a,b,c,d,f,k,h)=>{V(a).setViewport(b,c,d,f,k,h)},Ia:(a,b)=>{var c=A[b+4>>2];a=V(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:V(c),format:X[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Sb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=
Array.from(z.subarray(f>>2,f+4*d>>2),k=>X[k])}b=A[b>>2];0!==b&&(c.colorSpace=Zb[A[b+8>>2]],c.Tc={mode:gc[A[b+12>>2]]});a.configure(c)},Ba:(a,b)=>{a=V(a);try{var c=Nc(0),d=a.getCurrentTexture();U[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:W(b+4),format:X[A[b+12>>2]],dimension:fc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:
d,aspect:cc[A[b+36>>2]]}}b=V(a);a=Oc(0);b=b.createView(c);U[a>>>0]=b;return a}};function Wc(a=[]){var b=vc;a.unshift(ea);var c=a.length,d=tb(4*(c+1)),f=d,k;for(k of a)A[f>>2]=T(k),f+=4;A[f>>2]=0;try{var h=b(c,d);na=h;Ia(h)}catch(l){Ha(l)}}
function Xc(a=da){function b(){e.calledRun=!0;if(!t){Yc.$a();e.onRuntimeInitialized?.();e.noInitialRun||Wc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Xc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Xc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Yc;
(async function(){function a(c){c=Yc=c.exports;S=c.ab;pc=c.bb;qc=e.__sapp_emsc_onpaste=c.cb;rc=e.__sapp_html5_get_ask_leave_site=c.db;sc=e.__sapp_emsc_begin_drop=c.eb;tc=e.__sapp_emsc_drop=c.fb;uc=e.__sapp_emsc_end_drop=c.gb;e.__sapp_emsc_invoke_fetch_cb=c.hb;e.__sapp_emsc_set_fullscreen_flag=c.ib;vc=e._main=c.jb;wc=e.__saudio_emsc_pull=c.kb;xc=e.__sfetch_emsc_head_response=c.lb;yc=e.__sfetch_emsc_get_response=c.mb;zc=e.__sfetch_emsc_failed_http_status=c.nb;Ac=e.__sfetch_emsc_failed_buffer_too_small=
c.ob;Bc=e.__sfetch_emsc_failed_other=c.pb;Cc=c.qb;Dc=c.rb;Ec=c.sb;Fc=c.tb;Gc=c.ub;Hc=c.vb;Ic=c.wb;Jc=c.Ab;Kc=c.Bb;Lc=c.Cb;Mc=c.Db;Nc=c.Eb;Oc=c.Fb;Pc=c.Lb;Qc=c.Mb;Rc=c.Nb;Sc=c.Ob;Tc=c.Qb;Uc=c.Rb;Z=c.Sb;tb=c.Tb;Y=c.Ub;sa=c._a;eb=c.Pb;ra();D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Yc}D++;e.monitorRunDependencies?.(D);var b={a:Vc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("restart-sapp.wasm",ia):ia+"restart-sapp.wasm";
return a((await ya(b)).instance)})();Xc();
