var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var g=console.error.bind(console),p,q=!1,ma,la=a=>a.startsWith("file://"),na,u,y,oa,z,A,pa,B,qa;
function ra(){var a=na.buffer;u=new Int8Array(a);oa=new Int16Array(a);y=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);pa=new Float32Array(a);B=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}var C=0,D=null;function sa(a){e.onAbort?.(a);a="Aborted("+a+")";g(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(e)},za=[],Aa=[],Ba=()=>{var a=e.preRun.shift();Aa.push(a)},Ca=!0,Da=0,E={},Ea=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Fa=a=>{ma=a;Ca||0<Da||(e.onExit?.(a),q=!0);fa(a,new xa(a))},Ga=a=>{ma=a;Fa(a)},Ha=()=>{if(!(Ca||0<Da))try{var a=ma;ma=a;Fa(a)}catch(b){Ea(b)}},Ia=a=>{if(!q)try{a(),Ha()}catch(b){Ea(b)}},Qa=(a,b)=>{Ja=a;Ka=b;if(F)if(La||=!0,0==a)G=function(){setTimeout(H,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)G=function(){Na(H)};else if(2==a){if("undefined"==
typeof Oa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Oa=setImmediate;G=function(){Oa(H)}}},Za=(a,b,c,d,f)=>{function h(){return k<Ra?(Ha(),!1):!0}F=a;Sa=d;var k=Ra;La=!1;H=function(){if(!q)if(0<Ta.length){var m=
Ta.shift();m.Nb(m.Db);if(Ua){var n=Ua,t=0==n%1?n-1:Math.floor(n);Ua=m.Gb?t:(8*n+(t+.5))/9}e.setStatus&&(m=e.statusMessage||"Please wait...",n=Ua??0,t=Va.Lb??0,n?n<t?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(m):e.setStatus(""));h()&&setTimeout(H,0)}else if(h())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)G();else{0==Ja&&(Ma=performance.now());a:if(!q){for(m of Xa)if(!1===m())break a;Ia(a);for(n of Ya)n()}h()&&G()}};f||(0<b?Qa(0,1E3/b):Qa(1,1),G());if(c)throw"unwind";},La=!1,G=
null,Ra=0,F=null,Sa=0,Ja=0,Ka=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){G=null;Ra++}var I=0;function Na(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===I)I=b+1E3/60;else for(;b+2>=I;)I+=1E3/60;setTimeout(a,Math.max(I-b,0))}}
var Va={},Ma,H,Oa,Ua,ab="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a=0,b)=>{var c=y;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&ab)return ab.decode(c.subarray(a,d));for(b="";a<d;){var f=c[a++];if(f&128){var h=c[a++]&63;if(192==(f&224))b+=String.fromCharCode((f&31)<<6|h);else{var k=c[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|c[a++]&63;65536>f?b+=String.fromCharCode(f):(f-=65536,b+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else b+=String.fromCharCode(f)}return b},
bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?J(a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],eb,L=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=M.Na[a];b.target.removeEventListener(b.Ma,b.sb,b.Pa);M.Na.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:M.kb&&M.Cb.$a){var a=M.Ta;M.Ta=[];for(var b of a)b.nb(...b.rb)}}function N(a){if(!a.target)return-4;if(a.Sa)a.sb=function(c){++M.kb;M.Cb=a;gb();a.Xa(c);gb();--M.kb},a.target.addEventListener(a.Ma,a.sb,a.Pa),M.Na.push(a);else for(var b=0;b<M.Na.length;++b)M.Na[b].target==a.target&&M.Na[b].Ma==a.Ma&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={Eb:0,Ob:0,lb:0,Ya:0,qb:0,pb:0,jb:0,Kb:0,Rb:0,Jb:0,Mb:0,mb:0,$b:0,ob:0,Qb(a,b,c){u.set(u.subarray(b,b+c),a)},Sb(){for(;M.Na.length;)fb(M.Na.length-1);M.Ta=[]},kb:0,Ta:[],Ib(a,b,c){function d(h,k){if(h.length!=k.length)return!1;for(var m in h)if(h[m]!=k[m])return!1;return!0}for(var f of M.Ta)if(f.nb==a&&d(f.rb,c))return;M.Ta.push({nb:a,vb:b,rb:c});M.Ta.sort((h,k)=>h.vb<k.vb)},Ub(a){M.Ta=M.Ta.filter(b=>b.nb!=a)},Na:[],Tb:(a,b)=>{for(var c=0;c<M.Na.length;++c)M.Na[c].target!=a||b&&b!=M.Na[c].Ma||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},O=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;f++}}d[b]=0}},ib=(a,b,c,d,f,h)=>{M.jb||
(M.jb=P(256));a={target:K(a),Ma:h,Sa:d,Xa:(k=event)=>{var m=k.target.id?k.target.id:"",n=M.jb;O(hb(k.target),n+0,128);O(m,n+128,128);L(d)(f,n,b)&&k.preventDefault()},Pa:c};return N(a)},jb=(a,b,c,d,f,h)=>{M.lb||(M.lb=P(160));a={target:K(a),Ma:h,Sa:d,Xa:k=>{var m=M.lb;B[m>>3]=k.timeStamp;var n=m>>2;z[n+2]=k.location;u[m+12]=k.ctrlKey;u[m+13]=k.shiftKey;u[m+14]=k.altKey;u[m+15]=k.metaKey;u[m+16]=k.repeat;z[n+5]=k.charCode;z[n+6]=k.keyCode;z[n+7]=k.which;O(k.key||"",m+32,32);O(k.code||"",m+64,32);O(k.char||
"",m+96,32);O(k.locale||"",m+128,32);L(d)(f,m,b)&&k.preventDefault()},Pa:c};return N(a)},kb=(a,b,c)=>{B[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=cb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},Q=(a,b,c,d,f,h)=>{M.Ya||(M.Ya=P(64));a=K(a);return N({target:a,$a:"mousemove"!=h&&"mouseenter"!=
h&&"mouseleave"!=h,Ma:h,Sa:d,Xa:(k=event)=>{kb(M.Ya,k,a);L(d)(f,M.Ya,b)&&k.preventDefault()},Pa:c})},lb=(a,b,c,d)=>{M.mb||(M.mb=P(257));return N({target:a,Ma:"pointerlockchange",Sa:d,Xa:(f=event)=>{var h=M.mb,k=document.pointerLockElement;u[h]=!!k;var m=k?.id||"";O(hb(k),h+1,128);O(m,h+129,128);L(d)(20,h,b)&&f.preventDefault()},Pa:c})},mb=(a,b,c,d)=>N({target:a,Ma:"pointerlockerror",Sa:d,Xa:(f=event)=>{L(d)(38,0,b)&&f.preventDefault()},Pa:c}),nb=(a,b,c,d)=>{M.pb||(M.pb=P(36));a=K(a);return N({target:a,
Ma:"resize",Sa:d,Xa:(f=event)=>{if(f.target==a){var h=document.body;if(h){var k=M.pb;z[k>>2]=0;z[k+4>>2]=h.clientWidth;z[k+8>>2]=h.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;L(d)(10,k,b)&&f.preventDefault()}}},Pa:c})},ob=(a,b,c,d,f,h)=>{M.ob||(M.ob=P(1552));a=K(a);return N({target:a,$a:"touchstart"==h||"touchend"==h,Ma:h,Sa:d,Xa:k=>{var m={},n=k.touches;for(var t of n)t.tb=t.ub=0,m[t.identifier]=
t;for(var v of k.changedTouches)v.tb=1,m[v.identifier]=v;for(var l of k.targetTouches)m[l.identifier].ub=1;n=M.ob;B[n>>3]=k.timeStamp;u[n+12]=k.ctrlKey;u[n+13]=k.shiftKey;u[n+14]=k.altKey;u[n+15]=k.metaKey;t=n+16;v=cb(a);l=0;for(let r of Object.values(m))if(m=t>>2,z[m]=r.identifier,z[m+1]=r.screenX,z[m+2]=r.screenY,z[m+3]=r.clientX,z[m+4]=r.clientY,z[m+5]=r.pageX,z[m+6]=r.pageY,u[t+28]=r.tb,u[t+29]=r.ub,z[m+8]=r.clientX-(v.left|0),z[m+9]=r.clientY-(v.top|0),t+=48,31<++l)break;z[n+8>>2]=l;L(d)(f,n,
b)&&k.preventDefault()},Pa:c})},pb=(a,b,c,d)=>{M.qb||(M.qb=P(96));return N({target:a,$a:!0,Ma:"wheel",Sa:d,Xa:(f=event)=>{var h=M.qb;kb(h,f,a);B[h+64>>3]=f.deltaX;B[h+72>>3]=f.deltaY;B[h+80>>3]=f.deltaZ;z[h+88>>2]=f.deltaMode;L(d)(9,h,b)&&f.preventDefault()},Pa:c})},R=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=qb(b);O(a,c,b);return c},rb=[],S=(a,b)=>{rb[a>>>=0]=b},T=a=>{if(a)return rb[a>>>0]},U=a=>{var b=A[a>>2];a=A[a+
4>>2];if(b)return b?J(b,a):"";if(0===a)return""},sb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),tb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",
40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);
c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.Pb&&c("maxImmediateSize",148)},ub=["binding-not-used",,"uniform","storage","read-only-storage"],vb=[,"opaque","premultiplied","unpremultiplied","inherit"],wb=[,"compatibility","core"],xb={1:"core-features-and-limits",
2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",
327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},yb=[,"load","clear"],zb=[,"low-power","high-performance"],Ab=[,"srgb","display-p3"],Bb=["binding-not-used",,"filtering","non-filtering","comparison"],Cb=["binding-not-used",,"write-only","read-only","read-write"],Db=[,"store","discard"],Eb=[,"all","stencil-only","depth-only"],Fb=[,"1d","2d","3d"],V=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm",
"rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8",
"bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb",
"astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],Gb=["binding-not-used",
,"float","unfilterable-float","depth","sint","uint"],Hb=[,"1d","2d","2d-array","cube","cube-array","3d"],Ib=[,"standard","extended"],Jb={undefined:1,unknown:1,destroyed:2},Kb={rgba8unorm:22,bgra8unorm:27},Lb=a=>{var b=W();a();X(b)};e.requestAnimationFrame=Na;e.pauseMainLoop=$a;e.resumeMainLoop=function(){Ra++;var a=Ja,b=Ka,c=F;F=null;Za(c,0,!1,Sa,!0);Qa(a,b);G()};e.preMainLoop&&Xa.push(e.preMainLoop);e.postMainLoop&&Ya.push(e.postMainLoop);e.noExitRuntime&&(Ca=e.noExitRuntime);e.printErr&&(g=e.printErr);
e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
var Mb,Nb,Ob,Pb,Qb,Rb,Sb,P,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,Y,bc,cc,dc,X,qb,W,ec={L:()=>sa(""),I:()=>{Ca=!1;Da=0},J:(a,b)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!b)return 0;var c=setTimeout(()=>{delete E[a];Ia(()=>dc(a,performance.now()))},b);E[a]={id:c,Yb:b};return 0},ba:()=>{$a();F=null},A:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,C:(a,b,c)=>{a=K(a);if(!a)return-4;a=cb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},ca:()=>performance.now(),ha:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}
return requestAnimationFrame(c)},K:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ra();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},h:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),z:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},i:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),r:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),
p:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),q:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),ia:(a,b,c)=>{a=L(a);Za(a,b,c)},x:(a,b,c,d)=>Q(a,b,c,d,5,"mousedown"),u:(a,b,c,d)=>Q(a,b,c,d,33,"mouseenter"),t:(a,b,c,d)=>Q(a,b,c,d,34,"mouseleave"),v:(a,b,c,d)=>Q(a,b,c,d,8,"mousemove"),w:(a,b,c,d)=>Q(a,b,c,d,6,"mouseup"),k:(a,b,c,d)=>document.body?.requestPointerLock?(a=K(a))?lb(a,b,c,d):-4:-1,j:(a,b,c,d)=>document.body?.requestPointerLock?(a=K(a))?mb(a,b,c,d):-4:-1,B:(a,b,c,d)=>nb(a,b,c,d),l:(a,b,c,d)=>ob(a,b,c,d,25,"touchcancel"),
m:(a,b,c,d)=>ob(a,b,c,d,23,"touchend"),n:(a,b,c,d)=>ob(a,b,c,d,24,"touchmove"),o:(a,b,c,d)=>ob(a,b,c,d,22,"touchstart"),s:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?pb(a,b,c,d):-1:-4,P:function(a,b,c,d,f,h){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=T(a);var k={};if(h){var m=A[h+12>>2];if(m){var n=A[h+16>>2];k.requiredFeatures=Array.from(A.subarray(n>>2,n+4*m>>2),l=>xb[l])}var t=A[h+20>>2];if(t){var v={};function l(w,x,
Pa=!1){x=A[t+x>>2];4294967295==x||Pa&&0==x||(v[w]=x)}function r(w,x){x=t+x;var Pa=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=Pa)v[w]=4294967296*A[x+4>>2]+A[x>>2]}l("maxTextureDimension1D",4);l("maxTextureDimension2D",8);l("maxTextureDimension3D",12);l("maxTextureArrayLayers",16);l("maxBindGroups",20);l("maxBindGroupsPlusVertexBuffers",24);l("maxDynamicUniformBuffersPerPipelineLayout",32);l("maxDynamicStorageBuffersPerPipelineLayout",36);l("maxSampledTexturesPerShaderStage",40);l("maxSamplersPerShaderStage",
44);l("maxStorageBuffersPerShaderStage",48);l("maxStorageTexturesPerShaderStage",52);l("maxUniformBuffersPerShaderStage",56);l("minUniformBufferOffsetAlignment",80);l("minStorageBufferOffsetAlignment",84);r("maxUniformBufferBindingSize",64);r("maxStorageBufferBindingSize",72);l("maxVertexBuffers",88);r("maxBufferSize",96);l("maxVertexAttributes",104);l("maxVertexBufferArrayStride",108);l("maxInterStageShaderVariables",112);l("maxColorAttachments",116);l("maxColorAttachmentBytesPerSample",120);l("maxComputeWorkgroupStorageSize",
124);l("maxComputeInvocationsPerWorkgroup",128);l("maxComputeWorkgroupSizeX",132);l("maxComputeWorkgroupSizeY",136);l("maxComputeWorkgroupSizeZ",140);l("maxComputeWorkgroupsPerDimension",144);l("maxImmediateSize",148,!0);k.requiredLimits=v}if(m=A[h+24>>2])m={label:U(m+4)},k.defaultQueue=m;k.label=U(h+4)}a.requestDevice(k).then(l=>{S(f,l.queue);S(d,l);c&&l.lost.then(r=>{l.onuncapturederror=()=>{};var w=W(),x=R(r.message);ac(c,Jb[r.reason],x);X(w)});l.onuncapturederror=r=>{var w=5;r.error instanceof
GPUValidationError?w=2:r.error instanceof GPUOutOfMemoryError?w=3:r.error instanceof GPUInternalError&&(w=4);var x=W();r=R(r.error.message);cc(d,w,r);X(x)};bc(b,1,d,0)},l=>{var r=W();l=R(l.message);bc(b,3,d,l);c&&ac(c,4,l);X(r)})},a:a=>{delete rb[a]},O:(a,b,c)=>{var d=!!A[b+32>>2];b={label:U(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=T(a);try{var f=a.createBuffer(b)}catch(h){return!1}S(c,f);return!0},Q:a=>{a=T(a);a.onuncapturederror=null;a.destroy()},M:()=>
{var a=navigator.gpu.getPreferredCanvasFormat();return Kb[a]},N:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:wb[A[c+4>>2]],powerPreference:zb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.ac=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(h=>{if(h)S(d,h),Y(b,1,d,0);else{h=W();var k=R("WebGPU not available on this browser (requestAdapter returned null)");Y(b,3,d,k);X(h)}},h=>{var k=W();h=R(h.message);Y(b,
4,d,h);X(k)}):(f=W(),a=R("WebGPU not available on this browser (navigator.gpu is not available)"),Y(b,3,d,a),X(f))},H:Fa,qa:function(){e.wb=a=>{0!=Nb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.wb)},ja:function(){e.Bb=a=>{const b=a.clipboardData.getData("text");Lb(()=>{const c=R(b);Mb(c)})};window.addEventListener("paste",e.Bb)},da:function(){e.Vb=[];e.xb=b=>{b.stopPropagation();b.preventDefault()};e.yb=b=>{b.stopPropagation();b.preventDefault()};e.zb=b=>{b.stopPropagation();
b.preventDefault()};e.Ab=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Wb=c;Ob(c.length);for(let f=0;f<c.length;f++)Lb(()=>{const h=R(c[f].name);Pb(f,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Qb(b.clientX,b.clientY,d)};const a=e.Oa;a.addEventListener("dragenter",e.xb,!1);a.addEventListener("dragleave",e.yb,!1);a.addEventListener("dragover",e.zb,!1);a.addEventListener("drop",e.Ab,!1)},oa:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},F:function(a){e.Za&&(URL.revokeObjectURL(e.Za[a].Fb),e.Za[a]=null)},R:function(a,b){0!==b&&(document.title=b?J(b):"");a=a?J(a):"";void 0!==e.canvas&&("object"===typeof e.canvas?bb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.Oa=K(a);e.Oa||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.Oa.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},pa:function(){window.removeEventListener("beforeunload",
e.wb)},ea:function(){window.removeEventListener("paste",e.Bb)},Z:function(){const a=e.Oa;a.removeEventListener("dragenter",e.xb);a.removeEventListener("dragleave",e.yb);a.removeEventListener("dragover",e.zb);a.removeEventListener("drop",e.Ab)},d:function(){e.Oa&&e.Oa.requestPointerLock&&e.Oa.requestPointerLock()},G:function(a,b,c){if(e.Oa){if(0===b)a="none";else if(0!=c)a=e.Za[a].Hb;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.Oa.style.cursor=a}},na:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},ka:function(){return e.Qa?e.Qa.bufferSize:0},ma:function(a,b,c){e.La=null;e.Qa=null;"undefined"!==typeof AudioContext?e.La=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.La=null,console.log("sokol_audio.h: no WebAudio support"));return e.La?(console.log("sokol_audio.h: sample rate ",e.La.sampleRate),e.Qa=e.La.createScriptProcessor(c,0,b),e.Qa.onaudioprocess=d=>{const f=d.outputBuffer.length,h=Sb(f);if(h){const k=d.outputBuffer.numberOfChannels;
for(let m=0;m<k;m++){const n=d.outputBuffer.getChannelData(m);for(let t=0;t<f;t++)n[t]=pa[(h>>2)+(k*t+m)]}}},e.Qa.connect(e.La.destination),a=()=>{e.La&&"suspended"===e.La.state&&e.La.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},la:function(){return e.La?e.La.sampleRate:0},E:function(){const a=e.La;null!==a&&(e.Qa&&e.Qa.disconnect(),a.close(),e.La=null,e.Qa=null)},D:function(a,b){b=
b?J(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},c:(a,b)=>T(a).features.has(xb[b]),X:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=U(b+4);for(var f=A[b+12>>2],h=A[b+16>>2],k=[],m=0;m<f;++m){var n=k,t=n.push;var v=h+56*m;var l=A[v+4>>2];if(0!==l){var r=z[v+8>>2];-1==r&&(r=void 0);var w=v+24;v={view:T(l),depthSlice:r,resolveTarget:T(A[v+12>>2]),clearValue:{r:B[w>>3],g:B[w+8>>3],b:B[w+
16>>3],a:B[w+24>>3]},loadOp:yb[A[v+16>>2]],storeOp:Db[A[v+20>>2]]}}else v=void 0;t.call(n,v)}f=A[b+20>>2];f=0!==f?{view:T(A[f+4>>2]),depthClearValue:pa[f+16>>2],depthLoadOp:yb[A[f+8>>2]],depthStoreOp:Db[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:yb[A[f+24>>2]],stencilStoreOp:Db[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;h=A[b+28>>2];h=0!==h?{querySet:T(A[h+4>>2]),beginningOfPassWriteIndex:A[h+8>>2],endOfPassWriteIndex:A[h+12>>2]}:void 0;b={label:c,colorAttachments:k,
depthStencilAttachment:f,occlusionQuerySet:T(A[b+24>>2]),timestampWrites:h,maxDrawCount:d};a=T(a);d=Xb(0);S(d,a.beginRenderPass(b));return d},U:a=>{a=T(a);var b=Vb(0);S(b,a.finish());return b},V:a=>{T(a).end()},_:(a,b)=>{var c=U(b+4),d=T(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var h=[],k=0;k<f;++k){var m=h,n=m.push;var t=b+40*k;var v=A[t+8>>2],l=A[t+32>>2],r=A[t+36>>2],w=A[t+4>>2];v?(l=t+24,l=A[l>>2]+4294967296*z[l+4>>2],-1==l&&(l=void 0),t={binding:w,resource:{buffer:T(v),offset:4294967296*A[t+
4+16>>2]+A[t+16>>2],size:l}}):t=l?{binding:w,resource:T(l)}:{binding:w,resource:T(r)};n.call(m,t)}c={label:c,layout:d,entries:h};a=T(a);d=Tb(0);S(d,a.createBindGroup(c));return d},$:(a,b)=>{var c=U(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],h=0;h<d;++h){var k=f,m=k.push,n=b+88*h,t=A[n+4>>2],v=A[n+8>>2];var l=n+24;var r=A[l+4>>2];l=r?{type:ub[r],hasDynamicOffset:!!A[l+8>>2],minBindingSize:4294967296*A[l+4+16>>2]+A[l+16>>2]}:void 0;r=(r=A[n+48+4>>2])?{type:Bb[r]}:void 0;var w=n+56;var x=A[w+4>>2];
w=x?{sampleType:Gb[x],viewDimension:Hb[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;n+=72;n=(x=A[n+4>>2])?{access:Cb[x],format:V[A[n+8>>2]],viewDimension:Hb[A[n+12>>2]]}:void 0;m.call(k,{binding:t,visibility:v,buffer:l,sampler:r,texture:w,storageTexture:n})}c={label:c,entries:f};a=T(a);d=Ub(0);S(d,a.createBindGroupLayout(c));return d},g:(a,b)=>{var c;b&&(c={label:U(b+4)});a=T(a);b=Wb(0);S(b,a.createCommandEncoder(c));return b},y:(a,b)=>{var c={label:U(b+4),size:sb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+
48>>2],dimension:Fb[A[b+24>>2]],format:V[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>V[f]));a=T(a);d=Zb(0);S(d,a.createTexture(c));return d},Y:(a,b)=>{tb(T(a).limits,b);return 1},b:(a,b)=>T(a).features.has(xb[b]),ga:(a,b)=>{a=K(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Xb=U(b+4);b=Yb(0);S(b,a);return b},T:(a,b,c)=>{a=T(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>T(d));a.submit(b)},S:function(a,b,c,d,f){c=-9007199254740992>
c||9007199254740992<c?NaN:Number(c);T(a).writeBuffer(T(b),c,y.subarray(d,d+f),0,f)},W:a=>{T(a).end()},f:(a,b,c,d,f)=>{a=T(a);c=T(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},fa:(a,b)=>{var c=A[b+4>>2];a=T(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:T(c),format:V[A[b+8>>2]],usage:A[b+16>>2],alphaMode:vb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),h=>V[h])}b=A[b>>2];0!==
b&&(c.colorSpace=Ab[A[b+8>>2]],c.Zb={mode:Ib[A[b+12>>2]]});a.configure(c)},aa:(a,b)=>{a=T(a);try{var c=Zb(0);S(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},e:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:U(b+4),format:V[A[b+12>>2]],dimension:Hb[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Eb[A[b+36>>2]]}}a=T(a);b=$b(0);S(b,a.createView(c));return b}},
Z;
(async function(){function a(c){Z=c.exports;na=Z.ra;ra();eb=Z.eb;c=Z;e.__sapp_emsc_onpaste=Mb=c.ta;e.__sapp_html5_get_ask_leave_site=Nb=c.ua;e.__sapp_emsc_begin_drop=Ob=c.va;e.__sapp_emsc_drop=Pb=c.wa;e.__sapp_emsc_end_drop=Qb=c.xa;e.__sapp_emsc_invoke_fetch_cb=c.ya;e._main=Rb=c.za;e.__saudio_emsc_pull=Sb=c.Aa;e.__sfetch_emsc_head_response=c.Ba;e.__sfetch_emsc_get_response=c.Ca;e.__sfetch_emsc_failed_http_status=c.Da;e.__sfetch_emsc_failed_buffer_too_small=c.Ea;e.__sfetch_emsc_failed_other=c.Fa;P=
c.Ga;Tb=c.Ha;Ub=c.Ia;Vb=c.Ja;Wb=c.Ka;Xb=c.Ra;Yb=c.Ua;Zb=c.Va;$b=c.Wa;ac=c.ab;Y=c.bb;bc=c.cb;cc=c.db;dc=c.fb;X=c.gb;qb=c.hb;W=c.ib;C--;e.monitorRunDependencies?.(C);0==C&&D&&(c=D,D=null,c());return Z}C++;e.monitorRunDependencies?.(C);var b={a:ec};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ta??=e.locateFile?e.locateFile("saudio-sapp.wasm",ia):ia+"saudio-sapp.wasm";return a((await wa(b)).instance)})();
function fc(a=[]){var b=Rb;a.unshift(ea);var c=a.length,d=qb(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=R(k);f+=4});A[f>>2]=0;try{var h=b(c,d);Ga(h)}catch(k){Ea(k)}}
function gc(a=da){function b(){e.calledRun=!0;if(!q){Z.sa();e.onRuntimeInitialized?.();e.noInitialRun||fc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();za.push(c)}ya(za)}}if(0<C)D=gc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ba();ya(Aa);0<C?D=gc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();gc();
