var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var k=console.error.bind(console),m,p=!1,ma,la=a=>a.startsWith("file://"),u,w,na,z,A,oa,B,pa;
function qa(){var a=ra.buffer;u=new Int8Array(a);na=new Int16Array(a);w=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);oa=new Float32Array(a);B=new Float64Array(a);pa=new BigInt64Array(a);new BigUint64Array(a)}function sa(a){e.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(e)},za=[],Aa=[],Ba=()=>{var a=e.preRun.shift();Aa.push(a)},C=0,D=null,Ca=!0,Da=0,E={},Ea=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Fa=a=>{ma=a;Ca||0<Da||(e.onExit?.(a),p=!0);fa(a,new xa(a))},Ga=()=>{if(!(Ca||0<Da))try{var a=ma;ma=a;Fa(a)}catch(b){Ea(b)}},F=a=>{if(!p)try{a(),Ga()}catch(b){Ea(b)}},Na=(a,b)=>{Ha=a;Ia=b;if(G)if(Ja||=!0,0==a)H=function(){setTimeout(I,Math.max(0,Ka+b-performance.now())|0)};else if(1==a)H=function(){La(I)};else if(2==a){if(!Ma)if(globalThis.setImmediate)Ma=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ma=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}H=function(){Ma(I)}}},Xa=(a,b,c,d,f)=>{function g(){return h<Pa?(Ga(),!1):!0}G=a;Qa=d;var h=Pa;Ja=!1;I=function(){if(!p)if(0<Ra.length){var l=Ra.shift();l.Sb(l.Jb);if(Sa){var q=
Sa,r=0==q%1?q-1:Math.floor(q);Sa=l.Mb?r:(8*q+(r+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",q=Sa??0,r=Ta.Rb??0,q?q<r?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));g()&&setTimeout(I,0)}else if(g())if(Ua=Ua+1|0,1==Ha&&1<Ia&&0!=Ua%Ia)H();else{0==Ha&&(Ka=performance.now());a:if(!p){for(l of Va)if(!1===l())break a;F(a);for(q of Wa)q()}g()&&H()}};f||(0<b?Na(0,1E3/b):Na(1,1),H());if(c)throw"unwind";},Ja=!1,H=null,Pa=0,G=null,Qa=0,Ha=0,Ia=0,Ua=0,
Ra=[],Va=[],Wa=[];function Ya(){H=null;Pa++}var J=0;function La(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===J)J=b+1E3/60;else for(;b+2>=J;)J+=1E3/60;setTimeout(a,Math.max(J-b,0))}}
var Ta={},Ka,I,Ma,Sa,Za=globalThis.TextDecoder&&new TextDecoder,K=(a=0,b)=>{var c=w;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&Za)return Za.decode(c.subarray(a,d));for(b="";a<d;){var f=c[a++];if(f&128){var g=c[a++]&63;if(192==(f&224))b+=String.fromCharCode((f&31)<<6|g);else{var h=c[a++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|c[a++]&63;65536>f?b+=String.fromCharCode(f):(f-=65536,b+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else b+=String.fromCharCode(f)}return b},
$a=[0,globalThis.document??0,globalThis.window??0],L=a=>{a=2<a?a?K(a):"":a;return $a[a]||globalThis.document?.querySelector(a)},ab=a=>0>$a.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},bb=[],M=a=>{var b=bb[a];b||(bb[a]=b=cb.get(a));return b};function db(a){var b=N.La[a];b.target.removeEventListener(b.Pa,b.xb,b.Sa);N.La.splice(a,1)}function eb(){if(navigator.userActivation?navigator.userActivation.isActive:N.pb&&N.Hb.mb){var a=N.ab;N.ab=[];for(var b of a)b.sb(...b.wb)}}
function O(a){if(!a.target)return-4;if(a.Qa)a.xb=function(c){++N.pb;N.Hb=a;eb();a.Va(c);eb();--N.pb},a.target.addEventListener(a.Pa,a.xb,a.Sa),N.La.push(a);else for(var b=0;b<N.La.length;++b)N.La[b].target==a.target&&N.La[b].Pa==a.Pa&&db(b--);return 0}function fb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var N={Kb:0,Tb:0,qb:0,bb:0,vb:0,ub:0,nb:0,Qb:0,Vb:0,Pb:0,ob:0,rb:0,ec:0,tb:0,Wb(){for(;N.La.length;)db(N.La.length-1);N.ab=[]},pb:0,ab:[],Ob(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var l in g)if(g[l]!=h[l])return!1;return!0}for(var f of N.ab)if(f.sb==a&&d(f.wb,c))return;N.ab.push({sb:a,Ab:b,wb:c});N.ab.sort((g,h)=>g.Ab<h.Ab)},Yb(a){N.ab=N.ab.filter(b=>b.sb!=a)},La:[],Xb:(a,b)=>{for(var c=0;c<N.La.length;++c)N.La[c].target!=a||b&&b!=N.La[c].Pa||db(c--)},Zb(a){let b=!1;for(let c=0;c<
N.La.length;++c){const d=N.La[c];d.target===a.target&&d.Ra===a.Ra&&d.Qa===a.Qa&&d.Ta===a.Ta&&(db(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},P=(a,b,c)=>{var d=w;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;
d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0}},gb=(a,b,c,d,f,g)=>{N.nb||(N.nb=Q(256));a={target:L(a),Pa:g,Ra:f,Ta:b,Qa:d,Va:h=>{var l=h.target.id?h.target.id:"",q=N.nb;P(fb(h.target),q+0,128);P(l,q+128,128);M(d)(f,q,b)&&h.preventDefault()},Sa:c};return O(a)},hb=(a,b,c,d,f)=>{N.ob||(N.ob=Q(276));return O({target:a,Pa:f,Ra:19,Ta:b,Qa:d,Va:g=>{var h=N.ob,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,q=!!l;u[h]=q;u[h+1]=N.fullscreenEnabled();var r=q?l:N.Ib,v=r?.id||"";P(fb(r),h+2,128);P(v,h+130,128);z[h+260>>2]=r?r.clientWidth:0;z[h+264>>2]=r?r.clientHeight:0;z[h+268>>2]=screen.width;z[h+272>>2]=screen.height;q&&(N.Ib=l);M(d)(19,h,b)&&g.preventDefault()},Sa:c})},ib=(a,b,c,d,f,g)=>{N.qb||(N.qb=Q(160));a={target:L(a),Pa:g,Ra:f,Ta:b,Qa:d,Va:h=>{var l=N.qb;B[l>>3]=h.timeStamp;var q=l>>2;z[q+2]=h.location;u[l+12]=h.ctrlKey;u[l+13]=h.shiftKey;u[l+14]=h.altKey;u[l+15]=h.metaKey;
u[l+16]=h.repeat;z[q+5]=h.charCode;z[q+6]=h.keyCode;z[q+7]=h.which;P(h.key||"",l+32,32);P(h.code||"",l+64,32);P(h.char||"",l+96,32);P(h.locale||"",l+128,32);M(d)(f,l,b)&&h.preventDefault()},Sa:c};return O(a)},jb=(a,b,c)=>{B[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;na[2*d+14]=b.button;na[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=ab(c);z[d+10]=b.clientX-(a.left|
0);z[d+11]=b.clientY-(a.top|0)},R=(a,b,c,d,f,g)=>{N.bb||(N.bb=Q(64));a=L(a);return O({target:a,mb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Pa:g,Ra:f,Ta:b,Qa:d,Va:h=>{jb(N.bb,h,a);M(d)(f,N.bb,b)&&h.preventDefault()},Sa:c})},kb=(a,b,c,d)=>{N.rb||(N.rb=Q(257));return O({target:a,Pa:"pointerlockchange",Ra:20,Ta:b,Qa:d,Va:f=>{var g=N.rb,h=document.pointerLockElement;u[g]=!!h;var l=h?.id||"";P(fb(h),g+1,128);P(l,g+129,128);M(d)(20,g,b)&&f.preventDefault()},Sa:c})},lb=(a,b,c,d)=>O({target:a,Pa:"pointerlockerror",
Ra:38,Ta:b,Qa:d,Va:f=>{M(d)(38,0,b)&&f.preventDefault()},Sa:c}),mb=(a,b,c,d)=>{N.ub||(N.ub=Q(36));a=L(a);return O({target:a,Pa:"resize",Ra:10,Ta:b,Qa:d,Va:f=>{if(f.target==a){var g=document.body;if(g){var h=N.ub;z[h>>2]=0;z[h+4>>2]=g.clientWidth;z[h+8>>2]=g.clientHeight;z[h+12>>2]=innerWidth;z[h+16>>2]=innerHeight;z[h+20>>2]=outerWidth;z[h+24>>2]=outerHeight;z[h+28>>2]=pageXOffset|0;z[h+32>>2]=pageYOffset|0;M(d)(10,h,b)&&f.preventDefault()}}},Sa:c})},nb=(a,b,c,d,f,g)=>{N.tb||(N.tb=Q(1552));a=L(a);
return O({target:a,mb:"touchstart"==g||"touchend"==g,Pa:g,Ra:f,Ta:b,Qa:d,Va:h=>{var l={},q=h.touches;for(var r of q)r.yb=r.zb=0,l[r.identifier]=r;for(var v of h.changedTouches)v.yb=1,l[v.identifier]=v;for(var n of h.targetTouches)l[n.identifier].zb=1;q=N.tb;B[q>>3]=h.timeStamp;u[q+12]=h.ctrlKey;u[q+13]=h.shiftKey;u[q+14]=h.altKey;u[q+15]=h.metaKey;r=q+16;v=ab(a);n=0;for(let t of Object.values(l))if(l=r>>2,z[l]=t.identifier,z[l+1]=t.screenX,z[l+2]=t.screenY,z[l+3]=t.clientX,z[l+4]=t.clientY,z[l+5]=
t.pageX,z[l+6]=t.pageY,u[r+28]=t.yb,u[r+29]=t.zb,z[l+8]=t.clientX-(v.left|0),z[l+9]=t.clientY-(v.top|0),r+=48,31<++n)break;z[q+8>>2]=n;M(d)(f,q,b)&&h.preventDefault()},Sa:c})},ob=(a,b,c,d)=>{N.vb||(N.vb=Q(96));return O({target:a,mb:!0,Pa:"wheel",Ra:9,Ta:b,Qa:d,Va:f=>{var g=N.vb;jb(g,f,a);B[g+64>>3]=f.deltaX;B[g+72>>3]=f.deltaY;B[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;M(d)(9,g,b)&&f.preventDefault()},Sa:c})},S=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=
d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=pb(b);P(a,c,b);return c},T=[],qb=(a,b)=>{T[a>>>0]=b},U=a=>{if(a)return T[a>>>0]},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?K(b,a):"";if(0===a)return""},rb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),sb=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},tb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",
12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);
pa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);pa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);pa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",
140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.Ub&&c("maxImmediateSize",148)},ub=[,"opaque","premultiplied","unpremultiplied","inherit"],vb=[,"compatibility","core"],wb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",
13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},xb=[,"load","clear"],yb=[,"low-power","high-performance"],zb=[,"srgb","display-p3"],Ab=[,"store","discard"],Bb=[,"all","stencil-only",
"depth-only"],Cb=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint",
"rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm",
"etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb",
"astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],Db=[,"1d","2d","2d-array","cube","cube-array","3d"],Eb=[,"standard","extended"],Fb={undefined:1,unknown:1,destroyed:2},Gb={rgba8unorm:22,bgra8unorm:27},Hb=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=La;e.pauseMainLoop=Ya;e.resumeMainLoop=function(){Pa++;var a=Ha,b=Ia,c=G;G=null;Xa(c,0,!1,Qa,!0);Na(a,b);H()};e.preMainLoop&&Va.push(e.preMainLoop);e.postMainLoop&&Wa.push(e.postMainLoop);
e.noExitRuntime&&(Ca=e.noExitRuntime);e.printErr&&(k=e.printErr);e.wasmBinary&&(m=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var Ib,Jb,Kb,Lb,Mb,Nb,Ob,Q,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Z,Xb,Yb,Zb,Y,pb,X,ra,cb,$b={M:()=>sa(""),J:()=>{Ca=!1;Da=0},K:(a,b)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!b)return 0;var c=setTimeout(()=>{delete E[a];F(()=>Zb(a,performance.now()))},b);E[a]={id:c,cc:b};return 0},ca:()=>{Ya();G=null},B:()=>globalThis.devicePixelRatio??1,D:(a,b,c)=>{a=L(a);if(!a)return-4;a=ab(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},da:()=>performance.now(),ja:(a,b)=>{function c(d){M(a)(d,b)&&requestAnimationFrame(c)}
return requestAnimationFrame(c)},L:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);qa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},i:(a,b,c,d)=>gb(a,b,c,d,12,"blur"),A:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},j:(a,b,c,d)=>gb(a,b,c,d,13,"focus"),h:(a,b,c,d)=>{if(!N.fullscreenEnabled())return-1;
a=L(a);if(!a)return-4;hb(a,b,c,d,"webkitfullscreenchange");return hb(a,b,c,d,"fullscreenchange")},s:(a,b,c,d)=>ib(a,b,c,d,2,"keydown"),q:(a,b,c,d)=>ib(a,b,c,d,1,"keypress"),r:(a,b,c,d)=>ib(a,b,c,d,3,"keyup"),ka:(a,b,c)=>{a=M(a);Xa(a,b,c)},y:(a,b,c,d)=>R(a,b,c,d,5,"mousedown"),v:(a,b,c,d)=>R(a,b,c,d,33,"mouseenter"),u:(a,b,c,d)=>R(a,b,c,d,34,"mouseleave"),w:(a,b,c,d)=>R(a,b,c,d,8,"mousemove"),x:(a,b,c,d)=>R(a,b,c,d,6,"mouseup"),l:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?kb(a,b,c,d):-4:
-1,k:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?lb(a,b,c,d):-4:-1,C:(a,b,c,d)=>mb(a,b,c,d),m:(a,b,c,d)=>nb(a,b,c,d,25,"touchcancel"),n:(a,b,c,d)=>nb(a,b,c,d,23,"touchend"),o:(a,b,c,d)=>nb(a,b,c,d,24,"touchmove"),p:(a,b,c,d)=>nb(a,b,c,d,22,"touchstart"),t:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?ob(a,b,c,d):-1:-4,Q:function(a,b,c,d,f,g){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);var h={};if(g){var l=A[g+
12>>2];if(l){var q=A[g+16>>2];h.requiredFeatures=Array.from(A.subarray(q>>2,q+4*l>>2),n=>wb[n])}var r=A[g+20>>2];if(r){var v={};function n(x,y,Oa=!1){y=A[r+y>>2];4294967295==y||Oa&&0==y||(v[x]=y)}function t(x,y){y=r+y;var Oa=A[y+4>>2];if(4294967295!=A[y>>2]||4294967295!=Oa)v[x]=4294967296*A[y+4>>2]+A[y>>2]}n("maxTextureDimension1D",4);n("maxTextureDimension2D",8);n("maxTextureDimension3D",12);n("maxTextureArrayLayers",16);n("maxBindGroups",20);n("maxBindGroupsPlusVertexBuffers",24);n("maxDynamicUniformBuffersPerPipelineLayout",
32);n("maxDynamicStorageBuffersPerPipelineLayout",36);n("maxSampledTexturesPerShaderStage",40);n("maxSamplersPerShaderStage",44);n("maxStorageBuffersPerShaderStage",48);n("maxStorageTexturesPerShaderStage",52);n("maxUniformBuffersPerShaderStage",56);n("minUniformBufferOffsetAlignment",80);n("minStorageBufferOffsetAlignment",84);t("maxUniformBufferBindingSize",64);t("maxStorageBufferBindingSize",72);n("maxVertexBuffers",88);t("maxBufferSize",96);n("maxVertexAttributes",104);n("maxVertexBufferArrayStride",
108);n("maxInterStageShaderVariables",112);n("maxColorAttachments",116);n("maxColorAttachmentBytesPerSample",120);n("maxComputeWorkgroupStorageSize",124);n("maxComputeInvocationsPerWorkgroup",128);n("maxComputeWorkgroupSizeX",132);n("maxComputeWorkgroupSizeY",136);n("maxComputeWorkgroupSizeZ",140);n("maxComputeWorkgroupsPerDimension",144);n("maxImmediateSize",148,!0);h.requiredLimits=v}if(l=A[g+24>>2])l={label:V(l+4)},h.defaultQueue=l;h.label=V(g+4)}a.requestDevice(h).then(n=>{F(()=>{T[f>>>0]=n.queue;
T[d>>>0]=n;n.lost.then(t=>{F(()=>{n.onuncapturederror=()=>{};var x=X(),y=S(t.message);Wb(c,Fb[t.reason],y);Y(x)})});n.onuncapturederror=t=>{var x=5;t.error instanceof GPUValidationError?x=2:t.error instanceof GPUOutOfMemoryError?x=3:t.error instanceof GPUInternalError&&(x=4);var y=X();t=S(t.error.message);Yb(d,x,t);Y(y)};Xb(b,1,d,0)})},n=>{F(()=>{var t=X(),x=S(n.message);Xb(b,3,d,x);c&&Wb(c,4,x);Y(t)})})},a:a=>{delete T[a]},P:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*
A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(g){return!1}T[c>>>0]=f;return!0},R:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},N:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return Gb[a]},O:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:vb[A[c+4>>2]],powerPreference:yb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.fc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(g=>
{F(()=>{if(g)T[d>>>0]=g,Z(b,1,d,0);else{var h=X(),l=S("WebGPU not available on this browser (requestAdapter returned null)");Z(b,3,d,l);Y(h)}})},g=>{F(()=>{var h=X(),l=S(g.message);Z(b,4,d,l);Y(h)})}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Z(b,3,d,a),Y(f))},I:Fa,sa:function(){e.Bb=a=>{0!=Jb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Bb)},la:function(){e.Gb=a=>{const b=a.clipboardData.getData("text");Hb(()=>{const c=
S(b);Ib(c)})};window.addEventListener("paste",e.Gb)},ea:function(){e.$b=[];e.Cb=b=>{b.stopPropagation();b.preventDefault()};e.Db=b=>{b.stopPropagation();b.preventDefault()};e.Eb=b=>{b.stopPropagation();b.preventDefault()};e.Fb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.ac=c;Kb(c.length);for(let f=0;f<c.length;f++)Hb(()=>{const g=S(c[f].name);Lb(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Mb(b.clientX,b.clientY,d)};const a=e.Wa;
a.addEventListener("dragenter",e.Cb,!1);a.addEventListener("dragleave",e.Db,!1);a.addEventListener("dragover",e.Eb,!1);a.addEventListener("drop",e.Fb,!1)},qa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},G:function(a){e.cb&&(URL.revokeObjectURL(e.cb[a].Lb),e.cb[a]=null)},U:function(a,b){0!==b&&(document.title=b?K(b):"");a=a?K(a):"";void 0!==e.canvas&&("object"===typeof e.canvas?$a[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
e.Wa=L(a);e.Wa||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.Wa.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},ra:function(){window.removeEventListener("beforeunload",e.Bb)},fa:function(){window.removeEventListener("paste",e.Gb)},aa:function(){const a=e.Wa;a.removeEventListener("dragenter",e.Cb);a.removeEventListener("dragleave",e.Db);a.removeEventListener("dragover",e.Eb);a.removeEventListener("drop",e.Fb)},d:function(){e.Wa&&
e.Wa.requestPointerLock&&e.Wa.requestPointerLock()},H:function(a,b,c){if(e.Wa){if(0===b)a="none";else if(0!=c)a=e.cb[a].Nb;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.Wa.style.cursor=a}},pa:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(w.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ma:function(){return e.$a?e.$a.bufferSize:0},oa:function(a,b,c){e.Ka=null;e.$a=null;"undefined"!==typeof AudioContext?e.Ka=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Ka=null,console.log("sokol_audio.h: no WebAudio support"));
return e.Ka?(console.log("sokol_audio.h: sample rate ",e.Ka.sampleRate),e.$a=e.Ka.createScriptProcessor(c,0,b),e.$a.onaudioprocess=d=>{const f=d.outputBuffer.length,g=Ob(f);if(g){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const q=d.outputBuffer.getChannelData(l);for(let r=0;r<f;r++)q[r]=oa[(g>>2)+(h*r+l)]}}},e.$a.connect(e.Ka.destination),a=()=>{e.Ka&&"suspended"===e.Ka.state&&e.Ka.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),
document.addEventListener("keydown",a,{once:!0}),1):0},na:function(){return e.Ka?e.Ka.sampleRate:0},F:function(){const a=e.Ka;null!==a&&(e.$a&&e.$a.disconnect(),a.close(),e.Ka=null,e.$a=null)},E:function(a,b){b=b?K(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},ga:(a,b)=>{tb(U(a).limits,b);return 1},c:(a,b)=>U(a).features.has(wb[b]),Z:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:sb(A[b+12>>2])});b=U(a);a=Rb(0);
c=b.beginComputePass(c);T[a>>>0]=c;return a},Y:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],h=[],l=0;l<f;++l){var q=h,r=q.push;var v=g+56*l;var n=A[v+4>>2];if(0!==n){var t=z[v+8>>2];-1==t&&(t=void 0);var x=v+24;v={view:U(n),depthSlice:t,resolveTarget:U(A[v+12>>2]),clearValue:{r:B[x>>3],g:B[x+8>>3],b:B[x+16>>3],a:B[x+24>>3]},loadOp:xb[A[v+16>>2]],storeOp:Ab[A[v+20>>2]]}}else v=void 0;r.call(q,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+
4>>2]),depthClearValue:oa[f+16>>2],depthLoadOp:xb[A[f+8>>2]],depthStoreOp:Ab[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:xb[A[f+24>>2]],stencilStoreOp:Ab[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:h,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:sb(A[b+28>>2]),maxDrawCount:d};d=U(a);a=Sb(0);b=d.beginRenderPass(b);T[a>>>0]=b;return a},V:a=>{var b=U(a);a=Pb(0);b=b.finish();T[a>>>0]=b;return a},W:a=>{U(a).end()},
g:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},_:(a,b)=>{var c;b&&(c={label:V(b+4)});b=U(a);a=Qb(0);c=b.createCommandEncoder(c);T[a>>>0]=c;return a},z:(a,b)=>{var c={label:V(b+4),size:rb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:Cb[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=Ub(0);qb(d,a.createTexture(c));return d},$:(a,b)=>{tb(U(a).limits,
b);return 1},b:(a,b)=>U(a).features.has(wb[b]),ia:(a,b)=>{a=L(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.bc=V(b+4);b=Tb(0);T[b>>>0]=a;return b},T:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},S:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,w.subarray(d,d+f),0,f)},X:a=>{U(a).end()},f:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ha:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=
[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:ub[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),g=>W[g])}b=A[b>>2];0!==b&&(c.colorSpace=zb[A[b+8>>2]],c.dc={mode:Eb[A[b+12>>2]]});a.configure(c)},ba:(a,b)=>{a=U(a);try{var c=Ub(0),d=a.getCurrentTexture();T[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},e:(a,b)=>{if(b){var c=A[b+
24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:Db[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Bb[A[b+36>>2]]}}b=U(a);a=Vb(0);b=b.createView(c);T[a>>>0]=b;return a}};function ac(a=[]){var b=Nb;a.unshift(ea);var c=a.length,d=pb(4*(c+1)),f=d,g;for(g of a)A[f>>2]=S(g),f+=4;A[f>>2]=0;try{var h=b(c,d);ma=h;Fa(h)}catch(l){Ea(l)}}
function bc(a=da){function b(){e.calledRun=!0;if(!p){cc.ua();e.onRuntimeInitialized?.();e.noInitialRun||ac(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();za.push(c)}ya(za)}}if(0<C)D=bc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ba();ya(Aa);0<C?D=bc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var cc;
(async function(){function a(c){c=cc=c.exports;Ib=e.__sapp_emsc_onpaste=c.va;Jb=e.__sapp_html5_get_ask_leave_site=c.wa;Kb=e.__sapp_emsc_begin_drop=c.xa;Lb=e.__sapp_emsc_drop=c.ya;Mb=e.__sapp_emsc_end_drop=c.za;e.__sapp_emsc_invoke_fetch_cb=c.Aa;e.__sapp_emsc_set_fullscreen_flag=c.Ba;Nb=e._main=c.Ca;Ob=e.__saudio_emsc_pull=c.Da;e.__sfetch_emsc_head_response=c.Ea;e.__sfetch_emsc_get_response=c.Fa;e.__sfetch_emsc_failed_http_status=c.Ga;e.__sfetch_emsc_failed_buffer_too_small=c.Ha;e.__sfetch_emsc_failed_other=
c.Ia;Q=c.Ja;Pb=c.Ma;Qb=c.Na;Rb=c.Oa;Sb=c.Ua;Tb=c.Xa;Ub=c.Ya;Vb=c.Za;Wb=c.db;Z=c.eb;Xb=c.fb;Yb=c.gb;Zb=c.ib;Y=c.jb;pb=c.kb;X=c.lb;ra=c.ta;cb=c.hb;qa();C--;e.monitorRunDependencies?.(C);0==C&&D&&(c=D,D=null,c());return cc}C++;e.monitorRunDependencies?.(C);var b={a:$b};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ta??=e.locateFile?e.locateFile("saudio-sapp.wasm",ia):ia+"saudio-sapp.wasm";return a((await wa(b)).instance)})();bc();
