var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var g=console.error.bind(console),p,q=!1,ma,la=a=>a.startsWith("file://"),u,y,na,z,A,oa,B,pa;
function qa(){var a=ra.buffer;u=new Int8Array(a);na=new Int16Array(a);y=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);oa=new Float32Array(a);B=new Float64Array(a);pa=new BigInt64Array(a);new BigUint64Array(a)}function sa(a){e.onAbort?.(a);a="Aborted("+a+")";g(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(e)},za=[],Aa=[],Ba=()=>{var a=e.preRun.shift();Aa.push(a)},C=0,D=null,Ca=!0,Da=0,E={},Ea=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Fa=a=>{ma=a;Ca||0<Da||(e.onExit?.(a),q=!0);fa(a,new xa(a))},Ga=()=>{if(!(Ca||0<Da))try{var a=ma;ma=a;Fa(a)}catch(b){Ea(b)}},F=a=>{if(!q)try{a(),Ga()}catch(b){Ea(b)}},Na=(a,b)=>{Ha=a;Ia=b;if(G)if(Ja||=!0,0==a)H=function(){setTimeout(I,Math.max(0,Ka+b-performance.now())|0)};else if(1==a)H=function(){La(I)};else if(2==a){if(!Ma)if(globalThis.setImmediate)Ma=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ma=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}H=function(){Ma(I)}}},Xa=(a,b,c,d,f)=>{function h(){return k<Oa?(Ga(),!1):!0}G=a;Qa=d;var k=Oa;Ja=!1;I=function(){if(!q)if(0<Ra.length){var l=Ra.shift();l.Wb(l.Nb);if(Sa){var n=
Sa,r=0==n%1?n-1:Math.floor(n);Sa=l.Qb?r:(8*n+(r+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",n=Sa??0,r=Ta.Vb??0,n?n<r?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));h()&&setTimeout(I,0)}else if(h())if(Ua=Ua+1|0,1==Ha&&1<Ia&&0!=Ua%Ia)H();else{0==Ha&&(Ka=performance.now());a:if(!q){for(l of Va)if(!1===l())break a;F(a);for(n of Wa)n()}h()&&H()}};f||(0<b?Na(0,1E3/b):Na(1,1),H());if(c)throw"unwind";},Ja=!1,H=null,Oa=0,G=null,Qa=0,Ha=0,Ia=0,Ua=0,
Ra=[],Va=[],Wa=[];function Ya(){H=null;Oa++}var J=0;function La(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===J)J=b+1E3/60;else for(;b+2>=J;)J+=1E3/60;setTimeout(a,Math.max(J-b,0))}}
var Ta={},Ka,I,Ma,Sa,Za=globalThis.TextDecoder&&new TextDecoder,K=(a=0,b)=>{var c=y;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&Za)return Za.decode(c.subarray(a,d));for(b="";a<d;){var f=c[a++];if(f&128){var h=c[a++]&63;if(192==(f&224))b+=String.fromCharCode((f&31)<<6|h);else{var k=c[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|c[a++]&63;65536>f?b+=String.fromCharCode(f):(f-=65536,b+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else b+=String.fromCharCode(f)}return b},
$a=[0,globalThis.document??0,globalThis.window??0],L=a=>{a=2<a?a?K(a):"":a;return $a[a]||globalThis.document?.querySelector(a)},ab=a=>0>$a.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},bb=[],M=a=>{var b=bb[a];b||(bb[a]=b=cb.get(a));return b};function db(a){var b=N.Sa[a];b.target.removeEventListener(b.Ta,b.Bb,b.Xa);N.Sa.splice(a,1)}function eb(){if(navigator.userActivation?navigator.userActivation.isActive:N.tb&&N.Lb.qb){var a=N.eb;N.eb=[];for(var b of a)b.wb(...b.Ab)}}
function O(a){if(!a.target)return-4;if(a.Ua)a.Bb=function(c){++N.tb;N.Lb=a;eb();a.ab(c);eb();--N.tb},a.target.addEventListener(a.Ta,a.Bb,a.Xa),N.Sa.push(a);else for(var b=0;b<N.Sa.length;++b)N.Sa[b].target==a.target&&N.Sa[b].Ta==a.Ta&&db(b--);return 0}function fb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var N={Ob:0,Xb:0,ub:0,ob:0,zb:0,yb:0,rb:0,Ub:0,Zb:0,Tb:0,sb:0,vb:0,jc:0,xb:0,$b(){for(;N.Sa.length;)db(N.Sa.length-1);N.eb=[]},tb:0,eb:[],Sb(a,b,c){function d(h,k){if(h.length!=k.length)return!1;for(var l in h)if(h[l]!=k[l])return!1;return!0}for(var f of N.eb)if(f.wb==a&&d(f.Ab,c))return;N.eb.push({wb:a,Eb:b,Ab:c});N.eb.sort((h,k)=>h.Eb<k.Eb)},bc(a){N.eb=N.eb.filter(b=>b.wb!=a)},Sa:[],ac:(a,b)=>{for(var c=0;c<N.Sa.length;++c)N.Sa[c].target!=a||b&&b!=N.Sa[c].Ta||db(c--)},cc(a){let b=!1;for(let c=0;c<
N.Sa.length;++c){const d=N.Sa[c];d.target===a.target&&d.Va===a.Va&&d.Ua===a.Ua&&d.Ya===a.Ya&&(db(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},P=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;
d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;f++}}d[b]=0}},gb=(a,b,c,d,f,h)=>{N.rb||(N.rb=Q(256));a={target:L(a),Ta:h,Va:f,Ya:b,Ua:d,ab:k=>{var l=k.target.id?k.target.id:"",n=N.rb;P(fb(k.target),n+0,128);P(l,n+128,128);M(d)(f,n,b)&&k.preventDefault()},Xa:c};return O(a)},hb=(a,b,c,d,f)=>{N.sb||(N.sb=Q(276));return O({target:a,Ta:f,Va:19,Ya:b,Ua:d,ab:h=>{var k=N.sb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,n=!!l;u[k]=n;u[k+1]=N.fullscreenEnabled();var r=n?l:N.Mb,w=r?.id||"";P(fb(r),k+2,128);P(w,k+130,128);z[k+260>>2]=r?r.clientWidth:0;z[k+264>>2]=r?r.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;n&&(N.Mb=l);M(d)(19,k,b)&&h.preventDefault()},Xa:c})},ib=(a,b,c,d,f,h)=>{N.ub||(N.ub=Q(160));a={target:L(a),Ta:h,Va:f,Ya:b,Ua:d,ab:k=>{var l=N.ub;B[l>>3]=k.timeStamp;var n=l>>2;z[n+2]=k.location;u[l+12]=k.ctrlKey;u[l+13]=k.shiftKey;u[l+14]=k.altKey;u[l+15]=k.metaKey;
u[l+16]=k.repeat;z[n+5]=k.charCode;z[n+6]=k.keyCode;z[n+7]=k.which;P(k.key||"",l+32,32);P(k.code||"",l+64,32);P(k.char||"",l+96,32);P(k.locale||"",l+128,32);M(d)(f,l,b)&&k.preventDefault()},Xa:c};return O(a)},jb=(a,b,c)=>{B[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;na[2*d+14]=b.button;na[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=ab(c);z[d+10]=b.clientX-(a.left|
0);z[d+11]=b.clientY-(a.top|0)},R=(a,b,c,d,f,h)=>{N.ob||(N.ob=Q(64));a=L(a);return O({target:a,qb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Ta:h,Va:f,Ya:b,Ua:d,ab:k=>{jb(N.ob,k,a);M(d)(f,N.ob,b)&&k.preventDefault()},Xa:c})},kb=(a,b,c,d)=>{N.vb||(N.vb=Q(257));return O({target:a,Ta:"pointerlockchange",Va:20,Ya:b,Ua:d,ab:f=>{var h=N.vb,k=document.pointerLockElement;u[h]=!!k;var l=k?.id||"";P(fb(k),h+1,128);P(l,h+129,128);M(d)(20,h,b)&&f.preventDefault()},Xa:c})},lb=(a,b,c,d)=>O({target:a,Ta:"pointerlockerror",
Va:38,Ya:b,Ua:d,ab:f=>{M(d)(38,0,b)&&f.preventDefault()},Xa:c}),mb=(a,b,c,d)=>{N.yb||(N.yb=Q(36));a=L(a);return O({target:a,Ta:"resize",Va:10,Ya:b,Ua:d,ab:f=>{if(f.target==a){var h=document.body;if(h){var k=N.yb;z[k>>2]=0;z[k+4>>2]=h.clientWidth;z[k+8>>2]=h.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;M(d)(10,k,b)&&f.preventDefault()}}},Xa:c})},nb=(a,b,c,d,f,h)=>{N.xb||(N.xb=Q(1552));a=L(a);
return O({target:a,qb:"touchstart"==h||"touchend"==h,Ta:h,Va:f,Ya:b,Ua:d,ab:k=>{var l={},n=k.touches;for(var r of n)r.Cb=r.Db=0,l[r.identifier]=r;for(var w of k.changedTouches)w.Cb=1,l[w.identifier]=w;for(var m of k.targetTouches)l[m.identifier].Db=1;n=N.xb;B[n>>3]=k.timeStamp;u[n+12]=k.ctrlKey;u[n+13]=k.shiftKey;u[n+14]=k.altKey;u[n+15]=k.metaKey;r=n+16;w=ab(a);m=0;for(let t of Object.values(l))if(l=r>>2,z[l]=t.identifier,z[l+1]=t.screenX,z[l+2]=t.screenY,z[l+3]=t.clientX,z[l+4]=t.clientY,z[l+5]=
t.pageX,z[l+6]=t.pageY,u[r+28]=t.Cb,u[r+29]=t.Db,z[l+8]=t.clientX-(w.left|0),z[l+9]=t.clientY-(w.top|0),r+=48,31<++m)break;z[n+8>>2]=m;M(d)(f,n,b)&&k.preventDefault()},Xa:c})},ob=(a,b,c,d)=>{N.zb||(N.zb=Q(96));return O({target:a,qb:!0,Ta:"wheel",Va:9,Ya:b,Ua:d,ab:f=>{var h=N.zb;jb(h,f,a);B[h+64>>3]=f.deltaX;B[h+72>>3]=f.deltaY;B[h+80>>3]=f.deltaZ;z[h+88>>2]=f.deltaMode;M(d)(9,h,b)&&f.preventDefault()},Xa:c})},S=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=
d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=pb(b);P(a,c,b);return c},T=[],qb=(a,b)=>{T[a>>>0]=b},U=a=>{if(a)return T[a>>>0]},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?K(b,a):"";if(0===a)return""},rb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),sb=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},tb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",
12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);
pa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);pa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);pa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",
140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.Yb&&c("maxImmediateSize",148)},ub=["binding-not-used",,"uniform","storage","read-only-storage"],vb=[,"opaque","premultiplied","unpremultiplied","inherit"],wb=[,"compatibility","core"],xb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",
10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},yb=[,"load","clear"],zb=[,"low-power","high-performance"],
Ab=[,"srgb","display-p3"],Bb=["binding-not-used",,"filtering","non-filtering","comparison"],Cb=["binding-not-used",,"write-only","read-only","read-write"],Db=[,"store","discard"],Eb=[,"all","stencil-only","depth-only"],Fb=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm",
"rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm",
"bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm",
"astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],Gb=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],Hb=[,"1d","2d","2d-array","cube","cube-array","3d"],Ib=[,"standard","extended"],
Jb={undefined:1,unknown:1,destroyed:2},Kb={rgba8unorm:22,bgra8unorm:27},Lb=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=La;e.pauseMainLoop=Ya;e.resumeMainLoop=function(){Oa++;var a=Ha,b=Ia,c=G;G=null;Xa(c,0,!1,Qa,!0);Na(a,b);H()};e.preMainLoop&&Va.push(e.preMainLoop);e.postMainLoop&&Wa.push(e.postMainLoop);e.noExitRuntime&&(Ca=e.noExitRuntime);e.printErr&&(g=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var Mb,Nb,Ob,Pb,Qb,Rb,Sb,Q,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,Z,cc,dc,ec,Y,pb,X,ra,cb,fc={M:()=>sa(""),J:()=>{Ca=!1;Da=0},K:(a,b)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!b)return 0;var c=setTimeout(()=>{delete E[a];F(()=>ec(a,performance.now()))},b);E[a]={id:c,hc:b};return 0},ea:()=>{Ya();G=null},B:()=>globalThis.devicePixelRatio??1,D:(a,b,c)=>{a=L(a);if(!a)return-4;a=ab(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},fa:()=>performance.now(),la:(a,b)=>{function c(d){M(a)(d,b)&&requestAnimationFrame(c)}
return requestAnimationFrame(c)},L:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);qa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},i:(a,b,c,d)=>gb(a,b,c,d,12,"blur"),A:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},j:(a,b,c,d)=>gb(a,b,c,d,13,"focus"),h:(a,b,c,d)=>{if(!N.fullscreenEnabled())return-1;
a=L(a);if(!a)return-4;hb(a,b,c,d,"webkitfullscreenchange");return hb(a,b,c,d,"fullscreenchange")},s:(a,b,c,d)=>ib(a,b,c,d,2,"keydown"),q:(a,b,c,d)=>ib(a,b,c,d,1,"keypress"),r:(a,b,c,d)=>ib(a,b,c,d,3,"keyup"),ma:(a,b,c)=>{a=M(a);Xa(a,b,c)},y:(a,b,c,d)=>R(a,b,c,d,5,"mousedown"),v:(a,b,c,d)=>R(a,b,c,d,33,"mouseenter"),u:(a,b,c,d)=>R(a,b,c,d,34,"mouseleave"),w:(a,b,c,d)=>R(a,b,c,d,8,"mousemove"),x:(a,b,c,d)=>R(a,b,c,d,6,"mouseup"),l:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?kb(a,b,c,d):-4:
-1,k:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?lb(a,b,c,d):-4:-1,C:(a,b,c,d)=>mb(a,b,c,d),m:(a,b,c,d)=>nb(a,b,c,d,25,"touchcancel"),n:(a,b,c,d)=>nb(a,b,c,d,23,"touchend"),o:(a,b,c,d)=>nb(a,b,c,d,24,"touchmove"),p:(a,b,c,d)=>nb(a,b,c,d,22,"touchstart"),t:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?ob(a,b,c,d):-1:-4,Q:function(a,b,c,d,f,h){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);var k={};if(h){var l=A[h+
12>>2];if(l){var n=A[h+16>>2];k.requiredFeatures=Array.from(A.subarray(n>>2,n+4*l>>2),m=>xb[m])}var r=A[h+20>>2];if(r){var w={};function m(v,x,Pa=!1){x=A[r+x>>2];4294967295==x||Pa&&0==x||(w[v]=x)}function t(v,x){x=r+x;var Pa=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=Pa)w[v]=4294967296*A[x+4>>2]+A[x>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",24);m("maxDynamicUniformBuffersPerPipelineLayout",
32);m("maxDynamicStorageBuffersPerPipelineLayout",36);m("maxSampledTexturesPerShaderStage",40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);t("maxUniformBufferBindingSize",64);t("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);t("maxBufferSize",96);m("maxVertexAttributes",104);m("maxVertexBufferArrayStride",
108);m("maxInterStageShaderVariables",112);m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",148,!0);k.requiredLimits=w}if(l=A[h+24>>2])l={label:V(l+4)},k.defaultQueue=l;k.label=V(h+4)}a.requestDevice(k).then(m=>{F(()=>{T[f>>>0]=m.queue;
T[d>>>0]=m;m.lost.then(t=>{F(()=>{m.onuncapturederror=()=>{};var v=X(),x=S(t.message);bc(c,Jb[t.reason],x);Y(v)})});m.onuncapturederror=t=>{var v=5;t.error instanceof GPUValidationError?v=2:t.error instanceof GPUOutOfMemoryError?v=3:t.error instanceof GPUInternalError&&(v=4);var x=X();t=S(t.error.message);dc(d,v,t);Y(x)};cc(b,1,d,0)})},m=>{F(()=>{var t=X(),v=S(m.message);cc(b,3,d,v);c&&bc(c,4,v);Y(t)})})},a:a=>{delete T[a]},P:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*
A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(h){return!1}T[c>>>0]=f;return!0},R:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},N:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return Kb[a]},O:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:wb[A[c+4>>2]],powerPreference:zb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.kc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(h=>
{F(()=>{if(h)T[d>>>0]=h,Z(b,1,d,0);else{var k=X(),l=S("WebGPU not available on this browser (requestAdapter returned null)");Z(b,3,d,l);Y(k)}})},h=>{F(()=>{var k=X(),l=S(h.message);Z(b,4,d,l);Y(k)})}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Z(b,3,d,a),Y(f))},I:Fa,ua:function(){e.Fb=a=>{0!=Nb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Fb)},na:function(){e.Kb=a=>{const b=a.clipboardData.getData("text");Lb(()=>{const c=
S(b);Mb(c)})};window.addEventListener("paste",e.Kb)},ga:function(){e.dc=[];e.Gb=b=>{b.stopPropagation();b.preventDefault()};e.Hb=b=>{b.stopPropagation();b.preventDefault()};e.Ib=b=>{b.stopPropagation();b.preventDefault()};e.Jb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.ec=c;Ob(c.length);for(let f=0;f<c.length;f++)Lb(()=>{const h=S(c[f].name);Pb(f,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Qb(b.clientX,b.clientY,d)};const a=e.bb;
a.addEventListener("dragenter",e.Gb,!1);a.addEventListener("dragleave",e.Hb,!1);a.addEventListener("dragover",e.Ib,!1);a.addEventListener("drop",e.Jb,!1)},sa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},G:function(a){e.pb&&(URL.revokeObjectURL(e.pb[a].Pb),e.pb[a]=null)},W:function(a,b){0!==b&&(document.title=b?K(b):"");a=a?K(a):"";void 0!==e.canvas&&("object"===typeof e.canvas?$a[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
e.bb=L(a);e.bb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.bb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},ta:function(){window.removeEventListener("beforeunload",e.Fb)},ha:function(){window.removeEventListener("paste",e.Kb)},ca:function(){const a=e.bb;a.removeEventListener("dragenter",e.Gb);a.removeEventListener("dragleave",e.Hb);a.removeEventListener("dragover",e.Ib);a.removeEventListener("drop",e.Jb)},d:function(){e.bb&&
e.bb.requestPointerLock&&e.bb.requestPointerLock()},H:function(a,b,c){if(e.bb){if(0===b)a="none";else if(0!=c)a=e.pb[a].Rb;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.bb.style.cursor=a}},ra:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},oa:function(){return e.cb?e.cb.bufferSize:0},qa:function(a,b,c){e.Ra=null;e.cb=null;"undefined"!==typeof AudioContext?e.Ra=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Ra=null,console.log("sokol_audio.h: no WebAudio support"));
return e.Ra?(console.log("sokol_audio.h: sample rate ",e.Ra.sampleRate),e.cb=e.Ra.createScriptProcessor(c,0,b),e.cb.onaudioprocess=d=>{const f=d.outputBuffer.length,h=Sb(f);if(h){const k=d.outputBuffer.numberOfChannels;for(let l=0;l<k;l++){const n=d.outputBuffer.getChannelData(l);for(let r=0;r<f;r++)n[r]=oa[(h>>2)+(k*r+l)]}}},e.cb.connect(e.Ra.destination),a=()=>{e.Ra&&"suspended"===e.Ra.state&&e.Ra.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),
document.addEventListener("keydown",a,{once:!0}),1):0},pa:function(){return e.Ra?e.Ra.sampleRate:0},F:function(){const a=e.Ra;null!==a&&(e.cb&&e.cb.disconnect(),a.close(),e.Ra=null,e.cb=null)},E:function(a,b){b=b?K(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},ia:(a,b)=>{tb(U(a).limits,b);return 1},c:(a,b)=>U(a).features.has(xb[b]),Z:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:sb(A[b+12>>2])});b=U(a);a=Xb(0);
c=b.beginComputePass(c);T[a>>>0]=c;return a},Y:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],h=A[b+16>>2],k=[],l=0;l<f;++l){var n=k,r=n.push;var w=h+56*l;var m=A[w+4>>2];if(0!==m){var t=z[w+8>>2];-1==t&&(t=void 0);var v=w+24;w={view:U(m),depthSlice:t,resolveTarget:U(A[w+12>>2]),clearValue:{r:B[v>>3],g:B[v+8>>3],b:B[v+16>>3],a:B[v+24>>3]},loadOp:yb[A[w+16>>2]],storeOp:Db[A[w+20>>2]]}}else w=void 0;r.call(n,w)}f=A[b+20>>2];f=0!==f?{view:U(A[f+
4>>2]),depthClearValue:oa[f+16>>2],depthLoadOp:yb[A[f+8>>2]],depthStoreOp:Db[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:yb[A[f+24>>2]],stencilStoreOp:Db[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:sb(A[b+28>>2]),maxDrawCount:d};d=U(a);a=Yb(0);b=d.beginRenderPass(b);T[a>>>0]=b;return a},U:a=>{var b=U(a);a=Vb(0);b=b.finish();T[a>>>0]=b;return a},V:a=>{U(a).end()},
g:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},aa:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var h=[],k=0;k<f;++k){var l=h,n=l.push;var r=b+40*k;var w=A[r+8>>2],m=A[r+32>>2],t=A[r+36>>2],v=A[r+4>>2];w?(m=r+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),r={binding:v,resource:{buffer:U(w),offset:4294967296*A[r+4+16>>2]+A[r+16>>2],size:m}}):r=m?{binding:v,resource:U(m)}:{binding:v,resource:U(t)};n.call(l,r)}c={label:c,layout:d,entries:h};
d=U(a);a=Tb(0);c=d.createBindGroup(c);T[a>>>0]=c;return a},ba:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],h=0;h<d;++h){var k=f,l=k.push,n=b+88*h,r=A[n+4>>2],w=A[n+8>>2];var m=n+24;var t=A[m+4>>2];m=t?{type:ub[t],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;t=(t=A[n+48+4>>2])?{type:Bb[t]}:void 0;var v=n+56;var x=A[v+4>>2];v=x?{sampleType:Gb[x],viewDimension:Hb[A[v+8>>2]],multisampled:!!A[v+12>>2]}:void 0;n+=72;n=(x=A[n+4>>2])?{access:Cb[x],
format:W[A[n+8>>2]],viewDimension:Hb[A[n+12>>2]]}:void 0;l.call(k,{binding:r,visibility:w,buffer:m,sampler:t,texture:v,storageTexture:n})}c={label:c,entries:f};d=U(a);a=Ub(0);c=d.createBindGroupLayout(c);T[a>>>0]=c;return a},_:(a,b)=>{var c;b&&(c={label:V(b+4)});b=U(a);a=Wb(0);c=b.createCommandEncoder(c);T[a>>>0]=c;return a},z:(a,b)=>{var c={label:V(b+4),size:rb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:Fb[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=
A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=$b(0);qb(d,a.createTexture(c));return d},$:(a,b)=>{tb(U(a).limits,b);return 1},b:(a,b)=>U(a).features.has(xb[b]),ka:(a,b)=>{a=L(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.fc=V(b+4);b=Zb(0);T[b>>>0]=a;return b},T:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},S:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),
0,f)},X:a=>{U(a).end()},f:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ja:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:vb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),h=>W[h])}b=A[b>>2];0!==b&&(c.colorSpace=Ab[A[b+8>>2]],c.ic={mode:Ib[A[b+12>>2]]});a.configure(c)},da:(a,
b)=>{a=U(a);try{var c=$b(0),d=a.getCurrentTexture();T[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},e:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:Hb[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Eb[A[b+36>>2]]}}b=U(a);a=ac(0);b=b.createView(c);T[a>>>0]=b;return a}};
function gc(a=[]){var b=Rb;a.unshift(ea);var c=a.length,d=pb(4*(c+1)),f=d,h;for(h of a)A[f>>2]=S(h),f+=4;A[f>>2]=0;try{var k=b(c,d);ma=k;Fa(k)}catch(l){Ea(l)}}
function hc(a=da){function b(){e.calledRun=!0;if(!q){ic.wa();e.onRuntimeInitialized?.();e.noInitialRun||gc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();za.push(c)}ya(za)}}if(0<C)D=hc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ba();ya(Aa);0<C?D=hc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var ic;
(async function(){function a(c){c=ic=c.exports;Mb=e.__sapp_emsc_onpaste=c.xa;Nb=e.__sapp_html5_get_ask_leave_site=c.ya;Ob=e.__sapp_emsc_begin_drop=c.za;Pb=e.__sapp_emsc_drop=c.Aa;Qb=e.__sapp_emsc_end_drop=c.Ba;e.__sapp_emsc_invoke_fetch_cb=c.Ca;e.__sapp_emsc_set_fullscreen_flag=c.Da;Rb=e._main=c.Ea;Sb=e.__saudio_emsc_pull=c.Fa;e.__sfetch_emsc_head_response=c.Ga;e.__sfetch_emsc_get_response=c.Ha;e.__sfetch_emsc_failed_http_status=c.Ia;e.__sfetch_emsc_failed_buffer_too_small=c.Ja;e.__sfetch_emsc_failed_other=
c.Ka;Q=c.La;Tb=c.Ma;Ub=c.Na;Vb=c.Oa;Wb=c.Pa;Xb=c.Qa;Yb=c.Wa;Zb=c.Za;$b=c._a;ac=c.$a;bc=c.fb;Z=c.gb;cc=c.hb;dc=c.ib;ec=c.kb;Y=c.lb;pb=c.mb;X=c.nb;ra=c.va;cb=c.jb;qa();C--;e.monitorRunDependencies?.(C);0==C&&D&&(c=D,D=null,c());return ic}C++;e.monitorRunDependencies?.(C);var b={a:fc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ta??=e.locateFile?e.locateFile("saudio-sapp.wasm",ia):ia+"saudio-sapp.wasm";return a((await wa(b)).instance)})();hc();
