var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var g=console.error.bind(console),n,r=!1,ma,la=a=>a.startsWith("file://"),u,y,na,oa,z,A,B,C,pa;
function qa(){var a=ra.buffer;u=new Int8Array(a);na=new Int16Array(a);y=new Uint8Array(a);oa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);pa=new BigInt64Array(a);new BigUint64Array(a)}function sa(a){e.onAbort?.(a);a="Aborted("+a+")";g(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function xa(a){var b=ua;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(e)},Aa=[],Ba=[],Ca=()=>{var a=e.preRun.shift();Ba.push(a)},D=0,E=null,Da=!0,Ea=0,F={},Fa=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ga=a=>{ma=a;Da||0<Ea||(e.onExit?.(a),r=!0);fa(a,new ya(a))},Ha=a=>{ma=a;Ga(a)},Ia=()=>{if(!(Da||0<Ea))try{var a=ma;ma=a;Ga(a)}catch(b){Fa(b)}},G=a=>{if(!r)try{a(),Ia()}catch(b){Fa(b)}},Pa=(a,b)=>{Ja=a;Ka=b;if(H)if(La||=!0,0==a)I=function(){setTimeout(K,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)I=function(){Na(K)};else if(2==
a){if(!Oa)if(globalThis.setImmediate)Oa=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}I=function(){Oa(K)}}},Za=(a,b,c,d,f)=>{function h(){return k<Ra?(Ia(),!1):!0}H=a;Sa=d;var k=Ra;La=!1;K=function(){if(!r)if(0<Ta.length){var l=
Ta.shift();l.lc(l.bc);if(Ua){var p=Ua,t=0==p%1?p-1:Math.floor(p);Ua=l.ec?t:(8*p+(t+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",p=Ua??0,t=Va.kc??0,p?p<t?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));h()&&setTimeout(K,0)}else if(h())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)I();else{0==Ja&&(Ma=performance.now());a:if(!r){for(l of Xa)if(!1===l())break a;G(a);for(p of Ya)p()}h()&&I()}};f||(0<b?Pa(0,1E3/b):Pa(1,1),I());if(c)throw"unwind";},La=!1,I=null,
Ra=0,H=null,Sa=0,Ja=0,Ka=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){I=null;Ra++}var L=0;function Na(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===L)L=b+1E3/60;else for(;b+2>=L;)L+=1E3/60;setTimeout(a,Math.max(L-b,0))}}
var Va={},Ma,K,Oa,Ua,ab=globalThis.TextDecoder&&new TextDecoder,M=(a=0,b)=>{var c=y;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&ab)return ab.decode(c.subarray(a,d));for(b="";a<d;){var f=c[a++];if(f&128){var h=c[a++]&63;if(192==(f&224))b+=String.fromCharCode((f&31)<<6|h);else{var k=c[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|c[a++]&63;65536>f?b+=String.fromCharCode(f):(f-=65536,b+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else b+=String.fromCharCode(f)}return b},
bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?M(a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],O=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=P.gb[a];b.target.removeEventListener(b.fb,b.Qb,b.hb);P.gb.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:P.Hb&&P.$b.Eb){var a=P.rb;P.rb=[];for(var b of a)b.Lb(...b.Pb)}}function Q(a){if(!a.target)return-4;if(a.ob)a.Qb=function(c){++P.Hb;P.$b=a;gb();a.pb(c);gb();--P.Hb},a.target.addEventListener(a.fb,a.Qb,a.hb),P.gb.push(a);else for(var b=0;b<P.gb.length;++b)P.gb[b].target==a.target&&P.gb[b].fb==a.fb&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={cc:0,mc:0,Ib:0,sb:0,Ob:0,Nb:0,Fb:0,jc:0,pc:0,ic:0,Gb:0,Jb:0,yc:0,Mb:0,oc(a,b,c){u.set(u.subarray(b,b+c),a)},qc(){for(;P.gb.length;)fb(P.gb.length-1);P.rb=[]},Hb:0,rb:[],hc(a,b,c){function d(h,k){if(h.length!=k.length)return!1;for(var l in h)if(h[l]!=k[l])return!1;return!0}for(var f of P.rb)if(f.Lb==a&&d(f.Pb,c))return;P.rb.push({Lb:a,Tb:b,Pb:c});P.rb.sort((h,k)=>h.Tb<k.Tb)},sc(a){P.rb=P.rb.filter(b=>b.Lb!=a)},gb:[],rc:(a,b)=>{for(var c=0;c<P.gb.length;++c)P.gb[c].target!=a||b&&b!=P.gb[c].fb||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},R=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;f++}}d[b]=0}},ib=(a,b,c,d,f,h)=>{P.Fb||
(P.Fb=S(256));a={target:N(a),fb:h,ob:d,pb:(k=event)=>{var l=k.target.id?k.target.id:"",p=P.Fb;R(hb(k.target),p+0,128);R(l,p+128,128);O(d)(f,p,b)&&k.preventDefault()},hb:c};return Q(a)},jb=(a,b,c,d,f)=>{P.Gb||(P.Gb=S(276));return Q({target:a,fb:f,ob:d,pb:(h=event)=>{var k=P.Gb,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,p=!!l;u[k]=p;u[k+1]=P.fullscreenEnabled();var t=p?l:P.ac,v=
t?.id||"";R(hb(t),k+2,128);R(v,k+130,128);z[k+260>>2]=t?t.clientWidth:0;z[k+264>>2]=t?t.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;p&&(P.ac=l);O(d)(19,k,b)&&h.preventDefault()},hb:c})},kb=(a,b,c,d,f,h)=>{P.Ib||(P.Ib=S(160));a={target:N(a),fb:h,ob:d,pb:k=>{var l=P.Ib;C[l>>3]=k.timeStamp;var p=l>>2;z[p+2]=k.location;u[l+12]=k.ctrlKey;u[l+13]=k.shiftKey;u[l+14]=k.altKey;u[l+15]=k.metaKey;u[l+16]=k.repeat;z[p+5]=k.charCode;z[p+6]=k.keyCode;z[p+7]=k.which;R(k.key||"",l+32,32);R(k.code||
"",l+64,32);R(k.char||"",l+96,32);R(k.locale||"",l+128,32);O(d)(f,l,b)&&k.preventDefault()},hb:c};return Q(a)},lb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;na[2*d+14]=b.button;na[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=cb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},mb=(a,b,c,d,f,h)=>{P.sb||(P.sb=S(64));a=N(a);return Q({target:a,
Eb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,fb:h,ob:d,pb:(k=event)=>{lb(P.sb,k,a);O(d)(f,P.sb,b)&&k.preventDefault()},hb:c})},nb=(a,b,c,d)=>{P.Jb||(P.Jb=S(257));return Q({target:a,fb:"pointerlockchange",ob:d,pb:(f=event)=>{var h=P.Jb,k=document.pointerLockElement;u[h]=!!k;var l=k?.id||"";R(hb(k),h+1,128);R(l,h+129,128);O(d)(20,h,b)&&f.preventDefault()},hb:c})},ob=(a,b,c,d)=>Q({target:a,fb:"pointerlockerror",ob:d,pb:(f=event)=>{O(d)(38,0,b)&&f.preventDefault()},hb:c}),pb=(a,b,c,d)=>{P.Nb||
(P.Nb=S(36));a=N(a);return Q({target:a,fb:"resize",ob:d,pb:(f=event)=>{if(f.target==a){var h=document.body;if(h){var k=P.Nb;z[k>>2]=0;z[k+4>>2]=h.clientWidth;z[k+8>>2]=h.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;O(d)(10,k,b)&&f.preventDefault()}}},hb:c})},qb=(a,b,c,d,f,h)=>{P.Mb||(P.Mb=S(1552));a=N(a);return Q({target:a,Eb:"touchstart"==h||"touchend"==h,fb:h,ob:d,pb:k=>{var l={},p=k.touches;
for(var t of p)t.Rb=t.Sb=0,l[t.identifier]=t;for(var v of k.changedTouches)v.Rb=1,l[v.identifier]=v;for(var m of k.targetTouches)l[m.identifier].Sb=1;p=P.Mb;C[p>>3]=k.timeStamp;u[p+12]=k.ctrlKey;u[p+13]=k.shiftKey;u[p+14]=k.altKey;u[p+15]=k.metaKey;t=p+16;v=cb(a);m=0;for(let q of Object.values(l))if(l=t>>2,z[l]=q.identifier,z[l+1]=q.screenX,z[l+2]=q.screenY,z[l+3]=q.clientX,z[l+4]=q.clientY,z[l+5]=q.pageX,z[l+6]=q.pageY,u[t+28]=q.Rb,u[t+29]=q.Sb,z[l+8]=q.clientX-(v.left|0),z[l+9]=q.clientY-(v.top|
0),t+=48,31<++m)break;z[p+8>>2]=m;O(d)(f,p,b)&&k.preventDefault()},hb:c})},rb=(a,b,c,d)=>{P.Ob||(P.Ob=S(96));return Q({target:a,Eb:!0,fb:"wheel",ob:d,pb:(f=event)=>{var h=P.Ob;lb(h,f,a);C[h+64>>3]=f.deltaX;C[h+72>>3]=f.deltaY;C[h+80>>3]=f.deltaZ;z[h+88>>2]=f.deltaMode;O(d)(9,h,b)&&f.preventDefault()},hb:c})},T=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=sb(b);R(a,c,b);return c},U=[],tb=(a,b)=>{U[a>>>0]=b},ub=[],V=a=>{if(a)return U[a>>>
0]},vb=a=>{var b=A[a>>2];return b?M(b,A[a+4>>2]):""},W=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?M(b,a):"";if(0===a)return""},wb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),xb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),yb=a=>{if(0!==a)return{querySet:V(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},zb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,h=vb(f+4);c[h]=C[f+16>>3]}return c}},Ab=a=>a?V(a):"auto",Nb=a=>{function b(d){if(d)return{operation:Bb[A[d>>
2]],srcFactor:Cb[A[d+4>>2]],dstFactor:Cb[A[d+8>>2]]}}function c(d){return{compare:Db[A[d>>2]],failOp:Gb[A[d+4>>2]],depthFailOp:Gb[A[d+8>>2]],passOp:Gb[A[d+12>>2]]}}return{label:W(a+4),layout:Ab(A[a+12>>2]),vertex:function(d){if(d){var f=V(A[d+4>>2]),h=zb(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var l=A[d+28>>2];if(k){for(var p=[],t=0;t<k;++t){var v=p,m=v.push;var q=l+24*t;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var J=null;else{J=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Hb[w];q=A[q+20>>2];for(var Eb=
[],Qa=0;Qa<x;++Qa){var Fb=Eb,ta=q+24*Qa;Fb.push.call(Fb,{format:Ib[A[ta+4>>2]],offset:4294967296*A[ta+4+8>>2]+A[ta+8>>2],shaderLocation:A[ta+16>>2]})}J={arrayStride:J,stepMode:w,attributes:Eb}}}else J=void 0;m.call(v,J)}k=p}else k=void 0;return{module:f,constants:h,buffers:k,entryPoint:W(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Jb[A[d+4>>2]],stripIndexFormat:Kb[A[d+8>>2]],frontFace:Lb[A[d+12>>2]],cullMode:Mb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:X[A[d+
4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Db[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=V(A[d+4>>2]),h=zb(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],l=A[d+28>>2],p=[],t=0;t<k;++t){var v=p,m=v.push,
q=l+24*t,w=A[q+4>>2];if(0===w)q=void 0;else{w=X[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}m.call(v,q)}return{module:f,constants:h,targets:p,entryPoint:W(d+8)}}}(A[a+92>>2])}},Ob=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",
32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);pa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);pa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);pa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",
104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.nc&&c("maxImmediateSize",148)},Pb=[,"clamp-to-edge","repeat","mirror-repeat"],Cb=[,"zero","one","src","one-minus-src",
"src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Bb=[,"add","subtract","reverse-subtract","min","max"],Qb=["binding-not-used",,"uniform","storage","read-only-storage"],Db=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Rb=[,"opaque","premultiplied","unpremultiplied","inherit"],Mb=[,"none","front","back"],Sb=
[,"compatibility","core"],Tb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",
20:"texture-formats-tier2",21:"primitive-index",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Ub=[,"nearest","linear"],Lb=[,"ccw","cw"],Kb=[,"uint16","uint32"],Vb=[,"load","clear"],Wb=[,"nearest","linear"],Xb=[,"low-power","high-performance"],Yb=[,"srgb","display-p3"],Jb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],Zb=["binding-not-used",,"filtering","non-filtering",
"comparison"],Gb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],$b=["binding-not-used",,"write-only","read-only","read-write"],ac=[,"store","discard"],bc=[,"all","stencil-only","depth-only"],cc=[,"1d","2d","3d"],X=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm",
"rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb",
"bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb",
"astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],dc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],ec=[,"1d","2d","2d-array","cube","cube-array","3d"],fc=
[,"standard","extended"],Ib=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Hb=[,"vertex","instance"],
gc={undefined:1,unknown:1,destroyed:2},hc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";hc.Kb||(hc.Kb={});hc.Kb[a]||(hc.Kb[a]=1,ca&&(a="warning: "+a),g(a))},ic={rgba8unorm:22,bgra8unorm:27},jc=a=>{var b=Y();a();Z(b)};e.requestAnimationFrame=Na;e.pauseMainLoop=$a;e.resumeMainLoop=function(){Ra++;var a=Ja,b=Ka,c=H;H=null;Za(c,0,!1,Sa,!0);Pa(a,b);I()};e.preMainLoop&&Xa.push(e.preMainLoop);e.postMainLoop&&Ya.push(e.postMainLoop);e.noExitRuntime&&(Da=e.noExitRuntime);
e.printErr&&(g=e.printErr);e.wasmBinary&&(n=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var S,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Z,sb,Y,ra,eb,Kc={R:()=>sa(""),O:()=>{Da=!1;Ea=0},P:(a,b)=>{F[a]&&(clearTimeout(F[a].id),delete F[a]);if(!b)return 0;var c=setTimeout(()=>{delete F[a];G(()=>Ic(a,performance.now()))},b);F[a]={id:c,wc:b};return 0},ua:()=>{$a();H=null},I:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,K:(a,b,c)=>{a=N(a);if(!a)return-4;a=cb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},va:()=>performance.now(),Ca:(a,b)=>{function c(d){O(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Q:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);qa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},q:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),H:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},r:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),p:(a,
b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=N(a);if(!a)return-4;jb(a,b,c,d,"webkitfullscreenchange");return jb(a,b,c,d,"fullscreenchange")},A:(a,b,c,d)=>kb(a,b,c,d,2,"keydown"),y:(a,b,c,d)=>kb(a,b,c,d,1,"keypress"),z:(a,b,c,d)=>kb(a,b,c,d,3,"keyup"),Da:(a,b,c)=>{a=O(a);Za(a,b,c)},G:(a,b,c,d)=>mb(a,b,c,d,5,"mousedown"),D:(a,b,c,d)=>mb(a,b,c,d,33,"mouseenter"),C:(a,b,c,d)=>mb(a,b,c,d,34,"mouseleave"),E:(a,b,c,d)=>mb(a,b,c,d,8,"mousemove"),F:(a,b,c,d)=>mb(a,b,c,d,6,"mouseup"),t:(a,b,c,d)=>document.body?.requestPointerLock?
(a=N(a))?nb(a,b,c,d):-4:-1,s:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?ob(a,b,c,d):-4:-1,J:(a,b,c,d)=>pb(a,b,c,d),u:(a,b,c,d)=>qb(a,b,c,d,25,"touchcancel"),v:(a,b,c,d)=>qb(a,b,c,d,23,"touchend"),w:(a,b,c,d)=>qb(a,b,c,d,24,"touchmove"),x:(a,b,c,d)=>qb(a,b,c,d,22,"touchstart"),B:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?rb(a,b,c,d):-1:-4,W:function(a,b,c,d,f,h){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=V(a);
var k={};if(h){var l=A[h+12>>2];if(l){var p=A[h+16>>2];k.requiredFeatures=Array.from(A.subarray(p>>2,p+4*l>>2),m=>Tb[m])}var t=A[h+20>>2];if(t){var v={};function m(w,x,J=!1){x=A[t+x>>2];4294967295==x||J&&0==x||(v[w]=x)}function q(w,x){x=t+x;var J=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=J)v[w]=4294967296*A[x+4>>2]+A[x>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",
24);m("maxDynamicUniformBuffersPerPipelineLayout",32);m("maxDynamicStorageBuffersPerPipelineLayout",36);m("maxSampledTexturesPerShaderStage",40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);q("maxBufferSize",96);m("maxVertexAttributes",
104);m("maxVertexBufferArrayStride",108);m("maxInterStageShaderVariables",112);m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",148,!0);k.requiredLimits=v}if(l=A[h+24>>2])l={label:W(l+4)},k.defaultQueue=l;k.label=W(h+4)}a.requestDevice(k).then(m=>
{G(()=>{U[f>>>0]=m.queue;U[d>>>0]=m;m.lost.then(q=>{G(()=>{m.onuncapturederror=()=>{};var w=Y(),x=T(q.message);Ec(c,gc[q.reason],x);Z(w)})});m.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=Y();q=T(q.error.message);Hc(d,w,q);Z(x)};Gc(b,1,d,0)})},m=>{G(()=>{var q=Y(),w=T(m.message);Gc(b,3,d,w);c&&Ec(c,4,w);Z(q)})})},Z:(a,b,c)=>{var d=V(a);0===c&&hc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,
c)}catch(k){return 0}var h=Jc(16,f.byteLength);y.fill(0,h,f.byteLength);ub[a].push(()=>{(new Uint8Array(f)).set(y.subarray(h,h+f.byteLength));kc(h)});return h},Y:a=>{var b=V(a),c=ub[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete ub[a];b.unmap()}},a:a=>{delete U[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:W(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=V(a);try{var f=a.createBuffer(b)}catch(h){return!1}U[c>>>0]=f;d&&(ub[c]=[]);return!0},U:(a,b,c)=>{var d=A[b>>
2],f=A[d+4>>2];b={label:W(b+4),code:""};switch(f){case 2:b.code=vb(d+8)}a=V(a).createShaderModule(b);U[c>>>0]=a},X:a=>{a=V(a);a.onuncapturederror=null;a.destroy()},S:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return ic[a]},T:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Sb[A[c+4>>2]],powerPreference:Xb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.zc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(h=>
{G(()=>{if(h)U[d>>>0]=h,Fc(b,1,d,0);else{var k=Y(),l=T("WebGPU not available on this browser (requestAdapter returned null)");Fc(b,3,d,l);Z(k)}})},h=>{G(()=>{var k=Y(),l=T(h.message);Fc(b,4,d,l);Z(k)})}):(f=Y(),a=T("WebGPU not available on this browser (navigator.gpu is not available)"),Fc(b,3,d,a),Z(f))},N:Ga,Ha:function(){e.Ub=a=>{0!=mc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Ub)},Aa:function(){e.Zb=a=>{const b=a.clipboardData.getData("text");jc(()=>{const c=
T(b);lc(c)})};window.addEventListener("paste",e.Zb)},wa:function(){e.tc=[];e.Vb=b=>{b.stopPropagation();b.preventDefault()};e.Wb=b=>{b.stopPropagation();b.preventDefault()};e.Xb=b=>{b.stopPropagation();b.preventDefault()};e.Yb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.uc=c;nc(c.length);for(let f=0;f<c.length;f++)jc(()=>{const h=T(c[f].name);oc(f,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);pc(b.clientX,b.clientY,d)};const a=e.qb;
a.addEventListener("dragenter",e.Vb,!1);a.addEventListener("dragleave",e.Wb,!1);a.addEventListener("dragover",e.Xb,!1);a.addEventListener("drop",e.Yb,!1)},Fa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},M:function(a){e.Db&&(URL.revokeObjectURL(e.Db[a].dc),e.Db[a]=null)},ia:function(a,b){0!==b&&(document.title=b?M(b):"");a=a?M(a):"";void 0!==e.canvas&&("object"===typeof e.canvas?bb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
e.qb=N(a);e.qb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.qb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ga:function(){window.removeEventListener("beforeunload",e.Ub)},xa:function(){window.removeEventListener("paste",e.Zb)},ra:function(){const a=e.qb;a.removeEventListener("dragenter",e.Vb);a.removeEventListener("dragleave",e.Wb);a.removeEventListener("dragover",e.Xb);a.removeEventListener("drop",e.Yb)},h:function(){e.qb&&
e.qb.requestPointerLock&&e.qb.requestPointerLock()},V:function(a,b,c){if(e.qb){if(0===b)a="none";else if(0!=c)a=e.Db[a].fc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.qb.style.cursor=a}},Ea:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},L:function(a,b){b=b?M(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},ya:(a,b)=>{Ob(V(a).limits,b);return 1},e:(a,b)=>V(a).features.has(Tb[b]),ka:(a,b)=>{var c;
b&&(c={label:W(b+4),timestampWrites:yb(A[b+12>>2])});b=V(a);a=vc(0);c=b.beginComputePass(c);U[a>>>0]=c;return a},ja:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=W(b+4);for(var f=A[b+12>>2],h=A[b+16>>2],k=[],l=0;l<f;++l){var p=k,t=p.push;var v=h+56*l;var m=A[v+4>>2];if(0!==m){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:V(m),depthSlice:q,resolveTarget:V(A[v+12>>2]),clearValue:wb(v+24),loadOp:Vb[A[v+16>>2]],storeOp:ac[A[v+20>>2]]}}else v=void 0;t.call(p,v)}f=A[b+20>>2];f=
0!==f?{view:V(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Vb[A[f+8>>2]],depthStoreOp:ac[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Vb[A[f+24>>2]],stencilStoreOp:ac[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:V(A[b+24>>2]),timestampWrites:yb(A[b+28>>2]),maxDrawCount:d};d=V(a);a=yc(0);b=d.beginRenderPass(b);U[a>>>0]=b;return a},$:a=>{var b=V(a);a=tc(0);b=b.finish();U[a>>>0]=b;return a},
m:(a,b,c,d)=>{V(a).dispatchWorkgroups(b,c,d)},aa:a=>{V(a).end()},c:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ha:(a,b)=>{V(a).setPipeline(V(b))},i:(a,b)=>{var c=W(b+4),d=V(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var h=[],k=0;k<f;++k){var l=h,p=l.push;var t=b+40*k;var v=A[t+8>>2],m=A[t+32>>2],q=A[t+36>>2],w=A[t+4>>2];v?(m=t+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),t={binding:w,resource:{buffer:V(v),offset:4294967296*A[t+4+16>>2]+A[t+16>>2],size:m}}):
t=m?{binding:w,resource:V(m)}:{binding:w,resource:V(q)};p.call(l,t)}c={label:c,layout:d,entries:h};d=V(a);a=rc(0);c=d.createBindGroup(c);U[a>>>0]=c;return a},j:(a,b)=>{var c=W(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],h=0;h<d;++h){var k=f,l=k.push,p=b+88*h,t=A[p+4>>2],v=A[p+8>>2];var m=p+24;var q=A[m+4>>2];m=q?{type:Qb[q],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;q=(q=A[p+48+4>>2])?{type:Zb[q]}:void 0;var w=p+56;var x=A[w+4>>2];w=x?{sampleType:dc[x],
viewDimension:ec[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;p+=72;p=(x=A[p+4>>2])?{access:$b[x],format:X[A[p+8>>2]],viewDimension:ec[A[p+12>>2]]}:void 0;l.call(k,{binding:t,visibility:v,buffer:m,sampler:q,texture:w,storageTexture:p})}c={label:c,entries:f};d=V(a);a=sc(0);c=d.createBindGroupLayout(c);U[a>>>0]=c;return a},la:(a,b)=>{var c;b&&(c={label:W(b+4)});b=V(a);a=uc(0);c=b.createCommandEncoder(c);U[a>>>0]=c;return a},na:(a,b)=>{var c=W(b+4);var d=Ab(A[b+12>>2]);b=(b+=16)?{module:V(A[b+4>>2]),
constants:zb(A[b+16>>2],A[b+20>>2]),entryPoint:W(b+8)}:void 0;c={label:c,layout:d,compute:b};d=V(a);a=wc(0);c=d.createComputePipeline(c);U[a>>>0]=c;return a},oa:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],h=0;h<c;++h)f.push(V(A[d+4*h>>2]));b={label:W(b+4),bindGroupLayouts:f};c=V(a);a=xc(0);b=c.createPipelineLayout(b);U[a>>>0]=b;return a},ma:(a,b)=>{b=Nb(b);var c=V(a);a=zc(0);b=c.createRenderPipeline(b);U[a>>>0]=b;return a},pa:(a,b)=>{var c;b&&(c={label:W(b+4),addressModeU:Pb[A[b+12>>2]],addressModeV:Pb[A[b+
16>>2]],addressModeW:Pb[A[b+20>>2]],magFilter:Ub[A[b+24>>2]],minFilter:Ub[A[b+28>>2]],mipmapFilter:Wb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Db[A[b+44>>2]],maxAnisotropy:oa[b+48>>1]});b=V(a);a=Ac(0);c=b.createSampler(c);U[a>>>0]=c;return a},k:(a,b)=>{var c={label:W(b+4),size:xb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:cc[A[b+24>>2]],format:X[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>
2),f=>X[f]));a=V(a);d=Cc(0);tb(d,a.createTexture(c));return d},sa:(a,b)=>{Ob(V(a).limits,b);return 1},d:(a,b)=>V(a).features.has(Tb[b]),Ba:(a,b)=>{a=N(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.vc=W(b+4);b=Bc(0);U[b>>>0]=a;return b},_:(a,b,c)=>{a=V(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>V(d));a.submit(b)},l:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);V(a).writeBuffer(V(b),c,y.subarray(d,d+f),0,f)},qa:(a,b,c,d,f,h)=>{var k=A[f+8>>2],l=A[f+12>>2],p=
b+8;V(a).writeTexture({texture:V(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[p>>2],y:A[p+4>>2],z:A[p+8>>2]},aspect:bc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===k?void 0:k,rowsPerImage:4294967295===l?void 0:l},xb(h))},n:(a,b,c,d,f)=>{V(a).draw(b,c,d>>>0,f>>>0)},o:(a,b,c,d,f,h)=>{V(a).drawIndexed(b,c,d>>>0,f,h>>>0)},ba:a=>{V(a).end()},b:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},fa:(a,b)=>{V(a).setBlendConstant(wb(b))},
da:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);b=V(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Kb[c],d,f)},ga:(a,b)=>{V(a).setPipeline(V(b))},ea:(a,b)=>{V(a).setStencilReference(b>>>0)},ca:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);c=V(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},za:(a,b)=>{var c=A[b+4>>2];a=
V(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:V(c),format:X[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Rb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),h=>X[h])}b=A[b>>2];0!==b&&(c.colorSpace=Yb[A[b+8>>2]],c.xc={mode:fc[A[b+12>>2]]});a.configure(c)},ta:(a,b)=>{a=V(a);try{var c=Cc(0),d=a.getCurrentTexture();U[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=
A[b+24>>2];var d=A[b+32>>2];c={label:W(b+4),format:X[A[b+12>>2]],dimension:ec[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:bc[A[b+36>>2]]}}b=V(a);a=Dc(0);b=b.createView(c);U[a>>>0]=b;return a}};function Lc(a=[]){var b=qc;a.unshift(ea);var c=a.length,d=sb(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=T(k);f+=4});A[f>>2]=0;try{var h=b(c,d);Ha(h)}catch(k){Fa(k)}}
function Mc(a=da){function b(){e.calledRun=!0;if(!r){Nc.Ja();e.onRuntimeInitialized?.();e.noInitialRun||Lc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Aa.push(c)}za(Aa)}}if(0<D)E=Mc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ca();za(Ba);0<D?E=Mc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Nc;
(async function(){function a(c){c=Nc=c.exports;S=c.Ka;kc=c.La;lc=e.__sapp_emsc_onpaste=c.Ma;mc=e.__sapp_html5_get_ask_leave_site=c.Na;nc=e.__sapp_emsc_begin_drop=c.Oa;oc=e.__sapp_emsc_drop=c.Pa;pc=e.__sapp_emsc_end_drop=c.Qa;e.__sapp_emsc_invoke_fetch_cb=c.Ra;e.__sapp_emsc_set_fullscreen_flag=c.Sa;qc=e._main=c.Ta;e.__saudio_emsc_pull=c.Ua;e.__sfetch_emsc_head_response=c.Va;e.__sfetch_emsc_get_response=c.Wa;e.__sfetch_emsc_failed_http_status=c.Xa;e.__sfetch_emsc_failed_buffer_too_small=c.Ya;e.__sfetch_emsc_failed_other=
c.Za;rc=c._a;sc=c.$a;tc=c.ab;uc=c.bb;vc=c.cb;wc=c.db;xc=c.eb;yc=c.ib;zc=c.jb;Ac=c.kb;Bc=c.lb;Cc=c.mb;Dc=c.nb;Ec=c.tb;Fc=c.ub;Gc=c.vb;Hc=c.wb;Ic=c.yb;Jc=c.zb;Z=c.Ab;sb=c.Bb;Y=c.Cb;ra=c.Ia;eb=c.xb;qa();D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Nc}D++;e.monitorRunDependencies?.(D);var b={a:Kc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("sbufoffset-sapp.wasm",ia):ia+"sbufoffset-sapp.wasm";return a((await xa(b)).instance)})();
Mc();
