var e;e||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var g=console.error.bind(console),n,r=!1,ma,la=a=>a.startsWith("file://"),u,y,na,z,A,oa,B,pa;
function qa(){var a=ra.buffer;u=new Int8Array(a);na=new Int16Array(a);y=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);oa=new Float32Array(a);B=new Float64Array(a);pa=new BigInt64Array(a);new BigUint64Array(a)}function sa(a){e.onAbort?.(a);a="Aborted("+a+")";g(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function xa(a){var b=ua;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(e)},Aa=[],Ba=[],Ca=()=>{var a=e.preRun.shift();Ba.push(a)},C=0,D=null,Da=!0,Ea=0,E={},Fa=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ga=a=>{ma=a;Da||0<Ea||(e.onExit?.(a),r=!0);fa(a,new ya(a))},Ha=a=>{ma=a;Ga(a)},Ia=()=>{if(!(Da||0<Ea))try{var a=ma;ma=a;Ga(a)}catch(b){Fa(b)}},F=a=>{if(!r)try{a(),Ia()}catch(b){Fa(b)}},Qa=(a,b)=>{Ja=a;Ka=b;if(G)if(La||=!0,0==a)H=function(){setTimeout(J,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)H=function(){Na(J)};else if(2==
a){if(!Oa)if(globalThis.setImmediate)Oa=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}H=function(){Oa(J)}}},Za=(a,b,c,d,f)=>{function h(){return k<Ra?(Ia(),!1):!0}G=a;Sa=d;var k=Ra;La=!1;J=function(){if(!r)if(0<Ta.length){var l=
Ta.shift();l.ic(l.Zb);if(Ua){var p=Ua,t=0==p%1?p-1:Math.floor(p);Ua=l.bc?t:(8*p+(t+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",p=Ua??0,t=Va.hc??0,p?p<t?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));h()&&setTimeout(J,0)}else if(h())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)H();else{0==Ja&&(Ma=performance.now());a:if(!r){for(l of Xa)if(!1===l())break a;F(a);for(p of Ya)p()}h()&&H()}};f||(0<b?Qa(0,1E3/b):Qa(1,1),H());if(c)throw"unwind";},La=!1,H=null,
Ra=0,G=null,Sa=0,Ja=0,Ka=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){H=null;Ra++}var K=0;function Na(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===K)K=b+1E3/60;else for(;b+2>=K;)K+=1E3/60;setTimeout(a,Math.max(K-b,0))}}
var Va={},Ma,J,Oa,Ua,ab=globalThis.TextDecoder&&new TextDecoder,L=(a=0,b)=>{var c=y;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&ab)return ab.decode(c.subarray(a,d));for(b="";a<d;){var f=c[a++];if(f&128){var h=c[a++]&63;if(192==(f&224))b+=String.fromCharCode((f&31)<<6|h);else{var k=c[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|c[a++]&63;65536>f?b+=String.fromCharCode(f):(f-=65536,b+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else b+=String.fromCharCode(f)}return b},
bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?L(a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],N=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=O.eb[a];b.target.removeEventListener(b.cb,b.Nb,b.hb);O.eb.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:O.Eb&&O.Xb.Bb){var a=O.ob;O.ob=[];for(var b of a)b.Ib(...b.Mb)}}function P(a){if(!a.target)return-4;if(a.lb)a.Nb=function(c){++O.Eb;O.Xb=a;gb();a.mb(c);gb();--O.Eb},a.target.addEventListener(a.cb,a.Nb,a.hb),O.eb.push(a);else for(var b=0;b<O.eb.length;++b)O.eb[b].target==a.target&&O.eb[b].cb==a.cb&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var O={$b:0,jc:0,Fb:0,pb:0,Lb:0,Kb:0,Cb:0,fc:0,mc:0,ec:0,Db:0,Gb:0,vc:0,Jb:0,lc(a,b,c){u.set(u.subarray(b,b+c),a)},nc(){for(;O.eb.length;)fb(O.eb.length-1);O.ob=[]},Eb:0,ob:[],dc(a,b,c){function d(h,k){if(h.length!=k.length)return!1;for(var l in h)if(h[l]!=k[l])return!1;return!0}for(var f of O.ob)if(f.Ib==a&&d(f.Mb,c))return;O.ob.push({Ib:a,Qb:b,Mb:c});O.ob.sort((h,k)=>h.Qb<k.Qb)},pc(a){O.ob=O.ob.filter(b=>b.Ib!=a)},eb:[],oc:(a,b)=>{for(var c=0;c<O.eb.length;++c)O.eb[c].target!=a||b&&b!=O.eb[c].cb||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Q=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;f++}}d[b]=0}},ib=(a,b,c,d,f,h)=>{O.Cb||
(O.Cb=R(256));a={target:M(a),cb:h,lb:d,mb:(k=event)=>{var l=k.target.id?k.target.id:"",p=O.Cb;Q(hb(k.target),p+0,128);Q(l,p+128,128);N(d)(f,p,b)&&k.preventDefault()},hb:c};return P(a)},jb=(a,b,c,d,f)=>{O.Db||(O.Db=R(276));return P({target:a,cb:f,lb:d,mb:(h=event)=>{var k=O.Db,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,p=!!l;u[k]=p;u[k+1]=O.fullscreenEnabled();var t=p?l:O.Yb,v=
t?.id||"";Q(hb(t),k+2,128);Q(v,k+130,128);z[k+260>>2]=t?t.clientWidth:0;z[k+264>>2]=t?t.clientHeight:0;z[k+268>>2]=screen.width;z[k+272>>2]=screen.height;p&&(O.Yb=l);N(d)(19,k,b)&&h.preventDefault()},hb:c})},kb=(a,b,c,d,f,h)=>{O.Fb||(O.Fb=R(160));a={target:M(a),cb:h,lb:d,mb:k=>{var l=O.Fb;B[l>>3]=k.timeStamp;var p=l>>2;z[p+2]=k.location;u[l+12]=k.ctrlKey;u[l+13]=k.shiftKey;u[l+14]=k.altKey;u[l+15]=k.metaKey;u[l+16]=k.repeat;z[p+5]=k.charCode;z[p+6]=k.keyCode;z[p+7]=k.which;Q(k.key||"",l+32,32);Q(k.code||
"",l+64,32);Q(k.char||"",l+96,32);Q(k.locale||"",l+128,32);N(d)(f,l,b)&&k.preventDefault()},hb:c};return P(a)},lb=(a,b,c)=>{B[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;na[2*d+14]=b.button;na[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=cb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},S=(a,b,c,d,f,h)=>{O.pb||(O.pb=R(64));a=M(a);return P({target:a,
Bb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,cb:h,lb:d,mb:(k=event)=>{lb(O.pb,k,a);N(d)(f,O.pb,b)&&k.preventDefault()},hb:c})},mb=(a,b,c,d)=>{O.Gb||(O.Gb=R(257));return P({target:a,cb:"pointerlockchange",lb:d,mb:(f=event)=>{var h=O.Gb,k=document.pointerLockElement;u[h]=!!k;var l=k?.id||"";Q(hb(k),h+1,128);Q(l,h+129,128);N(d)(20,h,b)&&f.preventDefault()},hb:c})},nb=(a,b,c,d)=>P({target:a,cb:"pointerlockerror",lb:d,mb:(f=event)=>{N(d)(38,0,b)&&f.preventDefault()},hb:c}),ob=(a,b,c,d)=>{O.Kb||
(O.Kb=R(36));a=M(a);return P({target:a,cb:"resize",lb:d,mb:(f=event)=>{if(f.target==a){var h=document.body;if(h){var k=O.Kb;z[k>>2]=0;z[k+4>>2]=h.clientWidth;z[k+8>>2]=h.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;N(d)(10,k,b)&&f.preventDefault()}}},hb:c})},pb=(a,b,c,d,f,h)=>{O.Jb||(O.Jb=R(1552));a=M(a);return P({target:a,Bb:"touchstart"==h||"touchend"==h,cb:h,lb:d,mb:k=>{var l={},p=k.touches;
for(var t of p)t.Ob=t.Pb=0,l[t.identifier]=t;for(var v of k.changedTouches)v.Ob=1,l[v.identifier]=v;for(var m of k.targetTouches)l[m.identifier].Pb=1;p=O.Jb;B[p>>3]=k.timeStamp;u[p+12]=k.ctrlKey;u[p+13]=k.shiftKey;u[p+14]=k.altKey;u[p+15]=k.metaKey;t=p+16;v=cb(a);m=0;for(let q of Object.values(l))if(l=t>>2,z[l]=q.identifier,z[l+1]=q.screenX,z[l+2]=q.screenY,z[l+3]=q.clientX,z[l+4]=q.clientY,z[l+5]=q.pageX,z[l+6]=q.pageY,u[t+28]=q.Ob,u[t+29]=q.Pb,z[l+8]=q.clientX-(v.left|0),z[l+9]=q.clientY-(v.top|
0),t+=48,31<++m)break;z[p+8>>2]=m;N(d)(f,p,b)&&k.preventDefault()},hb:c})},qb=(a,b,c,d)=>{O.Lb||(O.Lb=R(96));return P({target:a,Bb:!0,cb:"wheel",lb:d,mb:(f=event)=>{var h=O.Lb;lb(h,f,a);B[h+64>>3]=f.deltaX;B[h+72>>3]=f.deltaY;B[h+80>>3]=f.deltaZ;z[h+88>>2]=f.deltaMode;N(d)(9,h,b)&&f.preventDefault()},hb:c})},T=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=rb(b);Q(a,c,b);return c},U=[],sb=(a,b)=>{U[a>>>0]=b},tb=[],V=a=>{if(a)return U[a>>>
0]},ub=a=>{var b=A[a>>2];return b?L(b,A[a+4>>2]):""},W=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?L(b,a):"";if(0===a)return""},vb=a=>({r:B[a>>3],g:B[a+8>>3],b:B[a+16>>3],a:B[a+24>>3]}),wb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),xb=a=>{if(0!==a)return{querySet:V(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},yb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,h=ub(f+4);c[h]=B[f+16>>3]}return c}},zb=a=>a?V(a):"auto",Mb=a=>{function b(d){if(d)return{operation:Ab[A[d>>
2]],srcFactor:Db[A[d+4>>2]],dstFactor:Db[A[d+8>>2]]}}function c(d){return{compare:Eb[A[d>>2]],failOp:Fb[A[d+4>>2]],depthFailOp:Fb[A[d+8>>2]],passOp:Fb[A[d+12>>2]]}}return{label:W(a+4),layout:zb(A[a+12>>2]),vertex:function(d){if(d){var f=V(A[d+4>>2]),h=yb(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var l=A[d+28>>2];if(k){for(var p=[],t=0;t<k;++t){var v=p,m=v.push;var q=l+24*t;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var I=null;else{I=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Gb[w];q=A[q+20>>2];for(var Bb=
[],Pa=0;Pa<x;++Pa){var Cb=Bb,ta=q+24*Pa;Cb.push.call(Cb,{format:Hb[A[ta+4>>2]],offset:4294967296*A[ta+4+8>>2]+A[ta+8>>2],shaderLocation:A[ta+16>>2]})}I={arrayStride:I,stepMode:w,attributes:Bb}}}else I=void 0;m.call(v,I)}k=p}else k=void 0;return{module:f,constants:h,buffers:k,entryPoint:W(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Ib[A[d+4>>2]],stripIndexFormat:Jb[A[d+8>>2]],frontFace:Kb[A[d+12>>2]],cullMode:Lb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:X[A[d+
4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Eb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:oa[d+60>>2],depthBiasClamp:oa[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=V(A[d+4>>2]),h=yb(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],l=A[d+28>>2],p=[],t=0;t<k;++t){var v=p,m=v.push,
q=l+24*t,w=A[q+4>>2];if(0===w)q=void 0;else{w=X[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}m.call(v,q)}return{module:f,constants:h,targets:p,entryPoint:W(d+8)}}}(A[a+92>>2])}},Nb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",
32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);pa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);pa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);pa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",
104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.kc&&c("maxImmediateSize",148)},Db=[,"zero","one","src","one-minus-src","src-alpha","one-minus-src-alpha","dst","one-minus-dst",
"dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Ab=[,"add","subtract","reverse-subtract","min","max"],Ob=["binding-not-used",,"uniform","storage","read-only-storage"],Eb=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Pb=[,"opaque","premultiplied","unpremultiplied","inherit"],Lb=[,"none","front","back"],Qb=[,"compatibility","core"],Rb={1:"core-features-and-limits",
2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",
327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Kb=[,"ccw","cw"],Jb=[,"uint16","uint32"],Sb=[,"load","clear"],Tb=[,"low-power","high-performance"],Ub=[,"srgb","display-p3"],Ib=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],Vb=["binding-not-used",,"filtering","non-filtering","comparison"],Fb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp",
"increment-wrap","decrement-wrap"],Wb=["binding-not-used",,"write-only","read-only","read-write"],Xb=[,"store","discard"],Yb=[,"all","stencil-only","depth-only"],Zb=[,"1d","2d","3d"],X=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb",
"rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float",
"bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm",
"astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],$b=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],ac=[,"1d","2d","2d-array","cube","cube-array","3d"],bc=[,"standard","extended"],Hb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8",
"unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Gb=[,"vertex","instance"],cc={undefined:1,unknown:1,destroyed:2},dc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";
dc.Hb||(dc.Hb={});dc.Hb[a]||(dc.Hb[a]=1,ca&&(a="warning: "+a),g(a))},ec={rgba8unorm:22,bgra8unorm:27},fc=a=>{var b=Y();a();Z(b)};e.requestAnimationFrame=Na;e.pauseMainLoop=$a;e.resumeMainLoop=function(){Ra++;var a=Ja,b=Ka,c=G;G=null;Za(c,0,!1,Sa,!0);Qa(a,b);H()};e.preMainLoop&&Xa.push(e.preMainLoop);e.postMainLoop&&Ya.push(e.postMainLoop);e.noExitRuntime&&(Da=e.noExitRuntime);e.printErr&&(g=e.printErr);e.wasmBinary&&(n=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
var gc,hc,ic,jc,kc,lc,R,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Z,rb,Y,ra,eb,Fc={N:()=>sa(""),K:()=>{Da=!1;Ea=0},L:(a,b)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!b)return 0;var c=setTimeout(()=>{delete E[a];F(()=>Dc(a,performance.now()))},b);E[a]={id:c,tc:b};return 0},ra:()=>{$a();G=null},E:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,G:(a,b,c)=>{a=M(a);if(!a)return-4;a=cb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},sa:()=>performance.now(),za:(a,b)=>{function c(d){N(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},M:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);qa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},l:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),D:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},m:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),k:(a,
b,c,d)=>{if(!O.fullscreenEnabled())return-1;a=M(a);if(!a)return-4;jb(a,b,c,d,"webkitfullscreenchange");return jb(a,b,c,d,"fullscreenchange")},v:(a,b,c,d)=>kb(a,b,c,d,2,"keydown"),t:(a,b,c,d)=>kb(a,b,c,d,1,"keypress"),u:(a,b,c,d)=>kb(a,b,c,d,3,"keyup"),Aa:(a,b,c)=>{a=N(a);Za(a,b,c)},B:(a,b,c,d)=>S(a,b,c,d,5,"mousedown"),y:(a,b,c,d)=>S(a,b,c,d,33,"mouseenter"),x:(a,b,c,d)=>S(a,b,c,d,34,"mouseleave"),z:(a,b,c,d)=>S(a,b,c,d,8,"mousemove"),A:(a,b,c,d)=>S(a,b,c,d,6,"mouseup"),o:(a,b,c,d)=>document.body?.requestPointerLock?
(a=M(a))?mb(a,b,c,d):-4:-1,n:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?nb(a,b,c,d):-4:-1,F:(a,b,c,d)=>ob(a,b,c,d),p:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),q:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),r:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),s:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),w:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?qb(a,b,c,d):-1:-4,S:function(a,b,c,d,f,h){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=V(a);
var k={};if(h){var l=A[h+12>>2];if(l){var p=A[h+16>>2];k.requiredFeatures=Array.from(A.subarray(p>>2,p+4*l>>2),m=>Rb[m])}var t=A[h+20>>2];if(t){var v={};function m(w,x,I=!1){x=A[t+x>>2];4294967295==x||I&&0==x||(v[w]=x)}function q(w,x){x=t+x;var I=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=I)v[w]=4294967296*A[x+4>>2]+A[x>>2]}m("maxTextureDimension1D",4);m("maxTextureDimension2D",8);m("maxTextureDimension3D",12);m("maxTextureArrayLayers",16);m("maxBindGroups",20);m("maxBindGroupsPlusVertexBuffers",
24);m("maxDynamicUniformBuffersPerPipelineLayout",32);m("maxDynamicStorageBuffersPerPipelineLayout",36);m("maxSampledTexturesPerShaderStage",40);m("maxSamplersPerShaderStage",44);m("maxStorageBuffersPerShaderStage",48);m("maxStorageTexturesPerShaderStage",52);m("maxUniformBuffersPerShaderStage",56);m("minUniformBufferOffsetAlignment",80);m("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);m("maxVertexBuffers",88);q("maxBufferSize",96);m("maxVertexAttributes",
104);m("maxVertexBufferArrayStride",108);m("maxInterStageShaderVariables",112);m("maxColorAttachments",116);m("maxColorAttachmentBytesPerSample",120);m("maxComputeWorkgroupStorageSize",124);m("maxComputeInvocationsPerWorkgroup",128);m("maxComputeWorkgroupSizeX",132);m("maxComputeWorkgroupSizeY",136);m("maxComputeWorkgroupSizeZ",140);m("maxComputeWorkgroupsPerDimension",144);m("maxImmediateSize",148,!0);k.requiredLimits=v}if(l=A[h+24>>2])l={label:W(l+4)},k.defaultQueue=l;k.label=W(h+4)}a.requestDevice(k).then(m=>
{F(()=>{U[f>>>0]=m.queue;U[d>>>0]=m;m.lost.then(q=>{F(()=>{m.onuncapturederror=()=>{};var w=Y(),x=T(q.message);zc(c,cc[q.reason],x);Z(w)})});m.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=Y();q=T(q.error.message);Cc(d,w,q);Z(x)};Bc(b,1,d,0)})},m=>{F(()=>{var q=Y(),w=T(m.message);Bc(b,3,d,w);c&&zc(c,4,w);Z(q)})})},V:(a,b,c)=>{var d=V(a);0===c&&dc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,
c)}catch(k){return 0}var h=Ec(16,f.byteLength);y.fill(0,h,f.byteLength);tb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(h,h+f.byteLength));mc(h)});return h},U:a=>{var b=V(a),c=tb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete tb[a];b.unmap()}},a:a=>{delete U[a]},f:(a,b,c)=>{var d=!!A[b+32>>2];b={label:W(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=V(a);try{var f=a.createBuffer(b)}catch(h){return!1}U[c>>>0]=f;d&&(tb[c]=[]);return!0},R:(a,b,c)=>{var d=A[b>>
2],f=A[d+4>>2];b={label:W(b+4),code:""};switch(f){case 2:b.code=ub(d+8)}a=V(a).createShaderModule(b);U[c>>>0]=a},T:a=>{a=V(a);a.onuncapturederror=null;a.destroy()},P:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return ec[a]},Q:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Qb[A[c+4>>2]],powerPreference:Tb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.wc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(h=>
{F(()=>{if(h)U[d>>>0]=h,Ac(b,1,d,0);else{var k=Y(),l=T("WebGPU not available on this browser (requestAdapter returned null)");Ac(b,3,d,l);Z(k)}})},h=>{F(()=>{var k=Y(),l=T(h.message);Ac(b,4,d,l);Z(k)})}):(f=Y(),a=T("WebGPU not available on this browser (navigator.gpu is not available)"),Ac(b,3,d,a),Z(f))},J:Ga,Ea:function(){e.Rb=a=>{0!=hc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Rb)},xa:function(){e.Wb=a=>{const b=a.clipboardData.getData("text");fc(()=>{const c=
T(b);gc(c)})};window.addEventListener("paste",e.Wb)},ta:function(){e.qc=[];e.Sb=b=>{b.stopPropagation();b.preventDefault()};e.Tb=b=>{b.stopPropagation();b.preventDefault()};e.Ub=b=>{b.stopPropagation();b.preventDefault()};e.Vb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.rc=c;ic(c.length);for(let f=0;f<c.length;f++)fc(()=>{const h=T(c[f].name);jc(f,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);kc(b.clientX,b.clientY,d)};const a=e.nb;
a.addEventListener("dragenter",e.Sb,!1);a.addEventListener("dragleave",e.Tb,!1);a.addEventListener("dragover",e.Ub,!1);a.addEventListener("drop",e.Vb,!1)},Ca:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},I:function(a){e.Ab&&(URL.revokeObjectURL(e.Ab[a].ac),e.Ab[a]=null)},fa:function(a,b){0!==b&&(document.title=b?L(b):"");a=a?L(a):"";void 0!==e.canvas&&("object"===typeof e.canvas?bb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
e.nb=M(a);e.nb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.nb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Da:function(){window.removeEventListener("beforeunload",e.Rb)},ua:function(){window.removeEventListener("paste",e.Wb)},oa:function(){const a=e.nb;a.removeEventListener("dragenter",e.Sb);a.removeEventListener("dragleave",e.Tb);a.removeEventListener("dragover",e.Ub);a.removeEventListener("drop",e.Vb)},g:function(){e.nb&&
e.nb.requestPointerLock&&e.nb.requestPointerLock()},O:function(a,b,c){if(e.nb){if(0===b)a="none";else if(0!=c)a=e.Ab[a].cc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.nb.style.cursor=a}},Ba:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},H:function(a,b){b=b?L(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},va:(a,b)=>{Nb(V(a).limits,b);return 1},e:(a,b)=>V(a).features.has(Rb[b]),ja:(a,b)=>{var c;
b&&(c={label:W(b+4),timestampWrites:xb(A[b+12>>2])});b=V(a);a=rc(0);c=b.beginComputePass(c);U[a>>>0]=c;return a},ia:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=W(b+4);for(var f=A[b+12>>2],h=A[b+16>>2],k=[],l=0;l<f;++l){var p=k,t=p.push;var v=h+56*l;var m=A[v+4>>2];if(0!==m){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:V(m),depthSlice:q,resolveTarget:V(A[v+12>>2]),clearValue:vb(v+24),loadOp:Sb[A[v+16>>2]],storeOp:Xb[A[v+20>>2]]}}else v=void 0;t.call(p,v)}f=A[b+20>>2];f=
0!==f?{view:V(A[f+4>>2]),depthClearValue:oa[f+16>>2],depthLoadOp:Sb[A[f+8>>2]],depthStoreOp:Xb[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Sb[A[f+24>>2]],stencilStoreOp:Xb[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b={label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:V(A[b+24>>2]),timestampWrites:xb(A[b+28>>2]),maxDrawCount:d};d=V(a);a=uc(0);b=d.beginRenderPass(b);U[a>>>0]=b;return a},Y:a=>{var b=V(a);a=pc(0);b=b.finish();U[a>>>0]=b;
return a},Z:a=>{V(a).end()},c:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ha:(a,b)=>{V(a).setPipeline(V(b))},h:(a,b)=>{var c=W(b+4),d=V(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var h=[],k=0;k<f;++k){var l=h,p=l.push;var t=b+40*k;var v=A[t+8>>2],m=A[t+32>>2],q=A[t+36>>2],w=A[t+4>>2];v?(m=t+24,m=A[m>>2]+4294967296*z[m+4>>2],-1==m&&(m=void 0),t={binding:w,resource:{buffer:V(v),offset:4294967296*A[t+4+16>>2]+A[t+16>>2],size:m}}):t=m?{binding:w,resource:V(m)}:{binding:w,
resource:V(q)};p.call(l,t)}c={label:c,layout:d,entries:h};d=V(a);a=nc(0);c=d.createBindGroup(c);U[a>>>0]=c;return a},i:(a,b)=>{var c=W(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],h=0;h<d;++h){var k=f,l=k.push,p=b+88*h,t=A[p+4>>2],v=A[p+8>>2];var m=p+24;var q=A[m+4>>2];m=q?{type:Ob[q],hasDynamicOffset:!!A[m+8>>2],minBindingSize:4294967296*A[m+4+16>>2]+A[m+16>>2]}:void 0;q=(q=A[p+48+4>>2])?{type:Vb[q]}:void 0;var w=p+56;var x=A[w+4>>2];w=x?{sampleType:$b[x],viewDimension:ac[A[w+8>>2]],multisampled:!!A[w+
12>>2]}:void 0;p+=72;p=(x=A[p+4>>2])?{access:Wb[x],format:X[A[p+8>>2]],viewDimension:ac[A[p+12>>2]]}:void 0;l.call(k,{binding:t,visibility:v,buffer:m,sampler:q,texture:w,storageTexture:p})}c={label:c,entries:f};d=V(a);a=oc(0);c=d.createBindGroupLayout(c);U[a>>>0]=c;return a},ka:(a,b)=>{var c;b&&(c={label:W(b+4)});b=V(a);a=qc(0);c=b.createCommandEncoder(c);U[a>>>0]=c;return a},ma:(a,b)=>{var c=W(b+4);var d=zb(A[b+12>>2]);b=(b+=16)?{module:V(A[b+4>>2]),constants:yb(A[b+16>>2],A[b+20>>2]),entryPoint:W(b+
8)}:void 0;c={label:c,layout:d,compute:b};d=V(a);a=sc(0);c=d.createComputePipeline(c);U[a>>>0]=c;return a},na:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],h=0;h<c;++h)f.push(V(A[d+4*h>>2]));b={label:W(b+4),bindGroupLayouts:f};c=V(a);a=tc(0);b=c.createPipelineLayout(b);U[a>>>0]=b;return a},la:(a,b)=>{b=Mb(b);var c=V(a);a=vc(0);b=c.createRenderPipeline(b);U[a>>>0]=b;return a},C:(a,b)=>{var c={label:W(b+4),size:wb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:Zb[A[b+24>>2]],format:X[A[b+
40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>X[f]));a=V(a);d=xc(0);sb(d,a.createTexture(c));return d},pa:(a,b)=>{Nb(V(a).limits,b);return 1},d:(a,b)=>V(a).features.has(Rb[b]),ya:(a,b)=>{a=M(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.sc=W(b+4);b=wc(0);U[b>>>0]=a;return b},X:(a,b,c)=>{a=V(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>V(d));a.submit(b)},W:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);
V(a).writeBuffer(V(b),c,y.subarray(d,d+f),0,f)},$:(a,b,c,d,f)=>{V(a).draw(b,c,d>>>0,f>>>0)},aa:(a,b,c,d,f,h)=>{V(a).drawIndexed(b,c,d>>>0,f,h>>>0)},_:a=>{V(a).end()},b:(a,b,c,d,f)=>{a=V(a);c=V(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ea:(a,b)=>{V(a).setBlendConstant(vb(b))},ca:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);b=V(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Jb[c],d,f)},ga:(a,b)=>{V(a).setPipeline(V(b))},
da:(a,b)=>{V(a).setStencilReference(b>>>0)},ba:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=V(a);c=V(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},wa:(a,b)=>{var c=A[b+4>>2];a=V(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:V(c),format:X[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Pb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>
2,f+4*d>>2),h=>X[h])}b=A[b>>2];0!==b&&(c.colorSpace=Ub[A[b+8>>2]],c.uc={mode:bc[A[b+12>>2]]});a.configure(c)},qa:(a,b)=>{a=V(a);try{var c=xc(0),d=a.getCurrentTexture();U[c>>>0]=d;A[b+4>>2]=c;z[b+8>>2]=1}catch(f){A[b+4>>2]=0,z[b+8>>2]=6}},j:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:W(b+4),format:X[A[b+12>>2]],dimension:ac[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Yb[A[b+36>>2]]}}b=
V(a);a=yc(0);b=b.createView(c);U[a>>>0]=b;return a}};function Gc(a=[]){var b=lc;a.unshift(ea);var c=a.length,d=rb(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=T(k);f+=4});A[f>>2]=0;try{var h=b(c,d);Ha(h)}catch(k){Fa(k)}}
function Hc(a=da){function b(){e.calledRun=!0;if(!r){Ic.Ga();e.onRuntimeInitialized?.();e.noInitialRun||Gc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Aa.push(c)}za(Aa)}}if(0<C)D=Hc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ca();za(Ba);0<C?D=Hc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}var Ic;
(async function(){function a(c){c=Ic=c.exports;gc=e.__sapp_emsc_onpaste=c.Ha;hc=e.__sapp_html5_get_ask_leave_site=c.Ia;ic=e.__sapp_emsc_begin_drop=c.Ja;jc=e.__sapp_emsc_drop=c.Ka;kc=e.__sapp_emsc_end_drop=c.La;e.__sapp_emsc_invoke_fetch_cb=c.Ma;e.__sapp_emsc_set_fullscreen_flag=c.Na;lc=e._main=c.Oa;e.__saudio_emsc_pull=c.Pa;e.__sfetch_emsc_head_response=c.Qa;e.__sfetch_emsc_get_response=c.Ra;e.__sfetch_emsc_failed_http_status=c.Sa;e.__sfetch_emsc_failed_buffer_too_small=c.Ta;e.__sfetch_emsc_failed_other=
c.Ua;R=c.Va;mc=c.Wa;nc=c.Xa;oc=c.Ya;pc=c.Za;qc=c._a;rc=c.$a;sc=c.ab;tc=c.bb;uc=c.fb;vc=c.gb;wc=c.ib;xc=c.jb;yc=c.kb;zc=c.qb;Ac=c.rb;Bc=c.sb;Cc=c.tb;Dc=c.vb;Ec=c.wb;Z=c.xb;rb=c.yb;Y=c.zb;ra=c.Fa;eb=c.ub;qa();C--;e.monitorRunDependencies?.(C);0==C&&D&&(c=D,D=null,c());return Ic}C++;e.monitorRunDependencies?.(C);var b={a:Fc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ua??=e.locateFile?e.locateFile("sdf-sapp.wasm",ia):ia+"sdf-sapp.wasm";return a((await xa(b)).instance)})();
Hc();
