var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),p,r=!1,na,la=a=>a.startsWith("file://"),oa,u,y,pa,qa,z,A,B,C,ra;
function sa(){var a=oa.buffer;u=new Int8Array(a);pa=new Int16Array(a);y=new Uint8Array(a);qa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var D=0,E=null;function ta(a){e.onAbort?.(a);a="Aborted("+a+")";k(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!p)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&p)a=new Uint8Array(p);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function ya(a){var b=va;if(!p&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(e)},Ba=[],Ca=[],Da=()=>{var a=e.preRun.shift();Ca.push(a)},Ea=!0,Fa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|h);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,
c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ga=0,G={},Ha=a=>{a instanceof za||"unwind"==a||fa(1,a)},Ia=a=>{na=a;Ea||0<Ga||(e.onExit?.(a),r=!0);fa(a,new za(a))},Ja=a=>{na=a;Ia(a)},Ka=()=>{if(!(Ea||0<Ga))try{var a=na;na=a;Ia(a)}catch(b){Ha(b)}},La=a=>{if(!r)try{a(),Ka()}catch(b){Ha(b)}},Ta=(a,b)=>{Ma=a;Na=b;if(H)if(Oa||=!0,0==a)I=function(){setTimeout(K,Math.max(0,Pa+b-performance.now())|0)};else if(1==a)I=function(){Qa(K)};else if(2==a){if("undefined"==
typeof Sa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Sa=setImmediate;I=function(){Sa(K)}}},bb=(a,b,c,d,f)=>{function h(){return g<Ua?(Ka(),!1):!0}H=a;Va=d;var g=Ua;Oa=!1;K=function(){if(!r)if(0<Wa.length){var m=
Wa.shift();m.uc(m.lc);if(Xa){var n=Xa,t=0==n%1?n-1:Math.floor(n);Xa=m.oc?t:(8*n+(t+.5))/9}e.setStatus&&(m=e.statusMessage||"Please wait...",n=Xa??0,t=Ya.tc??0,n?n<t?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(m):e.setStatus(""));h()&&setTimeout(K,0)}else if(h())if(Za=Za+1|0,1==Ma&&1<Na&&0!=Za%Na)I();else{0==Ma&&(Pa=performance.now());a:if(!r){for(m of $a)if(!1===m())break a;La(a);for(n of ab)n()}h()&&I()}};f||(0<b?Ta(0,1E3/b):Ta(1,1),I());if(c)throw"unwind";},Oa=!1,I=
null,Ua=0,H=null,Va=0,Ma=0,Na=0,Za=0,Wa=[],$a=[],ab=[];function cb(){I=null;Ua++}var L=0;function Qa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===L)L=b+1E3/60;else for(;b+2>=L;)L+=1E3/60;setTimeout(a,Math.max(L-b,0))}}
var Ya={},Pa,K,Sa,Xa,db=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?F(y,a):"":a;return db[a]||("undefined"!=typeof document?document.querySelector(a):null)},eb=a=>0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},fb=[],gb,N=a=>{var b=fb[a];b||(fb[a]=b=gb.get(a));return b};function hb(a){var b=O.pb[a];b.target.removeEventListener(b.mb,b.Zb,b.qb);O.pb.splice(a,1)}
function ib(){if(navigator.userActivation?navigator.userActivation.isActive:O.Qb&&O.jc.Nb){var a=O.Ab;O.Ab=[];for(var b of a)b.Ub(...b.Yb)}}function P(a){if(!a.target)return-4;if(a.rb)a.Zb=function(c){++O.Qb;O.jc=a;ib();a.yb(c);ib();--O.Qb},a.target.addEventListener(a.mb,a.Zb,a.qb),O.pb.push(a);else for(var b=0;b<O.pb.length;++b)O.pb[b].target==a.target&&O.pb[b].mb==a.mb&&hb(b--);return 0}function jb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var O={mc:0,vc:0,Rb:0,Bb:0,Xb:0,Wb:0,Ob:0,sc:0,yc:0,rc:0,Pb:0,Sb:0,Hc:0,Vb:0,xc(a,b,c){u.set(u.subarray(b,b+c),a)},zc(){for(;O.pb.length;)hb(O.pb.length-1);O.Ab=[]},Qb:0,Ab:[],qc(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var m in h)if(h[m]!=g[m])return!1;return!0}for(var f of O.Ab)if(f.Ub==a&&d(f.Yb,c))return;O.Ab.push({Ub:a,bc:b,Yb:c});O.Ab.sort((h,g)=>h.bc<g.bc)},Bc(a){O.Ab=O.Ab.filter(b=>b.Ub!=a)},pb:[],Ac:(a,b)=>{for(var c=0;c<O.pb.length;++c)O.pb[c].target!=a||b&&b!=O.pb[c].mb||
hb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Q=(a,b,c)=>{var d=y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;h++}}d[b]=0;return b-
f},kb=(a,b,c,d,f,h)=>{O.Ob||(O.Ob=R(256));a={target:M(a),mb:h,rb:d,yb:(g=event)=>{var m=g.target.id?g.target.id:"",n=O.Ob;Q(jb(g.target),n+0,128);Q(m,n+128,128);N(d)(f,n,b)&&g.preventDefault()},qb:c};return P(a)},lb=(a,b,c,d,f)=>{O.Pb||(O.Pb=R(276));return P({target:a,mb:f,rb:d,yb:(h=event)=>{var g=O.Pb,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!m;u[g]=n;u[g+1]=O.fullscreenEnabled();
var t=n?m:O.kc,v=t?.id||"";Q(jb(t),g+2,128);Q(v,g+130,128);z[g+260>>2]=t?t.clientWidth:0;z[g+264>>2]=t?t.clientHeight:0;z[g+268>>2]=screen.width;z[g+272>>2]=screen.height;n&&(O.kc=m);N(d)(19,g,b)&&h.preventDefault()},qb:c})},mb=(a,b,c,d,f,h)=>{O.Rb||(O.Rb=R(160));a={target:M(a),mb:h,rb:d,yb:g=>{var m=O.Rb;C[m>>3]=g.timeStamp;var n=m>>2;z[n+2]=g.location;u[m+12]=g.ctrlKey;u[m+13]=g.shiftKey;u[m+14]=g.altKey;u[m+15]=g.metaKey;u[m+16]=g.repeat;z[n+5]=g.charCode;z[n+6]=g.keyCode;z[n+7]=g.which;Q(g.key||
"",m+32,32);Q(g.code||"",m+64,32);Q(g.char||"",m+96,32);Q(g.locale||"",m+128,32);N(d)(f,m,b)&&g.preventDefault()},qb:c};return P(a)},nb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=eb(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},ob=(a,b,c,d,f,h)=>{O.Bb||(O.Bb=R(64));a=
M(a);return P({target:a,Nb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,mb:h,rb:d,yb:(g=event)=>{nb(O.Bb,g,a);N(d)(f,O.Bb,b)&&g.preventDefault()},qb:c})},pb=(a,b,c,d)=>{O.Sb||(O.Sb=R(257));return P({target:a,mb:"pointerlockchange",rb:d,yb:(f=event)=>{var h=O.Sb,g=document.pointerLockElement;u[h]=!!g;var m=g?.id||"";Q(jb(g),h+1,128);Q(m,h+129,128);N(d)(20,h,b)&&f.preventDefault()},qb:c})},qb=(a,b,c,d)=>P({target:a,mb:"pointerlockerror",rb:d,yb:(f=event)=>{N(d)(38,0,b)&&f.preventDefault()},qb:c}),
rb=(a,b,c,d)=>{O.Wb||(O.Wb=R(36));a=M(a);return P({target:a,mb:"resize",rb:d,yb:(f=event)=>{if(f.target==a){var h=document.body;if(h){var g=O.Wb;z[g>>2]=0;z[g+4>>2]=h.clientWidth;z[g+8>>2]=h.clientHeight;z[g+12>>2]=innerWidth;z[g+16>>2]=innerHeight;z[g+20>>2]=outerWidth;z[g+24>>2]=outerHeight;z[g+28>>2]=pageXOffset|0;z[g+32>>2]=pageYOffset|0;N(d)(10,g,b)&&f.preventDefault()}}},qb:c})},sb=(a,b,c,d,f,h)=>{O.Vb||(O.Vb=R(1552));a=M(a);return P({target:a,Nb:"touchstart"==h||"touchend"==h,mb:h,rb:d,yb:g=>
{var m={},n=g.touches;for(var t of n)t.$b=t.ac=0,m[t.identifier]=t;for(var v of g.changedTouches)v.$b=1,m[v.identifier]=v;for(var l of g.targetTouches)m[l.identifier].ac=1;n=O.Vb;C[n>>3]=g.timeStamp;u[n+12]=g.ctrlKey;u[n+13]=g.shiftKey;u[n+14]=g.altKey;u[n+15]=g.metaKey;t=n+16;v=eb(a);l=0;for(let q of Object.values(m))if(m=t>>2,z[m]=q.identifier,z[m+1]=q.screenX,z[m+2]=q.screenY,z[m+3]=q.clientX,z[m+4]=q.clientY,z[m+5]=q.pageX,z[m+6]=q.pageY,u[t+28]=q.$b,u[t+29]=q.ac,z[m+8]=q.clientX-(v.left|0),z[m+
9]=q.clientY-(v.top|0),t+=48,31<++l)break;z[n+8>>2]=l;N(d)(f,n,b)&&g.preventDefault()},qb:c})},tb=(a,b,c,d)=>{O.Xb||(O.Xb=R(96));return P({target:a,Nb:!0,mb:"wheel",rb:d,yb:(f=event)=>{var h=O.Xb;nb(h,f,a);C[h+64>>3]=f.deltaX;C[h+72>>3]=f.deltaY;C[h+80>>3]=f.deltaZ;z[h+88>>2]=f.deltaMode;N(d)(9,h,b)&&f.preventDefault()},qb:c})},ub=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},S=a=>{var b=ub(a)+1,c=vb(b);Q(a,c,b);return c},
wb=[],T=(a,b)=>{wb[a>>>=0]=b},xb=[],U=a=>{if(a)return wb[a>>>0]},yb=a=>{var b=A[a>>2];return b?F(y,b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?F(y,b,a):"";if(0===a)return""},zb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),Ab=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),Bb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,h=yb(f+4);c[h]=C[f+16>>3]}return c}},Cb=a=>a?U(a):"auto",Pb=a=>{function b(d){if(d)return{operation:Db[A[d>>2]],srcFactor:Eb[A[d+
4>>2]],dstFactor:Eb[A[d+8>>2]]}}function c(d){return{compare:Fb[A[d>>2]],failOp:Gb[A[d+4>>2]],depthFailOp:Gb[A[d+8>>2]],passOp:Gb[A[d+12>>2]]}}return{label:V(a+4),layout:Cb(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),h=Bb(A[d+16>>2],A[d+20>>2]);var g=A[d+24>>2];var m=A[d+28>>2];if(g){for(var n=[],t=0;t<g;++t){var v=n,l=v.push;var q=m+24*t;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var J=null;else{J=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Hb[w];q=A[q+20>>2];for(var Ib=[],Ra=0;Ra<x;++Ra){var Jb=
Ib,wc=Jb.push,ua=q+24*Ra;wc.call(Jb,{format:Kb[A[ua+4>>2]],offset:4294967296*A[ua+4+8>>2]+A[ua+8>>2],shaderLocation:A[ua+16>>2]})}J={arrayStride:J,stepMode:w,attributes:Ib}}}else J=void 0;l.call(v,J)}g=n}else g=void 0;return{module:f,constants:h,buffers:g,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Lb[A[d+4>>2]],stripIndexFormat:Mb[A[d+8>>2]],frontFace:Nb[A[d+12>>2]],cullMode:Ob[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+
4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Fb[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),h=Bb(A[d+16>>2],A[d+20>>2]),g=A[d+24>>2],m=A[d+28>>2],n=[],t=0;t<g;++t){var v=n,l=v.push,
q=m+24*t,w=A[q+4>>2];if(0===w)q=void 0;else{w=W[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}l.call(v,q)}return{module:f,constants:h,targets:n,entryPoint:V(d+8)}}}(A[a+92>>2])}},Qb=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",
32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);ra[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);ra[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);ra[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",
104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.wc&&c("maxImmediateSize",148)},Rb=[,"clamp-to-edge","repeat","mirror-repeat"],Eb=[,"zero","one","src","one-minus-src",
"src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Db=[,"add","subtract","reverse-subtract","min","max"],Sb=["binding-not-used",,"uniform","storage","read-only-storage"],Fb=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Tb=[,"opaque","premultiplied","unpremultiplied","inherit"],Ob=[,"none","front","back"],Ub=
[,"compatibility","core"],Vb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",
20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Wb=[,"nearest","linear"],Nb=[,"ccw","cw"],Mb=[,"uint16","uint32"],Xb=[,"load","clear"],Yb=[,"nearest","linear"],Zb=[,"low-power","high-performance"],$b=[,"srgb","display-p3"],Lb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],ac=["binding-not-used",,"filtering","non-filtering","comparison"],
Gb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],bc=["binding-not-used",,"write-only","read-only","read-write"],cc=[,"store","discard"],dc=[,"all","stencil-only","depth-only"],ec=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb",
"rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm",
"bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm",
"astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],fc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],gc=[,"1d","2d","2d-array","cube","cube-array","3d"],hc=[,"standard","extended"],
Kb=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Hb=[,"vertex","instance"],ic={undefined:1,unknown:1,
destroyed:2},jc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";jc.Tb||(jc.Tb={});jc.Tb[a]||(jc.Tb[a]=1,ca&&(a="warning: "+a),k(a))},kc={rgba8unorm:22,bgra8unorm:27},lc={},nc=()=>{if(!mc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in lc)void 0===lc[b]?delete a[b]:a[b]=lc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);mc=c}return mc},
mc,oc=[null,[],[]],pc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Qa;e.pauseMainLoop=cb;e.resumeMainLoop=function(){Ua++;var a=Ma,b=Na,c=H;H=null;bb(c,0,!1,Va,!0);Ta(a,b);I()};e.preMainLoop&&$a.push(e.preMainLoop);e.postMainLoop&&ab.push(e.postMainLoop);e.noExitRuntime&&(Ea=e.noExitRuntime);e.print&&(ma=e.print);e.printErr&&(k=e.printErr);e.wasmBinary&&(p=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
var qc,rc,sc,tc,uc,vc,R,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Y,vb,X,Qc={q:function(){return 0},Z:function(){return 0},_:function(){},ba:()=>ta(""),T:()=>{Ea=!1;Ga=0},U:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];La(()=>Oc(a,performance.now()))},b);G[a]={id:c,Fc:b};return 0},Ea:()=>{cb();H=null},O:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,Q:(a,b,c)=>{a=M(a);if(!a)return-4;a=eb(a);C[b>>3]=a.width;C[c>>3]=a.height;
return 0},Fa:()=>performance.now(),La:(a,b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},V:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},w:(a,b,c,d)=>kb(a,b,c,d,12,"blur"),N:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=
b;a.height=c;return 0},x:(a,b,c,d)=>kb(a,b,c,d,13,"focus"),v:(a,b,c,d)=>{if(!O.fullscreenEnabled())return-1;a=M(a);if(!a)return-4;lb(a,b,c,d,"webkitfullscreenchange");return lb(a,b,c,d,"fullscreenchange")},G:(a,b,c,d)=>mb(a,b,c,d,2,"keydown"),E:(a,b,c,d)=>mb(a,b,c,d,1,"keypress"),F:(a,b,c,d)=>mb(a,b,c,d,3,"keyup"),Ma:(a,b,c)=>{a=N(a);bb(a,b,c)},M:(a,b,c,d)=>ob(a,b,c,d,5,"mousedown"),J:(a,b,c,d)=>ob(a,b,c,d,33,"mouseenter"),I:(a,b,c,d)=>ob(a,b,c,d,34,"mouseleave"),K:(a,b,c,d)=>ob(a,b,c,d,8,"mousemove"),
L:(a,b,c,d)=>ob(a,b,c,d,6,"mouseup"),z:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?pb(a,b,c,d):-4:-1,y:(a,b,c,d)=>document.body?.requestPointerLock?(a=M(a))?qb(a,b,c,d):-4:-1,P:(a,b,c,d)=>rb(a,b,c,d),A:(a,b,c,d)=>sb(a,b,c,d,25,"touchcancel"),B:(a,b,c,d)=>sb(a,b,c,d,23,"touchend"),C:(a,b,c,d)=>sb(a,b,c,d,24,"touchmove"),D:(a,b,c,d)=>sb(a,b,c,d,22,"touchstart"),H:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?tb(a,b,c,d):-1:-4,fa:function(a,b,c,d,f,h){b=-9007199254740992>b||9007199254740992<
b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);var g={};if(h){var m=A[h+12>>2];if(m){var n=A[h+16>>2];g.requiredFeatures=Array.from(A.subarray(n>>2,n+4*m>>2),l=>Vb[l])}var t=A[h+20>>2];if(t){var v={};function l(w,x,J=!1){x=A[t+x>>2];4294967295==x||J&&0==x||(v[w]=x)}function q(w,x){x=t+x;var J=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=J)v[w]=4294967296*A[x+4>>2]+A[x>>2]}l("maxTextureDimension1D",4);l("maxTextureDimension2D",8);l("maxTextureDimension3D",12);l("maxTextureArrayLayers",
16);l("maxBindGroups",20);l("maxBindGroupsPlusVertexBuffers",24);l("maxDynamicUniformBuffersPerPipelineLayout",32);l("maxDynamicStorageBuffersPerPipelineLayout",36);l("maxSampledTexturesPerShaderStage",40);l("maxSamplersPerShaderStage",44);l("maxStorageBuffersPerShaderStage",48);l("maxStorageTexturesPerShaderStage",52);l("maxUniformBuffersPerShaderStage",56);l("minUniformBufferOffsetAlignment",80);l("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",
72);l("maxVertexBuffers",88);q("maxBufferSize",96);l("maxVertexAttributes",104);l("maxVertexBufferArrayStride",108);l("maxInterStageShaderVariables",112);l("maxColorAttachments",116);l("maxColorAttachmentBytesPerSample",120);l("maxComputeWorkgroupStorageSize",124);l("maxComputeInvocationsPerWorkgroup",128);l("maxComputeWorkgroupSizeX",132);l("maxComputeWorkgroupSizeY",136);l("maxComputeWorkgroupSizeZ",140);l("maxComputeWorkgroupsPerDimension",144);l("maxImmediateSize",148,!0);g.requiredLimits=v}if(m=
A[h+24>>2])m={label:V(m+4)},g.defaultQueue=m;g.label=V(h+4)}a.requestDevice(g).then(l=>{T(f,l.queue);T(d,l);c&&l.lost.then(q=>{l.onuncapturederror=()=>{};var w=X(),x=S(q.message);Kc(c,ic[q.reason],x);Y(w)});l.onuncapturederror=q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=X();q=S(q.error.message);Nc(d,w,q);Y(x)};Mc(b,1,d,0)},l=>{var q=X();l=S(l.message);Mc(b,3,d,l);c&&Kc(c,4,l);Y(q)})},ia:(a,b,c)=>
{var d=U(a);0===c&&jc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(g){return 0}var h=Pc(16,f.byteLength);y.fill(0,h,f.byteLength);xb[a].push(()=>{(new Uint8Array(f)).set(y.subarray(h,h+f.byteLength));xc(h)});return h},ha:a=>{var b=U(a),c=xb[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete xb[a];b.unmap()}},a:a=>{delete wb[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(h){return!1}T(c,
f);d&&(xb[c]=[]);return!0},ea:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=yb(d+8)}T(c,U(a).createShaderModule(b))},ga:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},ca:()=>{var a=navigator.gpu.getPreferredCanvasFormat();return kc[a]},da:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Ub[A[c+4>>2]],powerPreference:Zb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.Ic=!!A[a+8>>2])}"gpu"in
navigator?navigator.gpu.requestAdapter(f).then(h=>{if(h)T(d,h),Lc(b,1,d,0);else{h=X();var g=S("WebGPU not available on this browser (requestAdapter returned null)");Lc(b,3,d,g);Y(h)}},h=>{var g=X();h=S(h.message);Lc(b,4,d,h);Y(g)}):(f=X(),a=S("WebGPU not available on this browser (navigator.gpu is not available)"),Lc(b,3,d,a),Y(f))},$:(a,b)=>{var c=0,d=0,f;for(f of nc()){var h=b+c;A[a+d>>2]=h;c+=Q(f,h,Infinity)+1;d+=4}return 0},aa:(a,b)=>{var c=nc();A[a>>2]=c.length;a=0;for(var d of c)a+=ub(d)+1;
A[b>>2]=a;return 0},o:()=>52,Y:()=>52,W:function(){return 70},X:(a,b,c,d)=>{for(var f=0,h=0;h<c;h++){var g=A[b>>2],m=A[b+4>>2];b+=8;for(var n=0;n<m;n++){var t=a,v=y[g+n],l=oc[t];0===v||10===v?((1===t?ma:k)(F(l)),l.length=0):l.push(v)}f+=m}A[d>>2]=f;return 0},S:Ia,Ra:function(){e.cc=a=>{0!=rc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.cc)},Ka:function(){e.ic=a=>{const b=a.clipboardData.getData("text");pc(()=>{const c=S(b);qc(c)})};window.addEventListener("paste",
e.ic)},Ba:function(){e.Cc=[];e.dc=b=>{b.stopPropagation();b.preventDefault()};e.ec=b=>{b.stopPropagation();b.preventDefault()};e.fc=b=>{b.stopPropagation();b.preventDefault()};e.hc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Dc=c;sc(c.length);for(let f=0;f<c.length;f++)pc(()=>{const h=S(c[f].name);tc(f,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);uc(b.clientX,b.clientY,d)};const a=e.zb;a.addEventListener("dragenter",e.dc,!1);a.addEventListener("dragleave",
e.ec,!1);a.addEventListener("dragover",e.fc,!1);a.addEventListener("drop",e.hc,!1)},Oa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Pa:function(a){e.Cb&&(URL.revokeObjectURL(e.Cb[a].nc),e.Cb[a]=null)},ma:function(a,b){0!==b&&(document.title=b?F(y,b):"");a=a?F(y,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?db[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.zb=M(a);e.zb||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);e.zb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Qa:function(){window.removeEventListener("beforeunload",e.cc)},Ha:function(){window.removeEventListener("paste",e.ic)},ua:function(){const a=e.zb;a.removeEventListener("dragenter",e.dc);a.removeEventListener("dragleave",e.ec);a.removeEventListener("dragover",e.fc);a.removeEventListener("drop",e.hc)},h:function(){e.zb&&e.zb.requestPointerLock&&e.zb.requestPointerLock()},p:function(a,b,c){if(e.zb){if(0===
b)a="none";else if(0!=c)a=e.Cb[a].pc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.zb.style.cursor=a}},Na:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),h=f.createImageData(a,
b);h.data.set(y.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ga:function(a){a=a?F(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);
b.select();document.execCommand("copy");document.body.removeChild(b)},r:function(){return navigator.userAgent.includes("Macintosh")?1:0},R:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},e:(a,b)=>U(a).features.has(Vb[b]),va:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],h=A[b+16>>2],g=[],m=0;m<f;++m){var n=g,t=n.push;var v=h+56*m;var l=A[v+
4>>2];if(0!==l){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:U(l),depthSlice:q,resolveTarget:U(A[v+12>>2]),clearValue:zb(v+24),loadOp:Xb[A[v+16>>2]],storeOp:cc[A[v+20>>2]]}}else v=void 0;t.call(n,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Xb[A[f+8>>2]],depthStoreOp:cc[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Xb[A[f+24>>2]],stencilStoreOp:cc[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;h=A[b+28>>2];h=0!==h?{querySet:U(A[h+
4>>2]),beginningOfPassWriteIndex:A[h+8>>2],endOfPassWriteIndex:A[h+12>>2]}:void 0;b={label:c,colorAttachments:g,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:h,maxDrawCount:d};a=U(a);d=Ec(0);T(d,a.beginRenderPass(b));return d},ka:a=>{a=U(a);var b=Ac(0);T(b,a.finish());return b},la:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ta:(a,b)=>{U(a).setPipeline(U(b))},l:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+
20>>2];for(var h=[],g=0;g<f;++g){var m=h,n=m.push;var t=b+40*g;var v=A[t+8>>2],l=A[t+32>>2],q=A[t+36>>2],w=A[t+4>>2];v?(l=t+24,l=A[l>>2]+4294967296*z[l+4>>2],-1==l&&(l=void 0),t={binding:w,resource:{buffer:U(v),offset:4294967296*A[t+4+16>>2]+A[t+16>>2],size:l}}):t=l?{binding:w,resource:U(l)}:{binding:w,resource:U(q)};n.call(m,t)}c={label:c,layout:d,entries:h};a=U(a);d=yc(0);T(d,a.createBindGroup(c));return d},m:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],h=0;h<d;++h){var g=f,m=g.push,
n=b+88*h,t=A[n+4>>2],v=A[n+8>>2];var l=n+24;var q=A[l+4>>2];l=q?{type:Sb[q],hasDynamicOffset:!!A[l+8>>2],minBindingSize:4294967296*A[l+4+16>>2]+A[l+16>>2]}:void 0;q=(q=A[n+48+4>>2])?{type:ac[q]}:void 0;var w=n+56;var x=A[w+4>>2];w=x?{sampleType:fc[x],viewDimension:gc[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;n+=72;n=(x=A[n+4>>2])?{access:bc[x],format:W[A[n+8>>2]],viewDimension:gc[A[n+12>>2]]}:void 0;m.call(g,{binding:t,visibility:v,buffer:l,sampler:q,texture:w,storageTexture:n})}c={label:c,entries:f};
a=U(a);d=zc(0);T(d,a.createBindGroupLayout(c));return d},u:(a,b)=>{var c;b&&(c={label:V(b+4)});a=U(a);b=Bc(0);T(b,a.createCommandEncoder(c));return b},xa:(a,b)=>{var c=V(b+4);var d=Cb(A[b+12>>2]);b=(b+=16)?{module:U(A[b+4>>2]),constants:Bb(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=Cc(0);T(d,a.createComputePipeline(c));return d},ya:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],h=0;h<c;++h)f.push(U(A[d+4*h>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);
c=Dc(0);T(c,a.createPipelineLayout(b));return c},wa:(a,b)=>{b=Pb(b);a=U(a);var c=Fc(0);T(c,a.createRenderPipeline(b));return c},za:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Rb[A[b+12>>2]],addressModeV:Rb[A[b+16>>2]],addressModeW:Rb[A[b+20>>2]],magFilter:Wb[A[b+24>>2]],minFilter:Wb[A[b+28>>2]],mipmapFilter:Yb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Fb[A[b+44>>2]],maxAnisotropy:qa[b+48>>1]});a=U(a);b=Gc(0);T(b,a.createSampler(c));return b},n:(a,b)=>{var c={label:V(b+4),
size:Ab(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:ec[A[b+24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=Ic(0);T(d,a.createTexture(c));return d},Ca:(a,b)=>{Qb(U(a).limits,b);return 1},d:(a,b)=>U(a).features.has(Vb[b]),Ja:(a,b)=>{a=M(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.Ec=V(b+4);b=Hc(0);T(b,a);return b},ja:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),
d=>U(d));a.submit(b)},i:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},Aa:(a,b,c,d,f,h)=>{var g=A[f+8>>2],m=A[f+12>>2],n=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[n>>2],y:A[n+4>>2],z:A[n+8>>2]},aspect:dc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===g?void 0:g,rowsPerImage:4294967295===m?void 0:m},Ab(h))},s:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>
0)},t:(a,b,c,d,f,h)=>{U(a).drawIndexed(b,c,d>>>0,f,h>>>0)},na:a=>{U(a).end()},b:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ra:(a,b)=>{U(a).setBlendConstant(zb(b))},pa:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Mb[c],d,f)},sa:(a,b)=>{U(a).setPipeline(U(b))},j:(a,b,c,d,f)=>{U(a).setScissorRect(b,c,d,f)},qa:(a,b)=>{U(a).setStencilReference(b>>>
0)},oa:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},k:(a,b,c,d,f,h,g)=>{U(a).setViewport(b,c,d,f,h,g)},Ia:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Tb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=
Array.from(z.subarray(f>>2,f+4*d>>2),h=>W[h])}b=A[b>>2];0!==b&&(c.colorSpace=$b[A[b+8>>2]],c.Gc={mode:hc[A[b+12>>2]]});a.configure(c)},Da:(a,b)=>{a=U(a);try{var c=Ic(0);T(c,a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:gc[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:dc[A[b+
36>>2]]}}a=U(a);b=Jc(0);T(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Sa;sa();gb=Z.Hb;c=Z;e.__sapp_emsc_onpaste=qc=c.Ua;e.__sapp_html5_get_ask_leave_site=rc=c.Va;e.__sapp_emsc_begin_drop=sc=c.Wa;e.__sapp_emsc_drop=tc=c.Xa;e.__sapp_emsc_end_drop=uc=c.Ya;e.__sapp_emsc_invoke_fetch_cb=c.Za;e.__sapp_emsc_set_fullscreen_flag=c._a;e._main=vc=c.$a;e.__saudio_emsc_pull=c.ab;e.__sfetch_emsc_head_response=c.bb;e.__sfetch_emsc_get_response=c.cb;e.__sfetch_emsc_failed_http_status=c.db;e.__sfetch_emsc_failed_buffer_too_small=c.eb;
e.__sfetch_emsc_failed_other=c.fb;R=c.gb;xc=c.hb;yc=c.ib;zc=c.jb;Ac=c.kb;Bc=c.lb;Cc=c.nb;Dc=c.ob;Ec=c.sb;Fc=c.tb;Gc=c.ub;Hc=c.vb;Ic=c.wb;Jc=c.xb;Kc=c.Db;Lc=c.Eb;Mc=c.Fb;Nc=c.Gb;Oc=c.Ib;Pc=c.Jb;Y=c.Kb;vb=c.Lb;X=c.Mb;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Qc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});va??=e.locateFile?e.locateFile("tex3d-sapp-ui.wasm",ia):ia+"tex3d-sapp-ui.wasm";return a((await ya(b)).instance)})();
function Rc(a=[]){var b=vc;a.unshift(ea);var c=a.length,d=vb(4*(c+1)),f=d;a.forEach(g=>{A[f>>2]=S(g);f+=4});A[f>>2]=0;try{var h=b(c,d);Ja(h)}catch(g){Ha(g)}}
function Sc(a=da){function b(){e.calledRun=!0;if(!r){Z.Ta();e.onRuntimeInitialized?.();e.noInitialRun||Rc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<D)E=Sc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Aa(Ca);0<D?E=Sc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Sc();
