var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var h=console.error.bind(console),n,r=!1,ma,la=a=>a.startsWith("file://"),na,t,y,oa,pa,z,A,B,C,qa;
function ra(){var a=na.buffer;t=new Int8Array(a);oa=new Int16Array(a);y=new Uint8Array(a);pa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);B=new Float32Array(a);C=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}var D=0,E=null;function sa(a){e.onAbort?.(a);a="Aborted("+a+")";h(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(e)},za=[],Aa=[],Ba=()=>{var a=e.preRun.shift();Aa.push(a)},Ca=!0,Da=0,F={},Ea=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Fa=a=>{ma=a;Ca||0<Da||(e.onExit?.(a),r=!0);fa(a,new xa(a))},Ga=a=>{ma=a;Fa(a)},Ha=()=>{if(!(Ca||0<Da))try{var a=ma;ma=a;Fa(a)}catch(b){Ea(b)}},Ia=a=>{if(!r)try{a(),Ha()}catch(b){Ea(b)}},Pa=(a,b)=>{Ja=a;Ka=b;if(G)if(La||=!0,0==a)I=function(){setTimeout(J,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)I=function(){Na(J)};else if(2==a){if("undefined"==
typeof Oa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Oa=setImmediate;I=function(){Oa(J)}}},Za=(a,b,c,d,f)=>{function g(){return k<Ra?(Ha(),!1):!0}G=a;Sa=d;var k=Ra;La=!1;J=function(){if(!r)if(0<Ta.length){var m=
Ta.shift();m.hc(m.Xb);if(Ua){var p=Ua,u=0==p%1?p-1:Math.floor(p);Ua=m.$b?u:(8*p+(u+.5))/9}e.setStatus&&(m=e.statusMessage||"Please wait...",p=Ua??0,u=Va.ec??0,p?p<u?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(m):e.setStatus(""));g()&&setTimeout(J,0)}else if(g())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)I();else{0==Ja&&(Ma=performance.now());a:if(!r){for(m of Xa)if(!1===m())break a;Ia(a);for(p of Ya)p()}g()&&I()}};f||(0<b?Pa(0,1E3/b):Pa(1,1),I());if(c)throw"unwind";},La=!1,I=
null,Ra=0,G=null,Sa=0,Ja=0,Ka=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){I=null;Ra++}var ab=0;function Na(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ab)ab=b+1E3/60;else for(;b+2>=ab;)ab+=1E3/60;setTimeout(a,Math.max(ab-b,0))}}
var Va={},Ma,J,Oa,Ua,bb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,K=(a=0,b)=>{var c=y;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&bb)return bb.decode(c.subarray(a,d));for(b="";a<d;){var f=c[a++];if(f&128){var g=c[a++]&63;if(192==(f&224))b+=String.fromCharCode((f&31)<<6|g);else{var k=c[a++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|c[a++]&63;65536>f?b+=String.fromCharCode(f):(f-=65536,b+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else b+=String.fromCharCode(f)}return b},
cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],L=a=>{a=2<a?a?K(a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):null)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],fb,M=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};function gb(a){var b=N.cb[a];b.target.removeEventListener(b.bb,b.Mb,b.lb);N.cb.splice(a,1)}
function hb(){if(navigator.userActivation?navigator.userActivation.isActive:N.Db&&N.Wb.Bb){var a=N.nb;N.nb=[];for(var b of a)b.Hb(...b.Lb)}}function O(a){if(!a.target)return-4;if(a.mb)a.Mb=function(c){++N.Db;N.Wb=a;hb();a.ob(c);hb();--N.Db},a.target.addEventListener(a.bb,a.Mb,a.lb),N.cb.push(a);else for(var b=0;b<N.cb.length;++b)N.cb[b].target==a.target&&N.cb[b].bb==a.bb&&gb(b--);return 0}function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var N={Yb:0,ic:0,Eb:0,zb:0,Kb:0,Jb:0,Cb:0,dc:0,lc:0,cc:0,fc:0,Fb:0,uc:0,Ib:0,kc(a,b,c){t.set(t.subarray(b,b+c),a)},mc(){for(;N.cb.length;)gb(N.cb.length-1);N.nb=[]},Db:0,nb:[],bc(a,b,c){function d(g,k){if(g.length!=k.length)return!1;for(var m in g)if(g[m]!=k[m])return!1;return!0}for(var f of N.nb)if(f.Hb==a&&d(f.Lb,c))return;N.nb.push({Hb:a,Pb:b,Lb:c});N.nb.sort((g,k)=>g.Pb<k.Pb)},oc(a){N.nb=N.nb.filter(b=>b.Hb!=a)},cb:[],nc:(a,b)=>{for(var c=0;c<N.cb.length;++c)N.cb[c].target!=a||b&&b!=N.cb[c].bb||
gb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},P=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0}},jb=(a,b,c,d,f,g)=>{N.Cb||
(N.Cb=Q(256));a={target:L(a),bb:g,mb:d,ob:(k=event)=>{var m=k.target.id?k.target.id:"",p=N.Cb;P(ib(k.target),p+0,128);P(m,p+128,128);M(d)(f,p,b)&&k.preventDefault()},lb:c};return O(a)},kb=(a,b,c,d,f,g)=>{N.Eb||(N.Eb=Q(160));a={target:L(a),bb:g,mb:d,ob:k=>{var m=N.Eb;C[m>>3]=k.timeStamp;var p=m>>2;z[p+2]=k.location;t[m+12]=k.ctrlKey;t[m+13]=k.shiftKey;t[m+14]=k.altKey;t[m+15]=k.metaKey;t[m+16]=k.repeat;z[p+5]=k.charCode;z[p+6]=k.keyCode;z[p+7]=k.which;P(k.key||"",m+32,32);P(k.code||"",m+64,32);P(k.char||
"",m+96,32);P(k.locale||"",m+128,32);M(d)(f,m,b)&&k.preventDefault()},lb:c};return O(a)},lb=(a,b,c)=>{C[a>>3]=b.timeStamp;var d=a>>2;z[d+2]=b.screenX;z[d+3]=b.screenY;z[d+4]=b.clientX;z[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;z[d+8]=b.movementX;z[d+9]=b.movementY;a=db(c);z[d+10]=b.clientX-(a.left|0);z[d+11]=b.clientY-(a.top|0)},mb=(a,b,c,d,f,g)=>{N.zb||(N.zb=Q(64));a=L(a);return O({target:a,Bb:"mousemove"!=g&&
"mouseenter"!=g&&"mouseleave"!=g,bb:g,mb:d,ob:(k=event)=>{lb(N.zb,k,a);M(d)(f,N.zb,b)&&k.preventDefault()},lb:c})},nb=(a,b,c,d)=>{N.Fb||(N.Fb=Q(257));return O({target:a,bb:"pointerlockchange",mb:d,ob:(f=event)=>{var g=N.Fb,k=document.pointerLockElement;t[g]=!!k;var m=k?.id||"";P(ib(k),g+1,128);P(m,g+129,128);M(d)(20,g,b)&&f.preventDefault()},lb:c})},ob=(a,b,c,d)=>O({target:a,bb:"pointerlockerror",mb:d,ob:(f=event)=>{M(d)(38,0,b)&&f.preventDefault()},lb:c}),pb=(a,b,c,d)=>{N.Jb||(N.Jb=Q(36));a=L(a);
return O({target:a,bb:"resize",mb:d,ob:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=N.Jb;z[k>>2]=0;z[k+4>>2]=g.clientWidth;z[k+8>>2]=g.clientHeight;z[k+12>>2]=innerWidth;z[k+16>>2]=innerHeight;z[k+20>>2]=outerWidth;z[k+24>>2]=outerHeight;z[k+28>>2]=pageXOffset|0;z[k+32>>2]=pageYOffset|0;M(d)(10,k,b)&&f.preventDefault()}}},lb:c})},qb=(a,b,c,d,f,g)=>{N.Ib||(N.Ib=Q(1552));a=L(a);return O({target:a,Bb:"touchstart"==g||"touchend"==g,bb:g,mb:d,ob:k=>{var m={},p=k.touches;for(var u of p)u.Nb=
u.Ob=0,m[u.identifier]=u;for(var v of k.changedTouches)v.Nb=1,m[v.identifier]=v;for(var l of k.targetTouches)m[l.identifier].Ob=1;p=N.Ib;C[p>>3]=k.timeStamp;t[p+12]=k.ctrlKey;t[p+13]=k.shiftKey;t[p+14]=k.altKey;t[p+15]=k.metaKey;u=p+16;v=db(a);l=0;for(let q of Object.values(m))if(m=u>>2,z[m]=q.identifier,z[m+1]=q.screenX,z[m+2]=q.screenY,z[m+3]=q.clientX,z[m+4]=q.clientY,z[m+5]=q.pageX,z[m+6]=q.pageY,t[u+28]=q.Nb,t[u+29]=q.Ob,z[m+8]=q.clientX-(v.left|0),z[m+9]=q.clientY-(v.top|0),u+=48,31<++l)break;
z[p+8>>2]=l;M(d)(f,p,b)&&k.preventDefault()},lb:c})},rb=(a,b,c,d)=>{N.Kb||(N.Kb=Q(96));return O({target:a,Bb:!0,bb:"wheel",mb:d,ob:(f=event)=>{var g=N.Kb;lb(g,f,a);C[g+64>>3]=f.deltaX;C[g+72>>3]=f.deltaY;C[g+80>>3]=f.deltaZ;z[g+88>>2]=f.deltaMode;M(d)(9,g,b)&&f.preventDefault()},lb:c})},R=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b+=1;c=sb(b);P(a,c,b);return c},tb=[],S=(a,b)=>{tb[a>>>=0]=b},ub=[],U=a=>{if(a)return tb[a>>>0]},
vb=a=>{var b=A[a>>2];return b?K(b,A[a+4>>2]):""},V=a=>{var b=A[a>>2];a=A[a+4>>2];if(b)return b?K(b,a):"";if(0===a)return""},wb=a=>({r:C[a>>3],g:C[a+8>>3],b:C[a+16>>3],a:C[a+24>>3]}),xb=a=>({width:A[a>>2],height:A[a+4>>2],depthOrArrayLayers:A[a+8>>2]}),yb=a=>{if(0!==a)return{querySet:U(A[a+4>>2]),beginningOfPassWriteIndex:A[a+8>>2],endOfPassWriteIndex:A[a+12>>2]}},zb=(a,b)=>{if(a){for(var c={},d=0;d<a;++d){var f=b+24*d,g=vb(f+4);c[g]=C[f+16>>3]}return c}},Ab=a=>a?U(a):"auto",Nb=a=>{function b(d){if(d)return{operation:Bb[A[d>>
2]],srcFactor:Cb[A[d+4>>2]],dstFactor:Cb[A[d+8>>2]]}}function c(d){return{compare:Db[A[d>>2]],failOp:Gb[A[d+4>>2]],depthFailOp:Gb[A[d+8>>2]],passOp:Gb[A[d+12>>2]]}}return{label:V(a+4),layout:Ab(A[a+12>>2]),vertex:function(d){if(d){var f=U(A[d+4>>2]),g=zb(A[d+16>>2],A[d+20>>2]);var k=A[d+24>>2];var m=A[d+28>>2];if(k){for(var p=[],u=0;u<k;++u){var v=p,l=v.push;var q=m+24*u;if(q){var w=A[q+4>>2],x=A[q+16>>2];if(0===w&&0===x)var H=null;else{H=4294967296*A[q+4+8>>2]+A[q+8>>2];w=Hb[w];q=A[q+20>>2];for(var Eb=
[],Qa=0;Qa<x;++Qa){var Fb=Eb,sc=Fb.push;var T=q+24*Qa;T={format:Ib[A[T+4>>2]],offset:4294967296*A[T+4+8>>2]+A[T+8>>2],shaderLocation:A[T+16>>2]};sc.call(Fb,T)}H={arrayStride:H,stepMode:w,attributes:Eb}}}else H=void 0;l.call(v,H)}k=p}else k=void 0;return{module:f,constants:g,buffers:k,entryPoint:V(d+8)}}}(a+16),primitive:function(d){if(d)return{topology:Jb[A[d+4>>2]],stripIndexFormat:Kb[A[d+8>>2]],frontFace:Lb[A[d+12>>2]],cullMode:Mb[A[d+16>>2]],unclippedDepth:!!A[d+20>>2]}}(a+48),depthStencil:function(d){if(d)return{format:W[A[d+
4>>2]],depthWriteEnabled:!!A[d+8>>2],depthCompare:Db[A[d+12>>2]],stencilFront:c(d+16),stencilBack:c(d+32),stencilReadMask:A[d+48>>2],stencilWriteMask:A[d+52>>2],depthBias:z[d+56>>2],depthBiasSlopeScale:B[d+60>>2],depthBiasClamp:B[d+64>>2]}}(A[a+72>>2]),multisample:function(d){if(d)return{count:A[d+4>>2],mask:A[d+8>>2],alphaToCoverageEnabled:!!A[d+12>>2]}}(a+76),fragment:function(d){if(d){for(var f=U(A[d+4>>2]),g=zb(A[d+16>>2],A[d+20>>2]),k=A[d+24>>2],m=A[d+28>>2],p=[],u=0;u<k;++u){var v=p,l=v.push,
q=m+24*u,w=A[q+4>>2];if(0===w)q=void 0;else{w=W[w];var x=(x=A[q+8>>2])?{alpha:b(x+12),color:b(x+0)}:void 0;q={format:w,blend:x,writeMask:A[q+16>>2]}}l.call(v,q)}return{module:f,constants:g,targets:p,entryPoint:V(d+8)}}}(A[a+92>>2])}},Ob=(a,b)=>{function c(d,f){z[b+f>>2]=a[d]}c("maxTextureDimension1D",4);c("maxTextureDimension2D",8);c("maxTextureDimension3D",12);c("maxTextureArrayLayers",16);c("maxBindGroups",20);c("maxBindGroupsPlusVertexBuffers",24);c("maxBindingsPerBindGroup",28);c("maxDynamicUniformBuffersPerPipelineLayout",
32);c("maxDynamicStorageBuffersPerPipelineLayout",36);c("maxSampledTexturesPerShaderStage",40);c("maxSamplersPerShaderStage",44);c("maxStorageBuffersPerShaderStage",48);c("maxStorageTexturesPerShaderStage",52);c("maxUniformBuffersPerShaderStage",56);c("minUniformBufferOffsetAlignment",80);c("minStorageBufferOffsetAlignment",84);qa[b+64>>3]=BigInt(a.maxUniformBufferBindingSize);qa[b+72>>3]=BigInt(a.maxStorageBufferBindingSize);c("maxVertexBuffers",88);qa[b+96>>3]=BigInt(a.maxBufferSize);c("maxVertexAttributes",
104);c("maxVertexBufferArrayStride",108);c("maxInterStageShaderVariables",112);c("maxColorAttachments",116);c("maxColorAttachmentBytesPerSample",120);c("maxComputeWorkgroupStorageSize",124);c("maxComputeInvocationsPerWorkgroup",128);c("maxComputeWorkgroupSizeX",132);c("maxComputeWorkgroupSizeY",136);c("maxComputeWorkgroupSizeZ",140);c("maxComputeWorkgroupsPerDimension",144);void 0!==a.jc&&c("maxImmediateSize",148)},Pb=[,"clamp-to-edge","repeat","mirror-repeat"],Cb=[,"zero","one","src","one-minus-src",
"src-alpha","one-minus-src-alpha","dst","one-minus-dst","dst-alpha","one-minus-dst-alpha","src-alpha-saturated","constant","one-minus-constant","src1","one-minus-src1","src1alpha","one-minus-src1alpha"],Bb=[,"add","subtract","reverse-subtract","min","max"],Qb=["binding-not-used",,"uniform","storage","read-only-storage"],Db=[,"never","less","equal","less-equal","greater","not-equal","greater-equal","always"],Rb=[,"opaque","premultiplied","unpremultiplied","inherit"],Mb=[,"none","front","back"],Sb=
[,"compatibility","core"],Tb={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",
20:"texture-formats-tier2",327692:"chromium-experimental-unorm16-texture-formats",327693:"chromium-experimental-snorm16-texture-formats",327732:"chromium-experimental-multi-draw-indirect"},Ub=[,"nearest","linear"],Lb=[,"ccw","cw"],Kb=[,"uint16","uint32"],Vb=[,"load","clear"],Wb=[,"nearest","linear"],Xb=[,"low-power","high-performance"],Yb=[,"srgb","display-p3"],Jb=[,"point-list","line-list","line-strip","triangle-list","triangle-strip"],Zb=["binding-not-used",,"filtering","non-filtering","comparison"],
Gb=[,"keep","zero","replace","invert","increment-clamp","decrement-clamp","increment-wrap","decrement-wrap"],$b=["binding-not-used",,"write-only","read-only","read-write"],ac=[,"store","discard"],bc=[,"all","stencil-only","depth-only"],cc=[,"1d","2d","3d"],W=[,"r8unorm","r8snorm","r8uint","r8sint","r16unorm","r16snorm","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16unorm","rg16snorm","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb",
"rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2uint","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16unorm","rgba16snorm","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8","bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm",
"bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb","astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm",
"astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],dc=["binding-not-used",,"float","unfilterable-float","depth","sint","uint"],ec=[,"1d","2d","2d-array","cube","cube-array","3d"],fc=[,"standard","extended"],
Ib=[,"uint8","uint8x2","uint8x4","sint8","sint8x2","sint8x4","unorm8","unorm8x2","unorm8x4","snorm8","snorm8x2","snorm8x4","uint16","uint16x2","uint16x4","sint16","sint16x2","sint16x4","unorm16","unorm16x2","unorm16x4","snorm16","snorm16x2","snorm16x4","float16","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4","unorm10-10-10-2","unorm8x4-bgra"],Hb=[,"vertex","instance"],gc={undefined:1,unknown:1,
destroyed:2},hc=()=>{var a="getMappedRange size=0 no longer means WGPU_WHOLE_MAP_SIZE";hc.Gb||(hc.Gb={});hc.Gb[a]||(hc.Gb[a]=1,ca&&(a="warning: "+a),h(a))},ic={rgba8unorm:22,bgra8unorm:27},jc=a=>{var b=X();a();Y(b)};e.requestAnimationFrame=Na;e.pauseMainLoop=$a;e.resumeMainLoop=function(){Ra++;var a=Ja,b=Ka,c=G;G=null;Za(c,0,!1,Sa,!0);Pa(a,b);I()};e.preMainLoop&&Xa.push(e.preMainLoop);e.postMainLoop&&Ya.push(e.postMainLoop);e.noExitRuntime&&(Ca=e.noExitRuntime);e.printErr&&(h=e.printErr);
e.wasmBinary&&(n=e.wasmBinary);e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);
var Q,kc,lc,mc,nc,oc,pc,qc,rc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Y,sb,X,Lc={Q:()=>sa(""),N:()=>{Ca=!1;Da=0},O:(a,b)=>{F[a]&&(clearTimeout(F[a].id),delete F[a]);if(!b)return 0;var c=setTimeout(()=>{delete F[a];Ia(()=>Jc(a,performance.now()))},b);F[a]={id:c,sc:b};return 0},sa:()=>{$a();G=null},H:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,J:(a,b,c)=>{a=L(a);if(!a)return-4;a=db(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},ta:()=>performance.now(),za:(a,b)=>{function c(d){M(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},P:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ra();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},p:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),G:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},q:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),z:(a,
b,c,d)=>kb(a,b,c,d,2,"keydown"),x:(a,b,c,d)=>kb(a,b,c,d,1,"keypress"),y:(a,b,c,d)=>kb(a,b,c,d,3,"keyup"),Aa:(a,b,c)=>{a=M(a);Za(a,b,c)},F:(a,b,c,d)=>mb(a,b,c,d,5,"mousedown"),C:(a,b,c,d)=>mb(a,b,c,d,33,"mouseenter"),B:(a,b,c,d)=>mb(a,b,c,d,34,"mouseleave"),D:(a,b,c,d)=>mb(a,b,c,d,8,"mousemove"),E:(a,b,c,d)=>mb(a,b,c,d,6,"mouseup"),s:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?nb(a,b,c,d):-4:-1,r:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?ob(a,b,c,d):-4:-1,I:(a,b,c,d)=>pb(a,b,
c,d),t:(a,b,c,d)=>qb(a,b,c,d,25,"touchcancel"),u:(a,b,c,d)=>qb(a,b,c,d,23,"touchend"),v:(a,b,c,d)=>qb(a,b,c,d,24,"touchmove"),w:(a,b,c,d)=>qb(a,b,c,d,22,"touchstart"),A:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?rb(a,b,c,d):-1:-4,V:function(a,b,c,d,f,g){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);a=U(a);var k={};if(g){var m=A[g+12>>2];if(m){var p=A[g+16>>2];k.requiredFeatures=Array.from(A.subarray(p>>2,p+4*m>>2),l=>Tb[l])}var u=
A[g+20>>2];if(u){var v={};function l(w,x,H=!1){x=A[u+x>>2];4294967295==x||H&&0==x||(v[w]=x)}function q(w,x){x=u+x;var H=A[x+4>>2];if(4294967295!=A[x>>2]||4294967295!=H)v[w]=4294967296*A[x+4>>2]+A[x>>2]}l("maxTextureDimension1D",4);l("maxTextureDimension2D",8);l("maxTextureDimension3D",12);l("maxTextureArrayLayers",16);l("maxBindGroups",20);l("maxBindGroupsPlusVertexBuffers",24);l("maxDynamicUniformBuffersPerPipelineLayout",32);l("maxDynamicStorageBuffersPerPipelineLayout",36);l("maxSampledTexturesPerShaderStage",
40);l("maxSamplersPerShaderStage",44);l("maxStorageBuffersPerShaderStage",48);l("maxStorageTexturesPerShaderStage",52);l("maxUniformBuffersPerShaderStage",56);l("minUniformBufferOffsetAlignment",80);l("minStorageBufferOffsetAlignment",84);q("maxUniformBufferBindingSize",64);q("maxStorageBufferBindingSize",72);l("maxVertexBuffers",88);q("maxBufferSize",96);l("maxVertexAttributes",104);l("maxVertexBufferArrayStride",108);l("maxInterStageShaderVariables",112);l("maxColorAttachments",116);l("maxColorAttachmentBytesPerSample",
120);l("maxComputeWorkgroupStorageSize",124);l("maxComputeInvocationsPerWorkgroup",128);l("maxComputeWorkgroupSizeX",132);l("maxComputeWorkgroupSizeY",136);l("maxComputeWorkgroupSizeZ",140);l("maxComputeWorkgroupsPerDimension",144);l("maxImmediateSize",148,!0);k.requiredLimits=v}if(m=A[g+24>>2])m={label:V(m+4)},k.defaultQueue=m;k.label=V(g+4)}a.requestDevice(k).then(l=>{S(f,l.queue);S(d,l);c&&l.lost.then(q=>{l.onuncapturederror=()=>{};var w=X(),x=R(q.message);Fc(c,gc[q.reason],x);Y(w)});l.onuncapturederror=
q=>{var w=5;q.error instanceof GPUValidationError?w=2:q.error instanceof GPUOutOfMemoryError?w=3:q.error instanceof GPUInternalError&&(w=4);var x=X();q=R(q.error.message);Ic(d,w,q);Y(x)};Hc(b,1,d,0)},l=>{var q=X();l=R(l.message);Hc(b,3,d,l);c&&Fc(c,4,l);Y(q)})},Y:(a,b,c)=>{var d=U(a);0===c&&hc();-1==c&&(c=void 0);try{var f=d.getMappedRange(b,c)}catch(k){return 0}var g=Kc(16,f.byteLength);y.fill(0,g,f.byteLength);ub[a].push(()=>{(new Uint8Array(f)).set(y.subarray(g,g+f.byteLength));kc(g)});return g},
X:a=>{var b=U(a),c=ub[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete ub[a];b.unmap()}},a:a=>{delete tb[a]},g:(a,b,c)=>{var d=!!A[b+32>>2];b={label:V(b+4),usage:A[b+16>>2],size:4294967296*A[b+4+24>>2]+A[b+24>>2],mappedAtCreation:d};a=U(a);try{var f=a.createBuffer(b)}catch(g){return!1}S(c,f);d&&(ub[c]=[]);return!0},U:(a,b,c)=>{var d=A[b>>2],f=A[d+4>>2];b={label:V(b+4),code:""};switch(f){case 2:b.code=vb(d+8)}S(c,U(a).createShaderModule(b))},W:a=>{a=U(a);a.onuncapturederror=null;a.destroy()},S:()=>
{var a=navigator.gpu.getPreferredCanvasFormat();return ic[a]},T:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(c){var f={featureLevel:Sb[A[c+4>>2]],powerPreference:Xb[A[c+8>>2]],forceFallbackAdapter:!!A[c+12>>2]};a=A[c>>2];0!==a&&(f.vc=!!A[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(f).then(g=>{if(g)S(d,g),Gc(b,1,d,0);else{g=X();var k=R("WebGPU not available on this browser (requestAdapter returned null)");Gc(b,3,d,k);Y(g)}},g=>{var k=X();g=R(g.message);Gc(b,
4,d,g);Y(k)}):(f=X(),a=R("WebGPU not available on this browser (navigator.gpu is not available)"),Gc(b,3,d,a),Y(f))},M:Fa,Ea:function(){e.Qb=a=>{0!=mc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Qb)},xa:function(){e.Vb=a=>{const b=a.clipboardData.getData("text");jc(()=>{const c=R(b);lc(c)})};window.addEventListener("paste",e.Vb)},ua:function(){e.pc=[];e.Rb=b=>{b.stopPropagation();b.preventDefault()};e.Sb=b=>{b.stopPropagation();b.preventDefault()};e.Tb=b=>{b.stopPropagation();
b.preventDefault()};e.Ub=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.qc=c;nc(c.length);for(let f=0;f<c.length;f++)jc(()=>{const g=R(c[f].name);oc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);pc(b.clientX,b.clientY,d)};const a=e.kb;a.addEventListener("dragenter",e.Rb,!1);a.addEventListener("dragleave",e.Sb,!1);a.addEventListener("dragover",e.Tb,!1);a.addEventListener("drop",e.Ub,!1)},Ca:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},L:function(a){e.Ab&&(URL.revokeObjectURL(e.Ab[a].Zb),e.Ab[a]=null)},fa:function(a,b){0!==b&&(document.title=b?K(b):"");a=a?K(a):"";void 0!==e.canvas&&("object"===typeof e.canvas?cb[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));e.kb=L(a);e.kb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.kb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Da:function(){window.removeEventListener("beforeunload",
e.Qb)},va:function(){window.removeEventListener("paste",e.Vb)},oa:function(){const a=e.kb;a.removeEventListener("dragenter",e.Rb);a.removeEventListener("dragleave",e.Sb);a.removeEventListener("dragover",e.Tb);a.removeEventListener("drop",e.Ub)},h:function(){e.kb&&e.kb.requestPointerLock&&e.kb.requestPointerLock()},R:function(a,b,c){if(e.kb){if(0===b)a="none";else if(0!=c)a=e.Ab[a].ac;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}e.kb.style.cursor=a}},Ba:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(y.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},K:function(a,b){b=b?K(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},e:(a,b)=>U(a).features.has(Tb[b]),ja:(a,b)=>{var c;b&&(c={label:V(b+4),timestampWrites:yb(A[b+12>>2])});a=U(a);b=wc(0);S(b,a.beginComputePass(c));return b},ia:(a,b)=>{var c=A[b>>2],d=void 0;0!==c&&(d=4294967296*A[c+12>>2]+A[c+8>>2]);c=V(b+4);for(var f=A[b+12>>2],g=A[b+16>>2],k=[],m=0;m<f;++m){var p=k,u=
p.push;var v=g+56*m;var l=A[v+4>>2];if(0!==l){var q=z[v+8>>2];-1==q&&(q=void 0);v={view:U(l),depthSlice:q,resolveTarget:U(A[v+12>>2]),clearValue:wb(v+24),loadOp:Vb[A[v+16>>2]],storeOp:ac[A[v+20>>2]]}}else v=void 0;u.call(p,v)}f=A[b+20>>2];f=0!==f?{view:U(A[f+4>>2]),depthClearValue:B[f+16>>2],depthLoadOp:Vb[A[f+8>>2]],depthStoreOp:ac[A[f+12>>2]],depthReadOnly:!!A[f+20>>2],stencilClearValue:A[f+32>>2],stencilLoadOp:Vb[A[f+24>>2]],stencilStoreOp:ac[A[f+28>>2]],stencilReadOnly:!!A[f+36>>2]}:void 0;b=
{label:c,colorAttachments:k,depthStencilAttachment:f,occlusionQuerySet:U(A[b+24>>2]),timestampWrites:yb(A[b+28>>2]),maxDrawCount:d};a=U(a);d=zc(0);S(d,a.beginRenderPass(b));return d},_:a=>{a=U(a);var b=uc(0);S(b,a.finish());return b},$:a=>{U(a).end()},c:(a,b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ha:(a,b)=>{U(a).setPipeline(U(b))},i:(a,b)=>{var c=V(b+4),d=U(A[b+12>>2]),f=A[b+16>>2];b=A[b+20>>2];for(var g=[],k=0;k<f;++k){var m=g,p=m.push;var u=b+40*k;var v=A[u+
8>>2],l=A[u+32>>2],q=A[u+36>>2],w=A[u+4>>2];v?(l=u+24,l=A[l>>2]+4294967296*z[l+4>>2],-1==l&&(l=void 0),u={binding:w,resource:{buffer:U(v),offset:4294967296*A[u+4+16>>2]+A[u+16>>2],size:l}}):u=l?{binding:w,resource:U(l)}:{binding:w,resource:U(q)};p.call(m,u)}c={label:c,layout:d,entries:g};a=U(a);d=rc(0);S(d,a.createBindGroup(c));return d},j:(a,b)=>{var c=V(b+4),d=A[b+12>>2];b=A[b+16>>2];for(var f=[],g=0;g<d;++g){var k=f,m=k.push,p=b+88*g,u=A[p+4>>2],v=A[p+8>>2];var l=p+24;var q=A[l+4>>2];l=q?{type:Qb[q],
hasDynamicOffset:!!A[l+8>>2],minBindingSize:4294967296*A[l+4+16>>2]+A[l+16>>2]}:void 0;q=(q=A[p+48+4>>2])?{type:Zb[q]}:void 0;var w=p+56;var x=A[w+4>>2];w=x?{sampleType:dc[x],viewDimension:ec[A[w+8>>2]],multisampled:!!A[w+12>>2]}:void 0;p+=72;p=(x=A[p+4>>2])?{access:$b[x],format:W[A[p+8>>2]],viewDimension:ec[A[p+12>>2]]}:void 0;m.call(k,{binding:u,visibility:v,buffer:l,sampler:q,texture:w,storageTexture:p})}c={label:c,entries:f};a=U(a);d=tc(0);S(d,a.createBindGroupLayout(c));return d},o:(a,b)=>{var c;
b&&(c={label:V(b+4)});a=U(a);b=vc(0);S(b,a.createCommandEncoder(c));return b},la:(a,b)=>{var c=V(b+4);var d=Ab(A[b+12>>2]);b=(b+=16)?{module:U(A[b+4>>2]),constants:zb(A[b+16>>2],A[b+20>>2]),entryPoint:V(b+8)}:void 0;c={label:c,layout:d,compute:b};a=U(a);d=xc(0);S(d,a.createComputePipeline(c));return d},ma:(a,b)=>{for(var c=A[b+12>>2],d=A[b+16>>2],f=[],g=0;g<c;++g)f.push(U(A[d+4*g>>2]));b={label:V(b+4),bindGroupLayouts:f};a=U(a);c=yc(0);S(c,a.createPipelineLayout(b));return c},ka:(a,b)=>{b=Nb(b);a=
U(a);var c=Ac(0);S(c,a.createRenderPipeline(b));return c},na:(a,b)=>{var c;b&&(c={label:V(b+4),addressModeU:Pb[A[b+12>>2]],addressModeV:Pb[A[b+16>>2]],addressModeW:Pb[A[b+20>>2]],magFilter:Ub[A[b+24>>2]],minFilter:Ub[A[b+28>>2]],mipmapFilter:Wb[A[b+32>>2]],lodMinClamp:B[b+36>>2],lodMaxClamp:B[b+40>>2],compare:Db[A[b+44>>2]],maxAnisotropy:pa[b+48>>1]});a=U(a);b=Bc(0);S(b,a.createSampler(c));return b},k:(a,b)=>{var c={label:V(b+4),size:xb(b+28),mipLevelCount:A[b+44>>2],sampleCount:A[b+48>>2],dimension:cc[A[b+
24>>2]],format:W[A[b+40>>2]],usage:A[b+16>>2]},d=A[b+52>>2];d&&(b=A[b+56>>2],c.viewFormats=Array.from(z.subarray(b>>2,b+4*d>>2),f=>W[f]));a=U(a);d=Dc(0);S(d,a.createTexture(c));return d},qa:(a,b)=>{Ob(U(a).limits,b);return 1},d:(a,b)=>U(a).features.has(Tb[b]),ya:(a,b)=>{a=L(A[A[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;a.rc=V(b+4);b=Cc(0);S(b,a);return b},Z:(a,b,c)=>{a=U(a);b=Array.from(z.subarray(c>>2,c+4*b>>2),d=>U(d));a.submit(b)},l:function(a,b,c,d,f){c=-9007199254740992>c||9007199254740992<
c?NaN:Number(c);U(a).writeBuffer(U(b),c,y.subarray(d,d+f),0,f)},pa:(a,b,c,d,f,g)=>{var k=A[f+8>>2],m=A[f+12>>2],p=b+8;U(a).writeTexture({texture:U(A[b>>2]),mipLevel:A[b+4>>2],origin:{x:A[p>>2],y:A[p+4>>2],z:A[p+8>>2]},aspect:bc[A[b+20>>2]]},y.subarray(c,c+d),{offset:4294967296*A[f+4>>2]+A[f>>2],bytesPerRow:4294967295===k?void 0:k,rowsPerImage:4294967295===m?void 0:m},xb(g))},m:(a,b,c,d,f)=>{U(a).draw(b,c,d>>>0,f>>>0)},n:(a,b,c,d,f,g)=>{U(a).drawIndexed(b,c,d>>>0,f,g>>>0)},aa:a=>{U(a).end()},b:(a,
b,c,d,f)=>{a=U(a);c=U(c);0==d?a.setBindGroup(b,c):a.setBindGroup(b,c,A,f>>2,d)},ea:(a,b)=>{U(a).setBlendConstant(wb(b))},ca:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);a=U(a);b=U(b);-1==f&&(f=void 0);a.setIndexBuffer(b,Kb[c],d,f)},ga:(a,b)=>{U(a).setPipeline(U(b))},da:(a,b)=>{U(a).setStencilReference(b>>>0)},ba:function(a,b,c,d,f){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);f=-9007199254740992>f||9007199254740992<
f?NaN:Number(f);a=U(a);c=U(c);-1==f&&(f=void 0);a.setVertexBuffer(b,c,d,f)},wa:(a,b)=>{var c=A[b+4>>2];a=U(a);var d=[A[b+24>>2],A[b+28>>2]];0!==d[0]&&(a.canvas.width=d[0]);0!==d[1]&&(a.canvas.height=d[1]);c={device:U(c),format:W[A[b+8>>2]],usage:A[b+16>>2],alphaMode:Rb[A[b+40>>2]]};if(d=A[b+32>>2]){var f=A[b+36>>2];c.viewFormats=Array.from(z.subarray(f>>2,f+4*d>>2),g=>W[g])}b=A[b>>2];0!==b&&(c.colorSpace=Yb[A[b+8>>2]],c.tc={mode:fc[A[b+12>>2]]});a.configure(c)},ra:(a,b)=>{a=U(a);try{var c=Dc(0);S(c,
a.getCurrentTexture());A[b+4>>2]=c;z[b+8>>2]=1}catch(d){A[b+4>>2]=0,z[b+8>>2]=6}},f:(a,b)=>{if(b){var c=A[b+24>>2];var d=A[b+32>>2];c={label:V(b+4),format:W[A[b+12>>2]],dimension:ec[A[b+16>>2]],baseMipLevel:A[b+20>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:A[b+28>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:bc[A[b+36>>2]]}}a=U(a);b=Ec(0);S(b,a.createView(c));return b}},Z;
(async function(){function a(c){Z=c.exports;na=Z.Fa;ra();fb=Z.tb;c=Z;Q=c.Ha;kc=c.Ia;e.__sapp_emsc_onpaste=lc=c.Ja;e.__sapp_html5_get_ask_leave_site=mc=c.Ka;e.__sapp_emsc_begin_drop=nc=c.La;e.__sapp_emsc_drop=oc=c.Ma;e.__sapp_emsc_end_drop=pc=c.Na;e.__sapp_emsc_invoke_fetch_cb=c.Oa;e._main=qc=c.Pa;e.__saudio_emsc_pull=c.Qa;e.__sfetch_emsc_head_response=c.Ra;e.__sfetch_emsc_get_response=c.Sa;e.__sfetch_emsc_failed_http_status=c.Ta;e.__sfetch_emsc_failed_buffer_too_small=c.Ua;e.__sfetch_emsc_failed_other=
c.Va;rc=c.Wa;tc=c.Xa;uc=c.Ya;vc=c.Za;wc=c._a;xc=c.$a;yc=c.ab;zc=c.eb;Ac=c.fb;Bc=c.gb;Cc=c.hb;Dc=c.ib;Ec=c.jb;Fc=c.pb;Gc=c.qb;Hc=c.rb;Ic=c.sb;Jc=c.ub;Kc=c.vb;Y=c.wb;sb=c.xb;X=c.yb;D--;e.monitorRunDependencies?.(D);0==D&&E&&(c=E,E=null,c());return Z}D++;e.monitorRunDependencies?.(D);var b={a:Lc};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ta??=e.locateFile?e.locateFile("vertexindexbuffer-sapp.wasm",ia):ia+"vertexindexbuffer-sapp.wasm";return a((await wa(b)).instance)})();
function Mc(a=[]){var b=qc;a.unshift(ea);var c=a.length,d=sb(4*(c+1)),f=d;a.forEach(k=>{A[f>>2]=R(k);f+=4});A[f>>2]=0;try{var g=b(c,d);Ga(g)}catch(k){Ea(k)}}
function Nc(a=da){function b(){e.calledRun=!0;if(!r){Z.Ga();e.onRuntimeInitialized?.();e.noInitialRun||Mc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();za.push(c)}ya(za)}}if(0<D)E=Nc;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ba();ya(Aa);0<D?E=Nc:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Nc();
